import 'accounting_models.dart';

class AccountingMockData {
  // 1. Customer-Wise Financial Summaries
  static final List<CustomerFinancialSummary> customerSummaries = [
    const CustomerFinancialSummary(
      clientId: 'CL-101',
      clientName: 'Rajeev Singhania',
      clientPhone: '+91 98101 22910',
      projectTitle: 'DLF Magnolias #402, Gurugram',
      contractModel: 'Fixed Consulting',
      totalContractValue: 4850000,
      materialPaid: 1680000,
      materialUnpaid: 240000,
      labourPaid: 840000,
      labourUnpaid: 120000,
      feesPaid: 450000,
      feesUnpaid: 75000,
      totalBillsCount: 38,
      health: FinancialHealth.warning,
      completionPercent: 68.0,
    ),
    const CustomerFinancialSummary(
      clientId: 'CL-102',
      clientName: 'Kavita Chawla',
      clientPhone: '+91 99204 88319',
      projectTitle: 'Trump Towers #2104, Gurugram',
      contractModel: 'Percentage of Cost (12%)',
      totalContractValue: 6200000,
      materialPaid: 2150000,
      materialUnpaid: 0,
      labourPaid: 920000,
      labourUnpaid: 45000,
      feesPaid: 368000,
      feesUnpaid: 0,
      totalBillsCount: 46,
      health: FinancialHealth.healthy,
      completionPercent: 54.0,
    ),
    const CustomerFinancialSummary(
      clientId: 'CL-103',
      clientName: 'Dr. Sameer Joshi',
      clientPhone: '+91 98331 44520',
      projectTitle: 'Hiranandani Gardens #9B, Powai',
      contractModel: 'Turnkey Contract Milestone',
      totalContractValue: 3400000,
      materialPaid: 1420000,
      materialUnpaid: 0,
      labourPaid: 610000,
      labourUnpaid: 0,
      feesPaid: 340000,
      feesUnpaid: 0,
      totalBillsCount: 29,
      health: FinancialHealth.healthy,
      completionPercent: 92.0,
    ),
    const CustomerFinancialSummary(
      clientId: 'CL-104',
      clientName: 'Vikramaditya Shroff',
      clientPhone: '+91 98200 11400',
      projectTitle: 'Lodha Altamount #18A, Mumbai',
      contractModel: 'Fixed Consulting',
      totalContractValue: 9200000,
      materialPaid: 3100000,
      materialUnpaid: 850000,
      labourPaid: 1250000,
      labourUnpaid: 320000,
      feesPaid: 650000,
      feesUnpaid: 250000,
      totalBillsCount: 52,
      health: FinancialHealth.critical,
      completionPercent: 42.0,
    ),
  ];

  // 2. Client Expense Ledger Transactions with Commission Tracking
  static final List<LedgerTransaction> transactions = [
    LedgerTransaction(
      id: 'TXN-901',
      voucherNo: 'VCH-2026-0811',
      date: DateTime.now().subtract(const Duration(days: 1)),
      clientName: 'Rajeev Singhania',
      projectTitle: 'DLF Magnolias #402',
      category: LedgerCategory.material,
      payeeOrVendor: 'Century Wholesale Hub, DLF Phase 2',
      amount: 128250,
      paymentStatus: TransactionPaymentStatus.paid,
      commissionRatePercent: 6.5,
      commissionEarned: 8336.25,
      remarks: 'BWP Marine Ply 19mm (45 Sheets) for Master Wardrobe Carcass',
      voucherFileRef: 'INV-CEN-8821.pdf',
    ),
    LedgerTransaction(
      id: 'TXN-902',
      voucherNo: 'VCH-2026-0812',
      date: DateTime.now().subtract(const Duration(days: 3)),
      clientName: 'Rajeev Singhania',
      projectTitle: 'DLF Magnolias #402',
      category: LedgerCategory.labour,
      payeeOrVendor: 'Master Carpenter Nooruddin & Team',
      amount: 48000,
      paymentStatus: TransactionPaymentStatus.paid,
      commissionRatePercent: 5.0,
      commissionEarned: 2400.0,
      remarks: 'Weekly carpentry labour milestone: Wardrobe carcass assembly',
      voucherFileRef: 'LAB-MUSTER-W35.pdf',
    ),
    LedgerTransaction(
      id: 'TXN-903',
      voucherNo: 'VCH-2026-0813',
      date: DateTime.now().subtract(const Duration(days: 5)),
      clientName: 'Vikramaditya Shroff',
      projectTitle: 'Lodha Altamount #18A',
      category: LedgerCategory.material,
      payeeOrVendor: 'Classic Marble Company, Silvassa Depot',
      amount: 540000,
      paymentStatus: TransactionPaymentStatus.unpaid,
      commissionRatePercent: 8.0,
      commissionEarned: 43200.0,
      remarks: 'Imported Statuario Marble Slabs (1,200 Sqft) - Client payment pending',
      voucherFileRef: 'INV-CMC-712.pdf',
    ),
    LedgerTransaction(
      id: 'TXN-904',
      voucherNo: 'VCH-2026-0814',
      date: DateTime.now().subtract(const Duration(days: 6)),
      clientName: 'Kavita Chawla',
      projectTitle: 'Trump Towers #2104',
      category: LedgerCategory.material,
      payeeOrVendor: 'Hafele Direct Corporate Channel',
      amount: 100800,
      paymentStatus: TransactionPaymentStatus.paid,
      commissionRatePercent: 7.0,
      commissionEarned: 7056.0,
      remarks: 'Tandembox drawer runners & pantry pull-outs',
      voucherFileRef: 'INV-HAF-2104.pdf',
    ),
    LedgerTransaction(
      id: 'TXN-905',
      voucherNo: 'VCH-2026-0815',
      date: DateTime.now().subtract(const Duration(days: 8)),
      clientName: 'Rajeev Singhania',
      projectTitle: 'DLF Magnolias #402',
      category: LedgerCategory.supervisionFee,
      payeeOrVendor: 'Homio Interior Solutions Pvt Ltd',
      amount: 35000,
      paymentStatus: TransactionPaymentStatus.partial,
      commissionRatePercent: 100.0,
      commissionEarned: 35000.0,
      remarks: 'Saturday weekly site supervision fee (Week 35)',
      voucherFileRef: 'FEE-SAT-W35.pdf',
    ),
    LedgerTransaction(
      id: 'TXN-906',
      voucherNo: 'VCH-2026-0816',
      date: DateTime.now().subtract(const Duration(days: 10)),
      clientName: 'Dr. Sameer Joshi',
      projectTitle: 'Hiranandani Gardens #9B',
      category: LedgerCategory.material,
      payeeOrVendor: 'Asian Paints Wholesale Depot',
      amount: 49600,
      paymentStatus: TransactionPaymentStatus.paid,
      commissionRatePercent: 5.5,
      commissionEarned: 2728.0,
      remarks: 'Royale Glitz Ultra-Sheen paint drums',
      voucherFileRef: 'INV-AP-8819.pdf',
    ),
  ];

  // 3. Multi-Stakeholder Overdue Alerts
  static final List<OverdueAlert> overdueAlerts = [
    OverdueAlert(
      id: 'OVD-01',
      clientName: 'Vikramaditya Shroff',
      clientPhone: '+91 98200 11400',
      projectTitle: 'Lodha Altamount #18A',
      overdueDays: 18,
      dueAmount: 850000,
      supervisorName: 'Suresh Patil',
      siteHaltStatus: SiteHaltStatus.halted,
      escalationLevel: EscalationLevel.level2SupervisorHalt,
      lastAlertSent: DateTime.now().subtract(const Duration(hours: 4)),
      notes: 'Site work on Italian Marble installation HALTED by supervisor until marble invoice is cleared.',
    ),
    OverdueAlert(
      id: 'OVD-02',
      clientName: 'Rajeev Singhania',
      clientPhone: '+91 98101 22910',
      projectTitle: 'DLF Magnolias #402',
      overdueDays: 9,
      dueAmount: 240000,
      supervisorName: 'Rajesh Verma',
      siteHaltStatus: SiteHaltStatus.active,
      escalationLevel: EscalationLevel.level1ClientReminder,
      lastAlertSent: DateTime.now().subtract(const Duration(hours: 18)),
      notes: 'Plywood supplier invoice due. Level 1 automated WhatsApp reminder sent to client.',
    ),
    OverdueAlert(
      id: 'OVD-03',
      clientName: 'Kavita Chawla',
      clientPhone: '+91 99204 88319',
      projectTitle: 'Trump Towers #2104',
      overdueDays: 4,
      dueAmount: 45000,
      supervisorName: 'Amitabh Sharma',
      siteHaltStatus: SiteHaltStatus.active,
      escalationLevel: EscalationLevel.level1ClientReminder,
      lastAlertSent: DateTime.now().subtract(const Duration(days: 1)),
      notes: 'Minor MEP labour adjustment due. Gentle reminder dispatched.',
    ),
  ];
}
