// Homio CRM — Realistic Enterprise Mock Dataset for Accounting & Finance Module

import 'accounting_models.dart';

class AccountingMockData {
  // ===========================================================================
  // 1. LEGACY DATASETS (Preserved for existing components)
  // ===========================================================================
  static final List<CustomerFinancialSummary> customerSummaries = [
    const CustomerFinancialSummary(
      clientId: 'CL-101',
      clientName: 'Rajeev Singhania',
      clientPhone: '+91 98101 22910',
      projectTitle: 'DLF Magnolias #402, Gurugram',
      contractModel: 'Fixed Consulting',
      totalContractValue: 4850000,
      materialPaid: 1680000,
      materialUnpaid: 240000,
      labourPaid: 840000,
      labourUnpaid: 120000,
      feesPaid: 450000,
      feesUnpaid: 75000,
      totalBillsCount: 38,
      health: FinancialHealth.warning,
      completionPercent: 68.0,
    ),
    const CustomerFinancialSummary(
      clientId: 'CL-102',
      clientName: 'Kavita Chawla',
      clientPhone: '+91 99204 88319',
      projectTitle: 'Trump Towers #2104, Gurugram',
      contractModel: 'Percentage of Cost (12%)',
      totalContractValue: 6200000,
      materialPaid: 2150000,
      materialUnpaid: 0,
      labourPaid: 920000,
      labourUnpaid: 45000,
      feesPaid: 368000,
      feesUnpaid: 0,
      totalBillsCount: 46,
      health: FinancialHealth.healthy,
      completionPercent: 54.0,
    ),
    const CustomerFinancialSummary(
      clientId: 'CL-103',
      clientName: 'Dr. Sameer Joshi',
      clientPhone: '+91 98331 44520',
      projectTitle: 'Hiranandani Gardens #9B, Powai',
      contractModel: 'Turnkey Contract Milestone',
      totalContractValue: 3400000,
      materialPaid: 1420000,
      materialUnpaid: 0,
      labourPaid: 610000,
      labourUnpaid: 0,
      feesPaid: 340000,
      feesUnpaid: 0,
      totalBillsCount: 29,
      health: FinancialHealth.healthy,
      completionPercent: 92.0,
    ),
    const CustomerFinancialSummary(
      clientId: 'CL-104',
      clientName: 'Vikramaditya Shroff',
      clientPhone: '+91 98200 11400',
      projectTitle: 'Lodha Altamount #18A, Mumbai',
      contractModel: 'Fixed Consulting',
      totalContractValue: 9200000,
      materialPaid: 3100000,
      materialUnpaid: 850000,
      labourPaid: 1250000,
      labourUnpaid: 320000,
      feesPaid: 650000,
      feesUnpaid: 250000,
      totalBillsCount: 52,
      health: FinancialHealth.critical,
      completionPercent: 42.0,
    ),
  ];

  static final List<LedgerTransaction> transactions = [
    LedgerTransaction(
      id: 'TXN-901',
      voucherNo: 'VCH-2026-0811',
      date: DateTime.now().subtract(const Duration(days: 1)),
      clientName: 'Rajeev Singhania',
      projectTitle: 'DLF Magnolias #402',
      category: LedgerCategory.material,
      payeeOrVendor: 'Century Wholesale Hub, DLF Phase 2',
      amount: 128250,
      paymentStatus: TransactionPaymentStatus.paid,
      commissionRatePercent: 6.5,
      commissionEarned: 8336.25,
      remarks: 'BWP Marine Ply 19mm (45 Sheets) for Master Wardrobe Carcass',
      voucherFileRef: 'INV-CEN-8821.pdf',
    ),
    LedgerTransaction(
      id: 'TXN-902',
      voucherNo: 'VCH-2026-0812',
      date: DateTime.now().subtract(const Duration(days: 3)),
      clientName: 'Rajeev Singhania',
      projectTitle: 'DLF Magnolias #402',
      category: LedgerCategory.labour,
      payeeOrVendor: 'Master Carpenter Nooruddin & Team',
      amount: 45000,
      paymentStatus: TransactionPaymentStatus.paid,
      commissionRatePercent: 5.0,
      commissionEarned: 2250.0,
      remarks: 'Running feet kitchen modular fitting milestone 2',
      voucherFileRef: 'LB-PAY-104.pdf',
    ),
    LedgerTransaction(
      id: 'TXN-903',
      voucherNo: 'VCH-2026-0813',
      date: DateTime.now().subtract(const Duration(days: 7)),
      clientName: 'Vikramaditya Shroff',
      projectTitle: 'Lodha Altamount #18A',
      category: LedgerCategory.supervisionFee,
      payeeOrVendor: 'Homio PMC Services Private Limited',
      amount: 125000,
      paymentStatus: TransactionPaymentStatus.unpaid,
      commissionRatePercent: 0.0,
      commissionEarned: 0.0,
      remarks: 'Weekly Supervision & Quality Audit fee for Milestone 3',
      voucherFileRef: null,
    ),
  ];

  static final List<OverdueAlert> overdueAlerts = [
    OverdueAlert(
      id: 'OVD-01',
      clientName: 'Vikramaditya Shroff',
      clientPhone: '+91 98200 11400',
      projectTitle: 'Lodha Altamount #18A, Mumbai',
      overdueDays: 19,
      dueAmount: 850000,
      supervisorName: 'Karan Mehra',
      siteHaltStatus: SiteHaltStatus.active,
      escalationLevel: EscalationLevel.level2SupervisorHalt,
      lastAlertSent: DateTime.now().subtract(const Duration(days: 2)),
      notes: 'Customer promised RTGS post board meeting on 12th Sep.',
    ),
    OverdueAlert(
      id: 'OVD-02',
      clientName: 'Rajeev Singhania',
      clientPhone: '+91 98101 22910',
      projectTitle: 'DLF Magnolias #402, Gurugram',
      overdueDays: 8,
      dueAmount: 240000,
      supervisorName: 'Amit Verma',
      siteHaltStatus: SiteHaltStatus.active,
      escalationLevel: EscalationLevel.level1ClientReminder,
      lastAlertSent: DateTime.now().subtract(const Duration(days: 1)),
      notes: 'WhatsApp payment link sent with HDFC Virtual Account.',
    ),
  ];

  // ===========================================================================
  // 2. NEW PRD FINANCIAL DATASETS
  // ===========================================================================

  /// Customer Ledgers with 4-way segregation
  static final List<CustomerLedgerDetailModel> customerLedgers = [
    CustomerLedgerDetailModel(
      customerId: 'CUST-001',
      customerName: 'Rahul Sharma',
      customerPhone: '+91 98100 45210',
      customerEmail: 'rahul.sharma@dlf.in',
      billingAddress: 'Villa 1402, The Camellias, DLF Phase 5, Gurugram, Haryana - 122009',
      activeProjectName: 'The Camellias Villa Interior #1402',
      projectId: 'PRJ-CAM-101',
      projectManager: 'Amit Kumar',
      contractModel: 'Turnkey Luxury Interior',
      totalContractValue: 4800000,
      totalInvoiced: 3650000,
      totalCollected: 2820000,
      materialPaid: 1450000,
      materialUnpaid: 220000,
      labourPaid: 720000,
      labourUnpaid: 110000,
      consultingPaid: 350000,
      consultingUnpaid: 50000,
      supervisionPaid: 300000,
      supervisionUnpaid: 50000,
      totalOutstanding: 830000,
      overdueAmount: 320000,
      lastPaymentDate: DateTime.now().subtract(const Duration(days: 4)),
      accountStatus: FinancialHealth.warning,
      transactions: [
        LedgerTransactionItem(
          id: 'TXN-001',
          transactionId: 'TXN-2026-081',
          date: DateTime.now().subtract(const Duration(days: 28)),
          type: 'Invoice',
          reference: 'INV-2026-1021',
          projectName: 'The Camellias Villa Interior #1402',
          description: 'Milestone 1 Mobilization & Structural Carpentry Advance',
          debit: 1500000,
          credit: 0,
          balance: 1500000,
          status: 'Cleared',
        ),
        LedgerTransactionItem(
          id: 'TXN-002',
          transactionId: 'PAY-2026-042',
          date: DateTime.now().subtract(const Duration(days: 26)),
          type: 'Payment',
          reference: 'HDFC-NEFT-99210',
          projectName: 'The Camellias Villa Interior #1402',
          description: 'Received Mobilization Advance via Bank Transfer',
          debit: 0,
          credit: 1500000,
          balance: 0,
          status: 'Reconciled',
        ),
        LedgerTransactionItem(
          id: 'TXN-003',
          transactionId: 'TXN-2026-094',
          date: DateTime.now().subtract(const Duration(days: 14)),
          type: 'Invoice',
          reference: 'INV-2026-1024',
          projectName: 'The Camellias Villa Interior #1402',
          description: 'Milestone 2 Modular Woodwork & False Ceiling Invoicing',
          debit: 2150000,
          credit: 0,
          balance: 2150000,
          status: 'Partially Paid',
        ),
        LedgerTransactionItem(
          id: 'TXN-004',
          transactionId: 'PAY-2026-088',
          date: DateTime.now().subtract(const Duration(days: 4)),
          type: 'Payment',
          reference: 'HDFC-RTGS-33109',
          projectName: 'The Camellias Villa Interior #1402',
          description: 'Part Payment for Milestone 2 Woodwork',
          debit: 0,
          credit: 1320000,
          balance: 830000,
          status: 'Reconciled',
        ),
      ],
    ),
    CustomerLedgerDetailModel(
      customerId: 'CUST-002',
      customerName: 'Pooja Mehta',
      customerPhone: '+91 98201 77412',
      customerEmail: 'pooja.mehta@oberoigroup.com',
      billingAddress: 'Tower B, Flat 801, Oberoi Sky City, Borivali East, Mumbai - 400066',
      activeProjectName: 'Oberoi Sky City Penthouse #801',
      projectId: 'PRJ-OBR-202',
      projectManager: 'Karan Mehra',
      contractModel: 'Cost Plus Percentage (15%)',
      totalContractValue: 3800000,
      totalInvoiced: 2900000,
      totalCollected: 2650000,
      materialPaid: 1350000,
      materialUnpaid: 50000,
      labourPaid: 650000,
      labourUnpaid: 40000,
      consultingPaid: 350000,
      consultingUnpaid: 60000,
      supervisionPaid: 300000,
      supervisionUnpaid: 100000,
      totalOutstanding: 250000,
      overdueAmount: 0,
      lastPaymentDate: DateTime.now().subtract(const Duration(days: 2)),
      accountStatus: FinancialHealth.healthy,
      transactions: [
        LedgerTransactionItem(
          id: 'TXN-101',
          transactionId: 'TXN-2026-089',
          date: DateTime.now().subtract(const Duration(days: 20)),
          type: 'Invoice',
          reference: 'INV-2026-1019',
          projectName: 'Oberoi Sky City Penthouse #801',
          description: 'Acoustic Wall Panelling & Veneer Application',
          debit: 2900000,
          credit: 0,
          balance: 2900000,
          status: 'Partially Paid',
        ),
        LedgerTransactionItem(
          id: 'TXN-102',
          transactionId: 'PAY-2026-079',
          date: DateTime.now().subtract(const Duration(days: 2)),
          type: 'Payment',
          reference: 'ICICI-UPI-8812',
          projectName: 'Oberoi Sky City Penthouse #801',
          description: 'RTGS Transfer from Axis Bank Account',
          debit: 0,
          credit: 2650000,
          balance: 250000,
          status: 'Reconciled',
        ),
      ],
    ),
    CustomerLedgerDetailModel(
      customerId: 'CUST-003',
      customerName: 'Anand Mahindra',
      customerPhone: '+91 99000 11223',
      customerEmail: 'anand.m@prestige.com',
      billingAddress: 'Prestige Falcon City, Tower 5, Kanakapura Road, Bengaluru - 560062',
      activeProjectName: 'Prestige Falcon City 4BHK #504',
      projectId: 'PRJ-PFC-303',
      projectManager: 'Deepak Rao',
      contractModel: 'Turnkey Contract Milestone',
      totalContractValue: 2800000,
      totalInvoiced: 2100000,
      totalCollected: 1650000,
      materialPaid: 850000,
      materialUnpaid: 150000,
      labourPaid: 450000,
      labourUnpaid: 120000,
      consultingPaid: 200000,
      consultingUnpaid: 80000,
      supervisionPaid: 150000,
      supervisionUnpaid: 100000,
      totalOutstanding: 450000,
      overdueAmount: 180000,
      lastPaymentDate: DateTime.now().subtract(const Duration(days: 9)),
      accountStatus: FinancialHealth.warning,
      transactions: [],
    ),
  ];

  /// Comprehensive Invoice Registry
  static final List<Invoice> invoices = [
    Invoice(
      id: 'INV-001',
      invoiceNumber: 'INV-2026-1024',
      invoiceDate: DateTime.now().subtract(const Duration(days: 14)),
      dueDate: DateTime.now().subtract(const Duration(days: 1)),
      invoiceType: 'Tax Invoice',
      customerId: 'CUST-001',
      customerName: 'Rahul Sharma',
      customerPhone: '+91 98100 45210',
      customerEmail: 'rahul.sharma@dlf.in',
      billingAddress: 'Villa 1402, The Camellias, DLF Phase 5, Gurugram, Haryana',
      siteAddress: 'The Camellias, DLF Phase 5, Gurugram, Haryana',
      customerGstin: '06AABCU9603R1ZM',
      customerPan: 'AABCU9603R',
      projectId: 'PRJ-CAM-101',
      projectName: 'The Camellias Villa Interior #1402',
      referenceQuotationNo: 'QT-2026-081',
      referenceBookingNo: 'BKG-DLF-01',
      paymentTerms: '50% Advance, Balance on Milestone Completion',
      subtotal: 1822034,
      discount: 0,
      taxableAmount: 1822034,
      taxAmount: 327966, // 18% GST
      additionalCharges: 0,
      roundOff: 0,
      grandTotal: 2150000,
      paidAmount: 1320000,
      status: InvoiceStatus.overdue,
      paymentLink: 'https://pay.homio.in/inv/INV-2026-1024',
      createdBy: 'Finance Manager (Kavita Roy)',
      items: const [
        InvoiceLineItem(
          id: 'ITEM-01',
          itemName: 'Century Club Prime Marine Plywood 19mm Panelling',
          itemCode: 'MAT-PLY-710',
          description: 'Modular living room carcass and master bedroom framing',
          category: 'Woodwork',
          quantity: 48,
          unit: 'Piece/Nos',
          rate: 3450,
          discount: 0,
          taxPercent: 18,
          roomArea: 'Living Room',
          stageOrMilestone: 'Milestone 2',
        ),
        InvoiceLineItem(
          id: 'ITEM-02',
          itemName: 'Architectural Veneer Application & PU Polish',
          itemCode: 'FIN-VEN-04',
          description: 'Natural smoked oak veneer pressed with 0.8mm edge banding',
          category: 'Finishes',
          quantity: 380,
          unit: 'Sq.Ft.',
          rate: 450,
          discount: 0,
          taxPercent: 18,
          roomArea: 'Master Bedroom',
          stageOrMilestone: 'Milestone 2',
        ),
        InvoiceLineItem(
          id: 'ITEM-03',
          itemName: 'Modular Kitchen Blum Soft-Close Drawer Systems',
          itemCode: 'HDW-BLUM-01',
          description: 'Blum Legrabox pure silk white tandembox fittings',
          category: 'Hardware',
          quantity: 12,
          unit: 'Piece/Nos',
          rate: 6800,
          discount: 0,
          taxPercent: 18,
          roomArea: 'Modular Kitchen',
          stageOrMilestone: 'Milestone 2',
        ),
      ],
    ),
    Invoice(
      id: 'INV-002',
      invoiceNumber: 'INV-2026-1019',
      invoiceDate: DateTime.now().subtract(const Duration(days: 20)),
      dueDate: DateTime.now().add(const Duration(days: 5)),
      invoiceType: 'Tax Invoice',
      customerId: 'CUST-002',
      customerName: 'Pooja Mehta',
      customerPhone: '+91 98201 77412',
      customerEmail: 'pooja.mehta@oberoigroup.com',
      billingAddress: 'Tower B, Flat 801, Oberoi Sky City, Borivali East, Mumbai',
      siteAddress: 'Tower B, Flat 801, Oberoi Sky City, Borivali East, Mumbai',
      customerGstin: '27AABCU9603R1ZL',
      projectId: 'PRJ-OBR-202',
      projectName: 'Oberoi Sky City Penthouse #801',
      referenceQuotationNo: 'QT-2026-044',
      paymentTerms: 'Net 15 Days',
      subtotal: 2457627,
      taxableAmount: 2457627,
      taxAmount: 442373,
      grandTotal: 2900000,
      paidAmount: 2650000,
      status: InvoiceStatus.partiallyPaid,
      paymentLink: 'https://pay.homio.in/inv/INV-2026-1019',
      createdBy: 'Finance Manager (Kavita Roy)',
      items: const [
        InvoiceLineItem(
          id: 'ITEM-04',
          itemName: 'Italian Botticino Marble Flooring & Buffing',
          itemCode: 'FLR-MRB-01',
          description: 'Mirror diamond polishing with epoxy grouting',
          category: 'Civil',
          quantity: 850,
          unit: 'Sq.Ft.',
          rate: 850,
          discount: 0,
          taxPercent: 18,
          roomArea: 'Foyer & Living',
          stageOrMilestone: 'Milestone 3',
        ),
      ],
    ),
    Invoice(
      id: 'INV-003',
      invoiceNumber: 'INV-2026-1030',
      invoiceDate: DateTime.now().subtract(const Duration(days: 3)),
      dueDate: DateTime.now().add(const Duration(days: 12)),
      invoiceType: 'Tax Invoice',
      customerId: 'CUST-003',
      customerName: 'Anand Mahindra',
      customerPhone: '+91 99000 11223',
      customerEmail: 'anand.m@prestige.com',
      billingAddress: 'Prestige Falcon City, Tower 5, Bengaluru',
      siteAddress: 'Prestige Falcon City, Tower 5, Bengaluru',
      projectId: 'PRJ-PFC-303',
      projectName: 'Prestige Falcon City 4BHK #504',
      paymentTerms: 'Advance Due on Presentation',
      subtotal: 720339,
      taxableAmount: 720339,
      taxAmount: 129661,
      grandTotal: 850000,
      paidAmount: 0,
      status: InvoiceStatus.issued,
      paymentLink: 'https://pay.homio.in/inv/INV-2026-1030',
      createdBy: 'Finance Manager (Kavita Roy)',
      items: const [
        InvoiceLineItem(
          id: 'ITEM-05',
          itemName: 'False Ceiling Gyproc Board & Cove Lighting Frame',
          itemCode: 'POP-GYP-02',
          description: 'Saint Gobain channel frame with perimeter shadow profile',
          category: 'False Ceiling',
          quantity: 1100,
          unit: 'Sq.Ft.',
          rate: 185,
          discount: 0,
          taxPercent: 18,
          roomArea: 'Entire Flat',
          stageOrMilestone: 'Milestone 1',
        ),
      ],
    ),
    Invoice(
      id: 'INV-004',
      invoiceNumber: 'INV-2026-1002',
      invoiceDate: DateTime.now().subtract(const Duration(days: 45)),
      dueDate: DateTime.now().subtract(const Duration(days: 30)),
      invoiceType: 'Tax Invoice',
      customerId: 'CUST-001',
      customerName: 'Rahul Sharma',
      customerPhone: '+91 98100 45210',
      customerEmail: 'rahul.sharma@dlf.in',
      billingAddress: 'Villa 1402, The Camellias, DLF Phase 5, Gurugram',
      siteAddress: 'The Camellias, DLF Phase 5, Gurugram',
      projectId: 'PRJ-CAM-101',
      projectName: 'The Camellias Villa Interior #1402',
      paymentTerms: 'Advance Mobilization',
      subtotal: 1271186,
      taxableAmount: 1271186,
      taxAmount: 228814,
      grandTotal: 1500000,
      paidAmount: 1500000,
      status: InvoiceStatus.paid,
      paymentLink: null,
      createdBy: 'Finance Manager (Kavita Roy)',
      items: const [
        InvoiceLineItem(
          id: 'ITEM-06',
          itemName: 'Mobilization & 3D Design Approval Advance',
          itemCode: 'FEE-MOB-01',
          description: 'Signoff advance as per master client contract agreement',
          category: 'Consulting',
          quantity: 1,
          unit: 'Lump Sum',
          rate: 1500000,
          discount: 0,
          taxPercent: 18,
          roomArea: 'Overall Site',
          stageOrMilestone: 'Milestone 1',
        ),
      ],
    ),
  ];

  /// Customer Payments Collection History
  static final List<CustomerPaymentRecord> customerPayments = [
    CustomerPaymentRecord(
      id: 'PAY-001',
      paymentId: 'PAY-2026-088',
      paymentDate: DateTime.now().subtract(const Duration(days: 4)),
      customerId: 'CUST-001',
      customerName: 'Rahul Sharma',
      projectId: 'PRJ-CAM-101',
      projectName: 'The Camellias Villa Interior #1402',
      invoiceId: 'INV-001',
      invoiceNumber: 'INV-2026-1024',
      invoiceTotal: 2150000,
      previousPaid: 0,
      currentPayment: 1320000,
      paymentMethod: PaymentMethod.bankTransfer,
      transactionId: 'HDFC-RTGS-33109',
      bankReference: 'HDFCR520260904001920',
      utrNumber: 'HDFCR520260904001920',
      status: PaymentStatus.completed,
      receiptNumber: 'REC-2026-0412',
      payerName: 'Rahul Sharma',
      payerContact: '+91 98100 45210',
      notes: 'Cleared through HDFC Bank Corporate Clearing account.',
      recordedBy: 'Accounts Officer (Suresh N)',
    ),
    CustomerPaymentRecord(
      id: 'PAY-002',
      paymentId: 'PAY-2026-079',
      paymentDate: DateTime.now().subtract(const Duration(days: 2)),
      customerId: 'CUST-002',
      customerName: 'Pooja Mehta',
      projectId: 'PRJ-OBR-202',
      projectName: 'Oberoi Sky City Penthouse #801',
      invoiceId: 'INV-002',
      invoiceNumber: 'INV-2026-1019',
      invoiceTotal: 2900000,
      previousPaid: 0,
      currentPayment: 2650000,
      paymentMethod: PaymentMethod.bankTransfer,
      transactionId: 'AXIS-RTGS-77102',
      bankReference: 'AXISR520260906004812',
      utrNumber: 'AXISR520260906004812',
      status: PaymentStatus.completed,
      receiptNumber: 'REC-2026-0408',
      payerName: 'Pooja Mehta',
      payerContact: '+91 98201 77412',
      notes: 'Direct RTGS received. Retaining ₹2.5L for snag list sign-off.',
      recordedBy: 'Accounts Officer (Suresh N)',
    ),
    CustomerPaymentRecord(
      id: 'PAY-003',
      paymentId: 'PAY-2026-042',
      paymentDate: DateTime.now().subtract(const Duration(days: 26)),
      customerId: 'CUST-001',
      customerName: 'Rahul Sharma',
      projectId: 'PRJ-CAM-101',
      projectName: 'The Camellias Villa Interior #1402',
      invoiceId: 'INV-004',
      invoiceNumber: 'INV-2026-1002',
      invoiceTotal: 1500000,
      previousPaid: 0,
      currentPayment: 1500000,
      paymentMethod: PaymentMethod.bankTransfer,
      transactionId: 'HDFC-NEFT-99210',
      bankReference: 'HDFC00001099210',
      utrNumber: 'HDFC00001099210',
      status: PaymentStatus.completed,
      receiptNumber: 'REC-2026-0388',
      payerName: 'Rahul Sharma',
      payerContact: '+91 98100 45210',
      notes: 'Initial Project Mobilization Advance fully settled.',
      recordedBy: 'Accounts Officer (Suresh N)',
    ),
  ];

  /// Operational Project Expenses
  static final List<ProjectExpense> projectExpenses = [
    ProjectExpense(
      id: 'EXP-001',
      expenseNumber: 'EXP-2026-081',
      expenseDate: DateTime.now().subtract(const Duration(days: 3)),
      expenseType: ExpenseType.material,
      projectId: 'PRJ-CAM-101',
      projectName: 'The Camellias Villa Interior #1402',
      customerId: 'CUST-001',
      customerName: 'Rahul Sharma',
      siteAddress: 'The Camellias, DLF Phase 5, Gurugram',
      department: 'Modular Carpentry',
      costCentre: 'Cost Centre #104 (Gurugram West)',
      description: 'Century Club Prime BWP Marine Plywood 19mm (45 Sheets)',
      supplierOrPayee: 'Century Wholesale Hub, DLF Phase 2',
      supplierCode: 'VND-CEN-01',
      supplierGstin: '06AAACC1209B1Z8',
      invoiceOrBillNo: 'BILL-CEN-9910',
      billDate: DateTime.now().subtract(const Duration(days: 4)),
      subtotal: 155250,
      taxAmount: 27945,
      freightCharges: 3500,
      otherCharges: 0,
      totalAmount: 186695,
      paidAmount: 186695,
      status: ExpenseStatus.paid,
      commissionAmount: 10091,
      remarks: 'Inspected at service gate 3 by Rajesh Verma.',
      createdBy: 'Rajesh Verma (Site Supervisor)',
    ),
    ProjectExpense(
      id: 'EXP-002',
      expenseNumber: 'EXP-2026-082',
      expenseDate: DateTime.now().subtract(const Duration(days: 5)),
      expenseType: ExpenseType.labour,
      projectId: 'PRJ-CAM-101',
      projectName: 'The Camellias Villa Interior #1402',
      customerId: 'CUST-001',
      customerName: 'Rahul Sharma',
      siteAddress: 'The Camellias, DLF Phase 5, Gurugram',
      department: 'Modular Carpentry',
      costCentre: 'Cost Centre #104',
      description: 'Carpentry labor charges for wardrobe carcass assembly',
      supplierOrPayee: 'Nooruddin Carpentry Works',
      supplierCode: 'LAB-NOOR-01',
      invoiceOrBillNo: 'LB-BILL-402',
      billDate: DateTime.now().subtract(const Duration(days: 6)),
      subtotal: 65000,
      taxAmount: 0,
      freightCharges: 0,
      otherCharges: 0,
      totalAmount: 65000,
      paidAmount: 65000,
      status: ExpenseStatus.paid,
      commissionAmount: 3250,
      remarks: 'Verified 100% completion by Amit Kumar (PM).',
      createdBy: 'Rajesh Verma (Site Supervisor)',
    ),
    ProjectExpense(
      id: 'EXP-003',
      expenseNumber: 'EXP-2026-089',
      expenseDate: DateTime.now().subtract(const Duration(days: 1)),
      expenseType: ExpenseType.design,
      projectId: 'PRJ-OBR-202',
      projectName: 'Oberoi Sky City Penthouse #801',
      customerId: 'CUST-002',
      customerName: 'Pooja Mehta',
      siteAddress: 'Oberoi Sky City, Borivali East, Mumbai',
      department: 'Design Studio',
      costCentre: 'Cost Centre #201 (Mumbai North)',
      description: '3D Photorealistic Renderings & VR Walkthrough Set',
      supplierOrPayee: 'Apex CGI & Architectural Visuals',
      invoiceOrBillNo: 'APEX-INV-771',
      billDate: DateTime.now().subtract(const Duration(days: 2)),
      subtotal: 45000,
      taxAmount: 8100,
      freightCharges: 0,
      otherCharges: 0,
      totalAmount: 53100,
      paidAmount: 0,
      status: ExpenseStatus.approved,
      commissionAmount: 0,
      remarks: 'Approved by Sneha Sen (Lead Architect).',
      createdBy: 'Sneha Sen (Design Lead)',
    ),
  ];

  /// Vendor Payments connecting to Procurement POs
  static final List<VendorPaymentRecord> vendorPayments = [
    VendorPaymentRecord(
      id: 'VND-PAY-01',
      paymentId: 'VP-2026-041',
      vendorId: 'VND-001',
      vendorName: 'Century Wholesale Hub',
      vendorCode: 'VND-CEN-01',
      vendorContact: '+91 98111 23456',
      projectId: 'PRJ-CAM-101',
      projectName: 'The Camellias Villa Interior #1402',
      customerName: 'Rahul Sharma',
      poNumber: 'PO-2026-0081',
      rfqNumber: 'RFQ-2026-0041',
      materialRequestNo: 'MR-2026-001',
      dispatchLrNumber: 'LR-VRL-99201',
      vendorBillNumber: 'BILL-CEN-9910',
      billDate: DateTime.now().subtract(const Duration(days: 6)),
      dueDate: DateTime.now().add(const Duration(days: 9)),
      billTotal: 186695,
      previousPaid: 0,
      currentPayment: 186695,
      status: VendorPaymentStatus.paid,
      paymentMethod: PaymentMethod.bankTransfer,
      bankName: 'HDFC Bank Ltd',
      bankAccountNo: '50200049102910',
      utrNumber: 'HDFCR520260905001290',
      paymentDate: DateTime.now().subtract(const Duration(days: 2)),
      notes: 'Full payment released against site delivery acceptance.',
    ),
    VendorPaymentRecord(
      id: 'VND-PAY-02',
      paymentId: 'VP-2026-049',
      vendorId: 'VND-002',
      vendorName: 'Austin Plywood Direct',
      vendorCode: 'VND-AUS-02',
      vendorContact: '+91 98222 34567',
      projectId: 'PRJ-OBR-202',
      projectName: 'Oberoi Sky City Penthouse #801',
      customerName: 'Pooja Mehta',
      poNumber: 'PO-2026-0094',
      rfqNumber: 'RFQ-2026-0052',
      vendorBillNumber: 'BILL-AUS-4011',
      billDate: DateTime.now().subtract(const Duration(days: 3)),
      dueDate: DateTime.now().add(const Duration(days: 12)),
      billTotal: 245000,
      previousPaid: 100000,
      currentPayment: 0,
      status: VendorPaymentStatus.approved,
      paymentMethod: PaymentMethod.bankTransfer,
      bankName: 'State Bank of India',
      bankAccountNo: '30291029102',
      notes: 'Balance 145,000 scheduled for RTGS batch release this Friday.',
    ),
  ];

  /// Labour Payments connecting to Service Booking & site QA
  static final List<LabourPaymentRecord> labourPayments = [
    LabourPaymentRecord(
      id: 'LAB-PAY-01',
      paymentId: 'LP-2026-019',
      contractorName: 'Nooruddin Carpentry Team',
      contractorId: 'LAB-001',
      contactPhone: '+91 98765 43210',
      serviceCategory: 'Modular Carpentry',
      projectId: 'PRJ-CAM-101',
      projectName: 'The Camellias Villa Interior #1402',
      customerName: 'Rahul Sharma',
      siteAddress: 'The Camellias, DLF Phase 5, Gurugram',
      workItem: 'Wardrobe Carcass Assembly & Base Kitchen Cabinets',
      workArea: 'Master Suite & Kitchen',
      stageOrMilestone: 'Milestone 2',
      workDate: DateTime.now().subtract(const Duration(days: 2)),
      completionPercentage: 100,
      grossAmount: 68000,
      incentive: 2000,
      deduction: 0,
      commissionDeduction: 3400,
      netPayable: 66600,
      previousPaid: 0,
      currentPayment: 66600,
      status: LabourPaymentStatus.paid,
      workAssigned: true,
      workCompleted: true,
      siteVerified: true,
      pmApproved: true,
      paymentEligible: true,
      supervisorVerificationNotes: 'Completed with zero alignment errors.',
      utrNumber: 'UPI-9921004120',
      disbursementDate: DateTime.now().subtract(const Duration(days: 1)),
    ),
    LabourPaymentRecord(
      id: 'LAB-PAY-02',
      paymentId: 'LP-2026-024',
      contractorName: 'Ramesh Electrical & Lighting Squad',
      contractorId: 'LAB-002',
      contactPhone: '+91 99102 33445',
      serviceCategory: 'Electrical & Automation',
      projectId: 'PRJ-OBR-202',
      projectName: 'Oberoi Sky City Penthouse #801',
      customerName: 'Pooja Mehta',
      siteAddress: 'Oberoi Sky City, Borivali East, Mumbai',
      workItem: 'Conduit laying, DB dressing & DALI Dimming testing',
      workArea: 'Living, Dining & Balcony',
      stageOrMilestone: 'Milestone 3',
      workDate: DateTime.now().subtract(const Duration(days: 1)),
      completionPercentage: 85,
      grossAmount: 42000,
      incentive: 0,
      deduction: 2000, // Material wastage penalty
      commissionDeduction: 2100,
      netPayable: 37900,
      previousPaid: 0,
      currentPayment: 0,
      status: LabourPaymentStatus.pendingApproval,
      workAssigned: true,
      workCompleted: true,
      siteVerified: true,
      pmApproved: false,
      paymentEligible: false,
      supervisorVerificationNotes: 'Site verification passed. PM approval required.',
    ),
  ];

  /// Commercial Commission Records
  static final List<CommissionRecord> commissions = [
    CommissionRecord(
      id: 'COMM-01',
      commissionId: 'COM-2026-011',
      type: CommissionType.sales,
      recipientName: 'Arjun Kapoor',
      recipientType: 'Senior Sales Executive',
      recipientId: 'EMP-SAL-04',
      sourceTransactionType: 'Invoice',
      sourceTransactionId: 'INV-2026-1024',
      projectId: 'PRJ-CAM-101',
      projectName: 'The Camellias Villa Interior #1402',
      customerName: 'Rahul Sharma',
      baseAmount: 2150000,
      commissionRate: 2.5,
      commissionAmount: 53750,
      effectiveDate: DateTime.now().subtract(const Duration(days: 14)),
      dueDate: DateTime.now().add(const Duration(days: 15)),
      status: CommissionStatus.approved,
      paidAmount: 0,
      notes: 'Payable post 70% customer collection milestone.',
    ),
    CommissionRecord(
      id: 'COMM-02',
      commissionId: 'COM-2026-014',
      type: CommissionType.vendor,
      recipientName: 'Century Sourcing Incentive',
      recipientType: 'Vendor Sourcing',
      recipientId: 'VND-CEN-01',
      sourceTransactionType: 'Purchase Order',
      sourceTransactionId: 'PO-2026-0081',
      projectId: 'PRJ-CAM-101',
      projectName: 'The Camellias Villa Interior #1402',
      customerName: 'Rahul Sharma',
      baseAmount: 155250,
      commissionRate: 6.5,
      commissionAmount: 10091,
      effectiveDate: DateTime.now().subtract(const Duration(days: 4)),
      dueDate: DateTime.now().add(const Duration(days: 20)),
      status: CommissionStatus.payable,
      paidAmount: 0,
      notes: 'Quarterly manufacturer volume kickback.',
    ),
    CommissionRecord(
      id: 'COMM-03',
      commissionId: 'COM-2026-009',
      type: CommissionType.aiDesigner,
      recipientName: 'Homio AI Studio Revenue Pool',
      recipientType: 'AI Designer',
      recipientId: 'SYS-AI-POOL',
      sourceTransactionType: 'Quotation',
      sourceTransactionId: 'QT-2026-081',
      projectId: 'PRJ-CAM-101',
      projectName: 'The Camellias Villa Interior #1402',
      customerName: 'Rahul Sharma',
      baseAmount: 120000,
      commissionRate: 15.0,
      commissionAmount: 18000,
      effectiveDate: DateTime.now().subtract(const Duration(days: 30)),
      dueDate: DateTime.now().subtract(const Duration(days: 1)),
      status: CommissionStatus.paid,
      paidAmount: 18000,
      notes: 'Automated 3D Room Concept Generation royalty.',
    ),
  ];

  /// Overdue Collections & Escalations
  static final List<OverdueCollectionItem> overdueCollections = [
    OverdueCollectionItem(
      id: 'OVD-ITEM-01',
      customerId: 'CUST-001',
      customerName: 'Rahul Sharma',
      customerPhone: '+91 98100 45210',
      customerEmail: 'rahul.sharma@dlf.in',
      projectId: 'PRJ-CAM-101',
      projectName: 'The Camellias Villa Interior #1402',
      invoiceNumber: 'INV-2026-1024',
      invoiceDate: DateTime.now().subtract(const Duration(days: 14)),
      dueDate: DateTime.now().subtract(const Duration(days: 1)),
      invoiceAmount: 2150000,
      paidAmount: 1320000,
      outstandingAmount: 830000,
      daysOverdue: 1,
      collectionOwner: 'Kavita Roy (Finance Lead)',
      lastReminderDate: DateTime.now().subtract(const Duration(hours: 4)),
      nextFollowUpDate: DateTime.now().add(const Duration(days: 1)),
      risk: CollectionRisk.medium,
      reminderCount: 2,
      status: 'Active Followup',
      notes: 'Client promised transfer post board meeting this afternoon.',
    ),
    OverdueCollectionItem(
      id: 'OVD-ITEM-02',
      customerId: 'CUST-003',
      customerName: 'Anand Mahindra',
      customerPhone: '+91 99000 11223',
      customerEmail: 'anand.m@prestige.com',
      projectId: 'PRJ-PFC-303',
      projectName: 'Prestige Falcon City 4BHK #504',
      invoiceNumber: 'INV-2026-0992',
      invoiceDate: DateTime.now().subtract(const Duration(days: 38)),
      dueDate: DateTime.now().subtract(const Duration(days: 18)),
      invoiceAmount: 650000,
      paidAmount: 200000,
      outstandingAmount: 450000,
      daysOverdue: 18,
      collectionOwner: 'Deepak Rao (PM / Ops)',
      lastReminderDate: DateTime.now().subtract(const Duration(days: 2)),
      nextFollowUpDate: DateTime.now().add(const Duration(days: 2)),
      risk: CollectionRisk.high,
      reminderCount: 4,
      status: 'Escalated to Supervisor',
      notes: 'Site work on false ceiling slowed down pending ₹4.5L clearance.',
    ),
  ];

  /// Client Promises to Pay
  static final List<PromiseToPay> promisesToPay = [
    PromiseToPay(
      id: 'PTP-001',
      customerName: 'Rahul Sharma',
      projectName: 'The Camellias Villa Interior #1402',
      invoiceNumber: 'INV-2026-1024',
      promiseDate: DateTime.now().add(const Duration(days: 2)),
      promisedAmount: 830000,
      customerContact: '+91 98100 45210',
      collectionOwner: 'Kavita Roy (Finance Lead)',
      followUpDate: DateTime.now().add(const Duration(days: 3)),
      notes: 'Promised HDFC NetBanking clearance by 10th Sep.',
      status: PromiseToPayStatus.promised,
    ),
  ];

  /// Bank Reconciliation Items
  static final List<ReconciliationItem> reconciliations = [
    ReconciliationItem(
      id: 'REC-001',
      systemPaymentRef: 'PAY-2026-088',
      bankUtrRef: 'HDFCR520260904001920',
      paymentDate: DateTime.now().subtract(const Duration(days: 4)),
      amount: 1320000,
      customerName: 'Rahul Sharma',
      bankAccount: 'HDFC Bank - A/C 502000881920',
      isReconciled: true,
      reconciledAt: DateTime.now().subtract(const Duration(days: 3)),
    ),
    ReconciliationItem(
      id: 'REC-002',
      systemPaymentRef: 'PAY-2026-079',
      bankUtrRef: 'AXISR520260906004812',
      paymentDate: DateTime.now().subtract(const Duration(days: 2)),
      amount: 2650000,
      customerName: 'Pooja Mehta',
      bankAccount: 'Axis Bank - A/C 912020048192',
      isReconciled: true,
      reconciledAt: DateTime.now().subtract(const Duration(days: 1)),
    ),
    ReconciliationItem(
      id: 'REC-003',
      systemPaymentRef: 'PAY-PENDING-99',
      bankUtrRef: 'ICICIR520260908001099',
      paymentDate: DateTime.now().subtract(const Duration(hours: 6)),
      amount: 120000,
      customerName: 'Unidentified Client Credit',
      bankAccount: 'HDFC Bank - A/C 502000881920',
      isReconciled: false,
      discrepancyNotes: 'Needs client ledger allocation. Possible booking advance.',
    ),
  ];

  /// Project Financial Health Ranking Summaries
  static final List<ProjectFinancialHealthSummary> projectHealthSummaries = [
    const ProjectFinancialHealthSummary(
      projectId: 'PRJ-CAM-101',
      projectName: 'The Camellias Villa Interior #1402',
      customerName: 'Rahul Sharma',
      totalProjectValue: 4800000,
      invoicedAmount: 3650000,
      collectedAmount: 2820000,
      outstandingAmount: 830000,
      materialCost: 1670000,
      labourCost: 830000,
      designCost: 180000,
      consultingCost: 120000,
      supervisionCost: 80000,
      otherExpenses: 45000,
      health: FinancialHealth.warning,
    ),
    const ProjectFinancialHealthSummary(
      projectId: 'PRJ-OBR-202',
      projectName: 'Oberoi Sky City Penthouse #801',
      customerName: 'Pooja Mehta',
      totalProjectValue: 3800000,
      invoicedAmount: 2900000,
      collectedAmount: 2650000,
      outstandingAmount: 250000,
      materialCost: 1400000,
      labourCost: 690000,
      designCost: 140000,
      consultingCost: 90000,
      supervisionCost: 70000,
      otherExpenses: 30000,
      health: FinancialHealth.healthy,
    ),
    const ProjectFinancialHealthSummary(
      projectId: 'PRJ-PFC-303',
      projectName: 'Prestige Falcon City 4BHK #504',
      customerName: 'Anand Mahindra',
      totalProjectValue: 2800000,
      invoicedAmount: 2100000,
      collectedAmount: 1650000,
      outstandingAmount: 450000,
      materialCost: 1000000,
      labourCost: 570000,
      designCost: 110000,
      consultingCost: 80000,
      supervisionCost: 60000,
      otherExpenses: 25000,
      health: FinancialHealth.critical,
    ),
  ];

  static const OverdueAutomationConfig automationConfig = OverdueAutomationConfig();
}
