import 'hrms_models.dart';

class HrmsMockData {
  // 1. Employee Directory Dossiers
  static final List<EmployeeDossier> employees = [
    EmployeeDossier(
      id: 'EMP-01',
      fullName: 'Vikram Malhotra',
      email: 'vikram.m@homio.in',
      phone: '+91 98101 44210',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
      department: DepartmentType.sales,
      roleTitle: 'Head of Sales & Pipeline Governance',
      level: HierarchyLevel.lead,
      joiningDate: DateTime(2023, 3, 15),
      status: EmployeeStatus.active,
      accessScope: AccessScope.organizationWide,
      kyc: KycVerification(
        aadhaarVerified: true,
        panVerified: true,
        bankAccountLinked: true,
        signedAgreementAttached: true,
        aadhaarNumber: 'XXXX-XXXX-8821',
        panNumber: 'ABCDE1234F',
        bankAccountNumber: '918237189234',
        ifscCode: 'HDFC0001824',
      ),
      baseSalary: 120000,
      emergencyContactName: 'Meera Malhotra (Spouse)',
      emergencyContactPhone: '+91 98101 44211',
    ),
    EmployeeDossier(
      id: 'EMP-02',
      fullName: 'Ananya Roy',
      email: 'ananya.r@homio.in',
      phone: '+91 99201 88412',
      avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150',
      department: DepartmentType.design,
      roleTitle: 'Design Project Manager',
      level: HierarchyLevel.manager,
      joiningDate: DateTime(2023, 6, 1),
      status: EmployeeStatus.active,
      accessScope: AccessScope.organizationWide,
      kyc: KycVerification(
        aadhaarVerified: true,
        panVerified: true,
        bankAccountLinked: true,
        signedAgreementAttached: true,
        aadhaarNumber: 'XXXX-XXXX-9912',
        panNumber: 'BKLPQ9876K',
        bankAccountNumber: '109283746512',
        ifscCode: 'ICIC0000912',
      ),
      baseSalary: 95000,
      emergencyContactName: 'Debabrata Roy (Father)',
      emergencyContactPhone: '+91 99201 88410',
    ),
    EmployeeDossier(
      id: 'EMP-03',
      fullName: 'Pooja Hegde',
      email: 'pooja.h@homio.in',
      phone: '+91 98334 11200',
      avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150',
      department: DepartmentType.design,
      roleTitle: 'Senior 3D Artist & Rendering Specialist',
      level: HierarchyLevel.specialist,
      joiningDate: DateTime(2023, 8, 10),
      status: EmployeeStatus.active,
      accessScope: AccessScope.myLeadsTasks,
      kyc: KycVerification(
        aadhaarVerified: true,
        panVerified: true,
        bankAccountLinked: true,
        signedAgreementAttached: true,
        aadhaarNumber: 'XXXX-XXXX-3341',
        panNumber: 'CLRPZ4567M',
        bankAccountNumber: '556677889900',
        ifscCode: 'KKBK0004521',
      ),
      baseSalary: 68000,
      emergencyContactName: 'Girish Hegde (Brother)',
      emergencyContactPhone: '+91 98334 11201',
    ),
    EmployeeDossier(
      id: 'EMP-04',
      fullName: 'Rajesh Verma',
      email: 'rajesh.v@homio.in',
      phone: '+91 98112 33455',
      avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
      department: DepartmentType.execution,
      roleTitle: 'Senior Site Execution Supervisor',
      level: HierarchyLevel.manager,
      joiningDate: DateTime(2022, 11, 20),
      status: EmployeeStatus.active,
      accessScope: AccessScope.myLeadsTasks,
      kyc: KycVerification(
        aadhaarVerified: true,
        panVerified: true,
        bankAccountLinked: true,
        signedAgreementAttached: true,
        aadhaarNumber: 'XXXX-XXXX-5521',
        panNumber: 'DFGTY3456L',
        bankAccountNumber: '223344556677',
        ifscCode: 'SBIN0008912',
      ),
      baseSalary: 55000,
      emergencyContactName: 'Kusum Verma (Spouse)',
      emergencyContactPhone: '+91 98112 33450',
    ),
    EmployeeDossier(
      id: 'EMP-05',
      fullName: 'Amitabh Sharma',
      email: 'amitabh.s@homio.in',
      phone: '+91 99104 77819',
      avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
      department: DepartmentType.execution,
      roleTitle: 'Site Execution Supervisor (Civil & MEP)',
      level: HierarchyLevel.specialist,
      joiningDate: DateTime(2023, 2, 1),
      status: EmployeeStatus.active,
      accessScope: AccessScope.myLeadsTasks,
      kyc: KycVerification(
        aadhaarVerified: true,
        panVerified: true,
        bankAccountLinked: true,
        signedAgreementAttached: true,
        aadhaarNumber: 'XXXX-XXXX-4401',
        panNumber: 'PLMKO8765N',
        bankAccountNumber: '334455667788',
        ifscCode: 'PUNB0001234',
      ),
      baseSalary: 48000,
      emergencyContactName: 'Ramesh Sharma (Father)',
      emergencyContactPhone: '+91 99104 77810',
    ),
    EmployeeDossier(
      id: 'EMP-06',
      fullName: 'Neha Singhal',
      email: 'neha.s@homio.in',
      phone: '+91 98205 66710',
      avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150',
      department: DepartmentType.sales,
      roleTitle: 'High-Ticket Deal Closer',
      level: HierarchyLevel.manager,
      joiningDate: DateTime(2023, 5, 12),
      status: EmployeeStatus.active,
      accessScope: AccessScope.organizationWide,
      kyc: KycVerification(
        aadhaarVerified: true,
        panVerified: true,
        bankAccountLinked: true,
        signedAgreementAttached: true,
        aadhaarNumber: 'XXXX-XXXX-1123',
        panNumber: 'ZXCVB9876Q',
        bankAccountNumber: '445566778899',
        ifscCode: 'AXIS0000845',
      ),
      baseSalary: 75000,
      emergencyContactName: 'Aditya Singhal (Spouse)',
      emergencyContactPhone: '+91 98205 66711',
    ),
    EmployeeDossier(
      id: 'EMP-07',
      fullName: 'Rohan Deshmukh',
      email: 'rohan.d@homio.in',
      phone: '+91 98920 33419',
      avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
      department: DepartmentType.sales,
      roleTitle: 'Junior Telecaller (Autodialer Lead Intake)',
      level: HierarchyLevel.junior,
      joiningDate: DateTime(2024, 1, 15),
      status: EmployeeStatus.active,
      accessScope: AccessScope.myLeadsTasks,
      kyc: KycVerification(
        aadhaarVerified: true,
        panVerified: true,
        bankAccountLinked: true,
        signedAgreementAttached: true,
        aadhaarNumber: 'XXXX-XXXX-7721',
        panNumber: 'QWERT1234Z',
        bankAccountNumber: '667788990011',
        ifscCode: 'BARB0DELHI1',
      ),
      baseSalary: 28000,
      emergencyContactName: 'Sunita Deshmukh (Mother)',
      emergencyContactPhone: '+91 98920 33410',
    ),
    EmployeeDossier(
      id: 'EMP-08',
      fullName: 'Gaurav Sharma',
      email: 'gaurav.s@homio.in',
      phone: '+91 98711 55620',
      avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150',
      department: DepartmentType.design,
      roleTitle: 'Site Measurement & Laser Survey Coordinator',
      level: HierarchyLevel.junior,
      joiningDate: DateTime(2023, 10, 5),
      status: EmployeeStatus.noticePeriod,
      accessScope: AccessScope.myLeadsTasks,
      kyc: KycVerification(
        aadhaarVerified: true,
        panVerified: true,
        bankAccountLinked: true,
        signedAgreementAttached: true,
        aadhaarNumber: 'XXXX-XXXX-9988',
        panNumber: 'TYUIO5678P',
        bankAccountNumber: '778899001122',
        ifscCode: 'CNRB0001923',
      ),
      baseSalary: 32000,
      emergencyContactName: 'Manju Sharma (Mother)',
      emergencyContactPhone: '+91 98711 55621',
    ),
  ];

  // 2. Geofence Zones
  static const List<GeofenceZone> geofences = [
    GeofenceZone(
      id: 'GEO-01',
      name: 'Homio Corporate HQ, Cyber City',
      centerLat: 28.4984,
      centerLng: 77.0928,
      radiusMeters: 100.0,
      activeSiteName: 'Building 10B, DLF Cyber City, Gurugram',
    ),
    GeofenceZone(
      id: 'GEO-02',
      name: 'DLF Magnolias Site Perimeter',
      centerLat: 28.4595,
      centerLng: 77.0946,
      radiusMeters: 150.0,
      activeSiteName: 'Apartment #402, DLF Magnolias, Golf Course Rd',
    ),
    GeofenceZone(
      id: 'GEO-03',
      name: 'Trump Towers Site Perimeter',
      centerLat: 28.4121,
      centerLng: 77.0865,
      radiusMeters: 200.0,
      activeSiteName: 'Tower 2, Unit #2104, Golf Course Ext.',
    ),
    GeofenceZone(
      id: 'GEO-04',
      name: 'Lodha Altamount Site Boundary',
      centerLat: 18.9667,
      centerLng: 72.8083,
      radiusMeters: 120.0,
      activeSiteName: 'Altamount Road #18A, Mumbai',
    ),
  ];

  // 3. Attendance Records
  static final List<AttendanceRecord> attendanceRecords = [
    AttendanceRecord(
      id: 'ATT-01',
      employeeId: 'EMP-04',
      employeeName: 'Rajesh Verma',
      departmentName: 'Execution',
      date: DateTime.now(),
      checkInTime: DateTime(DateTime.now().year, DateTime.now().month, DateTime.now().day, 9, 15),
      checkInSelfieUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100',
      latitude: 28.4594,
      longitude: 77.0945,
      geofenceStatus: GeofenceStatus.withinGeofence,
      loggedHours: 8.5,
      overtimeHours: 1.0,
      status: AttendanceStatus.present,
    ),
    AttendanceRecord(
      id: 'ATT-02',
      employeeId: 'EMP-05',
      employeeName: 'Amitabh Sharma',
      departmentName: 'Execution',
      date: DateTime.now(),
      checkInTime: DateTime(DateTime.now().year, DateTime.now().month, DateTime.now().day, 9, 45),
      checkInSelfieUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100',
      latitude: 28.4120,
      longitude: 77.0864,
      geofenceStatus: GeofenceStatus.withinGeofence,
      loggedHours: 7.5,
      overtimeHours: 0.0,
      status: AttendanceStatus.late,
    ),
    AttendanceRecord(
      id: 'ATT-03',
      employeeId: 'EMP-02',
      employeeName: 'Ananya Roy',
      departmentName: 'Design',
      date: DateTime.now(),
      checkInTime: DateTime(DateTime.now().year, DateTime.now().month, DateTime.now().day, 9, 5),
      checkInSelfieUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=100',
      latitude: 28.4983,
      longitude: 77.0927,
      geofenceStatus: GeofenceStatus.withinGeofence,
      loggedHours: 8.8,
      overtimeHours: 0.5,
      status: AttendanceStatus.present,
    ),
    AttendanceRecord(
      id: 'ATT-04',
      employeeId: 'EMP-08',
      employeeName: 'Gaurav Sharma',
      departmentName: 'Design',
      date: DateTime.now(),
      checkInTime: DateTime(DateTime.now().year, DateTime.now().month, DateTime.now().day, 10, 20),
      checkInSelfieUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=100',
      latitude: 28.5300, // 3 km outside perimeter
      longitude: 77.1200,
      geofenceStatus: GeofenceStatus.outsideViolation,
      loggedHours: 6.0,
      overtimeHours: 0.0,
      status: AttendanceStatus.late,
    ),
  ];

  // 4. GPS Travel Mileage Records
  static final List<TravelMileageRecord> travelRecords = [
    TravelMileageRecord(
      id: 'TRV-101',
      employeeId: 'EMP-04',
      employeeName: 'Rajesh Verma',
      departmentName: 'Execution',
      date: DateTime.now().subtract(const Duration(hours: 3)),
      projectName: 'DLF Magnolias #402',
      departureLocation: 'Homio HQ Cyber City, Gurugram',
      departureTime: DateTime(DateTime.now().year, DateTime.now().month, DateTime.now().day, 8, 30),
      departureSelfieUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100',
      arrivalLocation: 'DLF Magnolias Site, Golf Course Road',
      arrivalTime: DateTime(DateTime.now().year, DateTime.now().month, DateTime.now().day, 9, 10),
      arrivalSelfieUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100',
      distanceKm: 14.8,
      ratePerKm: 12.0, // 2-wheeler rate
      reimbursementAmount: 177.6,
      approvalStatus: ApprovalStatus.approved,
      notes: 'Morning site inspection for master wardrobe carcass delivery.',
    ),
    TravelMileageRecord(
      id: 'TRV-102',
      employeeId: 'EMP-08',
      employeeName: 'Gaurav Sharma',
      departmentName: 'Design',
      date: DateTime.now().subtract(const Duration(hours: 5)),
      projectName: 'Trump Towers #2104',
      departureLocation: 'Homio HQ Cyber City',
      departureTime: DateTime(DateTime.now().year, DateTime.now().month, DateTime.now().day, 11, 0),
      departureSelfieUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=100',
      arrivalLocation: 'Trump Towers, Golf Course Ext.',
      arrivalTime: DateTime(DateTime.now().year, DateTime.now().month, DateTime.now().day, 11, 50),
      arrivalSelfieUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=100',
      distanceKm: 22.4,
      ratePerKm: 18.0, // 4-wheeler cab rate
      reimbursementAmount: 403.2,
      approvalStatus: ApprovalStatus.pending,
      notes: 'Laser survey & 3D scan for double-height living room elevation.',
    ),
  ];

  // 5. Leave Applications & Double Penalty Deductions
  static final List<LeaveApplication> leaveApplications = [
    LeaveApplication(
      id: 'LEV-01',
      employeeId: 'EMP-03',
      employeeName: 'Pooja Hegde',
      departmentName: 'Design',
      leaveType: LeaveType.casual,
      startDate: DateTime.now().add(const Duration(days: 4)),
      endDate: DateTime.now().add(const Duration(days: 5)),
      totalDays: 2,
      reason: 'Family wedding function in Mangalore.',
      status: ApprovalStatus.approved,
      appliedDate: DateTime.now().subtract(const Duration(days: 2)),
      reviewedBy: 'Ananya Roy (Design PM)',
    ),
    LeaveApplication(
      id: 'LEV-02',
      employeeId: 'EMP-07',
      employeeName: 'Rohan Deshmukh',
      departmentName: 'Sales',
      leaveType: LeaveType.unapproved,
      startDate: DateTime.now().subtract(const Duration(days: 2)),
      endDate: DateTime.now().subtract(const Duration(days: 2)),
      totalDays: 1,
      reason: 'Absent on Monday sales sprint without formal notification.',
      status: ApprovalStatus.rejected,
      isDoublePenaltyApplied: true,
      penaltyDeductionAmount: 1866.66, // 2 days of base salary (28,000 / 30 * 2)
      appliedDate: DateTime.now().subtract(const Duration(days: 2)),
      reviewedBy: 'Vikram Malhotra (Sales Head)',
    ),
    LeaveApplication(
      id: 'LEV-03',
      employeeId: 'EMP-05',
      employeeName: 'Amitabh Sharma',
      departmentName: 'Execution',
      leaveType: LeaveType.sick,
      startDate: DateTime.now().add(const Duration(days: 1)),
      endDate: DateTime.now().add(const Duration(days: 1)),
      totalDays: 1,
      reason: 'Doctor consultation & medical diagnostic checkup.',
      status: ApprovalStatus.pending,
      appliedDate: DateTime.now().subtract(const Duration(hours: 6)),
    ),
  ];

  // 6. Monthly Payroll Records
  static final List<PayrollRecord> payrollRecords = [
    PayrollRecord(
      id: 'PAY-2026-08-01',
      employeeId: 'EMP-01',
      employeeName: 'Vikram Malhotra',
      departmentName: 'Sales',
      roleTitle: 'Head of Sales',
      monthYear: 'August 2026',
      baseSalary: 120000,
      travelAllowance: 4800,
      incentives: 35000, // Deal closer incentive
      overtimePay: 0,
      absenteeismDoublePenalty: 0,
      statutoryDeductions: 14200, // PF + Professional Tax + TDS
      paymentStatus: PayrollStatus.approved,
      paymentRef: 'NEFT-HOM-202608-0192',
      generatedDate: DateTime.now().subtract(const Duration(days: 7)),
    ),
    PayrollRecord(
      id: 'PAY-2026-08-02',
      employeeId: 'EMP-04',
      employeeName: 'Rajesh Verma',
      departmentName: 'Execution',
      roleTitle: 'Senior Site Supervisor',
      monthYear: 'August 2026',
      baseSalary: 55000,
      travelAllowance: 6450, // High field mileage
      incentives: 8000, // On-time milestone completion
      overtimePay: 3200,
      absenteeismDoublePenalty: 0,
      statutoryDeductions: 6800,
      paymentStatus: PayrollStatus.approved,
      paymentRef: 'NEFT-HOM-202608-0193',
      generatedDate: DateTime.now().subtract(const Duration(days: 7)),
    ),
    PayrollRecord(
      id: 'PAY-2026-08-03',
      employeeId: 'EMP-07',
      employeeName: 'Rohan Deshmukh',
      departmentName: 'Sales',
      roleTitle: 'Junior Telecaller',
      monthYear: 'August 2026',
      baseSalary: 28000,
      travelAllowance: 0,
      incentives: 4500,
      overtimePay: 0,
      absenteeismDoublePenalty: 1866.66, // 1 unapproved leave * 2x
      statutoryDeductions: 3200,
      paymentStatus: PayrollStatus.draft,
      generatedDate: DateTime.now().subtract(const Duration(days: 7)),
    ),
  ];

  // 7. Resignations & Notice Period Clearance
  static final List<NoticePeriodHandoff> noticePeriodRecords = [
    NoticePeriodHandoff(
      id: 'NOT-01',
      employeeId: 'EMP-08',
      employeeName: 'Gaurav Sharma',
      departmentName: 'Design',
      roleTitle: 'Site Measurement Coordinator',
      resignationDate: DateTime.now().subtract(const Duration(days: 18)),
      noticeDays: 30,
      lwdDate: DateTime.now().add(const Duration(days: 12)),
      remainingDays: 12,
      assetClearanceStatus: true, // Laser meter returned
      projectHandoverStatus: false, // 2 site surveys pending transfer
      accountsNoDuesStatus: true,
      relievingLetterIssued: false,
    ),
  ];
}

// Convenient top-level aliases for HRMS screens
final List<EmployeeDossier> hrmsMockEmployees = HrmsMockData.employees;
final List<GeofenceZone> hrmsMockZones = HrmsMockData.geofences;
final List<AttendanceRecord> hrmsMockAttendance = HrmsMockData.attendanceRecords;
final List<TravelMileageRecord> hrmsMockTravelRecords = HrmsMockData.travelRecords;
final List<LeaveApplication> hrmsMockLeaves = HrmsMockData.leaveApplications;
final List<PayrollRecord> hrmsMockPayrolls = HrmsMockData.payrollRecords;
final List<NoticePeriodHandoff> hrmsMockNoticeHandoffs = HrmsMockData.noticePeriodRecords;

