import 'marketplace_enums.dart';
import 'digital_product_models.dart';
import 'home_decor_models.dart';
import 'material_models.dart';
import 'property_models.dart';
import 'labour_models.dart';
import 'order_models.dart';

/// Curated production-grade realistic mock data for HOMIO Marketplace
class MarketplaceMockData {
  // -------------------------------------------------------------
  // 1. DIGITAL PRODUCTS
  // -------------------------------------------------------------
  static final List<DigitalProductItem> digitalProducts = [
    DigitalProductItem(
      id: 'dig-001',
      title: 'Vastu Shastra Comprehensive Blueprints',
      subtitle: 'Complete 32-Zone Energy Mapping & Door Placement Guide',
      description:
          'Authoritative architectural Vastu handbook curated by senior Vedic architects. Includes detailed compass orientation overlays, kitchen/master-bedroom zoning, puja room alignment, and remedial geometries for non-compliant apartments.',
      category: DigitalProductCategory.vastuHandbooks,
      price: 1499.0,
      originalPrice: 2999.0,
      rating: 4.9,
      reviewCount: 238,
      downloadCount: 1840,
      fileFormat: 'PDF + AutoCAD DWG',
      fileSize: '48.5 MB',
      compatibleSoftware: ['AutoCAD', 'Revit', 'Adobe Acrobat', 'SketchUp'],
      previewImages: [
        'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1600565193348-f74bd3c7ccdf?w=800&auto=format&fit=crop&q=80',
      ],
      authorName: 'Ar. Rajeshwar Iyer',
      authorRole: 'Vedic Architecture Lead, HOMIO',
      publishedDate: DateTime(2026, 1, 15),
      downloadUrl: 'https://homio.in/assets/downloads/vastu_shastra_master_2026.zip',
      isFeatured: true,
      tags: ['Vastu', 'Energy Flow', 'Architectural DWG', 'Vedic'],
      inclusions: [
        'High-resolution vector 32-zone compass chart',
        'Ready-to-use AutoCAD 2024 DWG templates',
        'Room-by-room compliance score rubric',
        'Remedy placement cheat-sheet (Mirrors, Pyramids, Plants)',
      ],
    ),
    DigitalProductItem(
      id: 'dig-002',
      title: 'Luxury 3BHK BIM Revit Architecture Master Pack',
      subtitle: 'Fully Parametric Families, Millwork & Schedule Tables',
      description:
          'Ready-to-render BIM dataset for 1800-2400 sq.ft luxury apartments. Features custom cabinetry families, nested electrical junction boxes, dynamic lighting schedules, and automated BOQ extraction formulas.',
      category: DigitalProductCategory.cadBimTemplates,
      price: 3499.0,
      originalPrice: 5999.0,
      rating: 4.8,
      reviewCount: 142,
      downloadCount: 920,
      fileFormat: 'RVT (2024+) + IFC',
      fileSize: '312.0 MB',
      compatibleSoftware: ['Autodesk Revit', 'Navisworks', 'ArchiCAD', 'Blender'],
      previewImages: [
        'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&auto=format&fit=crop&q=80',
      ],
      authorName: 'Studio ArchDimension',
      authorRole: 'BIM Automation Partners',
      publishedDate: DateTime(2026, 2, 10),
      downloadUrl: 'https://homio.in/assets/downloads/revit_3bhk_pack.zip',
      isFeatured: true,
      tags: ['BIM', 'Revit', 'Parametric', 'BOQ Ready'],
      inclusions: [
        'Parametric Italian kitchen cabinetry families',
        'Pre-linked electrical, plumbing and HVAC MEP layers',
        'Automated bill of materials schedules',
      ],
    ),
    DigitalProductItem(
      id: 'dig-003',
      title: 'Japandi & Scandinavian 3ds Max + Corona Shaders',
      subtitle: '80+ PBR Textures with 8K Wood Veneers & Boucle Fabrics',
      description:
          'Hyper-photorealistic material library optimized for Corona Renderer and V-Ray 6. Handcrafted seamlessly tiling maps for oak fluted panels, travertine marble, brushed brass, and textured linen drapery.',
      category: DigitalProductCategory.interiorPresets,
      price: 2199.0,
      originalPrice: 3800.0,
      rating: 5.0,
      reviewCount: 89,
      downloadCount: 650,
      fileFormat: 'MAT + 8K PNG Textures',
      fileSize: '1.8 GB',
      compatibleSoftware: ['3ds Max', 'Corona Renderer', 'V-Ray', 'Cinema 4D'],
      previewImages: [
        'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=800&auto=format&fit=crop&q=80',
      ],
      authorName: 'CGI RenderCraft',
      authorRole: 'Lead Visualization Studio',
      publishedDate: DateTime(2026, 3, 1),
      downloadUrl: 'https://homio.in/assets/downloads/japandi_corona_shaders.zip',
      isFeatured: false,
      tags: ['Corona', '3ds Max', 'PBR Textures', 'Photoreal'],
      inclusions: [
        '80 PBR master materials (.mat)',
        '8K Diffuse, Roughness, Normal, Height maps',
        'Studio lighting rig scene template (.max)',
      ],
    ),
    DigitalProductItem(
      id: 'dig-004',
      title: 'Complete Commercial Turnkey Interior BOQ Spreadsheet',
      subtitle: 'Dynamic Formulae, CPWD Market Rates & Labour Factor Matrix',
      description:
          'Exhaustive Microsoft Excel financial model for interior fitouts. Built-in rate analysis for civil demolition, acoustic partitions, fire fighting MEP, networking conduits, and overhead escalation margins.',
      category: DigitalProductCategory.boqSpreadsheets,
      price: 1199.0,
      originalPrice: 1999.0,
      rating: 4.7,
      reviewCount: 310,
      downloadCount: 2450,
      fileFormat: 'XLSX + Google Sheets Link',
      fileSize: '14.2 MB',
      compatibleSoftware: ['Microsoft Excel', 'Google Sheets', 'LibreOffice'],
      previewImages: [
        'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&auto=format&fit=crop&q=80',
      ],
      authorName: 'HOMIO Cost Engineering Cell',
      authorRole: 'Senior QS & Estimation Team',
      publishedDate: DateTime(2026, 1, 28),
      downloadUrl: 'https://homio.in/assets/downloads/homio_master_boq.xlsx',
      isFeatured: false,
      tags: ['BOQ', 'Costing', 'Estimation', 'Excel'],
      inclusions: [
        '250+ categorized line items with CPWD rate benchmarks',
        'Automatic contractor profit & GST computation',
        'Client-ready executive summary sheet format',
      ],
    ),
    DigitalProductItem(
      id: 'dig-005',
      title: 'VR 360° Luxury Penthouse Interactive Walkthrough',
      subtitle: 'Oculus Quest & WebGL Browser Ready Unreal Engine 5 Build',
      description:
          'Fully baked interactive virtual reality interior walkthrough. Toggle daylight conditions from 9 AM golden hour to midnight mood lighting. Experience realistic acoustic soundscapes and tactile physics.',
      category: DigitalProductCategory.vrWalkthroughs,
      price: 4999.0,
      originalPrice: 8500.0,
      rating: 4.9,
      reviewCount: 47,
      downloadCount: 310,
      fileFormat: 'UE5 Executable + WebGL 2.0',
      fileSize: '3.4 GB',
      compatibleSoftware: ['Meta Quest 2/3', 'Windows PC', 'WebGL Chrome/Edge'],
      previewImages: [
        'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=800&auto=format&fit=crop&q=80',
      ],
      authorName: 'HOMIO Immersive Labs',
      authorRole: 'Spatial Computing Unit',
      publishedDate: DateTime(2026, 2, 22),
      downloadUrl: 'https://homio.in/assets/downloads/penthouse_vr_ue5.zip',
      isFeatured: true,
      tags: ['VR', 'Unreal Engine 5', 'WebGL', 'Walkthrough'],
      inclusions: [
        'Precompiled Windows executable with ray-tracing support',
        'Standalone APK for Meta Quest headsets',
        'Embeddable WebGL client preview link',
      ],
    ),
    DigitalProductItem(
      id: 'dig-006',
      title: 'Residential Construction Legal Due Diligence Kit',
      subtitle: 'RERA Verification Checklist, Encumbrance & Contractor Contracts',
      description:
          'Lawyer-drafted agreements tailored for Indian real estate buyers and renovators. Includes milestone-linked contractor contracts, penalty penalty clauses, defect liability periods, and property title vetting roadmaps.',
      category: DigitalProductCategory.legalChecklists,
      price: 899.0,
      originalPrice: 1799.0,
      rating: 4.8,
      reviewCount: 184,
      downloadCount: 1620,
      fileFormat: 'DOCX + Editable PDF',
      fileSize: '6.4 MB',
      compatibleSoftware: ['Microsoft Word', 'Google Docs', 'Adobe Acrobat'],
      previewImages: [
        'https://images.unsplash.com/photo-1450133064473-71024230f91b?w=800&auto=format&fit=crop&q=80',
      ],
      authorName: 'Adv. Meenakshi Sundaram',
      authorRole: 'Real Estate Legal Counsel',
      publishedDate: DateTime(2026, 1, 5),
      downloadUrl: 'https://homio.in/assets/downloads/legal_due_diligence_kit.zip',
      isFeatured: false,
      tags: ['Legal', 'RERA', 'Contract', 'Indian Law'],
      inclusions: [
        'Turnkey Contractor Agreement template with arbitration clause',
        'Architect Scope & Payment schedule agreement',
        'RERA sanction verification checklist (38 points)',
      ],
    ),
  ];

  // -------------------------------------------------------------
  // 2. HOME DECOR & CURATED FURNITURE
  // -------------------------------------------------------------
  static final List<HomeDecorItem> homeDecorItems = [
    HomeDecorItem(
      id: 'dec-001',
      title: 'Aethel Mid-Century Brass Sputnik Chandelier',
      brand: 'Lumiere Atelier',
      description:
          'Hand-spun brushed antique brass chandelier with 12 blown opal glass globes. Dimmable warm 2700K illumination designed to elevate high-ceiling living rooms and dining tables.',
      category: HomeDecorCategory.lighting,
      price: 18499.0,
      originalPrice: 24999.0,
      rating: 4.9,
      reviewCount: 76,
      imageUrls: [
        'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=800&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1540932239986-30128078f3c5?w=800&auto=format&fit=crop&q=80',
      ],
      specifications: {
        'Material': 'Solid Brass & Opal Frosted Glass',
        'Bulb Base': 'G9 LED (Included 12x 5W)',
        'Voltage': '220V - 240V Indian Standard',
        'Canopy Diameter': '15 cm',
        'Suspension Rod': 'Adjustable 60 cm to 120 cm',
      },
      dimensions: '95 cm x 95 cm x 72 cm',
      material: 'Solid Brass & Hand-blown Glass',
      colorOptions: ['Brushed Brass', 'Matte Black', 'Rose Copper'],
      inStock: true,
      stockCount: 8,
      isAffiliate: false,
      affiliatePlatform: AffiliatePlatform.homioDirect,
      estimatedDeliveryDays: 3,
      isFeatured: true,
      designStyle: 'Mid-Century Modern',
    ),
    HomeDecorItem(
      id: 'dec-002',
      title: 'Kiyomi Hand-Carved Teakwood Lounge Accent Chair',
      brand: 'Saga Living',
      description:
          'Sculptural Japandi lounge chair crafted from sustainably sourced Grade-A Burma Teak. Upholstered in stain-resistant textured off-white boucle fabric with high-density ergonomic cushioning.',
      category: HomeDecorCategory.furniture,
      price: 22999.0,
      originalPrice: 29999.0,
      rating: 4.8,
      reviewCount: 52,
      imageUrls: [
        'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=800&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&auto=format&fit=crop&q=80',
      ],
      specifications: {
        'Wood Finish': 'Natural Matte PU Sealer',
        'Fabric Grade': '450 GSM Heavy Boucle',
        'Weight Capacity': '160 kg tested',
        'Foam Density': '38 High Resilience Foam',
      },
      dimensions: '82 cm W x 86 cm D x 74 cm H',
      material: 'Grade-A Burma Teak & Boucle',
      colorOptions: ['Ivory Boucle', 'Oatmeal Tweed', 'Charcoal Grey'],
      inStock: true,
      stockCount: 14,
      isAffiliate: true,
      affiliatePlatform: AffiliatePlatform.pepperfry,
      affiliateUrl: 'https://pepperfry.com/p/saga-living-kiyomi-teak-chair',
      estimatedDeliveryDays: 5,
      isFeatured: true,
      designStyle: 'Japandi Minimalist',
    ),
    HomeDecorItem(
      id: 'dec-003',
      title: 'Tivoli Hand-Tufted New Zealand Wool Area Rug (8x10 ft)',
      brand: 'Varanasi Weave House',
      description:
          'High-density 100% pure New Zealand wool rug featuring an organic high-low carved linear relief pattern. Naturally hypoallergenic, stain resistant, and plush 18mm pile height.',
      category: HomeDecorCategory.carpetsRugs,
      price: 34500.0,
      originalPrice: 42000.0,
      rating: 4.9,
      reviewCount: 38,
      imageUrls: [
        'https://images.unsplash.com/photo-1600121848594-d8644e57abab?w=800&auto=format&fit=crop&q=80',
      ],
      specifications: {
        'Knot Density': '85,000 knots/sq.m',
        'Yarn': '100% Pure New Zealand Wool',
        'Backing': 'Natural Cotton Canvas & Latex',
        'Care': 'Vacuum regularly, professional wool clean',
      },
      dimensions: '240 cm x 300 cm (8 x 10 Feet)',
      material: '100% New Zealand Wool',
      colorOptions: ['Ivory & Sand', 'Slate & Chalk', 'Sage Green'],
      inStock: true,
      stockCount: 5,
      isAffiliate: false,
      affiliatePlatform: AffiliatePlatform.homioDirect,
      estimatedDeliveryDays: 4,
      isFeatured: false,
      designStyle: 'Scandinavian Organic',
    ),
    HomeDecorItem(
      id: 'dec-004',
      title: 'Aura Fluted Travertine Marble Round Coffee Table',
      brand: 'Urban Stonecraft',
      description:
          'Monolithic organic centerpiece cut from honed Italian Roman Travertine with characteristic porous textures and a fluted columnar pedestal base.',
      category: HomeDecorCategory.furniture,
      price: 39999.0,
      originalPrice: 52000.0,
      rating: 4.7,
      reviewCount: 29,
      imageUrls: [
        'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?w=800&auto=format&fit=crop&q=80',
      ],
      specifications: {
        'Stone Type': 'Roman Beige Travertine',
        'Top Thickness': '30 mm chamfered edge',
        'Sealing': 'Nano-coated matte sealant against wine/coffee stains',
        'Base': 'Solid fluted travertine cylinder',
      },
      dimensions: '90 cm Diameter x 42 cm Height',
      material: 'Natural Italian Travertine',
      colorOptions: ['Warm Beige', 'Titanium Silver'],
      inStock: true,
      stockCount: 3,
      isAffiliate: true,
      affiliatePlatform: AffiliatePlatform.urbanLadder,
      affiliateUrl: 'https://urbanladder.com/p/aura-travertine-coffee-table',
      estimatedDeliveryDays: 7,
      isFeatured: true,
      designStyle: 'Modern Luxury',
    ),
    HomeDecorItem(
      id: 'dec-005',
      title: 'Solstice Ceramic Fluted Amphora Vases (Set of 3)',
      brand: 'Mitti Studio',
      description:
          'Artisanal stoneware ceramic trio wheel-thrown by master potters in Khurja. Finished in tactile raw stone glaze with delicate fluted micro-ribbing.',
      category: HomeDecorCategory.plantersVases,
      price: 4299.0,
      originalPrice: 5999.0,
      rating: 4.8,
      reviewCount: 94,
      imageUrls: [
        'https://images.unsplash.com/photo-1612196808214-b8e1d6145a8c?w=800&auto=format&fit=crop&q=80',
      ],
      specifications: {
        'Glaze Finish': 'Matte Chalk Textured',
        'Waterproof': '100% vitrified interior, holds fresh flowers',
        'Heights': '32 cm, 24 cm, and 16 cm',
      },
      dimensions: 'Various (Set of 3)',
      material: 'Stoneware Ceramic',
      colorOptions: ['Chalk White', 'Terracotta Dust', 'Basalt Black'],
      inStock: true,
      stockCount: 22,
      isAffiliate: true,
      affiliatePlatform: AffiliatePlatform.ikeaIndia,
      affiliateUrl: 'https://ikea.com/in/en/p/solstice-fluted-vases-set',
      estimatedDeliveryDays: 3,
      isFeatured: false,
      designStyle: 'Wabi-Sabi Artisanal',
    ),
    HomeDecorItem(
      id: 'dec-006',
      title: 'Monochrome Arches Framed Fine Art Canvas (Large 40x60 in)',
      brand: 'Galerie Lumina',
      description:
          'Giclee museum-quality archival print on 380 GSM Belgian linen canvas. Encased in a solid natural white oak floating box frame with anti-reflective plexiglass.',
      category: HomeDecorCategory.wallArt,
      price: 8999.0,
      originalPrice: 12500.0,
      rating: 4.9,
      reviewCount: 63,
      imageUrls: [
        'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=800&auto=format&fit=crop&q=80',
      ],
      specifications: {
        'Frame': 'FSC Certified White Oak Float Frame',
        'Inks': '12-color archival pigment inks (100+ yr fade resistant)',
        'Hanging Kit': 'Pre-installed heavy duty brass cleats',
      },
      dimensions: '101 cm x 152 cm (40 x 60 Inches)',
      material: 'Belgian Linen & Solid Oak',
      colorOptions: ['Natural Oak Frame', 'Black Ash Frame'],
      inStock: true,
      stockCount: 11,
      isAffiliate: true,
      affiliatePlatform: AffiliatePlatform.amazonIndia,
      affiliateUrl: 'https://amazon.in/dp/B0CXHOMIOART',
      estimatedDeliveryDays: 4,
      isFeatured: false,
      designStyle: 'Architectural Abstract',
    ),
  ];

  // -------------------------------------------------------------
  // 3. CONSTRUCTION & INTERIOR FINISH MATERIALS
  // -------------------------------------------------------------
  static final List<MaterialItem> materials = [
    MaterialItem(
      id: 'mat-001',
      title: 'UltraTech Weather Pro Microfine Waterproof Cement',
      brand: 'UltraTech',
      manufacturer: 'UltraTech Cement Ltd.',
      category: MaterialCategory.civilCement,
      retailPrice: 485.0,
      tradePrice: 425.0,
      unit: MaterialUnit.bag,
      minimumOrderQuantity: 50,
      leadTimeDays: 2,
      technicalSpecs: {
        'Grade': 'IS 1489 Part 1 Certified PPC',
        'Water Repellency': 'Hydrophobic Silane additive matrix',
        'Setting Time': 'Initial 45 mins, Final 320 mins',
        'Compressive Strength (28d)': '53+ MPa guaranteed',
      },
      certifications: ['ISI Marked', 'GreenPro Certified', 'ISO 9001:2015'],
      imageUrls: [
        'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?w=800&auto=format&fit=crop&q=80',
      ],
      inStock: true,
      stockAvailable: 2400,
      hsnCode: '25232910',
      gstPercent: 28.0,
      isVerifiedTradeGrade: true,
      originCity: 'Mumbai Plant',
      description:
          'Engineered for premium structural RCC slabs, basements, and coastal exterior plastering with maximum resistance against chloride and sulphate attack.',
    ),
    MaterialItem(
      id: 'mat-002',
      title: 'Kajaria Eternity Calacatta Gold Glazed Vitrified Tiles',
      brand: 'Kajaria',
      manufacturer: 'Kajaria Ceramics Ltd.',
      category: MaterialCategory.tilesFlooring,
      retailPrice: 115.0,
      tradePrice: 88.0,
      unit: MaterialUnit.sqft,
      minimumOrderQuantity: 500,
      leadTimeDays: 3,
      technicalSpecs: {
        'Slab Size': '1200 mm x 1800 mm (4 x 6 Feet)',
        'Thickness': '9.5 mm',
        'Finish': 'Silky Silk Matte Nano Polished',
        'Water Absorption': '< 0.05% Vitrified',
        'Surface Hardness': 'Mohs Scale 7 (Scratch Proof)',
      },
      certifications: ['ISO 13006 / EN 14411', 'CE Certified', 'GRIHA Green'],
      imageUrls: [
        'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&auto=format&fit=crop&q=80',
      ],
      inStock: true,
      stockAvailable: 12000,
      hsnCode: '69072100',
      gstPercent: 18.0,
      isVerifiedTradeGrade: true,
      originCity: 'Morbi Hub',
      description:
          'Continuous-vein Italian bookmatch marble pattern scanned from Carrara quarries. Perfect for high-traffic living rooms and designer bathroom accents.',
    ),
    MaterialItem(
      id: 'mat-003',
      title: 'Asian Paints Royale Aspira Teflon Luxury Emulsion',
      brand: 'Asian Paints',
      manufacturer: 'Asian Paints Limited',
      category: MaterialCategory.paintsFinishes,
      retailPrice: 620.0,
      tradePrice: 510.0,
      unit: MaterialUnit.liter,
      minimumOrderQuantity: 40,
      leadTimeDays: 1,
      technicalSpecs: {
        'Sheen Level': 'Soft Velvet Sheen (15-20 units @ 60°)',
        'Scrub Resistance': '> 10,000 cycles (Washable stains)',
        'VOC Level': '< 15 gm/L (Ultra Low Odour & Eco Safe)',
        'Coverage': '260-280 sq.ft per liter per coat',
      },
      certifications: ['Singapore Green Label', 'Teflon Surface Protector'],
      imageUrls: [
        'https://images.unsplash.com/photo-1562259949-e8e7689d7828?w=800&auto=format&fit=crop&q=80',
      ],
      inStock: true,
      stockAvailable: 600,
      hsnCode: '32091000',
      gstPercent: 18.0,
      isVerifiedTradeGrade: true,
      originCity: 'Bengaluru Depo',
      description:
          'Flagship interior wall paint with Teflon surface protection. Repels ink, turmeric, and grease marks with unmatched washability and crack-bridging stretch.',
    ),
    MaterialItem(
      id: 'mat-004',
      title: 'CenturyPly Club Prime Waterproof Marine Plywood (19mm)',
      brand: 'CenturyPly',
      manufacturer: 'Century Plyboards India Ltd.',
      category: MaterialCategory.plyHardware,
      retailPrice: 155.0,
      tradePrice: 128.0,
      unit: MaterialUnit.sqft,
      minimumOrderQuantity: 150,
      leadTimeDays: 2,
      technicalSpecs: {
        'Standard': 'IS:710 Marine Grade Boiling Waterproof',
        'Glue Shear Strength': '> 1450 N (Phenol Formaldehyde Resin)',
        'Borer & Termite Proof': 'ViroKill Nanotechnology treated',
        'Warranty': '30-Year Comprehensive Replacement Warranty',
      },
      certifications: ['IS:710 Bureau of Indian Standards', 'FSC Certified'],
      imageUrls: [
        'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?w=800&auto=format&fit=crop&q=80',
      ],
      inStock: true,
      stockAvailable: 4500,
      hsnCode: '44123300',
      gstPercent: 18.0,
      isVerifiedTradeGrade: true,
      originCity: 'Chennai Port Depot',
      description:
          'Gold standard for modular kitchens, vanity units, and external shutters. 72-hour boiling water test resistant with zero delamination.',
    ),
    MaterialItem(
      id: 'mat-005',
      title: 'Schneider Electric AvatarOn Smart Modular Switches',
      brand: 'Schneider Electric',
      manufacturer: 'Schneider Electric India',
      category: MaterialCategory.electricals,
      retailPrice: 280.0,
      tradePrice: 215.0,
      unit: MaterialUnit.piece,
      minimumOrderQuantity: 50,
      leadTimeDays: 2,
      technicalSpecs: {
        'Design': 'Frameless Slim Unica Cover Plate',
        'Rating': '16AX / 250V AC with soft-click mechanism',
        'Durability': '40,000 mechanical switching cycles tested',
        'Indicator': 'Subtle ice-white fluorescent locator',
      },
      certifications: ['RoHS Compliant', 'IS 3854 Indian Standard'],
      imageUrls: [
        'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&auto=format&fit=crop&q=80',
      ],
      inStock: true,
      stockAvailable: 1500,
      hsnCode: '85365090',
      gstPercent: 18.0,
      isVerifiedTradeGrade: true,
      originCity: 'Gurugram Warehouse',
      description:
          'Sleek frameless design with customizable snap-on faceplates. Flame-retardant virgin polycarbonate engineering with silver alloy contacts.',
    ),
    MaterialItem(
      id: 'mat-006',
      title: 'Kohler ModernLife Wall-Hung Rimless Smart Toilet with Slim Seat',
      brand: 'Kohler',
      manufacturer: 'Kohler India Corp.',
      category: MaterialCategory.sanitaryBath,
      retailPrice: 19800.0,
      tradePrice: 15200.0,
      unit: MaterialUnit.piece,
      minimumOrderQuantity: 4,
      leadTimeDays: 4,
      technicalSpecs: {
        'Flushing': 'Class 5 Rimless Vortex Dual Flush (3/4.5 L)',
        'Seat Cover': 'Quick-release soft-close UF slim anti-microbial seat',
        'Glaze': 'Kohler CleanCoat hydrophobic stain barrier',
        'Load Capacity': '400 kg weight tested on concealed frame',
      },
      certifications: ['WaterSense Certified', 'UPC-I Standard'],
      imageUrls: [
        'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=800&auto=format&fit=crop&q=80',
      ],
      inStock: true,
      stockAvailable: 80,
      hsnCode: '69101000',
      gstPercent: 18.0,
      isVerifiedTradeGrade: true,
      originCity: 'Jhajjar Facility',
      description:
          'Architect-preferred minimalist rimless wall-hung WC bowl. Delivers powerful sanitary rinse with 40% less water usage and zero hidden limescale corners.',
    ),
  ];

  // -------------------------------------------------------------
  // 4. PROPERTIES & RENTALS (VERIFIED)
  // -------------------------------------------------------------
  static final List<PropertyItem> properties = [
    PropertyItem(
      id: 'prop-001',
      title: 'The Sky Crest Signature Penthouse (4 BHK)',
      locality: 'Indiranagar 100ft Road',
      city: 'Bengaluru',
      state: 'Karnataka',
      price: 185000.0,
      priceSuffix: ' / month',
      listingType: PropertyListingType.rental,
      category: PropertyCategory.penthouse,
      bedrooms: 4,
      bathrooms: 5,
      carpetAreaSqFt: 3450,
      superAreaSqFt: 4200,
      furnishingStatus: 'Fully Furnished by HOMIO Studio',
      parkingSpots: 3,
      availableFrom: 'Ready to Move',
      imageUrls: [
        'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1600565193348-f74bd3c7ccdf?w=800&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&auto=format&fit=crop&q=80',
      ],
      isVastuCompliant: true,
      vastuFacing: 'North-East Facing with Morning Sun',
      reraNumber: 'PRM/KA/RERA/1251/310/PR/171015/000412',
      isHomioVerified: true,
      unlockFee: 500.0,
      isUnlocked: false,
      ownerName: 'Brigadier Arvind Menon (Retd.)',
      ownerPhone: '+91 98450 12890',
      ownerEmail: 'arvind.menon.crests@gmail.com',
      amenities: [
        'Private Heated Terrace Pool',
        'Italian Poliform Modular Kitchen',
        'Daikin VRV Central Air Conditioning',
        '100% DG Power Backup (15 kVA)',
        'Biometric Smart Keyless Entry',
        'EV High-Speed Charging Station',
      ],
      description:
          'Spectacular duplex sky villa overlooking the golf course green expanse. Designed with double-height ceiling voids, expansive wrap-around wooden deck, integrated Sonos sound zones, and automated motorized curtain systems.',
    ),
    PropertyItem(
      id: 'prop-002',
      title: 'Meadowlands Sovereign Gated Villa (5 BHK)',
      locality: 'Whitefield Prestige Boulevard',
      city: 'Bengaluru',
      state: 'Karnataka',
      price: 68500000.0,
      priceSuffix: '',
      listingType: PropertyListingType.sale,
      category: PropertyCategory.independentVilla,
      bedrooms: 5,
      bathrooms: 6,
      carpetAreaSqFt: 4800,
      superAreaSqFt: 5600,
      furnishingStatus: 'Semi-Furnished (Built-in Wardrobes)',
      parkingSpots: 4,
      availableFrom: 'Immediate Registration',
      imageUrls: [
        'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&auto=format&fit=crop&q=80',
      ],
      isVastuCompliant: true,
      vastuFacing: 'East Facing Entrance',
      reraNumber: 'PRM/KA/RERA/1251/446/PR/200122/003211',
      isHomioVerified: true,
      unlockFee: 500.0,
      isUnlocked: true, // Unlocked mock demo
      ownerName: 'Dr. Shalini Reddy',
      ownerPhone: '+91 99001 77654',
      ownerEmail: 'dr.shalinireddy@apollohealth.org',
      amenities: [
        'Private Japanese Zen Garden',
        'Thyssenkrupp Home Hydraulic Elevator',
        'Solar Net-Metering 10kW System',
        'Home Cinema Room with 4K Acoustic Panels',
        'Rainwater Harvesting & RO Treatment Plant',
      ],
      description:
          'Bespoke modern architectural masterpiece situated in Bangalore premier NRI enclave. Includes German Schuco triple-glazed acoustic windows, custom marble staircases, and 24/7 security cordon.',
    ),
    PropertyItem(
      id: 'prop-003',
      title: 'Urban Serenade Designer 3 BHK Apartment',
      locality: 'Koramangala 4th Block',
      city: 'Bengaluru',
      state: 'Karnataka',
      price: 85000.0,
      priceSuffix: ' / month',
      listingType: PropertyListingType.rental,
      category: PropertyCategory.luxuryApartment,
      bedrooms: 3,
      bathrooms: 3,
      carpetAreaSqFt: 1850,
      superAreaSqFt: 2200,
      furnishingStatus: 'Fully Furnished Scandinavian Chic',
      parkingSpots: 2,
      availableFrom: '1st of Next Month',
      imageUrls: [
        'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=800&auto=format&fit=crop&q=80',
      ],
      isVastuCompliant: true,
      vastuFacing: 'North Facing',
      reraNumber: 'PRM/KA/RERA/1251/310/PR/180516/001784',
      isHomioVerified: true,
      unlockFee: 500.0,
      isUnlocked: false,
      ownerName: 'Vikramaditya Rao',
      ownerPhone: '+91 97402 33411',
      ownerEmail: 'v.rao.investments@outlook.com',
      amenities: [
        'Clubhouse & Rooftop Infinity Pool',
        'Fully equipped Technogym Fitness Suite',
        'High-speed Fiber Optic Dedicated Line',
        'Direct Access to ST Bed Park',
      ],
      description:
          'Quiet corner apartment bathed in natural daylight. Features chevron oak wooden floors, bespoke designer brass hardware, Liebherr integrated refrigerator, and private maid utility balcony.',
    ),
    PropertyItem(
      id: 'prop-004',
      title: 'Skyline Atelier Commercial Creative Studio',
      locality: 'Jubilee Hills Road No. 36',
      city: 'Hyderabad',
      state: 'Telangana',
      price: 140000.0,
      priceSuffix: ' / month',
      listingType: PropertyListingType.commercial,
      category: PropertyCategory.studioApartment,
      bedrooms: 0,
      bathrooms: 2,
      carpetAreaSqFt: 2100,
      superAreaSqFt: 2500,
      furnishingStatus: 'Plug & Play Loft Office',
      parkingSpots: 3,
      availableFrom: 'Immediate',
      imageUrls: [
        'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&auto=format&fit=crop&q=80',
      ],
      isVastuCompliant: true,
      vastuFacing: 'North-West Facing',
      reraNumber: 'TG/RERA/HYD/COMM/2023/889',
      isHomioVerified: true,
      unlockFee: 500.0,
      isUnlocked: false,
      ownerName: 'Sanjay Chunduru',
      ownerPhone: '+91 98855 66782',
      ownerEmail: 'sanjay@hyderabadproperties.co',
      amenities: [
        'Exposed Concrete & Industrial Brick Aesthetics',
        'Boardroom with 75-inch 4K Presentation Screen',
        'Artisanal Coffee Bar & Pantry Counter',
        'Tier-3 Server Room with Dedicated Cooling',
      ],
      description:
          'Prime boutique commercial studio on Hyderabad prime boulevard. Ideal for architecture firms, creative tech agencies, or venture studios seeking high street presence.',
    ),
  ];

  // -------------------------------------------------------------
  // 5. LABOUR & VERIFIED ON-DEMAND TRADES
  // -------------------------------------------------------------
  static final List<LabourWorkerProfile> labourWorkers = [
    LabourWorkerProfile(
      id: 'wkr-001',
      name: 'Ustad Mohammed Rafiq',
      trade: LabourTradeCategory.masterCarpenter,
      skillLevel: LabourSkillLevel.masterCraftsman,
      dailyWage: 1650.0,
      hourlyRate: 250.0,
      rating: 4.95,
      reviewCount: 164,
      jobsCompleted: 340,
      yearsExperience: 18,
      city: 'Bengaluru',
      locality: 'Shivajinagar / Indiranagar',
      photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&auto=format&fit=crop&q=80',
      isBackgroundVerified: true,
      isPoliceVerified: true,
      isInsuranceCovered: true,
      languages: ['Hindi', 'Urdu', 'Kannada', 'English'],
      toolsOwned: ['Festool Track Saw', 'Makita Plunge Router', 'Dewalt Laser Level', 'Bosch Cordless Drills'],
      certifications: ['National Skill Development Council (NSDC) Level 5', 'HOMIO Master Artisan Certified'],
      availabilityStatus: 'Available Tomorrow',
      bio:
          '3rd-generation timber craftsman specializing in bespoke curved fluting, seamless concealed soft-close hinges, veneer press jointing, and solid teak temple structures.',
      phone: '+91 98451 90234',
    ),
    LabourWorkerProfile(
      id: 'wkr-002',
      name: 'Rameshwar Mahato',
      trade: LabourTradeCategory.plumber,
      skillLevel: LabourSkillLevel.masterCraftsman,
      dailyWage: 1450.0,
      hourlyRate: 220.0,
      rating: 4.88,
      reviewCount: 122,
      jobsCompleted: 280,
      yearsExperience: 14,
      city: 'Bengaluru',
      locality: 'HSR Layout / Bellandur',
      photoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=800&auto=format&fit=crop&q=80',
      isBackgroundVerified: true,
      isPoliceVerified: true,
      isInsuranceCovered: true,
      languages: ['Hindi', 'Bengali', 'Kannada'],
      toolsOwned: ['Rothenberger Pipe Pressing Tool', 'Hydrostatic Pressure Testing Pump', 'Digital Bore Camera'],
      certifications: ['Indian Plumbing Association (IPA) Certified', 'Grohe & Kohler Authorized Installer'],
      availabilityStatus: 'Available Immediately',
      bio:
          'Expert in Viega CPVC/PEX multi-layer composite piping, concealed cistern wall framing, rain-shower mixer calibrations, and zero-leakage sump booster pumps.',
      phone: '+91 97312 88701',
    ),
    LabourWorkerProfile(
      id: 'wkr-003',
      name: 'Karthik Sunderam',
      trade: LabourTradeCategory.electrician,
      skillLevel: LabourSkillLevel.masterCraftsman,
      dailyWage: 1550.0,
      hourlyRate: 240.0,
      rating: 4.92,
      reviewCount: 198,
      jobsCompleted: 410,
      yearsExperience: 12,
      city: 'Bengaluru',
      locality: 'Whitefield / Marathahalli',
      photoUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=800&auto=format&fit=crop&q=80',
      isBackgroundVerified: true,
      isPoliceVerified: true,
      isInsuranceCovered: true,
      languages: ['English', 'Tamil', 'Kannada', 'Hindi'],
      toolsOwned: ['Fluke True-RMS Multimeter', 'Hikmicro Thermal Camera', 'Schneider Relay Programmers'],
      certifications: ['Govt Licensed Electrical Supervisor (Class 1)', 'KNX Home Automation Specialist'],
      availabilityStatus: 'Booked Today (Free Saturday)',
      bio:
          'Specialist in high-end residential electrical load balancing, smart home DALI/KNX lighting automation, home theatre conduit routing, and solar inverter integration.',
      phone: '+91 99401 55623',
    ),
    LabourWorkerProfile(
      id: 'wkr-004',
      name: 'Gurpreet Singh',
      trade: LabourTradeCategory.painter,
      skillLevel: LabourSkillLevel.skilledWorker,
      dailyWage: 1350.0,
      hourlyRate: 200.0,
      rating: 4.85,
      reviewCount: 95,
      jobsCompleted: 190,
      yearsExperience: 9,
      city: 'Bengaluru',
      locality: 'JP Nagar / Jayanagar',
      photoUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=800&auto=format&fit=crop&q=80',
      isBackgroundVerified: true,
      isPoliceVerified: true,
      isInsuranceCovered: true,
      languages: ['Punjabi', 'Hindi', 'English'],
      toolsOwned: ['Graco Airless Paint Sprayer', 'Festool Dustless Wall Sander', 'Elcometer Thickness Gauge'],
      certifications: ['Asian Paints Certified Color Idea Master', 'PU Italian Polish Specialist'],
      availabilityStatus: 'Available Immediately',
      bio:
          'Flawless surface preparation specialist with dust-free orbital mechanical sanding. Expert in Italian Sirca PU wood polish, metallic lime plaster, and concrete textures.',
      phone: '+91 98140 33490',
    ),
  ];

  // Standardized service packages
  static final List<LabourServicePackage> servicePackages = [
    LabourServicePackage(
      id: 'pkg-001',
      title: 'Complete Modular Kitchen Installation & Alignment',
      trade: LabourTradeCategory.masterCarpenter,
      shortDescription: 'Precision fitting of base/wall carcases, Blum hinges, quartz sink cutouts and appliances.',
      scopeChecklist: [
        'Laser level verification of all base cabinet carcases',
        'Soft-close tandem box drawer alignment with 1mm tolerance',
        'Quartz/granite under-mount sink cutout preparation',
        'Concealed chimney ducting and hob gasket sealing',
        '30-day post-installation re-tensioning inspection',
      ],
      fixedPrice: 6499.0,
      estimatedHours: 12,
      isPopular: true,
      inclusions: ['2 Master Carpenters for full day', 'All hardware leveling consumables'],
      exclusions: ['Raw stone or quartz slab (Customer provided)'],
    ),
    LabourServicePackage(
      id: 'pkg-002',
      title: 'Full Apartment Electrical Safety & Load Audit',
      trade: LabourTradeCategory.electrician,
      shortDescription: 'Thermal imaging scan of DB board, earth pit resistance testing & surge protection review.',
      scopeChecklist: [
        'FLIR Thermal infrared scan for hot connection terminals',
        'Megger insulation resistance test across all branch circuits',
        'Earth pit electrode resistance measurement (< 2.0 Ohms)',
        'MCB/RCCB tripping sensitivity verification',
        'Formal stamp-certified electrical safety report',
      ],
      fixedPrice: 2899.0,
      estimatedHours: 4,
      isPopular: false,
      inclusions: ['Licensed Supervisor visit', 'Formal digital report with thermal photos'],
      exclusions: ['Replacement of burnt contactors/cables'],
    ),
    LabourServicePackage(
      id: 'pkg-003',
      title: 'Bathroom Concealed Plumbing & Fixture Overhaul',
      trade: LabourTradeCategory.plumber,
      shortDescription: 'Replacement of diverter cartridges, angle valves, shower channels & wall-hung cistern setup.',
      scopeChecklist: [
        'Diverter cartridge descaling and ceramic disc inspection',
        'Installation of concealed wall-hung toilet cistern frame',
        'Acoustic silicone vibration dampening on water inlet pipes',
        '4-bar pressure retention testing for 2 hours',
      ],
      fixedPrice: 3899.0,
      estimatedHours: 6,
      isPopular: true,
      inclusions: ['Master Plumber + Assistant', 'Pressure gauge equipment test'],
      exclusions: ['Tiles breakage & re-tiling if internal pipe bursts'],
    ),
    LabourServicePackage(
      id: 'pkg-004',
      title: 'Dust-Free High-End Accent Wall Texture Application',
      trade: LabourTradeCategory.painter,
      shortDescription: 'Stucco Italiano, Travertine Lime Plaster or Metallic Raw Concrete texture application.',
      scopeChecklist: [
        'Floor and furniture plastic masking with 3M painters tape',
        'Dust-free mechanical orbital vacuum sanding',
        'Acrylic base primer coat + 2 coats imported Italian texture',
        'Protective clear matte hydrophobic protective glaze coat',
      ],
      fixedPrice: 7999.0,
      estimatedHours: 10,
      isPopular: false,
      inclusions: ['Up to 150 sq.ft wall area coverage', 'All Italian stucco texture compounds'],
      exclusions: ['Civil plaster replastering if wall has active seepage'],
    ),
  ];

  // -------------------------------------------------------------
  // 6. ORDERS & TRANSACTIONS
  // -------------------------------------------------------------
  static final List<MarketplaceOrder> orders = [
    MarketplaceOrder(
      id: 'ord-8921',
      orderNumber: 'HOM-2026-8921',
      createdAt: DateTime(2026, 9, 8, 14, 30),
      status: MarketplaceOrderStatus.dispatched,
      items: [
        MarketplaceOrderItem(
          id: 'item-101',
          productId: 'dec-001',
          productTitle: 'Aethel Mid-Century Brass Sputnik Chandelier',
          category: MarketplaceCategory.homeDecor,
          unitPrice: 18499.0,
          quantity: 1,
          subtotal: 18499.0,
          imageUrl: 'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=800&auto=format&fit=crop&q=80',
          variantDescription: 'Brushed Brass / 12-Globe G9',
        ),
        MarketplaceOrderItem(
          id: 'item-102',
          productId: 'dec-005',
          productTitle: 'Solstice Ceramic Fluted Amphora Vases (Set of 3)',
          category: MarketplaceCategory.homeDecor,
          unitPrice: 4299.0,
          quantity: 1,
          subtotal: 4299.0,
          imageUrl: 'https://images.unsplash.com/photo-1612196808214-b8e1d6145a8c?w=800&auto=format&fit=crop&q=80',
          variantDescription: 'Chalk White Stone Glaze',
        ),
      ],
      subtotal: 22798.0,
      taxGst: 4103.64,
      shippingCost: 0.0,
      discountAmount: 1000.0,
      grandTotal: 25901.64,
      deliveryAddress: 'Penthouse B-1402, Embassy Boulevard, Bellary Road, Bengaluru 560064',
      trackingNumber: 'BLUEDART-8829104',
      trackingCarrier: 'BlueDart Express Premium Air',
      estimatedDeliveryDate: DateTime(2026, 9, 13),
      invoiceUrl: 'https://homio.in/invoices/hom-2026-8921.pdf',
      paymentMethod: 'HDFC Corporate Card (ending 9102)',
      paymentTransactionId: 'TXN-HDFC-9918237190',
    ),
    MarketplaceOrder(
      id: 'ord-8714',
      orderNumber: 'HOM-2026-8714',
      createdAt: DateTime(2026, 8, 22, 10, 15),
      status: MarketplaceOrderStatus.delivered,
      items: [
        MarketplaceOrderItem(
          id: 'item-201',
          productId: 'dig-001',
          productTitle: 'Vastu Shastra Comprehensive Blueprints',
          category: MarketplaceCategory.digitalProducts,
          unitPrice: 1499.0,
          quantity: 1,
          subtotal: 1499.0,
          imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&auto=format&fit=crop&q=80',
          variantDescription: 'PDF + DWG Vector Bundle (Instant Download)',
        ),
      ],
      subtotal: 1499.0,
      taxGst: 269.82,
      shippingCost: 0.0,
      discountAmount: 0.0,
      grandTotal: 1768.82,
      deliveryAddress: 'Digital Download (Linked to Client Account: rahul.mehta@gmail.com)',
      trackingNumber: 'INSTANT-VAULT-ACCESS',
      trackingCarrier: 'HOMIO Cloud Vault',
      estimatedDeliveryDate: DateTime(2026, 8, 22),
      invoiceUrl: 'https://homio.in/invoices/hom-2026-8714.pdf',
      paymentMethod: 'UPI (rahul@okaxis)',
      paymentTransactionId: 'UPI-982736192837',
    ),
    MarketplaceOrder(
      id: 'ord-8510',
      orderNumber: 'HOM-2026-8510',
      createdAt: DateTime(2026, 8, 5, 16, 45),
      status: MarketplaceOrderStatus.delivered,
      items: [
        MarketplaceOrderItem(
          id: 'item-301',
          productId: 'mat-002',
          productTitle: 'Kajaria Eternity Calacatta Gold Glazed Vitrified Tiles',
          category: MarketplaceCategory.materials,
          unitPrice: 88.0,
          quantity: 600,
          subtotal: 52800.0,
          imageUrl: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&auto=format&fit=crop&q=80',
          variantDescription: 'Trade Pricing (600 sq.ft batch / Silk Matte)',
        ),
      ],
      subtotal: 52800.0,
      taxGst: 9504.0,
      shippingCost: 1500.0,
      discountAmount: 2500.0,
      grandTotal: 61304.0,
      deliveryAddress: 'Site #42, Ferns Habitat, Doddanekkundi, Bengaluru 560037',
      trackingNumber: 'VRL-LOGISTICS-77192',
      trackingCarrier: 'VRL Heavy Freight',
      estimatedDeliveryDate: DateTime(2026, 8, 8),
      invoiceUrl: 'https://homio.in/invoices/hom-2026-8510.pdf',
      paymentMethod: 'NEFT Bank Transfer',
      paymentTransactionId: 'NEFT-ICICI-00918237',
    ),
  ];

  // Labour Booking Records
  static final List<LabourBookingRecord> labourBookings = [
    LabourBookingRecord(
      id: 'lbk-001',
      bookingNumber: 'HOM-SRV-412',
      workerId: 'wkr-001',
      workerName: 'Ustad Mohammed Rafiq',
      workerPhoto: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&auto=format&fit=crop&q=80',
      trade: LabourTradeCategory.masterCarpenter,
      serviceTitle: 'Modular Kitchen Installation & Alignment',
      scheduledDate: DateTime(2026, 9, 15),
      timeSlot: '09:00 AM - 05:00 PM',
      status: BookingStatus.workerAssigned,
      totalAmount: 6499.0,
      siteAddress: 'Flat 902, Sobha Iris, Outer Ring Road, Bengaluru',
      specialInstructions: 'Blum soft close lift-up aventos mechanisms require calibration.',
      createdAt: DateTime(2026, 9, 10),
    ),
    LabourBookingRecord(
      id: 'lbk-002',
      bookingNumber: 'HOM-SRV-398',
      workerId: 'wkr-003',
      workerName: 'Karthik Sunderam',
      workerPhoto: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=800&auto=format&fit=crop&q=80',
      trade: LabourTradeCategory.electrician,
      serviceTitle: 'Full Apartment Electrical Safety & Load Audit',
      scheduledDate: DateTime(2026, 8, 29),
      timeSlot: '11:00 AM - 03:00 PM',
      status: BookingStatus.completed,
      totalAmount: 2899.0,
      siteAddress: 'Villa 14, Prestige Silver Oak, Whitefield, Bengaluru',
      specialInstructions: 'Main 63A RCCB was tripping during heavy monsoon rains.',
      createdAt: DateTime(2026, 8, 25),
    ),
  ];
}
