import 'admin_models.dart';

class AdminMockData {
  // ==========================================================================
  // 1. USERS & RBAC MOCK DATA
  // ==========================================================================

  static final List<AdminDepartment> departments = [
    const AdminDepartment(
      id: 'dept_sales',
      code: 'DEP-SLS',
      name: 'Sales & Growth',
      description: 'Lead generation, telecalling, client consultations, and deal conversions',
      headOfDepartment: 'Vikramaditya Singhania',
      activeTeamsCount: 3,
      activeEmployeesCount: 14,
    ),
    const AdminDepartment(
      id: 'dept_design',
      code: 'DEP-DSG',
      name: 'Design & Architecture',
      description: 'Spatial planning, 3D visualizations, material boards, and drawing approvals',
      headOfDepartment: 'Ar. Ananya Deshmukh',
      activeTeamsCount: 2,
      activeEmployeesCount: 10,
    ),
    const AdminDepartment(
      id: 'dept_execution',
      code: 'DEP-EXE',
      name: 'Projects & Civil Execution',
      description: 'Site operations, contractor supervisor, QA audits, and milestone completion',
      headOfDepartment: 'Er. Rajeshwar Rao',
      activeTeamsCount: 4,
      activeEmployeesCount: 18,
    ),
    const AdminDepartment(
      id: 'dept_procurement',
      code: 'DEP-PRC',
      name: 'Procurement & Supply Chain',
      description: 'Vendor RFQs, purchase orders, factory batching, and logistics dispatch',
      headOfDepartment: 'Sunil Mehta',
      activeTeamsCount: 2,
      activeEmployeesCount: 6,
    ),
    const AdminDepartment(
      id: 'dept_accounts',
      code: 'DEP-ACC',
      name: 'Finance & Accounting',
      description: 'Client billing, contractor disbursements, margin audit, and tax compliance',
      headOfDepartment: 'Pooja Agarwal (CA)',
      activeTeamsCount: 1,
      activeEmployeesCount: 5,
    ),
    const AdminDepartment(
      id: 'dept_aftersales',
      code: 'DEP-AFT',
      name: 'After-Sales & Warranty Hub',
      description: 'Customer retention, snag ticketing, annual maintenance contracts (AMC)',
      headOfDepartment: 'Deepak Nambiar',
      activeTeamsCount: 1,
      activeEmployeesCount: 4,
    ),
  ];

  static final List<AdminTeam> teams = [
    const AdminTeam(
      id: 'team_sls_closer',
      code: 'TM-CLS-01',
      name: 'High-Ticket Deal Closers',
      departmentId: 'dept_sales',
      departmentName: 'Sales & Growth',
      teamLead: 'Vikramaditya Singhania',
      description: 'Senior closers managing ₹40L+ turnkey luxury villa and penthouse projects',
      memberNames: ['Vikramaditya Singhania', 'Aditi Sharma', 'Rohan Verma'],
    ),
    const AdminTeam(
      id: 'team_sls_tele',
      code: 'TM-TEL-02',
      name: 'Digital Inbound & SDR Squad',
      departmentId: 'dept_sales',
      departmentName: 'Sales & Growth',
      teamLead: 'Priya Sundaram',
      description: 'Fast response telecallers handling Meta, Google and WhatsApp inquiries',
      memberNames: ['Priya Sundaram', 'Kavita Menon', 'Arjun Kapoor', 'Sneha Reddy'],
    ),
    const AdminTeam(
      id: 'team_dsg_3d',
      code: 'TM-DSG-3D',
      name: '3D Render & VR Studio',
      departmentId: 'dept_design',
      departmentName: 'Design & Architecture',
      teamLead: 'Farhan Akhtar',
      description: 'High-fidelity photorealistic renders, Lumion walkthroughs, and VR tours',
      memberNames: ['Farhan Akhtar', 'Tanya Sen', 'Manoj Gowda'],
    ),
    const AdminTeam(
      id: 'team_exe_villa',
      code: 'TM-EXE-VIL',
      name: 'Turnkey Civil & Fitout Squad',
      departmentId: 'dept_execution',
      departmentName: 'Projects & Civil Execution',
      teamLead: 'Karthik Raja',
      description: 'Site management for active luxury residential execution projects',
      memberNames: ['Karthik Raja', 'Sunita Patil', 'Dinesh Kumar', 'Harish Babu'],
    ),
  ];

  static final List<String> allHomioModules = [
    'Dashboard',
    'CRM & Leads',
    'Sales Funnels',
    'Calendar & Meetings',
    'Tasks & Follow-ups',
    'Projects Overview',
    'Execution & Site Visits',
    'Quotations & Estimator',
    'Designs & 3D Vault',
    'Procurement & RFQs',
    'Vendors & Purchase Orders',
    'Accounting & Invoices',
    'HRMS & Attendance',
    'Service & Labour Directory',
    'Customer Communication',
    'Reports & Analytics',
    'AI Studio & WhatsApp Bot',
    'Marketplace Operations',
    'System Administration',
  ];

  static List<ModulePermissionMatrix> generatePermissionsForRole(String roleName) {
    final isSuper = roleName.contains('Admin');
    final isSales = roleName.contains('Sales') || roleName.contains('Telecaller') || roleName.contains('Closer');
    final isDesign = roleName.contains('Designer') || roleName.contains('3D');
    final isExec = roleName.contains('Execution') || roleName.contains('Project Manager') || roleName.contains('Site');
    final isFinance = roleName.contains('Finance') || roleName.contains('Accountant');

    return allHomioModules.map((module) {
      bool canView = isSuper;
      bool canCreate = isSuper;
      bool canEdit = isSuper;
      bool canDelete = isSuper;
      bool canApprove = isSuper;
      bool canExport = isSuper;
      bool canPay = isSuper && isFinance;
      DataScopeType scope = DataScopeType.organization;

      if (module == 'Dashboard') {
        canView = true;
      } else if (module.contains('CRM') || module.contains('Sales') || module.contains('Calendar') || module.contains('Tasks')) {
        if (isSales || isSuper) {
          canView = true;
          canCreate = true;
          canEdit = true;
          canExport = isSuper || roleName.contains('Head');
          canApprove = roleName.contains('Head');
          scope = roleName.contains('Telecaller') ? DataScopeType.myRecords : DataScopeType.myDepartment;
        }
      } else if (module.contains('Quotations')) {
        if (isSales || isFinance || isSuper) {
          canView = true;
          canCreate = true;
          canEdit = true;
          canApprove = roleName.contains('Head') || isFinance || isSuper;
          canExport = true;
          scope = DataScopeType.myDepartment;
        }
      } else if (module.contains('Designs')) {
        if (isDesign || isExec || isSuper) {
          canView = true;
          canCreate = isDesign || isSuper;
          canEdit = isDesign || isSuper;
          canApprove = isSuper || roleName.contains('Head');
        }
      } else if (module.contains('Projects') || module.contains('Execution')) {
        if (isExec || isSuper) {
          canView = true;
          canCreate = true;
          canEdit = true;
          canApprove = roleName.contains('Manager') || isSuper;
          scope = DataScopeType.assignedProjects;
        }
      } else if (module.contains('Accounting') || module.contains('Procurement')) {
        if (isFinance || isSuper) {
          canView = true;
          canCreate = true;
          canEdit = true;
          canApprove = true;
          canPay = true;
          scope = DataScopeType.organization;
        }
      }

      final Map<GranularAction, bool> actions = {
        GranularAction.view: canView,
        GranularAction.create: canCreate,
        GranularAction.edit: canEdit,
        GranularAction.delete: canDelete,
        GranularAction.approve: canApprove,
        GranularAction.reject: canApprove,
        GranularAction.assign: canEdit,
        GranularAction.export: canExport,
        GranularAction.download: canView,
        GranularAction.share: canView,
        GranularAction.pay: canPay,
        GranularAction.requestPayment: canEdit,
        GranularAction.sendCommunication: canEdit,
        GranularAction.configure: isSuper,
      };

      return ModulePermissionMatrix(
        moduleId: module.toLowerCase().replaceAll(RegExp(r'[^a-z0-9]'), '_'),
        moduleName: module,
        category: 'Core Operations',
        actions: actions,
        dataScope: scope,
        phoneMasked: roleName.contains('Telecaller') || roleName.contains('Junior'),
        marginMasked: !isSuper && !isFinance && !roleName.contains('Head'),
      );
    }).toList();
  }

  static final List<AdminRole> roles = [
    AdminRole(
      id: 'role_super_admin',
      roleCode: 'ROL-SAD-01',
      roleName: 'Enterprise Super Admin',
      departmentId: 'dept_sales',
      departmentName: 'Corporate Management',
      description: 'Unrestricted master access across all Homio entities, financial approvals, API keys, and RBAC policies',
      approvalAuthority: 'Unlimited (Organization Ceilings)',
      defaultScope: DataScopeType.organization,
      usersAssignedCount: 2,
      permissions: generatePermissionsForRole('Enterprise Super Admin'),
      createdAt: DateTime(2025, 1, 1),
      updatedAt: DateTime(2026, 8, 15),
    ),
    AdminRole(
      id: 'role_sales_head',
      roleCode: 'ROL-SLS-01',
      roleName: 'Sales Head / Commercial VP',
      departmentId: 'dept_sales',
      departmentName: 'Sales & Growth',
      description: 'Directs sales pipelines, authorizes quotation discounts up to 10%, reallocates high-value leads, monitors CPL',
      approvalAuthority: 'Tier 3 (Quotations up to ₹1.5 Cr, Discounts <= 10%)',
      defaultScope: DataScopeType.myDepartment,
      usersAssignedCount: 1,
      permissions: generatePermissionsForRole('Sales Head'),
      createdAt: DateTime(2025, 1, 10),
      updatedAt: DateTime(2026, 8, 20),
    ),
    AdminRole(
      id: 'role_deal_closer',
      roleCode: 'ROL-DCL-02',
      roleName: 'Senior Deal Closer',
      departmentId: 'dept_sales',
      departmentName: 'Sales & Growth',
      description: 'Field meetings, detailed quotation presentations, client negotiation, booking advances',
      approvalAuthority: 'Tier 1 (Up to ₹25,000 spot discount)',
      defaultScope: DataScopeType.myTeam,
      usersAssignedCount: 4,
      permissions: generatePermissionsForRole('Senior Deal Closer'),
      createdAt: DateTime(2025, 2, 1),
      updatedAt: DateTime(2026, 7, 10),
    ),
    AdminRole(
      id: 'role_telecaller',
      roleCode: 'ROL-TEL-03',
      roleName: 'Inbound Telecaller / SDR',
      departmentId: 'dept_sales',
      departmentName: 'Sales & Growth',
      description: 'First customer touchpoint, qualification calls, meeting scheduling. Restricted to assigned prospects',
      approvalAuthority: 'None (Requires Supervisor Approval)',
      defaultScope: DataScopeType.myRecords,
      usersAssignedCount: 6,
      permissions: generatePermissionsForRole('Junior Telecaller'),
      createdAt: DateTime(2025, 2, 15),
      updatedAt: DateTime(2026, 9, 1),
    ),
    AdminRole(
      id: 'role_proj_manager',
      roleCode: 'ROL-PM-01',
      roleName: 'Senior Project Manager (PM)',
      departmentId: 'dept_execution',
      departmentName: 'Projects & Civil Execution',
      description: 'Overall site delivery, contractor work approvals, snag resolution, weekly milestone sign-offs',
      approvalAuthority: 'Tier 2 (Material indent up to ₹2.5L)',
      defaultScope: DataScopeType.assignedProjects,
      usersAssignedCount: 5,
      permissions: generatePermissionsForRole('Project Manager'),
      createdAt: DateTime(2025, 1, 15),
      updatedAt: DateTime(2026, 8, 28),
    ),
    AdminRole(
      id: 'role_designer',
      roleCode: 'ROL-DSG-01',
      roleName: 'Principal Interior Designer',
      departmentId: 'dept_design',
      departmentName: 'Design & Architecture',
      description: 'Spatial layouts, mood boards, client presentations, 2D working drawings and finish schedules',
      approvalAuthority: 'Design Document Approvals',
      defaultScope: DataScopeType.assignedProjects,
      usersAssignedCount: 4,
      permissions: generatePermissionsForRole('Designer'),
      createdAt: DateTime(2025, 2, 10),
      updatedAt: DateTime(2026, 8, 12),
    ),
    AdminRole(
      id: 'role_finance_mgr',
      roleCode: 'ROL-FIN-01',
      roleName: 'Finance & Accounts Controller',
      departmentId: 'dept_accounts',
      departmentName: 'Finance & Accounting',
      description: 'Tax invoices, ledger auditing, vendor payments, milestone disbursements, and bank reconciliation',
      approvalAuthority: 'Tier 3 (Financial disbursements up to ₹10L)',
      defaultScope: DataScopeType.organization,
      usersAssignedCount: 2,
      permissions: generatePermissionsForRole('Finance'),
      createdAt: DateTime(2025, 1, 5),
      updatedAt: DateTime(2026, 9, 5),
    ),
  ];

  static final List<AdminUser> users = [
    AdminUser(
      id: 'usr_001',
      employeeId: 'HOM-1001',
      firstName: 'Vikramaditya',
      middleName: 'Raj',
      lastName: 'Singhania',
      displayName: 'Vikram Singhania',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
      jobTitle: 'Vice President of Commercial Sales',
      employmentType: EmploymentType.fullTime,
      accountStatus: UserAccountStatus.active,
      primaryMobile: '+91 98201 55432',
      alternateMobile: '+91 98201 99887',
      email: 'vikram.singhania@homio.in',
      address: 'Penthouse 1402, Oberoi Sky Heights, Worli',
      city: 'Mumbai',
      state: 'Maharashtra',
      postalCode: '400018',
      departmentId: 'dept_sales',
      departmentName: 'Sales & Growth',
      teamId: 'team_sls_closer',
      teamName: 'High-Ticket Deal Closers',
      roleId: 'role_sales_head',
      roleName: 'Sales Head / Commercial VP',
      workLocation: 'Homio Mumbai HQ (Bandra Kurla Complex)',
      joiningDate: DateTime(2024, 3, 1),
      accessScope: DataScopeType.myDepartment,
      approvalAuthority: 'Tier 3 (Quotations up to ₹1.5 Cr, Discounts <= 10%)',
      lastLogin: DateTime(2026, 9, 11, 11, 24),
      allowedModules: ['Dashboard', 'CRM & Leads', 'Sales Funnels', 'Quotations & Estimator', 'Reports & Analytics'],
      activityHistory: [
        UserActivityLog(
          id: 'act_01',
          actionTitle: 'Role Modified',
          actionCategory: 'RBAC Access',
          details: 'Assigned Tier 3 Quotation Discount Approval privilege',
          performedBy: 'Super Admin',
          timestamp: DateTime(2026, 8, 20, 14, 10),
        ),
        UserActivityLog(
          id: 'act_02',
          actionTitle: 'Login Verified',
          actionCategory: 'Security',
          details: 'Authenticated via 2FA Hardware Token from 103.22.45.18',
          performedBy: 'System Auth',
          timestamp: DateTime(2026, 9, 11, 11, 24),
        ),
      ],
    ),
    AdminUser(
      id: 'usr_002',
      employeeId: 'HOM-1014',
      firstName: 'Priya',
      lastName: 'Sundaram',
      displayName: 'Priya Sundaram',
      avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150',
      jobTitle: 'Inbound Telecalling Team Lead',
      employmentType: EmploymentType.fullTime,
      accountStatus: UserAccountStatus.active,
      primaryMobile: '+91 97412 88901',
      email: 'priya.sundaram@homio.in',
      address: 'Flat 304, Green Glen Layout, Bellandur',
      city: 'Bengaluru',
      state: 'Karnataka',
      postalCode: '560103',
      departmentId: 'dept_sales',
      departmentName: 'Sales & Growth',
      teamId: 'team_sls_tele',
      teamName: 'Digital Inbound & SDR Squad',
      roleId: 'role_telecaller',
      roleName: 'Inbound Telecaller / SDR',
      reportingManagerId: 'usr_001',
      reportingManagerName: 'Vikramaditya Singhania',
      workLocation: 'Bengaluru Innovation Center (Indiranagar)',
      joiningDate: DateTime(2024, 7, 15),
      accessScope: DataScopeType.myTeam,
      approvalAuthority: 'None',
      lastLogin: DateTime(2026, 9, 11, 9, 15),
      allowedModules: ['Dashboard', 'CRM & Leads', 'Calendar & Meetings', 'Tasks & Follow-ups'],
      activityHistory: [
        UserActivityLog(
          id: 'act_03',
          actionTitle: 'Phone Masking Enforced',
          actionCategory: 'Privacy Compliance',
          details: 'Restricted direct export of raw prospect contact lists',
          performedBy: 'Compliance Admin',
          timestamp: DateTime(2026, 9, 1, 10, 0),
        ),
      ],
    ),
    AdminUser(
      id: 'usr_003',
      employeeId: 'HOM-1022',
      firstName: 'Ar. Ananya',
      lastName: 'Deshmukh',
      displayName: 'Ar. Ananya Deshmukh',
      avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150',
      jobTitle: 'Principal Architect & Design Director',
      employmentType: EmploymentType.fullTime,
      accountStatus: UserAccountStatus.active,
      primaryMobile: '+91 99304 44321',
      email: 'ananya.deshmukh@homio.in',
      address: 'Studio 10, Koregaon Park Plaza',
      city: 'Pune',
      state: 'Maharashtra',
      postalCode: '411001',
      departmentId: 'dept_design',
      departmentName: 'Design & Architecture',
      teamId: 'team_dsg_3d',
      teamName: '3D Render & VR Studio',
      roleId: 'role_designer',
      roleName: 'Principal Interior Designer',
      workLocation: 'Pune Design Hub',
      joiningDate: DateTime(2024, 1, 10),
      accessScope: DataScopeType.myDepartment,
      approvalAuthority: 'Design Document Approvals',
      lastLogin: DateTime(2026, 9, 10, 17, 45),
      allowedModules: ['Dashboard', 'Designs & 3D Vault', 'Projects Overview', 'AI Studio & WhatsApp Bot'],
      activityHistory: [],
    ),
    AdminUser(
      id: 'usr_004',
      employeeId: 'HOM-1035',
      firstName: 'Er. Rajeshwar',
      lastName: 'Rao',
      displayName: 'Rajeshwar Rao',
      avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
      jobTitle: 'Vice President of Civil Execution',
      employmentType: EmploymentType.fullTime,
      accountStatus: UserAccountStatus.active,
      primaryMobile: '+91 94401 22890',
      email: 'rajeshwar.rao@homio.in',
      address: 'House 88, Jubilee Hills Phase 3',
      city: 'Hyderabad',
      state: 'Telangana',
      postalCode: '500033',
      departmentId: 'dept_execution',
      departmentName: 'Projects & Civil Execution',
      teamId: 'team_exe_villa',
      teamName: 'Turnkey Civil & Fitout Squad',
      roleId: 'role_proj_manager',
      roleName: 'Senior Project Manager (PM)',
      workLocation: 'Hyderabad Regional Hub',
      joiningDate: DateTime(2024, 2, 1),
      accessScope: DataScopeType.organization,
      approvalAuthority: 'Tier 3 (Material indents up to ₹10L)',
      lastLogin: DateTime(2026, 9, 11, 8, 30),
      allowedModules: ['Dashboard', 'Projects Overview', 'Execution & Site Visits', 'Service & Labour Directory'],
      activityHistory: [],
    ),
    AdminUser(
      id: 'usr_005',
      employeeId: 'HOM-1048',
      firstName: 'Pooja',
      lastName: 'Agarwal',
      displayName: 'Pooja Agarwal (CA)',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
      jobTitle: 'Financial Controller & Chief Auditor',
      employmentType: EmploymentType.fullTime,
      accountStatus: UserAccountStatus.active,
      primaryMobile: '+91 98110 33452',
      email: 'pooja.agarwal@homio.in',
      address: 'Tower 4, DLF Magnolias, Golf Course Road',
      city: 'Gurugram',
      state: 'Haryana',
      postalCode: '122002',
      departmentId: 'dept_accounts',
      departmentName: 'Finance & Accounting',
      teamId: 'team_sls_closer',
      teamName: 'Finance Audit',
      roleId: 'role_finance_mgr',
      roleName: 'Finance & Accounts Controller',
      workLocation: 'Gurugram Regional HQ',
      joiningDate: DateTime(2024, 4, 15),
      accessScope: DataScopeType.organization,
      approvalAuthority: 'Tier 3 (Disbursements up to ₹10L)',
      lastLogin: DateTime(2026, 9, 11, 10, 48),
      allowedModules: ['Dashboard', 'Accounting & Invoices', 'Quotations & Estimator', 'Reports & Analytics'],
      activityHistory: [],
    ),
    AdminUser(
      id: 'usr_006',
      employeeId: 'HOM-1052',
      firstName: 'Kavita',
      lastName: 'Menon',
      displayName: 'Kavita Menon',
      jobTitle: 'Telecalling Specialist (Malayalam & English)',
      employmentType: EmploymentType.fullTime,
      accountStatus: UserAccountStatus.active,
      primaryMobile: '+91 98470 11234',
      email: 'kavita.menon@homio.in',
      address: 'Panampilly Nagar',
      city: 'Kochi',
      state: 'Kerala',
      postalCode: '682036',
      departmentId: 'dept_sales',
      departmentName: 'Sales & Growth',
      teamId: 'team_sls_tele',
      teamName: 'Digital Inbound & SDR Squad',
      roleId: 'role_telecaller',
      roleName: 'Inbound Telecaller / SDR',
      reportingManagerId: 'usr_002',
      reportingManagerName: 'Priya Sundaram',
      workLocation: 'Kochi Remote Hub',
      joiningDate: DateTime(2025, 1, 15),
      accessScope: DataScopeType.myRecords,
      approvalAuthority: 'None',
      lastLogin: DateTime(2026, 9, 10, 16, 20),
      allowedModules: ['CRM & Leads', 'Calendar & Meetings'],
      activityHistory: [],
    ),
    AdminUser(
      id: 'usr_007',
      employeeId: 'HOM-1065',
      firstName: 'Deepak',
      lastName: 'Nambiar',
      displayName: 'Deepak Nambiar',
      jobTitle: 'Head of After-Sales & CSAT',
      employmentType: EmploymentType.fullTime,
      accountStatus: UserAccountStatus.active,
      primaryMobile: '+91 97401 77654',
      email: 'deepak.nambiar@homio.in',
      address: 'HSR Layout Sector 2',
      city: 'Bengaluru',
      state: 'Karnataka',
      postalCode: '560102',
      departmentId: 'dept_aftersales',
      departmentName: 'After-Sales & Warranty Hub',
      teamId: 'team_exe_villa',
      teamName: 'After-Sales Squad',
      roleId: 'role_proj_manager',
      roleName: 'Senior Project Manager (PM)',
      workLocation: 'Bengaluru Innovation Center',
      joiningDate: DateTime(2024, 6, 1),
      accessScope: DataScopeType.myDepartment,
      approvalAuthority: 'Warranty Claims up to ₹50,000',
      lastLogin: DateTime(2026, 9, 11, 12, 10),
      allowedModules: ['Dashboard', 'Projects Overview', 'Service & Labour Directory'],
      activityHistory: [],
    ),
    AdminUser(
      id: 'usr_008',
      employeeId: 'HOM-1078',
      firstName: 'Tanya',
      lastName: 'Sen',
      displayName: 'Tanya Sen',
      jobTitle: 'Junior 3D Visualizer & VR Artist',
      employmentType: EmploymentType.probation,
      accountStatus: UserAccountStatus.pendingInvite,
      primaryMobile: '+91 98300 44556',
      email: 'tanya.sen@homio.in',
      address: 'Salt Lake Sector V',
      city: 'Kolkata',
      state: 'West Bengal',
      postalCode: '700091',
      departmentId: 'dept_design',
      departmentName: 'Design & Architecture',
      teamId: 'team_dsg_3d',
      teamName: '3D Render & VR Studio',
      roleId: 'role_designer',
      roleName: 'Principal Interior Designer',
      reportingManagerId: 'usr_003',
      reportingManagerName: 'Ar. Ananya Deshmukh',
      workLocation: 'Kolkata Design Studio',
      joiningDate: DateTime(2026, 9, 1),
      accessScope: DataScopeType.assignedProjects,
      approvalAuthority: 'None',
      lastLogin: null,
      allowedModules: ['Designs & 3D Vault'],
      activityHistory: [],
    ),
    AdminUser(
      id: 'usr_009',
      employeeId: 'HOM-1090',
      firstName: 'Rohan',
      lastName: 'Verma',
      displayName: 'Rohan Verma',
      jobTitle: 'Deal Closer (Luxury Residential)',
      employmentType: EmploymentType.fullTime,
      accountStatus: UserAccountStatus.inactive,
      primaryMobile: '+91 98711 00223',
      email: 'rohan.verma@homio.in',
      address: 'Vasant Kunj Pocket B',
      city: 'New Delhi',
      state: 'Delhi',
      postalCode: '110070',
      departmentId: 'dept_sales',
      departmentName: 'Sales & Growth',
      teamId: 'team_sls_closer',
      teamName: 'High-Ticket Deal Closers',
      roleId: 'role_deal_closer',
      roleName: 'Senior Deal Closer',
      reportingManagerId: 'usr_001',
      reportingManagerName: 'Vikramaditya Singhania',
      workLocation: 'Delhi Regional Hub',
      joiningDate: DateTime(2024, 8, 1),
      accessScope: DataScopeType.myTeam,
      approvalAuthority: 'Tier 1 (Up to ₹25,000 spot discount)',
      lastLogin: DateTime(2026, 8, 14, 15, 30),
      allowedModules: ['CRM & Leads', 'Quotations & Estimator'],
      activityHistory: [],
    ),
  ];

  // ==========================================================================
  // 2. MASTER DATA MOCK DATA
  // ==========================================================================

  static final List<MasterCategoryItem> masterCategories = [
    // CRM
    const MasterCategoryItem(
      id: 'cat_lead_stages',
      group: MasterGroupCategory.crm,
      code: 'CRM-STG',
      name: 'Lead Stages & Pipeline States',
      description: 'Standard progression stages for prospective interior/construction clients',
      recordCount: 8,
    ),
    const MasterCategoryItem(
      id: 'cat_lead_sources',
      group: MasterGroupCategory.crm,
      code: 'CRM-SRC',
      name: 'Lead Sources & Channels',
      description: 'Attribution origins including Meta, Google, Architectural Referrals, Site Signboards',
      recordCount: 7,
    ),
    const MasterCategoryItem(
      id: 'cat_lead_tags',
      group: MasterGroupCategory.crm,
      code: 'CRM-TAG',
      name: 'Lead Qualification Tags',
      description: 'Budget markers, timeline urgency, property type labels (Villa, 3BHK, Commercial)',
      recordCount: 9,
    ),
    const MasterCategoryItem(
      id: 'cat_declining_reasons',
      group: MasterGroupCategory.crm,
      code: 'CRM-DEC',
      name: 'Lead Declining / Lost Reasons',
      description: 'Standardized drop-off reasons for sales audit (Budget Mismatch, Timeline Delayed)',
      recordCount: 6,
    ),

    // Projects & Execution
    const MasterCategoryItem(
      id: 'cat_proj_types',
      group: MasterGroupCategory.projects,
      code: 'PRJ-TYP',
      name: 'Project Types & Archetypes',
      description: 'Complete Turnkey, Modular Only, Civil Renovation, Villa Architecture, Commercial Retail',
      recordCount: 5,
    ),
    const MasterCategoryItem(
      id: 'cat_proj_stages',
      group: MasterGroupCategory.projects,
      code: 'PRJ-STG',
      name: 'Project Execution Stages',
      description: 'Site Demolition, Masonry & Plumbing, Electrical Rough-in, POP & False Ceiling, Modular Fitout, Handover',
      recordCount: 7,
    ),
    const MasterCategoryItem(
      id: 'cat_complaint_types',
      group: MasterGroupCategory.projects,
      code: 'PRJ-CMP',
      name: 'Complaint & Snag Categories',
      description: 'Surface scratches, hinge alignment, paint peeling, plumbing leakages, electrical tripping',
      recordCount: 6,
    ),

    // Commercial
    const MasterCategoryItem(
      id: 'cat_units',
      group: MasterGroupCategory.commercial,
      code: 'COM-UNT',
      name: 'Units of Measurement (UOM)',
      description: 'Area, linear, volume, piece, and lumpsum commercial standards',
      recordCount: 7,
    ),
    const MasterCategoryItem(
      id: 'cat_payment_terms',
      group: MasterGroupCategory.commercial,
      code: 'COM-TRM',
      name: 'Milestone Payment Terms',
      description: 'Standard milestone payment split templates (e.g., 10% Booking, 40% Woodwork, 40% Fitout, 10% Handover)',
      recordCount: 4,
    ),

    // Procurement
    const MasterCategoryItem(
      id: 'cat_material_cats',
      group: MasterGroupCategory.procurement,
      code: 'PRC-MAT',
      name: 'Material Master Categories',
      description: 'Plywood & Boards, Laminates & Veneers, Hardware & Hinges, Tiles & Marble, Sanitaryware',
      recordCount: 8,
    ),

    // Workforce
    const MasterCategoryItem(
      id: 'cat_labour_cats',
      group: MasterGroupCategory.workforce,
      code: 'WRK-LBR',
      name: 'Labour & Trade Categories',
      description: 'Master Carpenter, Assistant Carpenter, Electrician, Plumber, Painter, Mason, Tiler',
      recordCount: 8,
    ),

    // Marketplace
    const MasterCategoryItem(
      id: 'cat_marketplace_cats',
      group: MasterGroupCategory.marketplace,
      code: 'MKT-CAT',
      name: 'Marketplace Product Categories',
      description: 'Lighting Fixtures, Accent Furniture, Wall Decor, Digital Design Templates',
      recordCount: 6,
    ),
  ];

  static final List<MasterRecord> masterRecords = [
    // Lead Stages
    MasterRecord(
      id: 'rec_stg_01',
      categoryId: 'cat_lead_stages',
      categoryName: 'Lead Stages & Pipeline States',
      code: 'STG-NEW',
      name: 'New Inquiry Received',
      description: 'Raw inbound prospect captured via web form, WhatsApp, or phone call',
      displayOrder: 1,
      isSystemDefined: true,
      effectiveDate: DateTime(2025, 1, 1),
      usageCount: 245,
      usageContextDescription: 'Referenced across 245 active CRM leads and 12 sales automation workflows.',
    ),
    MasterRecord(
      id: 'rec_stg_02',
      categoryId: 'cat_lead_stages',
      categoryName: 'Lead Stages & Pipeline States',
      code: 'STG-QLF',
      name: 'Qualified & Floorplan Uploaded',
      description: 'Client budget confirmed, possession date verified, architectural floorplan received',
      displayOrder: 2,
      isSystemDefined: true,
      effectiveDate: DateTime(2025, 1, 1),
      usageCount: 168,
      usageContextDescription: 'Referenced across 168 qualified leads currently in design estimation queue.',
    ),
    MasterRecord(
      id: 'rec_stg_03',
      categoryId: 'cat_lead_stages',
      categoryName: 'Lead Stages & Pipeline States',
      code: 'STG-MEET',
      name: 'Design Center Consultation',
      description: 'Client visited experience center or attended 3D virtual walkthrough call',
      displayOrder: 3,
      isSystemDefined: true,
      effectiveDate: DateTime(2025, 1, 1),
      usageCount: 84,
      usageContextDescription: 'Referenced by 84 scheduled meetings and designer calendar logs.',
    ),
    MasterRecord(
      id: 'rec_stg_04',
      categoryId: 'cat_lead_stages',
      categoryName: 'Lead Stages & Pipeline States',
      code: 'STG-QTE',
      name: 'Quotation Presented',
      description: 'BOQ generated from Item Master and shared with prospective homeowner',
      displayOrder: 4,
      isSystemDefined: true,
      effectiveDate: DateTime(2025, 1, 1),
      usageCount: 52,
      usageContextDescription: 'Referenced by 52 active quotation proposals awaiting client token advance.',
    ),
    MasterRecord(
      id: 'rec_stg_05',
      categoryId: 'cat_lead_stages',
      categoryName: 'Lead Stages & Pipeline States',
      code: 'STG-BOK',
      name: 'Token Booking Advance Received',
      description: '10% design signup advance collected, project transitioned to architecture team',
      displayOrder: 5,
      isSystemDefined: true,
      effectiveDate: DateTime(2025, 1, 1),
      usageCount: 39,
      usageContextDescription: 'Referenced by 39 live booked projects in preliminary 3D drawing stage.',
    ),

    // Lead Sources
    MasterRecord(
      id: 'rec_src_01',
      categoryId: 'cat_lead_sources',
      categoryName: 'Lead Sources & Channels',
      code: 'SRC-META',
      name: 'Meta Ads (Instagram / Facebook)',
      description: 'Direct Instant Forms and Lead Gen Carousel ads with visual room renders',
      displayOrder: 1,
      isSystemDefined: true,
      effectiveDate: DateTime(2025, 1, 1),
      usageCount: 1240,
      usageContextDescription: 'Referenced by 1,240 historical leads and Meta Webhook integration.',
    ),
    MasterRecord(
      id: 'rec_src_02',
      categoryId: 'cat_lead_sources',
      categoryName: 'Lead Sources & Channels',
      code: 'SRC-GGL',
      name: 'Google High-Intent Search',
      description: 'Search campaigns for "luxury interior designers in Bangalore/Mumbai"',
      displayOrder: 2,
      isSystemDefined: true,
      effectiveDate: DateTime(2025, 1, 1),
      usageCount: 680,
      usageContextDescription: 'Referenced by 680 leads and Google Ads conversion tracking.',
    ),
    MasterRecord(
      id: 'rec_src_03',
      categoryId: 'cat_lead_sources',
      categoryName: 'Lead Sources & Channels',
      code: 'SRC-ARCH',
      name: 'Architect & Builder Referral',
      description: 'Commissions shared with external structural architects and real estate brokers',
      displayOrder: 3,
      isSystemDefined: false,
      effectiveDate: DateTime(2025, 3, 1),
      usageCount: 94,
      usageContextDescription: 'Referenced by 94 high-ticket projects and channel partner ledger accounts.',
    ),

    // Commercial Units
    MasterRecord(
      id: 'rec_unt_01',
      categoryId: 'cat_units',
      categoryName: 'Units of Measurement (UOM)',
      code: 'UOM-SQFT',
      name: 'Square Feet (Sq. Ft.)',
      description: 'Standard 2D surface area metric for flooring, ceilings, and wall paneling',
      displayOrder: 1,
      isSystemDefined: true,
      effectiveDate: DateTime(2025, 1, 1),
      usageCount: 860,
      usageContextDescription: 'Referenced in 860 BOQ line items and quotation calculation algorithms.',
    ),
    MasterRecord(
      id: 'rec_unt_02',
      categoryId: 'cat_units',
      categoryName: 'Units of Measurement (UOM)',
      code: 'UOM-RFT',
      name: 'Running Feet (R.Ft.)',
      description: 'Linear perimeter measurement for skirting, pelmets, LED cove profile, and counter edge',
      displayOrder: 2,
      isSystemDefined: true,
      effectiveDate: DateTime(2025, 1, 1),
      usageCount: 420,
      usageContextDescription: 'Referenced across 420 woodwork and skirting catalog entries.',
    ),
    MasterRecord(
      id: 'rec_unt_03',
      categoryId: 'cat_units',
      categoryName: 'Units of Measurement (UOM)',
      code: 'UOM-NOS',
      name: 'Numbers / Pieces (Nos)',
      description: 'Discrete physical items like spotlights, pendant lights, basin mixers, handles',
      displayOrder: 3,
      isSystemDefined: true,
      effectiveDate: DateTime(2025, 1, 1),
      usageCount: 710,
      usageContextDescription: 'Referenced across 710 electrical, hardware, and sanitaryware catalogue items.',
    ),
  ];

  // ==========================================================================
  // 3. ITEM / RATE MASTERS MOCK DATA
  // ==========================================================================

  static final List<RateMasterItem> rateItems = [
    RateMasterItem(
      id: 'itm_wood_01',
      itemCode: 'WD-MOD-KTCH-01',
      itemName: 'Modular Kitchen Base Carcass (BWP Marine Ply + Anti-Bacterial Liner)',
      category: 'Modular Woodwork',
      subCategory: 'Kitchen Base Units',
      brand: 'CenturyPly Club Prime / Greenpanel',
      modelVariant: '710 BWP Grade Marine Plywood 18mm',
      shortDescription: 'Boiling Waterproof (BWP) 710 grade 18mm marine plywood cabinet carcass with 0.8mm internal white off-white laminate liner.',
      detailedDescription: 'Constructed using calibrated CenturyPly Club Prime BWP plywood with IS:710 certification. All edges sealed with 2mm PVC hot-melt edge banding. Includes CNC cam-lock knock-down fasteners, stainless steel levelling legs (100mm), and moisture-barrier plinth skirting.',
      imageUrl: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=300',
      unit: RateUnitBasis.sqFt,
      specs: const TechSpecifications(
        material: 'Plywood & High-Pressure Laminate',
        coreMaterial: 'IS:710 BWP Grade Hardwood Marine Core',
        finish: '0.8mm Anti-Bacterial Off-White Liner',
        thickness: '18mm carcass, 12mm back panel',
        dimensions: '600mm Depth x 720mm Height modular matrix',
        hardware: 'Hettich / Hafele Concealed Cam-Locks',
        brand: 'CenturyPly Club Prime',
        grade: 'IS:710 Marine Grade',
        color: 'Off-White Matte',
        warrantyPeriod: '25 Years Manufacturer Warranty against borer/fungus',
        technicalNotes: 'Presoak edges in marine adhesive before 2mm edge banding',
      ),
      baseMaterialCost: 1450.0,
      baseLaborCost: 350.0,
      sellingRate: 2350.0,
      marginType: MarginCalculationType.percentage,
      marginValue: 23.4,
      effectiveFrom: DateTime(2026, 1, 1),
      quotationReferencesCount: 142,
      activeCataloguesCount: 3,
      lastUpdated: DateTime(2026, 8, 1),
      rateHistory: [
        RateHistoryEntry(
          id: 'rh_01',
          itemId: 'itm_wood_01',
          previousRate: 2150.0,
          newRate: 2350.0,
          effectiveDate: DateTime(2026, 1, 1),
          changedBy: 'Pooja Agarwal (CA)',
          reason: 'Timber import tariff & resin cost escalation by CenturyPly',
          status: 'Applied',
        ),
      ],
    ),
    RateMasterItem(
      id: 'itm_shutter_02',
      itemCode: 'WD-SHT-ACR-02',
      itemName: 'High-Gloss Seamless Acrylic Shutter (2mm Acrylic on HDHMR Core)',
      category: 'Modular Woodwork',
      subCategory: 'Shutters & Facias',
      brand: 'Senosan Glass / Action TESA',
      modelVariant: '2mm Scratch-Resistant Ultra High-Gloss Acrylic',
      shortDescription: 'Mirror-finish 2mm acrylic laminated on 18mm high-density water-resistant HDHMR board with zero-joint PUR laser edge banding.',
      detailedDescription: 'Manufactured using German PUR hot-melt edge banding technology ensuring 100% moisture resistance at joints. Ultra-high UV resistance prevents yellowing over 15+ years. Suitable for premium modular kitchens and vanity units.',
      imageUrl: 'https://images.unsplash.com/photo-1507089947368-19c1da9775ae?w=300',
      unit: RateUnitBasis.sqFt,
      specs: const TechSpecifications(
        material: 'Acrylic & HDHMR',
        coreMaterial: 'Action TESA Grade HDHMR (Moisture-Resistant High Density)',
        finish: '2mm Senosan Austria Scratch-Resistant Acrylic',
        thickness: '20mm finished thickness',
        dimensions: 'Custom shutter cut to order',
        hardware: 'Requires soft-close clip-on hinges with 8mm dowels',
        brand: 'Senosan / Action TESA',
        grade: 'European Class 1 Scratch Resistant',
        color: 'Champagne Metallic / Super White',
        warrantyPeriod: '10 Years Surface Warranty against fading and delamination',
        technicalNotes: 'Peel protective film only after on-site installation and final cleaning',
      ),
      baseMaterialCost: 1850.0,
      baseLaborCost: 400.0,
      sellingRate: 2950.0,
      marginType: MarginCalculationType.percentage,
      marginValue: 23.7,
      effectiveFrom: DateTime(2026, 2, 1),
      quotationReferencesCount: 118,
      activeCataloguesCount: 2,
      lastUpdated: DateTime(2026, 8, 10),
      rateHistory: [],
    ),
    RateMasterItem(
      id: 'itm_ceil_01',
      itemCode: 'CL-GYP-IND-01',
      itemName: 'Designer False Ceiling (Saint-Gobain Gyproc Sheet + GI Framing)',
      category: 'False Ceiling & Gyproc',
      subCategory: 'Gypsum Ceilings',
      brand: 'Saint-Gobain Gyproc',
      modelVariant: '12.5mm Standard Gypsum Plasterboard + Ultra Frame',
      shortDescription: 'Drop ceiling system featuring Saint-Gobain 12.5mm plasterboard suspended with GI channel framing, mesh tape, jointing compound & 2 coats primer.',
      detailedDescription: 'Includes heavy-duty perimeter GI channels, intermediate channels, ceiling sections suspended with adjustable GI soffit cleats. All joints taped with Gyproc fiber-mesh and finished with 3 coats of joint filler sanded smooth for paint readiness. Cove LED lighting cutouts included.',
      imageUrl: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=300',
      unit: RateUnitBasis.sqFt,
      specs: const TechSpecifications(
        material: 'Gypsum Plasterboard & Galvanized Iron (GI)',
        coreMaterial: 'Aerated Gypsum Core with Heavy Duty Paper Liners',
        finish: 'Gyproc Jointing Compound Sanded to Level 4 Finish',
        thickness: '12.5mm board + 75mm to 150mm drop cavity',
        dimensions: 'As per spatial false ceiling architectural layout',
        hardware: 'G.I. Drywall Screws & Rawl Plug Anchors',
        brand: 'Saint-Gobain Gyproc Elite',
        grade: 'Fire-Retardant Class 1 Surface',
        color: 'White Jointed Ready for Paint',
        warrantyPeriod: '10 Years Structural Suspension Guarantee',
        technicalNotes: 'Ensure 600mm c/c framing interval to prevent center sagging',
      ),
      baseMaterialCost: 75.0,
      baseLaborCost: 45.0,
      sellingRate: 165.0,
      marginType: MarginCalculationType.percentage,
      marginValue: 27.2,
      effectiveFrom: DateTime(2025, 6, 1),
      quotationReferencesCount: 285,
      activeCataloguesCount: 4,
      lastUpdated: DateTime(2026, 7, 15),
      rateHistory: [],
    ),
    RateMasterItem(
      id: 'itm_flr_01',
      itemCode: 'FL-ITA-MRB-01',
      itemName: 'Imported Italian Marble (Bottochino / Statuario with Diamond Polishing)',
      category: 'Civil & Flooring',
      subCategory: 'Natural Stone',
      brand: 'Classic Marble Company (CMC) / Imported',
      modelVariant: '18mm Book-Matched Italian Slabs',
      shortDescription: 'Premium natural Italian marble supply, gang-saw slab cutting, dry-lay dry matching, cement slurry bed laying, paper jointing, and 8-stage diamond crystallization polish.',
      detailedDescription: 'Exquisite European imported marble. Workmanship includes chemical backing fiber-net reinforcement, dry inspection at slab stockyard, slurry bed installation with polymer-modified adhesive, hairline joints with color-matched epoxy, and mirror crystallization polish delivering 95+ gloss units.',
      imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=300',
      unit: RateUnitBasis.sqFt,
      specs: const TechSpecifications(
        material: 'Natural Metamorphic Italian Calcite Marble',
        coreMaterial: '100% Solid Natural Quarried Stone',
        finish: 'Mirror Crystallization Polish (95+ Gloss Level)',
        thickness: '18mm to 20mm calibrated slab',
        dimensions: 'Random Jumbo Slabs (Typically 8ft x 5ft+)',
        hardware: 'Roff Epoxy Grout & Laticrete Polymer Bed Adhesive',
        brand: 'Imported Italian Bottochino Classico',
        grade: 'First Quality Select Grade',
        color: 'Beige with subtle golden veins',
        warrantyPeriod: 'Lifetime natural stone longevity; 3-year polish gloss retention',
        technicalNotes: 'Always perform slab dry-laying at client presence before wet mortar fixing',
      ),
      baseMaterialCost: 420.0,
      baseLaborCost: 180.0,
      sellingRate: 850.0,
      marginType: MarginCalculationType.percentage,
      marginValue: 29.4,
      effectiveFrom: DateTime(2026, 1, 1),
      quotationReferencesCount: 64,
      activeCataloguesCount: 1,
      lastUpdated: DateTime(2026, 8, 22),
      rateHistory: [],
    ),
  ];

  // ==========================================================================
  // 4. MESSAGE TEMPLATES MOCK DATA
  // ==========================================================================

  static final List<MessageTemplate> messageTemplates = [
    MessageTemplate(
      id: 'tmpl_wa_01',
      code: 'WA-LEAD-WLC-01',
      name: 'Instant WhatsApp Lead Welcome & Lookbook Link',
      category: 'Lead Welcome & Nurturing',
      description: 'Triggered within 60 seconds of a new Meta/Google inquiry being captured',
      channel: TemplateChannel.whatsApp,
      language: 'English (en_IN)',
      status: TemplateApprovalState.published,
      triggerEvent: 'Lead Created',
      internalNotes: 'Pre-approved with Meta WhatsApp Cloud API template key: `homio_inbound_welcome_v2`',
      messageBody: 'Hello {{Customer Name}},\n\nThank you for reaching out to *Homio Interior & Architecture*. We are excited to collaborate with you on designing your dream home!\n\nOur Senior Design Consultant, *{{Employee Name}}*, will reach out shortly to discuss your floor plan and spatial preferences.\n\nIn the meantime, feel free to browse our curated 2026 Turnkey Lookbook here: {{Digital Store Link}}.\n\nWarm regards,\n*Team Homio*',
      usedVariables: ['Customer Name', 'Employee Name', 'Digital Store Link'],
      buttons: [
        TemplateButtonAction(id: 'btn_1', buttonType: 'Quick Reply', label: 'View Lookbook', value: 'VIEW_LOOKBOOK'),
        TemplateButtonAction(id: 'btn_2', buttonType: 'Quick Reply', label: 'Request Call Now', value: 'CALL_NOW'),
      ],
      activeAutomationsCount: 4,
      updatedAt: DateTime(2026, 8, 25),
      updatedBy: 'Vikramaditya Singhania',
    ),
    MessageTemplate(
      id: 'tmpl_wa_02',
      code: 'WA-MEET-CNF-02',
      name: 'Experience Center Consultation Confirmed',
      category: 'Meeting & Calendar',
      description: 'Sent when design consultation is scheduled in CRM calendar',
      channel: TemplateChannel.whatsApp,
      language: 'English (en_IN)',
      status: TemplateApprovalState.published,
      triggerEvent: 'Meeting Scheduled',
      messageBody: 'Dear {{Customer Name}},\n\nYour 3D Design Consultation for *{{Project Name}}* is officially scheduled!\n\n📅 *Date:* {{Meeting Date}}\n⏰ *Time:* {{Meeting Time}}\n📍 *Location:* Homio Experience Center, Bandra West\n👨‍💼 *Lead Architect:* {{Employee Name}}\n\nPlease bring your CAD floorplan or possession document for real-time 3D budget estimation.\n\nNeed to reschedule? Tap the button below.',
      usedVariables: ['Customer Name', 'Project Name', 'Meeting Date', 'Meeting Time', 'Employee Name'],
      buttons: [
        TemplateButtonAction(id: 'btn_3', buttonType: 'Quick Reply', label: 'Confirm Attendance', value: 'CONFIRM_MEET'),
        TemplateButtonAction(id: 'btn_4', buttonType: 'Quick Reply', label: 'Reschedule', value: 'RESCHEDULE_MEET'),
      ],
      activeAutomationsCount: 2,
      updatedAt: DateTime(2026, 9, 2),
      updatedBy: 'Priya Sundaram',
    ),
    MessageTemplate(
      id: 'tmpl_eml_01',
      code: 'EML-QTE-DLV-01',
      name: 'Official Quotation BOQ & 3D Cost Breakdown',
      category: 'Quotations & Pricing',
      description: 'Formal corporate email dispatch attaching PDF BOQ and payment schedule',
      channel: TemplateChannel.email,
      language: 'English (en_IN)',
      status: TemplateApprovalState.published,
      triggerEvent: 'Quotation Sent',
      messageBody: 'Dear {{Customer Name}},\n\nFollowing our productive design session, we are delighted to present the comprehensive Turnkey Interior BOQ Estimate for {{Project Name}}.\n\n• Quotation Reference: {{Quotation Number}}\n• Total Estimated Commercials: {{Quotation Amount}} (Inclusive of 18% GST)\n• Proposal Validity: 14 Days from issuance\n\nYou can review the line-item specifications, material brands (CenturyPly 710, Saint-Gobain, Hafele hardware), and milestone terms in the attached secure document: {{Approval Link}}.\n\nShould you have any queries, your Dedicated Project Lead, {{Employee Name}}, is available at {{Company Contact}}.\n\nWarm regards,\nCommercial Estimations Desk\nHomio Architecture & Interiors',
      usedVariables: ['Customer Name', 'Project Name', 'Quotation Number', 'Quotation Amount', 'Approval Link', 'Employee Name', 'Company Contact'],
      activeAutomationsCount: 5,
      updatedAt: DateTime(2026, 8, 30),
      updatedBy: 'Pooja Agarwal (CA)',
    ),
    MessageTemplate(
      id: 'tmpl_wa_03',
      code: 'WA-PAY-DMD-03',
      name: 'Milestone Work Completion Payment Request',
      category: 'Billing & Payments',
      description: 'Sent when Project Manager marks site milestone complete (e.g., False Ceiling ready)',
      channel: TemplateChannel.whatsApp,
      language: 'English (en_IN)',
      status: TemplateApprovalState.published,
      triggerEvent: 'Payment Requested',
      messageBody: 'Hello {{Customer Name}},\n\nGreat news! Milestone *{{Milestone Name}}* for your home *{{Project Name}}* has been inspected and approved by our Quality Audit team. ✅\n\nTo initiate the next stage of modular factory dispatch, please review the invoice and complete the scheduled installment:\n\n💳 *Amount Payable:* {{Payment Amount}}\n🔗 *Secure Payment Link:* {{Payment Link}}\n\nAll official receipts are instantly generated and logged into your Client Portal account.\n\nBest regards,\n*Homio Finance & Billing Team*',
      usedVariables: ['Customer Name', 'Milestone Name', 'Project Name', 'Payment Amount', 'Payment Link'],
      buttons: [
        TemplateButtonAction(id: 'btn_5', buttonType: 'Call To Action (URL)', label: 'Pay Securely Online', value: '{{Payment Link}}'),
      ],
      activeAutomationsCount: 3,
      updatedAt: DateTime(2026, 9, 8),
      updatedBy: 'Pooja Agarwal (CA)',
    ),
  ];

  // ==========================================================================
  // 5. AI TRAINING MOCK DATA
  // ==========================================================================

  static final List<AiPricingGuardrail> pricingGuardrails = [
    const AiPricingGuardrail(
      id: 'grd_01',
      topic: 'Turnkey Residential Full Interior Minimum Rate',
      rule: 'AI MUST NOT quote below ₹1,850 per sq.ft. for premium turnkey interior solutions',
      allowedDisclosure: 'Inform customer that Homio turnkey luxury interiors typically start from ₹1,850 to ₹2,400 per sq.ft. depending on material specifications (e.g. Acrylic vs PU polish, quartz vs Italian marble).',
      forbiddenDisclosure: 'Never promise custom rates below ₹1,850/sq.ft. or commit to individual hardware prices without architect BOQ measurement.',
      minimumSqFtFloor: 1850.0,
      maximumDiscountAllowed: 7.0,
      isStrictNonNegotiable: true,
    ),
    const AiPricingGuardrail(
      id: 'grd_02',
      topic: 'Spot Discount & Advance Waiver Limitations',
      rule: 'AI has ZERO authority to offer discounts greater than 5% or waive the 10% signup token advance',
      allowedDisclosure: 'Mention that during your experience center visit, the Sales Head may evaluate current seasonal manufacturer promotions of up to 5% on factory-made cabinetry.',
      forbiddenDisclosure: 'Never state "we can waive token fee" or "I can give you 15% discount".',
      minimumSqFtFloor: 0.0,
      maximumDiscountAllowed: 5.0,
      isStrictNonNegotiable: true,
    ),
  ];

  static final List<AiFaqItem> aiFaqs = [
    AiFaqItem(
      id: 'faq_01',
      question: 'What is Homio’s 45-day move-in guarantee, and does it include penalty clauses?',
      answer: 'Yes! Homio provides a guaranteed 45-day move-in timeline for all standard modular woodworking and false ceiling fitouts from the date of final 3D drawing sign-off. If there is an unexcused delay attributable to Homio, we credit ₹1,000 per day directly to your final milestone ledger.',
      category: 'Timeline & Guarantees',
      keywords: ['45 day', 'delivery timeline', 'delay penalty', 'guarantee', 'handover'],
      priority: 1,
      lastUpdated: DateTime(2026, 8, 1),
    ),
    AiFaqItem(
      id: 'faq_02',
      question: 'What materials do you use for kitchen cabinetry in humid coastal areas?',
      answer: 'For wet zones and coastal regions like Mumbai or Kochi, Homio strictly uses IS:710 Marine Grade BWP (Boiling Waterproof) plywood from certified brands like CenturyPly Club Prime or Greenpanel. All carcass edges are sealed with 2mm German PUR laser edge banding to guarantee zero swelling.',
      category: 'Materials & Specifications',
      keywords: ['plywood', 'marine', 'bwp', 'waterproof', 'coastal', 'century', 'kitchen carcass'],
      priority: 2,
      lastUpdated: DateTime(2026, 8, 15),
    ),
    AiFaqItem(
      id: 'faq_03',
      question: 'Can I customize only a modular kitchen without renovating the entire 3BHK flat?',
      answer: 'Absolutely. Homio offers dedicated Kitchen & Wardrobe standalone packages starting from ₹3.5 Lakhs, including complete 3D design visualizers, quartz worktops, and soft-close German hardware from Hafele or Hettich.',
      category: 'Scope & Packages',
      keywords: ['kitchen only', 'modular kitchen', 'partial renovation', 'wardrobe only'],
      priority: 2,
      lastUpdated: DateTime(2026, 9, 2),
    ),
    AiFaqItem(
      id: 'faq_04',
      question: 'I want to speak with a human designer right now. Stop talking, robot.',
      answer: 'I completely understand! I am transferring this conversation to our Senior Architect on duty right now. They will reach out via this WhatsApp number within the next 5 minutes.',
      category: 'Escalation & Human Handoff',
      keywords: ['human', 'agent', 'speak to person', 'real person', 'stop bot', 'customer care'],
      priority: 1,
      escalationRequired: true,
      lastUpdated: DateTime(2026, 9, 5),
    ),
  ];

  static final List<AiKnowledgeSource> aiKnowledgeSources = [
    AiKnowledgeSource(
      id: 'ks_01',
      name: 'Homio Corporate Overview & 2026 Turnkey Scope Document',
      type: KnowledgeSourceType.companyPolicy,
      category: 'Company Knowledge',
      status: 'Published',
      version: 'v3.2',
      createdBy: 'Vikramaditya Singhania',
      lastUpdated: DateTime(2026, 8, 10),
      lastIndexed: DateTime(2026, 9, 10),
      summary: 'Detailed company background, 14 operating branches, ISO 9001 certifications, experience center locations, and working hours (10 AM to 8 PM).',
      tokensCount: 4200,
    ),
    AiKnowledgeSource(
      id: 'ks_02',
      name: 'Architectural Design Styles & Portfolio Catalog',
      type: KnowledgeSourceType.portfolioCase,
      category: 'Portfolio Knowledge',
      status: 'Published',
      version: 'v2.8',
      createdBy: 'Ar. Ananya Deshmukh',
      lastUpdated: DateTime(2026, 8, 18),
      lastIndexed: DateTime(2026, 9, 10),
      summary: 'Photographic case studies for Japandi, Contemporary Neo-Classical, Scandinavian Minimalist, and Modern Industrial luxury villas.',
      tokensCount: 6800,
    ),
    AiKnowledgeSource(
      id: 'ks_03',
      name: 'Approved Hardware & Woodwork Spec Matrix',
      type: KnowledgeSourceType.pricingGuardrails,
      category: 'Product & Pricing Guardrails',
      status: 'Published',
      version: 'v4.1',
      createdBy: 'Pooja Agarwal (CA)',
      lastUpdated: DateTime(2026, 9, 1),
      lastIndexed: DateTime(2026, 9, 11),
      summary: 'Strict boundaries on allowed vs forbidden pricing quotes. Zero tolerance for unverified rate commitments.',
      tokensCount: 3100,
    ),
  ];

  static final List<AiTestingSimulation> playgroundSimulations = [
    const AiTestingSimulation(
      customerQuery: 'How much will it cost to design my 3BHK flat in HSR Layout Bangalore (1500 sq.ft)?',
      aiResponse: 'Hello! For a 1,500 sq.ft. 3BHK in HSR Layout, our turnkey interior packages typically range from ₹27.75 Lakhs to ₹36 Lakhs (approx. ₹1,850 – ₹2,400 per sq.ft.). This includes complete modular kitchen in IS:710 marine ply, floor-to-ceiling wardrobes, designer false ceilings with COB LEDs, and premium Asian Paints Royale finishes. Would you like our Senior Architect to share a 3D floor plan layout?',
      matchedKnowledgeSource: 'Approved Hardware & Woodwork Spec Matrix (Pricing Guardrails)',
      confidenceScore: 0.94,
      escalationDecision: false,
      suggestedHumanAction: 'Assign lead to SDR for floorplan collection call',
    ),
    const AiTestingSimulation(
      customerQuery: 'Can you give me this entire package for ₹15 Lakhs? My budget is very tight.',
      aiResponse: 'We appreciate your transparency about your budget! Because we strictly use 100% boiling waterproof BWP marine plywood and branded Hafele soft-close hardware backed by a 10-year warranty, our complete turnkey 3BHK package cannot be delivered at ₹15 Lakhs. However, we can customize a Modular-Only Core Package (Kitchen + Wardrobes + Bath vanities) comfortably within ₹14 to ₹16 Lakhs! Would you like to explore this option?',
      matchedKnowledgeSource: 'Pricing Guardrail #1 & Scope Standards',
      confidenceScore: 0.91,
      escalationDecision: false,
      suggestedHumanAction: 'Tag lead as "Core Modular Only - Budget Conscious"',
    ),
    const AiTestingSimulation(
      customerQuery: 'There is water leaking behind the kitchen cabinet you installed last month! Send someone immediately!',
      aiResponse: 'I am so sorry to hear about this leakage! Your satisfaction and home safety are our top priorities. I have flagged this as an Urgent Emergency Snag ticket (#SNG-9942) and notified our Head of After-Sales, Deepak Nambiar. A certified plumbing technician is being dispatched to your residence. Our team will call you within 15 minutes.',
      matchedKnowledgeSource: 'Emergency Snag Escalation Rule',
      confidenceScore: 0.98,
      escalationDecision: true,
      suggestedHumanAction: 'Immediate dispatch of site supervisor & warranty plumbing team',
    ),
  ];

  // ==========================================================================
  // 6. INTEGRATIONS MOCK DATA
  // ==========================================================================

  static final List<IntegrationService> integrations = [
    IntegrationService(
      id: 'int_meta',
      providerKey: 'meta_leads',
      name: 'Meta Ads Lead Sync (Instagram & FB)',
      category: IntegrationCategory.crmLeadSources,
      description: 'Instant real-time webhook ingestion of prospective homeowners submitting Instagram and Facebook Lead Gen forms.',
      iconUrl: 'https://cdn-icons-png.flaticon.com/512/5968/5968764.png',
      connectionStatus: IntegrationConnectionStatus.connected,
      environment: 'Production',
      connectedSince: DateTime(2024, 5, 10),
      lastSyncTimestamp: DateTime(2026, 9, 11, 14, 2),
      connectionOwner: 'Vikramaditya Singhania',
      credentialsMap: {
        'App ID': '884920481920481',
        'App Secret': '••••••••••••••••••••••••3a9f',
        'System User Access Token': 'EAAGz••••••••••••••••••••••••wZDZD',
        'Webhook Verify Token': 'homio_meta_lead_sync_secret_998',
      },
      providerConfig: {
        'Connected Pages': 'Homio Interiors Official (ID: 1092837482)',
        'Active Lead Forms': '5 Active Forms (3BHK Luxury, Villa Lookbook, Modular Kitchen)',
        'Destination Pipeline': 'Inbound Digital Leads',
        'Auto Assign Squad': 'Digital Inbound & SDR Squad',
      },
      fieldMappings: [
        const IntegrationFieldMapping(id: 'fm_01', externalField: 'full_name', homioField: 'Customer Full Name', isRequired: true, sampleData: 'Rhea Chakraborty'),
        const IntegrationFieldMapping(id: 'fm_02', externalField: 'phone_number', homioField: 'Primary Mobile (+91)', isRequired: true, sampleData: '+919820011223'),
        const IntegrationFieldMapping(id: 'fm_03', externalField: 'email', homioField: 'Customer Email', isRequired: false, sampleData: 'rhea@gmail.com'),
        const IntegrationFieldMapping(id: 'fm_04', externalField: 'city_property', homioField: 'Work Location / City', isRequired: true, sampleData: 'Bengaluru'),
        const IntegrationFieldMapping(id: 'fm_05', externalField: 'estimated_budget', homioField: 'Estimated Budget Tier', isRequired: false, sampleData: '₹25L - ₹40L'),
      ],
      healthMetrics: const IntegrationHealthMetrics(
        uptimePercent: 99.95,
        totalRequests24h: 184,
        successfulRequests24h: 184,
        failedRequests24h: 0,
        latencyMs: 140,
      ),
      affectedWorkflowsOnDisable: [
        'Automatic inbound lead creation for all active Instagram and Facebook ad campaigns',
        'Instant WhatsApp lookbook welcome message dispatch',
        'Telecaller round-robin lead allocation queue',
      ],
    ),
    IntegrationService(
      id: 'int_wa_cloud',
      providerKey: 'whatsapp_cloud_api',
      name: 'WhatsApp Business Cloud API (Official)',
      category: IntegrationCategory.communication,
      description: 'Official Meta WhatsApp Business Cloud infrastructure handling 2-way client chats, quotation PDF delivery & AI chatbot.',
      iconUrl: 'https://cdn-icons-png.flaticon.com/512/3670/3670051.png',
      connectionStatus: IntegrationConnectionStatus.connected,
      environment: 'Production',
      connectedSince: DateTime(2024, 4, 1),
      lastSyncTimestamp: DateTime(2026, 9, 11, 14, 5),
      connectionOwner: 'Enterprise Super Admin',
      credentialsMap: {
        'WABA Account ID': '109283746192837',
        'Phone Number ID': '100293847561029',
        'Display Phone Number': '+91 80 4719 2200 (Green Badge Verified)',
        'Permanent Bearer Token': 'EAAK••••••••••••••••••••••••vBZAZ',
      },
      providerConfig: {
        'Webhook URL': 'https://api.homio.in/v1/webhooks/whatsapp',
        'Sync Frequency': 'Real-time WebSocket Push',
        'Verified Display Name': 'Homio Architecture & Turnkey Interiors',
        'Quality Rating': 'High (Green Indicator)',
      },
      healthMetrics: const IntegrationHealthMetrics(
        uptimePercent: 99.98,
        totalRequests24h: 2450,
        successfulRequests24h: 2448,
        failedRequests24h: 2,
        latencyMs: 210,
        lastErrorSummary: 'Meta Rate Limit Soft Throttle (auto-recovered)',
      ),
      affectedWorkflowsOnDisable: [
        'All client WhatsApp chat interactions in CRM inbox',
        'Milestone approval notifications and payment reminder links',
        'Automated AI WhatsApp Consultant and doubt solver',
      ],
    ),
    IntegrationService(
      id: 'int_razorpay',
      providerKey: 'razorpay_pg',
      name: 'Razorpay Payment Gateway & Smart Routing',
      category: IntegrationCategory.payments,
      description: 'Token advances, milestone installment payments via UPI, Credit Cards, Netbanking & Easy EMI options.',
      iconUrl: 'https://cdn.iconscout.com/icon/free/png-256/free-razorpay-logo-icon-download-in-svg-png-gif-file-formats--payment-gateway-brand-logos-pack-icons-5226490.png',
      connectionStatus: IntegrationConnectionStatus.connected,
      environment: 'Production',
      connectedSince: DateTime(2024, 3, 15),
      lastSyncTimestamp: DateTime(2026, 9, 11, 13, 40),
      connectionOwner: 'Pooja Agarwal (CA)',
      credentialsMap: {
        'Key ID': 'rzp_live_9Fk••••••••••••',
        'Key Secret': '••••••••••••••••••••••••8812',
        'Webhook Secret': 'rzp_wh_sec_homio_prod_2026',
      },
      providerConfig: {
        'Settlement Currency': 'INR (₹)',
        'Auto Capture Payments': 'Enabled (Capture on Gateway Success)',
        'Instant GST Invoicing': 'Enabled (Auto sync with Accounting Ledger)',
      },
      healthMetrics: const IntegrationHealthMetrics(
        uptimePercent: 100.0,
        totalRequests24h: 48,
        successfulRequests24h: 48,
        failedRequests24h: 0,
        latencyMs: 320,
      ),
      affectedWorkflowsOnDisable: [
        'Live credit card / UPI token payment checkout in Client Portal',
        'Milestone payment links generated inside WhatsApp messages',
        'Instant automated GST receipt generation',
      ],
    ),
    IntegrationService(
      id: 'int_exotel',
      providerKey: 'exotel_telephony',
      name: 'Exotel Cloud Telephony & Call Recording',
      category: IntegrationCategory.calling,
      description: 'Virtual numbers, click-to-call for sales SDRs, call recording storage, and missed call automated callbacks.',
      iconUrl: 'https://cdn-icons-png.flaticon.com/512/3616/3616215.png',
      connectionStatus: IntegrationConnectionStatus.connected,
      environment: 'Production',
      connectedSince: DateTime(2024, 6, 20),
      lastSyncTimestamp: DateTime(2026, 9, 11, 14, 0),
      connectionOwner: 'Vikramaditya Singhania',
      credentialsMap: {
        'Account SID': 'homiointeriors1',
        'API Key': 'ex_key_••••••••••••••••',
        'API Token': '••••••••••••••••••••••••90aa',
        'Caller ID (Virtual No)': '080-6922-8800',
      },
      providerConfig: {
        'Call Recording': '100% Inbound & Outbound Dual Channel',
        'Storage Retention': '180 Days Cloud Audio Retention',
        'WebRTC Softphone': 'Enabled in CRM Top Bar',
      },
      healthMetrics: const IntegrationHealthMetrics(
        uptimePercent: 99.8,
        totalRequests24h: 310,
        successfulRequests24h: 308,
        failedRequests24h: 2,
        latencyMs: 180,
      ),
      affectedWorkflowsOnDisable: [
        'Click-to-call functionality from CRM Leads and Follow-ups tables',
        'Call audio playback and speech analytics in Lead Dossier',
      ],
    ),
    IntegrationService(
      id: 'int_aws_s3',
      providerKey: 'aws_s3_storage',
      name: 'AWS S3 Cloud Media & DAM Vault',
      category: IntegrationCategory.storage,
      description: 'High-speed object storage for 4K 3D renders, architectural AutoCAD DWGs, site progress videos, and supplier bills.',
      iconUrl: 'https://cdn-icons-png.flaticon.com/512/873/873107.png',
      connectionStatus: IntegrationConnectionStatus.connected,
      environment: 'Production',
      connectedSince: DateTime(2024, 1, 1),
      lastSyncTimestamp: DateTime(2026, 9, 11, 14, 8),
      connectionOwner: 'Enterprise Super Admin',
      credentialsMap: {
        'Access Key ID': 'AKIA••••••••••••••••',
        'Secret Access Key': '••••••••••••••••••••••••77a1',
        'Bucket Name': 'homio-dam-vault-production-ap-south-1',
        'AWS Region': 'ap-south-1 (Mumbai)',
      },
      providerConfig: {
        'CDN CloudFront Distribution': 'd11a2837.cloudfront.net',
        'Max File Size Limit': '500 MB per single file',
        'Allowed MIME Types': 'Images (PNG, WEBP, JPG), PDF, DWG, RVT, MP4',
      },
      healthMetrics: const IntegrationHealthMetrics(
        uptimePercent: 100.0,
        totalRequests24h: 4200,
        successfulRequests24h: 4200,
        failedRequests24h: 0,
        latencyMs: 45,
      ),
      affectedWorkflowsOnDisable: [
        'Uploading 3D project renders and client approval documentation',
        'Site supervisors uploading live progress photos from mobile app',
      ],
    ),
    IntegrationService(
      id: 'int_gmaps',
      providerKey: 'google_maps_platform',
      name: 'Google Maps Geocoding & Distance Matrix',
      category: IntegrationCategory.mapsLocation,
      description: 'Site address autocomplete, geolocation geofencing for attendance check-ins, and technician travel mileage calculation.',
      iconUrl: 'https://cdn-icons-png.flaticon.com/512/2991/2991231.png',
      connectionStatus: IntegrationConnectionStatus.connected,
      environment: 'Production',
      connectedSince: DateTime(2024, 2, 1),
      lastSyncTimestamp: DateTime(2026, 9, 11, 13, 15),
      connectionOwner: 'Enterprise Super Admin',
      credentialsMap: {
        'API Key': 'AIzaSy••••••••••••••••••••••••99ab',
      },
      providerConfig: {
        'Active APIs': 'Geocoding API, Distance Matrix API, Places API (New)',
        'Geofence Radius': '150 Meters around project site',
        'Monthly API Budget Limit': '₹25,000 / month',
      },
      healthMetrics: const IntegrationHealthMetrics(
        uptimePercent: 99.99,
        totalRequests24h: 890,
        successfulRequests24h: 890,
        failedRequests24h: 0,
        latencyMs: 65,
      ),
      affectedWorkflowsOnDisable: [
        'Site supervisor GPS attendance validation',
        'Field visit travel allowance kilometer calculation',
      ],
    ),
    IntegrationService(
      id: 'int_openai',
      providerKey: 'openai_gemini_suite',
      name: 'Generative AI Suite (OpenAI & Gemini Pro)',
      category: IntegrationCategory.aiProviders,
      description: 'Multi-model LLM routing powering the AI Room Designer, Vastu Consultant, WhatsApp Lead Assistant, and BOQ auto-tagger.',
      iconUrl: 'https://cdn-icons-png.flaticon.com/512/12222/12222560.png',
      connectionStatus: IntegrationConnectionStatus.connected,
      environment: 'Production',
      connectedSince: DateTime(2024, 3, 1),
      lastSyncTimestamp: DateTime(2026, 9, 11, 14, 10),
      connectionOwner: 'Enterprise Super Admin',
      credentialsMap: {
        'Primary API Key (OpenAI)': 'sk-proj-••••••••••••••••••••••••11bb',
        'Fallback API Key (Google AI)': 'AIzaSy••••••••••••••••••••••••55cc',
      },
      providerConfig: {
        'Active Primary Model': 'gpt-4o (2024-08-06)',
        'Fallback Model': 'gemini-1.5-pro',
        'Temperature': '0.35 (Factual & grounded in Homio knowledge base)',
        'Max Monthly Token Cap': '150,000,000 Tokens',
      },
      healthMetrics: const IntegrationHealthMetrics(
        uptimePercent: 99.9,
        totalRequests24h: 1420,
        successfulRequests24h: 1418,
        failedRequests24h: 2,
        latencyMs: 820,
        lastErrorSummary: 'OpenAI Rate Limit Warning (auto-fallback triggered)',
      ),
      affectedWorkflowsOnDisable: [
        'AI WhatsApp Assistant real-time customer replies',
        'AI Room Visualizer prompt rendering and Vastu audit generator',
      ],
    ),
    IntegrationService(
      id: 'int_google_calendar',
      providerKey: 'google_workspace_calendar',
      name: 'Google Calendar & Google Meet Sync',
      category: IntegrationCategory.calendarVideo,
      description: 'Two-way synchronization of designer consultations, site visit bookings, and automated Google Meet links.',
      iconUrl: 'https://cdn-icons-png.flaticon.com/512/2991/2991147.png',
      connectionStatus: IntegrationConnectionStatus.actionRequired,
      environment: 'Production',
      connectedSince: DateTime(2024, 7, 10),
      lastSyncTimestamp: DateTime(2026, 9, 10, 18, 0),
      connectionOwner: 'Ar. Ananya Deshmukh',
      credentialsMap: {
        'OAuth Client ID': '918237461928-••••••••••••.apps.googleusercontent.com',
        'OAuth Client Secret': '••••••••••••••••••••••••22dd',
        'OAuth Refresh Token': '1//04••••••••••••••••••••••••ee',
      },
      providerConfig: {
        'Target Calendar': 'design-consultations@homio.in',
        'Auto-generate Meet Links': 'Enabled',
      },
      healthMetrics: const IntegrationHealthMetrics(
        uptimePercent: 94.5,
        totalRequests24h: 65,
        successfulRequests24h: 58,
        failedRequests24h: 7,
        latencyMs: 310,
        lastErrorSummary: 'OAuth Refresh Token Expired for design-consultations@homio.in',
        lastErrorTimestamp: null,
      ),
      affectedWorkflowsOnDisable: [
        'Automated Google Meet link generation in designer meeting invites',
      ],
    ),
  ];
}
