import 'admin_phase2_models.dart';

class AdminPhase2MockData {
  // ==========================================================================
  // 1. NOTIFICATION LOGS (25+ Realistic Activity Records)
  // ==========================================================================
  static final List<AdminNotificationLog> notifications = [
    AdminNotificationLog(
      id: 'notif_001',
      recipientName: 'Rahul Mehra',
      recipientRoleOrType: 'Customer',
      recipientContact: '+91 98450 11223',
      eventTitle: 'Design Presentation Meeting in 24 Hours',
      moduleName: 'Sales CRM & Meetings',
      channel: NotificationChannelType.whatsApp,
      relatedRecordType: 'Meeting',
      relatedRecordId: 'MTG-8821',
      relatedRecordTitle: '3D Walkthrough Review - Indiranagar Villa',
      messageBody: 'Hi Rahul, your interior design presentation is scheduled for tomorrow at 11:00 AM IST at Homio Experience Studio, Indiranagar. Please let us know if you need to reschedule.',
      templateCode: 'WT_MEETING_REMINDER_24H',
      sentAt: DateTime.now().subtract(const Duration(minutes: 14)),
      deliveryStatus: NotificationDeliveryStatus.read,
      isRead: true,
      readAt: DateTime.now().subtract(const Duration(minutes: 8)),
      triggeredBy: 'Automated Meeting Reminder Rule #1',
      technicalPayload: '{"provider": "WhatsApp Cloud API", "wamid": "wamid.HBgLMzk4NDUwMTEyMjMVAgASGBQzQT...==", "status": "read"}',
    ),
    AdminNotificationLog(
      id: 'notif_002',
      recipientName: 'Amit Verma (Sales Head)',
      recipientRoleOrType: 'Reporting Manager',
      recipientContact: 'amit.v@homio.in',
      eventTitle: 'High-Value Lead Assigned: Hiranandani Penthouse',
      moduleName: 'Sales CRM & Funnels',
      channel: NotificationChannelType.inApp,
      relatedRecordType: 'Lead',
      relatedRecordId: 'LD-9024',
      relatedRecordTitle: 'Ananya Roy (Est. ₹45 Lakhs)',
      messageBody: 'Lead LD-9024 has been assigned to Priya Nair. Budget: ₹45,00,000. Source: Meta Ads Campaign - Luxury Architecture.',
      sentAt: DateTime.now().subtract(const Duration(minutes: 32)),
      deliveryStatus: NotificationDeliveryStatus.delivered,
      isRead: true,
      readAt: DateTime.now().subtract(const Duration(minutes: 20)),
      triggeredBy: 'Lead Distribution Automation Rule #4',
    ),
    AdminNotificationLog(
      id: 'notif_003',
      recipientName: 'Vikramaditya Rao',
      recipientRoleOrType: 'Customer',
      recipientContact: '+91 97410 44556',
      eventTitle: 'Quotation Expiry Approaching in 48 Hours',
      moduleName: 'Quotation & Estimation',
      channel: NotificationChannelType.email,
      relatedRecordType: 'Quotation',
      relatedRecordId: 'Q-2026-0814',
      relatedRecordTitle: 'Turnkey Commercial Proposal v2',
      messageBody: 'Dear Vikramaditya, your customized commercial rate proposal Q-2026-0814 will expire on 13th Sept 2026. Review and confirm to lock in current woodwork and civil material pricing.',
      templateCode: 'EM_QUOTE_EXPIRY_WARNING',
      sentAt: DateTime.now().subtract(const Duration(hours: 1, minutes: 15)),
      deliveryStatus: NotificationDeliveryStatus.delivered,
      isRead: false,
      triggeredBy: 'Automated Quotation Expiry Alert',
    ),
    AdminNotificationLog(
      id: 'notif_004',
      recipientName: 'Kavita Sundaram',
      recipientRoleOrType: 'Finance Specialist',
      recipientContact: 'kavita.s@homio.in',
      eventTitle: 'Milestone Sign-Off: Payment Link Dispatched',
      moduleName: 'Finance & Payments',
      channel: NotificationChannelType.inApp,
      relatedRecordType: 'Payment',
      relatedRecordId: 'PAY-4410',
      relatedRecordTitle: 'Tranche 2: Woodwork Production (₹5,40,000)',
      messageBody: 'Customer verified False Ceiling completion. Razorpay payment request for ₹5,40,000 dispatched to Mrs. Sneha Patil.',
      sentAt: DateTime.now().subtract(const Duration(hours: 2, minutes: 40)),
      deliveryStatus: NotificationDeliveryStatus.delivered,
      isRead: true,
      readAt: DateTime.now().subtract(const Duration(hours: 1, minutes: 50)),
      triggeredBy: 'Milestone Completion Automation',
    ),
    AdminNotificationLog(
      id: 'notif_005',
      recipientName: 'Suresh Carpentry Works',
      recipientRoleOrType: 'Vendor / Contractor',
      recipientContact: '+91 98800 77112',
      eventTitle: 'Site Progress Upload Overdue: Brigade Gateway #402',
      moduleName: 'Site Execution & Civil',
      channel: NotificationChannelType.sms,
      relatedRecordType: 'Project',
      relatedRecordId: 'PRJ-401',
      relatedRecordTitle: 'Modular Kitchen Installation Squad',
      messageBody: 'Homio Ops: Daily site progress photos for PRJ-401 overdue. Please upload today\'s milestone photos by 7 PM to avoid SLA penalties.',
      sentAt: DateTime.now().subtract(const Duration(hours: 3, minutes: 10)),
      deliveryStatus: NotificationDeliveryStatus.delivered,
      isRead: false,
      triggeredBy: 'Site Milestone Daily Check SLA',
    ),
    AdminNotificationLog(
      id: 'notif_006',
      recipientName: 'Deepak Joshi',
      recipientRoleOrType: 'Customer',
      recipientContact: '+91 99160 33221',
      eventTitle: 'Payment Gateway Error on Tranche 1',
      moduleName: 'Finance & Payments',
      channel: NotificationChannelType.whatsApp,
      relatedRecordType: 'Payment',
      relatedRecordId: 'PAY-4399',
      relatedRecordTitle: 'Advance Booking Deposit ₹1,50,000',
      messageBody: 'Hi Deepak, we noticed an issue processing your UPI transfer. A refreshed Razorpay checkout link has been generated. Our team is on standby to assist.',
      sentAt: DateTime.now().subtract(const Duration(hours: 4, minutes: 5)),
      deliveryStatus: NotificationDeliveryStatus.failed,
      retryCount: 2,
      failureReason: 'Gateway timeout from recipient bank UPI switch. Auto-retry in progress.',
      triggeredBy: 'Payment Failure Recovery System',
      technicalPayload: '{"gateway": "RazorpayX", "errorCode": "GATEWAY_TIMEOUT", "httpStatus": 504}',
    ),
    AdminNotificationLog(
      id: 'notif_007',
      recipientName: 'Pooja Hegde',
      recipientRoleOrType: 'Interior Designer',
      recipientContact: 'pooja.h@homio.in',
      eventTitle: 'Client Requested 3D Rendering Revision',
      moduleName: 'Design Vault & DAM',
      channel: NotificationChannelType.push,
      relatedRecordType: 'Design',
      relatedRecordId: 'DSG-1092',
      relatedRecordTitle: 'Master Bedroom Wardrobe Elevation v3',
      messageBody: 'Client marked revision notes on Slide 4: "Change laminate from charcoal oak to Scandinavian fluted birch".',
      sentAt: DateTime.now().subtract(const Duration(hours: 5, minutes: 22)),
      deliveryStatus: NotificationDeliveryStatus.delivered,
      isRead: true,
      readAt: DateTime.now().subtract(const Duration(hours: 4, minutes: 45)),
      triggeredBy: 'Customer Portal Revision Action',
    ),
  ];

  // ==========================================================================
  // 2. NOTIFICATION RULES (Configurable System Events)
  // ==========================================================================
  static final List<NotificationRule> notificationRules = [
    NotificationRule(
      id: 'nr_001',
      ruleName: 'Meeting 24-Hour Automated Reminder',
      eventCode: 'MEETING_UPCOMING_24H',
      eventName: 'Meeting Scheduled: 24 Hours Prior',
      moduleName: 'Sales CRM & Funnels',
      description: 'Dispatches automated reminder via WhatsApp and Email 24 hours prior to scheduled client showroom consultation.',
      recipientType: NotificationRecipientType.customer,
      recipientTarget: 'Meeting Attendee (Primary Customer)',
      channels: [NotificationChannelType.whatsApp, NotificationChannelType.email],
      templateId: 'WT_MEETING_REMINDER_24H',
      triggerCondition: 'Meeting.status == "Confirmed" && hoursUntilMeeting == 24',
      scheduleOffset: '24 Hours Before Meeting',
      priority: 'High',
      isActive: true,
      isSystemMandatory: true,
    ),
    NotificationRule(
      id: 'nr_002',
      ruleName: 'Meeting 1-Hour Morning Flash Reminder',
      eventCode: 'MEETING_UPCOMING_1H',
      eventName: 'Meeting Scheduled: 1 Hour Prior',
      moduleName: 'Sales CRM & Funnels',
      description: 'Sends quick Google Maps location pin and staff coordinator contact 1 hour before meeting.',
      recipientType: NotificationRecipientType.customer,
      recipientTarget: 'Customer Mobile',
      channels: [NotificationChannelType.whatsApp, NotificationChannelType.sms],
      templateId: 'WT_MEETING_MAP_PIN',
      triggerCondition: 'Meeting.status == "Confirmed" && hoursUntilMeeting == 1',
      scheduleOffset: '1 Hour Before Meeting',
      priority: 'High',
      isActive: true,
      isSystemMandatory: false,
    ),
    NotificationRule(
      id: 'nr_003',
      ruleName: 'Quotation Expiry Imminent Escalation',
      eventCode: 'QUOTE_EXPIRING_SOON',
      eventName: 'Quotation Approaching 15-Day Expiry',
      moduleName: 'Quotation & Estimation',
      description: 'Alerts customer and sales executive 48h before commercial tariff locks expire.',
      recipientType: NotificationRecipientType.customer,
      recipientTarget: 'Customer & Assigned Sales Rep',
      channels: [NotificationChannelType.email, NotificationChannelType.inApp],
      templateId: 'EM_QUOTE_EXPIRY_WARNING',
      triggerCondition: 'Quotation.status == "Sent" && daysUntilExpiry <= 2',
      scheduleOffset: '48 Hours Before Expiry',
      priority: 'Medium',
      isActive: true,
    ),
    NotificationRule(
      id: 'nr_004',
      ruleName: 'Payment Overdue Recovery Notification',
      eventCode: 'PAYMENT_TRANCHE_OVERDUE',
      eventName: 'Payment Milestone Exceeds Grace Period',
      moduleName: 'Finance & Payments',
      description: 'Sends formal payment reminder to customer and triggers alert to Project Manager.',
      recipientType: NotificationRecipientType.customer,
      recipientTarget: 'Billing Contact',
      channels: [NotificationChannelType.whatsApp, NotificationChannelType.email, NotificationChannelType.inApp],
      templateId: 'WT_PAYMENT_OVERDUE',
      triggerCondition: 'Invoice.status == "Unpaid" && daysPastDue >= 3',
      scheduleOffset: 'Daily at 10:00 AM until paid',
      priority: 'Critical',
      isActive: true,
      isSystemMandatory: true,
    ),
    NotificationRule(
      id: 'nr_005',
      ruleName: 'Site Execution Delay Escalation',
      eventCode: 'SITE_TASK_OVERDUE',
      eventName: 'Milestone Work Delayed Beyond SLA',
      moduleName: 'Site Execution & Civil',
      description: 'Notifies Operations Head and Project Coordinator when civil/modular site task falls behind schedule.',
      recipientType: NotificationRecipientType.reportingManager,
      recipientTarget: 'Project Manager & Ops Lead',
      channels: [NotificationChannelType.inApp, NotificationChannelType.push],
      templateId: 'IN_APP_TASK_OVERDUE',
      triggerCondition: 'Task.isOverdue == true && Task.criticalPath == true',
      scheduleOffset: 'Immediate upon SLA breach',
      priority: 'High',
      isActive: true,
    ),
  ];

  // ==========================================================================
  // 3. USER NOTIFICATION PREFERENCES (Mandatory vs Optional Controls)
  // ==========================================================================
  static final List<UserNotificationPreference> defaultPreferences = [
    UserNotificationPreference(
      category: 'Critical Operational Alerts',
      title: 'Payment Confirmations & Security Codes',
      description: 'Transactional receipts, invoice copies, 2FA codes, and statutory billing receipts.',
      isMandatory: true,
      channelStates: {
        NotificationChannelType.inApp: true,
        NotificationChannelType.whatsApp: true,
        NotificationChannelType.email: true,
        NotificationChannelType.sms: true,
        NotificationChannelType.push: true,
      },
    ),
    UserNotificationPreference(
      category: 'Meeting & Calendar Reminders',
      title: 'Consultations & Studio Visits',
      description: '24-hour and 1-hour automated reminders for design walkthroughs and site meetings.',
      isMandatory: false,
      channelStates: {
        NotificationChannelType.inApp: true,
        NotificationChannelType.whatsApp: true,
        NotificationChannelType.email: true,
        NotificationChannelType.sms: false,
        NotificationChannelType.push: true,
      },
    ),
    UserNotificationPreference(
      category: 'Design & Engineering Updates',
      title: '3D Renderings & Specification Approvals',
      description: 'Notifications when designer uploads new moodboards or revisions requiring sign-off.',
      isMandatory: false,
      channelStates: {
        NotificationChannelType.inApp: true,
        NotificationChannelType.whatsApp: true,
        NotificationChannelType.email: true,
        NotificationChannelType.sms: false,
        NotificationChannelType.push: false,
      },
    ),
    UserNotificationPreference(
      category: 'Daily Site Progress',
      title: 'Photos, Snags & Quality Inspections',
      description: 'End-of-day site logs, material arrivals, and site milestone photo streams.',
      isMandatory: false,
      channelStates: {
        NotificationChannelType.inApp: true,
        NotificationChannelType.whatsApp: false,
        NotificationChannelType.email: false,
        NotificationChannelType.sms: false,
        NotificationChannelType.push: true,
      },
    ),
  ];

  // ==========================================================================
  // 4. WORKFLOW AUTOMATIONS (6 Production-Grade Workflows)
  // ==========================================================================
  static final List<WorkflowAutomation> automations = [
    WorkflowAutomation(
      id: 'auto_001',
      name: 'Meta Ads Lead Auto-Assignment & WhatsApp Welcome',
      module: 'Sales CRM & Funnels',
      triggerEvent: 'Lead Created',
      triggerDescription: 'WHEN a new lead is ingested from Meta Lead Ads or Google Campaign',
      status: AutomationStatus.active,
      conditions: [
        WorkflowCondition(field: 'Lead.source', operator: 'equals', value: 'Meta Lead Ads'),
        WorkflowCondition(field: 'Lead.city', operator: 'equals', value: 'Bengaluru', logicalOp: 'AND'),
      ],
      actions: [
        WorkflowAction(actionType: 'assign_lead', target: 'Round Robin: Bengaluru Sales Pod', description: 'Assign lead to next available Senior Consultant'),
        WorkflowAction(actionType: 'send_whatsapp', target: 'Lead Mobile', description: 'Dispatch Homio Welcome Brochure and Studio video link', templateId: 'WT_LEAD_WELCOME'),
        WorkflowAction(actionType: 'create_task', target: 'Assigned Consultant', description: 'Schedule Discovery Call within 15 minutes', delayString: 'Immediate'),
      ],
      lastRunAt: DateTime.now().subtract(const Duration(minutes: 18)),
      executionCount: 1420,
      failureCount: 4,
      createdBy: 'Amit Verma (Admin)',
      createdAt: DateTime(2026, 1, 15),
      updatedAt: DateTime(2026, 8, 20),
    ),
    WorkflowAutomation(
      id: 'auto_002',
      name: 'Design Walkthrough 24h & 1h Reminder Drip',
      module: 'Sales CRM & Funnels',
      triggerEvent: 'Meeting Scheduled',
      triggerDescription: 'WHEN a client consultation is booked on the Homio Calendar',
      status: AutomationStatus.active,
      conditions: [
        WorkflowCondition(field: 'Meeting.type', operator: 'equals', value: 'Design Walkthrough'),
      ],
      actions: [
        WorkflowAction(actionType: 'send_whatsapp', target: 'Customer', description: 'Send confirmation with calendar invite attachment', delayString: 'Immediate'),
        WorkflowAction(actionType: 'send_whatsapp', target: 'Customer', description: 'Send 24-hour reminder with designer portfolio', delayString: '24 Hours Before Meeting'),
        WorkflowAction(actionType: 'send_sms', target: 'Customer', description: 'Send Google Map Pin 1 hour before meeting', delayString: '1 Hour Before Meeting'),
      ],
      lastRunAt: DateTime.now().subtract(const Duration(hours: 1, minutes: 2)),
      executionCount: 890,
      failureCount: 1,
      createdBy: 'System Operations',
      createdAt: DateTime(2026, 2, 1),
      updatedAt: DateTime(2026, 7, 10),
    ),
    WorkflowAutomation(
      id: 'auto_003',
      name: 'Quotation Expiry Auto-Lock & Escalation',
      module: 'Quotation & Estimation',
      triggerEvent: 'Quotation Nearing Expiry',
      triggerDescription: 'WHEN a generated quotation reaches 13 days without client approval',
      status: AutomationStatus.active,
      conditions: [
        WorkflowCondition(field: 'Quotation.status', operator: 'equals', value: 'Sent'),
        WorkflowCondition(field: 'Quotation.daysOpen', operator: 'greater_than', value: '13', logicalOp: 'AND'),
      ],
      actions: [
        WorkflowAction(actionType: 'send_email', target: 'Customer', description: 'Warning: Pricing will revert to base tariffs in 48 hours', templateId: 'EM_QUOTE_EXPIRY'),
        WorkflowAction(actionType: 'create_task', target: 'Quotation Owner', description: 'Call client to offer optional valid extension or discount waiver'),
      ],
      lastRunAt: DateTime.now().subtract(const Duration(hours: 6)),
      executionCount: 312,
      failureCount: 0,
      createdBy: 'Priya Nair (Sales Ops)',
      createdAt: DateTime(2026, 3, 5),
      updatedAt: DateTime(2026, 8, 1),
    ),
    WorkflowAutomation(
      id: 'auto_004',
      name: 'Milestone 100% Sign-Off → Auto Payment Generation',
      module: 'Site Execution & Civil',
      triggerEvent: 'Milestone Approved',
      triggerDescription: 'WHEN Site Engineer and Customer mark milestone 100% inspected',
      status: AutomationStatus.active,
      conditions: [
        WorkflowCondition(field: 'Milestone.progress', operator: 'equals', value: '100%'),
        WorkflowCondition(field: 'Inspection.snagsPending', operator: 'equals', value: '0', logicalOp: 'AND'),
      ],
      actions: [
        WorkflowAction(actionType: 'request_payment', target: 'RazorpayX Integration', description: 'Generate invoice and encrypted payment link for next tranche'),
        WorkflowAction(actionType: 'send_whatsapp', target: 'Customer', description: 'Send digital inspection sign-off certificate and payment link'),
        WorkflowAction(actionType: 'send_notification', target: 'Finance Team', description: 'Notify Accounts Receivable of milestone completion'),
      ],
      lastRunAt: DateTime.now().subtract(const Duration(hours: 12)),
      executionCount: 204,
      failureCount: 2,
      createdBy: 'Rohan Sharma (Site Ops)',
      createdAt: DateTime(2026, 4, 12),
      updatedAt: DateTime(2026, 8, 15),
    ),
    WorkflowAutomation(
      id: 'auto_005',
      name: 'Weekly Automated Database Disaster Archive Dispatch',
      module: 'Platform Administration',
      triggerEvent: 'Weekly Cron Trigger',
      triggerDescription: 'WHEN Sunday 02:00 AM IST cron fires',
      status: AutomationStatus.active,
      conditions: [
        WorkflowCondition(field: 'System.dayOfWeek', operator: 'equals', value: 'Sunday'),
      ],
      actions: [
        WorkflowAction(actionType: 'create_backup', target: 'AWS S3 Vault', description: 'Dump PostgreSQL schemas, Mongo collections, encrypt with AES-256'),
        WorkflowAction(actionType: 'send_email', target: 'superadmin@homio.in', description: 'Dispatch download manifest, SHA-256 checksum and recovery token'),
      ],
      lastRunAt: DateTime.now().subtract(const Duration(days: 4)),
      nextRunAt: DateTime.now().add(const Duration(days: 3)),
      executionCount: 52,
      failureCount: 0,
      createdBy: 'System Root',
      createdAt: DateTime(2026, 1, 1),
      updatedAt: DateTime(2026, 6, 1),
    ),
    WorkflowAutomation(
      id: 'auto_006',
      name: 'Dormant Lead Follow-Up Drip Campaign',
      module: 'Sales CRM & Funnels',
      triggerEvent: 'Lead Inactive 7 Days',
      triggerDescription: 'WHEN no interaction recorded on qualified lead for 7 consecutive days',
      status: AutomationStatus.paused,
      conditions: [
        WorkflowCondition(field: 'Lead.daysInactive', operator: 'greater_than', value: '7'),
        WorkflowCondition(field: 'Lead.stage', operator: 'not_equals', value: 'Lost', logicalOp: 'AND'),
      ],
      actions: [
        WorkflowAction(actionType: 'send_whatsapp', target: 'Lead', description: 'Send inspirational lookbook: Top 10 Modular Kitchens 2026'),
      ],
      lastRunAt: DateTime.now().subtract(const Duration(days: 14)),
      executionCount: 618,
      failureCount: 12,
      createdBy: 'Marketing Automation Lead',
      createdAt: DateTime(2026, 2, 10),
      updatedAt: DateTime(2026, 8, 18),
    ),
  ];

  // ==========================================================================
  // 5. AUTOMATION EXECUTION HISTORY
  // ==========================================================================
  static final List<AutomationExecutionLog> executionLogs = [
    AutomationExecutionLog(
      id: 'exec_8801',
      automationId: 'auto_001',
      automationName: 'Meta Ads Lead Auto-Assignment & WhatsApp Welcome',
      executedAt: DateTime.now().subtract(const Duration(minutes: 18)),
      triggeredRecordType: 'Lead',
      triggeredRecordId: 'LD-9024',
      triggeredRecordTitle: 'Ananya Roy (Hiranandani Penthouse)',
      triggerEvent: 'Lead Ingested from Meta Webhook',
      result: AutomationExecutionResult.successful,
      actionsExecuted: [
        'Resolved Bengaluru pod (Next: Priya Nair)',
        'Assigned Lead LD-9024 to Priya Nair',
        'WhatsApp Welcome Brochure dispatched via Meta API',
        'Follow-up discovery call task created (Due in 15m)',
      ],
      durationFormatted: '480ms',
      stepTrace: 'Trigger Webhook → Condition Check (Meta == Meta: PASS, BLR == BLR: PASS) → Pod Assign → WhatsApp API (200 OK) → Task Insert (Done).',
    ),
    AutomationExecutionLog(
      id: 'exec_8802',
      automationId: 'auto_002',
      automationName: 'Design Walkthrough 24h & 1h Reminder Drip',
      executedAt: DateTime.now().subtract(const Duration(hours: 1, minutes: 2)),
      triggeredRecordType: 'Meeting',
      triggeredRecordId: 'MTG-8821',
      triggeredRecordTitle: '3D Walkthrough - Rahul Mehra',
      triggerEvent: 'Scheduler: 24h Before Meeting',
      result: AutomationExecutionResult.successful,
      actionsExecuted: [
        'Checked meeting confirmation status (Confirmed: PASS)',
        'WhatsApp reminder template WT_MEETING_REMINDER_24H sent to +91 98450 11223',
      ],
      durationFormatted: '310ms',
      stepTrace: 'Cron trigger → Condition Verified → Template populated with Rahul Mehra, 11:00 AM → Sent.',
    ),
    AutomationExecutionLog(
      id: 'exec_8803',
      automationId: 'auto_004',
      automationName: 'Milestone 100% Sign-Off → Auto Payment Generation',
      executedAt: DateTime.now().subtract(const Duration(hours: 12)),
      triggeredRecordType: 'Project',
      triggeredRecordId: 'PRJ-308',
      triggeredRecordTitle: 'Brigade Gateway 3BHK Renovation',
      triggerEvent: 'Milestone Completion Signed Off',
      result: AutomationExecutionResult.successful,
      actionsExecuted: [
        'Verified False Ceiling inspection certificate',
        'Generated Razorpay payment request for ₹5,40,000',
        'WhatsApp notification dispatched with payment URL',
        'Internal alert sent to Finance department',
      ],
      durationFormatted: '890ms',
      stepTrace: 'Inspection Verified → Gateway Invoice Created → Multi-channel notification dispatch complete.',
    ),
    AutomationExecutionLog(
      id: 'exec_8804',
      automationId: 'auto_001',
      automationName: 'Meta Ads Lead Auto-Assignment & WhatsApp Welcome',
      executedAt: DateTime.now().subtract(const Duration(hours: 16)),
      triggeredRecordType: 'Lead',
      triggeredRecordId: 'LD-9018',
      triggeredRecordTitle: 'Karan Shah (Whitefield Villa)',
      triggerEvent: 'Lead Ingested from Meta Webhook',
      result: AutomationExecutionResult.partiallySuccessful,
      actionsExecuted: [
        'Assigned Lead to Vikram Malhotra',
        'WhatsApp Welcome message failed (Invalid phone number format)',
        'Fallback email alert sent to Consultant to verify contact',
      ],
      durationFormatted: '1.2s',
      failureReason: 'WhatsApp Cloud API returned code 131026: Receiver phone number not registered on WhatsApp.',
      stepTrace: 'Trigger → Assignment OK → WhatsApp API 400 Bad Request → Fallback Triggered.',
    ),
  ];

  // ==========================================================================
  // 6. AUDIT LOGS (Immutable Traceability for Sensitive Events)
  // ==========================================================================
  static final List<AuditLogEntry> auditLogs = [
    AuditLogEntry(
      id: 'aud_9901',
      timestamp: DateTime.now().subtract(const Duration(minutes: 25)),
      userName: 'Amit Verma',
      userRole: 'Super Administrator',
      userEmail: 'amit.v@homio.in',
      actionTitle: 'Modified Commercial Rate for Item ISO-PLY-710',
      moduleName: 'Item / Rate Masters',
      recordType: 'ItemRate',
      recordId: 'rate_ply_710',
      recordTitle: 'Marine Grade BWR Ply 18mm',
      changeType: AuditChangeType.financialAction,
      ipAddress: '106.51.240.18',
      sessionLocation: 'Bengaluru, Karnataka (Desktop Chrome)',
      isSuccess: true,
      severity: AuditSeverity.critical,
      diffs: [
        AuditFieldDiff(fieldName: 'Selling Rate (₹/sqft)', previousValue: '₹145.00', newValue: '₹152.00'),
        AuditFieldDiff(fieldName: 'Gross Margin', previousValue: '26.8%', newValue: '29.2%'),
        AuditFieldDiff(fieldName: 'Revision Reason', previousValue: 'N/A', newValue: 'Q4 Tariff Escalation from Supplier Greenlam'),
      ],
      contextSummary: 'Commercial price update executed. Preserves 609 existing proposals under historical rate lock.',
    ),
    AuditLogEntry(
      id: 'aud_9902',
      timestamp: DateTime.now().subtract(const Duration(hours: 1, minutes: 40)),
      userName: 'Pooja Hegde',
      userRole: 'Lead Architect',
      userEmail: 'pooja.h@homio.in',
      actionTitle: 'Submitted Design Version v3.1 for Client Sign-Off',
      moduleName: 'Design Vault & DAM',
      recordType: 'DesignSpec',
      recordId: 'DSG-1092',
      recordTitle: 'Master Bedroom Wardrobe Elevation',
      changeType: AuditChangeType.update,
      ipAddress: '49.207.214.55',
      sessionLocation: 'Bengaluru Studio (MacOS Safari)',
      isSuccess: true,
      severity: AuditSeverity.info,
      diffs: [
        AuditFieldDiff(fieldName: 'Version', previousValue: 'v2.8', newValue: 'v3.1'),
        AuditFieldDiff(fieldName: 'Finish Spec', previousValue: 'Charcoal Oak', newValue: 'Scandinavian Fluted Birch'),
        AuditFieldDiff(fieldName: 'File Hash', previousValue: 'e81a3d90...', newValue: 'fa990c88...', isSensitiveMasked: true),
      ],
      contextSummary: 'Client revision incorporated following walkthrough notes.',
    ),
    AuditLogEntry(
      id: 'aud_9903',
      timestamp: DateTime.now().subtract(const Duration(hours: 3, minutes: 12)),
      userName: 'Kavita Sundaram',
      userRole: 'Finance Specialist',
      userEmail: 'kavita.s@homio.in',
      actionTitle: 'Recorded Cheque Payment of ₹5,40,000',
      moduleName: 'Finance & Payments',
      recordType: 'PaymentRecord',
      recordId: 'PAY-4410',
      recordTitle: 'Milestone 2 Woodwork Tranche',
      changeType: AuditChangeType.financialAction,
      ipAddress: '106.51.240.18',
      sessionLocation: 'Bengaluru Central Office',
      isSuccess: true,
      severity: AuditSeverity.critical,
      diffs: [
        AuditFieldDiff(fieldName: 'Status', previousValue: 'Payment Requested', newValue: 'Cleared / Settled'),
        AuditFieldDiff(fieldName: 'Payment Mode', previousValue: 'Pending', newValue: 'NEFT Transfer (HDFC Bank)'),
        AuditFieldDiff(fieldName: 'Bank Ref #', previousValue: 'None', newValue: 'HDFC982173618', isSensitiveMasked: true),
      ],
      contextSummary: 'Client invoice marked paid in full. Ledger entry reconciled with RazorpayX account.',
    ),
    AuditLogEntry(
      id: 'aud_9904',
      timestamp: DateTime.now().subtract(const Duration(hours: 5, minutes: 50)),
      userName: 'Amit Verma',
      userRole: 'Super Administrator',
      userEmail: 'amit.v@homio.in',
      actionTitle: 'Updated Granular Permission Matrix for "Site Supervisor"',
      moduleName: 'Users & RBAC',
      recordType: 'AdminRole',
      recordId: 'role_site_sup',
      recordTitle: 'Site Supervisor (Civil Ops)',
      changeType: AuditChangeType.permissionChange,
      ipAddress: '106.51.240.18',
      sessionLocation: 'Bengaluru Central Office',
      isSuccess: true,
      severity: AuditSeverity.critical,
      diffs: [
        AuditFieldDiff(fieldName: 'Customer Phone Masking', previousValue: 'Full Access (Unmasked)', newValue: 'Masked Partial (Enforced)'),
        AuditFieldDiff(fieldName: 'Can Delete Material Requisition', previousValue: 'True', newValue: 'False'),
      ],
      contextSummary: 'Security compliance policy enforced: Customer phone numbers now hidden for field contractors.',
    ),
    AuditLogEntry(
      id: 'aud_9905',
      timestamp: DateTime.now().subtract(const Duration(hours: 8, minutes: 15)),
      userName: 'Rohan Sharma',
      userRole: 'Project Manager',
      userEmail: 'rohan.s@homio.in',
      actionTitle: 'Archived Obsolete Quotation Draft Q-2026-0740',
      moduleName: 'Quotation & Estimation',
      recordType: 'Quotation',
      recordId: 'Q-2026-0740',
      recordTitle: 'Draft Quote: Hiranandani Villa v1',
      changeType: AuditChangeType.delete,
      ipAddress: '157.49.122.9',
      sessionLocation: 'Bengaluru, India',
      isSuccess: true,
      severity: AuditSeverity.warning,
      diffs: [
        AuditFieldDiff(fieldName: 'State', previousValue: 'Draft Proposal', newValue: 'Archived (Soft Delete)'),
      ],
      contextSummary: 'Superseded by Version 2. Proposal removed from live pipeline.',
    ),
    AuditLogEntry(
      id: 'aud_9906',
      timestamp: DateTime.now().subtract(const Duration(hours: 14)),
      userName: 'System Root',
      userRole: 'Automated Automation Engine',
      userEmail: 'system@homio.in',
      actionTitle: 'Dispatched Automated WhatsApp Reminder to Lead',
      moduleName: 'Automations Engine',
      recordType: 'WorkflowAutomation',
      recordId: 'auto_001',
      recordTitle: 'Meta Ads Auto Assignment',
      changeType: AuditChangeType.systemConfig,
      ipAddress: '127.0.0.1 (Internal Worker)',
      sessionLocation: 'AWS EC2 Production Cluster (Mumbai)',
      isSuccess: true,
      severity: AuditSeverity.info,
      diffs: [
        AuditFieldDiff(fieldName: 'Actions Executed', previousValue: '0', newValue: '4'),
      ],
      contextSummary: 'Automated trigger completed in 480ms without human intervention.',
    ),
  ];

  // ==========================================================================
  // 7. BACKUP & RECOVERY RECORDS
  // ==========================================================================
  static final List<BackupRecord> backups = [
    BackupRecord(
      id: 'bck_001',
      backupCode: 'HOMIO-DB-SNAP-20260907-0200',
      type: BackupType.scheduled,
      startedAt: DateTime(2026, 9, 7, 2, 0),
      completedAt: DateTime(2026, 9, 7, 2, 4, 18),
      durationFormatted: '4m 18s',
      sizeMb: 174.6,
      status: BackupJobStatus.completed,
      storageLocation: 'AWS S3 Vault (ap-south-1 Mumbai)',
      retentionUntil: DateTime(2026, 12, 6),
      sha256Checksum: '8e71a9f0293bcf9128a8d9102484918e9fa014299b8214812a890123ef71a8bc',
      destinationEmail: 'superadmin@homio.in, compliance@homio.in',
      createdBy: 'Scheduled Weekly Automation',
    ),
    BackupRecord(
      id: 'bck_002',
      backupCode: 'HOMIO-DB-MANUAL-20260904-1620',
      type: BackupType.manual,
      startedAt: DateTime(2026, 9, 4, 16, 20),
      completedAt: DateTime(2026, 9, 4, 16, 22, 10),
      durationFormatted: '2m 10s',
      sizeMb: 171.2,
      status: BackupJobStatus.completed,
      storageLocation: 'AWS S3 Vault (ap-south-1 Mumbai)',
      retentionUntil: DateTime(2026, 12, 3),
      sha256Checksum: '7fa0c98fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852e128',
      destinationEmail: 'superadmin@homio.in',
      createdBy: 'Amit Verma (Admin)',
    ),
    BackupRecord(
      id: 'bck_003',
      backupCode: 'HOMIO-DB-PRE-RESTORE-20260831-0130',
      type: BackupType.preRestore,
      startedAt: DateTime(2026, 8, 31, 1, 30),
      completedAt: DateTime(2026, 8, 31, 1, 34, 5),
      durationFormatted: '4m 5s',
      sizeMb: 168.9,
      status: BackupJobStatus.completed,
      storageLocation: 'AWS S3 Vault (ap-south-1 Mumbai)',
      retentionUntil: DateTime(2026, 11, 29),
      sha256Checksum: '319a8bc459021e8fa24098bc1902847190ac4819024890192840918239019283',
      destinationEmail: 'superadmin@homio.in',
      createdBy: 'System Pre-Restore Safety Guard',
    ),
    BackupRecord(
      id: 'bck_004',
      backupCode: 'HOMIO-DB-SNAP-20260824-0200',
      type: BackupType.scheduled,
      startedAt: DateTime(2026, 8, 24, 2, 0),
      completedAt: DateTime(2026, 8, 24, 2, 4, 30),
      durationFormatted: '4m 30s',
      sizeMb: 164.2,
      status: BackupJobStatus.completed,
      storageLocation: 'AWS S3 Vault (ap-south-1 Mumbai)',
      retentionUntil: DateTime(2026, 11, 22),
      sha256Checksum: '9081248091823091823091823091823091823091823091823091823091823091',
      destinationEmail: 'superadmin@homio.in, compliance@homio.in',
      createdBy: 'Scheduled Weekly Automation',
    ),
  ];

  static final List<RestoreTestLog> restoreTests = [
    RestoreTestLog(
      id: 'test_001',
      testDate: DateTime(2026, 9, 5, 11, 30),
      backupTestedCode: 'HOMIO-DB-MANUAL-20260904-1620',
      isSuccessful: true,
      durationFormatted: '3m 12s in Isolated Sandbox',
      validatedBy: 'DevOps & DBA Lead (Kiran Rao)',
      testNotes: 'Sandbox database spun up successfully. 100% table schemas, foreign keys, and indexes verified against current production commit.',
    ),
    RestoreTestLog(
      id: 'test_002',
      testDate: DateTime(2026, 8, 15, 14, 0),
      backupTestedCode: 'HOMIO-DB-SNAP-20260810-0200',
      isSuccessful: true,
      durationFormatted: '3m 28s in Isolated Sandbox',
      validatedBy: 'Compliance Officer (Rajesh S)',
      testNotes: 'Quarterly ISO-27001 data recovery drill passed. Checksum match verified.',
    ),
  ];

  // ==========================================================================
  // 8. SYSTEM SETTINGS DEFAULTS
  // ==========================================================================
  static const OrganizationSettings defaultOrgSettings = OrganizationSettings(
    orgName: 'Homio Technologies Private Limited',
    legalName: 'Homio Turnkey Architecture & Interior Solutions Pvt. Ltd.',
    logoUrl: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=100',
    businessAddress: 'Homio Headquarters, 4th Floor, Salarpuria Towers, Indiranagar 100ft Road, Bengaluru, Karnataka - 560038',
    contactEmail: 'contact@homio.in',
    supportPhone: '+91 (080) 4122-8900',
    website: 'https://homio.in',
    gstNumber: '29AAACH7821Q1Z4',
    defaultCurrency: 'INR (₹ - Indian Rupee)',
    defaultTimezone: 'Asia/Kolkata (IST +05:30)',
  );

  static const SecuritySettings defaultSecuritySettings = SecuritySettings(
    sessionTimeoutMinutes: 60,
    maxLoginAttemptsBeforeLockout: 5,
    lockoutDurationMinutes: 30,
    passwordMinLength: 10,
    requireSpecialCharacters: true,
    requireTwoFactorAuthForAdmins: true,
    enforceIpAllowlistForFinance: false,
  );

  static const CommercialDefaults defaultCommercialSettings = CommercialDefaults(
    standardPaymentTerms: '10% Advance Booking, 40% Woodwork Production, 40% Installation, 10% Handover',
    quotationValidityDays: 15,
    invoiceGracePeriodDays: 7,
    maxExecutiveDiscountPercent: 5.0,
    requireManagerApprovalAboveDiscount: true,
  );

  static const OperationalBusinessRules defaultBusinessRules = OperationalBusinessRules(
    workingDaysSummary: 'Monday to Saturday (6 Working Days)',
    businessStartTime: '09:30 AM',
    businessEndTime: '07:00 PM',
    weekendHandling: 'Auto-shift overdue task deadlines to Monday 10:00 AM',
    defaultSlaFollowUpHours: 4,
    meetingReminderHoursBefore: 24,
  );
}
