import 'system_admin_models.dart';

class SystemAdminMockData {
  // 1. Core Platform RBAC Permissions
  static final List<RbacPermissionRow> rbacPermissions = [
    const RbacPermissionRow(
      id: 'RBAC-01',
      moduleCode: 'MOD-SALES',
      moduleName: 'Sales CRM & Lead Funnels',
      category: AdminModuleCategory.sales,
      canView: true,
      canCreate: true,
      canEdit: true,
      canDelete: false,
      canExport: false,
      canApprove: false,
      isFieldIsolated: true, // Junior staff restricted to My Leads Only
      phoneMasking: FieldMaskLevel.maskedPartial,
      marginVisibility: FieldMaskLevel.hidden,
      canOverrideCost: false,
    ),
    const RbacPermissionRow(
      id: 'RBAC-02',
      moduleCode: 'MOD-QUOTATION',
      moduleName: 'Quotation Engine & Estimation',
      category: AdminModuleCategory.quotation,
      canView: true,
      canCreate: true,
      canEdit: true,
      canDelete: false,
      canExport: true,
      canApprove: false,
      isFieldIsolated: true,
      phoneMasking: FieldMaskLevel.maskedPartial,
      marginVisibility: FieldMaskLevel.hidden,
      canOverrideCost: false, // Prevents unauthorized price cuts
    ),
    const RbacPermissionRow(
      id: 'RBAC-03',
      moduleCode: 'MOD-DAM',
      moduleName: 'Design Deliverable DAM & 3D Vault',
      category: AdminModuleCategory.dam,
      canView: true,
      canCreate: true,
      canEdit: true,
      canDelete: false,
      canExport: true,
      canApprove: true,
      isFieldIsolated: false,
      phoneMasking: FieldMaskLevel.fullAccess,
      marginVisibility: FieldMaskLevel.fullAccess,
      canOverrideCost: false,
    ),
    const RbacPermissionRow(
      id: 'RBAC-04',
      moduleCode: 'MOD-EXEC',
      moduleName: 'Site Execution & Turnkey Civil',
      category: AdminModuleCategory.execution,
      canView: true,
      canCreate: true,
      canEdit: true,
      canDelete: false,
      canExport: true,
      canApprove: true,
      isFieldIsolated: true,
      phoneMasking: FieldMaskLevel.fullAccess,
      marginVisibility: FieldMaskLevel.maskedPartial,
      canOverrideCost: false,
    ),
    const RbacPermissionRow(
      id: 'RBAC-05',
      moduleCode: 'MOD-SERVICE',
      moduleName: 'After-Sales Service & 10-Yr Warranty',
      category: AdminModuleCategory.service,
      canView: true,
      canCreate: true,
      canEdit: true,
      canDelete: false,
      canExport: true,
      canApprove: true,
      isFieldIsolated: true,
      phoneMasking: FieldMaskLevel.fullAccess,
      marginVisibility: FieldMaskLevel.hidden,
      canOverrideCost: false,
    ),
    const RbacPermissionRow(
      id: 'RBAC-06',
      moduleCode: 'MOD-HRMS',
      moduleName: 'HRMS, Geofencing & Biometrics',
      category: AdminModuleCategory.hrms,
      canView: true,
      canCreate: false,
      canEdit: false,
      canDelete: false,
      canExport: false,
      canApprove: false,
      isFieldIsolated: false,
      phoneMasking: FieldMaskLevel.maskedPartial,
      marginVisibility: FieldMaskLevel.hidden,
      canOverrideCost: false,
    ),
    const RbacPermissionRow(
      id: 'RBAC-07',
      moduleCode: 'MOD-FINANCE',
      moduleName: 'Client Ledgers & Milestone Invoices',
      category: AdminModuleCategory.accounting,
      canView: false,
      canCreate: false,
      canEdit: false,
      canDelete: false,
      canExport: false,
      canApprove: false,
      isFieldIsolated: true,
      phoneMasking: FieldMaskLevel.hidden,
      marginVisibility: FieldMaskLevel.hidden,
      canOverrideCost: false,
    ),
    const RbacPermissionRow(
      id: 'RBAC-08',
      moduleCode: 'MOD-MARKET',
      moduleName: 'Wholesale Materials & Index',
      category: AdminModuleCategory.marketplace,
      canView: true,
      canCreate: false,
      canEdit: false,
      canDelete: false,
      canExport: true,
      canApprove: false,
      isFieldIsolated: false,
      phoneMasking: FieldMaskLevel.fullAccess,
      marginVisibility: FieldMaskLevel.fullAccess,
      canOverrideCost: false,
    ),
    const RbacPermissionRow(
      id: 'RBAC-09',
      moduleCode: 'MOD-AI-SUITE',
      moduleName: 'AI Architectural Suite & Vastu',
      category: AdminModuleCategory.aiSuite,
      canView: true,
      canCreate: true,
      canEdit: true,
      canDelete: false,
      canExport: true,
      canApprove: false,
      isFieldIsolated: false,
      phoneMasking: FieldMaskLevel.fullAccess,
      marginVisibility: FieldMaskLevel.fullAccess,
      canOverrideCost: false,
    ),
  ];

  // 2. Master Rate Cards & Margins
  static final List<MasterRateCardItem> masterRateCards = [
    MasterRateCardItem(
      id: 'RATE-01',
      itemCode: 'WD-PLY-01',
      itemName: 'BWP Marine Grade Plywood (IS:710)',
      category: RateCategory.modularWoodwork,
      subCategory: 'Carcass Core Substrates',
      unit: RateUnitType.sqft,
      materialCost: 118.0,
      contractorLaborRate: 45.0,
      recommendedSellingPrice: 220.0,
      preferredBrand: 'CenturyPly Club Prime / Greenlam',
      technicalSpecification: '16mm/19mm boiling waterproof calibrated sheet with 25-yr guarantee',
      lastUpdated: DateTime(2026, 8, 15),
    ),
    MasterRateCardItem(
      id: 'RATE-02',
      itemCode: 'WD-LAM-01',
      itemName: '1.0mm Zero-Scratch Suede Matte Laminate',
      category: RateCategory.modularWoodwork,
      subCategory: 'Surface Shutter Finishes',
      unit: RateUnitType.sqft,
      materialCost: 52.0,
      contractorLaborRate: 30.0,
      recommendedSellingPrice: 125.0,
      preferredBrand: 'Merino / Royale Touche',
      technicalSpecification: 'Anti-bacterial, anti-fingerprint thermal resistant laminate sheet',
      lastUpdated: DateTime(2026, 8, 20),
    ),
    MasterRateCardItem(
      id: 'RATE-03',
      itemCode: 'WD-ACR-01',
      itemName: '2.0mm High Gloss Seamless Acrylic Finish',
      category: RateCategory.modularWoodwork,
      subCategory: 'Premium Shutter Finishes',
      unit: RateUnitType.sqft,
      materialCost: 140.0,
      contractorLaborRate: 50.0,
      recommendedSellingPrice: 280.0,
      preferredBrand: 'Senosan Glass Acrylic',
      technicalSpecification: 'Mirror gloss UV-cured acrylic with matching edge band tape',
      lastUpdated: DateTime(2026, 8, 25),
    ),
    MasterRateCardItem(
      id: 'RATE-04',
      itemCode: 'FC-GYP-01',
      itemName: 'Gyproc Seamless False Ceiling with Cove Light Profile',
      category: RateCategory.falseCeiling,
      subCategory: 'Ceiling Architecture',
      unit: RateUnitType.sqft,
      materialCost: 58.0,
      contractorLaborRate: 42.0,
      recommendedSellingPrice: 145.0,
      preferredBrand: 'Saint-Gobain Gyproc Elite',
      technicalSpecification: '12.5mm moisture-resistant gypsum boards with GI perimeter channel frame',
      lastUpdated: DateTime(2026, 8, 12),
    ),
    MasterRateCardItem(
      id: 'RATE-05',
      itemCode: 'PNT-ROY-01',
      itemName: 'Asian Paints Royale Luxury Velvet Emulsion',
      category: RateCategory.paintingPolishing,
      subCategory: 'Interior Wall Finishing',
      unit: RateUnitType.sqft,
      materialCost: 24.0,
      contractorLaborRate: 18.0,
      recommendedSellingPrice: 58.0,
      preferredBrand: 'Asian Paints Royale Luxury',
      technicalSpecification: '2 coats acrylic primer + 2 coats luxury velvet topcoat with washable Teflon',
      lastUpdated: DateTime(2026, 8, 18),
    ),
    MasterRateCardItem(
      id: 'RATE-06',
      itemCode: 'CIV-TL-01',
      itemName: 'Italian Marble 800x1600mm Vitrified Floor Tiling',
      category: RateCategory.civilFlooring,
      subCategory: 'Flooring Masonry',
      unit: RateUnitType.sqft,
      materialCost: 110.0,
      contractorLaborRate: 55.0,
      recommendedSellingPrice: 235.0,
      preferredBrand: 'Kajaria / Simpolo Glazed Vitrified',
      technicalSpecification: 'GVT high-gloss rectified porcelain tile with epoxy joint grout',
      lastUpdated: DateTime(2026, 8, 22),
    ),
    MasterRateCardItem(
      id: 'RATE-07',
      itemCode: 'ELC-SMT-01',
      itemName: 'Smart Zigbee Touch Switchboard Retrofit (8-Module)',
      category: RateCategory.electricalLighting,
      subCategory: 'Home Automation',
      unit: RateUnitType.nos,
      materialCost: 2800.0,
      contractorLaborRate: 600.0,
      recommendedSellingPrice: 4800.0,
      preferredBrand: 'Schneider AvatarOn / Legrand Arteor',
      technicalSpecification: 'Capacitive touch tempered glass faceplate with voice assistant relay',
      lastUpdated: DateTime(2026, 8, 28),
    ),
    MasterRateCardItem(
      id: 'RATE-08',
      itemCode: 'PLM-SN-01',
      itemName: 'Concealed Diverter Single-Lever Hot/Cold Shower Set',
      category: RateCategory.plumbingSanitary,
      subCategory: 'Bathroom Brassware',
      unit: RateUnitType.nos,
      materialCost: 5200.0,
      contractorLaborRate: 1400.0,
      recommendedSellingPrice: 9200.0,
      preferredBrand: 'Kohler July / Jaquar Alive',
      technicalSpecification: 'Brass body thermostatic mixer with 300mm rain shower arm',
      lastUpdated: DateTime(2026, 8, 10),
    ),
    MasterRateCardItem(
      id: 'RATE-09',
      itemCode: 'GLS-PRT-01',
      itemName: '10mm Toughened Glass Shower Partition with Fluted Profile',
      category: RateCategory.glassHardware,
      subCategory: 'Wet Area Glasswork',
      unit: RateUnitType.sqft,
      materialCost: 240.0,
      contractorLaborRate: 85.0,
      recommendedSellingPrice: 460.0,
      preferredBrand: 'Saint-Gobain Planilaque / Ozone Hardware',
      technicalSpecification: 'Tempered safety glass with matte black anodized SS-304 stabilizing bars',
      lastUpdated: DateTime(2026, 9, 01),
    ),
  ];

  // 3. Margin Tier Protection Rules
  static final List<MarginTierRule> marginRules = [
    const MarginTierRule(
      id: 'TIER-01',
      tierName: 'Standard Turnkey Homes',
      budgetRange: '₹12 Lakhs - ₹25 Lakhs',
      targetGrossMargin: 24.0,
      minimumFloorMargin: 14.0,
      approverRole: 'Sales Head Sign-off Required if < 18%',
    ),
    const MarginTierRule(
      id: 'TIER-02',
      tierName: 'Luxury Villas & Penthouse Suite',
      budgetRange: '₹25 Lakhs - ₹75 Lakhs',
      targetGrossMargin: 32.0,
      minimumFloorMargin: 20.0,
      approverRole: 'Managing Director Approval Required if < 25%',
    ),
    const MarginTierRule(
      id: 'TIER-03',
      tierName: 'Commercial Boutique Studios',
      budgetRange: '₹15 Lakhs - ₹50 Lakhs',
      targetGrossMargin: 28.0,
      minimumFloorMargin: 16.0,
      approverRole: 'Finance Controller Sign-off Required if < 20%',
    ),
  ];

  // 4. WhatsApp Conversational AI Configuration
  static final AiTrainingConfig aiConfig = AiTrainingConfig(
    systemPrompt: '''You are "Homio Aura", an elite senior interior architecture consultant representing Homio Turnkey Interiors.
Your objective is to qualify luxury homeowners, understand their floorplan requirements (2BHK, 3BHK, Villa, Penthouse), provide high-level transparent cost insights, and book a 30-minute studio consultation with a dedicated Project Manager.

Rules:
1. Always maintain a warm, ultra-luxurious, and transparent architectural tone.
2. Emphasize Homio's 10-Year Structural Warranty, zero-hidden-fee guarantee, and 45-day on-time delivery commitment.
3. If the user asks for quotes, guide them through material choices (BWP Marine Ply vs Commercial Ply, Acrylic vs Laminate) before estimating.
4. Maximum allowable discount offer is strictly 5.0% on advance token sign-off.
5. If the client mentions a budget exceeding ₹50 Lakhs or exhibits dissatisfaction, trigger human manager handoff immediately.''',
    modelName: 'Gemini 1.5 Flash (Enterprise WhatsApp Gateway)',
    temperature: 0.35,
    maxDiscountPercent: 5.0,
    primaryTone: 'Luxury Professional & Consultative',
    supportedLanguages: ['English', 'Hindi (Hinglish)', 'Tamil', 'Kannada'],
    humanEscalationKeywords: [
      'urgent',
      'dispute',
      'refund',
      'call manager',
      'lawyer',
      'budget > 50L',
      'site accident',
      'poor quality',
    ],
    activeSnippetsCount: 18,
  );

  // 5. WhatsApp AI Knowledge Base Snippets
  static final List<AiKnowledgeSnippet> knowledgeSnippets = [
    AiKnowledgeSnippet(
      id: 'KB-01',
      title: 'Starting Pricing & Turnkey Packages',
      category: 'Pricing Policy',
      questionPattern: 'How much does a 3BHK interior cost? / What are your starting prices?',
      responseBody: 'Our turnkey 3BHK interiors typically range from ₹12 Lakhs to ₹28 Lakhs depending on the selected finish tier (Essential, Premium, or Luxury). This includes complete modular kitchen, master wardrobes, false ceiling with warm coves, and premium painting.',
      isVerified: true,
      lastUpdated: DateTime(2026, 8, 25),
    ),
    AiKnowledgeSnippet(
      id: 'KB-02',
      title: 'Local Carpenter vs Homio Factory Turnkey',
      category: 'Objection Handling',
      questionPattern: 'Why are you more expensive than local freelance carpenters?',
      responseBody: 'Unlike unorganized carpenters who hand-press glue on-site leading to bubbling and delays, Homio uses German CNC laser edge-banding with zero glue lines, certified CenturyPly BWP marine ply, a legally binding 45-day handover SLA, and an insured 10-Year Structural Warranty.',
      isVerified: true,
      lastUpdated: DateTime(2026, 8, 28),
    ),
    AiKnowledgeSnippet(
      id: 'KB-03',
      title: '10-Year Structural Warranty Coverage',
      category: 'FAQ',
      questionPattern: 'What is covered in the 10-year warranty?',
      responseBody: 'Our 10-Year Structural Warranty covers all internal plywood carcasses against termite infestation, borers, and delamination. Hardware like Hafele/Hettich hinges comes with a lifetime manufacturer warranty. Turnkey finishes have a 1-year complimentary snag repair period.',
      isVerified: true,
      lastUpdated: DateTime(2026, 8, 14),
    ),
    AiKnowledgeSnippet(
      id: 'KB-04',
      title: 'Milestone Stage Payment Plan',
      category: 'Pricing Policy',
      questionPattern: 'How do payments work? Do I pay upfront?',
      responseBody: 'We follow an ultra-safe milestone escrow framework: 10% on design booking, 40% upon 3D render approval before factory manufacturing, 40% on material delivery at site, and the final 10% only after your satisfactory handover inspection.',
      isVerified: true,
      lastUpdated: DateTime(2026, 8, 22),
    ),
    AiKnowledgeSnippet(
      id: 'KB-05',
      title: 'Sobha Dream Acres Portfolio Proof Point',
      category: 'Case Study',
      questionPattern: 'Have you worked in Sobha or DLF properties?',
      responseBody: 'Yes! We recently handed over Unit 1402 at Sobha Dream Acres (1,450 sqft 3BHK) featuring Scandinavian fluted panelling and Blum tandem drawers, completed in exactly 38 calendar days with a 9.6/10 CSAT rating.',
      isVerified: true,
      lastUpdated: DateTime(2026, 9, 02),
    ),
  ];

  // 6. Automated Disaster Recovery Backup Logs
  static final List<DisasterBackupLog> disasterBackupLogs = [
    DisasterBackupLog(
      id: 'BCK-2026-09-06',
      backupCode: 'HOMIO-DB-SNAP-20260906-0000',
      timestamp: DateTime(2026, 9, 6, 0, 0),
      triggerType: 'Weekly Automated Cron',
      sizeMb: 164.8,
      includedFormats: ['Excel (.xlsx)', 'SQL Dump (.sql.gz)', 'Media Manifest (.json)'],
      sha256Checksum: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
      destinationEmail: 'superadmin@homio.in, compliance@homio.in',
      status: BackupStatus.completed,
      durationFormatted: '1m 42s',
    ),
    DisasterBackupLog(
      id: 'BCK-2026-08-30',
      backupCode: 'HOMIO-DB-SNAP-20260830-0000',
      timestamp: DateTime(2026, 8, 30, 0, 0),
      triggerType: 'Weekly Automated Cron',
      sizeMb: 158.2,
      includedFormats: ['Excel (.xlsx)', 'SQL Dump (.sql.gz)', 'Media Manifest (.json)'],
      sha256Checksum: 'a89c89283f6f534bc7e4c3d234a9b23f27ae41e4649b934ca495991b7852b112',
      destinationEmail: 'superadmin@homio.in, compliance@homio.in',
      status: BackupStatus.completed,
      durationFormatted: '1m 38s',
    ),
    DisasterBackupLog(
      id: 'BCK-2026-08-23',
      backupCode: 'HOMIO-DB-SNAP-20260823-0000',
      timestamp: DateTime(2026, 8, 23, 0, 0),
      triggerType: 'Weekly Automated Cron',
      sizeMb: 151.6,
      includedFormats: ['Excel (.xlsx)', 'SQL Dump (.sql.gz)', 'Media Manifest (.json)'],
      sha256Checksum: 'c12d45a98fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852c994',
      destinationEmail: 'superadmin@homio.in, compliance@homio.in',
      status: BackupStatus.completed,
      durationFormatted: '1m 35s',
    ),
    DisasterBackupLog(
      id: 'BCK-2026-08-16',
      backupCode: 'HOMIO-DB-SNAP-20260816-0000',
      timestamp: DateTime(2026, 8, 16, 0, 0),
      triggerType: 'Weekly Automated Cron',
      sizeMb: 146.4,
      includedFormats: ['Excel (.xlsx)', 'SQL Dump (.sql.gz)', 'Media Manifest (.json)'],
      sha256Checksum: 'f789e22498fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852da01',
      destinationEmail: 'superadmin@homio.in, compliance@homio.in',
      status: BackupStatus.completed,
      durationFormatted: '1m 31s',
    ),
    DisasterBackupLog(
      id: 'BCK-2026-08-09',
      backupCode: 'HOMIO-DB-SNAP-20260809-0000',
      timestamp: DateTime(2026, 8, 9, 0, 0),
      triggerType: 'Weekly Automated Cron',
      sizeMb: 140.1,
      includedFormats: ['Excel (.xlsx)', 'SQL Dump (.sql.gz)', 'Media Manifest (.json)'],
      sha256Checksum: '98ba123498fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852aa47',
      destinationEmail: 'superadmin@homio.in, compliance@homio.in',
      status: BackupStatus.completed,
      durationFormatted: '1m 27s',
    ),
  ];
}
