import 'package:flutter/material.dart';
import 'reports_models.dart';

/// Seed Generator producing rich enterprise data for Homio Reports & Analytics.
abstract class ReportsMockData {
  // ==========================================================================
  // 1. MARKETING DATA
  // ==========================================================================

  static const List<ReportKpiMetric> marketingKpis = [
    ReportKpiMetric(
      id: 'mkt_leads',
      title: 'Total Inbound Leads',
      value: '1,248',
      changeText: '+18.4% vs last month',
      isPositive: true,
      icon: Icons.campaign_rounded,
      color: Color(0xFF6366F1),
      subtitle: 'Target: 1,100 • 84% Verified',
    ),
    ReportKpiMetric(
      id: 'mkt_cpl',
      title: 'Cost Per Lead (CPL)',
      value: '₹420',
      changeText: '-12.5% reduction',
      isPositive: true,
      icon: Icons.monetization_on_rounded,
      color: Color(0xFF10B981),
      subtitle: 'Benchmark: ₹480 • Top: Meta Ads',
    ),
    ReportKpiMetric(
      id: 'mkt_spend',
      title: 'Total Ad Spend',
      value: '₹5.24 L',
      changeText: '+4.2% budget utilized',
      isPositive: true,
      icon: Icons.account_balance_wallet_rounded,
      color: Color(0xFF3B82F6),
      subtitle: 'Meta 58% • Google 34% • Other 8%',
    ),
    ReportKpiMetric(
      id: 'mkt_conversions',
      title: 'Cost Per Conversion',
      value: '₹3,690',
      changeText: '142 Signed Projects',
      isPositive: true,
      icon: Icons.verified_rounded,
      color: Color(0xFFF59E0B),
      subtitle: 'CAC: ₹18,500 • ROI: 14.8x',
    ),
  ];

  static const List<FunnelStageItem> marketingFunnelStages = [
    FunnelStageItem(
      stageId: 'stage_raw',
      stageName: '1. Total Inbound Leads',
      count: 1248,
      percentage: 100.0,
      color: Color(0xFF6366F1),
      subtext: 'Paid Ad Campaigns & Organic Inquiries',
    ),
    FunnelStageItem(
      stageId: 'stage_qualified',
      stageName: '2. Tele-Qualified Leads',
      count: 680,
      percentage: 54.5,
      color: Color(0xFF3B82F6),
      subtext: '340 Unresponsive • 228 Not Qualified',
    ),
    FunnelStageItem(
      stageId: 'stage_meeting_sched',
      stageName: '3. Meeting Scheduled',
      count: 410,
      percentage: 32.8,
      color: Color(0xFF0EA5E9),
      subtext: 'Experience Center / Zoom Consultations',
    ),
    FunnelStageItem(
      stageId: 'stage_meeting_done',
      stageName: '4. Design Consultation Done',
      count: 315,
      percentage: 25.2,
      color: Color(0xFF10B981),
      subtext: '3D Concept & Budget Estimation Presented',
    ),
    FunnelStageItem(
      stageId: 'stage_waiting_payment',
      stageName: '5. Proposal & Escrow Token',
      count: 180,
      percentage: 14.4,
      color: Color(0xFFF59E0B),
      subtext: 'Awaiting 10% Booking Token Advance',
    ),
    FunnelStageItem(
      stageId: 'stage_booked',
      stageName: '6. Confirmed Project Bookings',
      count: 142,
      percentage: 11.4,
      color: Color(0xFF8B5CF6),
      subtext: 'Final Milestone Executed & Handover Planned',
    ),
  ];

  static const List<DecliningReasonItem> marketingDecliningReasons = [
    DecliningReasonItem(reason: 'High Pricing / Budget Mismatch', count: 72, percentage: 41.6, color: Color(0xFFEF4444)),
    DecliningReasonItem(reason: 'Quality / Material Specifications', count: 42, percentage: 24.3, color: Color(0xFFF59E0B)),
    DecliningReasonItem(reason: 'Brand Trust / Competitor Comparison', count: 31, percentage: 17.9, color: Color(0xFF3B82F6)),
    DecliningReasonItem(reason: 'Possession / Handover Timeline', count: 28, percentage: 16.2, color: Color(0xFF8B5CF6)),
  ];

  static const List<SocialCommentItem> socialComments = [
    SocialCommentItem(
      id: 'sc_01',
      author: '@ananya_interiors',
      platform: 'Instagram',
      commentText: 'Loved the modular kitchen finish in the DLF Cybercity project! What was the estimated budget?',
      postTitle: 'Reel: Luxury 4BHK Modular Kitchen Walkthrough',
      timeAgo: '12m ago',
      isAiReplied: true,
      replyText: 'Hi Ananya! For this 4BHK German finish kitchen, the budget was ₹4.8 Lakhs including Hafele hardware.',
    ),
    SocialCommentItem(
      id: 'sc_02',
      author: 'Rohit Sharma (Bangalore)',
      platform: 'YouTube',
      commentText: 'Do you provide full turnkey execution in Whitefield Bangalore as well?',
      postTitle: 'Video: Full Home Interior Transformation Tour',
      timeAgo: '45m ago',
      isAiReplied: true,
      replyText: 'Yes Rohit! We have active site teams and experience centers in Whitefield and Indiranagar.',
    ),
    SocialCommentItem(
      id: 'sc_03',
      author: '@kavita_designs',
      platform: 'Pinterest',
      commentText: 'Saved this fluted panel TV unit design. Can you share CAD drawings?',
      postTitle: 'Pin: Modern Minimalist Living Room TV Accent Wall',
      timeAgo: '2h ago',
      isAiReplied: false,
    ),
    SocialCommentItem(
      id: 'sc_04',
      author: '@vikas_mehta',
      platform: 'Instagram',
      commentText: 'Booked a consultation yesterday. Excited to meet your designer in Gurgaon!',
      postTitle: 'Post: Free 3D Vastu Consultation Slot Booking',
      timeAgo: '3h ago',
      isAiReplied: true,
      replyText: 'Thank you Vikas! Our senior design lead Vikram Malhotra looks forward to hosting you!',
    ),
  ];

  // ==========================================================================
  // 2. SALES DATA
  // ==========================================================================

  static const List<ReportKpiMetric> salesKpis = [
    ReportKpiMetric(
      id: 'sales_meetings',
      title: 'Total Consultations Done',
      value: '315',
      changeText: '+24 vs last month',
      isPositive: true,
      icon: Icons.groups_rounded,
      color: Color(0xFF3B82F6),
      subtitle: 'Site 48% • Studio 36% • Zoom 16%',
    ),
    ReportKpiMetric(
      id: 'sales_calls',
      title: 'Total Calling Minutes',
      value: '6,240m',
      changeText: '1,480 outbound dials',
      isPositive: true,
      icon: Icons.phone_in_talk_rounded,
      color: Color(0xFF10B981),
      subtitle: 'Avg 4.2 mins/call • 42 followups',
    ),
    ReportKpiMetric(
      id: 'sales_bookings',
      title: 'Closed Project Bookings',
      value: '142',
      changeText: '₹1.84 Cr gross order value',
      isPositive: true,
      icon: Icons.handshake_rounded,
      color: Color(0xFF8B5CF6),
      subtitle: '45.1% consultation-to-close',
    ),
    ReportKpiMetric(
      id: 'sales_whatsapp',
      title: 'WhatsApp Response Speed',
      value: '2.4 mins',
      changeText: '98.8% SLA adherence',
      isPositive: true,
      icon: Icons.chat_rounded,
      color: Color(0xFF10B981),
      subtitle: '4 unread incoming chats',
    ),
  ];

  static const List<SalesObjectionItem> salesObjections = [
    SalesObjectionItem(objectionName: 'Quotation Pricing / Rate Dispute', count: 64, percentage: 38.0, color: Color(0xFFEF4444)),
    SalesObjectionItem(objectionName: 'Material Brand Preference (Action Tesa vs Merino)', count: 38, percentage: 22.6, color: Color(0xFFF59E0B)),
    SalesObjectionItem(objectionName: 'Handover Possession Timeline (45 vs 60 days)', count: 30, percentage: 17.8, color: Color(0xFF3B82F6)),
    SalesObjectionItem(objectionName: '10-Year Warranty Terms & Exclusions', count: 21, percentage: 12.5, color: Color(0xFF10B981)),
    SalesObjectionItem(objectionName: 'Civil Modification Scope Limitations', count: 15, percentage: 9.1, color: Color(0xFF8B5CF6)),
  ];

  static const List<SalesTopRankerItem> salesTopRankers = [
    SalesTopRankerItem(
      rank: 1,
      consultantName: 'Aarav Singhania',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120',
      callsCount: 380,
      callMinutes: 1640,
      meetingsDone: 82,
      bookingsCount: 44,
      revenueGenerated: 58.4,
      conversionRate: 53.6,
    ),
    SalesTopRankerItem(
      rank: 2,
      consultantName: 'Pooja Hegde',
      avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=120',
      callsCount: 340,
      callMinutes: 1480,
      meetingsDone: 74,
      bookingsCount: 36,
      revenueGenerated: 46.2,
      conversionRate: 48.6,
    ),
    SalesTopRankerItem(
      rank: 3,
      consultantName: 'Rohan Deshmukh',
      avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120',
      callsCount: 290,
      callMinutes: 1220,
      meetingsDone: 62,
      bookingsCount: 28,
      revenueGenerated: 35.8,
      conversionRate: 45.1,
    ),
    SalesTopRankerItem(
      rank: 4,
      consultantName: 'Sneha Kapoor',
      avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=120',
      callsCount: 260,
      callMinutes: 1080,
      meetingsDone: 54,
      bookingsCount: 21,
      revenueGenerated: 27.5,
      conversionRate: 38.8,
    ),
    SalesTopRankerItem(
      rank: 5,
      consultantName: 'Kunal Verma',
      avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120',
      callsCount: 210,
      callMinutes: 820,
      meetingsDone: 43,
      bookingsCount: 13,
      revenueGenerated: 16.1,
      conversionRate: 30.2,
    ),
  ];

  // ==========================================================================
  // 3. DESIGN DATA
  // ==========================================================================

  static const List<ReportKpiMetric> designKpis = [
    ReportKpiMetric(
      id: 'des_approvals',
      title: 'Files Approved & In-Execution',
      value: '38',
      changeText: '8 submitted today',
      isPositive: true,
      icon: Icons.verified_user_rounded,
      color: Color(0xFF10B981),
      subtitle: '14 Pending Review • 6 Revisions',
    ),
    ReportKpiMetric(
      id: 'des_hours',
      title: 'Team Productive Hours',
      value: '1,420h',
      changeText: 'Avg 7.8 hrs/designer/day',
      isPositive: true,
      icon: Icons.access_time_filled_rounded,
      color: Color(0xFF6366F1),
      subtitle: '128 3D files & 84 drawings completed',
    ),
    ReportKpiMetric(
      id: 'des_csat',
      title: 'Customer CSAT Score',
      value: '9.3 / 10',
      changeText: 'Grade: Outstanding (A+)',
      isPositive: true,
      icon: Icons.star_rounded,
      color: Color(0xFFF59E0B),
      subtitle: 'Quality 9.5 • Punctuality 9.1 • Comms 9.4',
    ),
    ReportKpiMetric(
      id: 'des_incentives',
      title: 'Incentives Paid (Month)',
      value: '₹1.85 L',
      changeText: '142 Project Milestone Credits',
      isPositive: true,
      icon: Icons.emoji_events_rounded,
      color: Color(0xFF8B5CF6),
      subtitle: 'Top Designer Bonus: ₹25,000',
    ),
  ];

  static const List<DesignerProductivityItem> designerProductivityList = [
    DesignerProductivityItem(
      rank: 1,
      designerName: 'Kriti Sanon (Lead)',
      avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=120',
      hoursWorked: 172.0,
      filesCompleted: 34,
      meetingsTaken: 22,
      siteVisits: 8,
      productivityScore: 98.2,
      bookingsClosed: 14,
      incentiveEarned: 25000,
      csatRating: 9.8,
    ),
    DesignerProductivityItem(
      rank: 2,
      designerName: 'Devansh Roy',
      avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=120',
      hoursWorked: 168.0,
      filesCompleted: 29,
      meetingsTaken: 19,
      siteVisits: 7,
      productivityScore: 94.6,
      bookingsClosed: 11,
      incentiveEarned: 19500,
      csatRating: 9.4,
    ),
    DesignerProductivityItem(
      rank: 3,
      designerName: 'Ananya Deshmukh',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120',
      hoursWorked: 162.0,
      filesCompleted: 26,
      meetingsTaken: 17,
      siteVisits: 6,
      productivityScore: 91.8,
      bookingsClosed: 9,
      incentiveEarned: 16000,
      csatRating: 9.2,
    ),
    DesignerProductivityItem(
      rank: 4,
      designerName: 'Siddharth Nair',
      avatarUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=120',
      hoursWorked: 154.0,
      filesCompleted: 21,
      meetingsTaken: 14,
      siteVisits: 4,
      productivityScore: 86.4,
      bookingsClosed: 6,
      incentiveEarned: 11000,
      csatRating: 8.9,
    ),
  ];

  static const List<DesignFileApprovalItem> designApprovals = [
    DesignFileApprovalItem(
      projectId: 'PRJ-1048',
      projectName: 'DLF Magnolias 4BHK Penthouse',
      clientName: 'Rahul Khurana',
      designerName: 'Kriti Sanon',
      fileType: '3D Photorealistic V-Ray Render',
      status: 'Approved',
      statusColor: Color(0xFF10B981),
      submittedDate: 'Sep 5, 2026',
      reviewNotes: 'Approved by homeowner. Handed over to civil contractor.',
    ),
    DesignFileApprovalItem(
      projectId: 'PRJ-1049',
      projectName: 'Prestige Falcon City Villa',
      clientName: 'Sanjay Dutt',
      designerName: 'Devansh Roy',
      fileType: 'Joinery & CNC Cutting File',
      status: 'Pending Review',
      statusColor: Color(0xFFF59E0B),
      submittedDate: 'Sep 6, 2026',
      reviewNotes: 'Awaiting client color shade confirmation on laminates.',
    ),
    DesignFileApprovalItem(
      projectId: 'PRJ-1050',
      projectName: 'Godrej Woods 3BHK',
      clientName: 'Meenakshi Iyer',
      designerName: 'Ananya Deshmukh',
      fileType: 'False Ceiling & Electrical Layout',
      status: 'Revision Needed',
      statusColor: Color(0xFFEF4444),
      submittedDate: 'Sep 4, 2026',
      reviewNotes: 'A/C ducting drop depth needs to be reduced to 7 inches.',
    ),
    DesignFileApprovalItem(
      projectId: 'PRJ-1051',
      projectName: 'Sobha Royal Pavilion 3BHK',
      clientName: 'Harish Rao',
      designerName: 'Siddharth Nair',
      fileType: 'Walk-in Wardrobe Working Drawings',
      status: 'Approved',
      statusColor: Color(0xFF10B981),
      submittedDate: 'Sep 3, 2026',
      reviewNotes: 'Final spec verified with Hettich sliding sensor specs.',
    ),
  ];

  // ==========================================================================
  // 4. EXECUTION DATA
  // ==========================================================================

  static const List<ReportKpiMetric> executionKpis = [
    ReportKpiMetric(
      id: 'exe_active',
      title: 'Active Site Projects',
      value: '28',
      changeText: '24 On-Time (Green)',
      isPositive: true,
      icon: Icons.construction_rounded,
      color: Color(0xFF3B82F6),
      subtitle: '4 Delayed by ≥1 Week (Red Alert)',
    ),
    ReportKpiMetric(
      id: 'exe_feedback',
      title: 'Client Quality Feedback',
      value: '94.6%',
      changeText: '72% Excellent • 22% Good',
      isPositive: true,
      icon: Icons.thumb_up_rounded,
      color: Color(0xFF10B981),
      subtitle: '6% Needs Attention • 0 Critical escalations',
    ),
    ReportKpiMetric(
      id: 'exe_complaints',
      title: 'Snag & Complaint SLA',
      value: '88.4%',
      changeText: '38/43 resolved on-time',
      isPositive: true,
      icon: Icons.checklist_rounded,
      color: Color(0xFFF59E0B),
      subtitle: '2 Unsolved in Progress • Avg 1.8 days',
    ),
    ReportKpiMetric(
      id: 'exe_inspections',
      title: 'Physical Site Audits',
      value: '92',
      changeText: '3 Overdue (>10 days)',
      isPositive: false,
      icon: Icons.pin_drop_rounded,
      color: Color(0xFFEF4444),
      subtitle: 'Audit SLA: Max 7 days per site visit',
    ),
  ];

  static const List<ExecutionProjectProgressItem> executionProjects = [
    ExecutionProjectProgressItem(
      projectId: 'PRJ-982',
      projectName: 'DLF Magnolias Penthouse (Tower 2)',
      clientName: 'Vikram & Aarti Singhania',
      stage: 'Woodwork & Joinery',
      progressPercent: 78.0,
      isDelayed: false,
      delayDays: 0,
      siteEngineer: 'Naveen Kumar',
      lastPhysicalVisitDate: 'Sep 4, 2026',
      isVisitOverdue: false,
      pendingTasks: 4,
    ),
    ExecutionProjectProgressItem(
      projectId: 'PRJ-984',
      projectName: 'Prestige Falcon City Villa 402',
      clientName: 'Kunal Singhal',
      stage: 'Finishing & Painting',
      progressPercent: 92.0,
      isDelayed: true,
      delayDays: 8,
      siteEngineer: 'Rajat Sharma',
      lastPhysicalVisitDate: 'Aug 24, 2026',
      isVisitOverdue: true,
      pendingTasks: 9,
    ),
    ExecutionProjectProgressItem(
      projectId: 'PRJ-986',
      projectName: 'Sobha Royal Pavilion 3BHK',
      clientName: 'Priyanka Chopra',
      stage: 'Civil & Plastering',
      progressPercent: 44.0,
      isDelayed: false,
      delayDays: 0,
      siteEngineer: 'Amit Joshi',
      lastPhysicalVisitDate: 'Sep 5, 2026',
      isVisitOverdue: false,
      pendingTasks: 3,
    ),
    ExecutionProjectProgressItem(
      projectId: 'PRJ-988',
      projectName: 'Godrej Woods 4BHK Luxury',
      clientName: 'Tanvi & Rahul Malhotra',
      stage: 'Electrical & Automation',
      progressPercent: 62.0,
      isDelayed: true,
      delayDays: 11,
      siteEngineer: 'Vikash Yadav',
      lastPhysicalVisitDate: 'Aug 22, 2026',
      isVisitOverdue: true,
      pendingTasks: 12,
    ),
    ExecutionProjectProgressItem(
      projectId: 'PRJ-990',
      projectName: 'Hiranandani Estate 2BHK',
      clientName: 'Abhishek Roy',
      stage: 'Handover & Snagging',
      progressPercent: 98.0,
      isDelayed: false,
      delayDays: 0,
      siteEngineer: 'Naveen Kumar',
      lastPhysicalVisitDate: 'Sep 6, 2026',
      isVisitOverdue: false,
      pendingTasks: 1,
    ),
  ];

  static const List<ExecutionComplaintItem> executionComplaints = [
    ExecutionComplaintItem(
      ticketId: 'SNAG-408',
      clientName: 'Kunal Singhal',
      projectName: 'Prestige Falcon City Villa 402',
      category: 'Quality',
      issueDescription: 'Laminate edge banding peeling in master bedroom wardrobe corner.',
      registeredDate: 'Sep 2, 2026',
      status: 'Solved On-Time',
      statusColor: Color(0xFF10B981),
      resolutionDays: 2,
    ),
    ExecutionComplaintItem(
      ticketId: 'SNAG-409',
      clientName: 'Tanvi Malhotra',
      projectName: 'Godrej Woods 4BHK Luxury',
      category: 'Timeline',
      issueDescription: 'Civil tile delivery delayed by 4 days due to supplier transport strike.',
      registeredDate: 'Aug 30, 2026',
      status: 'Solved Delayed',
      statusColor: Color(0xFFF59E0B),
      resolutionDays: 5,
    ),
    ExecutionComplaintItem(
      ticketId: 'SNAG-410',
      clientName: 'Rahul Khurana',
      projectName: 'DLF Magnolias Penthouse',
      category: 'Site Behaviour',
      issueDescription: 'Contractor debris left in residential corridor past 6 PM.',
      registeredDate: 'Sep 5, 2026',
      status: 'Unsolved',
      statusColor: Color(0xFFEF4444),
      resolutionDays: 1,
    ),
  ];

  static const List<SiteMediaFeedItem> siteMediaFeed = [
    SiteMediaFeedItem(
      id: 'sm_01',
      clientName: 'Vikram Singhania (DLF Magnolias)',
      siteLocation: 'Golf Course Road, Gurgaon',
      stage: 'Woodwork & Modular Kitchen',
      uploadedBy: 'Naveen Kumar (Site Eng)',
      timeAgo: '1h ago',
      mediaUrl: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=600',
      isVideo: true,
      note: 'Base carcass alignment completed with Blum tandembox fittings.',
    ),
    SiteMediaFeedItem(
      id: 'sm_02',
      clientName: 'Kunal Singhal (Prestige Villa)',
      siteLocation: 'Whitefield, Bangalore',
      stage: 'Italian Marble Polishing',
      uploadedBy: 'Rajat Sharma (Site Eng)',
      timeAgo: '3h ago',
      mediaUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600',
      isVideo: false,
      note: 'Dyna marble mirror diamond polish stage 4 completed.',
    ),
    SiteMediaFeedItem(
      id: 'sm_03',
      clientName: 'Priyanka Chopra (Sobha Royal)',
      siteLocation: 'Sarjapur Road, Bangalore',
      stage: 'POP False Ceiling Framing',
      uploadedBy: 'Amit Joshi (Site Eng)',
      timeAgo: '5h ago',
      mediaUrl: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=600',
      isVideo: false,
      note: 'GI perimeter channel framing completed for cove lighting.',
    ),
  ];

  // ==========================================================================
  // 5. VENDOR RATINGS DATA
  // ==========================================================================

  static const List<ReportKpiMetric> vendorKpis = [
    ReportKpiMetric(
      id: 'ven_avg_score',
      title: 'Average Vendor Rating',
      value: '8.7 / 10',
      changeText: '+0.4 vs last quarter',
      isPositive: true,
      icon: Icons.star_half_rounded,
      color: Color(0xFF10B981),
      subtitle: '34 Active Verified Contractor Teams',
    ),
    ReportKpiMetric(
      id: 'ven_critical',
      title: 'Critical Audit Alerts (<5.0)',
      value: '2 Vendors',
      changeText: 'Immediate Action Required',
      isPositive: false,
      icon: Icons.warning_amber_rounded,
      color: Color(0xFFEF4444),
      subtitle: 'Quality & Material Wastage Threshold Breached',
    ),
    ReportKpiMetric(
      id: 'ven_winner',
      title: 'Winner of the Month',
      value: 'Royal Woodcraft',
      changeText: 'Score: 9.8 / 10 • 0 Snags',
      isPositive: true,
      icon: Icons.workspace_premium_rounded,
      color: Color(0xFFF59E0B),
      subtitle: 'Carpentry & Joinery • 6 active sites',
    ),
    ReportKpiMetric(
      id: 'ven_punctuality',
      title: 'On-Time Milestone Rate',
      value: '91.2%',
      changeText: '210/230 milestones delivered',
      isPositive: true,
      icon: Icons.timer_outlined,
      color: Color(0xFF3B82F6),
      subtitle: 'Material wastage controlled < 3.8%',
    ),
  ];

  static const List<VendorScorecardItem> vendorScorecards = [
    VendorScorecardItem(
      vendorId: 'VEN-01',
      vendorName: 'Royal Woodcraft & Modulars',
      tradeCategory: 'Carpentry & Joinery',
      overallRating: 9.8,
      qualityScore: 99.0,
      punctualityScore: 96.0,
      wastageControlScore: 97.0,
      activeSitesCount: 6,
      completedSitesCount: 42,
      isWinnerOfMonth: true,
      isCriticalAlert: false,
      auditStatus: 'Certified',
    ),
    VendorScorecardItem(
      vendorId: 'VEN-02',
      vendorName: 'Sri Balaji Civil & POP Works',
      tradeCategory: 'Civil & Masonry',
      overallRating: 8.9,
      qualityScore: 90.0,
      punctualityScore: 88.0,
      wastageControlScore: 89.0,
      activeSitesCount: 8,
      completedSitesCount: 64,
      isWinnerOfMonth: false,
      isCriticalAlert: false,
      auditStatus: 'Certified',
    ),
    VendorScorecardItem(
      vendorId: 'VEN-03',
      vendorName: 'Apex Precision Glass & Aluminum',
      tradeCategory: 'Glass & Aluminum',
      overallRating: 8.6,
      qualityScore: 88.0,
      punctualityScore: 85.0,
      wastageControlScore: 86.0,
      activeSitesCount: 4,
      completedSitesCount: 28,
      isWinnerOfMonth: false,
      isCriticalAlert: false,
      auditStatus: 'Certified',
    ),
    VendorScorecardItem(
      vendorId: 'VEN-04',
      vendorName: 'VoltSmart Electrical Automation',
      tradeCategory: 'Electrical & Automation',
      overallRating: 9.1,
      qualityScore: 94.0,
      punctualityScore: 90.0,
      wastageControlScore: 92.0,
      activeSitesCount: 5,
      completedSitesCount: 39,
      isWinnerOfMonth: false,
      isCriticalAlert: false,
      auditStatus: 'Certified',
    ),
    VendorScorecardItem(
      vendorId: 'VEN-05',
      vendorName: 'Shree Sai Painters & Polishers',
      tradeCategory: 'Painting & Polishing',
      overallRating: 4.8,
      qualityScore: 52.0,
      punctualityScore: 46.0,
      wastageControlScore: 48.0,
      activeSitesCount: 2,
      completedSitesCount: 14,
      isWinnerOfMonth: false,
      isCriticalAlert: true,
      auditStatus: 'Under Watch',
    ),
    VendorScorecardItem(
      vendorId: 'VEN-06',
      vendorName: 'Prime Flow Sanitary & Plumbing',
      tradeCategory: 'Plumbing & Sanitary',
      overallRating: 4.6,
      qualityScore: 50.0,
      punctualityScore: 44.0,
      wastageControlScore: 46.0,
      activeSitesCount: 2,
      completedSitesCount: 18,
      isWinnerOfMonth: false,
      isCriticalAlert: true,
      auditStatus: 'Audit Pending',
    ),
  ];

  // ==========================================================================
  // 6. FINANCIAL DATA
  // ==========================================================================

  static const List<ReportKpiMetric> financialKpis = [
    ReportKpiMetric(
      id: 'fin_material',
      title: 'Material Procurement',
      value: '₹42.80 L',
      changeText: '60.7% total outflow',
      isPositive: true,
      icon: Icons.inventory_2_rounded,
      color: Color(0xFF3B82F6),
      subtitle: 'Plywood, Hardware, Marble & Paint',
    ),
    ReportKpiMetric(
      id: 'fin_labour',
      title: 'Contractor & Labour Paid',
      value: '₹18.40 L',
      changeText: '26.1% total outflow',
      isPositive: true,
      icon: Icons.engineering_rounded,
      color: Color(0xFF10B981),
      subtitle: 'Carpentry, Civil, Electrical & POP',
    ),
    ReportKpiMetric(
      id: 'fin_design',
      title: 'Design & 3D Fees',
      value: '₹6.20 L',
      changeText: '8.8% total outflow',
      isPositive: true,
      icon: Icons.draw_rounded,
      color: Color(0xFF8B5CF6),
      subtitle: '38 Project Concept & CAD files',
    ),
    ReportKpiMetric(
      id: 'fin_consulting',
      title: 'Consulting & Vastu Fees',
      value: '₹3.10 L',
      changeText: '4.4% total outflow',
      isPositive: true,
      icon: Icons.psychology_rounded,
      color: Color(0xFFF59E0B),
      subtitle: 'Structural Engineers & Vastu Audits',
    ),
  ];

  static const List<FinancialOutflowLedgerItem> financialOutflows = [
    FinancialOutflowLedgerItem(
      txnId: 'TXN-FIN-801',
      projectId: 'PRJ-1048',
      clientName: 'Rahul Khurana (DLF Penthouse)',
      category: 'Material Procurement',
      recipientName: 'Action Tesa Plywood & CenturyPly',
      amount: 485000,
      date: 'Sep 5, 2026',
      paymentMethod: 'Bank RTGS',
      status: 'Settled',
      statusColor: Color(0xFF10B981),
      invoiceRef: 'INV-AT-9021',
    ),
    FinancialOutflowLedgerItem(
      txnId: 'TXN-FIN-802',
      projectId: 'PRJ-1048',
      clientName: 'Rahul Khurana (DLF Penthouse)',
      category: 'Labour Disbursement',
      recipientName: 'Royal Woodcraft & Modulars',
      amount: 195000,
      date: 'Sep 4, 2026',
      paymentMethod: 'Bank RTGS',
      status: 'Settled',
      statusColor: Color(0xFF10B981),
      invoiceRef: 'INV-RW-4402',
    ),
    FinancialOutflowLedgerItem(
      txnId: 'TXN-FIN-803',
      projectId: 'PRJ-1049',
      clientName: 'Sanjay Dutt (Prestige Villa)',
      category: 'Material Procurement',
      recipientName: 'Hafele & Hettich Hardware India',
      amount: 320000,
      date: 'Sep 3, 2026',
      paymentMethod: 'Bank RTGS',
      status: 'Settled',
      statusColor: Color(0xFF10B981),
      invoiceRef: 'INV-HF-1092',
    ),
    FinancialOutflowLedgerItem(
      txnId: 'TXN-FIN-804',
      projectId: 'PRJ-1050',
      clientName: 'Meenakshi Iyer (Godrej Woods)',
      category: 'Design Fees',
      recipientName: 'Kriti Sanon (Design Lead)',
      amount: 85000,
      date: 'Sep 2, 2026',
      paymentMethod: 'Escrow Release',
      status: 'Settled',
      statusColor: Color(0xFF10B981),
      invoiceRef: 'DES-KS-08',
    ),
    FinancialOutflowLedgerItem(
      txnId: 'TXN-FIN-805',
      projectId: 'PRJ-1051',
      clientName: 'Harish Rao (Sobha Royal)',
      category: 'Consulting Fees',
      recipientName: 'Dr. R.K. Sharma (Vastu & Struct)',
      amount: 45000,
      date: 'Sep 1, 2026',
      paymentMethod: 'UPI / IMPS',
      status: 'Settled',
      statusColor: Color(0xFF10B981),
      invoiceRef: 'CNS-VST-19',
    ),
  ];
}
