import 'after_sales_models.dart';

class AfterSalesMockData {
  // 1. Post-Handover Snag & Warranty Tickets
  static final List<SnagTicket> snagTickets = [
    SnagTicket(
      id: 'SNG-001',
      ticketNumber: 'TKT-2026-8801',
      projectId: 'PRJ-VILLA-42',
      projectName: 'Sobha Royal Pavilion #42',
      clientName: 'Sunita Mehra',
      clientPhone: '+91 98450 12345',
      handoverDate: DateTime(2026, 6, 15),
      category: SnagCategory.carpentry,
      priority: SnagPriority.high,
      warrantyStatus: WarrantyStatus.active1YrComprehensive,
      title: 'Master Bedroom Wardrobe Hydraulic Soft-Close Malfunction',
      description: 'Right hydraulic hinge on the 8ft PU painted sliding shutter is jammed and squeaking upon closure.',
      reportedDate: DateTime.now().subtract(const Duration(hours: 14)),
      slaDeadline: DateTime.now().add(const Duration(hours: 10)),
      assignedTechnician: 'Dinesh Carpenter Lead',
      technicianPhone: '+91 98221 44556',
      status: SnagStatus.dispatched,
      beforePhotoUrl: 'https://images.unsplash.com/photo-1558997519-83ea9252def8?w=300',
    ),
    SnagTicket(
      id: 'SNG-002',
      ticketNumber: 'TKT-2026-8802',
      projectId: 'PRJ-MAGNOLIA-402',
      projectName: 'DLF Magnolias #402',
      clientName: 'Vikram Mehta',
      clientPhone: '+91 98110 99887',
      handoverDate: DateTime(2026, 4, 10),
      category: SnagCategory.civil,
      priority: SnagPriority.critical,
      warrantyStatus: WarrantyStatus.active10YrStructural,
      title: 'Balcony Slab Grout Seepage & Marble Discoloration',
      description: 'Minor moisture penetration observed along the south balcony perimeter expansion joint following heavy monsoon showers.',
      reportedDate: DateTime.now().subtract(const Duration(hours: 3)),
      slaDeadline: DateTime.now().add(const Duration(hours: 1)), // 4h emergency SLA
      assignedTechnician: 'Harish Civil Engineer',
      technicianPhone: '+91 99104 22334',
      status: SnagStatus.inProgress,
      beforePhotoUrl: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=300',
    ),
    SnagTicket(
      id: 'SNG-003',
      ticketNumber: 'TKT-2026-8803',
      projectId: 'PRJ-TRUMP-2104',
      projectName: 'Trump Towers #2104',
      clientName: 'Rajesh Khanna',
      clientPhone: '+91 98200 55443',
      handoverDate: DateTime(2026, 7, 1),
      category: SnagCategory.electricalMep,
      priority: SnagPriority.medium,
      warrantyStatus: WarrantyStatus.active1YrComprehensive,
      title: 'Dining Chandelier Dimmable Driver Flickering',
      description: '12-arm crystal chandelier lighting channel driver experiences intermittent voltage flicker when dimmed to 30%.',
      reportedDate: DateTime.now().subtract(const Duration(days: 1)),
      slaDeadline: DateTime.now().add(const Duration(hours: 24)),
      assignedTechnician: 'Santosh Electrician',
      technicianPhone: '+91 98331 66778',
      status: SnagStatus.resolved,
      beforePhotoUrl: 'https://images.unsplash.com/photo-1540932239986-30128078f3c5?w=300',
      afterPhotoUrl: 'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=300',
      clientSignoff: true,
      resolvedDate: DateTime.now().subtract(const Duration(hours: 2)),
      resolutionNotes: 'Replaced 150W magnetic driver with smart Zigbee phase-cut dimmable driver. Client tested and signed off.',
    ),
    SnagTicket(
      id: 'SNG-004',
      ticketNumber: 'TKT-2026-8804',
      projectId: 'PRJ-LODHA-18A',
      projectName: 'Lodha Altamount #18A',
      clientName: 'Pooja Hegde',
      clientPhone: '+91 98334 11200',
      handoverDate: DateTime(2025, 2, 20),
      category: SnagCategory.paintPolish,
      priority: SnagPriority.low,
      warrantyStatus: WarrantyStatus.outOfWarranty,
      title: 'Touchup Required for Foyer Wall Scuff Marks',
      description: 'Furniture relocation by owner caused scuff marks on foyer Italian stucco finish. Requesting billable touchup service.',
      reportedDate: DateTime.now().subtract(const Duration(days: 3)),
      slaDeadline: DateTime.now().add(const Duration(days: 4)),
      status: SnagStatus.open,
    ),
  ];

  // 2. Client Retention & CSAT Follow-up Calls
  static final List<RetentionCallRecord> retentionCalls = [
    RetentionCallRecord(
      id: 'RET-101',
      clientId: 'CLI-01',
      clientName: 'Sunita Mehra',
      clientPhone: '+91 98450 12345',
      projectName: 'Sobha Royal Pavilion #42',
      handoverDate: DateTime(2026, 6, 15),
      scheduledDate: DateTime.now().subtract(const Duration(days: 5)),
      conductedDate: DateTime.now().subtract(const Duration(days: 5)),
      callStatus: CallStatus.completed,
      csatScore: 9.2,
      designQualityRating: 9.5, // 40% weight
      timelineRating: 9.0, // 30% weight
      behaviourRating: 9.0, // 30% weight
      callerName: 'Priya Service Telecaller',
      feedbackNotes: 'Client expressed high appreciation for 3D render fidelity and on-time carpentry delivery. Left a 5-star Google review.',
      reviewLinkSent: true,
      reviewPosted: true,
      referralLeadName: 'Kavita Chawla (Sister)',
      referralLeadPhone: '+91 98450 77889',
      referralRewardStatus: ReferralRewardStatus.credited,
    ),
    RetentionCallRecord(
      id: 'RET-102',
      clientId: 'CLI-02',
      clientName: 'Vikram Mehta',
      clientPhone: '+91 98110 99887',
      projectName: 'DLF Magnolias #402',
      handoverDate: DateTime(2026, 4, 10),
      scheduledDate: DateTime.now(),
      callStatus: CallStatus.scheduled,
      callerName: 'Priya Service Telecaller',
      feedbackNotes: 'Scheduled 90-day post-handover health checkup call. Check on balcony moisture resolution.',
    ),
    RetentionCallRecord(
      id: 'RET-103',
      clientId: 'CLI-03',
      clientName: 'Rajesh Khanna',
      clientPhone: '+91 98200 55443',
      projectName: 'Trump Towers #2104',
      handoverDate: DateTime(2026, 7, 1),
      scheduledDate: DateTime.now().subtract(const Duration(days: 2)),
      conductedDate: DateTime.now().subtract(const Duration(days: 2)),
      callStatus: CallStatus.completed,
      csatScore: 8.8,
      designQualityRating: 9.0,
      timelineRating: 8.5,
      behaviourRating: 9.0,
      callerName: 'Priya Service Telecaller',
      feedbackNotes: 'Client pleased with lighting resolution. WhatsApp review link dispatched.',
      reviewLinkSent: true,
      reviewPosted: false,
      referralRewardStatus: ReferralRewardStatus.eligible,
    ),
    RetentionCallRecord(
      id: 'RET-104',
      clientId: 'CLI-04',
      clientName: 'Pooja Hegde',
      clientPhone: '+91 98334 11200',
      projectName: 'Lodha Altamount #18A',
      handoverDate: DateTime(2025, 2, 20),
      scheduledDate: DateTime.now().add(const Duration(days: 2)),
      callStatus: CallStatus.scheduled,
      callerName: 'Priya Service Telecaller',
      feedbackNotes: '18-month warranty expiration check & anniversary congratulations.',
    ),
  ];
}
