import 'after_sales_models.dart';

class AfterSalesMockData {
  // ==========================================================================
  // 1. SERVICE REQUESTS
  // ==========================================================================
  static final List<ServiceRequest> serviceRequests = [
    ServiceRequest(
      id: 'REQ-2026-001',
      requestNumber: 'SR-BLR-8801',
      customerId: 'CUST-BLR-01',
      customerName: 'Sunita Mehra',
      customerPhone: '+91 98450 12345',
      customerEmail: 'sunita.mehra@gmail.com',
      preferredChannel: 'WhatsApp',
      projectId: 'PRJ-VILLA-42',
      projectName: 'Sobha Royal Pavilion #42',
      projectType: '4BHK Luxury Penthouse',
      siteAddress: 'Tower 3, Penthouse 42, Sarjapur Road, Bangalore 560035',
      handoverDate: DateTime(2026, 6, 15),
      projectManager: 'Rajesh Kumar',
      supervisor: 'Suresh Gowda',
      requestType: 'Defect Rectification',
      category: ServiceCategory.carpentry,
      subject: 'Master Bedroom Wardrobe Hydraulic Shutter Stuck',
      description: 'Right hydraulic soft-close hinge on the 8ft PU painted sliding shutter is jammed and squeaking upon closure.',
      areaRoom: 'Master Bedroom Suite',
      specificLocation: 'Walk-in Wardrobe, Shutter Bay 2',
      issueDate: DateTime.now().subtract(const Duration(hours: 18)),
      priority: ServicePriority.high,
      status: ServiceRequestStatus.scheduled,
      customerExpectation: 'Replace defective hinge and align shutter before weekend guests arrive.',
      preferredServiceDate: DateTime.now().add(const Duration(days: 1)),
      preferredTime: '10:00 AM - 12:00 PM',
      availabilityNotes: 'Client will be at home during morning hours.',
      additionalRemarks: 'Keep replacement Blum soft-close hinges in technician kit.',
      assignedToName: 'Dinesh Carpenter Lead',
      assignedToRole: 'Senior Modular Technician',
      assignedDate: DateTime.now().subtract(const Duration(hours: 14)),
      createdDate: DateTime.now().subtract(const Duration(hours: 18)),
      dueDate: DateTime.now().add(const Duration(hours: 6)),
      lastActivity: DateTime.now().subtract(const Duration(hours: 2)),
      nextFollowUpDate: DateTime.now().add(const Duration(hours: 12)),
      isWarrantyCovered: true,
      warrantyId: 'WAR-BLR-01-COMP',
      billingStatus: BillingStatus.warrantyCovered,
      estimatedCost: 0.0,
      tasks: [
        ServiceTask(
          id: 'TSK-01',
          title: 'Dispatch replacement Blum 110-deg hinge',
          description: 'Collect 2x Blum soft-close hinges from Central Warehouse.',
          assignee: 'Warehouse Team',
          priority: ServicePriority.high,
          dueDate: DateTime.now().add(const Duration(hours: 4)),
          isCompleted: true,
          completedDate: DateTime.now().subtract(const Duration(hours: 1)),
        ),
        ServiceTask(
          id: 'TSK-02',
          title: 'On-site Hinge Replacement & Track Alignment',
          description: 'Inspect track rollers and replace malfunctioning hinge assembly.',
          assignee: 'Dinesh Carpenter Lead',
          priority: ServicePriority.high,
          dueDate: DateTime.now().add(const Duration(hours: 18)),
          isCompleted: false,
        ),
      ],
      attachments: [
        ServiceAttachment(
          id: 'ATT-01',
          fileName: 'wardrobe_hinge_jammed.jpg',
          fileType: 'image/jpeg',
          fileSize: '2.4 MB',
          uploadedBy: 'Sunita Mehra (Client)',
          uploadedDate: DateTime.now().subtract(const Duration(hours: 18)),
          category: 'Customer Uploaded',
          fileUrl: 'https://images.unsplash.com/photo-1558997519-83ea9252def8?w=500',
        ),
      ],
      internalNotes: [
        InternalNote(
          id: 'NT-01',
          authorName: 'Priya Service Telecaller',
          authorRole: 'After-Sales Telecaller',
          timestamp: DateTime.now().subtract(const Duration(hours: 16)),
          note: 'Client called expressing urgency as they have relatives staying over on Saturday. Prioritized for tomorrow morning.',
        ),
      ],
      visitIds: ['VST-2026-001'],
    ),

    ServiceRequest(
      id: 'REQ-2026-002',
      requestNumber: 'SR-DEL-8802',
      customerId: 'CUST-DEL-02',
      customerName: 'Vikram Mehta',
      customerPhone: '+91 98110 99887',
      customerEmail: 'vikram.mehta@outlook.com',
      preferredChannel: 'Phone',
      projectId: 'PRJ-MAGNOLIA-402',
      projectName: 'DLF Magnolias #402',
      projectType: 'Luxury Golf Villa',
      siteAddress: 'Block B, Villa 402, Golf Course Road, Sector 42, Gurgaon 122002',
      handoverDate: DateTime(2026, 4, 10),
      projectManager: 'Amit Bansal',
      supervisor: 'Rakesh Sharma',
      requestType: 'Warranty Emergency',
      category: ServiceCategory.civil,
      subject: 'Balcony Expansion Joint Water Ingress & Marble Dampness',
      description: 'Minor moisture penetration observed along the south balcony perimeter expansion joint following heavy monsoon showers.',
      areaRoom: 'South Balcony Deck',
      specificLocation: 'Perimeter expansion joint near glass railing post #3',
      issueDate: DateTime.now().subtract(const Duration(hours: 6)),
      priority: ServicePriority.critical,
      status: ServiceRequestStatus.inProgress,
      customerExpectation: 'Urgent waterproofing injection and marble sealant before interior wooden flooring is affected.',
      preferredServiceDate: DateTime.now(),
      preferredTime: 'Immediate Emergency Visit',
      availabilityNotes: 'Site security will grant entry to Homio van.',
      assignedToName: 'Harish Civil Engineer',
      assignedToRole: 'Senior MEP & Waterproofing Specialist',
      assignedDate: DateTime.now().subtract(const Duration(hours: 4)),
      createdDate: DateTime.now().subtract(const Duration(hours: 6)),
      dueDate: DateTime.now().add(const Duration(hours: 2)), // 4h SLA
      lastActivity: DateTime.now().subtract(const Duration(minutes: 30)),
      isWarrantyCovered: true,
      warrantyId: 'WAR-DEL-02-STRUCT',
      billingStatus: BillingStatus.warrantyCovered,
      estimatedCost: 0.0,
      tasks: [
        ServiceTask(
          id: 'TSK-03',
          title: 'Moisture Meter Level Inspection',
          description: 'Measure sub-base dampness with digital pinless moisture probe.',
          assignee: 'Harish Civil Engineer',
          priority: ServicePriority.critical,
          dueDate: DateTime.now().add(const Duration(hours: 1)),
        ),
      ],
      attachments: [
        ServiceAttachment(
          id: 'ATT-02',
          fileName: 'balcony_seepage.jpg',
          fileType: 'image/jpeg',
          fileSize: '3.1 MB',
          uploadedBy: 'Vikram Mehta (Client)',
          uploadedDate: DateTime.now().subtract(const Duration(hours: 6)),
          category: 'Customer Uploaded',
          fileUrl: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=500',
        ),
      ],
      visitIds: ['VST-2026-002'],
      complaintId: 'CMP-2026-101',
    ),

    ServiceRequest(
      id: 'REQ-2026-003',
      requestNumber: 'SR-MUM-8803',
      customerId: 'CUST-MUM-03',
      customerName: 'Rajesh Khanna',
      customerPhone: '+91 98200 55443',
      customerEmail: 'rajesh.khanna@towers.in',
      preferredChannel: 'WhatsApp',
      projectId: 'PRJ-TRUMP-2104',
      projectName: 'Trump Towers #2104',
      projectType: '3BHK Sea Facing Apartment',
      siteAddress: 'Tower A, Floor 21, Flat 2104, Worli, Mumbai 400018',
      handoverDate: DateTime(2026, 7, 1),
      projectManager: 'Nikhil Desai',
      supervisor: 'Deepak Patil',
      requestType: 'Routine Service',
      category: ServiceCategory.electrical,
      subject: 'Dining Chandelier Dimmable Driver Replacement',
      description: '12-arm crystal chandelier lighting channel driver experiences intermittent voltage flicker when dimmed to 30%.',
      areaRoom: 'Formal Dining Hall',
      specificLocation: 'Ceiling center medallion chandelier junction',
      issueDate: DateTime.now().subtract(const Duration(days: 3)),
      priority: ServicePriority.normal,
      status: ServiceRequestStatus.resolved,
      customerExpectation: 'Replace 150W magnetic driver with smart Zigbee phase-cut driver.',
      preferredServiceDate: DateTime.now().subtract(const Duration(days: 1)),
      preferredTime: '02:00 PM - 04:00 PM',
      availabilityNotes: 'Owner available in afternoon.',
      assignedToName: 'Santosh Electrician',
      assignedToRole: 'Lead MEP Technician',
      assignedDate: DateTime.now().subtract(const Duration(days: 2)),
      createdDate: DateTime.now().subtract(const Duration(days: 3)),
      dueDate: DateTime.now().subtract(const Duration(days: 1)),
      lastActivity: DateTime.now().subtract(const Duration(days: 1)),
      resolvedDate: DateTime.now().subtract(const Duration(days: 1)),
      closedDate: DateTime.now().subtract(const Duration(hours: 12)),
      isWarrantyCovered: true,
      warrantyId: 'WAR-MUM-03-COMP',
      billingStatus: BillingStatus.warrantyCovered,
      estimatedCost: 0.0,
      rating: 5.0,
      visitIds: ['VST-2026-003'],
    ),

    ServiceRequest(
      id: 'REQ-2026-004',
      requestNumber: 'SR-MUM-8804',
      customerId: 'CUST-MUM-04',
      customerName: 'Pooja Hegde',
      customerPhone: '+91 98334 11200',
      customerEmail: 'pooja.hegde@altamount.com',
      preferredChannel: 'Phone',
      projectId: 'PRJ-LODHA-18A',
      projectName: 'Lodha Altamount #18A',
      projectType: '4BHK Ultra Luxury Apartment',
      siteAddress: '18th Floor, Flat 18A, Altamount Road, Mumbai 400026',
      handoverDate: DateTime(2025, 2, 20),
      projectManager: 'Sneha Kulkarni',
      supervisor: 'Santosh Shinde',
      requestType: 'Chargeable Touchup',
      category: ServiceCategory.finishSurface,
      subject: 'Foyer Italian Stucco Wall Scuff Mark Touchup',
      description: 'Furniture relocation by owner caused scuff marks on foyer Italian stucco finish. Requesting billable touchup service.',
      areaRoom: 'Entrance Foyer',
      specificLocation: 'East Wall flanking console table',
      issueDate: DateTime.now().subtract(const Duration(days: 4)),
      priority: ServicePriority.low,
      status: ServiceRequestStatus.waitingCustomer,
      customerExpectation: 'Match stucco shade code #PU-STUCCO-882 and blend seamlessly.',
      preferredServiceDate: DateTime.now().add(const Duration(days: 3)),
      preferredTime: '11:00 AM - 01:00 PM',
      availabilityNotes: 'Domestic help will open apartment door.',
      assignedToName: 'Ramesh Painter Lead',
      assignedToRole: 'Italian Stucco Artisan',
      assignedDate: DateTime.now().subtract(const Duration(days: 2)),
      createdDate: DateTime.now().subtract(const Duration(days: 4)),
      dueDate: DateTime.now().add(const Duration(days: 3)),
      lastActivity: DateTime.now().subtract(const Duration(hours: 5)),
      isWarrantyCovered: false,
      billingStatus: BillingStatus.chargeable,
      estimatedCost: 4500.0,
      paymentLinkSent: true,
      isPaid: false,
      internalNotes: [
        InternalNote(
          id: 'NT-02',
          authorName: 'Amit Service Manager',
          authorRole: 'After-Sales Service Manager',
          timestamp: DateTime.now().subtract(const Duration(days: 1)),
          note: 'Warranty expired in Feb 2026. Sent ₹4,500 estimate link via WhatsApp. Awaiting client authorization.',
        ),
      ],
    ),

    ServiceRequest(
      id: 'REQ-2026-005',
      requestNumber: 'SR-BLR-8805',
      customerId: 'CUST-BLR-05',
      customerName: 'Rohan Deshmukh',
      customerPhone: '+91 99001 22334',
      customerEmail: 'rohan.deshmukh@gmail.com',
      preferredChannel: 'WhatsApp',
      projectId: 'PRJ-PRESTIGE-108',
      projectName: 'Prestige Golfshire #108',
      projectType: 'Golf Villa',
      siteAddress: 'Villa 108, Nandi Hills Road, Devanahalli, Bangalore 562110',
      handoverDate: DateTime(2026, 5, 18),
      projectManager: 'Arun Varma',
      supervisor: 'Mohan Reddy',
      requestType: 'Plumbing Service',
      category: ServiceCategory.plumbing,
      subject: 'Powder Room Concealed Cistern Slow Fill Valve',
      description: 'Grohe pneumatic concealed flush tank fill valve makes continuous hissing sound and takes 8 minutes to refill.',
      areaRoom: 'Ground Floor Powder Room',
      specificLocation: 'Concealed cistern behind marble wall panelling',
      issueDate: DateTime.now().subtract(const Duration(days: 1)),
      priority: ServicePriority.normal,
      status: ServiceRequestStatus.assigned,
      customerExpectation: 'Service fill valve diaphragm or replace with OEM Grohe part.',
      preferredServiceDate: DateTime.now().add(const Duration(days: 2)),
      preferredTime: '03:00 PM - 05:00 PM',
      availabilityNotes: 'Client will be home in late afternoon.',
      assignedToName: 'Karthik Plumber',
      assignedToRole: 'Certified Sanitary Technician',
      assignedDate: DateTime.now().subtract(const Duration(hours: 3)),
      createdDate: DateTime.now().subtract(const Duration(days: 1)),
      dueDate: DateTime.now().add(const Duration(days: 1)),
      lastActivity: DateTime.now().subtract(const Duration(hours: 3)),
      isWarrantyCovered: true,
      warrantyId: 'WAR-BLR-05-COMP',
      billingStatus: BillingStatus.warrantyCovered,
      estimatedCost: 0.0,
      visitIds: ['VST-2026-005'],
    ),

    ServiceRequest(
      id: 'REQ-2026-006',
      requestNumber: 'SR-DEL-8806',
      customerId: 'CUST-DEL-06',
      customerName: 'Ananya Sharma',
      customerPhone: '+91 98101 33445',
      customerEmail: 'ananya.sharma@dlf.com',
      preferredChannel: 'Phone',
      projectId: 'PRJ-CAMEL-501',
      projectName: 'The Camellias #501',
      projectType: 'Luxury Golf Facing Apartment',
      siteAddress: 'Tower 2, Flat 501, Golf Course Road, Gurgaon 122002',
      handoverDate: DateTime(2026, 3, 25),
      projectManager: 'Amit Bansal',
      supervisor: 'Rakesh Sharma',
      requestType: 'Hardware Adjustment',
      category: ServiceCategory.hardware,
      subject: 'Kitchen Soft-Close Blum Tandembox Drawer Sagging',
      description: 'Pantry unit heavy-load spice pullout drawer is catching bottom runner flange when fully extended.',
      areaRoom: 'Dry Kitchen',
      specificLocation: 'Tall Pantry Unit, Lower 30kg Blum Tandembox drawer',
      issueDate: DateTime.now().subtract(const Duration(hours: 8)),
      priority: ServicePriority.high,
      status: ServiceRequestStatus.newRequest,
      customerExpectation: 'Adjust lateral tilt cams and tighten drawer front bracket screws.',
      preferredServiceDate: DateTime.now().add(const Duration(days: 1)),
      preferredTime: '10:00 AM - 12:00 PM',
      availabilityNotes: 'Morning preference.',
      assignedToName: 'Unassigned',
      assignedToRole: 'Pending Dispatch Assignment',
      createdDate: DateTime.now().subtract(const Duration(hours: 8)),
      dueDate: DateTime.now().add(const Duration(hours: 16)),
      lastActivity: DateTime.now().subtract(const Duration(hours: 8)),
      isWarrantyCovered: true,
      warrantyId: 'WAR-DEL-06-HARD',
      billingStatus: BillingStatus.warrantyCovered,
      estimatedCost: 0.0,
    ),
  ];

  // ==========================================================================
  // 2. COMPLAINTS & MULTI-SNAG REGISTRY
  // ==========================================================================
  static final List<Complaint> complaints = [
    Complaint(
      id: 'CMP-2026-101',
      complaintNumber: 'CMP-1042',
      customerId: 'CUST-DEL-02',
      customerName: 'Vikram Mehta',
      customerPhone: '+91 98110 99887',
      customerEmail: 'vikram.mehta@outlook.com',
      projectId: 'PRJ-MAGNOLIA-402',
      projectName: 'DLF Magnolias #402',
      siteAddress: 'Block B, Villa 402, Golf Course Road, Sector 42, Gurgaon 122002',
      projectManager: 'Amit Bansal',
      supervisor: 'Rakesh Sharma',
      handoverDate: DateTime(2026, 4, 10),
      complaintType: 'Material & Waterproofing Defect',
      subject: 'Monsoon Water Seepage & Balcony Marble Grout Leaks',
      description: 'Heavy rainfall exposed seepage along South Balcony expansion joint, penetrating towards master bedroom timber thresholds. Client requested immediate executive review.',
      areaRoom: 'South Balcony & Master Bedroom Threshold',
      specificLocation: 'External perimeter joint and marble sill interface',
      issueDate: DateTime.now().subtract(const Duration(hours: 6)),
      severity: ComplaintSeverity.critical,
      customerImpact: 'High risk of water damage to ₹18 Lakh imported Italian timber parquet flooring.',
      expectedResolution: 'Core injection grouting, polyurethane elastomeric sealant, and thermal moisture imaging sign-off.',
      status: ComplaintStatus.inCorrection,
      assignedToName: 'Amit Service Manager',
      assignedToRole: 'Regional Service Lead (North)',
      createdDate: DateTime.now().subtract(const Duration(hours: 6)),
      dueDate: DateTime.now().add(const Duration(hours: 2)),
      escalationLevel: 'Project Manager & Management Escalation Active',
      inspectionRequired: true,
      visitId: 'VST-2026-002',
      snags: [
        SnagItem(
          id: 'SNG-101-1',
          snagNumber: 'SNG-01',
          complaintId: 'CMP-2026-101',
          roomArea: 'South Balcony',
          specificLocation: 'Balcony perimeter expansion joint 4.2m length',
          description: 'Failed silicone backing rod allowing rain pooling beneath marble coping.',
          photoUrl: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=400',
          responsibleTeam: 'Civil & Waterproofing Team',
          assignedPerson: 'Harish Civil Engineer',
          priority: ServicePriority.critical,
          targetDate: DateTime.now().add(const Duration(hours: 3)),
          status: SnagItemStatus.inProgress,
        ),
        SnagItem(
          id: 'SNG-101-2',
          snagNumber: 'SNG-02',
          complaintId: 'CMP-2026-101',
          roomArea: 'Master Bedroom Threshold',
          specificLocation: 'Oak timber floor transition strip',
          description: 'Slight moisture discoloration on outer 150mm edge of wood planks.',
          photoUrl: 'https://images.unsplash.com/photo-1540932239986-30128078f3c5?w=400',
          responsibleTeam: 'Flooring Vendor Lead',
          assignedPerson: 'Mukesh Flooring Lead',
          priority: ServicePriority.high,
          targetDate: DateTime.now().add(const Duration(days: 2)),
          status: SnagItemStatus.assigned,
        ),
      ],
    ),

    Complaint(
      id: 'CMP-2026-102',
      complaintNumber: 'CMP-1043',
      customerId: 'CUST-BLR-01',
      customerName: 'Sunita Mehra',
      customerPhone: '+91 98450 12345',
      customerEmail: 'sunita.mehra@gmail.com',
      projectId: 'PRJ-VILLA-42',
      projectName: 'Sobha Royal Pavilion #42',
      siteAddress: 'Tower 3, Penthouse 42, Sarjapur Road, Bangalore 560035',
      projectManager: 'Rajesh Kumar',
      supervisor: 'Suresh Gowda',
      handoverDate: DateTime(2026, 6, 15),
      complaintType: 'Installation & Fitment',
      subject: 'Kitchen Island Quartz Countertop Joint Gap & Cabinet Alignment',
      description: 'Customer noticed a 1.5mm widening epoxy seam on the Calacatta gold quartz island countertop accompanied by two misaligned lower drawers.',
      areaRoom: 'Kitchen Island',
      specificLocation: 'Center seam of 10ft quartz slab and lower pot drawers',
      issueDate: DateTime.now().subtract(const Duration(days: 2)),
      severity: ComplaintSeverity.moderate,
      customerImpact: 'Food particles accumulating in the joint seam; aesthetic dissatisfaction.',
      expectedResolution: 'Re-grout with color-matched Tenax epoxy resin and level drawer slides.',
      status: ComplaintStatus.assigned,
      assignedToName: 'Suresh Gowda (Supervisor)',
      assignedToRole: 'Site Supervisor',
      createdDate: DateTime.now().subtract(const Duration(days: 2)),
      dueDate: DateTime.now().add(const Duration(days: 1)),
      escalationLevel: 'Service Manager Review',
      inspectionRequired: true,
      snags: [
        SnagItem(
          id: 'SNG-102-1',
          snagNumber: 'SNG-01',
          complaintId: 'CMP-2026-102',
          roomArea: 'Kitchen Island',
          specificLocation: '10ft Quartz countertop central seam',
          description: 'Epoxy seam shrinkage causing 1.5mm groove.',
          photoUrl: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=400',
          responsibleTeam: 'Quartz Stonework Specialist',
          assignedPerson: 'Raju Marble Fabricator',
          priority: ServicePriority.high,
          targetDate: DateTime.now().add(const Duration(days: 2)),
          status: SnagItemStatus.assigned,
        ),
        SnagItem(
          id: 'SNG-102-2',
          snagNumber: 'SNG-02',
          complaintId: 'CMP-2026-102',
          roomArea: 'Kitchen Island',
          specificLocation: 'Lower pot and pan drawers #1 & #2',
          description: 'Uneven vertical reveal gap (3mm left vs 6mm right).',
          photoUrl: 'https://images.unsplash.com/photo-1556912173-3bb406ef7e77?w=400',
          responsibleTeam: 'Modular Carpentry Team',
          assignedPerson: 'Dinesh Carpenter Lead',
          priority: ServicePriority.normal,
          targetDate: DateTime.now().add(const Duration(days: 2)),
          status: SnagItemStatus.assigned,
        ),
      ],
    ),

    Complaint(
      id: 'CMP-2026-103',
      complaintNumber: 'CMP-1044',
      customerId: 'CUST-MUM-04',
      customerName: 'Pooja Hegde',
      customerPhone: '+91 98334 11200',
      customerEmail: 'pooja.hegde@altamount.com',
      projectId: 'PRJ-LODHA-18A',
      projectName: 'Lodha Altamount #18A',
      siteAddress: '18th Floor, Flat 18A, Altamount Road, Mumbai 400026',
      projectManager: 'Sneha Kulkarni',
      supervisor: 'Santosh Shinde',
      handoverDate: DateTime(2025, 2, 20),
      complaintType: 'Communication & Response Delay',
      subject: 'Delay in Quotation for Wall Stucco Rectification',
      description: 'Client expressed frustration that touchup estimate took 3 days to receive following initial inquiry.',
      areaRoom: 'Entrance Foyer',
      specificLocation: 'General communication',
      issueDate: DateTime.now().subtract(const Duration(days: 1)),
      severity: ComplaintSeverity.minor,
      customerImpact: 'Client VIP status requires expedited response within 4 hours.',
      expectedResolution: 'Phone call from Service Manager and complimentary touchup consideration.',
      status: ComplaintStatus.resolved,
      assignedToName: 'Amit Service Manager',
      assignedToRole: 'Regional Service Lead',
      createdDate: DateTime.now().subtract(const Duration(days: 1)),
      dueDate: DateTime.now().add(const Duration(hours: 12)),
      resolvedDate: DateTime.now().subtract(const Duration(hours: 4)),
      escalationLevel: 'Resolved by Service Manager Call',
      inspectionRequired: false,
      isCustomerConfirmed: true,
      snags: [],
    ),
  ];

  // ==========================================================================
  // 3. WARRANTY REGISTRY & POLICIES
  // ==========================================================================
  static final List<WarrantyRecord> warranties = [
    WarrantyRecord(
      id: 'WAR-BLR-01-STRUCT',
      warrantyNumber: 'WAR-10YR-2026-0042',
      customerId: 'CUST-BLR-01',
      customerName: 'Sunita Mehra',
      customerPhone: '+91 98450 12345',
      projectId: 'PRJ-VILLA-42',
      projectName: 'Sobha Royal Pavilion #42',
      handoverDate: DateTime(2026, 6, 15),
      milestoneRef: 'FINAL-HANDOVER-SIGN-OFF',
      category: WarrantyCategory.structural10Yr,
      coveredItemWork: 'RCC Structural Waterproofing, Balcony Slabs & Wet Area Barriers',
      description: '10-Year multi-layer crystalline waterproofing barrier covering all balconies, bathrooms, and terrace gardens.',
      startDate: DateTime(2026, 6, 15),
      endDate: DateTime(2036, 6, 14),
      status: WarrantyStatus.active,
      termsSummary: 'Covers core structural seepage, membrane detachment, and joint leakage.',
      inclusions: [
        'Dr. Fixit crystalline membrane failure',
        'Wet area core sunken slab leaks',
        'Expansion joint elastomeric seal breakdown',
      ],
      exclusions: [
        'Post-handover plumbing modifications by 3rd party',
        'External structural earth settlement / earthquakes',
        'Physical drilling into waterproofing membrane by customer',
      ],
      policyDocumentUrl: 'https://cdn.homio.in/docs/warranty_10yr_structural_terms.pdf',
      claimsCount: 0,
      relatedInvoiceNumber: 'INV-2026-4401',
    ),

    WarrantyRecord(
      id: 'WAR-BLR-01-COMP',
      warrantyNumber: 'WAR-1YR-2026-0042',
      customerId: 'CUST-BLR-01',
      customerName: 'Sunita Mehra',
      customerPhone: '+91 98450 12345',
      projectId: 'PRJ-VILLA-42',
      projectName: 'Sobha Royal Pavilion #42',
      handoverDate: DateTime(2026, 6, 15),
      milestoneRef: 'FINAL-HANDOVER-SIGN-OFF',
      category: WarrantyCategory.comprehensive1Yr,
      coveredItemWork: 'Complete Interior Modular Fitments, Hardware, Electrical Wiring & Plumbing',
      description: 'Comprehensive 1-Year bumper-to-bumper warranty covering all modular cabinetry, concealed wiring, and plumbing fittings.',
      startDate: DateTime(2026, 6, 15),
      endDate: DateTime(2027, 6, 14),
      status: WarrantyStatus.active,
      termsSummary: 'Free replacement of defective hardware, free labour, and free on-site service visits.',
      inclusions: [
        'Modular wardrobe soft-close hinges & channels',
        'Concealed wiring shorts & MCB tripping',
        'Sanitary CP fitting leaks and cartridges',
        'Kitchen drawer alignment & runners',
      ],
      exclusions: [
        'Water logging damage from open taps',
        'Scratches and abrasive cleaner chemical damage',
        'Overloading beyond 45kg load per drawer',
      ],
      policyDocumentUrl: 'https://cdn.homio.in/docs/warranty_1yr_comprehensive_terms.pdf',
      claimsCount: 1,
      relatedInvoiceNumber: 'INV-2026-4401',
    ),

    WarrantyRecord(
      id: 'WAR-DEL-02-STRUCT',
      warrantyNumber: 'WAR-10YR-2026-0402',
      customerId: 'CUST-DEL-02',
      customerName: 'Vikram Mehta',
      customerPhone: '+91 98110 99887',
      projectId: 'PRJ-MAGNOLIA-402',
      projectName: 'DLF Magnolias #402',
      handoverDate: DateTime(2026, 4, 10),
      milestoneRef: 'FINAL-HANDOVER-SIGN-OFF',
      category: WarrantyCategory.structural10Yr,
      coveredItemWork: 'External Balconies, Sunken Bathrooms & Terrace Waterproofing',
      description: '10-Year heavy-duty polyurea waterproofing barrier with certified flood test verification.',
      startDate: DateTime(2026, 4, 10),
      endDate: DateTime(2036, 4, 9),
      status: WarrantyStatus.claimRaised,
      termsSummary: 'Immediate 4-hour emergency response for water penetration.',
      inclusions: [
        'Balcony expansion joint failures',
        'Water penetration through coping stones',
      ],
      exclusions: [
        'Damage caused by third-party AC outdoor unit drilling',
      ],
      policyDocumentUrl: 'https://cdn.homio.in/docs/warranty_10yr_structural_terms.pdf',
      claimsCount: 1,
      relatedInvoiceNumber: 'INV-2026-3912',
    ),

    WarrantyRecord(
      id: 'WAR-MUM-04-PU',
      warrantyNumber: 'WAR-2YR-2025-0018',
      customerId: 'CUST-MUM-04',
      customerName: 'Pooja Hegde',
      customerPhone: '+91 98334 11200',
      projectId: 'PRJ-LODHA-18A',
      projectName: 'Lodha Altamount #18A',
      handoverDate: DateTime(2025, 2, 20),
      milestoneRef: 'FINAL-HANDOVER-SIGN-OFF',
      category: WarrantyCategory.surfacePUFinish,
      coveredItemWork: 'Italian PU Polish & Wall Stucco Coating',
      description: '2-Year warranty on high-gloss and matte PU furniture coatings against bubbling, peeling, or yellowing.',
      startDate: DateTime(2025, 2, 20),
      endDate: DateTime.now().add(const Duration(days: 15)), // Expiring soon!
      status: WarrantyStatus.expiringSoon,
      termsSummary: 'Covers spontaneous peeling and discoloration; excludes mechanical abrasions.',
      inclusions: [
        'Spontaneous peeling / blistering',
        'UV yellowing of white PU coatings',
      ],
      exclusions: [
        'Mechanical scratches, furniture shifting impacts, scuffs',
      ],
      policyDocumentUrl: 'https://cdn.homio.in/docs/warranty_2yr_pu_terms.pdf',
      claimsCount: 0,
      relatedInvoiceNumber: 'INV-2025-1801',
    ),
  ];

  // ==========================================================================
  // 4. WARRANTY CLAIMS
  // ==========================================================================
  static final List<WarrantyClaim> warrantyClaims = [
    WarrantyClaim(
      id: 'CLM-2026-501',
      claimNumber: 'CLM-BLR-001',
      warrantyId: 'WAR-BLR-01-COMP',
      warrantyNumber: 'WAR-1YR-2026-0042',
      customerId: 'CUST-BLR-01',
      customerName: 'Sunita Mehra',
      projectId: 'PRJ-VILLA-42',
      projectName: 'Sobha Royal Pavilion #42',
      issueArea: 'Master Bedroom Wardrobe',
      issueDate: DateTime.now().subtract(const Duration(hours: 18)),
      description: 'Hydraulic Blum hinge failure on sliding wardrobe shutter. Hinge piston seized.',
      evidenceUrls: ['https://images.unsplash.com/photo-1558997519-83ea9252def8?w=500'],
      requestedResolution: 'Replacement Blum 110-deg soft-close hinge with free installation.',
      claimDate: DateTime.now().subtract(const Duration(hours: 18)),
      status: WarrantyStatus.approved,
      reviewerName: 'Amit Service Manager',
      reviewDate: DateTime.now().subtract(const Duration(hours: 14)),
      approvedCoverageAmount: 1850.0,
    ),

    WarrantyClaim(
      id: 'CLM-2026-502',
      claimNumber: 'CLM-DEL-002',
      warrantyId: 'WAR-DEL-02-STRUCT',
      warrantyNumber: 'WAR-10YR-2026-0402',
      customerId: 'CUST-DEL-02',
      customerName: 'Vikram Mehta',
      projectId: 'PRJ-MAGNOLIA-402',
      projectName: 'DLF Magnolias #402',
      issueArea: 'South Balcony Expansion Joint',
      issueDate: DateTime.now().subtract(const Duration(hours: 6)),
      description: 'Water seepage during monsoon rainfall. Moisture penetrating beneath marble floor threshold.',
      evidenceUrls: ['https://images.unsplash.com/photo-1513694203232-719a280e022f?w=500'],
      requestedResolution: 'Emergency PU injection grouting and re-sealing under 10-Yr Structural Warranty.',
      claimDate: DateTime.now().subtract(const Duration(hours: 6)),
      status: WarrantyStatus.claimUnderReview,
      reviewerName: 'Harish Civil Engineer',
      reviewDate: DateTime.now().subtract(const Duration(hours: 4)),
      approvedCoverageAmount: 12000.0,
    ),
  ];

  // ==========================================================================
  // 5. FIELD SERVICE VISITS
  // ==========================================================================
  static final List<ServiceVisit> serviceVisits = [
    ServiceVisit(
      id: 'VST-2026-001',
      visitNumber: 'VST-BLR-901',
      serviceRequestId: 'REQ-2026-001',
      customerId: 'CUST-BLR-01',
      customerName: 'Sunita Mehra',
      customerPhone: '+91 98450 12345',
      projectId: 'PRJ-VILLA-42',
      projectName: 'Sobha Royal Pavilion #42',
      siteAddress: 'Tower 3, Penthouse 42, Sarjapur Road, Bangalore 560035',
      visitType: VisitType.correctiveRepair,
      purpose: 'Replace jammed wardrobe soft-close hydraulic hinge & align sliding track',
      visitDate: DateTime.now().add(const Duration(days: 1)),
      startTime: '10:00 AM',
      endTime: '11:30 AM',
      assignedEmployee: 'Suresh Gowda (Supervisor)',
      assignedTechnician: 'Dinesh Carpenter Lead',
      contactPerson: 'Sunita Mehra',
      contactNumber: '+91 98450 12345',
      specialInstructions: 'Bring shoe covers and drop cloth. Master bedroom has white Italian marble.',
      requiredTools: ['Cordless drill', 'Laser level', 'Torx bit set', 'Silicone spray'],
      requiredMaterials: ['2x Blum 110-deg soft-close hinges', 'Track guide buffers'],
      status: ServiceVisitStatus.confirmed,
      outcome: 'Scheduled for tomorrow morning.',
      checklist: [
        const VisitChecklistItem(id: 'CHK-01', title: 'Verify client reported issue on site', isChecked: false),
        const VisitChecklistItem(id: 'CHK-02', title: 'Inspect surrounding woodwork for secondary rubbing', isChecked: false),
        const VisitChecklistItem(id: 'CHK-03', title: 'Replace defective hinge assembly with OEM part', isChecked: false),
        const VisitChecklistItem(id: 'CHK-04', title: 'Lubricate sliding tracks with dry PTFE spray', isChecked: false),
        const VisitChecklistItem(id: 'CHK-05', title: 'Demonstrate smooth closing to client', isChecked: false),
        const VisitChecklistItem(id: 'CHK-06', title: 'Obtain digital client sign-off on mobile app', isChecked: false),
      ],
    ),

    ServiceVisit(
      id: 'VST-2026-002',
      visitNumber: 'VST-DEL-902',
      serviceRequestId: 'REQ-2026-002',
      complaintId: 'CMP-2026-101',
      customerId: 'CUST-DEL-02',
      customerName: 'Vikram Mehta',
      customerPhone: '+91 98110 99887',
      projectId: 'PRJ-MAGNOLIA-402',
      projectName: 'DLF Magnolias #402',
      siteAddress: 'Block B, Villa 402, Golf Course Road, Sector 42, Gurgaon 122002',
      visitType: VisitType.diagnosis,
      purpose: 'Emergency moisture tracing & balcony expansion joint injection grouting',
      visitDate: DateTime.now(),
      startTime: '02:00 PM',
      endTime: '04:30 PM',
      assignedEmployee: 'Amit Service Manager',
      assignedTechnician: 'Harish Civil Engineer',
      contactPerson: 'Vikram Mehta',
      contactNumber: '+91 98110 99887',
      specialInstructions: 'Gate pass authorized under Homio Operations vehicle HR-26-8802.',
      requiredTools: ['Thermal moisture camera', 'PU pressure pump', 'Moisture pin probe'],
      requiredMaterials: ['Fosroc Polyurethane expansion resin', 'Backing rods'],
      status: ServiceVisitStatus.checkedIn,
      outcome: 'Technician on-site conducting moisture test.',
      checkInRecord: VisitCheckInRecord(
        checkInTime: DateTime.now().subtract(const Duration(minutes: 45)),
        latitude: 28.4595,
        longitude: 77.0266,
        siteAddress: 'DLF Magnolias Block B, Sector 42, Gurgaon',
        isGeofenceValid: true,
        selfiePhotoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200',
      ),
      checklist: [
        const VisitChecklistItem(id: 'CHK-11', title: 'Perform thermal camera moisture scan', isChecked: true, remarks: 'Moisture concentrated in 1.2m radius near post 3'),
        const VisitChecklistItem(id: 'CHK-12', title: 'Identify exact water ingress point', isChecked: true, remarks: 'Confirmed failure at expansion joint coping'),
        const VisitChecklistItem(id: 'CHK-13', title: 'Inject elastomeric PU grout', isChecked: false),
        const VisitChecklistItem(id: 'CHK-14', title: 'Seal outer weather-facing joint with UV silicone', isChecked: false),
        const VisitChecklistItem(id: 'CHK-15', title: 'Water flood test for 30 minutes', isChecked: false),
      ],
    ),

    ServiceVisit(
      id: 'VST-2026-003',
      visitNumber: 'VST-MUM-903',
      serviceRequestId: 'REQ-2026-003',
      customerId: 'CUST-MUM-03',
      customerName: 'Rajesh Khanna',
      customerPhone: '+91 98200 55443',
      projectId: 'PRJ-TRUMP-2104',
      projectName: 'Trump Towers #2104',
      siteAddress: 'Tower A, Floor 21, Flat 2104, Worli, Mumbai 400018',
      visitType: VisitType.correctiveRepair,
      purpose: 'Replace dimmable crystal chandelier LED driver with smart Zigbee unit',
      visitDate: DateTime.now().subtract(const Duration(days: 1)),
      startTime: '02:00 PM',
      endTime: '03:15 PM',
      assignedEmployee: 'Deepak Patil (Supervisor)',
      assignedTechnician: 'Santosh Electrician',
      contactPerson: 'Rajesh Khanna',
      contactNumber: '+91 98200 55443',
      requiredTools: ['Multimeter', 'Fibreglass ladder', 'Insulated tool kit'],
      requiredMaterials: ['150W Zigbee phase-cut dimmable driver'],
      status: ServiceVisitStatus.completed,
      outcome: 'Work completed successfully. Client signed off.',
      checkInRecord: VisitCheckInRecord(
        checkInTime: DateTime.now().subtract(const Duration(days: 1, hours: 2)),
        latitude: 18.9986,
        longitude: 72.8174,
        siteAddress: 'Trump Towers Worli, Mumbai',
        isGeofenceValid: true,
        selfiePhotoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200',
      ),
      checklist: [
        const VisitChecklistItem(id: 'CHK-21', title: 'Isolate chandelier breaker switch', isChecked: true),
        const VisitChecklistItem(id: 'CHK-22', title: 'Remove flickering magnetic driver', isChecked: true),
        const VisitChecklistItem(id: 'CHK-23', title: 'Install and wire Zigbee dimmable module', isChecked: true),
        const VisitChecklistItem(id: 'CHK-24', title: 'Test dimming range 10% to 100% without flicker', isChecked: true),
        const VisitChecklistItem(id: 'CHK-25', title: 'Client satisfaction demonstration', isChecked: true),
      ],
      report: VisitReport(
        arrivalTime: DateTime.now().subtract(const Duration(days: 1, hours: 2)),
        completionTime: DateTime.now().subtract(const Duration(days: 1, hours: 1)),
        diagnosis: 'Previous magnetic driver had high harmonic distortion causing LED triac flicker.',
        workPerformed: 'Replaced with Philips certified smart Zigbee phase-cut driver. Paired with living room scene controller.',
        materialsUsed: '1x 150W Zigbee Dimmer Driver, 2x Wago connectors',
        labourHours: 1.25,
        beforePhotoUrls: ['https://images.unsplash.com/photo-1540932239986-30128078f3c5?w=500'],
        afterPhotoUrls: ['https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=500'],
        customerSignatureName: 'Rajesh Khanna',
        customerConfirmed: true,
        rating: 5.0,
        internalRemarks: 'Job executed cleanly. Client delighted with instant scene response.',
      ),
    ),
  ];

  // ==========================================================================
  // 6. RETENTION & PROACTIVE FOLLOW-UPS
  // ==========================================================================
  static final List<ServiceFollowUp> retentionFollowUps = [
    ServiceFollowUp(
      id: 'RET-2026-001',
      customerId: 'CUST-BLR-01',
      customerName: 'Sunita Mehra',
      customerPhone: '+91 98450 12345',
      customerEmail: 'sunita.mehra@gmail.com',
      projectId: 'PRJ-VILLA-42',
      projectName: 'Sobha Royal Pavilion #42',
      handoverDate: DateTime(2026, 6, 15),
      followUpType: FollowUpType.postHandoverCheckin,
      reason: '30-Day Post-Handover Health Check & Living Experience Inquiry',
      assignedEmployee: 'Priya Service Telecaller',
      scheduledDate: DateTime.now().subtract(const Duration(days: 3)),
      conductedDate: DateTime.now().subtract(const Duration(days: 3)),
      preferredTime: '11:00 AM',
      channel: 'Phone & WhatsApp',
      objective: 'Check on modular kitchen and wardrobe performance after 1 month of full occupancy.',
      notes: 'Client loves the aesthetic and lighting. Mentioned the wardrobe shutter issue which was immediately logged as SR-BLR-8801.',
      outcome: FollowUpOutcome.serviceRequired,
      nextFollowUpDate: DateTime.now().add(const Duration(days: 7)),
      satisfactionRating: 4.8,
    ),

    ServiceFollowUp(
      id: 'RET-2026-002',
      customerId: 'CUST-DEL-02',
      customerName: 'Vikram Mehta',
      customerPhone: '+91 98110 99887',
      customerEmail: 'vikram.mehta@outlook.com',
      projectId: 'PRJ-MAGNOLIA-402',
      projectName: 'DLF Magnolias #402',
      handoverDate: DateTime(2026, 4, 10),
      followUpType: FollowUpType.complaintFollowUp,
      reason: 'Monsoon Balcony Seepage Rectification Follow-up',
      assignedEmployee: 'Amit Service Manager',
      scheduledDate: DateTime.now().add(const Duration(days: 2)),
      preferredTime: '04:00 PM',
      channel: 'Phone',
      objective: 'Follow up post emergency visit to verify zero residual dampness after grouting.',
      notes: 'Scheduled call with Mr. Mehta after weekend rains.',
      outcome: FollowUpOutcome.followUpRequired,
      nextFollowUpDate: DateTime.now().add(const Duration(days: 2)),
    ),

    ServiceFollowUp(
      id: 'RET-2026-003',
      customerId: 'CUST-MUM-03',
      customerName: 'Rajesh Khanna',
      customerPhone: '+91 98200 55443',
      customerEmail: 'rajesh.khanna@towers.in',
      projectId: 'PRJ-TRUMP-2104',
      projectName: 'Trump Towers #2104',
      handoverDate: DateTime(2026, 7, 1),
      followUpType: FollowUpType.feedbackRequest,
      reason: 'Google 5-Star Review & Video Testimonial Invitation',
      assignedEmployee: 'Priya Service Telecaller',
      scheduledDate: DateTime.now().subtract(const Duration(days: 1)),
      conductedDate: DateTime.now().subtract(const Duration(days: 1)),
      preferredTime: '12:00 PM',
      channel: 'WhatsApp',
      objective: 'Send Google review link after successful chandelier driver replacement.',
      notes: 'Customer gave 5.0 rating on WhatsApp and posted review on Google Maps.',
      outcome: FollowUpOutcome.feedbackGiven,
      satisfactionRating: 5.0,
    ),

    ServiceFollowUp(
      id: 'RET-2026-004',
      customerId: 'CUST-MUM-04',
      customerName: 'Pooja Hegde',
      customerPhone: '+91 98334 11200',
      customerEmail: 'pooja.hegde@altamount.com',
      projectId: 'PRJ-LODHA-18A',
      projectName: 'Lodha Altamount #18A',
      handoverDate: DateTime(2025, 2, 20),
      followUpType: FollowUpType.maintenanceReminder,
      reason: 'Annual Maintenance Contract (AMC) & Warranty Renewal Offer',
      assignedEmployee: 'Priya Service Telecaller',
      scheduledDate: DateTime.now(),
      preferredTime: '03:00 PM',
      channel: 'Phone',
      objective: 'Discuss comprehensive annual maintenance contract as 2-yr PU warranty expires in 15 days.',
      notes: 'Customer expressed interest in annual marble re-polishing and AC deep-cleaning package.',
      outcome: FollowUpOutcome.interested,
      nextFollowUpDate: DateTime.now().add(const Duration(days: 5)),
      satisfactionRating: 4.5,
    ),

    ServiceFollowUp(
      id: 'RET-2026-005',
      customerId: 'CUST-BLR-05',
      customerName: 'Rohan Deshmukh',
      customerPhone: '+91 99001 22334',
      customerEmail: 'rohan.deshmukh@gmail.com',
      projectId: 'PRJ-PRESTIGE-108',
      projectName: 'Prestige Golfshire #108',
      handoverDate: DateTime(2026, 5, 18),
      followUpType: FollowUpType.repeatServiceOpportunity,
      reason: 'Outdoor Deck Pergola & BBQ Counter Addition Discussion',
      assignedEmployee: 'Amit Service Manager',
      scheduledDate: DateTime.now().add(const Duration(days: 3)),
      preferredTime: '11:30 AM',
      channel: 'In-Person Meeting',
      objective: 'Present proposal for teakwood terrace pergola expansion.',
      notes: 'Repeat revenue potential: ₹12.5 Lakhs.',
      outcome: FollowUpOutcome.followUpRequired,
      nextFollowUpDate: DateTime.now().add(const Duration(days: 3)),
    ),
  ];

  // ==========================================================================
  // 7. CUSTOMER FEEDBACK & CSAT
  // ==========================================================================
  static final List<CustomerFeedback> customerFeedbacks = [
    CustomerFeedback(
      id: 'FDB-2026-001',
      feedbackNumber: 'CSAT-8801',
      customerId: 'CUST-MUM-03',
      customerName: 'Rajesh Khanna',
      customerPhone: '+91 98200 55443',
      projectId: 'PRJ-TRUMP-2104',
      projectName: 'Trump Towers #2104',
      serviceRequestId: 'REQ-2026-003',
      visitId: 'VST-2026-003',
      touchpoint: 'Post-Service Resolution',
      submittedDate: DateTime.now().subtract(const Duration(hours: 20)),
      overallRating: 5.0,
      qualityRating: 5.0,
      timelinessRating: 5.0,
      professionalismRating: 5.0,
      communicationRating: 4.8,
      resolutionRating: 5.0,
      issueResolvedAnswer: IssueResolutionAnswer.yes,
      whatWentWell: 'Technician Santosh was exceptionally punctual, polite and solved the chandelier dimming issue in 45 minutes.',
      whatCouldImprove: 'Nothing, great service experience.',
      customerComments: 'Homio after-sales responsiveness matches luxury brand standards. Very impressed!',
    ),

    CustomerFeedback(
      id: 'FDB-2026-002',
      feedbackNumber: 'CSAT-8802',
      customerId: 'CUST-BLR-01',
      customerName: 'Sunita Mehra',
      customerPhone: '+91 98450 12345',
      projectId: 'PRJ-VILLA-42',
      projectName: 'Sobha Royal Pavilion #42',
      touchpoint: '30-Day Handover Review',
      submittedDate: DateTime.now().subtract(const Duration(days: 3)),
      overallRating: 4.6,
      qualityRating: 5.0,
      timelinessRating: 4.2,
      professionalismRating: 4.8,
      communicationRating: 4.5,
      resolutionRating: 4.5,
      issueResolvedAnswer: IssueResolutionAnswer.yes,
      whatWentWell: 'The 3D design to actual execution match is stunning. The kitchen island is our family centerpiece.',
      whatCouldImprove: 'Speed of dispatch for minor wardrobe hinge issues could be slightly faster.',
      customerComments: 'Delighted with the final home. Would definitely recommend Homio to friends.',
    ),

    CustomerFeedback(
      id: 'FDB-2026-003',
      feedbackNumber: 'CSAT-8803',
      customerId: 'CUST-DEL-02',
      customerName: 'Vikram Mehta',
      customerPhone: '+91 98110 99887',
      projectId: 'PRJ-MAGNOLIA-402',
      projectName: 'DLF Magnolias #402',
      serviceRequestId: 'REQ-2026-002',
      touchpoint: 'Monsoon Seepage Incident',
      submittedDate: DateTime.now().subtract(const Duration(hours: 2)),
      overallRating: 2.5, // Low Rating!
      qualityRating: 3.0,
      timelinessRating: 3.0,
      professionalismRating: 4.0,
      communicationRating: 3.0,
      resolutionRating: 2.0,
      issueResolvedAnswer: IssueResolutionAnswer.partially,
      whatWentWell: 'Technician arrived quickly once escalated.',
      whatCouldImprove: 'A luxury villa should never have water seepage through balcony joints in the first place.',
      customerComments: 'I expect 100% resolution before next rainstorm. Waiting for final thermal moisture report.',
      isEscalated: true,
      escalationReason: 'Low CSAT rating (< 3.0) and partial resolution reported on critical waterproofing snag.',
      managerFollowUpNotes: 'Amit Service Manager personally overseeing on-site injection grouting and following up with client.',
    ),
  ];

  // ==========================================================================
  // 8. COMMERCIAL SERVICE ESTIMATES
  // ==========================================================================
  static final List<ServiceEstimate> serviceEstimates = [
    ServiceEstimate(
      id: 'EST-2026-01',
      estimateNumber: 'EST-MUM-4401',
      serviceRequestId: 'REQ-2026-004',
      customerName: 'Pooja Hegde',
      projectName: 'Lodha Altamount #18A',
      items: [
        const EstimateItem(
          description: 'Italian Stucco Touchup Compound (Shade #PU-STUCCO-882)',
          quantity: 1,
          unit: 'Kit',
          rate: 1500.0,
          labourCost: 1500.0,
          materialCost: 800.0,
        ),
        const EstimateItem(
          description: 'Protective Matte Acrylic Topcoat Sealer',
          quantity: 1,
          unit: 'Canister',
          rate: 700.0,
          labourCost: 500.0,
          materialCost: 500.0,
        ),
      ],
      discount: 500.0,
      taxRate: 0.18,
      generatedDate: DateTime.now().subtract(const Duration(days: 1)),
      validityDate: DateTime.now().add(const Duration(days: 14)),
      isApprovedByCustomer: false,
      paymentLink: 'https://pay.homio.in/est/EST-MUM-4401',
      isPaid: false,
    ),
  ];

  // Backward compatibility legacy lists
  static final List<SnagTicket> snagTickets = [
    SnagTicket(
      id: 'SNG-001',
      ticketNumber: 'TKT-2026-8801',
      projectId: 'PRJ-VILLA-42',
      projectName: 'Sobha Royal Pavilion #42',
      clientName: 'Sunita Mehra',
      clientPhone: '+91 98450 12345',
      handoverDate: DateTime(2026, 6, 15),
      category: ServiceCategory.carpentry,
      priority: ServicePriority.high,
      warrantyStatus: WarrantyStatus.active,
      title: 'Master Bedroom Wardrobe Hydraulic Soft-Close Malfunction',
      description: 'Right hydraulic hinge on the 8ft PU painted sliding shutter is jammed and squeaking upon closure.',
      reportedDate: DateTime.now().subtract(const Duration(hours: 14)),
      slaDeadline: DateTime.now().add(const Duration(hours: 10)),
      assignedTechnician: 'Dinesh Carpenter Lead',
      technicianPhone: '+91 98221 44556',
      status: SnagStatus.dispatched,
      beforePhotoUrl: 'https://images.unsplash.com/photo-1558997519-83ea9252def8?w=300',
    ),
  ];

  static final List<RetentionCallRecord> retentionCalls = [
    RetentionCallRecord(
      id: 'RET-101',
      clientId: 'CLI-01',
      clientName: 'Sunita Mehra',
      clientPhone: '+91 98450 12345',
      projectName: 'Sobha Royal Pavilion #42',
      handoverDate: DateTime(2026, 6, 15),
      scheduledDate: DateTime.now().subtract(const Duration(days: 5)),
      conductedDate: DateTime.now().subtract(const Duration(days: 5)),
      callStatus: CallStatus.completed,
      csatScore: 9.2,
      designQualityRating: 9.5,
      timelineRating: 9.0,
      behaviourRating: 9.0,
      callerName: 'Priya Service Telecaller',
      feedbackNotes: 'Client expressed high appreciation for 3D render fidelity and on-time carpentry delivery. Left a 5-star Google review.',
      reviewLinkSent: true,
      reviewPosted: true,
      referralLeadName: 'Kavita Chawla (Sister)',
      referralLeadPhone: '+91 98450 77889',
      referralRewardStatus: ReferralRewardStatus.credited,
    ),
  ];
}
