import 'ai_suite_models.dart';

class AiSuiteMockData {
  static final AiCommercialConfig defaultCommercialConfig = AiCommercialConfig(
    doubtQueryFee: 50.0,
    freeDoubtQueriesQuota: 3,
    consultation30MinFee: 300.0,
    platformRevenueSharePercent: 50.0,
    designerRevenueSharePercent: 50.0,
    roomDesignCreditCost: 10,
    vastuAnalysisCreditCost: 15,
    budgetEstimateCreditCost: 5,
    propertyContactUnlockFee: 500.0,
  );

  static const List<CreditPackage> creditPackages = [
    CreditPackage(
      id: 'pkg_starter',
      title: 'Starter Pack',
      credits: 100,
      price: 499.0,
      bonusCredits: 10,
      validity: '180 Days',
      description: 'Ideal for 1-2 room redesigns, quick Vastu checks & budget estimations.',
    ),
    CreditPackage(
      id: 'pkg_standard',
      title: 'Standard Creator',
      credits: 500,
      price: 1999.0,
      bonusCredits: 75,
      isPopular: true,
      validity: '365 Days',
      description: 'Most popular choice for 2BHK/3BHK full home visualization & material estimation.',
    ),
    CreditPackage(
      id: 'pkg_pro',
      title: 'Pro Designer',
      credits: 1200,
      price: 3999.0,
      bonusCredits: 250,
      validity: '365 Days',
      description: 'High-volume generation for studios, architects, and multi-flat property projects.',
    ),
    CreditPackage(
      id: 'pkg_enterprise',
      title: 'Enterprise Studio',
      credits: 3000,
      price: 8999.0,
      bonusCredits: 800,
      validity: 'Lifetime',
      description: 'Unlimited team multi-seat generation with dedicated priority GPU rendering queue.',
    ),
  ];

  static final List<AiJobEntity> initialJobs = [
    AiJobEntity(
      id: 'JOB-9021',
      productType: 'Room Designer',
      title: 'Italian Luxury Living Room 4K Render',
      user: 'Rahul Sharma (DLF Phase 5)',
      createdAt: DateTime.now().subtract(const Duration(minutes: 8)),
      startedAt: DateTime.now().subtract(const Duration(minutes: 7)),
      completedAt: DateTime.now().subtract(const Duration(minutes: 5)),
      status: AiJobStatus.completed,
      creditsCharged: 10,
      prompt: 'Living room, Modern Luxury, Concealed warm cove, Bookmatched marble TV unit',
    ),
    AiJobEntity(
      id: 'JOB-9022',
      productType: 'Vastu Consultant',
      title: '16-Zone Floor Plan Energy Diagnostic',
      user: 'Pooja Verma (Prestige Lakeside)',
      createdAt: DateTime.now().subtract(const Duration(minutes: 18)),
      startedAt: DateTime.now().subtract(const Duration(minutes: 17)),
      completedAt: DateTime.now().subtract(const Duration(minutes: 14)),
      status: AiJobStatus.completed,
      creditsCharged: 15,
      prompt: 'North-East 42° calibration, Agneya kitchen check, Master bedroom southwest analysis',
    ),
    AiJobEntity(
      id: 'JOB-9023',
      productType: 'Room Designer',
      title: 'Japandi Master Bedroom Render',
      user: 'Arjun Mehta (Lodha Park)',
      createdAt: DateTime.now().subtract(const Duration(minutes: 25)),
      startedAt: DateTime.now().subtract(const Duration(minutes: 24)),
      status: AiJobStatus.processing,
      creditsCharged: 10,
      prompt: 'Japandi bedroom, light oak fluting, neutral linen textures, low wooden platform bed',
    ),
    AiJobEntity(
      id: 'JOB-9024',
      productType: 'Room Designer',
      title: 'Neo-Classical Modular Kitchen 4K',
      user: 'Kavita Singh (Godrej Woods)',
      createdAt: DateTime.now().subtract(const Duration(minutes: 42)),
      startedAt: DateTime.now().subtract(const Duration(minutes: 41)),
      completedAt: DateTime.now().subtract(const Duration(minutes: 40)),
      status: AiJobStatus.failed,
      creditsCharged: 10,
      prompt: 'Neo-classical kitchen, champagne profile handles, quartz waterfall island',
      failureReason: 'GPU Memory OutOfBounds: High-resolution depth tensor failed on ceiling mesh.',
    ),
    AiJobEntity(
      id: 'JOB-9025',
      productType: 'Budget Calculator',
      title: '3BHK Wardrobe & Kitchen Material BOQ',
      user: 'Sanjay Deshmukh (Brigade Gateway)',
      createdAt: DateTime.now().subtract(const Duration(hours: 2)),
      startedAt: DateTime.now().subtract(const Duration(hours: 2)),
      completedAt: DateTime.now().subtract(const Duration(hours: 2)),
      status: AiJobStatus.completed,
      creditsCharged: 5,
      prompt: 'Master wardrobe HDHMR acrylic finish + U-shaped modular kitchen estimation',
    ),
  ];

  static final List<WalletTransaction> walletTransactions = [
    WalletTransaction(
      id: 'TXN-801',
      date: DateTime.now().subtract(const Duration(hours: 1)),
      title: 'Standard Pack Recharge (575 Credits)',
      type: WalletTransactionType.purchase,
      credits: 575,
      rupeeAmount: 1999.0,
      referenceId: 'RAZOR_PAY_9824',
      clientName: 'Rahul Sharma',
    ),
    WalletTransaction(
      id: 'TXN-802',
      date: DateTime.now().subtract(const Duration(hours: 2)),
      title: 'Room Redesign - DLF Living Room',
      type: WalletTransactionType.roomDebit,
      credits: -10,
      rupeeAmount: 50.0,
      referenceId: 'JOB-9021',
      clientName: 'Rahul Sharma',
    ),
    WalletTransaction(
      id: 'TXN-803',
      date: DateTime.now().subtract(const Duration(hours: 5)),
      title: '16-Zone Vastu Diagnostic - Prestige Flat',
      type: WalletTransactionType.vastuDebit,
      credits: -15,
      rupeeAmount: 75.0,
      referenceId: 'JOB-9022',
      clientName: 'Pooja Verma',
    ),
    WalletTransaction(
      id: 'TXN-804',
      date: DateTime.now().subtract(const Duration(hours: 8)),
      title: '30-Min Video Consultation - Ananya Iyer',
      type: WalletTransactionType.consultationDebit,
      credits: 0,
      rupeeAmount: 300.0,
      referenceId: 'CNS-501',
      clientName: 'Rahul Sharma',
      designerName: 'Ananya Iyer',
      platformShare: 150.0,
      designerShare: 150.0,
    ),
    WalletTransaction(
      id: 'TXN-805',
      date: DateTime.now().subtract(const Duration(days: 1)),
      title: 'Refund: Failed GPU Generation JOB-9024',
      type: WalletTransactionType.refund,
      credits: 10,
      rupeeAmount: 50.0,
      referenceId: 'JOB-9024',
      clientName: 'Kavita Singh',
    ),
  ];

  static final List<AiRoomDesignEntity> mockRoomDesigns = [
    AiRoomDesignEntity(
      id: 'DES-101',
      title: 'Modern Luxury Living Room',
      projectName: 'DLF Phase 5 Penthouse',
      roomType: AiRoomType.livingRoom,
      lighting: AiLightingMode.warm,
      style: AiDesignStyle.luxury,
      colorPalette: AiColorPalette.neutral,
      customRequirements: 'Preserve marble floor, add concealed acoustic fluted wood TV wall, warm ceiling cove.',
      carpetAreaSqFt: 340.0,
      originalImageUrl: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=1200&auto=format&fit=crop&q=80',
      generatedImageUrl: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=1200&auto=format&fit=crop&q=80',
      createdAt: DateTime(2026, 9, 8, 14, 30),
      creditsUsed: 10,
      isSaved: true,
      advancedSettings: {
        'Preserve layout': true,
        'Add concealed storage': true,
        'Add false ceiling': true,
        'Add accent artwork': true,
      },
      preliminarySpecs: [
        AiMaterialSpecItem(
          category: 'Flooring',
          suggestedMaterial: 'Italian Statuario Marble Polish',
          specification: 'Diamond glazed crystal buffing with epoxy grouting',
          quantity: 340.0,
          unit: 'Sq.Ft.',
        ),
        AiMaterialSpecItem(
          category: 'Wall Finish',
          suggestedMaterial: 'Charcoal Smoked Oak Veneer Panelling',
          specification: '12mm calibrated MR plywood with 4mm natural crown-cut veneer',
          quantity: 180.0,
          unit: 'Sq.Ft.',
        ),
        AiMaterialSpecItem(
          category: 'Lighting',
          suggestedMaterial: 'Philips Hue Cob Strip 3000K & Magnetic Track',
          specification: 'Concealed aluminium profile channels with glare-free diffusers',
          quantity: 48.0,
          unit: 'R.Ft.',
        ),
        AiMaterialSpecItem(
          category: 'Furniture',
          suggestedMaterial: 'Modular 3-Seater Velvet Sofa with Chaise',
          specification: 'Solid salwood frame, 40-density high-resilience foam',
          quantity: 1.0,
          unit: 'Nos',
        ),
      ],
    ),
    AiRoomDesignEntity(
      id: 'DES-102',
      title: 'Japandi Minimalist Master Suite',
      projectName: 'Lodha Bellissimo',
      roomType: AiRoomType.masterBedroom,
      lighting: AiLightingMode.natural,
      style: AiDesignStyle.japandi,
      colorPalette: AiColorPalette.earthy,
      customRequirements: 'Low platform wooden bed, limewash texture paint on headboard, minimal wardrobe.',
      carpetAreaSqFt: 260.0,
      originalImageUrl: 'https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?w=1200&auto=format&fit=crop&q=80',
      generatedImageUrl: 'https://images.unsplash.com/photo-1598928506311-c55ded91a20c?w=1200&auto=format&fit=crop&q=80',
      createdAt: DateTime(2026, 9, 9, 11, 15),
      creditsUsed: 10,
      isSaved: true,
      advancedSettings: {
        'Preserve layout': false,
        'Add wardrobe': true,
        'Add plants': true,
      },
      preliminarySpecs: [
        AiMaterialSpecItem(
          category: 'Flooring',
          suggestedMaterial: 'Engineered White Oak Wood Planks',
          specification: '15mm click-lock tongue and groove with acoustic underlay',
          quantity: 260.0,
          unit: 'Sq.Ft.',
        ),
        AiMaterialSpecItem(
          category: 'Wall Finish',
          suggestedMaterial: 'Mineral Limewash Wabi-Sabi Plaster',
          specification: 'Eco-friendly breathable lime putty with soft clouding',
          quantity: 220.0,
          unit: 'Sq.Ft.',
        ),
        AiMaterialSpecItem(
          category: 'Furniture',
          suggestedMaterial: 'Floating Teak Bed with Cane Headboard',
          specification: 'Seasoned CP teak wood with natural matte PU seal',
          quantity: 1.0,
          unit: 'Nos',
        ),
      ],
    ),
  ];

  static final List<AiVastuReportEntity> mockVastuReports = [
    AiVastuReportEntity(
      id: 'VAS-701',
      projectName: 'Prestige Lakeside Habitat 3BHK',
      propertyType: 'Residential Apartment',
      plotAreaSqFt: 1850.0,
      builtUpAreaSqFt: 1650.0,
      totalFloors: 1,
      bedrooms: 3,
      bathrooms: 3,
      entranceDirection: VastuDirection.northeast,
      kitchenDirection: VastuDirection.southeast,
      northCalibratedDegrees: 42.5,
      overallScore: 84,
      floorPlanImageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1000&auto=format&fit=crop&q=80',
      createdAt: DateTime(2026, 9, 7, 16, 20),
      creditsUsed: 15,
      positiveObservations: [
        'Main Entrance in Northeast (Ishanya) attracts immense prosperity, peace and positive prana.',
        'Kitchen perfectly aligned in Agneya (South-East), boosting family health and digestive vitality.',
        'Master bedroom located in South-West (Nairutya), establishing grounding stability and leadership.',
      ],
      areasRequiringAttention: [
        'Study desk facing South causes mental fatigue; recommended facing North or East.',
        'Water purifier located too close to the cooking hob causing fire-water element clash.',
      ],
      zoneRecords: [
        VastuZoneRecord(
          zone: 'North (Kuber)',
          element: 'Water',
          currentCondition: 'Living Room Foyer with indoor planter',
          assessment: 'Auspicious financial flow & wealth accumulation',
          recommendedAction: 'Place brass vessel with fresh water and green plants',
          priority: 'Low',
        ),
        VastuZoneRecord(
          zone: 'North-East (Ishanya)',
          element: 'Water / Ether',
          currentCondition: 'Puja Alcove & clear ventilation',
          assessment: 'Optimal spiritual clarity & high energy vibration',
          recommendedAction: 'Keep clutter-free, use light yellow or white lighting',
          priority: 'Low',
        ),
        VastuZoneRecord(
          zone: 'South-East (Agneya)',
          element: 'Fire',
          currentCondition: 'Modular Kitchen cooking counter',
          assessment: 'Excellent spatial placement for digestion & vigor',
          recommendedAction: 'Ensure chef faces East while preparing meals',
          priority: 'Medium',
        ),
        VastuZoneRecord(
          zone: 'South-West (Nairutya)',
          element: 'Earth',
          currentCondition: 'Master Bedroom suite',
          assessment: 'High stability, grounding and decision-making power',
          recommendedAction: 'Headboard should touch South or West wall firmly',
          priority: 'Medium',
        ),
      ],
      colorRecommendations: [
        VastuColorRecommendation(
          color: 'Warm Off-White & Soft Gold',
          suggestedRoom: 'North-East Puja & Living Room',
          reason: 'Enhances cosmic positivity and mental peace without obstructing light.',
        ),
        VastuColorRecommendation(
          color: 'Earthy Terracotta & Almond',
          suggestedRoom: 'South-West Master Bedroom',
          reason: 'Bolsters the Earth element, promoting deep restful sleep and stability.',
        ),
        VastuColorRecommendation(
          color: 'Pistachio Green & Pale Peach',
          suggestedRoom: 'South-East Kitchen Accent Wall',
          reason: 'Harmonizes fire energy with fresh organic growth vibrations.',
        ),
      ],
      furniturePlacements: [
        VastuFurniturePlacement(
          furniture: 'Master Bed',
          recommendedDirection: 'South-West zone',
          placement: 'Headboard against South wall, sleeping head pointing South',
          notes: 'Avoid mirrors reflecting the bed while sleeping.',
        ),
        VastuFurniturePlacement(
          furniture: 'Study / Work Desk',
          recommendedDirection: 'North or East zone',
          placement: 'Seated person faces East towards morning light',
          notes: 'Keep open space ahead of the desk for mental clarity.',
        ),
      ],
      remedies: [
        VastuRemedy(
          issue: 'Mirror facing toilet door in bedroom corridor',
          recommendedRemedy: 'Apply frosted decorative film or reposition mirror to North wall',
          priority: 'High',
          implementationNote: 'Non-demolition instant solution requiring zero structural rework.',
        ),
        VastuRemedy(
          issue: 'Overhead beam running directly across dining table',
          recommendedRemedy: 'Conceal beam with false ceiling cove or hang crystal lotus',
          priority: 'Medium',
          implementationNote: 'Relieves subconscious pressure and promotes harmonious meals.',
        ),
      ],
    ),
  ];

  static final List<AiBudgetEstimateEntity> mockBudgetEstimates = [
    AiBudgetEstimateEntity(
      id: 'EST-401',
      title: 'Full Height Sliding Wardrobe (10x8)',
      projectName: 'DLF Phase 5',
      room: 'Master Bedroom',
      furnitureType: 'Sliding Wardrobe',
      width: 10.0,
      height: 8.0,
      depth: 2.0,
      unit: 'Sq.Ft.',
      coreMaterial: 'BWP Marine Grade Plywood (IS:710)',
      thickness: '18mm carcass, 12mm backer, 25mm shelves',
      finish: '1mm Anti-Fingerprint Matte Laminate + Acrylic Door Panels',
      hardware: 'Hafele Slido Classic 50VF Soft-Close System',
      budgetTier: 'Premium Tier',
      includeInstallation: true,
      includeDelivery: true,
      includeLabour: true,
      includeGst: true,
      materialCost: 72000.0,
      labourCost: 28000.0,
      hardwareCost: 18500.0,
      finishCost: 14500.0,
      installationCost: 7000.0,
      subtotal: 140000.0,
      gstAmount: 25200.0,
      totalEstimate: 165200.0,
      createdAt: DateTime(2026, 9, 9, 10, 0),
      boqItems: [
        AiBudgetBoqItem(
          item: 'Carcase Fabrication',
          specification: 'CenturyPly Club Prime BWP 18mm with 0.8mm internal off-white liner',
          quantity: 80.0,
          unit: 'Sq.Ft.',
          estimatedRate: 900.0,
          estimatedAmount: 72000.0,
        ),
        AiBudgetBoqItem(
          item: 'Sliding Door Mechanism',
          specification: 'Hafele Top-Hung 2-Door System with Synchro Soft Dampers',
          quantity: 1.0,
          unit: 'Set',
          estimatedRate: 18500.0,
          estimatedAmount: 18500.0,
        ),
        AiBudgetBoqItem(
          item: 'External Finish',
          specification: 'Greenlam Anti-Fingerprint Laminate with PVC edgebanding 2mm',
          quantity: 80.0,
          unit: 'Sq.Ft.',
          estimatedRate: 181.25,
          estimatedAmount: 14500.0,
        ),
      ],
      recommendedBrands: [
        RecommendedBrandItem(
          brand: 'CenturyPly',
          materialName: 'Club Prime BWP 710 Plywood',
          qualityTier: 'Tier 1 Certified Marine',
          priceRange: '₹105 - ₹125 / Sq.Ft.',
          vendorName: 'Greenply Century Hub Okhla',
          vendorRating: 4.9,
          warranty: '30-Year Borer & Fungus Warranty',
        ),
        RecommendedBrandItem(
          brand: 'Hafele India',
          materialName: 'Slido Classic 50VF Hardware Kit',
          qualityTier: 'German Engineered Architectural Hardware',
          priceRange: '₹16,500 - ₹19,800 / Kit',
          vendorName: 'Hafele Design Studio MG Road',
          vendorRating: 4.8,
          warranty: '10-Year Mechanical Replacement Warranty',
        ),
      ],
    ),
  ];

  static final List<AiDoubtConversationEntity> mockDoubtConversations = [
    AiDoubtConversationEntity(
      id: 'CONV-301',
      title: 'Kitchen Cabinet Plywood Selection',
      projectContext: 'DLF Penthouse',
      roomContext: 'Kitchen',
      updatedAt: DateTime.now().subtract(const Duration(hours: 3)),
      totalQuestions: 2,
      creditsConsumed: 0,
      messages: [
        AiDoubtMessage(
          id: 'MSG-1',
          isUser: true,
          text: 'Which plywood is best for kitchen cabinets under the sink area to prevent water damage?',
          timestamp: DateTime.now().subtract(const Duration(hours: 3, minutes: 2)),
        ),
        AiDoubtMessage(
          id: 'MSG-2',
          isUser: false,
          text: '''For under-sink kitchen carcases, **IS:710 Marine Grade BWP (Boiling Water Proof) Plywood** or **HDHMR (High Density High Moisture Resistance)** are the industry benchmarks:

### Key Recommendations:
1. **BWP 710 Plywood (Century Club Prime / Greenply 710):**
   - Built with phenol formaldehyde synthetic resin adhesive.
   - Can withstand 72 hours of boiling water without delamination.
   - Ideal for load-bearing under-sink carcases with water purifiers and RO units.

2. **Edge-Banding & Sealing (Critical):**
   - Always insist on **2mm machine PVC edge-banding** with PUR waterproof glue.
   - Seal all plumbing pipe cutouts with silicone sealant.

3. **Avoid Commercial MR Plywood:**
   - Moisture Resistant (MR) is only interior grade and will swell when exposed to pipe drips.''',
          timestamp: DateTime.now().subtract(const Duration(hours: 3, minutes: 1)),
          sources: [
            'Bureau of Indian Standards (IS 710:2010)',
            'Homio Standard Construction Quality Guidelines v3',
          ],
          followUpChips: [
            'What is the cost difference between BWP and MR?',
            'Should I use acrylic or PU finish for kitchen shutters?',
            'How to seal plumbing pipe penetrations?',
          ],
        ),
      ],
    ),
  ];

  static final List<DesignerConsultant> designerRoster = [
    const DesignerConsultant(
      id: 'DSG-1',
      name: 'Ananya Iyer',
      title: 'Principal Luxury Architect',
      qualification: 'B.Arch (NID Ahmedabad) • CoA Registered',
      yearsExperience: 12,
      avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=500&auto=format&fit=crop&q=80',
      rating: 4.9,
      totalConsultations: 148,
      specializations: ['Luxury Contemporary', 'Vastu Shastra', 'High-Rise Penthouses'],
      consultationFee: 300.0,
      bio: 'Alumnus of NID Ahmedabad with 12+ years of experience designing luxury penthouses across Mumbai & Bengaluru.',
      availability: DesignerAvailability.online,
    ),
    const DesignerConsultant(
      id: 'DSG-2',
      name: 'Vikram Malhotra',
      title: 'Senior Interior & Modular Specialist',
      qualification: 'M.Des (CEPT University)',
      yearsExperience: 9,
      avatarUrl: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=500&auto=format&fit=crop&q=80',
      rating: 4.8,
      totalConsultations: 112,
      specializations: ['Modular Kitchens', 'Storage Engineering', 'Hafele / Blum Hardware'],
      consultationFee: 300.0,
      bio: 'Expert in European kitchen hardware and precision storage optimization.',
      availability: DesignerAvailability.online,
    ),
    const DesignerConsultant(
      id: 'DSG-3',
      name: 'Rhea Sen',
      title: 'Biophilic & Sustainable Design Lead',
      qualification: 'B.Arch (SPA Delhi) • LEED AP',
      yearsExperience: 7,
      avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=500&auto=format&fit=crop&q=80',
      rating: 4.9,
      totalConsultations: 89,
      specializations: ['Japandi Minimalist', 'Biophilic Design', 'Sustainable Timber'],
      consultationFee: 300.0,
      bio: 'Passionate about sustainable timber, breathable textures, and serene neutral homes.',
      availability: DesignerAvailability.busy,
    ),
  ];

  static final List<BookedConsultationSession> bookedSessions = [];

  static final List<DesignerProfile> mockDesigners = [
    const DesignerProfile(
      id: 'DSG-1',
      name: 'Ananya Iyer',
      avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=500&auto=format&fit=crop&q=80',
      specialization: 'Luxury Contemporary & Vastu Compliance',
      experienceYears: 12,
      rating: 4.9,
      consultationsCount: 148,
      languages: ['English', 'Hindi', 'Tamil'],
      consultationFee: 300.0,
      bio: 'Alumnus of NID Ahmedabad with 12+ years of experience designing celebrity penthouses across Mumbai & Bengaluru. Specializes in luxury marble and Vastu harmony.',
      availableSlots: ['Today 04:30 PM', 'Today 06:00 PM', 'Tomorrow 11:00 AM', 'Tomorrow 03:30 PM'],
    ),
    const DesignerProfile(
      id: 'DSG-2',
      name: 'Vikram Malhotra',
      avatarUrl: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=500&auto=format&fit=crop&q=80',
      specialization: 'Modular Kitchens & Material Engineering',
      experienceYears: 9,
      rating: 4.8,
      consultationsCount: 112,
      languages: ['English', 'Hindi', 'Punjabi'],
      consultationFee: 300.0,
      bio: 'Expert in European kitchen hardware (Hafele, Blum) and precision storage optimization. Helped 300+ homeowners save 20-30% on interior procurement.',
      availableSlots: ['Today 05:00 PM', 'Tomorrow 10:00 AM', 'Tomorrow 02:00 PM'],
    ),
    const DesignerProfile(
      id: 'DSG-3',
      name: 'Rhea Sen',
      avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=500&auto=format&fit=crop&q=80',
      specialization: 'Scandinavian, Japandi & Biophilic Design',
      experienceYears: 7,
      rating: 4.9,
      consultationsCount: 89,
      languages: ['English', 'Bengali', 'Hindi'],
      consultationFee: 300.0,
      bio: 'Passionate about sustainable timber, breathable textures, and serene neutral homes. Regular contributor to Architectural Digest India.',
      availableSlots: ['Today 06:30 PM', 'Tomorrow 12:30 PM', 'Tomorrow 04:00 PM'],
    ),
  ];

  static final List<ConsultationBookingEntity> mockConsultations = [
    ConsultationBookingEntity(
      id: 'CNS-501',
      designer: mockDesigners[0],
      clientName: 'Rahul Sharma',
      clientPhone: '+91 98765 43210',
      clientEmail: 'rahul.sharma@gmail.com',
      projectName: 'DLF Phase 5 Penthouse',
      consultationType: 'Interior Design & Vastu Review',
      scheduledDate: DateTime.now().add(const Duration(hours: 2)),
      timeSlot: 'Today 04:30 PM',
      durationMinutes: 30,
      topic: 'Living Room False Ceiling & Puja Zone Alignment',
      description: 'Need advice on concealing an overhead structural beam without lowering the ceiling height, plus puja unit placement.',
      fee: 300.0,
      platformShare: 150.0,
      designerShare: 150.0,
      meetingStatus: 'Scheduled',
      paymentStatus: 'Paid',
      meetingUrl: 'https://meet.homio.in/cns-501-room',
      attachments: ['floor_plan_dlf.pdf', 'living_room_photo.jpg'],
    ),
    ConsultationBookingEntity(
      id: 'CNS-502',
      designer: mockDesigners[1],
      clientName: 'Rahul Sharma',
      clientPhone: '+91 98765 43210',
      clientEmail: 'rahul.sharma@gmail.com',
      projectName: 'DLF Phase 5 Penthouse',
      consultationType: 'Material & Hardware Review',
      scheduledDate: DateTime.now().subtract(const Duration(days: 3)),
      timeSlot: '11:00 AM',
      durationMinutes: 30,
      topic: 'Kitchen Plywood & Hafele Fittings Review',
      description: 'Verified BWP vs HDHMR quotes and selected soft-close tandem boxes.',
      fee: 300.0,
      platformShare: 150.0,
      designerShare: 150.0,
      meetingStatus: 'Completed',
      paymentStatus: 'Paid',
      meetingUrl: 'https://meet.homio.in/cns-502-room',
      ratingGiven: 5,
      feedbackText: 'Vikram saved us ₹65,000 by catching an overpriced hardware line item in our vendor quotation!',
    ),
  ];

  static final List<AiAuditRecord> auditRecords = [
    AiAuditRecord(
      id: 'AUD-101',
      action: 'Credit Package Purchase',
      user: 'Rahul Sharma',
      entity: 'AiWallet',
      previousValue: '120 Credits',
      newValue: '695 Credits (+575 Standard Pack)',
      timestamp: DateTime.now().subtract(const Duration(hours: 1)),
      reason: 'Online Payment Gateway confirmation #RAZOR_PAY_9824',
    ),
    AiAuditRecord(
      id: 'AUD-102',
      action: 'GPU Job Credit Debit',
      user: 'Rahul Sharma',
      entity: 'AiJob-9021',
      previousValue: '695 Credits',
      newValue: '685 Credits (-10 Credits)',
      timestamp: DateTime.now().subtract(const Duration(minutes: 8)),
      reason: 'Generated 4K AI Living Room Render with preliminary BOQ',
    ),
    AiAuditRecord(
      id: 'AUD-103',
      action: 'Job Failure Credit Refund',
      user: 'Kavita Singh',
      entity: 'AiJob-9024',
      previousValue: '45 Credits',
      newValue: '55 Credits (+10 Credits Refunded)',
      timestamp: DateTime.now().subtract(const Duration(days: 1)),
      reason: 'GPU OutOfMemory tensor failure during ceiling mesh calculation',
    ),
  ];

  static final List<DoubtQueryMessage> initialDoubtChat = [
    DoubtQueryMessage(
      id: 'MSG-INIT-1',
      isFromUser: true,
      content: 'Which plywood grade is strictly specified for kitchen under-sink carcase and wet areas?',
      timestamp: DateTime.now().subtract(const Duration(hours: 4)),
      category: DoubtCategory.materialQuality,
    ),
    DoubtQueryMessage(
      id: 'MSG-INIT-2',
      isFromUser: false,
      content: 'Under-sink carcases must utilize **IS:710 Certified BWP (Boiling Water Proof)** Marine Grade Plywood bonded with unextended phenol formaldehyde resin, or **HDHMR** with 2mm PVC edge-banding.',
      timestamp: DateTime.now().subtract(const Duration(hours: 4)),
      category: DoubtCategory.materialQuality,
      actionChecklist: const [
        'Inspect genuine ISI mark with manufacturer license CML number',
        'Ensure 2mm machine PVC edge-banding with PUR glue',
      ],
      contractorTip: 'Never allow commercial MR grade plywood in under-sink areas.',
    ),
  ];
}
