import 'organization_models.dart';

class OrganizationMockData {
  // 1. The 5 Core Department Entities
  static final List<DepartmentEntity> departments = [
    const DepartmentEntity(
      id: 'DEPT-MKT',
      name: 'Marketing & Growth',
      type: DepartmentType.marketing,
      headOfDepartment: 'Meera Rao',
      headEmail: 'meera.r@homio.in',
      headPhone: '+91 98101 22334',
      headcount: 4,
      targetKpi: '350 Qualified Inbound Leads / Mo',
      monthlyBudgetPool: 850000,
      description: 'Acquisition funnels, Google/Meta paid media campaigns, CAC/CPL optimization, and social growth.',
      coreFunctions: [
        'Ad Spend & CAC Optimization',
        'Multi-Channel Content Creation',
        'Social Media & Community AI Replies',
        'Portfolio Case Study Releases',
      ],
    ),
    const DepartmentEntity(
      id: 'DEPT-SALES',
      name: 'Sales & Consultations',
      type: DepartmentType.sales,
      headOfDepartment: 'Vikram Malhotra',
      headEmail: 'vikram.m@homio.in',
      headPhone: '+91 98101 44210',
      headcount: 5,
      targetKpi: '₹85 Lakhs GMV Bookings / Mo',
      monthlyBudgetPool: 1250000,
      description: 'Lead qualification, multi-funnel velocity, face-to-face deal closing, and dynamic commission earnings.',
      coreFunctions: [
        'Autodialer Lead Triage & Qualification',
        'Site Surveys & Laser Dimension Intake',
        'Consultation Slot Scheduling',
        'Contract Closing & Deposit Collection',
      ],
    ),
    const DepartmentEntity(
      id: 'DEPT-DESIGN',
      name: 'Design & Architecture',
      type: DepartmentType.design,
      headOfDepartment: 'Ananya Roy',
      headEmail: 'ananya.r@homio.in',
      headPhone: '+91 99201 88412',
      headcount: 6,
      targetKpi: '24 Turnkey Blueprints & 3D Render Sets / Mo',
      monthlyBudgetPool: 1600000,
      description: '2D drafting, 3D BIM modelling, AI moodboard generation, material palettes, and client revisions.',
      coreFunctions: [
        '3D Photorealistic V-Ray & Lumion Renders',
        'Detailed Working CAD Drawings',
        'Weekly Project Update Calls',
        'Laser Precision Site Measurement',
      ],
    ),
    const DepartmentEntity(
      id: 'DEPT-EXEC',
      name: 'Site Execution & Turnkey Civil',
      type: DepartmentType.execution,
      headOfDepartment: 'Rajesh Verma',
      headEmail: 'rajesh.v@homio.in',
      headPhone: '+91 98112 33455',
      headcount: 7,
      targetKpi: '98.5% On-Time Milestone Turnarounds',
      monthlyBudgetPool: 2200000,
      description: 'On-site turnkey supervision, subcontractor labour muster rolls, BOQ installations, and daily videos.',
      coreFunctions: [
        'Daily Site Video Log Capture',
        'Material Requisition Indents (RFQ)',
        'Labour Contractor Muster Roll',
        'Weekly Milestone Fee Collection',
      ],
    ),
    const DepartmentEntity(
      id: 'DEPT-SERVICE',
      name: 'After-Sales & Warranty Service',
      type: DepartmentType.afterSales,
      headOfDepartment: 'Priya Nambiar',
      headEmail: 'priya.n@homio.in',
      headPhone: '+91 98331 44550',
      headcount: 3,
      targetKpi: '< 4 Hour Mean Emergency Response Time',
      monthlyBudgetPool: 450000,
      description: 'Post-handover snag resolution, 10-year structural warranty claims, quarterly CSAT surveys & referrals.',
      coreFunctions: [
        'Emergency Snag Ticket SLA Dispatch',
        '10-Yr Structural Warranty Governance',
        'Customer Satisfaction Surveys (CSAT)',
        '₹10,000 Referral Loyalty Rewards',
      ],
    ),
  ];

  // 2. The 15 Role Definitions Matching PRD Section 6.2
  static final List<RoleDefinition> roles = [
    // Marketing
    const RoleDefinition(
      id: 'ROLE-MKT-01',
      departmentType: DepartmentType.marketing,
      roleTitle: 'Digital Marketer',
      hierarchyLevel: HierarchyLevel.manager,
      reportingToRole: 'Marketing Head',
      responsibilities: [
        'Manage Google & Meta Ads budget allocations',
        'Audit CPL & CAC weekly cohorts',
        'Optimize lead form conversion rates',
      ],
      minSalary: 60000,
      maxSalary: 95000,
      defaultScope: AccessScope.organizationWide,
      activeMembersCount: 1,
    ),
    const RoleDefinition(
      id: 'ROLE-MKT-02',
      departmentType: DepartmentType.marketing,
      roleTitle: 'Content Manager',
      hierarchyLevel: HierarchyLevel.specialist,
      reportingToRole: 'Digital Marketer',
      responsibilities: [
        'Social media calendar scheduling',
        'Case study and brochure copywriting',
        'Client testimonial video scripts',
      ],
      minSalary: 45000,
      maxSalary: 65000,
      defaultScope: AccessScope.organizationWide,
      activeMembersCount: 1,
    ),
    const RoleDefinition(
      id: 'ROLE-MKT-03',
      departmentType: DepartmentType.marketing,
      roleTitle: 'Editor',
      hierarchyLevel: HierarchyLevel.specialist,
      reportingToRole: 'Content Manager',
      responsibilities: [
        'Post-production of site progress timelapses',
        'Color grading of luxury home walk-throughs',
        'Reels & YouTube Shorts formatting',
      ],
      minSalary: 40000,
      maxSalary: 60000,
      defaultScope: AccessScope.organizationWide,
      activeMembersCount: 1,
    ),
    const RoleDefinition(
      id: 'ROLE-MKT-04',
      departmentType: DepartmentType.marketing,
      roleTitle: 'Videographer',
      hierarchyLevel: HierarchyLevel.specialist,
      reportingToRole: 'Content Manager',
      responsibilities: [
        'On-site 4K camera & gimbal recording',
        'Milestone completion drone shots',
        'Client handover interview recordings',
      ],
      minSalary: 42000,
      maxSalary: 58000,
      defaultScope: AccessScope.organizationWide,
      activeMembersCount: 1,
    ),

    // Sales
    const RoleDefinition(
      id: 'ROLE-SALES-01',
      departmentType: DepartmentType.sales,
      roleTitle: 'Sales Head',
      hierarchyLevel: HierarchyLevel.lead,
      reportingToRole: 'Super Admin',
      responsibilities: [
        'Monthly quota allocation and deal closing approvals',
        'Sales pipeline acceleration & team governance',
        'Discounts & special commercial pricing sign-offs',
      ],
      minSalary: 110000,
      maxSalary: 160000,
      defaultScope: AccessScope.organizationWide,
      activeMembersCount: 1,
    ),
    const RoleDefinition(
      id: 'ROLE-SALES-02',
      departmentType: DepartmentType.sales,
      roleTitle: 'Deal Closer',
      hierarchyLevel: HierarchyLevel.manager,
      reportingToRole: 'Sales Head',
      responsibilities: [
        'In-person & video consultation pitch presentations',
        'Quotation review & scope customization',
        'Advance booking deposit collection',
      ],
      minSalary: 70000,
      maxSalary: 110000,
      defaultScope: AccessScope.organizationWide,
      activeMembersCount: 1,
    ),
    const RoleDefinition(
      id: 'ROLE-SALES-03',
      departmentType: DepartmentType.sales,
      roleTitle: 'Meeting Organiser',
      hierarchyLevel: HierarchyLevel.specialist,
      reportingToRole: 'Sales Head',
      responsibilities: [
        'Calendar slot orchestration between clients & PMs',
        'Studio experience center walk-in scheduling',
        'Meeting reminder automation monitoring',
      ],
      minSalary: 35000,
      maxSalary: 50000,
      defaultScope: AccessScope.organizationWide,
      activeMembersCount: 1,
    ),
    const RoleDefinition(
      id: 'ROLE-SALES-04',
      departmentType: DepartmentType.sales,
      roleTitle: 'Junior Telecaller',
      hierarchyLevel: HierarchyLevel.junior,
      reportingToRole: 'Meeting Organiser',
      responsibilities: [
        'Autodialer high-frequency lead qualification',
        'Intake questionnaire documentation',
        'Follow-up reminders & drip campaign monitoring',
      ],
      minSalary: 25000,
      maxSalary: 35000,
      defaultScope: AccessScope.myLeadsTasks, // STRICT ISOLATION
      activeMembersCount: 2,
    ),

    // Design
    const RoleDefinition(
      id: 'ROLE-DES-01',
      departmentType: DepartmentType.design,
      roleTitle: 'Project Manager (PM)',
      hierarchyLevel: HierarchyLevel.lead,
      reportingToRole: 'Super Admin',
      responsibilities: [
        'Client account leadership and design scope governance',
        'Weekly client video calls & milestone approvals',
        'Allocating design sprint tasks to 3D and 2D artists',
      ],
      minSalary: 90000,
      maxSalary: 130000,
      defaultScope: AccessScope.organizationWide,
      activeMembersCount: 2,
    ),
    const RoleDefinition(
      id: 'ROLE-DES-02',
      departmentType: DepartmentType.design,
      roleTitle: '3D Artist & Renderer',
      hierarchyLevel: HierarchyLevel.specialist,
      reportingToRole: 'Project Manager (PM)',
      responsibilities: [
        '3ds Max / SketchUp modelling with V-Ray textures',
        'Photorealistic lighting and material finishes',
        'Client revision iterations within 24h SLA',
      ],
      minSalary: 55000,
      maxSalary: 80000,
      defaultScope: AccessScope.myLeadsTasks,
      activeMembersCount: 2,
    ),
    const RoleDefinition(
      id: 'ROLE-DES-03',
      departmentType: DepartmentType.design,
      roleTitle: 'Junior Designer',
      hierarchyLevel: HierarchyLevel.junior,
      reportingToRole: 'Project Manager (PM)',
      responsibilities: [
        'AutoCAD 2D working drawings & floor layouts',
        'Electrical, plumbing & HVAC schematic drawings',
        'Initial client mood board curation',
      ],
      minSalary: 30000,
      maxSalary: 45000,
      defaultScope: AccessScope.myLeadsTasks, // STRICT ISOLATION
      activeMembersCount: 1,
    ),
    const RoleDefinition(
      id: 'ROLE-DES-04',
      departmentType: DepartmentType.design,
      roleTitle: 'Site Measurement Coordinator',
      hierarchyLevel: HierarchyLevel.junior,
      reportingToRole: 'Project Manager (PM)',
      responsibilities: [
        'Physical on-site laser distance surveying',
        'Beam, column, and ceiling offset documentation',
        'Uploading CAD measurement point clouds',
      ],
      minSalary: 32000,
      maxSalary: 45000,
      defaultScope: AccessScope.myLeadsTasks, // STRICT ISOLATION
      activeMembersCount: 1,
    ),

    // Execution
    const RoleDefinition(
      id: 'ROLE-EXEC-01',
      departmentType: DepartmentType.execution,
      roleTitle: 'Site Supervisor',
      hierarchyLevel: HierarchyLevel.manager,
      reportingToRole: 'Super Admin',
      responsibilities: [
        'Daily on-site contractor & labour muster deployment',
        'BOQ material quality inspection & sign-off',
        'Collecting weekly stage milestone payments',
      ],
      minSalary: 50000,
      maxSalary: 75000,
      defaultScope: AccessScope.myLeadsTasks, // STRICT ISOLATION
      activeMembersCount: 4,
    ),
    const RoleDefinition(
      id: 'ROLE-EXEC-02',
      departmentType: DepartmentType.execution,
      roleTitle: 'Junior Coordinator',
      hierarchyLevel: HierarchyLevel.junior,
      reportingToRole: 'Site Supervisor',
      responsibilities: [
        'Raw material dispatch tracking & gate passes',
        'Recording daily progress video walkthroughs',
        'Labour attendance biometric / selfie checks',
      ],
      minSalary: 28000,
      maxSalary: 38000,
      defaultScope: AccessScope.myLeadsTasks, // STRICT ISOLATION
      activeMembersCount: 3,
    ),

    // After-Sales Service
    const RoleDefinition(
      id: 'ROLE-SVC-01',
      departmentType: DepartmentType.afterSales,
      roleTitle: 'Service Manager',
      hierarchyLevel: HierarchyLevel.manager,
      reportingToRole: 'Super Admin',
      responsibilities: [
        'Post-handover snag ticket triage & technician dispatch',
        '10-Year Structural warranty claim assessments',
        'Emergency response SLA compliance governance',
      ],
      minSalary: 65000,
      maxSalary: 90000,
      defaultScope: AccessScope.organizationWide,
      activeMembersCount: 1,
    ),
    const RoleDefinition(
      id: 'ROLE-SVC-02',
      departmentType: DepartmentType.afterSales,
      roleTitle: 'Service Telecaller',
      hierarchyLevel: HierarchyLevel.junior,
      reportingToRole: 'Service Manager',
      responsibilities: [
        'Scheduled 30-60-90 day post-handover CSAT calls',
        'WhatsApp Google Review link distribution',
        'Referral loyalty reward lead registration',
      ],
      minSalary: 26000,
      maxSalary: 36000,
      defaultScope: AccessScope.myLeadsTasks, // STRICT ISOLATION
      activeMembersCount: 2,
    ),
  ];

  // 3. Module Permissions Matrix
  static final List<ModulePermission> permissions = [
    const ModulePermission(
      id: 'PERM-01',
      moduleCode: 'MOD-SALES',
      moduleName: 'Sales CRM & Lead Funnel',
      description: 'Lead generation, autodialer intake, appointments, and deal closing.',
      canView: true,
      canCreate: true,
      canEdit: true,
      canDelete: false,
      canExport: true,
      canApprove: true,
      isFieldIsolated: true, // Junior telecallers isolated to My Leads Only
    ),
    const ModulePermission(
      id: 'PERM-02',
      moduleCode: 'MOD-QUOTATION',
      moduleName: 'Quotation & Estimation Engine',
      description: 'Room grouping, dynamic margins, discount urgency, and PDF quotes.',
      canView: true,
      canCreate: true,
      canEdit: true,
      canDelete: false,
      canExport: true,
      canApprove: true,
      isFieldIsolated: true,
    ),
    const ModulePermission(
      id: 'PERM-03',
      moduleCode: 'MOD-DESIGN',
      moduleName: 'Design Deliverable DAM & Reviews',
      description: '3D renders, CAD floorplans, client approval loops, and Google Drive links.',
      canView: true,
      canCreate: true,
      canEdit: true,
      canDelete: false,
      canExport: true,
      canApprove: true,
      isFieldIsolated: true,
    ),
    const ModulePermission(
      id: 'PERM-04',
      moduleCode: 'MOD-EXEC',
      moduleName: 'Site Execution & Turnkey Civil',
      description: 'Gantt WBS, site progress videos, trade contractor deployment, and BOQs.',
      canView: true,
      canCreate: true,
      canEdit: true,
      canDelete: false,
      canExport: true,
      canApprove: true,
      isFieldIsolated: true,
    ),
    const ModulePermission(
      id: 'PERM-05',
      moduleCode: 'MOD-HRMS',
      moduleName: 'HRMS, Geofence & Payroll',
      description: 'Directory, GPS boundary punches, mileage reimbursement, 2X leave penalty.',
      canView: true,
      canCreate: true,
      canEdit: true,
      canDelete: false,
      canExport: true,
      canApprove: true,
      isFieldIsolated: false,
    ),
    const ModulePermission(
      id: 'PERM-06',
      moduleCode: 'MOD-AFTER-SALES',
      moduleName: 'After-Sales Service & Warranty',
      description: 'Snag tracking, 10-yr structural warranty, technician dispatch, CSAT surveys.',
      canView: true,
      canCreate: true,
      canEdit: true,
      canDelete: false,
      canExport: true,
      canApprove: true,
      isFieldIsolated: true,
    ),
  ];
}
