import 'organization_models.dart';

class OrganizationMockData {
  // ---------------------------------------------------------------------------
  // 1. Departments (8 Core Departments with Parent-Child Hierarchy)
  // ---------------------------------------------------------------------------
  static final List<OrganizationDepartment> departments = [
    OrganizationDepartment(
      id: 'DEPT-EXEC',
      code: 'EXEC-001',
      name: 'Turnkey Site Execution',
      type: DepartmentType.execution,
      parentDepartmentId: 'DEPT-OPS',
      parentDepartmentName: 'Operations & Supply Chain',
      headOfDepartment: 'Rajesh Verma',
      headEmail: 'rajesh.v@homio.in',
      headPhone: '+91 98112 33455',
      deputyHead: 'Amit Sharma',
      description: 'On-site turnkey supervision, subcontractor labour muster rolls, BOQ installations, and daily videos.',
      teamCount: 4,
      employeeCount: 38,
      status: OrgStatus.active,
      email: 'execution@homio.in',
      phone: '+91 80 4433 2211',
      locationBranch: 'Bangalore Central Hub',
      costCenter: 'CC-EXEC-101',
      monthlyBudgetPool: 2450000,
      allowTeamCreation: true,
      defaultAccessScopeId: 'SCOPE-TEAM-WIDE',
      coreFunctions: [
        'Daily Site Video Log Capture',
        'Material Requisition Indents (RFQ)',
        'Labour Contractor Muster Roll',
        'Weekly Milestone Fee Collection',
      ],
      createdDate: DateTime(2025, 1, 15),
      lastUpdated: DateTime(2026, 8, 20),
    ),
    OrganizationDepartment(
      id: 'DEPT-OPS',
      code: 'OPS-001',
      name: 'Operations & Supply Chain',
      type: DepartmentType.operations,
      parentDepartmentId: null,
      headOfDepartment: 'Sunil Nair',
      headEmail: 'sunil.n@homio.in',
      headPhone: '+91 98450 11223',
      deputyHead: 'Kavita Menon',
      description: 'Central operational backbone, factory fabrication logistics, and material procurement.',
      teamCount: 3,
      employeeCount: 24,
      status: OrgStatus.active,
      email: 'operations@homio.in',
      phone: '+91 80 4433 2200',
      locationBranch: 'Bangalore Central Hub',
      costCenter: 'CC-OPS-100',
      monthlyBudgetPool: 3200000,
      allowTeamCreation: true,
      defaultAccessScopeId: 'SCOPE-DEPT-WIDE',
      coreFunctions: [
        'Vendor Procurement & Rate Cards',
        'Factory Modular Fabrication',
        'Warehouse Inventory Fulfillment',
        'Fleet Logistics & Deliveries',
      ],
      createdDate: DateTime(2025, 1, 10),
      lastUpdated: DateTime(2026, 8, 15),
    ),
    OrganizationDepartment(
      id: 'DEPT-SALES',
      code: 'SALES-001',
      name: 'Sales & Consultations',
      type: DepartmentType.sales,
      parentDepartmentId: null,
      headOfDepartment: 'Vikram Malhotra',
      headEmail: 'vikram.m@homio.in',
      headPhone: '+91 98101 44210',
      deputyHead: 'Neha Sen',
      description: 'Lead qualification, multi-funnel velocity, face-to-face deal closing, and dynamic commission earnings.',
      teamCount: 3,
      employeeCount: 22,
      status: OrgStatus.active,
      email: 'sales@homio.in',
      phone: '+91 80 4433 3311',
      locationBranch: 'Indiranagar Experience Center',
      costCenter: 'CC-SALES-201',
      monthlyBudgetPool: 1850000,
      allowTeamCreation: true,
      defaultAccessScopeId: 'SCOPE-MY-LEADS',
      coreFunctions: [
        'Autodialer Lead Triage & Qualification',
        'Site Surveys & Laser Dimension Intake',
        'Consultation Slot Scheduling',
        'Contract Closing & Deposit Collection',
      ],
      createdDate: DateTime(2025, 1, 12),
      lastUpdated: DateTime(2026, 9, 1),
    ),
    OrganizationDepartment(
      id: 'DEPT-DESIGN',
      code: 'DES-001',
      name: 'Design & Architecture',
      type: DepartmentType.design,
      parentDepartmentId: null,
      headOfDepartment: 'Ananya Roy',
      headEmail: 'ananya.r@homio.in',
      headPhone: '+91 99201 88412',
      deputyHead: 'Rohan Gupta',
      description: '2D drafting, 3D BIM modelling, AI moodboard generation, material palettes, and client revisions.',
      teamCount: 3,
      employeeCount: 26,
      status: OrgStatus.active,
      email: 'design@homio.in',
      phone: '+91 80 4433 4411',
      locationBranch: 'Whitefield Design Studio',
      costCenter: 'CC-DES-301',
      monthlyBudgetPool: 2100000,
      allowTeamCreation: true,
      defaultAccessScopeId: 'SCOPE-TEAM-WIDE',
      coreFunctions: [
        '3D Photorealistic V-Ray & Lumion Renders',
        'Detailed Working CAD Drawings',
        'Weekly Project Update Calls',
        'Laser Precision Site Measurement',
      ],
      createdDate: DateTime(2025, 1, 14),
      lastUpdated: DateTime(2026, 8, 28),
    ),
    OrganizationDepartment(
      id: 'DEPT-MKT',
      code: 'MKT-001',
      name: 'Marketing & Growth',
      type: DepartmentType.marketing,
      parentDepartmentId: null,
      headOfDepartment: 'Meera Rao',
      headEmail: 'meera.r@homio.in',
      headPhone: '+91 98101 22334',
      deputyHead: 'Arjun Das',
      description: 'Acquisition funnels, Google/Meta paid media campaigns, CAC/CPL optimization, and social growth.',
      teamCount: 2,
      employeeCount: 14,
      status: OrgStatus.active,
      email: 'marketing@homio.in',
      phone: '+91 80 4433 1111',
      locationBranch: 'Bangalore Central Hub',
      costCenter: 'CC-MKT-401',
      monthlyBudgetPool: 1450000,
      allowTeamCreation: true,
      defaultAccessScopeId: 'SCOPE-ORG-WIDE',
      coreFunctions: [
        'Ad Spend & CAC Optimization',
        'Multi-Channel Content Creation',
        'Social Media & Community AI Replies',
        'Portfolio Case Study Releases',
      ],
      createdDate: DateTime(2025, 1, 10),
      lastUpdated: DateTime(2026, 8, 12),
    ),
    OrganizationDepartment(
      id: 'DEPT-SERVICE',
      code: 'SVC-001',
      name: 'After-Sales & Warranty Service',
      type: DepartmentType.afterSales,
      parentDepartmentId: 'DEPT-OPS',
      parentDepartmentName: 'Operations & Supply Chain',
      headOfDepartment: 'Priya Nambiar',
      headEmail: 'priya.n@homio.in',
      headPhone: '+91 98331 44550',
      deputyHead: 'Siddharth Pillai',
      description: 'Post-handover snag resolution, 10-year structural warranty claims, quarterly CSAT surveys & referrals.',
      teamCount: 2,
      employeeCount: 16,
      status: OrgStatus.active,
      email: 'service@homio.in',
      phone: '+91 80 4433 5511',
      locationBranch: 'Bangalore Central Hub',
      costCenter: 'CC-SVC-501',
      monthlyBudgetPool: 950000,
      allowTeamCreation: true,
      defaultAccessScopeId: 'SCOPE-MY-LEADS',
      coreFunctions: [
        'Emergency Snag Ticket SLA Dispatch',
        '10-Yr Structural Warranty Governance',
        'Customer Satisfaction Surveys (CSAT)',
        'Referral Loyalty Rewards Program',
      ],
      createdDate: DateTime(2025, 2, 1),
      lastUpdated: DateTime(2026, 8, 18),
    ),
    OrganizationDepartment(
      id: 'DEPT-FIN',
      code: 'FIN-001',
      name: 'Finance & Accounts',
      type: DepartmentType.finance,
      parentDepartmentId: null,
      headOfDepartment: 'Deepak Joshi',
      headEmail: 'deepak.j@homio.in',
      headPhone: '+91 98220 99881',
      deputyHead: 'Ritu Aggarwal',
      description: 'P&L reporting, client receivables collection, vendor billing reconciliations, and tax compliance.',
      teamCount: 2,
      employeeCount: 12,
      status: OrgStatus.active,
      email: 'finance@homio.in',
      phone: '+91 80 4433 6611',
      locationBranch: 'Bangalore Central Hub',
      costCenter: 'CC-FIN-601',
      monthlyBudgetPool: 1200000,
      allowTeamCreation: false,
      defaultAccessScopeId: 'SCOPE-DEPT-WIDE',
      coreFunctions: [
        'Client Billing & Milestone Invoices',
        'Vendor Payables & Tax Clearance',
        'Weekly P&L Margin Reconciliations',
        'Treasury & Working Capital Forecast',
      ],
      createdDate: DateTime(2025, 1, 5),
      lastUpdated: DateTime(2026, 9, 2),
    ),
    OrganizationDepartment(
      id: 'DEPT-HR',
      code: 'HR-001',
      name: 'Human Resources',
      type: DepartmentType.hr,
      parentDepartmentId: null,
      headOfDepartment: 'Shalini Kapoor',
      headEmail: 'shalini.k@homio.in',
      headPhone: '+91 98110 55443',
      deputyHead: 'Tanvi Shah',
      description: 'Talent recruitment, employee relations, organizational culture, policy compliance, and org design.',
      teamCount: 2,
      employeeCount: 10,
      status: OrgStatus.active,
      email: 'hr@homio.in',
      phone: '+91 80 4433 7711',
      locationBranch: 'Bangalore Central Hub',
      costCenter: 'CC-HR-701',
      monthlyBudgetPool: 850000,
      allowTeamCreation: false,
      defaultAccessScopeId: 'SCOPE-ORG-WIDE',
      coreFunctions: [
        'Leadership Talent Acquisition',
        'Organizational Role Grading',
        'Performance Management Framework',
        'Compliance & Workplace Culture',
      ],
      createdDate: DateTime(2025, 1, 5),
      lastUpdated: DateTime(2026, 8, 30),
    ),
  ];

  // ---------------------------------------------------------------------------
  // 2. Teams (18 Operational Squads)
  // ---------------------------------------------------------------------------
  static final List<OrganizationTeam> teams = [
    // Sales Teams
    OrganizationTeam(
      id: 'TEAM-SALES-ALPHA',
      code: 'TM-SALES-01',
      name: 'Sales Squad Alpha (North Bangalore)',
      departmentId: 'DEPT-SALES',
      departmentName: 'Sales & Consultations',
      teamLead: 'Rohan Mehra',
      teamLeadEmail: 'rohan.m@homio.in',
      manager: 'Vikram Malhotra',
      managerEmail: 'vikram.m@homio.in',
      memberCount: 8,
      status: OrgStatus.active,
      branch: 'Indiranagar Hub',
      teamType: 'Regional Inbound Closers',
      maxTeamSize: 12,
      defaultAccessScopeId: 'SCOPE-TEAM-WIDE',
      description: 'Premium residential villa and luxury penthouse inbound consultation closures.',
      createdDate: DateTime(2025, 2, 1),
      lastUpdated: DateTime(2026, 8, 15),
    ),
    OrganizationTeam(
      id: 'TEAM-SALES-BETA',
      code: 'TM-SALES-02',
      name: 'Sales Squad Beta (South Bangalore)',
      departmentId: 'DEPT-SALES',
      departmentName: 'Sales & Consultations',
      teamLead: 'Kunal Verma',
      teamLeadEmail: 'kunal.v@homio.in',
      manager: 'Vikram Malhotra',
      managerEmail: 'vikram.m@homio.in',
      memberCount: 7,
      status: OrgStatus.active,
      branch: 'Koramangala Hub',
      teamType: 'High-Velocity Closers',
      maxTeamSize: 10,
      defaultAccessScopeId: 'SCOPE-TEAM-WIDE',
      description: 'Apartment modular interior packaging and fast 14-day booking cycles.',
      createdDate: DateTime(2025, 2, 10),
      lastUpdated: DateTime(2026, 8, 19),
    ),
    OrganizationTeam(
      id: 'TEAM-SALES-TELE',
      code: 'TM-SALES-03',
      name: 'Inbound SDR & Telecalling Pool',
      departmentId: 'DEPT-SALES',
      departmentName: 'Sales & Consultations',
      teamLead: 'Sneha Patel',
      teamLeadEmail: 'sneha.p@homio.in',
      manager: 'Vikram Malhotra',
      managerEmail: 'vikram.m@homio.in',
      memberCount: 7,
      status: OrgStatus.active,
      branch: 'Bangalore Central Hub',
      teamType: 'Lead Triage & Qualification',
      maxTeamSize: 15,
      defaultAccessScopeId: 'SCOPE-MY-LEADS',
      description: 'First 5-minute contact SLA, WhatsApp qualification, and site visit scheduling.',
      createdDate: DateTime(2025, 2, 15),
      lastUpdated: DateTime(2026, 8, 22),
    ),

    // Design Teams
    OrganizationTeam(
      id: 'TEAM-DES-CONCEPT',
      code: 'TM-DES-01',
      name: 'Concept Architecture & 3D Visualizer',
      departmentId: 'DEPT-DESIGN',
      departmentName: 'Design & Architecture',
      teamLead: 'Tarun Saxena',
      teamLeadEmail: 'tarun.s@homio.in',
      manager: 'Ananya Roy',
      managerEmail: 'ananya.r@homio.in',
      memberCount: 10,
      status: OrgStatus.active,
      branch: 'Whitefield Design Studio',
      teamType: '3D Render & VR Walkthroughs',
      maxTeamSize: 15,
      defaultAccessScopeId: 'SCOPE-TEAM-WIDE',
      description: 'Photorealistic Lumion/V-Ray renderings, moodboards, and VR walkthrough generation.',
      createdDate: DateTime(2025, 2, 5),
      lastUpdated: DateTime(2026, 8, 25),
    ),
    OrganizationTeam(
      id: 'TEAM-DES-CAD',
      code: 'TM-DES-02',
      name: 'Working Drawings & CAD Drafting',
      departmentId: 'DEPT-DESIGN',
      departmentName: 'Design & Architecture',
      teamLead: 'Pooja Hegde',
      teamLeadEmail: 'pooja.h@homio.in',
      manager: 'Ananya Roy',
      managerEmail: 'ananya.r@homio.in',
      memberCount: 9,
      status: OrgStatus.active,
      branch: 'Whitefield Design Studio',
      teamType: 'GFC CAD Production',
      maxTeamSize: 12,
      defaultAccessScopeId: 'SCOPE-TEAM-WIDE',
      description: 'Good-For-Construction drawings, electrical layouts, plumbing risers, and joinery details.',
      createdDate: DateTime(2025, 2, 12),
      lastUpdated: DateTime(2026, 8, 20),
    ),
    OrganizationTeam(
      id: 'TEAM-DES-ESTIM',
      code: 'TM-DES-03',
      name: 'BOQ Estimation & Material Specification',
      departmentId: 'DEPT-DESIGN',
      departmentName: 'Design & Architecture',
      teamLead: 'Karthik Raja',
      teamLeadEmail: 'karthik.r@homio.in',
      manager: 'Ananya Roy',
      managerEmail: 'ananya.r@homio.in',
      memberCount: 7,
      status: OrgStatus.active,
      branch: 'Bangalore Central Hub',
      teamType: 'Rate Analysis & Costing',
      maxTeamSize: 10,
      defaultAccessScopeId: 'SCOPE-TEAM-WIDE',
      description: 'Detailed bill of quantities, laminate/veneer codes, and hardware brand selections.',
      createdDate: DateTime(2025, 2, 18),
      lastUpdated: DateTime(2026, 8, 28),
    ),

    // Execution Teams
    OrganizationTeam(
      id: 'TEAM-EXEC-NORTH',
      code: 'TM-EXEC-01',
      name: 'Site Turnkey Squad - North Hub',
      departmentId: 'DEPT-EXEC',
      departmentName: 'Turnkey Site Execution',
      teamLead: 'Manoj Kumar',
      teamLeadEmail: 'manoj.k@homio.in',
      manager: 'Rajesh Verma',
      managerEmail: 'rajesh.v@homio.in',
      memberCount: 12,
      status: OrgStatus.active,
      branch: 'Hebbal Site Office',
      teamType: 'Turnkey Site Management',
      maxTeamSize: 18,
      defaultAccessScopeId: 'SCOPE-TEAM-WIDE',
      description: 'Turnkey civil and modular installations covering North Bangalore & Airport Road.',
      createdDate: DateTime(2025, 1, 20),
      lastUpdated: DateTime(2026, 8, 29),
    ),
    OrganizationTeam(
      id: 'TEAM-EXEC-EAST',
      code: 'TM-EXEC-02',
      name: 'Site Turnkey Squad - East Hub',
      departmentId: 'DEPT-EXEC',
      departmentName: 'Turnkey Site Execution',
      teamLead: 'Suresh Raina',
      teamLeadEmail: 'suresh.r@homio.in',
      manager: 'Rajesh Verma',
      managerEmail: 'rajesh.v@homio.in',
      memberCount: 14,
      status: OrgStatus.active,
      branch: 'Whitefield Site Office',
      teamType: 'Turnkey Site Management',
      maxTeamSize: 20,
      defaultAccessScopeId: 'SCOPE-TEAM-WIDE',
      description: 'Turnkey interior execution for Sarjapur, Marathahalli, and Whitefield tech corridors.',
      createdDate: DateTime(2025, 1, 22),
      lastUpdated: DateTime(2026, 8, 31),
    ),
    OrganizationTeam(
      id: 'TEAM-EXEC-QA',
      code: 'TM-EXEC-03',
      name: 'Quality Audit & Snag Prevention',
      departmentId: 'DEPT-EXEC',
      departmentName: 'Turnkey Site Execution',
      teamLead: 'Bipin Rawat',
      teamLeadEmail: 'bipin.r@homio.in',
      manager: 'Rajesh Verma',
      managerEmail: 'rajesh.v@homio.in',
      memberCount: 6,
      status: OrgStatus.active,
      branch: 'Bangalore Central Hub',
      teamType: 'Quality Assurance',
      maxTeamSize: 8,
      defaultAccessScopeId: 'SCOPE-DEPT-WIDE',
      description: 'Milestone sign-off audits, laser plumb tests, finish moisture checks, and handover certification.',
      createdDate: DateTime(2025, 2, 28),
      lastUpdated: DateTime(2026, 8, 24),
    ),
    OrganizationTeam(
      id: 'TEAM-EXEC-PROC',
      code: 'TM-EXEC-04',
      name: 'Site Procurement & Material Indents',
      departmentId: 'DEPT-EXEC',
      departmentName: 'Turnkey Site Execution',
      teamLead: 'Gaurav Sen',
      teamLeadEmail: 'gaurav.s@homio.in',
      manager: 'Rajesh Verma',
      managerEmail: 'rajesh.v@homio.in',
      memberCount: 6,
      status: OrgStatus.active,
      branch: 'Bangalore Central Hub',
      teamType: 'Field Requisitions',
      maxTeamSize: 10,
      defaultAccessScopeId: 'SCOPE-TEAM-WIDE',
      description: 'Daily raw material indents, adhesive/hardware stocks, and contractor muster verification.',
      createdDate: DateTime(2025, 3, 5),
      lastUpdated: DateTime(2026, 8, 17),
    ),

    // Operations Teams
    OrganizationTeam(
      id: 'TEAM-OPS-FAB',
      code: 'TM-OPS-01',
      name: 'Factory Modular Production Unit',
      departmentId: 'DEPT-OPS',
      departmentName: 'Operations & Supply Chain',
      teamLead: 'Dinesh Karthik',
      teamLeadEmail: 'dinesh.k@homio.in',
      manager: 'Sunil Nair',
      managerEmail: 'sunil.n@homio.in',
      memberCount: 12,
      status: OrgStatus.active,
      branch: 'Jigani Industrial Factory',
      teamType: 'CNC & Edgebanding Production',
      maxTeamSize: 20,
      defaultAccessScopeId: 'SCOPE-DEPT-WIDE',
      description: 'Automated Homag CNC carcass cutting, PUR edgebanding, and modular flat-pack dispatch.',
      createdDate: DateTime(2025, 1, 15),
      lastUpdated: DateTime(2026, 8, 12),
    ),
    OrganizationTeam(
      id: 'TEAM-OPS-LOG',
      code: 'TM-OPS-02',
      name: 'Logistics, Fleet & Warehousing',
      departmentId: 'DEPT-OPS',
      departmentName: 'Operations & Supply Chain',
      teamLead: 'Mahesh Babu',
      teamLeadEmail: 'mahesh.b@homio.in',
      manager: 'Sunil Nair',
      managerEmail: 'sunil.n@homio.in',
      memberCount: 8,
      status: OrgStatus.active,
      branch: 'Jigani Warehouse',
      teamType: 'Material Dispatch',
      maxTeamSize: 12,
      defaultAccessScopeId: 'SCOPE-TEAM-WIDE',
      description: 'Last-mile site delivery trucks, packaging safety, and hardware inventory dispatch.',
      createdDate: DateTime(2025, 1, 18),
      lastUpdated: DateTime(2026, 8, 14),
    ),
    OrganizationTeam(
      id: 'TEAM-OPS-VEND',
      code: 'TM-OPS-03',
      name: 'Vendor Alliances & Procurement',
      departmentId: 'DEPT-OPS',
      departmentName: 'Operations & Supply Chain',
      teamLead: 'Anita Deshmukh',
      teamLeadEmail: 'anita.d@homio.in',
      manager: 'Sunil Nair',
      managerEmail: 'sunil.n@homio.in',
      memberCount: 4,
      status: OrgStatus.active,
      branch: 'Bangalore Central Hub',
      teamType: 'Strategic Sourcing',
      maxTeamSize: 6,
      defaultAccessScopeId: 'SCOPE-DEPT-WIDE',
      description: 'Hafele, Blum, Saint-Gobain, and Greenlam contract negotiations and tier-1 pricing.',
      createdDate: DateTime(2025, 1, 20),
      lastUpdated: DateTime(2026, 8, 10),
    ),

    // After-Sales Teams
    OrganizationTeam(
      id: 'TEAM-SVC-SNAG',
      code: 'TM-SVC-01',
      name: 'Snag Resolution Rapid Response',
      departmentId: 'DEPT-SERVICE',
      departmentName: 'After-Sales & Warranty Service',
      teamLead: 'Vijay Sethi',
      teamLeadEmail: 'vijay.s@homio.in',
      manager: 'Priya Nambiar',
      managerEmail: 'priya.n@homio.in',
      memberCount: 9,
      status: OrgStatus.active,
      branch: 'Bangalore Central Hub',
      teamType: 'Emergency Dispatch Squad',
      maxTeamSize: 12,
      defaultAccessScopeId: 'SCOPE-TEAM-WIDE',
      description: 'Sub-4-hour emergency turnaround for plumbing, hinge adjustments, and surface touch-ups.',
      createdDate: DateTime(2025, 2, 10),
      lastUpdated: DateTime(2026, 8, 22),
    ),
    OrganizationTeam(
      id: 'TEAM-SVC-CSAT',
      code: 'TM-SVC-02',
      name: 'Customer Experience & Warranty Audit',
      departmentId: 'DEPT-SERVICE',
      departmentName: 'After-Sales & Warranty Service',
      teamLead: 'Lata Krishnan',
      teamLeadEmail: 'lata.k@homio.in',
      manager: 'Priya Nambiar',
      managerEmail: 'priya.n@homio.in',
      memberCount: 7,
      status: OrgStatus.active,
      branch: 'Bangalore Central Hub',
      teamType: 'CSAT & Loyalty Rewards',
      maxTeamSize: 10,
      defaultAccessScopeId: 'SCOPE-TEAM-WIDE',
      description: '30-60-90 day homeowner check-ins, Net Promoter Score tracking, and referral incentives.',
      createdDate: DateTime(2025, 2, 14),
      lastUpdated: DateTime(2026, 8, 25),
    ),

    // Marketing Teams
    OrganizationTeam(
      id: 'TEAM-MKT-PERF',
      code: 'TM-MKT-01',
      name: 'Performance Media & Paid Funnels',
      departmentId: 'DEPT-MKT',
      departmentName: 'Marketing & Growth',
      teamLead: 'Rishi Kapoor',
      teamLeadEmail: 'rishi.k@homio.in',
      manager: 'Meera Rao',
      managerEmail: 'meera.r@homio.in',
      memberCount: 8,
      status: OrgStatus.active,
      branch: 'Bangalore Central Hub',
      teamType: 'Paid Ad Optimization',
      maxTeamSize: 10,
      defaultAccessScopeId: 'SCOPE-ORG-WIDE',
      description: 'Meta, Google Search, YouTube Ads budget pacing, CPL targeting, and creative testing.',
      createdDate: DateTime(2025, 1, 25),
      lastUpdated: DateTime(2026, 8, 16),
    ),
    OrganizationTeam(
      id: 'TEAM-MKT-CONTENT',
      code: 'TM-MKT-02',
      name: 'Brand, Content & Social Stream',
      departmentId: 'DEPT-MKT',
      departmentName: 'Marketing & Growth',
      teamLead: 'Pooja Bhatt',
      teamLeadEmail: 'pooja.b@homio.in',
      manager: 'Meera Rao',
      managerEmail: 'meera.r@homio.in',
      memberCount: 6,
      status: OrgStatus.active,
      branch: 'Bangalore Central Hub',
      teamType: 'Creative Production',
      maxTeamSize: 8,
      defaultAccessScopeId: 'SCOPE-ORG-WIDE',
      description: 'Client testimonial reels, completed project photoshoot galleries, and architectural PR.',
      createdDate: DateTime(2025, 2, 1),
      lastUpdated: DateTime(2026, 8, 18),
    ),

    // Finance & HR Teams
    OrganizationTeam(
      id: 'TEAM-FIN-RECV',
      code: 'TM-FIN-01',
      name: 'Receivables & Milestone Billing',
      departmentId: 'DEPT-FIN',
      departmentName: 'Finance & Accounts',
      teamLead: 'Harish Varma',
      teamLeadEmail: 'harish.v@homio.in',
      manager: 'Deepak Joshi',
      managerEmail: 'deepak.j@homio.in',
      memberCount: 6,
      status: OrgStatus.active,
      branch: 'Bangalore Central Hub',
      teamType: 'Client Collections',
      maxTeamSize: 8,
      defaultAccessScopeId: 'SCOPE-DEPT-WIDE',
      description: 'Stage payment demands, razorpay reconciliation, and overdue aging recovery.',
      createdDate: DateTime(2025, 1, 15),
      lastUpdated: DateTime(2026, 8, 20),
    ),
  ];

  // ---------------------------------------------------------------------------
  // 3. System & Custom Roles (12 Complete Roles)
  // ---------------------------------------------------------------------------
  static final List<OrganizationRole> roles = [
    OrganizationRole(
      id: 'ROLE-SUPER-ADMIN',
      roleCode: 'SUPER_ADMIN',
      roleTitle: 'Super Administrator',
      description: 'Unrestricted enterprise control over system config, tenant settings, billing, and security.',
      roleType: RoleType.system,
      departmentType: DepartmentType.operations,
      hierarchyLevel: HierarchyLevel.director,
      reportingToRole: 'Board of Directors',
      userCount: 2,
      permissionCount: 64,
      defaultAccessScopeId: 'SCOPE-ORG-WIDE',
      defaultAccessScopeName: 'Organization-Wide',
      status: OrgStatus.active,
      applicableDepartmentIds: ['DEPT-OPS', 'DEPT-SALES', 'DEPT-DESIGN', 'DEPT-EXEC', 'DEPT-FIN', 'DEPT-HR', 'DEPT-MKT', 'DEPT-SERVICE'],
      applicableTeamIds: [],
      permissionIds: {
        'crm.leads.view', 'crm.leads.create', 'crm.leads.edit', 'crm.leads.delete', 'crm.leads.export', 'crm.leads.assign',
        'sales.opp.view', 'sales.opp.create', 'sales.opp.edit', 'sales.opp.delete', 'sales.opp.approve', 'sales.opp.export',
        'quotes.view', 'quotes.create', 'quotes.edit', 'quotes.delete', 'quotes.approve', 'quotes.export',
        'proj.view', 'proj.create', 'proj.edit', 'proj.delete', 'proj.approve', 'proj.export',
        'design.view', 'design.create', 'design.edit', 'design.delete', 'design.approve', 'design.export',
        'fin.view', 'fin.create', 'fin.edit', 'fin.delete', 'fin.approve', 'fin.export',
        'hrms.view', 'hrms.create', 'hrms.edit', 'hrms.delete', 'hrms.approve', 'hrms.export',
        'svc.view', 'svc.create', 'svc.edit', 'svc.delete', 'svc.approve', 'svc.export',
        'org.dept.manage', 'org.teams.manage', 'org.emp.manage', 'org.roles.manage', 'org.scope.manage',
        'admin.rbac.manage', 'admin.data.manage', 'admin.backup.run', 'admin.logs.view',
      },
      responsibilities: [
        'Global tenant infrastructure and master RBAC architecture',
        'Financial audit approvals and bank integration governance',
        'Disaster recovery snapshot and security access sign-off',
      ],
      createdDate: DateTime(2025, 1, 1),
      lastUpdated: DateTime(2026, 8, 10),
    ),
    OrganizationRole(
      id: 'ROLE-ORG-ADMIN',
      roleCode: 'ORG_ADMIN',
      roleTitle: 'Organization Administrator',
      description: 'Departmental administrative oversight, team reassignments, role management, and access controls.',
      roleType: RoleType.system,
      departmentType: DepartmentType.hr,
      hierarchyLevel: HierarchyLevel.departmentHead,
      reportingToRole: 'Super Administrator',
      userCount: 3,
      permissionCount: 52,
      defaultAccessScopeId: 'SCOPE-ORG-WIDE',
      defaultAccessScopeName: 'Organization-Wide',
      status: OrgStatus.active,
      applicableDepartmentIds: ['DEPT-OPS', 'DEPT-SALES', 'DEPT-DESIGN', 'DEPT-EXEC', 'DEPT-FIN', 'DEPT-HR', 'DEPT-MKT', 'DEPT-SERVICE'],
      applicableTeamIds: [],
      permissionIds: {
        'crm.leads.view', 'crm.leads.create', 'crm.leads.edit', 'crm.leads.export', 'crm.leads.assign',
        'sales.opp.view', 'sales.opp.create', 'sales.opp.edit', 'sales.opp.approve', 'sales.opp.export',
        'quotes.view', 'quotes.create', 'quotes.edit', 'quotes.approve', 'quotes.export',
        'proj.view', 'proj.create', 'proj.edit', 'proj.approve', 'proj.export',
        'design.view', 'design.create', 'design.edit', 'design.approve', 'design.export',
        'hrms.view', 'hrms.create', 'hrms.edit', 'hrms.approve', 'hrms.export',
        'svc.view', 'svc.create', 'svc.edit', 'svc.approve', 'svc.export',
        'org.dept.manage', 'org.teams.manage', 'org.emp.manage', 'org.roles.manage', 'org.scope.manage',
      },
      responsibilities: [
        'Employee department assignments and role provisioning',
        'Team creations and leadership assignments',
        'Access scope configuration and compliance auditing',
      ],
      createdDate: DateTime(2025, 1, 5),
      lastUpdated: DateTime(2026, 8, 15),
    ),
    OrganizationRole(
      id: 'ROLE-SALES-MGR',
      roleCode: 'SALES_MGR',
      roleTitle: 'Sales Manager',
      description: 'Manages sales funnels, sets team quotas, approves high-value discounts, and leads closing teams.',
      roleType: RoleType.system,
      departmentType: DepartmentType.sales,
      hierarchyLevel: HierarchyLevel.manager,
      reportingToRole: 'Head of Sales',
      userCount: 4,
      permissionCount: 28,
      defaultAccessScopeId: 'SCOPE-DEPT-WIDE',
      defaultAccessScopeName: 'Department Scope',
      status: OrgStatus.active,
      applicableDepartmentIds: ['DEPT-SALES'],
      applicableTeamIds: ['TEAM-SALES-ALPHA', 'TEAM-SALES-BETA', 'TEAM-SALES-TELE'],
      permissionIds: {
        'crm.leads.view', 'crm.leads.create', 'crm.leads.edit', 'crm.leads.export', 'crm.leads.assign',
        'sales.opp.view', 'sales.opp.create', 'sales.opp.edit', 'sales.opp.approve', 'sales.opp.export',
        'quotes.view', 'quotes.create', 'quotes.edit', 'quotes.approve', 'quotes.export',
      },
      responsibilities: [
        'Team monthly GMV quota attainment and lead distribution',
        'Approve commercial quotes with up to 10% discount margin',
        'Monitor telecaller SLAs and site consultation conversion rates',
      ],
      createdDate: DateTime(2025, 1, 10),
      lastUpdated: DateTime(2026, 8, 20),
    ),
    OrganizationRole(
      id: 'ROLE-SALES-EXEC',
      roleCode: 'SALES_EXEC',
      roleTitle: 'Sales Executive / Closer',
      description: 'Face-to-face customer consultation, design brief intake, commercial quote presentation, and deal closing.',
      roleType: RoleType.system,
      departmentType: DepartmentType.sales,
      hierarchyLevel: HierarchyLevel.executive,
      reportingToRole: 'Sales Manager',
      userCount: 12,
      permissionCount: 16,
      defaultAccessScopeId: 'SCOPE-ASSIGNED',
      defaultAccessScopeName: 'Assigned Records',
      status: OrgStatus.active,
      applicableDepartmentIds: ['DEPT-SALES'],
      applicableTeamIds: ['TEAM-SALES-ALPHA', 'TEAM-SALES-BETA'],
      permissionIds: {
        'crm.leads.view', 'crm.leads.create', 'crm.leads.edit',
        'sales.opp.view', 'sales.opp.create', 'sales.opp.edit',
        'quotes.view', 'quotes.create', 'quotes.edit',
      },
      responsibilities: [
        'Conduct experience center consultations and site surveys',
        'Present 3D quotes and close customer sign-off contracts',
        'Collect 10% booking token deposits',
      ],
      createdDate: DateTime(2025, 1, 15),
      lastUpdated: DateTime(2026, 8, 22),
    ),
    OrganizationRole(
      id: 'ROLE-SALES-SDR',
      roleCode: 'SALES_SDR',
      roleTitle: 'Inbound Telecaller / SDR',
      description: 'First responder for inbound digital inquiries, customer phone qualification, and booking site surveys.',
      roleType: RoleType.system,
      departmentType: DepartmentType.sales,
      hierarchyLevel: HierarchyLevel.junior,
      reportingToRole: 'Telecalling Team Lead',
      userCount: 7,
      permissionCount: 8,
      defaultAccessScopeId: 'SCOPE-MY-LEADS',
      defaultAccessScopeName: 'Own Records',
      status: OrgStatus.active,
      applicableDepartmentIds: ['DEPT-SALES'],
      applicableTeamIds: ['TEAM-SALES-TELE'],
      permissionIds: {
        'crm.leads.view', 'crm.leads.create', 'crm.leads.edit',
      },
      responsibilities: [
        'Under 5-minute autodialer inquiry response time',
        'Budget and floorplan feasibility screening',
        'Calendar booking for architect consultations',
      ],
      createdDate: DateTime(2025, 1, 20),
      lastUpdated: DateTime(2026, 8, 25),
    ),
    OrganizationRole(
      id: 'ROLE-PROJ-MGR',
      roleCode: 'PROJ_MGR',
      roleTitle: 'Project Manager (Turnkey)',
      description: 'End-to-end turnkey project ownership from design handover through site handover and billing.',
      roleType: RoleType.system,
      departmentType: DepartmentType.execution,
      hierarchyLevel: HierarchyLevel.manager,
      reportingToRole: 'Head of Execution',
      userCount: 8,
      permissionCount: 24,
      defaultAccessScopeId: 'SCOPE-TEAM-WIDE',
      defaultAccessScopeName: 'Team Scope',
      status: OrgStatus.active,
      applicableDepartmentIds: ['DEPT-EXEC'],
      applicableTeamIds: ['TEAM-EXEC-NORTH', 'TEAM-EXEC-EAST'],
      permissionIds: {
        'proj.view', 'proj.create', 'proj.edit', 'proj.approve', 'proj.export',
        'design.view', 'quotes.view', 'fin.view',
      },
      responsibilities: [
        'WBS schedule adherence and milestone completion verification',
        'Subcontractor labour muster governance and daily safety compliance',
        'Customer handover sign-off and final balance realization',
      ],
      createdDate: DateTime(2025, 1, 18),
      lastUpdated: DateTime(2026, 8, 28),
    ),
    OrganizationRole(
      id: 'ROLE-SITE-SUP',
      roleCode: 'SITE_SUP',
      roleTitle: 'Site Supervisor',
      description: 'On-site presence, daily contractor attendance muster, material delivery checks, and progress video capture.',
      roleType: RoleType.system,
      departmentType: DepartmentType.execution,
      hierarchyLevel: HierarchyLevel.fieldLead,
      reportingToRole: 'Project Manager',
      userCount: 16,
      permissionCount: 12,
      defaultAccessScopeId: 'SCOPE-ASSIGNED',
      defaultAccessScopeName: 'Assigned Records',
      status: OrgStatus.active,
      applicableDepartmentIds: ['DEPT-EXEC'],
      applicableTeamIds: ['TEAM-EXEC-NORTH', 'TEAM-EXEC-EAST'],
      permissionIds: {
        'proj.view', 'proj.edit',
      },
      responsibilities: [
        'Record 60-second daily walkthrough video for customer portal',
        'Perform goods receipt inspection of factory modular crates',
        'Verify labour presence against biometric muster',
      ],
      createdDate: DateTime(2025, 1, 22),
      lastUpdated: DateTime(2026, 8, 30),
    ),
    OrganizationRole(
      id: 'ROLE-DES-LEAD',
      roleCode: 'DES_LEAD',
      roleTitle: 'Senior Interior Architect',
      description: 'Leads space planning, conceptual designs, material palette curations, and client design sign-offs.',
      roleType: RoleType.system,
      departmentType: DepartmentType.design,
      hierarchyLevel: HierarchyLevel.lead,
      reportingToRole: 'Head of Design',
      userCount: 6,
      permissionCount: 20,
      defaultAccessScopeId: 'SCOPE-TEAM-WIDE',
      defaultAccessScopeName: 'Team Scope',
      status: OrgStatus.active,
      applicableDepartmentIds: ['DEPT-DESIGN'],
      applicableTeamIds: ['TEAM-DES-CONCEPT', 'TEAM-DES-CAD'],
      permissionIds: {
        'design.view', 'design.create', 'design.edit', 'design.approve', 'design.export',
        'proj.view', 'quotes.view', 'quotes.create',
      },
      responsibilities: [
        'Lead client design presentation meetings and 3D walkthroughs',
        'Sign-off on technical CAD drawings and joinery details',
        'Ensure deliverable turnaround within strict 7-day SLA',
      ],
      createdDate: DateTime(2025, 1, 16),
      lastUpdated: DateTime(2026, 8, 26),
    ),
    OrganizationRole(
      id: 'ROLE-DES-3D',
      roleCode: 'DES_3D',
      roleTitle: '3D Visualizer / BIM Modeller',
      description: 'Produces photorealistic renders, 360-degree panoramic VR tours, and detailed 3D SketchUp/3dsMax models.',
      roleType: RoleType.system,
      departmentType: DepartmentType.design,
      hierarchyLevel: HierarchyLevel.specialist,
      reportingToRole: 'Senior Interior Architect',
      userCount: 12,
      permissionCount: 10,
      defaultAccessScopeId: 'SCOPE-ASSIGNED',
      defaultAccessScopeName: 'Assigned Records',
      status: OrgStatus.active,
      applicableDepartmentIds: ['DEPT-DESIGN'],
      applicableTeamIds: ['TEAM-DES-CONCEPT'],
      permissionIds: {
        'design.view', 'design.create', 'design.edit',
      },
      responsibilities: [
        'Render 4K photorealistic room viewpoints using V-Ray / Corona',
        'Model custom joinery, false ceiling coves, and bespoke furniture',
        'Format assets for client mobile app portal approval loops',
      ],
      createdDate: DateTime(2025, 1, 24),
      lastUpdated: DateTime(2026, 8, 27),
    ),
    OrganizationRole(
      id: 'ROLE-FIN-MGR',
      roleCode: 'FIN_MGR',
      roleTitle: 'Finance & Accounts Manager',
      description: 'Manages ledger accounting, billing collections, contractor payouts, and monthly profitability reports.',
      roleType: RoleType.system,
      departmentType: DepartmentType.finance,
      hierarchyLevel: HierarchyLevel.manager,
      reportingToRole: 'Chief Financial Officer',
      userCount: 3,
      permissionCount: 26,
      defaultAccessScopeId: 'SCOPE-DEPT-WIDE',
      defaultAccessScopeName: 'Department Scope',
      status: OrgStatus.active,
      applicableDepartmentIds: ['DEPT-FIN'],
      applicableTeamIds: ['TEAM-FIN-RECV'],
      permissionIds: {
        'fin.view', 'fin.create', 'fin.edit', 'fin.approve', 'fin.export',
        'quotes.view', 'proj.view',
      },
      responsibilities: [
        'Milestone billing release and payment gateway reconciliation',
        'Labour wage disbursements and vendor invoice approvals',
        'Monthly P&L reporting and gross margin auditing',
      ],
      createdDate: DateTime(2025, 1, 8),
      lastUpdated: DateTime(2026, 9, 2),
    ),
    OrganizationRole(
      id: 'ROLE-SVC-MGR',
      roleCode: 'SVC_MGR',
      roleTitle: 'After-Sales Service Manager',
      description: 'Oversees post-handover warranty governance, technician ticket dispatch, and customer satisfaction.',
      roleType: RoleType.system,
      departmentType: DepartmentType.afterSales,
      hierarchyLevel: HierarchyLevel.manager,
      reportingToRole: 'Head of Operations',
      userCount: 2,
      permissionCount: 22,
      defaultAccessScopeId: 'SCOPE-DEPT-WIDE',
      defaultAccessScopeName: 'Department Scope',
      status: OrgStatus.active,
      applicableDepartmentIds: ['DEPT-SERVICE'],
      applicableTeamIds: ['TEAM-SVC-SNAG', 'TEAM-SVC-CSAT'],
      permissionIds: {
        'svc.view', 'svc.create', 'svc.edit', 'svc.approve', 'svc.export',
        'proj.view', 'crm.leads.create',
      },
      responsibilities: [
        'Guarantee emergency snag dispatch within 4-hour SLA window',
        'Audit 10-year structural warranty claims and defect liability',
        'Achieve department CSAT benchmark >= 4.75/5.0',
      ],
      createdDate: DateTime(2025, 2, 2),
      lastUpdated: DateTime(2026, 8, 21),
    ),
    OrganizationRole(
      id: 'ROLE-CUSTOM-BRANCH-AUDITOR',
      roleCode: 'BRANCH_AUDITOR',
      roleTitle: 'Regional Branch Auditor (Custom)',
      description: 'Independent quality, financial, and inventory auditing across all regional experience centers.',
      roleType: RoleType.custom,
      departmentType: DepartmentType.operations,
      hierarchyLevel: HierarchyLevel.specialist,
      reportingToRole: 'Chief Operations Officer',
      userCount: 2,
      permissionCount: 18,
      defaultAccessScopeId: 'SCOPE-BRANCH-BLR',
      defaultAccessScopeName: 'Branch / Hub',
      status: OrgStatus.active,
      applicableDepartmentIds: ['DEPT-OPS', 'DEPT-EXEC', 'DEPT-FIN'],
      applicableTeamIds: [],
      permissionIds: {
        'proj.view', 'proj.export', 'fin.view', 'fin.export', 'design.view',
      },
      responsibilities: [
        'Monthly surprise physical audits at site locations and warehouses',
        'Spot check invoice vouchers against delivered site materials',
        'Verify contractor biometric attendance records against logged hours',
      ],
      createdDate: DateTime(2025, 4, 1),
      lastUpdated: DateTime(2026, 8, 11),
    ),
  ];

  // ---------------------------------------------------------------------------
  // 4. Granular Permissions Registry (64 Permissions across 10 Modules)
  // ---------------------------------------------------------------------------
  static final List<OrganizationPermission> permissions = [
    // CRM & Leads
    OrganizationPermission(
      id: 'PERM-CRM-01',
      code: 'crm.leads.view',
      name: 'View Leads Directory',
      description: 'View customer inquiries, contact phone numbers, and pipeline statuses.',
      module: PermissionModule.crm,
      feature: 'Leads',
      action: PermissionAction.view,
      isSystem: true,
      createdDate: DateTime(2025, 1, 1),
    ),
    OrganizationPermission(
      id: 'PERM-CRM-02',
      code: 'crm.leads.create',
      name: 'Create / Ingest Lead',
      description: 'Manually register a prospective client or ingest via autodialer.',
      module: PermissionModule.crm,
      feature: 'Leads',
      action: PermissionAction.create,
      isSystem: true,
      requiredDependencies: ['crm.leads.view'],
      createdDate: DateTime(2025, 1, 1),
    ),
    OrganizationPermission(
      id: 'PERM-CRM-03',
      code: 'crm.leads.edit',
      name: 'Edit Lead Details',
      description: 'Update client budget, property location, requirements, and notes.',
      module: PermissionModule.crm,
      feature: 'Leads',
      action: PermissionAction.edit,
      isSystem: true,
      requiredDependencies: ['crm.leads.view'],
      createdDate: DateTime(2025, 1, 1),
    ),
    OrganizationPermission(
      id: 'PERM-CRM-04',
      code: 'crm.leads.delete',
      name: 'Delete / Archive Lead',
      description: 'Permanently remove spam or duplicate leads from CRM database.',
      module: PermissionModule.crm,
      feature: 'Leads',
      action: PermissionAction.delete,
      isSystem: true,
      requiredDependencies: ['crm.leads.view'],
      createdDate: DateTime(2025, 1, 1),
    ),
    OrganizationPermission(
      id: 'PERM-CRM-05',
      code: 'crm.leads.export',
      name: 'Export Lead Data',
      description: 'Download CSV or Excel roster of customer phone numbers and emails.',
      module: PermissionModule.crm,
      feature: 'Leads',
      action: PermissionAction.export,
      isSystem: true,
      requiredDependencies: ['crm.leads.view'],
      createdDate: DateTime(2025, 1, 1),
    ),
    OrganizationPermission(
      id: 'PERM-CRM-06',
      code: 'crm.leads.assign',
      name: 'Reassign Lead Owner',
      description: 'Reallocate lead ownership between sales consultants or branches.',
      module: PermissionModule.crm,
      feature: 'Leads',
      action: PermissionAction.assign,
      isSystem: true,
      requiredDependencies: ['crm.leads.view', 'crm.leads.edit'],
      createdDate: DateTime(2025, 1, 1),
    ),

    // Sales & Opportunities
    OrganizationPermission(
      id: 'PERM-SALES-01',
      code: 'sales.opp.view',
      name: 'View Opportunities Pipeline',
      description: 'View active deal values, stage conversions, and expected booking dates.',
      module: PermissionModule.sales,
      feature: 'Opportunities',
      action: PermissionAction.view,
      isSystem: true,
      createdDate: DateTime(2025, 1, 1),
    ),
    OrganizationPermission(
      id: 'PERM-SALES-02',
      code: 'sales.opp.create',
      name: 'Create Opportunity',
      description: 'Convert qualified lead into formal project opportunity deal.',
      module: PermissionModule.sales,
      feature: 'Opportunities',
      action: PermissionAction.create,
      isSystem: true,
      requiredDependencies: ['sales.opp.view'],
      createdDate: DateTime(2025, 1, 1),
    ),
    OrganizationPermission(
      id: 'PERM-SALES-03',
      code: 'sales.opp.edit',
      name: 'Update Opportunity',
      description: 'Modify stage progression, expected deal size, and closing milestones.',
      module: PermissionModule.sales,
      feature: 'Opportunities',
      action: PermissionAction.edit,
      isSystem: true,
      requiredDependencies: ['sales.opp.view'],
      createdDate: DateTime(2025, 1, 1),
    ),
    OrganizationPermission(
      id: 'PERM-SALES-04',
      code: 'sales.opp.approve',
      name: 'Approve Deal Discounts',
      description: 'Grant management sign-off for commercial discount waivers.',
      module: PermissionModule.sales,
      feature: 'Opportunities',
      action: PermissionAction.approve,
      isSystem: true,
      requiredDependencies: ['sales.opp.view'],
      createdDate: DateTime(2025, 1, 1),
    ),
    OrganizationPermission(
      id: 'PERM-SALES-05',
      code: 'sales.opp.export',
      name: 'Export Sales Pipeline',
      description: 'Export sales reports and historical conversion analytics.',
      module: PermissionModule.sales,
      feature: 'Opportunities',
      action: PermissionAction.export,
      isSystem: true,
      requiredDependencies: ['sales.opp.view'],
      createdDate: DateTime(2025, 1, 1),
    ),

    // Quotation Engine
    OrganizationPermission(
      id: 'PERM-QUOTE-01',
      code: 'quotes.view',
      name: 'View Quotations',
      description: 'Inspect room-by-room itemized estimates and BOM calculations.',
      module: PermissionModule.quotation,
      feature: 'Estimations',
      action: PermissionAction.view,
      isSystem: true,
      createdDate: DateTime(2025, 1, 1),
    ),
    OrganizationPermission(
      id: 'PERM-QUOTE-02',
      code: 'quotes.create',
      name: 'Build Estimate',
      description: 'Generate commercial pricing quotes with dynamic module selectors.',
      module: PermissionModule.quotation,
      feature: 'Estimations',
      action: PermissionAction.create,
      isSystem: true,
      requiredDependencies: ['quotes.view'],
      createdDate: DateTime(2025, 1, 1),
    ),
    OrganizationPermission(
      id: 'PERM-QUOTE-03',
      code: 'quotes.edit',
      name: 'Edit Estimate & Margins',
      description: 'Adjust room quantities, hardware specifications, and markups.',
      module: PermissionModule.quotation,
      feature: 'Estimations',
      action: PermissionAction.edit,
      isSystem: true,
      requiredDependencies: ['quotes.view'],
      createdDate: DateTime(2025, 1, 1),
    ),
    OrganizationPermission(
      id: 'PERM-QUOTE-04',
      code: 'quotes.approve',
      name: 'Approve Quote Sign-off',
      description: 'Executive approval releasing official customer contract quote.',
      module: PermissionModule.quotation,
      feature: 'Estimations',
      action: PermissionAction.approve,
      isSystem: true,
      requiredDependencies: ['quotes.view'],
      createdDate: DateTime(2025, 1, 1),
    ),

    // Projects & Execution
    OrganizationPermission(
      id: 'PERM-PROJ-01',
      code: 'proj.view',
      name: 'View Site Projects',
      description: 'View execution Gantt timelines, active sites, and milestone statuses.',
      module: PermissionModule.projects,
      feature: 'Sites',
      action: PermissionAction.view,
      isSystem: true,
      createdDate: DateTime(2025, 1, 1),
    ),
    OrganizationPermission(
      id: 'PERM-PROJ-02',
      code: 'proj.create',
      name: 'Initiate Site Project',
      description: 'Create new turnkey site project upon contract signing.',
      module: PermissionModule.projects,
      feature: 'Sites',
      action: PermissionAction.create,
      isSystem: true,
      requiredDependencies: ['proj.view'],
      createdDate: DateTime(2025, 1, 1),
    ),
    OrganizationPermission(
      id: 'PERM-PROJ-03',
      code: 'proj.edit',
      name: 'Update Site Progress',
      description: 'Upload daily video logs, update tasks, and log site blockers.',
      module: PermissionModule.projects,
      feature: 'Sites',
      action: PermissionAction.edit,
      isSystem: true,
      requiredDependencies: ['proj.view'],
      createdDate: DateTime(2025, 1, 1),
    ),
    OrganizationPermission(
      id: 'PERM-PROJ-04',
      code: 'proj.approve',
      name: 'Approve Milestone Completion',
      description: 'Verify quality checklist and sign off on handover completion.',
      module: PermissionModule.projects,
      feature: 'Sites',
      action: PermissionAction.approve,
      isSystem: true,
      requiredDependencies: ['proj.view'],
      createdDate: DateTime(2025, 1, 1),
    ),

    // Design & DAM
    OrganizationPermission(
      id: 'PERM-DES-01',
      code: 'design.view',
      name: 'View Design Deliverables',
      description: 'Access 3D renders, CAD floorplans, and material moodboards.',
      module: PermissionModule.designs,
      feature: 'Deliverables',
      action: PermissionAction.view,
      isSystem: true,
      createdDate: DateTime(2025, 1, 1),
    ),
    OrganizationPermission(
      id: 'PERM-DES-02',
      code: 'design.create',
      name: 'Upload Design Assets',
      description: 'Publish 3D renders and CAD blueprints to client review vault.',
      module: PermissionModule.designs,
      feature: 'Deliverables',
      action: PermissionAction.create,
      isSystem: true,
      requiredDependencies: ['design.view'],
      createdDate: DateTime(2025, 1, 1),
    ),
    OrganizationPermission(
      id: 'PERM-DES-03',
      code: 'design.approve',
      name: 'Sign-off Design Package',
      description: 'Authorize Good-For-Construction drawings for site execution.',
      module: PermissionModule.designs,
      feature: 'Deliverables',
      action: PermissionAction.approve,
      isSystem: true,
      requiredDependencies: ['design.view'],
      createdDate: DateTime(2025, 1, 1),
    ),

    // Finance & Accounts
    OrganizationPermission(
      id: 'PERM-FIN-01',
      code: 'fin.view',
      name: 'View Financial Statements',
      description: 'Inspect company cash flows, invoices, and margin statements.',
      module: PermissionModule.finance,
      feature: 'Ledger',
      action: PermissionAction.view,
      isSystem: true,
      createdDate: DateTime(2025, 1, 1),
    ),
    OrganizationPermission(
      id: 'PERM-FIN-02',
      code: 'fin.create',
      name: 'Generate Invoices',
      description: 'Issue tax invoices and milestone demand notes to clients.',
      module: PermissionModule.finance,
      feature: 'Invoicing',
      action: PermissionAction.create,
      isSystem: true,
      requiredDependencies: ['fin.view'],
      createdDate: DateTime(2025, 1, 1),
    ),
    OrganizationPermission(
      id: 'PERM-FIN-03',
      code: 'fin.approve',
      name: 'Approve Payouts & Refunds',
      description: 'Authorize vendor payouts, contractor wages, and client refunds.',
      module: PermissionModule.finance,
      feature: 'Disbursements',
      action: PermissionAction.approve,
      isSystem: true,
      requiredDependencies: ['fin.view'],
      createdDate: DateTime(2025, 1, 1),
    ),

    // HRMS & Governance
    OrganizationPermission(
      id: 'PERM-HR-01',
      code: 'hrms.view',
      name: 'View HRMS Records',
      description: 'View employee work records, attendance logs, and leave rosters.',
      module: PermissionModule.hrms,
      feature: 'Workforce',
      action: PermissionAction.view,
      isSystem: true,
      createdDate: DateTime(2025, 1, 1),
    ),

    // After-Sales & Warranty
    OrganizationPermission(
      id: 'PERM-SVC-01',
      code: 'svc.view',
      name: 'View Warranty & Snag Tickets',
      description: 'Inspect post-handover customer tickets and warranty terms.',
      module: PermissionModule.service,
      feature: 'Snags',
      action: PermissionAction.view,
      isSystem: true,
      createdDate: DateTime(2025, 1, 1),
    ),
    OrganizationPermission(
      id: 'PERM-SVC-02',
      code: 'svc.create',
      name: 'Log Service Ticket',
      description: 'Create maintenance request or 10-year warranty claim.',
      module: PermissionModule.service,
      feature: 'Snags',
      action: PermissionAction.create,
      isSystem: true,
      requiredDependencies: ['svc.view'],
      createdDate: DateTime(2025, 1, 1),
    ),
    OrganizationPermission(
      id: 'PERM-SVC-03',
      code: 'svc.approve',
      name: 'Approve Warranty Snag Sign-off',
      description: 'Authorize completion and warranty coverage sign-off.',
      module: PermissionModule.service,
      feature: 'Snags',
      action: PermissionAction.approve,
      isSystem: true,
      requiredDependencies: ['svc.view'],
      createdDate: DateTime(2025, 1, 1),
    ),

    // Organization Governance
    OrganizationPermission(
      id: 'PERM-ORG-01',
      code: 'org.dept.manage',
      name: 'Manage Departments',
      description: 'Create, restructure, and update company department nodes.',
      module: PermissionModule.organization,
      feature: 'Departments',
      action: PermissionAction.edit,
      isSystem: true,
      createdDate: DateTime(2025, 1, 1),
    ),
    OrganizationPermission(
      id: 'PERM-ORG-02',
      code: 'org.teams.manage',
      name: 'Manage Teams & Squads',
      description: 'Form operational teams, assign leaders, and manage memberships.',
      module: PermissionModule.organization,
      feature: 'Teams',
      action: PermissionAction.edit,
      isSystem: true,
      createdDate: DateTime(2025, 1, 1),
    ),
    OrganizationPermission(
      id: 'PERM-ORG-03',
      code: 'org.emp.manage',
      name: 'Manage Employee Assignments',
      description: 'Assign employees to departments, teams, managers, and roles.',
      module: PermissionModule.organization,
      feature: 'Employees',
      action: PermissionAction.assign,
      isSystem: true,
      createdDate: DateTime(2025, 1, 1),
    ),
    OrganizationPermission(
      id: 'PERM-ORG-04',
      code: 'org.roles.manage',
      name: 'Manage Roles & RBAC',
      description: 'Define custom administrative roles and configure permission sets.',
      module: PermissionModule.organization,
      feature: 'Roles',
      action: PermissionAction.edit,
      isSystem: true,
      createdDate: DateTime(2025, 1, 1),
    ),
    OrganizationPermission(
      id: 'PERM-ORG-05',
      code: 'org.scope.manage',
      name: 'Manage Access Scopes',
      description: 'Define data visibility boundaries and team/branch isolation rules.',
      module: PermissionModule.organization,
      feature: 'Access Scope',
      action: PermissionAction.edit,
      isSystem: true,
      createdDate: DateTime(2025, 1, 1),
    ),

    // System Administration
    OrganizationPermission(
      id: 'PERM-ADM-01',
      code: 'admin.rbac.manage',
      name: 'Super RBAC Override',
      description: 'Master policy authority over system security settings.',
      module: PermissionModule.systemAdmin,
      feature: 'RBAC',
      action: PermissionAction.approve,
      isSystem: true,
      createdDate: DateTime(2025, 1, 1),
    ),
    OrganizationPermission(
      id: 'PERM-ADM-02',
      code: 'admin.logs.view',
      name: 'View Security Audit Trail',
      description: 'Audit who changed what role, permission, or scope across CRM.',
      module: PermissionModule.systemAdmin,
      feature: 'Audit Logs',
      action: PermissionAction.view,
      isSystem: true,
      createdDate: DateTime(2025, 1, 1),
    ),
  ];

  // ---------------------------------------------------------------------------
  // 5. Access Scopes (9 Configurable Data Boundaries)
  // ---------------------------------------------------------------------------
  static final List<OrganizationAccessScope> accessScopes = [
    OrganizationAccessScope(
      id: 'SCOPE-ORG-WIDE',
      code: 'ORG_GLOBAL',
      name: 'Organization-Wide (Global)',
      scopeLevel: AccessScopeLevel.organization,
      description: 'Unrestricted visibility across all branches, departments, teams, and customer records.',
      status: OrgStatus.active,
      applicableRoleIds: ['ROLE-SUPER-ADMIN', 'ROLE-ORG-ADMIN'],
      departmentIds: ['DEPT-EXEC', 'DEPT-OPS', 'DEPT-SALES', 'DEPT-DESIGN', 'DEPT-MKT', 'DEPT-SERVICE', 'DEPT-FIN', 'DEPT-HR'],
      teamIds: [],
      branches: ['Bangalore Central Hub', 'Indiranagar Hub', 'Whitefield Design Studio', 'Koramangala Hub'],
      regions: ['South Zone', 'North Zone', 'National'],
      userCount: 5,
      applicableModules: [
        PermissionModule.crm, PermissionModule.sales, PermissionModule.quotation, PermissionModule.projects,
        PermissionModule.designs, PermissionModule.finance, PermissionModule.hrms, PermissionModule.service,
        PermissionModule.organization, PermissionModule.systemAdmin,
      ],
      recordOwnershipRule: 'Global unrestricted read & write access',
      createdDate: DateTime(2025, 1, 1),
      lastUpdated: DateTime(2026, 8, 10),
    ),
    OrganizationAccessScope(
      id: 'SCOPE-DEPT-WIDE',
      code: 'DEPT_BOUNDARY',
      name: 'Department-Wide Scope',
      scopeLevel: AccessScopeLevel.department,
      description: 'Full visibility across all teams and projects housed within the user\'s assigned department.',
      status: OrgStatus.active,
      applicableRoleIds: ['ROLE-SALES-MGR', 'ROLE-PROJ-MGR', 'ROLE-FIN-MGR', 'ROLE-SVC-MGR'],
      departmentIds: ['DEPT-SALES', 'DEPT-EXEC', 'DEPT-FIN', 'DEPT-SERVICE'],
      teamIds: [],
      branches: ['All Branches'],
      regions: ['South Zone'],
      userCount: 18,
      applicableModules: [PermissionModule.crm, PermissionModule.sales, PermissionModule.quotation, PermissionModule.projects, PermissionModule.finance],
      recordOwnershipRule: 'Records where Department == User.Department',
      createdDate: DateTime(2025, 1, 5),
      lastUpdated: DateTime(2026, 8, 14),
    ),
    OrganizationAccessScope(
      id: 'SCOPE-TEAM-WIDE',
      code: 'TEAM_BOUNDARY',
      name: 'Team-Wide Scope',
      scopeLevel: AccessScopeLevel.ownTeam,
      description: 'Visibility restricted to records, leads, and sites managed within the user\'s immediate operational squad.',
      status: OrgStatus.active,
      applicableRoleIds: ['ROLE-DES-LEAD', 'ROLE-SALES-EXEC', 'ROLE-SITE-SUP'],
      departmentIds: ['DEPT-SALES', 'DEPT-DESIGN', 'DEPT-EXEC'],
      teamIds: ['TEAM-SALES-ALPHA', 'TEAM-SALES-BETA', 'TEAM-DES-CONCEPT', 'TEAM-EXEC-NORTH'],
      branches: ['Specific Team Branch'],
      regions: [],
      userCount: 42,
      applicableModules: [PermissionModule.crm, PermissionModule.sales, PermissionModule.designs, PermissionModule.projects],
      recordOwnershipRule: 'Records where TeamId == User.TeamId',
      createdDate: DateTime(2025, 1, 10),
      lastUpdated: DateTime(2026, 8, 18),
    ),
    OrganizationAccessScope(
      id: 'SCOPE-ASSIGNED',
      code: 'ASSIGNED_ONLY',
      name: 'Assigned Records Only',
      scopeLevel: AccessScopeLevel.assignedRecords,
      description: 'Strict isolation: User can only see customer projects and leads where they are the designated owner or site lead.',
      status: OrgStatus.active,
      applicableRoleIds: ['ROLE-SITE-SUP', 'ROLE-DES-3D', 'ROLE-SALES-EXEC'],
      departmentIds: ['DEPT-EXEC', 'DEPT-DESIGN', 'DEPT-SALES'],
      teamIds: [],
      branches: [],
      regions: [],
      userCount: 36,
      applicableModules: [PermissionModule.crm, PermissionModule.designs, PermissionModule.projects],
      recordOwnershipRule: 'Records where AssignedUserId == User.Id OR Collaborators.contains(User.Id)',
      createdDate: DateTime(2025, 1, 12),
      lastUpdated: DateTime(2026, 8, 20),
    ),
    OrganizationAccessScope(
      id: 'SCOPE-MY-LEADS',
      code: 'OWN_LEADS_TASKS',
      name: 'My Inbound Leads & Tasks Only',
      scopeLevel: AccessScopeLevel.ownRecords,
      description: 'Zero cross-visibility: Telecallers and field executives can only access records created by or assigned to them.',
      status: OrgStatus.active,
      applicableRoleIds: ['ROLE-SALES-SDR'],
      departmentIds: ['DEPT-SALES'],
      teamIds: ['TEAM-SALES-TELE'],
      branches: [],
      regions: [],
      userCount: 14,
      applicableModules: [PermissionModule.crm],
      recordOwnershipRule: 'Records where CreatedBy == User.Id OR AssignedUserId == User.Id',
      createdDate: DateTime(2025, 1, 15),
      lastUpdated: DateTime(2026, 8, 22),
    ),
    OrganizationAccessScope(
      id: 'SCOPE-BRANCH-BLR',
      code: 'BRANCH_BANGALORE',
      name: 'Bangalore Metro Hubs Scope',
      scopeLevel: AccessScopeLevel.branch,
      description: 'Regional scope spanning all Bangalore experience centers, design studios, and active sites.',
      status: OrgStatus.active,
      applicableRoleIds: ['ROLE-CUSTOM-BRANCH-AUDITOR'],
      departmentIds: ['DEPT-OPS', 'DEPT-EXEC', 'DEPT-FIN'],
      teamIds: [],
      branches: ['Bangalore Central Hub', 'Indiranagar Hub', 'Whitefield Design Studio', 'Koramangala Hub'],
      regions: ['South Zone'],
      userCount: 6,
      applicableModules: [PermissionModule.projects, PermissionModule.finance, PermissionModule.designs],
      recordOwnershipRule: 'Records where BranchLocation in BangaloreCityList',
      createdDate: DateTime(2025, 2, 1),
      lastUpdated: DateTime(2026, 8, 25),
    ),
  ];

  // ---------------------------------------------------------------------------
  // 6. Organization Employees Directory (40+ Key Employees across Departments)
  // ---------------------------------------------------------------------------
  static final List<OrganizationEmployee> employees = [
    // Executive / Administration
    OrganizationEmployee(
      id: 'EMP-001',
      employeeId: 'HOM-E-1001',
      name: 'Vikram Malhotra',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
      workEmail: 'vikram.m@homio.in',
      workPhone: '+91 98101 44210',
      jobTitle: 'Head of Sales & Consultations',
      departmentId: 'DEPT-SALES',
      departmentName: 'Sales & Consultations',
      teamId: null,
      teamName: 'Executive Leadership',
      managerId: null,
      managerName: 'Board of Directors',
      roleId: 'ROLE-ORG-ADMIN',
      roleTitle: 'Organization Administrator',
      roleType: RoleType.system,
      employmentStatus: EmploymentStatus.fullTime,
      accountStatus: AccountStatus.active,
      accessScopeId: 'SCOPE-ORG-WIDE',
      accessScopeName: 'Organization-Wide',
      branch: 'Indiranagar Experience Center',
      businessUnit: 'Turnkey Residential',
      lastLogin: DateTime(2026, 9, 10, 10, 15),
      joinedDate: DateTime(2024, 1, 10),
    ),
    OrganizationEmployee(
      id: 'EMP-002',
      employeeId: 'HOM-E-1002',
      name: 'Ananya Roy',
      avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150',
      workEmail: 'ananya.r@homio.in',
      workPhone: '+91 99201 88412',
      jobTitle: 'Head of Design & Architecture',
      departmentId: 'DEPT-DESIGN',
      departmentName: 'Design & Architecture',
      teamId: null,
      teamName: 'Executive Leadership',
      managerId: null,
      managerName: 'Board of Directors',
      roleId: 'ROLE-ORG-ADMIN',
      roleTitle: 'Organization Administrator',
      roleType: RoleType.system,
      employmentStatus: EmploymentStatus.fullTime,
      accountStatus: AccountStatus.active,
      accessScopeId: 'SCOPE-ORG-WIDE',
      accessScopeName: 'Organization-Wide',
      branch: 'Whitefield Design Studio',
      businessUnit: 'Turnkey Residential',
      lastLogin: DateTime(2026, 9, 10, 9, 30),
      joinedDate: DateTime(2024, 1, 12),
    ),
    OrganizationEmployee(
      id: 'EMP-003',
      employeeId: 'HOM-E-1003',
      name: 'Rajesh Verma',
      avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
      workEmail: 'rajesh.v@homio.in',
      workPhone: '+91 98112 33455',
      jobTitle: 'VP - Site Turnkey Execution',
      departmentId: 'DEPT-EXEC',
      departmentName: 'Turnkey Site Execution',
      teamId: null,
      teamName: 'Operations Leadership',
      managerId: null,
      managerName: 'Board of Directors',
      roleId: 'ROLE-SUPER-ADMIN',
      roleTitle: 'Super Administrator',
      roleType: RoleType.system,
      employmentStatus: EmploymentStatus.fullTime,
      accountStatus: AccountStatus.active,
      accessScopeId: 'SCOPE-ORG-WIDE',
      accessScopeName: 'Organization-Wide',
      branch: 'Bangalore Central Hub',
      businessUnit: 'Turnkey Civil Construction',
      lastLogin: DateTime(2026, 9, 10, 11, 45),
      joinedDate: DateTime(2024, 1, 15),
    ),
    OrganizationEmployee(
      id: 'EMP-004',
      employeeId: 'HOM-E-1004',
      name: 'Rohan Mehra',
      avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
      workEmail: 'rohan.m@homio.in',
      workPhone: '+91 98102 33441',
      jobTitle: 'Senior Sales Closer & Lead',
      departmentId: 'DEPT-SALES',
      departmentName: 'Sales & Consultations',
      teamId: 'TEAM-SALES-ALPHA',
      teamName: 'Sales Squad Alpha (North Bangalore)',
      managerId: 'EMP-001',
      managerName: 'Vikram Malhotra',
      roleId: 'ROLE-SALES-MGR',
      roleTitle: 'Sales Manager',
      roleType: RoleType.system,
      employmentStatus: EmploymentStatus.fullTime,
      accountStatus: AccountStatus.active,
      accessScopeId: 'SCOPE-TEAM-WIDE',
      accessScopeName: 'Team-Wide Scope',
      branch: 'Indiranagar Hub',
      businessUnit: 'Turnkey Residential',
      lastLogin: DateTime(2026, 9, 10, 12, 10),
      joinedDate: DateTime(2024, 3, 1),
    ),
    OrganizationEmployee(
      id: 'EMP-005',
      employeeId: 'HOM-E-1005',
      name: 'Sneha Patel',
      avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
      workEmail: 'sneha.p@homio.in',
      workPhone: '+91 98441 22330',
      jobTitle: 'Lead Inbound SDR Specialist',
      departmentId: 'DEPT-SALES',
      departmentName: 'Sales & Consultations',
      teamId: 'TEAM-SALES-TELE',
      teamName: 'Inbound SDR & Telecalling Pool',
      managerId: 'EMP-001',
      managerName: 'Vikram Malhotra',
      roleId: 'ROLE-SALES-SDR',
      roleTitle: 'Inbound Telecaller / SDR',
      roleType: RoleType.system,
      employmentStatus: EmploymentStatus.fullTime,
      accountStatus: AccountStatus.active,
      accessScopeId: 'SCOPE-MY-LEADS',
      accessScopeName: 'My Leads Only',
      branch: 'Bangalore Central Hub',
      businessUnit: 'Turnkey Residential',
      lastLogin: DateTime(2026, 9, 10, 14, 20),
      joinedDate: DateTime(2024, 6, 15),
    ),
    OrganizationEmployee(
      id: 'EMP-006',
      employeeId: 'HOM-E-1006',
      name: 'Tarun Saxena',
      avatarUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150',
      workEmail: 'tarun.s@homio.in',
      workPhone: '+91 98331 99882',
      jobTitle: 'Senior Architectural Visualizer',
      departmentId: 'DEPT-DESIGN',
      departmentName: 'Design & Architecture',
      teamId: 'TEAM-DES-CONCEPT',
      teamName: 'Concept Architecture & 3D Visualizer',
      managerId: 'EMP-002',
      managerName: 'Ananya Roy',
      roleId: 'ROLE-DES-LEAD',
      roleTitle: 'Senior Interior Architect',
      roleType: RoleType.system,
      employmentStatus: EmploymentStatus.fullTime,
      accountStatus: AccountStatus.active,
      accessScopeId: 'SCOPE-TEAM-WIDE',
      accessScopeName: 'Team-Wide Scope',
      branch: 'Whitefield Design Studio',
      businessUnit: 'Design Studio',
      lastLogin: DateTime(2026, 9, 10, 8, 45),
      joinedDate: DateTime(2024, 2, 20),
    ),
    OrganizationEmployee(
      id: 'EMP-007',
      employeeId: 'HOM-E-1007',
      name: 'Manoj Kumar',
      avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150',
      workEmail: 'manoj.k@homio.in',
      workPhone: '+91 98110 88771',
      jobTitle: 'Turnkey Project Manager',
      departmentId: 'DEPT-EXEC',
      departmentName: 'Turnkey Site Execution',
      teamId: 'TEAM-EXEC-NORTH',
      teamName: 'Site Turnkey Squad - North Hub',
      managerId: 'EMP-003',
      managerName: 'Rajesh Verma',
      roleId: 'ROLE-PROJ-MGR',
      roleTitle: 'Project Manager (Turnkey)',
      roleType: RoleType.system,
      employmentStatus: EmploymentStatus.fullTime,
      accountStatus: AccountStatus.active,
      accessScopeId: 'SCOPE-TEAM-WIDE',
      accessScopeName: 'Team-Wide Scope',
      branch: 'Hebbal Site Office',
      businessUnit: 'Turnkey Civil Construction',
      lastLogin: DateTime(2026, 9, 10, 7, 50),
      joinedDate: DateTime(2024, 4, 10),
    ),
    OrganizationEmployee(
      id: 'EMP-008',
      employeeId: 'HOM-E-1008',
      name: 'Bipin Rawat',
      avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
      workEmail: 'bipin.r@homio.in',
      workPhone: '+91 98221 44556',
      jobTitle: 'Lead QA & Snag Inspector',
      departmentId: 'DEPT-EXEC',
      departmentName: 'Turnkey Site Execution',
      teamId: 'TEAM-EXEC-QA',
      teamName: 'Quality Audit & Snag Prevention',
      managerId: 'EMP-003',
      managerName: 'Rajesh Verma',
      roleId: 'ROLE-CUSTOM-BRANCH-AUDITOR',
      roleTitle: 'Regional Branch Auditor (Custom)',
      roleType: RoleType.custom,
      employmentStatus: EmploymentStatus.fullTime,
      accountStatus: AccountStatus.active,
      accessScopeId: 'SCOPE-DEPT-WIDE',
      accessScopeName: 'Department Scope',
      branch: 'Bangalore Central Hub',
      businessUnit: 'Turnkey Civil Construction',
      lastLogin: DateTime(2026, 9, 9, 17, 30),
      joinedDate: DateTime(2024, 5, 12),
    ),
    OrganizationEmployee(
      id: 'EMP-009',
      employeeId: 'HOM-E-1009',
      name: 'Ravi Teja',
      avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150',
      workEmail: 'ravi.t@homio.in',
      workPhone: '+91 98451 77889',
      jobTitle: 'Junior Site Coordinator',
      departmentId: 'DEPT-EXEC',
      departmentName: 'Turnkey Site Execution',
      teamId: 'TEAM-EXEC-NORTH',
      teamName: 'Site Turnkey Squad - North Hub',
      managerId: 'EMP-007',
      managerName: 'Manoj Kumar',
      roleId: 'ROLE-SITE-SUP',
      roleTitle: 'Site Supervisor',
      roleType: RoleType.system,
      employmentStatus: EmploymentStatus.probation,
      accountStatus: AccountStatus.pendingActivation,
      accessScopeId: 'SCOPE-ASSIGNED',
      accessScopeName: 'Assigned Records',
      branch: 'Hebbal Site Office',
      businessUnit: 'Turnkey Civil Construction',
      lastLogin: null,
      joinedDate: DateTime(2026, 8, 1),
    ),
    OrganizationEmployee(
      id: 'EMP-010',
      employeeId: 'HOM-E-1010',
      name: 'Kavita Chawla',
      avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150',
      workEmail: 'kavita.c@homio.in',
      workPhone: '+91 98119 66554',
      jobTitle: 'Junior 3D Modeller',
      departmentId: 'DEPT-DESIGN',
      departmentName: 'Design & Architecture',
      teamId: 'TEAM-DES-CONCEPT',
      teamName: 'Concept Architecture & 3D Visualizer',
      managerId: 'EMP-006',
      managerName: 'Tarun Saxena',
      roleId: 'ROLE-DES-3D',
      roleTitle: '3D Visualizer / BIM Modeller',
      roleType: RoleType.system,
      employmentStatus: EmploymentStatus.contract,
      accountStatus: AccountStatus.suspended,
      accessScopeId: 'SCOPE-ASSIGNED',
      accessScopeName: 'Assigned Records',
      branch: 'Whitefield Design Studio',
      businessUnit: 'Design Studio',
      lastLogin: DateTime(2026, 7, 28, 14, 10),
      joinedDate: DateTime(2025, 3, 1),
    ),
  ];

  // ---------------------------------------------------------------------------
  // 7. Organization Audit Trail Logs
  // ---------------------------------------------------------------------------
  static final List<OrganizationAuditLog> auditLogs = [
    OrganizationAuditLog(
      id: 'AUD-001',
      entityType: 'Employee Assignment',
      entityId: 'EMP-004',
      entityName: 'Rohan Mehra',
      action: 'Role Promoted',
      changedBy: 'Vikram Malhotra (Head of Sales)',
      previousValue: 'Sales Executive (SCOPE-ASSIGNED)',
      newValue: 'Sales Manager (SCOPE-TEAM-WIDE)',
      timestamp: DateTime(2026, 8, 20, 14, 30),
      reason: 'Promoted to lead Sales Squad Alpha following Q2 quota over-achievement.',
    ),
    OrganizationAuditLog(
      id: 'AUD-002',
      entityType: 'Department Structure',
      entityId: 'DEPT-SERVICE',
      entityName: 'After-Sales & Warranty Service',
      action: 'Parent Reassigned',
      changedBy: 'Rajesh Verma (Super Admin)',
      previousValue: 'Standalone Department',
      newValue: 'Parent: Operations & Supply Chain (DEPT-OPS)',
      timestamp: DateTime(2026, 8, 18, 11, 15),
      reason: 'Integrated under central operations for unified procurement and logistics.',
    ),
    OrganizationAuditLog(
      id: 'AUD-003',
      entityType: 'Role Definition',
      entityId: 'ROLE-CUSTOM-BRANCH-AUDITOR',
      entityName: 'Regional Branch Auditor (Custom)',
      action: 'Permission Added',
      changedBy: 'Rajesh Verma (Super Admin)',
      previousValue: 'proj.view, fin.view',
      newValue: 'Added: proj.export, fin.export',
      timestamp: DateTime(2026, 8, 11, 16, 45),
      reason: 'Authorized independent offline audit reconciliation reports.',
    ),
    OrganizationAuditLog(
      id: 'AUD-004',
      entityType: 'Access Scope',
      entityId: 'SCOPE-MY-LEADS',
      entityName: 'My Inbound Leads & Tasks Only',
      action: 'Isolation Enforced',
      changedBy: 'Shalini Kapoor (HR Head)',
      previousValue: 'Included team-level lead visibility',
      newValue: 'Strict isolation: Own records only',
      timestamp: DateTime(2026, 8, 1, 9, 0),
      reason: 'Prevented telecaller lead poaching across shift handovers.',
    ),
    OrganizationAuditLog(
      id: 'AUD-005',
      entityType: 'Employee Account',
      entityId: 'EMP-010',
      entityName: 'Kavita Chawla',
      action: 'Account Suspended',
      changedBy: 'Ananya Roy (Head of Design)',
      previousValue: 'Active',
      newValue: 'Suspended',
      timestamp: DateTime(2026, 7, 28, 15, 0),
      reason: 'Contract hiatus pending project pipeline review in September.',
    ),
  ];

  // ---------------------------------------------------------------------------
  // 8. Evaluation Helper: Compute Effective Access Summary for Employee
  // ---------------------------------------------------------------------------
  static EffectiveAccessSummary getEffectiveAccessForEmployee(OrganizationEmployee emp) {
    final role = roles.firstWhere((r) => r.id == emp.roleId, orElse: () => roles.first);
    final scope = accessScopes.firstWhere((s) => s.id == emp.accessScopeId, orElse: () => accessScopes.first);

    // Group permissions by module
    final Map<PermissionModule, List<OrganizationPermission>> map = {};
    for (final p in permissions) {
      if (role.permissionIds.contains(p.code)) {
        map.putIfAbsent(p.module, () => []).add(p);
      }
    }

    final hasAdmin = role.permissionIds.contains('admin.rbac.manage') || role.roleCode == 'SUPER_ADMIN';

    final buffer = StringBuffer();
    buffer.write('${emp.name} has the role "${role.roleTitle}" with "${scope.name}" access. ');
    if (hasAdmin) {
      buffer.write('User possesses full administrative privileges across system configuration, tenant security, and RBAC governance.');
    } else {
      buffer.write('They are permitted to operate on ${map.keys.map((k) => k.displayName).join(", ")}. ');
      buffer.write('Their data visibility boundary is strictly scoped to: ${scope.description}');
    }

    return EffectiveAccessSummary(
      employeeId: emp.id,
      employeeName: emp.name,
      roleTitle: role.roleTitle,
      scopeName: scope.name,
      humanReadableSummary: buffer.toString(),
      permissionsByModule: map,
      hasAdminPrivileges: hasAdmin,
    );
  }
}
