import 'execution_models.dart';

/// Centralized production-grade mock data repository for Project Execution (Module 5).
class ExecutionMockData {
  // ---------------------------------------------------------------------------
  // Master Projects with Comprehensive WBS, Media, Snags, Stages, Ratings, Ledgers
  // ---------------------------------------------------------------------------
  static final List<ProjectMaster> projects = [
    // -------------------------------------------------------------------------
    // PROJECT 1: DLF The Camellias (Turnkey Contract)
    // -------------------------------------------------------------------------
    ProjectMaster(
      id: 'PRJ-104',
      projectCode: 'PRJ-104',
      projectTitle: 'DLF The Camellias - 4BHK Duplex Penthouse',
      clientName: 'Vikram Malhotra',
      clientPhone: '+91 98112 33445',
      clientEmail: 'vikram.malhotra@apexholdings.in',
      siteAddress: 'Penthouse 24B, Golf Course Road',
      city: 'Gurgaon, NCR',
      floorAreaSqft: 4800.0,
      projectManagerName: 'Rohit Deshmukh',
      siteSupervisorName: 'Sanjay Rawat',
      startDate: DateTime.now().subtract(const Duration(days: 42)),
      targetHandoverDate: DateTime.now().add(const Duration(days: 38)),
      status: ProjectStatus.inExecution,
      timelineHealth: TimelineHealth.onTime,
      contractModel: ContractModel.turnkeyContract,
      totalContractValue: 3500000.0,
      totalBilled: 2100000.0,
      totalPaid: 1925000.0,
      totalDesignFiles: 24,
      completedDesignFiles: 24,
      averageCsatRating: 4.9,
      milestones: [
        MilestoneWorkStream(
          id: 'MS-104-01',
          projectId: 'PRJ-104',
          name: '1. 2D CAD & 3D Design Approvals',
          startDate: DateTime.now().subtract(const Duration(days: 42)),
          endDate: DateTime.now().subtract(const Duration(days: 28)),
          completionPercentage: 1.0,
          isApprovedByClient: true,
          clientOtpSignoffDate: '12/08/2026 (OTP: 884129)',
          tasks: [
            WbsTask(
              id: 'TSK-104-01',
              milestoneId: 'MS-104-01',
              title: 'Site Laser Measurement & As-Built Verification',
              scopeDescription: 'Accurate laser distance survey for all 4 bedrooms, double-height living room & terrace',
              originalTargetDate: DateTime.now().subtract(const Duration(days: 40)),
              currentDueDate: DateTime.now().subtract(const Duration(days: 40)),
              assigneeName: 'Praveen Kumar',
              assigneeRole: 'Survey Engineer',
              priority: TaskPriority.high,
              isCompleted: true,
              checklistItems: ['Laser measurements verified', 'Plumbing duct checks', 'Ceiling level mapping'],
              checklistChecked: [true, true, true],
            ),
            WbsTask(
              id: 'TSK-104-02',
              milestoneId: 'MS-104-01',
              title: '3D Photorealistic Render Approval',
              scopeDescription: 'Client presentation of luxury Italian marble and bespoke wood panelling',
              originalTargetDate: DateTime.now().subtract(const Duration(days: 30)),
              currentDueDate: DateTime.now().subtract(const Duration(days: 30)),
              assigneeName: 'Ananya Roy',
              assigneeRole: 'Lead Architect',
              priority: TaskPriority.urgent,
              isCompleted: true,
              checklistItems: ['Living room 3D signoff', 'Master suite walk-in wardrobe', 'Gourmet kitchen renders'],
              checklistChecked: [true, true, true],
            ),
          ],
        ),
        MilestoneWorkStream(
          id: 'MS-104-02',
          projectId: 'PRJ-104',
          name: '2. Civil Demolition & Core MEP Rough-in',
          startDate: DateTime.now().subtract(const Duration(days: 27)),
          endDate: DateTime.now().subtract(const Duration(days: 14)),
          completionPercentage: 1.0,
          isApprovedByClient: true,
          clientOtpSignoffDate: '26/08/2026 (OTP: 914502)',
          tasks: [
            WbsTask(
              id: 'TSK-104-03',
              milestoneId: 'MS-104-02',
              title: 'HVAC Concealed Copper Piping & Core Cutting',
              scopeDescription: 'Daikin VRV indoor unit core drilling and insulated copper pipe routing',
              originalTargetDate: DateTime.now().subtract(const Duration(days: 22)),
              currentDueDate: DateTime.now().subtract(const Duration(days: 22)),
              assigneeName: 'Rajesh HVAC Services',
              assigneeRole: 'MEP Contractor',
              priority: TaskPriority.urgent,
              isCompleted: true,
              checklistItems: ['Pressure test 400 PSI passed', 'Drain slope 1:100 checked', 'Condensate insulation'],
              checklistChecked: [true, true, true],
            ),
            WbsTask(
              id: 'TSK-104-04',
              milestoneId: 'MS-104-02',
              title: 'Electrical Concealed Conduiting & Distribution Boards',
              scopeDescription: 'Schneider Electric AvatarOn conduit chasing in brick masonry with Finolex FRLS wires',
              originalTargetDate: DateTime.now().subtract(const Duration(days: 16)),
              currentDueDate: DateTime.now().subtract(const Duration(days: 14)),
              assigneeName: 'Manoj Electrician',
              assigneeRole: 'Master Electrician',
              priority: TaskPriority.high,
              isCompleted: true,
              isRescheduled: true,
              rescheduleReason: 'Client added 12 additional dimmable automation circuits in living pavilion',
              rescheduledAt: DateTime.now().subtract(const Duration(days: 18)),
              checklistItems: ['DB phase balancing', 'Earthing resistance < 2 ohms', 'Automation bus wire routed'],
              checklistChecked: [true, true, true],
            ),
          ],
        ),
        MilestoneWorkStream(
          id: 'MS-104-03',
          projectId: 'PRJ-104',
          name: '3. False Ceiling & POP Decorative Coves',
          startDate: DateTime.now().subtract(const Duration(days: 13)),
          endDate: DateTime.now().add(const Duration(days: 2)),
          completionPercentage: 0.90,
          isApprovedByClient: false,
          tasks: [
            WbsTask(
              id: 'TSK-104-05',
              milestoneId: 'MS-104-03',
              title: 'Saint-Gobain Gyproc Framing & Level Alignment',
              scopeDescription: 'Perimeter GI channel framing with water-level verification across 4800 sqft',
              originalTargetDate: DateTime.now().subtract(const Duration(days: 5)),
              currentDueDate: DateTime.now().subtract(const Duration(days: 5)),
              assigneeName: 'Ramu Gypsum Team',
              assigneeRole: 'False Ceiling Supervisor',
              priority: TaskPriority.high,
              isCompleted: true,
              checklistItems: ['Grid spacing 400mm max', 'Fasteners torque verified', 'AC grill cutouts framed'],
              checklistChecked: [true, true, true],
            ),
            WbsTask(
              id: 'TSK-104-06',
              milestoneId: 'MS-104-03',
              title: 'Plaster of Paris (POP) Punning & Cove Lighting Grooves',
              scopeDescription: 'Smooth finish punning with concealed LED strip channels in perimeter coves',
              originalTargetDate: DateTime.now().add(const Duration(days: 2)),
              currentDueDate: DateTime.now().add(const Duration(days: 2)),
              assigneeName: 'Ramu Gypsum Team',
              assigneeRole: 'False Ceiling Specialist',
              priority: TaskPriority.urgent,
              isCompleted: false,
              checklistItems: ['Seamless joint taping', 'Primer coat applied', 'Cove profile aligned'],
              checklistChecked: [true, false, false],
            ),
          ],
        ),
        MilestoneWorkStream(
          id: 'MS-104-04',
          projectId: 'PRJ-104',
          name: '4. Carpentry, Wardrobes & Modular Kitchen Carcass',
          startDate: DateTime.now().subtract(const Duration(days: 5)),
          endDate: DateTime.now().add(const Duration(days: 20)),
          completionPercentage: 0.45,
          isApprovedByClient: false,
          tasks: [
            WbsTask(
              id: 'TSK-104-07',
              milestoneId: 'MS-104-04',
              title: 'Master Wardrobe BWP 710 Plywood Carcass Erection',
              scopeDescription: 'Century Club Prime Marine plywood assembly with 2mm PVC edge banding',
              originalTargetDate: DateTime.now().add(const Duration(days: 4)),
              currentDueDate: DateTime.now().add(const Duration(days: 8)),
              assigneeName: 'Dinesh Sharma',
              assigneeRole: 'Senior Carpenter',
              priority: TaskPriority.high,
              isCompleted: false,
              isRescheduled: true,
              rescheduleReason: 'Vendor delayed hardware shipment of Hafele soft-close sliding tracks',
              rescheduledAt: DateTime.now().subtract(const Duration(days: 2)),
              checklistItems: ['Carcass plumb & right angle verified', 'Internal laminate pressed', 'Leveling legs tuned'],
              checklistChecked: [true, true, false],
            ),
            WbsTask(
              id: 'TSK-104-08',
              milestoneId: 'MS-104-04',
              title: 'Modular Kitchen Blum Drawer Runner Alignment',
              scopeDescription: 'Installation of 8 Blum Legrabox soft-close drawer sets with 50kg capacity',
              originalTargetDate: DateTime.now().add(const Duration(days: 14)),
              currentDueDate: DateTime.now().add(const Duration(days: 14)),
              assigneeName: 'Mohan Modulars',
              assigneeRole: 'Kitchen Specialist',
              priority: TaskPriority.medium,
              isCompleted: false,
              checklistItems: ['Runner sync checked', 'Gap tolerance < 1.5mm', 'Cutlery tray inserts fitted'],
              checklistChecked: [false, false, false],
            ),
          ],
        ),
        MilestoneWorkStream(
          id: 'MS-104-05',
          projectId: 'PRJ-104',
          name: '5. Painting, PU Polish & Deep Cleaning',
          startDate: DateTime.now().add(const Duration(days: 21)),
          endDate: DateTime.now().add(const Duration(days: 34)),
          completionPercentage: 0.0,
          isApprovedByClient: false,
          tasks: [
            WbsTask(
              id: 'TSK-104-09',
              milestoneId: 'MS-104-05',
              title: 'Asian Paints Royale Luxury Emulsion 3-Coat Application',
              scopeDescription: 'Birla White putty with 3 coats of Asian Paints Royale Matte with Teflon surface protector',
              originalTargetDate: DateTime.now().add(const Duration(days: 28)),
              currentDueDate: DateTime.now().add(const Duration(days: 28)),
              assigneeName: 'Pankaj Painters',
              assigneeRole: 'Painting Contractor',
              priority: TaskPriority.medium,
              isCompleted: false,
              checklistItems: ['Surface sanding grit 320', 'Masking tape protection', 'Roll marks inspection'],
              checklistChecked: [false, false, false],
            ),
          ],
        ),
        MilestoneWorkStream(
          id: 'MS-104-06',
          projectId: 'PRJ-104',
          name: '6. Snag Resolution & Final Client Handover',
          startDate: DateTime.now().add(const Duration(days: 35)),
          endDate: DateTime.now().add(const Duration(days: 38)),
          completionPercentage: 0.0,
          isApprovedByClient: false,
          tasks: [
            WbsTask(
              id: 'TSK-104-10',
              milestoneId: 'MS-104-06',
              title: 'Comprehensive 150-Point QC Audit & Key Handover',
              scopeDescription: 'Senior QA engineer walkthrough, warranty dossier handover & client satisfaction sign-off',
              originalTargetDate: DateTime.now().add(const Duration(days: 38)),
              currentDueDate: DateTime.now().add(const Duration(days: 38)),
              assigneeName: 'Rohit Deshmukh',
              assigneeRole: 'Project Manager',
              priority: TaskPriority.urgent,
              isCompleted: false,
              checklistItems: ['Appliance testing', 'Deep chemical cleaning', 'Key handover gift box'],
              checklistChecked: [false, false, false],
            ),
          ],
        ),
      ],
      mediaLogs: [
        SiteMediaLog(
          id: 'MED-104-01',
          projectId: 'PRJ-104',
          projectTitle: 'DLF The Camellias - 4BHK Penthouse',
          milestoneName: 'False Ceiling & POP Coves',
          title: 'Perimeter Cove Level Laser Check & Philips Strip Fitting',
          description: 'Supervisor inspection video showing seamless Saint-Gobain ceiling board jointing and warm LED illumination test.',
          mediaUrl: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=1200&q=80',
          thumbnailUrl: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=400&q=80',
          isVideo: true,
          durationText: '02:15',
          recordedAt: DateTime.now().subtract(const Duration(hours: 3)),
          supervisorName: 'Sanjay Rawat',
          workerCountOnSite: 9,
          weatherCondition: 'Sunny 30°C',
          gpsCoordinates: '28.4595° N, 77.0266° E (Gurgaon)',
          isGpsVerified: true,
        ),
        SiteMediaLog(
          id: 'MED-104-02',
          projectId: 'PRJ-104',
          projectTitle: 'DLF The Camellias - 4BHK Penthouse',
          milestoneName: 'Carpentry & Wardrobes',
          title: 'Century BWP Plywood Delivery & Thickness Gauge Audit',
          description: 'Unloading of 45 sheets of Century Club Prime 19mm marine ply. Vernier calliper verified 19.2mm calibrated thickness.',
          mediaUrl: 'https://images.unsplash.com/photo-1595428774223-ef52624120d2?w=1200&q=80',
          thumbnailUrl: 'https://images.unsplash.com/photo-1595428774223-ef52624120d2?w=400&q=80',
          isVideo: false,
          durationText: 'Photo',
          recordedAt: DateTime.now().subtract(const Duration(days: 1, hours: 2)),
          supervisorName: 'Sanjay Rawat',
          workerCountOnSite: 7,
          weatherCondition: 'Clear Sky 28°C',
          gpsCoordinates: '28.4595° N, 77.0266° E (Gurgaon)',
          isGpsVerified: true,
        ),
        SiteMediaLog(
          id: 'MED-104-03',
          projectId: 'PRJ-104',
          projectTitle: 'DLF The Camellias - 4BHK Penthouse',
          milestoneName: 'Civil Demolition & Core MEP',
          title: 'Daikin VRV Copper Pressure Testing (400 PSI nitrogen holding)',
          description: 'Digital manifold gauge reading 412 PSI stable after 48-hour pressure hold test across living and bedroom zones.',
          mediaUrl: 'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=1200&q=80',
          thumbnailUrl: 'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=400&q=80',
          isVideo: true,
          durationText: '01:45',
          recordedAt: DateTime.now().subtract(const Duration(days: 14)),
          supervisorName: 'Sanjay Rawat',
          workerCountOnSite: 11,
          weatherCondition: 'Sunny 32°C',
          gpsCoordinates: '28.4595° N, 77.0266° E (Gurgaon)',
          isGpsVerified: true,
        ),
      ],
      snags: [
        SnagTicket(
          id: 'SNG-104-01',
          ticketNumber: 'SNG-104-01',
          projectId: 'PRJ-104',
          projectTitle: 'DLF The Camellias - 4BHK Penthouse',
          roomArea: 'Living Room East Cove',
          category: SnagCategory.qualityDefect,
          description: 'Minor wave distortion visible in the false ceiling pop cove under grazing spotlight angle.',
          priority: TaskPriority.high,
          status: SnagStatus.inProgress,
          raisedAt: DateTime.now().subtract(const Duration(hours: 18)),
          slaDeadline: DateTime.now().add(const Duration(hours: 30)),
          raisedBy: 'Vikram Malhotra (Client via Portal)',
          assignedTo: 'Sanjay Rawat (Site Supervisor)',
          photoUrls: ['https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=400&q=80'],
          correctiveChecklist: [
            'Light beam grazing test',
            'Re-sand with fine 400 grit emery paper',
            'Touch-up with Asian Paints Royale base primer',
          ],
          checklistDone: [true, false, false],
        ),
        SnagTicket(
          id: 'SNG-104-02',
          ticketNumber: 'SNG-104-02',
          projectId: 'PRJ-104',
          projectTitle: 'DLF The Camellias - 4BHK Penthouse',
          roomArea: 'Master Bedroom Wardrobe',
          category: SnagCategory.materialDeviation,
          description: 'Internal laminate shade installed is Off-White instead of specified Fabric Textured Grey (Merino 2104).',
          priority: TaskPriority.urgent,
          status: SnagStatus.open,
          raisedAt: DateTime.now().subtract(const Duration(hours: 8)),
          slaDeadline: DateTime.now().add(const Duration(hours: 40)),
          raisedBy: 'Rohit Deshmukh (Project Manager)',
          assignedTo: 'Dinesh Sharma (Carpenter Lead)',
          photoUrls: ['https://images.unsplash.com/photo-1595428774223-ef52624120d2?w=400&q=80'],
          correctiveChecklist: [
            'Verify architect drawing code',
            'Order replacement Merino 2104 laminate sheets',
            'Press replacement laminate over carcass before client review',
          ],
          checklistDone: [true, false, false],
        ),
        SnagTicket(
          id: 'SNG-104-03',
          ticketNumber: 'SNG-104-03',
          projectId: 'PRJ-104',
          projectTitle: 'DLF The Camellias - 4BHK Penthouse',
          roomArea: 'Double Height Foyer',
          category: SnagCategory.siteCleanliness,
          description: 'Dust accumulation on newly laid Armani Grey Italian marble slabs during POP work.',
          priority: TaskPriority.medium,
          status: SnagStatus.resolvedOnTime,
          raisedAt: DateTime.now().subtract(const Duration(days: 3)),
          slaDeadline: DateTime.now().subtract(const Duration(days: 2)),
          raisedBy: 'Rohit Deshmukh (PM)',
          assignedTo: 'Sanjay Rawat',
          photoUrls: ['https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=400&q=80'],
          correctiveChecklist: [
            'Dry vacuum cleaning',
            '3mm protective foam padding',
            'Corrugated sheet masking with reinforced tape',
          ],
          checklistDone: [true, true, true],
          resolutionNotes: 'Marble protected with 3mm high-density foam and heavy corrugated flute sheets.',
          resolvedAt: DateTime.now().subtract(const Duration(days: 2)),
        ),
      ],
      stageApprovals: [
        StageApprovalRequest(
          id: 'APR-104-01',
          projectId: 'PRJ-104',
          projectCode: 'PRJ-104',
          projectTitle: 'DLF The Camellias - 4BHK Penthouse',
          clientName: 'Vikram Malhotra',
          clientPhone: '+91 98112 33445',
          milestoneName: 'Milestone 1: 2D Working CAD & 3D Design Approval',
          stageContractShareAmount: 700000.0,
          requestedAt: DateTime.now().subtract(const Duration(days: 28)),
          isApproved: true,
          approvedAt: '12/08/2026 18:20 IST',
          otpSignoffAudit: 'Verified via WhatsApp OTP (884129) • IP: 49.36.112.9 • Device: iPhone 15 Pro',
          inspectionChecklist: [
            'All bedroom 3D renders signed off',
            'Kitchen appliance cutouts confirmed',
            'Lighting plan and switch automation layout approved',
          ],
          completionPhotoUrls: ['https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=600&q=80'],
        ),
        StageApprovalRequest(
          id: 'APR-104-02',
          projectId: 'PRJ-104',
          projectCode: 'PRJ-104',
          projectTitle: 'DLF The Camellias - 4BHK Penthouse',
          clientName: 'Vikram Malhotra',
          clientPhone: '+91 98112 33445',
          milestoneName: 'Milestone 2: Civil Demolition & Core MEP Rough-in',
          stageContractShareAmount: 700000.0,
          requestedAt: DateTime.now().subtract(const Duration(days: 14)),
          isApproved: true,
          approvedAt: '26/08/2026 14:32 IST',
          otpSignoffAudit: 'Verified via WhatsApp OTP (914502) • IP: 49.36.112.9 • Device: iPhone 15 Pro',
          inspectionChecklist: [
            'All partition demolition cleared and debris disposed',
            'Plumbing pressure test verified (400 PSI)',
            'VRV copper piping gas-tested without pressure drop',
          ],
          completionPhotoUrls: ['https://images.unsplash.com/photo-1541888946425-d0fbb186f5f7?w=600&q=80'],
        ),
        StageApprovalRequest(
          id: 'APR-104-03',
          projectId: 'PRJ-104',
          projectCode: 'PRJ-104',
          projectTitle: 'DLF The Camellias - 4BHK Penthouse',
          clientName: 'Vikram Malhotra',
          clientPhone: '+91 98112 33445',
          milestoneName: 'Milestone 3: False Ceiling & Decorative POP (90% Ready)',
          stageContractShareAmount: 700000.0,
          requestedAt: DateTime.now().subtract(const Duration(hours: 14)),
          isApproved: false,
          inspectionChecklist: [
            '100% Perimeter GI channels level-aligned with water level',
            'Fire-retardant Gypboard 12.5mm installed',
            'Concealed Philips COB light wiring tested',
            'Air-conditioning linear supply grills framed',
          ],
          completionPhotoUrls: [
            'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=600&q=80',
            'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=600&q=80',
          ],
        ),
        StageApprovalRequest(
          id: 'APR-104-04',
          projectId: 'PRJ-104',
          projectCode: 'PRJ-104',
          projectTitle: 'DLF The Camellias - 4BHK Penthouse',
          clientName: 'Vikram Malhotra',
          clientPhone: '+91 98112 33445',
          milestoneName: 'Milestone 4: Carpentry Carcass & Modular Woodwork',
          stageContractShareAmount: 700000.0,
          requestedAt: DateTime.now().add(const Duration(days: 15)),
          isApproved: false,
          inspectionChecklist: [
            'Marine BWP plywood carcass squareness check',
            'Hafele soft close drawer runners test',
            'Veneer sheet matching signoff',
          ],
          completionPhotoUrls: ['https://images.unsplash.com/photo-1595428774223-ef52624120d2?w=600&q=80'],
        ),
        StageApprovalRequest(
          id: 'APR-104-05',
          projectId: 'PRJ-104',
          projectCode: 'PRJ-104',
          projectTitle: 'DLF The Camellias - 4BHK Penthouse',
          clientName: 'Vikram Malhotra',
          clientPhone: '+91 98112 33445',
          milestoneName: 'Milestone 5: Final Painting, Snag Rectification & Handover',
          stageContractShareAmount: 700000.0,
          requestedAt: DateTime.now().add(const Duration(days: 35)),
          isApproved: false,
          inspectionChecklist: [
            '3 coats Royale Luxury emulsion visual inspection',
            '150-point QA checklist defect clearance',
            'All keys, warranty dossiers, and appliance manuals handed over',
          ],
          completionPhotoUrls: [],
        ),
      ],
      ratings: [
        StakeholderRating(
          id: 'RAT-104-01',
          projectId: 'PRJ-104',
          projectTitle: 'DLF The Camellias',
          stakeholderType: StakeholderType.supervisor,
          targetName: 'Sanjay Rawat (Site Supervisor)',
          score1: 5.0,
          label1: 'Daily Site Updates & Video Frequency',
          score2: 4.8,
          label2: 'Client Communication & Behaviour',
          score3: 4.9,
          label3: 'On-Site Availability & Contractor Coordination',
          reviewNote: 'Sanjay is exceptionally punctual and uploads 4K video walkthroughs twice every day without fail.',
          ratedAt: DateTime.now().subtract(const Duration(days: 2)),
          ratedBy: 'Vikram Malhotra (Client CSAT Survey)',
        ),
        StakeholderRating(
          id: 'RAT-104-02',
          projectId: 'PRJ-104',
          projectTitle: 'DLF The Camellias',
          stakeholderType: StakeholderType.labour,
          targetName: 'Dinesh Sharma & Team (Carpentry Contractor)',
          score1: 4.6,
          label1: 'Milestone Timeline Adherence',
          score2: 4.9,
          label2: 'Craftsmanship & Carcass Joinery Quality',
          score3: 4.7,
          label3: 'Site Safety & Professional Conduct',
          reviewNote: 'Immaculate mitre cuts and edge banding finish. Rehau glue line is completely invisible.',
          ratedAt: DateTime.now().subtract(const Duration(days: 4)),
          ratedBy: 'Rohit Deshmukh (Project Manager)',
        ),
        StakeholderRating(
          id: 'RAT-104-03',
          projectId: 'PRJ-104',
          projectTitle: 'DLF The Camellias',
          stakeholderType: StakeholderType.materialVendor,
          targetName: 'CenturyPly Official Distribution Depot',
          score1: 5.0,
          label1: 'Price Competitiveness & Invoice Transparency',
          score2: 4.5,
          label2: 'Delivery SLA Compliance',
          score3: 5.0,
          label3: 'BWP Grade Certification & Warranty Dossier',
          reviewNote: 'Delivered direct from factory depot with genuine QR code verification barcodes on every sheet.',
          ratedAt: DateTime.now().subtract(const Duration(days: 6)),
          ratedBy: 'Sanjay Rawat (Supervisor)',
        ),
        StakeholderRating(
          id: 'RAT-104-04',
          projectId: 'PRJ-104',
          projectTitle: 'DLF The Camellias',
          stakeholderType: StakeholderType.designer,
          targetName: 'Ananya Roy (Principal Architect)',
          score1: 5.0,
          label1: 'Design Aesthetics & Space Innovation',
          score2: 4.9,
          label2: 'Working Drawing Technical Accuracy',
          score3: 5.0,
          label3: 'Client Collaboration & Listening Skills',
          reviewNote: 'Ananya translated our moodboard into a world-class architectural masterpiece.',
          ratedAt: DateTime.now().subtract(const Duration(days: 12)),
          ratedBy: 'Vikram & Radhika Malhotra (Homeowners)',
        ),
      ],
      ledgerEntries: [
        FinancialLedgerEntry(
          id: 'LED-104-01',
          projectId: 'PRJ-104',
          projectTitle: 'DLF The Camellias',
          type: LedgerType.material,
          date: DateTime.now().subtract(const Duration(days: 2)),
          payeeOrVendor: 'CenturyPly Depot Gurgaon',
          description: '45 Sheets BWP 710 Club Prime 19mm + 20 Sheets 12mm Marine Ply',
          amount: 284500.0,
          isPaid: true,
          commissionPercent: 4.0,
          commissionAmount: 11380.0,
          note: 'Trade dealer incentive received directly in firm current account',
        ),
        FinancialLedgerEntry(
          id: 'LED-104-02',
          projectId: 'PRJ-104',
          projectTitle: 'DLF The Camellias',
          type: LedgerType.material,
          date: DateTime.now().subtract(const Duration(days: 5)),
          payeeOrVendor: 'Hafele India Gallery',
          description: 'Soft-close tandem drawers, concealed hinges & profile handles',
          amount: 142000.0,
          isPaid: false,
          commissionPercent: 5.0,
          commissionAmount: 7100.0,
          note: 'Payment due on delivery verification tomorrow',
        ),
        FinancialLedgerEntry(
          id: 'LED-104-03',
          projectId: 'PRJ-104',
          projectTitle: 'DLF The Camellias',
          type: LedgerType.labour,
          date: DateTime.now().subtract(const Duration(days: 1)),
          payeeOrVendor: 'Dinesh Sharma (Carpenter)',
          description: 'Weekly running labour bill for bedroom carcass woodwork (5 carpenters x 6 days)',
          amount: 72000.0,
          isPaid: true,
          commissionPercent: 0.0,
          note: 'Signed supervisor attendance log attached',
        ),
        FinancialLedgerEntry(
          id: 'LED-104-04',
          projectId: 'PRJ-104',
          projectTitle: 'DLF The Camellias',
          type: LedgerType.labour,
          date: DateTime.now().subtract(const Duration(days: 7)),
          payeeOrVendor: 'Ramu False Ceiling Works',
          description: 'Final milestone clearance for living room & dining POP framing',
          amount: 54000.0,
          isPaid: true,
          note: 'Deducted Rs. 2,000 for site cleanup negligence on Friday',
        ),
        FinancialLedgerEntry(
          id: 'LED-104-05',
          projectId: 'PRJ-104',
          projectTitle: 'DLF The Camellias',
          type: LedgerType.supervision,
          date: DateTime.now().subtract(const Duration(days: 10)),
          payeeOrVendor: 'Sanjay Rawat (Site Supervisor)',
          description: 'Monthly Site Supervision & Field Execution Allowance',
          amount: 35000.0,
          isPaid: true,
          commissionPercent: 2.0,
          commissionAmount: 18000.0,
          note: 'Zero snag milestone bonus credited',
        ),
      ],
    ),

    // -------------------------------------------------------------------------
    // PROJECT 2: Godrej Woods Tower B (Percentage Model)
    // -------------------------------------------------------------------------
    ProjectMaster(
      id: 'PRJ-105',
      projectCode: 'PRJ-105',
      projectTitle: 'Godrej Woods Tower B - 3BHK Luxury Interior',
      clientName: 'Radhika Singhania',
      clientPhone: '+91 98201 44552',
      clientEmail: 'radhika.singhania@gmail.com',
      siteAddress: 'Flat 1402, Sector 43',
      city: 'Noida, NCR',
      floorAreaSqft: 2250.0,
      projectManagerName: 'Ananya Roy',
      siteSupervisorName: 'Vikas Tyagi',
      startDate: DateTime.now().subtract(const Duration(days: 18)),
      targetHandoverDate: DateTime.now().add(const Duration(days: 52)),
      status: ProjectStatus.inExecution,
      timelineHealth: TimelineHealth.atRisk,
      contractModel: ContractModel.percentageModel,
      totalContractValue: 2450000.0,
      totalBilled: 980000.0,
      totalPaid: 980000.0,
      totalDesignFiles: 18,
      completedDesignFiles: 18,
      averageCsatRating: 4.7,
      milestones: [
        MilestoneWorkStream(
          id: 'MS-105-01',
          projectId: 'PRJ-105',
          name: '1. Civil Masonry & Plumbing Rerouting',
          startDate: DateTime.now().subtract(const Duration(days: 18)),
          endDate: DateTime.now().subtract(const Duration(days: 4)),
          completionPercentage: 1.0,
          isApprovedByClient: true,
          clientOtpSignoffDate: '02/09/2026 (OTP: 552109)',
          tasks: [
            WbsTask(
              id: 'TSK-105-01',
              milestoneId: 'MS-105-01',
              title: 'Kitchen Partition Demolition & Kitchen Island Gas Line Reroute',
              scopeDescription: 'Demolishing 10ft non-load-bearing brick wall to open kitchen into dining foyer',
              originalTargetDate: DateTime.now().subtract(const Duration(days: 12)),
              currentDueDate: DateTime.now().subtract(const Duration(days: 12)),
              assigneeName: 'Santosh Civil Team',
              assigneeRole: 'Masonry Contractor',
              priority: TaskPriority.high,
              isCompleted: true,
              checklistItems: ['Structural column protection', 'IGI gas line diversion signoff', 'Debris cleared'],
              checklistChecked: [true, true, true],
            ),
            WbsTask(
              id: 'TSK-105-02',
              milestoneId: 'MS-105-01',
              title: 'Master Bathroom Concealed Diverter & Drainage Slope',
              scopeDescription: 'Grohe SmartControl concealed thermostat installation with 1:80 wet area slope',
              originalTargetDate: DateTime.now().subtract(const Duration(days: 5)),
              currentDueDate: DateTime.now().subtract(const Duration(days: 4)),
              assigneeName: 'Pappu Plumbers',
              assigneeRole: 'Plumbing Specialist',
              priority: TaskPriority.urgent,
              isCompleted: true,
              checklistItems: ['Waterproofing coat 1 & 2', 'Hydrostatic pressure test', 'Linear floor drain aligned'],
              checklistChecked: [true, true, true],
            ),
          ],
        ),
        MilestoneWorkStream(
          id: 'MS-105-02',
          projectId: 'PRJ-105',
          name: '2. Electrical Rough-in & False Ceiling',
          startDate: DateTime.now().subtract(const Duration(days: 3)),
          endDate: DateTime.now().add(const Duration(days: 14)),
          completionPercentage: 0.40,
          isApprovedByClient: false,
          tasks: [
            WbsTask(
              id: 'TSK-105-03',
              milestoneId: 'MS-105-02',
              title: 'Main DB Conduiting & Finolex FRLS Cabling',
              scopeDescription: 'Heavy-duty 4 sq.mm cabling for 5 air conditioning indoor split units and kitchen',
              originalTargetDate: DateTime.now().add(const Duration(days: 3)),
              currentDueDate: DateTime.now().add(const Duration(days: 6)),
              assigneeName: 'Vikas Tyagi',
              assigneeRole: 'Electrical Supervisor',
              priority: TaskPriority.urgent,
              isCompleted: false,
              isRescheduled: true,
              rescheduleReason: 'Tower maintenance prohibited drilling on Sunday & Monday',
              rescheduledAt: DateTime.now().subtract(const Duration(days: 1)),
              checklistItems: ['Circuit numbering marked', 'Earthing check', 'Chasing plaster seal'],
              checklistChecked: [true, false, false],
            ),
            WbsTask(
              id: 'TSK-105-04',
              milestoneId: 'MS-105-02',
              title: 'Perimeter Gypsum Board Ceiling Framing',
              scopeDescription: 'False ceiling channel framing across all bedrooms with magnetic access panels',
              originalTargetDate: DateTime.now().add(const Duration(days: 12)),
              currentDueDate: DateTime.now().add(const Duration(days: 14)),
              assigneeName: 'Modern False Ceiling',
              assigneeRole: 'Ceiling Specialist',
              priority: TaskPriority.high,
              isCompleted: false,
              checklistItems: ['Water level reference transfer', 'GI channel suspension at 600mm', 'Trapdoor cutouts'],
              checklistChecked: [false, false, false],
            ),
          ],
        ),
        MilestoneWorkStream(
          id: 'MS-105-03',
          projectId: 'PRJ-105',
          name: '3. Kitchen & Wardrobe Joinery',
          startDate: DateTime.now().add(const Duration(days: 15)),
          endDate: DateTime.now().add(const Duration(days: 35)),
          completionPercentage: 0.0,
          isApprovedByClient: false,
          tasks: [
            WbsTask(
              id: 'TSK-105-05',
              milestoneId: 'MS-105-03',
              title: 'Acrylic Finish Kitchen Carcass Erection',
              scopeDescription: 'Boiling Waterproof marine ply modular kitchen with Hettich Atira soft close runners',
              originalTargetDate: DateTime.now().add(const Duration(days: 28)),
              currentDueDate: DateTime.now().add(const Duration(days: 28)),
              assigneeName: 'Dinesh Modular Works',
              assigneeRole: 'Kitchen Specialist',
              priority: TaskPriority.high,
              isCompleted: false,
              checklistItems: ['Sink cutout sealing', 'Dado tile coordination', 'Chimney ducting routed'],
              checklistChecked: [false, false, false],
            ),
          ],
        ),
        MilestoneWorkStream(
          id: 'MS-105-04',
          projectId: 'PRJ-105',
          name: '4. Wall Textures & PU Coatings',
          startDate: DateTime.now().add(const Duration(days: 36)),
          endDate: DateTime.now().add(const Duration(days: 48)),
          completionPercentage: 0.0,
          isApprovedByClient: false,
          tasks: [
            WbsTask(
              id: 'TSK-105-06',
              milestoneId: 'MS-105-04',
              title: 'Accent Wall Italian Stucco & PU Furniture Spraying',
              scopeDescription: 'Lime plaster stucco application in living room and matt PU clear coat on veneers',
              originalTargetDate: DateTime.now().add(const Duration(days: 45)),
              currentDueDate: DateTime.now().add(const Duration(days: 45)),
              assigneeName: 'Elite Polishers',
              assigneeRole: 'Finishing Specialist',
              priority: TaskPriority.medium,
              isCompleted: false,
              checklistItems: ['Base coat burnishing', 'Dust free drying room setup', 'Specular sheen test'],
              checklistChecked: [false, false, false],
            ),
          ],
        ),
      ],
      mediaLogs: [
        SiteMediaLog(
          id: 'MED-105-01',
          projectId: 'PRJ-105',
          projectTitle: 'Godrej Woods Tower B - 3BHK',
          milestoneName: 'Electrical Rough-in',
          title: 'Kitchen Concealed Conduit Pulling & DB Connection',
          description: 'Finolex 4 sq.mm cabling pulled for 16A microwave, induction hub, and dishwasher power points.',
          mediaUrl: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=1200&q=80',
          thumbnailUrl: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=400&q=80',
          isVideo: true,
          durationText: '01:30',
          recordedAt: DateTime.now().subtract(const Duration(days: 2)),
          supervisorName: 'Vikas Tyagi',
          workerCountOnSite: 5,
          weatherCondition: 'Rainy 25°C',
          gpsCoordinates: '28.5355° N, 77.3910° E (Noida)',
          isGpsVerified: true,
        ),
        SiteMediaLog(
          id: 'MED-105-02',
          projectId: 'PRJ-105',
          projectTitle: 'Godrej Woods Tower B - 3BHK',
          milestoneName: 'Civil Masonry',
          title: 'Bathroom Waterproofing Ponding Test (72 Hours)',
          description: 'Ponding water level verified with brass ruler marker. Zero seepage recorded on ceiling below.',
          mediaUrl: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=1200&q=80',
          thumbnailUrl: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=400&q=80',
          isVideo: false,
          durationText: 'Photo',
          recordedAt: DateTime.now().subtract(const Duration(days: 6)),
          supervisorName: 'Vikas Tyagi',
          workerCountOnSite: 6,
          weatherCondition: 'Cloudy 27°C',
          gpsCoordinates: '28.5355° N, 77.3910° E (Noida)',
          isGpsVerified: true,
        ),
      ],
      snags: [
        SnagTicket(
          id: 'SNG-105-01',
          ticketNumber: 'SNG-105-01',
          projectId: 'PRJ-105',
          projectTitle: 'Godrej Woods Tower B - 3BHK',
          roomArea: 'Common Corridor',
          category: SnagCategory.siteCleanliness,
          description: 'Building society RWA issued complaint regarding plaster rubble in service elevator.',
          priority: TaskPriority.urgent,
          status: SnagStatus.resolvedOnTime,
          raisedAt: DateTime.now().subtract(const Duration(days: 2)),
          slaDeadline: DateTime.now().subtract(const Duration(days: 1)),
          raisedBy: 'Building RWA Security',
          assignedTo: 'Vikas Tyagi',
          photoUrls: ['https://images.unsplash.com/photo-1541888946425-d0fbb186f5f7?w=400&q=80'],
          correctiveChecklist: ['Full debris vacuuming', 'Protective corrugated sheets laid', 'RWA guard sign-off'],
          checklistDone: [true, true, true],
          resolutionNotes: 'Elevator cleaned thoroughly and covered with corrugated plastic sheet. Security guard signed NOC.',
          resolvedAt: DateTime.now().subtract(const Duration(days: 1, hours: 4)),
        ),
        SnagTicket(
          id: 'SNG-105-02',
          ticketNumber: 'SNG-105-02',
          projectId: 'PRJ-105',
          projectTitle: 'Godrej Woods Tower B - 3BHK',
          roomArea: 'Bed 2 Study Table',
          category: SnagCategory.measurementError,
          description: 'Switchboard height was chased at 900mm instead of 750mm desk height specified in electrical drawing.',
          priority: TaskPriority.high,
          status: SnagStatus.inProgress,
          raisedAt: DateTime.now().subtract(const Duration(hours: 14)),
          slaDeadline: DateTime.now().add(const Duration(hours: 34)),
          raisedBy: 'Ananya Roy (Architect)',
          assignedTo: 'Vikas Tyagi',
          photoUrls: ['https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=400&q=80'],
          correctiveChecklist: [
            'Chasing re-cut at 750mm FFL',
            'Patch plaster old metal box hole',
            'Wire loop continuity test',
          ],
          checklistDone: [true, false, false],
        ),
      ],
      stageApprovals: [
        StageApprovalRequest(
          id: 'APR-105-01',
          projectId: 'PRJ-105',
          projectCode: 'PRJ-105',
          projectTitle: 'Godrej Woods Tower B - 3BHK',
          clientName: 'Radhika Singhania',
          clientPhone: '+91 98201 44552',
          milestoneName: 'Stage 1: Civil Masonry & Plumbing Rerouting Sign-off',
          stageContractShareAmount: 490000.0,
          requestedAt: DateTime.now().subtract(const Duration(days: 4)),
          isApproved: true,
          approvedAt: '02/09/2026 11:15 IST',
          otpSignoffAudit: 'Verified via WhatsApp OTP (552109) • IP: 103.21.12.44 • Device: Samsung S24 Ultra',
          inspectionChecklist: [
            'Ponding test video reviewed and signed off',
            'Concealed plumbing leak test passed',
            'Masonry wall plumb verified with laser level',
          ],
          completionPhotoUrls: ['https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=600&q=80'],
        ),
        StageApprovalRequest(
          id: 'APR-105-02',
          projectId: 'PRJ-105',
          projectCode: 'PRJ-105',
          projectTitle: 'Godrej Woods Tower B - 3BHK',
          clientName: 'Radhika Singhania',
          clientPhone: '+91 98201 44552',
          milestoneName: 'Stage 2: Electrical Rough-in & Gypsum Ceiling Framing',
          stageContractShareAmount: 490000.0,
          requestedAt: DateTime.now().add(const Duration(days: 12)),
          isApproved: false,
          inspectionChecklist: [
            'Conduit chase plastering flush',
            'Ceiling drop levels compliant with design',
            'AC indoor unit bracket mounting pull-tested',
          ],
          completionPhotoUrls: [],
        ),
      ],
      ratings: [
        StakeholderRating(
          id: 'RAT-105-01',
          projectId: 'PRJ-105',
          projectTitle: 'Godrej Woods Tower B',
          stakeholderType: StakeholderType.supervisor,
          targetName: 'Vikas Tyagi (Site Supervisor)',
          score1: 4.8,
          label1: 'Daily Site Progress & Safety Reporting',
          score2: 4.6,
          label2: 'RWA Coordination & Cleanliness Handling',
          score3: 4.7,
          label3: 'Contractor Management',
          reviewNote: 'Quick to resolve the elevator debris issue with RWA management, avoiding any builder penalties.',
          ratedAt: DateTime.now().subtract(const Duration(days: 1)),
          ratedBy: 'Ananya Roy (Lead Architect)',
        ),
        StakeholderRating(
          id: 'RAT-105-02',
          projectId: 'PRJ-105',
          projectTitle: 'Godrej Woods Tower B',
          stakeholderType: StakeholderType.materialVendor,
          targetName: 'Finolex Regional Depot',
          score1: 4.9,
          label1: 'Cable Batch Authentication & Quality',
          score2: 4.8,
          label2: 'Delivery Turnaround Time',
          score3: 4.7,
          label3: 'Billing Clarity & GST Compliance',
          reviewNote: 'All spools delivered with batch test certificates and flame retardancy compliance.',
          ratedAt: DateTime.now().subtract(const Duration(days: 7)),
          ratedBy: 'Vikas Tyagi',
        ),
      ],
      ledgerEntries: [
        FinancialLedgerEntry(
          id: 'LED-105-01',
          projectId: 'PRJ-105',
          projectTitle: 'Godrej Woods Tower B',
          type: LedgerType.material,
          date: DateTime.now().subtract(const Duration(days: 3)),
          payeeOrVendor: 'Finolex Depot Noida',
          description: '12 Coils Finolex FRLS Copper Wires (2.5 & 4 sq.mm) + PVC Conduits',
          amount: 68400.0,
          isPaid: true,
          commissionPercent: 3.5,
          commissionAmount: 2394.0,
          note: 'Billed with 18% GST input credit invoice',
        ),
        FinancialLedgerEntry(
          id: 'LED-105-02',
          projectId: 'PRJ-105',
          projectTitle: 'Godrej Woods Tower B',
          type: LedgerType.labour,
          date: DateTime.now().subtract(const Duration(days: 4)),
          payeeOrVendor: 'Santosh Civil Contractors',
          description: 'Masonry wall dismantling and core drilling labour (Stage 1 settlement)',
          amount: 38000.0,
          isPaid: true,
          note: 'Includes society debris hauling charges',
        ),
        FinancialLedgerEntry(
          id: 'LED-105-03',
          projectId: 'PRJ-105',
          projectTitle: 'Godrej Woods Tower B',
          type: LedgerType.supervision,
          date: DateTime.now().subtract(const Duration(days: 8)),
          payeeOrVendor: 'Vikas Tyagi (Supervisor)',
          description: 'Fortnightly Site Supervision Allowance',
          amount: 18000.0,
          isPaid: true,
          commissionPercent: 1.5,
          commissionAmount: 8500.0,
          note: 'Civil stage completion milestone incentive included',
        ),
      ],
    ),

    // -------------------------------------------------------------------------
    // PROJECT 3: Prestige Golfshire Luxury Villa #42 (Fixed Consulting)
    // -------------------------------------------------------------------------
    ProjectMaster(
      id: 'PRJ-106',
      projectCode: 'PRJ-106',
      projectTitle: 'Prestige Golfshire Luxury Villa #42',
      clientName: 'Col. K.S. Rathore',
      clientPhone: '+91 98450 11922',
      clientEmail: 'ks.rathore@indianarmy.org',
      siteAddress: 'Villa 42, Nandi Hills Road',
      city: 'Bangalore',
      floorAreaSqft: 6500.0,
      projectManagerName: 'Arjun Swaminathan',
      siteSupervisorName: 'Murugan K',
      startDate: DateTime.now().subtract(const Duration(days: 60)),
      targetHandoverDate: DateTime.now().add(const Duration(days: 20)),
      status: ProjectStatus.snagging,
      timelineHealth: TimelineHealth.onTime,
      contractModel: ContractModel.fixedConsulting,
      totalContractValue: 4800000.0,
      totalBilled: 4200000.0,
      totalPaid: 3900000.0,
      totalDesignFiles: 32,
      completedDesignFiles: 32,
      averageCsatRating: 5.0,
      milestones: [
        MilestoneWorkStream(
          id: 'MS-106-01',
          projectId: 'PRJ-106',
          name: '1. Architectural 3D Sign-off & BOQ Validation',
          startDate: DateTime.now().subtract(const Duration(days: 60)),
          endDate: DateTime.now().subtract(const Duration(days: 45)),
          completionPercentage: 1.0,
          isApprovedByClient: true,
          clientOtpSignoffDate: '28/07/2026 (OTP: 712390)',
          tasks: [
            WbsTask(
              id: 'TSK-106-01',
              milestoneId: 'MS-106-01',
              title: 'Villa Structural Audit & Load Bearing Confirmation',
              scopeDescription: 'Senior structural consultant review for double-height chandelier hanging point and outdoor deck pergola',
              originalTargetDate: DateTime.now().subtract(const Duration(days: 52)),
              currentDueDate: DateTime.now().subtract(const Duration(days: 52)),
              assigneeName: 'Prof. V. Raman',
              assigneeRole: 'Structural Engineer',
              priority: TaskPriority.urgent,
              isCompleted: true,
              checklistItems: ['Chandelier anchor load tested (350kg)', 'Terrace load assessment', 'NOC issued'],
              checklistChecked: [true, true, true],
            ),
            WbsTask(
              id: 'TSK-106-02',
              milestoneId: 'MS-106-01',
              title: 'Detailed Tender BOQ & Item Rate Finalization',
              scopeDescription: 'Comprehensive 400-item BOQ for marble, teakwood, and automated HVAC',
              originalTargetDate: DateTime.now().subtract(const Duration(days: 46)),
              currentDueDate: DateTime.now().subtract(const Duration(days: 46)),
              assigneeName: 'Arjun Swaminathan',
              assigneeRole: 'Project Manager',
              priority: TaskPriority.high,
              isCompleted: true,
              checklistItems: ['Contractor rates locked', 'Client signoff on finishes schedule'],
              checklistChecked: [true, true],
            ),
          ],
        ),
        MilestoneWorkStream(
          id: 'MS-106-02',
          projectId: 'PRJ-106',
          name: '2. Italian Marble Flooring & Wall Cladding',
          startDate: DateTime.now().subtract(const Duration(days: 44)),
          endDate: DateTime.now().subtract(const Duration(days: 20)),
          completionPercentage: 1.0,
          isApprovedByClient: true,
          clientOtpSignoffDate: '16/08/2026 (OTP: 630142)',
          tasks: [
            WbsTask(
              id: 'TSK-106-03',
              milestoneId: 'MS-106-02',
              title: 'Dyna Statuario Italian Marble Dry Laying & Bookmatch Inspection',
              scopeDescription: 'Dry-laying 3200 sqft marble slabs in natural daylight to ensure seamless grain continuation',
              originalTargetDate: DateTime.now().subtract(const Duration(days: 35)),
              currentDueDate: DateTime.now().subtract(const Duration(days: 35)),
              assigneeName: 'Murugan K',
              assigneeRole: 'Site Supervisor',
              priority: TaskPriority.urgent,
              isCompleted: true,
              checklistItems: ['Bookmatch vein approved by client', 'Epoxy adhesive leveling', 'Laticrete grout filled'],
              checklistChecked: [true, true, true],
            ),
            WbsTask(
              id: 'TSK-106-04',
              milestoneId: 'MS-106-02',
              title: 'Diamond Pad Mirror Polishing (8-Stage Klindex System)',
              scopeDescription: 'Crystallization polishing achieving 95+ gloss unit mirror reflection across ground floor',
              originalTargetDate: DateTime.now().subtract(const Duration(days: 22)),
              currentDueDate: DateTime.now().subtract(const Duration(days: 22)),
              assigneeName: 'Bangalore Marble Artisans',
              assigneeRole: 'Master Polishers',
              priority: TaskPriority.high,
              isCompleted: true,
              checklistItems: ['Klindex grit 3000 completed', 'Gloss meter verified at 96', 'Silane impregnating sealer coat'],
              checklistChecked: [true, true, true],
            ),
          ],
        ),
        MilestoneWorkStream(
          id: 'MS-106-03',
          projectId: 'PRJ-106',
          name: '3. Bespoke Veneer & Solid Burma Teak Woodwork',
          startDate: DateTime.now().subtract(const Duration(days: 19)),
          endDate: DateTime.now().add(const Duration(days: 5)),
          completionPercentage: 0.95,
          isApprovedByClient: false,
          tasks: [
            WbsTask(
              id: 'TSK-106-05',
              milestoneId: 'MS-106-03',
              title: 'Burma Teak Double Door Main Entrance Frame & Panelling',
              scopeDescription: 'Handcrafted solid teak door with biometric Yale fingerprint lock integration',
              originalTargetDate: DateTime.now().subtract(const Duration(days: 2)),
              currentDueDate: DateTime.now().subtract(const Duration(days: 2)),
              assigneeName: 'Narayana Master Woodcraft',
              assigneeRole: 'Heritage Carpenter',
              priority: TaskPriority.urgent,
              isCompleted: true,
              checklistItems: ['Frame anchored with heavy SS bolts', 'Biometric lock tested 50 cycles', 'Clear matt sealer applied'],
              checklistChecked: [true, true, true],
            ),
            WbsTask(
              id: 'TSK-106-06',
              milestoneId: 'MS-106-03',
              title: 'Walk-in Closet Smoked Oak Veneer Finishing & Sensor Lights',
              scopeDescription: 'Imported smoked oak fluted panels with concealed warm white 3000K sensor profiles',
              originalTargetDate: DateTime.now().add(const Duration(days: 4)),
              currentDueDate: DateTime.now().add(const Duration(days: 4)),
              assigneeName: 'Narayana Master Woodcraft',
              assigneeRole: 'Senior Carpenter',
              priority: TaskPriority.high,
              isCompleted: false,
              checklistItems: ['Veneer press alignment', 'Magnetic door catches', 'Light sensor delay timing set'],
              checklistChecked: [true, true, false],
            ),
          ],
        ),
        MilestoneWorkStream(
          id: 'MS-106-04',
          projectId: 'PRJ-106',
          name: '4. Snagging, Defect Rectification & Key Handover',
          startDate: DateTime.now().add(const Duration(days: 6)),
          endDate: DateTime.now().add(const Duration(days: 20)),
          completionPercentage: 0.15,
          isApprovedByClient: false,
          tasks: [
            WbsTask(
              id: 'TSK-106-07',
              milestoneId: 'MS-106-04',
              title: 'Pre-Handover Snag Audit Walkthrough with Col. Rathore',
              scopeDescription: 'Room-by-room punch list generation with handheld laser distance and electrical testers',
              originalTargetDate: DateTime.now().add(const Duration(days: 10)),
              currentDueDate: DateTime.now().add(const Duration(days: 10)),
              assigneeName: 'Arjun Swaminathan',
              assigneeRole: 'Project Manager',
              priority: TaskPriority.urgent,
              isCompleted: false,
              checklistItems: ['HVAC temperature delta test', 'All plumbing valves checked', 'Appliance warranty signoff'],
              checklistChecked: [false, false, false],
            ),
          ],
        ),
      ],
      mediaLogs: [
        SiteMediaLog(
          id: 'MED-106-01',
          projectId: 'PRJ-106',
          projectTitle: 'Prestige Golfshire Luxury Villa #42',
          milestoneName: 'Italian Marble Flooring',
          title: 'Dyna Statuario Mirror Crystallization 4K Walkthrough',
          description: 'Inspection of mirror finish reflection in double-height living room with reflection of garden greens.',
          mediaUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&q=80',
          thumbnailUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=400&q=80',
          isVideo: true,
          durationText: '03:10',
          recordedAt: DateTime.now().subtract(const Duration(days: 5)),
          supervisorName: 'Murugan K',
          workerCountOnSite: 8,
          weatherCondition: 'Pleasant 24°C',
          gpsCoordinates: '13.3644° N, 77.6833° E (Nandi Hills)',
          isGpsVerified: true,
        ),
        SiteMediaLog(
          id: 'MED-106-02',
          projectId: 'PRJ-106',
          projectTitle: 'Prestige Golfshire Luxury Villa #42',
          milestoneName: 'Teak Woodwork',
          title: 'Burma Teak Entrance Portal & Smart Lock Installation',
          description: 'High-res close-up of 85mm thick Burma teak solid wood door frame and Yale biometric handle.',
          mediaUrl: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=1200&q=80',
          thumbnailUrl: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=400&q=80',
          isVideo: false,
          durationText: 'Photo',
          recordedAt: DateTime.now().subtract(const Duration(days: 8)),
          supervisorName: 'Murugan K',
          workerCountOnSite: 6,
          weatherCondition: 'Sunny 26°C',
          gpsCoordinates: '13.3644° N, 77.6833° E (Nandi Hills)',
          isGpsVerified: true,
        ),
      ],
      snags: [
        SnagTicket(
          id: 'SNG-106-01',
          ticketNumber: 'SNG-106-01',
          projectId: 'PRJ-106',
          projectTitle: 'Prestige Golfshire Luxury Villa #42',
          roomArea: 'Powder Room Marble Basin',
          category: SnagCategory.qualityDefect,
          description: 'Water drainage pooling on left corner of custom carved marble vanity counter.',
          priority: TaskPriority.high,
          status: SnagStatus.inProgress,
          raisedAt: DateTime.now().subtract(const Duration(hours: 12)),
          slaDeadline: DateTime.now().add(const Duration(hours: 36)),
          raisedBy: 'Col. K.S. Rathore (Homeowner)',
          assignedTo: 'Bangalore Marble Artisans',
          photoUrls: ['https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=400&q=80'],
          correctiveChecklist: [
            'Micro-grind vanity surface to introduce 2mm slope to center waste',
            'Re-polish with diamond paste',
            'Hydrophobic sealant application',
          ],
          checklistDone: [true, false, false],
        ),
        SnagTicket(
          id: 'SNG-106-02',
          ticketNumber: 'SNG-106-02',
          projectId: 'PRJ-106',
          projectTitle: 'Prestige Golfshire Luxury Villa #42',
          roomArea: 'Master Bedroom Closet',
          category: SnagCategory.materialDeviation,
          description: 'One soft-close damper piston in left wardrobe shutter is sticking intermittently.',
          priority: TaskPriority.medium,
          status: SnagStatus.resolvedOnTime,
          raisedAt: DateTime.now().subtract(const Duration(days: 3)),
          slaDeadline: DateTime.now().subtract(const Duration(days: 1)),
          raisedBy: 'Murugan K (Supervisor)',
          assignedTo: 'Narayana Master Woodcraft',
          photoUrls: ['https://images.unsplash.com/photo-1595428774223-ef52624120d2?w=400&q=80'],
          correctiveChecklist: ['Replace Blum piston with new unit', 'Check hinge tension', 'Client test'],
          checklistDone: [true, true, true],
          resolutionNotes: 'Hinge replaced under manufacturer warranty. Operation verified silky smooth.',
          resolvedAt: DateTime.now().subtract(const Duration(days: 2)),
        ),
      ],
      stageApprovals: [
        StageApprovalRequest(
          id: 'APR-106-01',
          projectId: 'PRJ-106',
          projectCode: 'PRJ-106',
          projectTitle: 'Prestige Golfshire Luxury Villa #42',
          clientName: 'Col. K.S. Rathore',
          clientPhone: '+91 98450 11922',
          milestoneName: 'Milestone 1: Architectural BOQ & Structural Audit Clearance',
          stageContractShareAmount: 960000.0,
          requestedAt: DateTime.now().subtract(const Duration(days: 45)),
          isApproved: true,
          approvedAt: '28/07/2026 16:45 IST',
          otpSignoffAudit: 'Verified via WhatsApp OTP (712390) • IP: 14.143.40.18 • Device: MacBook Pro M2',
          inspectionChecklist: ['Chandelier structural support load certificate', 'BOQ rates agreed'],
          completionPhotoUrls: ['https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600&q=80'],
        ),
        StageApprovalRequest(
          id: 'APR-106-02',
          projectId: 'PRJ-106',
          projectCode: 'PRJ-106',
          projectTitle: 'Prestige Golfshire Luxury Villa #42',
          clientName: 'Col. K.S. Rathore',
          clientPhone: '+91 98450 11922',
          milestoneName: 'Milestone 2: Italian Marble Statuario Laying & Polishing',
          stageContractShareAmount: 1440000.0,
          requestedAt: DateTime.now().subtract(const Duration(days: 20)),
          isApproved: true,
          approvedAt: '16/08/2026 12:30 IST',
          otpSignoffAudit: 'Verified via WhatsApp OTP (630142) • IP: 14.143.40.18 • Device: iPhone 14 Pro',
          inspectionChecklist: ['Gloss meter test 95+ GU', 'Laying level tolerance < 1mm', 'Sealer protection complete'],
          completionPhotoUrls: ['https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600&q=80'],
        ),
        StageApprovalRequest(
          id: 'APR-106-03',
          projectId: 'PRJ-106',
          projectCode: 'PRJ-106',
          projectTitle: 'Prestige Golfshire Luxury Villa #42',
          clientName: 'Col. K.S. Rathore',
          clientPhone: '+91 98450 11922',
          milestoneName: 'Milestone 3: Teak Woodwork & Smart Home Automation (Ready for Sign-off)',
          stageContractShareAmount: 1200000.0,
          requestedAt: DateTime.now().subtract(const Duration(hours: 20)),
          isApproved: false,
          inspectionChecklist: [
            'Burma teak doors acoustic sealing verified',
            'Lutron smart switches lighting scenes configured',
            'Motorized curtain tracking tested in all master suites',
          ],
          completionPhotoUrls: ['https://images.unsplash.com/photo-1513694203232-719a280e022f?w=600&q=80'],
        ),
      ],
      ratings: [
        StakeholderRating(
          id: 'RAT-106-01',
          projectId: 'PRJ-106',
          projectTitle: 'Prestige Golfshire Villa',
          stakeholderType: StakeholderType.supervisor,
          targetName: 'Murugan K (Site Supervisor)',
          score1: 5.0,
          label1: 'Punctuality & Villa Inspection Discipline',
          score2: 5.0,
          label2: 'Technical Super-Luxury Quality Control',
          score3: 4.9,
          label3: 'Contractor Orchestration',
          reviewNote: 'Murugan runs the villa site like military precision. Absolutely immaculate craftsmanship standards.',
          ratedAt: DateTime.now().subtract(const Duration(days: 3)),
          ratedBy: 'Col. K.S. Rathore (Homeowner)',
        ),
        StakeholderRating(
          id: 'RAT-106-02',
          projectId: 'PRJ-106',
          projectTitle: 'Prestige Golfshire Villa',
          stakeholderType: StakeholderType.labour,
          targetName: 'Bangalore Marble Artisans (Italian Stone Master)',
          score1: 5.0,
          label1: 'Vein Alignment & Bookmatch Precision',
          score2: 5.0,
          label2: 'Klindex Mirror Crystallization Quality',
          score3: 4.8,
          label3: 'Site Protection Standards',
          reviewNote: 'The Statuario bookmatch in the foyer is truly a work of fine art. Flawless reflection.',
          ratedAt: DateTime.now().subtract(const Duration(days: 10)),
          ratedBy: 'Arjun Swaminathan (Project Manager)',
        ),
      ],
      ledgerEntries: [
        FinancialLedgerEntry(
          id: 'LED-106-01',
          projectId: 'PRJ-106',
          projectTitle: 'Prestige Golfshire Villa',
          type: LedgerType.material,
          date: DateTime.now().subtract(const Duration(days: 15)),
          payeeOrVendor: 'Classic Marble Company Bangalore',
          description: 'Dyna Statuario Extra White Italian Marble (3200 sqft)',
          amount: 890000.0,
          isPaid: true,
          commissionPercent: 5.0,
          commissionAmount: 44500.0,
          note: 'Direct quarry import batch certified with slab thickness 20mm',
        ),
        FinancialLedgerEntry(
          id: 'LED-106-02',
          projectId: 'PRJ-106',
          projectTitle: 'Prestige Golfshire Villa',
          type: LedgerType.labour,
          date: DateTime.now().subtract(const Duration(days: 8)),
          payeeOrVendor: 'Bangalore Marble Artisans',
          description: 'Marble laying and 8-stage diamond pad mirror polish contractor settlement',
          amount: 145000.0,
          isPaid: true,
          note: 'Gloss level passed 96 GU audit milestone',
        ),
        FinancialLedgerEntry(
          id: 'LED-106-03',
          projectId: 'PRJ-106',
          projectTitle: 'Prestige Golfshire Villa',
          type: LedgerType.supervision,
          date: DateTime.now().subtract(const Duration(days: 12)),
          payeeOrVendor: 'Murugan K (Senior Site Engineer)',
          description: 'Monthly Senior Site Project Supervision Fee',
          amount: 50000.0,
          isPaid: true,
          commissionPercent: 2.5,
          commissionAmount: 25000.0,
          note: 'Zero tolerance quality milestone incentive released',
        ),
      ],
    ),

    // -------------------------------------------------------------------------
    // PROJECT 4: Oberoi Sky City Tower E (Turnkey Contract)
    // -------------------------------------------------------------------------
    ProjectMaster(
      id: 'PRJ-107',
      projectCode: 'PRJ-107',
      projectTitle: 'Oberoi Sky City Tower E - 4BHK Duplex',
      clientName: 'Meera & Siddharth Shroff',
      clientPhone: '+91 98205 77890',
      clientEmail: 'siddharth.shroff@kotakprivate.com',
      siteAddress: 'Tower E, 38th Floor, Borivali East',
      city: 'Mumbai',
      floorAreaSqft: 3400.0,
      projectManagerName: 'Rohit Deshmukh',
      siteSupervisorName: 'Ganesh Shinde',
      startDate: DateTime.now().subtract(const Duration(days: 10)),
      targetHandoverDate: DateTime.now().add(const Duration(days: 75)),
      status: ProjectStatus.inExecution,
      timelineHealth: TimelineHealth.onTime,
      contractModel: ContractModel.turnkeyContract,
      totalContractValue: 6200000.0,
      totalBilled: 1860000.0,
      totalPaid: 1860000.0,
      totalDesignFiles: 28,
      completedDesignFiles: 28,
      averageCsatRating: 4.9,
      milestones: [
        MilestoneWorkStream(
          id: 'MS-107-01',
          projectId: 'PRJ-107',
          name: '1. Demolition & Fire Suppression Piping Upgrades',
          startDate: DateTime.now().subtract(const Duration(days: 10)),
          endDate: DateTime.now().subtract(const Duration(days: 1)),
          completionPercentage: 1.0,
          isApprovedByClient: true,
          clientOtpSignoffDate: '05/09/2026 (OTP: 441920)',
          tasks: [
            WbsTask(
              id: 'TSK-107-01',
              milestoneId: 'MS-107-01',
              title: 'Sprinkler Line Relocation & Pressure Testing',
              scopeDescription: 'Relocating 14 concealed sprinkler pendants according to new architectural ceiling design',
              originalTargetDate: DateTime.now().subtract(const Duration(days: 4)),
              currentDueDate: DateTime.now().subtract(const Duration(days: 4)),
              assigneeName: 'Mumbai Fire Safety Services',
              assigneeRole: 'Fire Safety Contractor',
              priority: TaskPriority.urgent,
              isCompleted: true,
              checklistItems: ['High-rise safety permit', 'Pressure hold 250 PSI', 'MCGM compliant pendants'],
              checklistChecked: [true, true, true],
            ),
          ],
        ),
        MilestoneWorkStream(
          id: 'MS-107-02',
          projectId: 'PRJ-107',
          name: '2. Acoustical Ceiling & Concealed Ducted HVAC',
          startDate: DateTime.now(),
          endDate: DateTime.now().add(const Duration(days: 18)),
          completionPercentage: 0.25,
          isApprovedByClient: false,
          tasks: [
            WbsTask(
              id: 'TSK-107-02',
              milestoneId: 'MS-107-02',
              title: 'Mitsubishi Heavy Industries VRF High Static Duct Installation',
              scopeDescription: 'Indoor units duct routing with sound attenuators and vibration isolation hangers',
              originalTargetDate: DateTime.now().add(const Duration(days: 8)),
              currentDueDate: DateTime.now().add(const Duration(days: 8)),
              assigneeName: 'CoolAir Technologies Mumbai',
              assigneeRole: 'HVAC Specialist',
              priority: TaskPriority.urgent,
              isCompleted: false,
              checklistItems: ['Acoustic lagging on supply ducts', 'Condensate gravity fall test', 'Vibration isolators torqued'],
              checklistChecked: [true, false, false],
            ),
            WbsTask(
              id: 'TSK-107-03',
              milestoneId: 'MS-107-02',
              title: 'Saint-Gobain Rigitone Acoustic Board Ceiling',
              scopeDescription: 'Perforated sound absorption panels installed in home theatre and music lounge',
              originalTargetDate: DateTime.now().add(const Duration(days: 16)),
              currentDueDate: DateTime.now().add(const Duration(days: 16)),
              assigneeName: 'Ganesh Shinde',
              assigneeRole: 'Site Supervisor',
              priority: TaskPriority.high,
              isCompleted: false,
              checklistItems: ['Acoustic fleece lining intact', 'Laser grid true', 'Seamless joint filler applied'],
              checklistChecked: [false, false, false],
            ),
          ],
        ),
        MilestoneWorkStream(
          id: 'MS-107-03',
          projectId: 'PRJ-107',
          name: '3. Imported German Modular Kitchen & Joinery',
          startDate: DateTime.now().add(const Duration(days: 19)),
          endDate: DateTime.now().add(const Duration(days: 42)),
          completionPercentage: 0.0,
          isApprovedByClient: false,
          tasks: [
            WbsTask(
              id: 'TSK-107-04',
              milestoneId: 'MS-107-03',
              title: 'Poggenpohl Kitchen Modular Cabinet Assembly',
              scopeDescription: 'Direct Hamburg import installation with Dekton Laurent porcelain waterfall island counter',
              originalTargetDate: DateTime.now().add(const Duration(days: 35)),
              currentDueDate: DateTime.now().add(const Duration(days: 35)),
              assigneeName: 'Poggenpohl India Tech Team',
              assigneeRole: 'Factory Certified Installer',
              priority: TaskPriority.high,
              isCompleted: false,
              checklistItems: ['Laser leveling of island', 'Appliance integration test', 'Waterfall miter joints glued'],
              checklistChecked: [false, false, false],
            ),
          ],
        ),
      ],
      mediaLogs: [
        SiteMediaLog(
          id: 'MED-107-01',
          projectId: 'PRJ-107',
          projectTitle: 'Oberoi Sky City Tower E',
          milestoneName: 'Acoustical Ceiling & HVAC',
          title: 'Mitsubishi Ducted HVAC Indoor Unit Acoustic Dampening Test',
          description: 'Sound level meter reading only 24 dB sound at 2 meters under full cooling air throw.',
          mediaUrl: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200&q=80',
          thumbnailUrl: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=400&q=80',
          isVideo: true,
          durationText: '01:50',
          recordedAt: DateTime.now().subtract(const Duration(hours: 5)),
          supervisorName: 'Ganesh Shinde',
          workerCountOnSite: 7,
          weatherCondition: 'Humid 29°C',
          gpsCoordinates: '19.2288° N, 72.8541° E (Borivali East)',
          isGpsVerified: true,
        ),
      ],
      snags: [
        SnagTicket(
          id: 'SNG-107-01',
          ticketNumber: 'SNG-107-01',
          projectId: 'PRJ-107',
          projectTitle: 'Oberoi Sky City Tower E',
          roomArea: 'Home Theatre Ceiling',
          category: SnagCategory.materialDeviation,
          description: 'Perforation pattern on acoustic panel delivered is circular instead of square micro-mesh.',
          priority: TaskPriority.high,
          status: SnagStatus.inProgress,
          raisedAt: DateTime.now().subtract(const Duration(hours: 6)),
          slaDeadline: DateTime.now().add(const Duration(hours: 42)),
          raisedBy: 'Rohit Deshmukh (PM)',
          assignedTo: 'Ganesh Shinde',
          photoUrls: ['https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=400&q=80'],
          correctiveChecklist: [
            'Reject delivery batch with Saint-Gobain rep',
            'Order priority courier replacement of Square 8/18 pattern',
          ],
          checklistDone: [true, false],
        ),
      ],
      stageApprovals: [
        StageApprovalRequest(
          id: 'APR-107-01',
          projectId: 'PRJ-107',
          projectCode: 'PRJ-107',
          projectTitle: 'Oberoi Sky City Tower E',
          clientName: 'Meera & Siddharth Shroff',
          clientPhone: '+91 98205 77890',
          milestoneName: 'Milestone 1: Demolition & Fire Safety Upgrades Signoff',
          stageContractShareAmount: 1860000.0,
          requestedAt: DateTime.now().subtract(const Duration(days: 1)),
          isApproved: true,
          approvedAt: '05/09/2026 19:10 IST',
          otpSignoffAudit: 'Verified via WhatsApp OTP (441920) • IP: 49.37.200.12 • Device: iPad Pro M4',
          inspectionChecklist: [
            'Sprinkler hydraulic test approved by building facility engineer',
            'All civil rubble evacuated via service lift with zero debris in lobby',
          ],
          completionPhotoUrls: ['https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=600&q=80'],
        ),
      ],
      ratings: [
        StakeholderRating(
          id: 'RAT-107-01',
          projectId: 'PRJ-107',
          projectTitle: 'Oberoi Sky City',
          stakeholderType: StakeholderType.supervisor,
          targetName: 'Ganesh Shinde (Site Supervisor)',
          score1: 4.9,
          label1: 'Daily Site Log Uploads & GPS Accuracy',
          score2: 4.8,
          label2: 'Tower Security Protocol Adherence',
          score3: 5.0,
          label3: 'Acoustic Ceiling Knowledge',
          reviewNote: 'Very proactive supervisor. Managed high-rise freight elevator slots seamlessly without complaints.',
          ratedAt: DateTime.now().subtract(const Duration(days: 1)),
          ratedBy: 'Siddharth Shroff (Client)',
        ),
      ],
      ledgerEntries: [
        FinancialLedgerEntry(
          id: 'LED-107-01',
          projectId: 'PRJ-107',
          projectTitle: 'Oberoi Sky City',
          type: LedgerType.material,
          date: DateTime.now().subtract(const Duration(days: 2)),
          payeeOrVendor: 'Saint-Gobain Gyproc Depot Mumbai',
          description: 'Rigitone Acoustic Perforated Gypsum Boards & GI Framework',
          amount: 195000.0,
          isPaid: true,
          commissionPercent: 4.5,
          commissionAmount: 8775.0,
          note: 'Direct project discount invoiced with GST',
        ),
      ],
    ),
  ];

  // ---------------------------------------------------------------------------
  // Backward-Compatible Static Lists Flattened Across All Projects
  // ---------------------------------------------------------------------------
  static List<SiteMediaLog> get siteMediaLogs =>
      projects.expand((p) => p.mediaLogs).toList();

  static List<SnagTicket> get snagTickets =>
      projects.expand((p) => p.snags).toList();

  static List<StageApprovalRequest> get stageApprovals =>
      projects.expand((p) => p.stageApprovals).toList();

  static List<StakeholderRating> get stakeholderRatings =>
      projects.expand((p) => p.ratings).toList();

  static List<FinancialLedgerEntry> get financialLedgers =>
      projects.expand((p) => p.ledgerEntries).toList();
}
