import 'package:flutter/material.dart';
import 'operations_models.dart';

class OperationsMockData {
  // ===========================================================================
  // 1. LEGACY GETTERS (Preserved for backwards compatibility)
  // ===========================================================================

  static final List<MaterialRequisitionIndent> indents = [
    MaterialRequisitionIndent(
      id: 'IND-8821',
      projectTitle: 'DLF Magnolias #402, Gurugram',
      clientName: 'Rajeev Singhania',
      siteSupervisor: 'Rajesh Verma',
      itemName: 'Century Club Prime BWP Marine Plywood 19mm',
      quantity: 45,
      unit: 'Sheets (8x4)',
      requiredDate: DateTime.now().add(const Duration(days: 2)),
      urgency: IndentUrgency.urgent,
      status: IndentStatus.bidsReceived,
      notes: 'Required urgently for Master Bedroom walk-in wardrobe carcasses.',
      bids: const [
        VendorBid(
          id: 'BID-01',
          vendorName: 'Century Wholesale Hub, DLF Phase 2',
          vendorRating: 4.8,
          unitPrice: 2850,
          totalPrice: 128250,
          gstPercent: 18,
          deliveryDays: 1,
          qualityGrade: 'IS:710 Marine Certified (Calibrated)',
          warrantyMonths: 300,
          paymentTerms: '100% Advance via Homio Pay',
          isSelected: true,
        ),
        VendorBid(
          id: 'BID-02',
          vendorName: 'Austin Plywood Regional Depot, Delhi',
          vendorRating: 4.6,
          unitPrice: 2680,
          totalPrice: 120600,
          gstPercent: 18,
          deliveryDays: 2,
          qualityGrade: 'Austin Defender BWP Grade',
          warrantyMonths: 240,
          paymentTerms: '50% Advance, 50% on Site Unloading',
        ),
      ],
      approvedBidId: 'BID-01',
      clientPaymentUrl: 'https://pay.homio.in/inv/DLF-MR-8821',
    ),
  ];

  static final List<DesignPaymentMilestone> designMilestones = [
    DesignPaymentMilestone(
      id: 'DPM-101',
      projectTitle: 'The Camellias #1402, Golf Course Rd',
      clientName: 'Rahul Sharma',
      clientPhone: '+91 98101 44550',
      phaseTitle: 'Phase 2: Concept 3D Renders & Material Board Freeze',
      baseAmount: 150000,
      gstPercent: 18,
      status: PaymentLinkStatus.paid,
      paymentLinkUrl: 'https://pay.homio.in/design/CAM-DES-02',
      generatedDate: DateTime.now().subtract(const Duration(days: 10)),
      paidDate: DateTime.now().subtract(const Duration(days: 8)),
      invoiceNumber: 'HOM-DES-2026-041',
    ),
  ];

  static final List<SaturdayFeeBatch> saturdayFees = [
    SaturdayFeeBatch(
      id: 'SAT-BATCH-01',
      projectName: 'The Camellias #1402',
      clientName: 'Rahul Sharma',
      clientPhone: '+91 98101 44550',
      supervisorName: 'Rajesh Verma',
      currentStage: 'Modular Carpentry & Joinery Fitouts',
      weekProgressPercent: 12.5,
      contractModel: 'Turnkey Architectural Supervision',
      baseWeeklyFee: 35000,
      calculatedFee: 35000,
      adjustment: 0,
      status: SaturdayFeeStatus.scheduled,
      billingDate: DateTime.now().add(const Duration(days: 2)),
      invoiceRef: 'SAT-INV-2026-W36-01',
    ),
  ];

  // ===========================================================================
  // 2. PRD SCREEN 1: MATERIAL REQUESTS (8 Realistic Requests)
  // ===========================================================================

  static final List<MaterialRequest> materialRequests = [
    MaterialRequest(
      id: 'mr-001',
      requestNumber: 'MR-2026-00124',
      requestDate: DateTime(2026, 9, 2),
      requestType: RequestType.projectMaterial,
      department: 'Modular Carpentry',
      requestedBy: 'Rajesh Verma (Site Supervisor)',
      projectId: 'PRJ-CAM-01',
      projectName: 'The Camellias Villa Interior #1402',
      customerId: 'CUST-RS-01',
      customerName: 'Rahul Sharma',
      siteAddress: 'The Camellias, Golf Course Road, DLF Phase 5, Gurugram',
      floor: 'First Floor',
      roomArea: 'Master Suite & Walk-in Wardrobe',
      costCentre: 'CC-CARP-01',
      projectBudgetCategory: 'Woodwork & Joinery',
      requiredByDate: DateTime(2026, 9, 15),
      priority: RequestPriority.high,
      requestReason: 'Approved GFC drawing joinery carcass fabrication',
      businessJustification: 'Adherence to Milestone 3 execution handover date',
      internalNotes: 'Client Rahul Sharma requested 710 calibrated marine ply with Hafele fittings only.',
      items: [
        MaterialRequestItem(
          id: 'mri-101',
          itemName: 'Century Club Prime BWP Marine Plywood 19mm',
          itemCode: 'MAT-PLY-710-19',
          category: 'Wood & Boards',
          subcategory: 'Marine Plywood',
          description: 'Calibrated boiling waterproof marine plywood for carcass',
          specification: const MaterialSpecification(
            materialType: 'BWP Plywood',
            grade: '710 IS:710 Marine',
            thickness: '18 mm / 19 mm Calibrated',
            size: '8 ft x 4 ft (32 Sq.Ft.)',
            finish: 'Calibrated Smooth Face',
            brand: 'Century Club Prime',
            qualityLevel: 'Premium Calibrated IS:710',
            installationRequirement: 'Moisture resistant core for bedroom ensuite perimeter',
          ),
          dimensions: const DimensionInput(length: 8, width: 4, height: 0, thickness: 19, unit: 'ft'),
          quantity: 45,
          unit: 'Sheets (8x4)',
          preferredBrand: 'Century',
          preferredVendor: 'Century Wholesale Hub, Gurugram',
          estimatedRate: 2850,
          estimatedAmount: 128250,
          requiredDate: DateTime(2026, 9, 15),
          notes: 'Pre-treated anti-termite certificate mandatory',
        ),
        MaterialRequestItem(
          id: 'mri-102',
          itemName: 'Häfele Soft-Close Tandembox Antaro 500mm',
          itemCode: 'MAT-HAF-TB-500',
          category: 'Hardware & Fittings',
          subcategory: 'Drawer Systems',
          description: 'Silk white concealed drawer runners with motion dampening',
          specification: const MaterialSpecification(
            materialType: 'Steel Drawer Runner',
            grade: 'Dynamic 65kg',
            finish: 'Silk White Matte',
            brand: 'Häfele Blumotion',
            qualityLevel: 'Architectural Grade',
            installationRequirement: 'Precise 32mm system boring template required',
          ),
          quantity: 16,
          unit: 'Sets',
          preferredBrand: 'Häfele',
          preferredVendor: 'Hafele Direct Corporate Channel',
          estimatedRate: 4200,
          estimatedAmount: 67200,
          requiredDate: DateTime(2026, 9, 15),
          notes: 'Include front fixing brackets and gallery rails',
        ),
      ],
      estimatedMaterialCost: 195450,
      otherCharges: 4500,
      estimatedTotal: 199950,
      approvedAmount: 199950,
      budgetAvailable: 280000,
      status: MaterialRequestStatus.approved,
      procurementOwner: 'Amit Kumar',
      lastUpdated: DateTime(2026, 9, 3, 11, 30),
      timeline: [
        ProcurementTimelineEvent(
          id: 'tl-1',
          timestamp: DateTime(2026, 9, 2, 10, 15),
          title: 'Material Request Created',
          description: 'Raised by Rajesh Verma (Site Supervisor)',
          actorName: 'Rajesh Verma',
          actorRole: 'Site Supervisor',
          icon: Icons.add_circle_outline_rounded,
        ),
        ProcurementTimelineEvent(
          id: 'tl-2',
          timestamp: DateTime(2026, 9, 3, 11, 30),
          title: 'Request Approved & PO Assigned',
          description: 'Approved by PM Amit Kumar. Forwarded to Procurement.',
          actorName: 'Amit Kumar',
          actorRole: 'Project Manager',
          icon: Icons.verified_rounded,
        ),
      ],
    ),
    MaterialRequest(
      id: 'mr-002',
      requestNumber: 'MR-2026-00125',
      requestDate: DateTime(2026, 9, 3),
      requestType: RequestType.projectMaterial,
      department: 'Flooring & Stonework',
      requestedBy: 'Mahesh Kadam (Site Engg)',
      projectId: 'PRJ-OBS-02',
      projectName: 'Oberoi Sky City Luxury Penthouse #A-2201',
      customerId: 'CUST-AS-02',
      customerName: 'Dr. Arjun Singhania',
      siteAddress: 'Oberoi Sky City, Western Express Hwy, Borivali East, Mumbai',
      floor: '22nd Floor Penthouse',
      roomArea: 'Formal Drawing & Dining Foyer',
      costCentre: 'CC-STONE-02',
      projectBudgetCategory: 'Natural Stone & Marble',
      requiredByDate: DateTime(2026, 9, 20),
      priority: RequestPriority.urgent,
      requestReason: 'Dry-lay approved at Italian marble stockyard',
      businessJustification: 'Client approved bookmatch layout. Slab booking required.',
      internalNotes: 'Italian Statuario marble booked under Slab lot #ST-881.',
      items: [
        MaterialRequestItem(
          id: 'mri-201',
          itemName: 'Italian Statuario Marble Slabs 20mm',
          itemCode: 'MAT-MRB-STAT-20',
          category: 'Flooring & Cladding',
          subcategory: 'Imported Marble',
          description: 'White base with defined grey veining, bookmatched pairs',
          specification: const MaterialSpecification(
            materialType: 'Natural Marble',
            grade: 'First Grade Statuario Extra',
            thickness: '20 mm Gangsaw Cut',
            finish: 'Epoxy Treated & Fibre Mesh Backed',
            brand: 'Classic Marble Company / Imported',
            qualityLevel: 'Zero Crack Luxury Lot',
            installationRequirement: 'White adhesive with fiber reinforced screed',
          ),
          dimensions: const DimensionInput(length: 10, width: 6, height: 0, thickness: 20, unit: 'ft'),
          quantity: 1200,
          unit: 'Sq.Ft.',
          preferredBrand: 'CMC',
          preferredVendor: 'Classic Marble Depot, Silvassa',
          estimatedRate: 850,
          estimatedAmount: 1020000,
          requiredDate: DateTime(2026, 9, 20),
          notes: 'Fibre mesh backing and epoxy seal mandatory before crating',
        ),
      ],
      estimatedMaterialCost: 1020000,
      otherCharges: 25000,
      estimatedTotal: 1045000,
      approvedAmount: 1045000,
      budgetAvailable: 1200000,
      status: MaterialRequestStatus.inProcurement,
      procurementOwner: 'Vikram Malhotra',
      lastUpdated: DateTime(2026, 9, 4, 14, 0),
    ),
    MaterialRequest(
      id: 'mr-003',
      requestNumber: 'MR-2026-00126',
      requestDate: DateTime(2026, 9, 4),
      requestType: RequestType.projectMaterial,
      department: 'Electrical & MEP',
      requestedBy: 'Suresh Patil (MEP Lead)',
      projectId: 'PRJ-PFC-03',
      projectName: 'Prestige Falcon City 4BHK #1804',
      customerId: 'CUST-MD-03',
      customerName: 'Meera Deshmukh',
      siteAddress: 'Prestige Falcon City, Kanakapura Road, Bangalore',
      floor: '18th Floor',
      roomArea: 'All Bedrooms, Living & Automation DB',
      costCentre: 'CC-MEP-01',
      projectBudgetCategory: 'Automation & Electricals',
      requiredByDate: DateTime(2026, 9, 18),
      priority: RequestPriority.normal,
      requestReason: 'Concealed conduit wiring before gypsum false ceiling',
      businessJustification: 'False ceiling framing completed. Wiring pull underway.',
      internalNotes: 'Schneider Zencelo flat switches and Polycab FRLS copper wires.',
      items: [
        MaterialRequestItem(
          id: 'mri-301',
          itemName: 'Polycab FRLS-H Copper Wire 2.5 sq.mm',
          itemCode: 'MAT-ELE-POL-25',
          category: 'Electrical & Automation',
          subcategory: 'Cables & Wires',
          description: 'Flame retardant low smoke copper single core wire',
          specification: const MaterialSpecification(
            materialType: 'FRLS Copper',
            grade: 'IS:694 Certified',
            colour: 'Red, Yellow, Blue, Green, Black',
            brand: 'Polycab',
            qualityLevel: 'Pure Electrolytic Grade',
          ),
          quantity: 20,
          unit: 'Rolls (90m)',
          preferredBrand: 'Polycab',
          estimatedRate: 2450,
          estimatedAmount: 49000,
          requiredDate: DateTime(2026, 9, 18),
        ),
      ],
      estimatedMaterialCost: 49000,
      otherCharges: 1000,
      estimatedTotal: 50000,
      approvedAmount: 50000,
      budgetAvailable: 75000,
      status: MaterialRequestStatus.underReview,
      procurementOwner: 'Amit Kumar',
      lastUpdated: DateTime(2026, 9, 4, 16, 20),
    ),
    MaterialRequest(
      id: 'mr-004',
      requestNumber: 'MR-2026-00127',
      requestDate: DateTime(2026, 9, 5),
      requestType: RequestType.siteMaterial,
      department: 'Civil & Masonry',
      requestedBy: 'Amitabh Sharma (Site PM)',
      projectId: 'PRJ-LOD-04',
      projectName: 'Lodha Park Tower A #501',
      customerId: 'CUST-VS-04',
      customerName: 'Vikramaditya Shroff',
      siteAddress: 'Lodha Park, Pandurang Budhkar Marg, Worli, Mumbai',
      floor: '5th Floor',
      roomArea: 'Dry Balcony & Kitchen Extension',
      costCentre: 'CC-CIVIL-04',
      projectBudgetCategory: 'Civil Works',
      requiredByDate: DateTime(2026, 9, 12),
      priority: RequestPriority.urgent,
      requestReason: 'AAC blocks and polymer modified block mortar for partition',
      businessJustification: 'Structural alteration approved by society management',
      items: [
        MaterialRequestItem(
          id: 'mri-401',
          itemName: 'Ultratech AAC Lightweight Blocks 4-inch',
          itemCode: 'MAT-AAC-UT-04',
          category: 'Civil & Masonry',
          subcategory: 'Masonry Blocks',
          description: 'Autoclaved aerated concrete masonry blocks 600x200x100mm',
          quantity: 450,
          unit: 'PC / Nos',
          preferredBrand: 'Ultratech',
          estimatedRate: 68,
          estimatedAmount: 30600,
          requiredDate: DateTime(2026, 9, 12),
        ),
      ],
      estimatedMaterialCost: 30600,
      otherCharges: 3000,
      estimatedTotal: 33600,
      approvedAmount: 0,
      budgetAvailable: 50000,
      status: MaterialRequestStatus.draft,
      procurementOwner: 'Vikram Malhotra',
      lastUpdated: DateTime(2026, 9, 5, 09, 0),
    ),
  ];

  // ===========================================================================
  // 3. PRD SCREEN 2: VENDOR RFQs (Detailed Multi-Vendor RFQs)
  // ===========================================================================

  static final List<VendorRfq> vendorRfqs = [
    VendorRfq(
      id: 'rfq-001',
      rfqNumber: 'RFQ-2026-00084',
      rfqTitle: 'Plywood & Tandembox Hardware Requisition for Camellias #1402',
      rfqDate: DateTime(2026, 9, 3),
      responseDeadline: DateTime(2026, 9, 8),
      materialRequestId: 'mr-001',
      materialRequestNumber: 'MR-2026-00124',
      projectId: 'PRJ-CAM-01',
      projectName: 'The Camellias Villa Interior #1402',
      customerName: 'Rahul Sharma',
      siteAddress: 'The Camellias, Golf Course Road, DLF Phase 5, Gurugram',
      procurementOwner: 'Amit Kumar',
      priority: RequestPriority.high,
      vendors: const [
        RfqVendorInvite(
          vendorId: 'VND-001',
          vendorName: 'Century Wholesale Hub',
          vendorCode: 'VND-CEN-01',
          category: 'Plywood & Veneers',
          rating: 4.8,
          location: 'DLF Phase 2, Gurugram',
          contactPerson: 'Sunil Aggarwal',
          mobile: '+91 98101 33412',
          email: 'sales@centuryhub.in',
          status: 'Responded',
        ),
        RfqVendorInvite(
          vendorId: 'VND-002',
          vendorName: 'Austin Plywood Regional Depot',
          vendorCode: 'VND-AUS-02',
          category: 'Plywood & Boards',
          rating: 4.6,
          location: 'Kirti Nagar Timber Market, Delhi',
          contactPerson: 'Ramesh Bansal',
          mobile: '+91 98112 44900',
          email: 'quotes@austindepot.com',
          status: 'Responded',
        ),
        RfqVendorInvite(
          vendorId: 'VND-003',
          vendorName: 'Greenply Metro Distributors',
          vendorCode: 'VND-GRN-03',
          category: 'Plywood & Laminates',
          rating: 4.7,
          location: 'Sohna Road, Gurugram',
          contactPerson: 'Deepak Chopra',
          mobile: '+91 99105 88210',
          email: 'procure@greenplymetro.in',
          status: 'Responded',
        ),
      ],
      items: materialRequests[0].items,
      estimatedValue: 195450,
      status: VendorRfqStatus.comparisonReady,
    ),
    VendorRfq(
      id: 'rfq-002',
      rfqNumber: 'RFQ-2026-00085',
      rfqTitle: 'Italian Statuario Marble Lot for Oberoi Penthouse #A-2201',
      rfqDate: DateTime(2026, 9, 4),
      responseDeadline: DateTime(2026, 9, 10),
      materialRequestId: 'mr-002',
      materialRequestNumber: 'MR-2026-00125',
      projectId: 'PRJ-OBS-02',
      projectName: 'Oberoi Sky City Luxury Penthouse #A-2201',
      customerName: 'Dr. Arjun Singhania',
      siteAddress: 'Western Express Hwy, Borivali East, Mumbai',
      procurementOwner: 'Vikram Malhotra',
      priority: RequestPriority.urgent,
      vendors: const [
        RfqVendorInvite(
          vendorId: 'VND-004',
          vendorName: 'Classic Marble Company (CMC)',
          vendorCode: 'VND-CMC-01',
          category: 'Imported Marble',
          rating: 4.9,
          location: 'Bandra Kurla Complex, Mumbai',
          contactPerson: 'Amitabh Jha',
          mobile: '+91 98200 99182',
          email: 'luxury@classicmarble.com',
          status: 'Responded',
        ),
        RfqVendorInvite(
          vendorId: 'VND-005',
          vendorName: 'R K Marble Mumbai Stockyard',
          vendorCode: 'VND-RKM-02',
          category: 'Exotic Natural Stones',
          rating: 4.7,
          location: 'Vile Parle East, Mumbai',
          contactPerson: 'Vikas Singhal',
          mobile: '+91 98211 44550',
          email: 'quotes@rkmarble.com',
          status: 'Opened',
        ),
      ],
      items: materialRequests[1].items,
      estimatedValue: 1020000,
      status: VendorRfqStatus.partiallyResponded,
    ),
  ];

  // ===========================================================================
  // 4. PRD SCREEN 3: VENDOR QUOTATIONS & COMPARISON WORKSPACE
  // ===========================================================================

  static final List<VendorQuotation> vendorQuotations = [
    // Quote A for RFQ-001
    VendorQuotation(
      id: 'vq-101',
      vendorQuoteNumber: 'QT-CEN-2026-881',
      rfqId: 'rfq-001',
      rfqNumber: 'RFQ-2026-00084',
      vendorId: 'VND-001',
      vendorName: 'Century Wholesale Hub',
      vendorCode: 'VND-CEN-01',
      projectId: 'PRJ-CAM-01',
      projectName: 'The Camellias Villa Interior #1402',
      quoteDate: DateTime(2026, 9, 5),
      validUntil: DateTime(2026, 9, 20),
      contactPerson: 'Sunil Aggarwal',
      contactNumber: '+91 98101 33412',
      contactEmail: 'sales@centuryhub.in',
      subtotal: 184500,
      discount: 3500,
      tax: 32580,
      freight: 2500,
      grandTotal: 216080,
      paymentTerms: '50% Advance with PO, 50% on Site Unloading',
      advancePercent: 50,
      creditPeriod: '0 Days',
      deliveryTimeline: '2 Days (Direct Hub Dispatch)',
      warrantyPeriod: '25 Years Warranty (IS:710 Marine)',
      quoteValidity: '15 Days',
      scorecard: VendorScorecard(
        rateScore: 8.5,
        qualityScore: 9.2,
        trustScore: 9.0,
        timelineScore: 9.5,
        warrantyScore: 9.8,
        overallRating: 4.8,
        feedback: 'Top-tier calibrated ply, zero thickness variance across 45 sheets.',
        evaluatedBy: 'Amit Kumar',
        evaluatedDate: DateTime(2026, 9, 6),
      ),
      items: const [
        VendorQuotationItem(
          itemName: 'Century Club Prime BWP Marine Plywood 19mm',
          materialSpecification: 'IS:710 Marine Calibrated 19mm',
          brand: 'Century Club Prime',
          quantity: 45,
          unit: 'Sheets (8x4)',
          unitRate: 2820,
          total: 126900,
          deliveryDays: '2 Days',
          warrantyPeriod: '25 Years',
        ),
        VendorQuotationItem(
          itemName: 'Häfele Soft-Close Tandembox Antaro 500mm',
          materialSpecification: 'Blumotion 65kg Silk White',
          brand: 'Häfele',
          quantity: 16,
          unit: 'Sets',
          unitRate: 3600,
          total: 57600,
          deliveryDays: '2 Days',
          warrantyPeriod: '10 Years',
        ),
      ],
      status: VendorQuotationStatus.recommended,
      recommendationRationale: '✓ Lowest lead time (2 days) • Highest quality score (9.2/10) • 25-yr warranty certified',
    ),
    // Quote B for RFQ-001
    VendorQuotation(
      id: 'vq-102',
      vendorQuoteNumber: 'QT-AUS-2026-442',
      rfqId: 'rfq-001',
      rfqNumber: 'RFQ-2026-00084',
      vendorId: 'VND-002',
      vendorName: 'Austin Plywood Regional Depot',
      vendorCode: 'VND-AUS-02',
      projectId: 'PRJ-CAM-01',
      projectName: 'The Camellias Villa Interior #1402',
      quoteDate: DateTime(2026, 9, 5),
      validUntil: DateTime(2026, 9, 20),
      contactPerson: 'Ramesh Bansal',
      contactNumber: '+91 98112 44900',
      contactEmail: 'quotes@austindepot.com',
      subtotal: 178200,
      discount: 2000,
      tax: 31716,
      freight: 4500,
      grandTotal: 212416,
      paymentTerms: '100% on Delivery Verification',
      advancePercent: 0,
      creditPeriod: '7 Days',
      deliveryTimeline: '4 Days (Delhi Depot)',
      warrantyPeriod: '20 Years Warranty',
      quoteValidity: '15 Days',
      scorecard: VendorScorecard(
        rateScore: 9.0,
        qualityScore: 8.4,
        trustScore: 8.6,
        timelineScore: 8.0,
        warrantyScore: 8.5,
        overallRating: 4.6,
        feedback: 'Competitive rate. 2-day slower delivery from Delhi depot.',
        evaluatedBy: 'Amit Kumar',
        evaluatedDate: DateTime(2026, 9, 6),
      ),
      items: const [
        VendorQuotationItem(
          itemName: 'Austin Defender BWP Marine Plywood 19mm',
          materialSpecification: 'IS:710 Marine 19mm',
          brand: 'Austin Defender',
          quantity: 45,
          unit: 'Sheets (8x4)',
          unitRate: 2680,
          total: 120600,
          deliveryDays: '4 Days',
          warrantyPeriod: '20 Years',
        ),
        VendorQuotationItem(
          itemName: 'Häfele Soft-Close Tandembox Antaro 500mm',
          materialSpecification: 'Hettich Atira Alternative',
          brand: 'Hettich',
          quantity: 16,
          unit: 'Sets',
          unitRate: 3600,
          total: 57600,
          deliveryDays: '4 Days',
          warrantyPeriod: '10 Years',
        ),
      ],
      status: VendorQuotationStatus.shortlisted,
    ),
    // Quote C for RFQ-001
    VendorQuotation(
      id: 'vq-103',
      vendorQuoteNumber: 'QT-GRN-2026-902',
      rfqId: 'rfq-001',
      rfqNumber: 'RFQ-2026-00084',
      vendorId: 'VND-003',
      vendorName: 'Greenply Metro Distributors',
      vendorCode: 'VND-GRN-03',
      projectId: 'PRJ-CAM-01',
      projectName: 'The Camellias Villa Interior #1402',
      quoteDate: DateTime(2026, 9, 6),
      validUntil: DateTime(2026, 9, 20),
      contactPerson: 'Deepak Chopra',
      contactNumber: '+91 99105 88210',
      contactEmail: 'procure@greenplymetro.in',
      subtotal: 191400,
      discount: 0,
      tax: 34452,
      freight: 1500,
      grandTotal: 227352,
      paymentTerms: '100% Advance via NEFT',
      advancePercent: 100,
      creditPeriod: '0 Days',
      deliveryTimeline: '3 Days',
      warrantyPeriod: '25 Years Warranty',
      quoteValidity: '10 Days',
      scorecard: VendorScorecard(
        rateScore: 7.8,
        qualityScore: 9.0,
        trustScore: 8.8,
        timelineScore: 8.5,
        warrantyScore: 9.5,
        overallRating: 4.7,
        feedback: 'Higher unit rate with 100% advance demand.',
        evaluatedBy: 'Amit Kumar',
        evaluatedDate: DateTime(2026, 9, 6),
      ),
      items: const [
        VendorQuotationItem(
          itemName: 'Green 710 Premium Marine Plywood 19mm',
          materialSpecification: 'IS:710 Calibrated 19mm',
          brand: 'Greenply',
          quantity: 45,
          unit: 'Sheets (8x4)',
          unitRate: 2920,
          total: 131400,
          deliveryDays: '3 Days',
          warrantyPeriod: '25 Years',
        ),
      ],
      status: VendorQuotationStatus.received,
    ),
  ];

  // ===========================================================================
  // 5. PRD SCREEN 4: PURCHASE ORDERS (Complete Enterprise POs)
  // ===========================================================================

  static final List<PurchaseOrder> purchaseOrders = [
    PurchaseOrder(
      id: 'po-001',
      poNumber: 'PO-2026-00142',
      poDate: DateTime(2026, 9, 6),
      vendorId: 'VND-001',
      vendorLegalName: 'Century Wholesale Hub Private Limited',
      vendorCode: 'VND-CEN-01',
      gstin: '07AABCC8810K1ZT',
      pan: 'AABCC8810K',
      vendorContactPerson: 'Sunil Aggarwal (Director - Institutional Sales)',
      vendorMobile: '+91 98101 33412',
      vendorEmail: 'sales@centuryhub.in',
      shippingAddress: 'The Camellias, Tower 2, Flat 1402, Golf Course Road, DLF Phase 5, Gurugram - 122002',
      rfqId: 'rfq-001',
      rfqNumber: 'RFQ-2026-00084',
      vendorQuoteId: 'vq-101',
      vendorQuoteNumber: 'QT-CEN-2026-881',
      materialRequestId: 'mr-001',
      materialRequestNumber: 'MR-2026-00124',
      projectId: 'PRJ-CAM-01',
      projectName: 'The Camellias Villa Interior #1402',
      customerId: 'CUST-RS-01',
      customerName: 'Rahul Sharma',
      siteAddress: 'The Camellias, Golf Course Road, DLF Phase 5, Gurugram',
      procurementOwner: 'Amit Kumar',
      expectedDeliveryDate: DateTime(2026, 9, 9),
      advancePercent: 50.0,
      advanceAmount: 108040.0,
      creditPeriod: '15 Days',
      retentionPercent: 5.0,
      tax: 32580.0,
      grandTotal: 216080.0,
      paidAmount: 108040.0,
      items: [
        PurchaseOrderItem(
          id: 'poi-1',
          itemName: 'Century Club Prime BWP Marine Plywood 19mm',
          itemCode: 'MAT-PLY-710-19',
          specification: 'IS:710 Marine Calibrated 19mm (8ft x 4ft)',
          quantity: 45,
          unit: 'Sheets (8x4)',
          rate: 2820,
          amount: 126900,
          requiredDate: DateTime(2026, 9, 9),
          expectedDelivery: DateTime(2026, 9, 9),
        ),
        PurchaseOrderItem(
          id: 'poi-2',
          itemName: 'Häfele Soft-Close Tandembox Antaro 500mm',
          itemCode: 'MAT-HAF-TB-500',
          specification: 'Blumotion 65kg Dynamic Silk White Runner Kit',
          quantity: 16,
          unit: 'Sets',
          rate: 3600,
          amount: 57600,
          requiredDate: DateTime(2026, 9, 9),
          expectedDelivery: DateTime(2026, 9, 9),
        ),
      ],
      status: PurchaseOrderStatus.vendorAcknowledged,
      dispatchStatus: MaterialDispatchStatus.dispatched,
      timeline: [
        ProcurementTimelineEvent(
          id: 'po-tl-1',
          timestamp: DateTime(2026, 9, 6, 14, 0),
          title: 'PO Generated & Approved',
          description: 'Approved by Ops Head & Accounts Director',
          actorName: 'Amit Kumar',
          actorRole: 'Operations Head',
          icon: Icons.verified_rounded,
        ),
        ProcurementTimelineEvent(
          id: 'po-tl-2',
          timestamp: DateTime(2026, 9, 6, 16, 30),
          title: 'Vendor Acknowledged & Advance Received',
          description: 'Century Wholesale Hub confirmed dispatch date Sep 8',
          actorName: 'Sunil Aggarwal',
          actorRole: 'Vendor Admin',
          icon: Icons.handshake_rounded,
        ),
      ],
    ),
    PurchaseOrder(
      id: 'po-002',
      poNumber: 'PO-2026-00143',
      poDate: DateTime(2026, 9, 4),
      vendorId: 'VND-004',
      vendorLegalName: 'Classic Marble Company Private Limited',
      vendorCode: 'VND-CMC-01',
      gstin: '27AAACG1920L1Z9',
      pan: 'AAACG1920L',
      vendorContactPerson: 'Amitabh Jha (VP - Luxury Projects)',
      vendorMobile: '+91 98200 99182',
      vendorEmail: 'luxury@classicmarble.com',
      shippingAddress: 'Oberoi Sky City, Tower A, Penthouse 2201, Western Express Hwy, Borivali East, Mumbai - 400066',
      rfqId: 'rfq-002',
      rfqNumber: 'RFQ-2026-00085',
      vendorQuoteId: 'vq-201',
      vendorQuoteNumber: 'QT-CMC-2026-092',
      materialRequestId: 'mr-002',
      materialRequestNumber: 'MR-2026-00125',
      projectId: 'PRJ-OBS-02',
      projectName: 'Oberoi Sky City Luxury Penthouse #A-2201',
      customerId: 'CUST-AS-02',
      customerName: 'Dr. Arjun Singhania',
      siteAddress: 'Western Express Hwy, Borivali East, Mumbai',
      procurementOwner: 'Vikram Malhotra',
      expectedDeliveryDate: DateTime(2026, 9, 14),
      advancePercent: 60.0,
      advanceAmount: 734400.0,
      tax: 224000.0,
      grandTotal: 1224000.0,
      paidAmount: 734400.0,
      items: [
        PurchaseOrderItem(
          id: 'poi-3',
          itemName: 'Italian Statuario Marble Slabs 20mm',
          itemCode: 'MAT-MRB-STAT-20',
          specification: 'Statuario Extra Lot #ST-881, Bookmatched Pairs',
          quantity: 1200,
          unit: 'Sq.Ft.',
          rate: 850,
          amount: 1020000,
          requiredDate: DateTime(2026, 9, 14),
          expectedDelivery: DateTime(2026, 9, 14),
        ),
      ],
      status: PurchaseOrderStatus.sentToVendor,
      dispatchStatus: MaterialDispatchStatus.ready,
    ),
  ];

  // ===========================================================================
  // 6. PRD SCREEN 5: MATERIAL DISPATCH & SITE RECEIPT INSPECTIONS
  // ===========================================================================

  static final List<MaterialDispatch> materialDispatches = [
    MaterialDispatch(
      id: 'dsp-001',
      dispatchNumber: 'DSP-2026-00091',
      poId: 'po-001',
      poNumber: 'PO-2026-00142',
      vendorName: 'Century Wholesale Hub Private Limited',
      projectId: 'PRJ-CAM-01',
      projectName: 'The Camellias Villa Interior #1402',
      customerName: 'Rahul Sharma',
      siteAddress: 'The Camellias, Golf Course Road, DLF Phase 5, Gurugram',
      dispatchDate: DateTime(2026, 9, 7, 09, 30),
      expectedArrival: DateTime(2026, 9, 8, 14, 00),
      actualArrival: DateTime(2026, 9, 8, 13, 45),
      destination: 'The Camellias Site Staging Area (Basement Level 2)',
      dispatchOwner: 'Vikram Malhotra',
      transporterName: 'VRL Logistics Logistics Dedicated Carrier',
      transporterContact: '+91 98112 00192',
      vehicleNumber: 'HR 26 DQ 8812',
      driverName: 'Mohinder Singh',
      driverContact: '+91 99102 77102',
      lrNumber: 'VRL-GGN-2026-9921',
      trackingNumber: 'TRK-HR26-8812-LIVE',
      eWayBillNumber: '2810 9920 4410',
      freightCharges: 2500,
      transportNotes: 'Dedicated flatbed vehicle with water-resistant tarpaulin tie-downs.',
      items: const [
        DispatchItem(
          itemName: 'Century Club Prime BWP Marine Plywood 19mm',
          poQuantity: 45,
          previouslyDispatched: 0,
          currentDispatchQuantity: 45,
          unit: 'Sheets (8x4)',
          batchLot: 'LOT-CEN-SEP26-04',
          remarks: 'All 45 sheets sealed with factory QA stamp',
        ),
        DispatchItem(
          itemName: 'Häfele Soft-Close Tandembox Antaro 500mm',
          poQuantity: 16,
          previouslyDispatched: 0,
          currentDispatchQuantity: 16,
          unit: 'Sets',
          batchLot: 'HAF-BLUM-9921',
          remarks: 'Master box sealed with tamper tape',
        ),
      ],
      receiptChecklist: const [
        SiteReceiptItem(
          itemName: 'Century Club Prime BWP Marine Plywood 19mm',
          dispatchedQuantity: 45,
          quantityReceived: 45,
          quantityAccepted: 45,
          quantityRejected: 0,
          shortQuantity: 0,
          damagedQuantity: 0,
          condition: MaterialItemCondition.good,
          remarks: 'Verified IS:710 watermark and digital caliper thickness 19.1mm.',
        ),
        SiteReceiptItem(
          itemName: 'Häfele Soft-Close Tandembox Antaro 500mm',
          dispatchedQuantity: 16,
          quantityReceived: 16,
          quantityAccepted: 15,
          quantityRejected: 1,
          shortQuantity: 0,
          damagedQuantity: 1,
          condition: MaterialItemCondition.damaged,
          remarks: '1 runner set gallery rail bent during transit unloading. Replacement dispatched.',
        ),
      ],
      siteSupervisorSignature: 'Rajesh Verma (Digital Site QA Seal)',
      deliveryProofUrl: 'https://cdn.homio.in/proofs/CAM-DSP-00091-RECEIPT.pdf',
      status: MaterialDispatchStatus.partiallyReceived,
      timeline: [
        ProcurementTimelineEvent(
          id: 'dsp-tl-1',
          timestamp: DateTime(2026, 9, 7, 10, 0),
          title: 'Dispatched from Vendor Warehouse',
          description: 'Vehicle HR 26 DQ 8812 loaded and dispatched with E-Way Bill 2810 9920 4410.',
          actorName: 'Mohinder Singh',
          actorRole: 'Transporter Driver',
          icon: Icons.local_shipping_rounded,
        ),
        ProcurementTimelineEvent(
          id: 'dsp-tl-2',
          timestamp: DateTime(2026, 9, 8, 14, 15),
          title: 'Site Delivery & Inspection Completed',
          description: '45 Plywood sheets accepted (Good). 15 Hafele sets accepted, 1 set rejected (damaged rail).',
          actorName: 'Rajesh Verma',
          actorRole: 'Site Supervisor',
          icon: Icons.fact_check_rounded,
        ),
      ],
    ),
    MaterialDispatch(
      id: 'dsp-002',
      dispatchNumber: 'DSP-2026-00092',
      poId: 'po-002',
      poNumber: 'PO-2026-00143',
      vendorName: 'Classic Marble Company Private Limited',
      projectId: 'PRJ-OBS-02',
      projectName: 'Oberoi Sky City Luxury Penthouse #A-2201',
      customerName: 'Dr. Arjun Singhania',
      siteAddress: 'Western Express Hwy, Borivali East, Mumbai',
      dispatchDate: DateTime(2026, 9, 8, 08, 00),
      expectedArrival: DateTime(2026, 9, 10, 16, 00),
      destination: 'Oberoi Penthouse Heavy Unloading Bay',
      dispatchOwner: 'Vikram Malhotra',
      transporterName: 'Om Shanti Heavy Craters & Rigging',
      transporterContact: '+91 98200 44109',
      vehicleNumber: 'MH 04 FK 4410',
      driverName: 'Kallu Yadav',
      driverContact: '+91 98221 11200',
      lrNumber: 'LR-CMC-MUM-4491',
      trackingNumber: 'GPS-MH04FK4410',
      eWayBillNumber: '2910 8821 0092',
      freightCharges: 18000,
      transportNotes: 'A-frame wooden crate packaging with shock sensors for marble slabs.',
      items: const [
        DispatchItem(
          itemName: 'Italian Statuario Marble Slabs 20mm',
          poQuantity: 1200,
          previouslyDispatched: 0,
          currentDispatchQuantity: 1200,
          unit: 'Sq.Ft.',
          batchLot: 'LOT-ST-881',
          remarks: '6 Wooden A-frame crates, bookmatch slab sequence 1-12',
        ),
      ],
      status: MaterialDispatchStatus.inTransit,
    ),
  ];

  // ===========================================================================
  // 7. PRD SCREEN 6: DESIGN PAYMENT REQUESTS (Full Milestone Requests)
  // ===========================================================================

  static final List<DesignPaymentRequest> designPaymentRequests = [
    DesignPaymentRequest(
      id: 'dpr-001',
      requestNumber: 'DPR-2026-00045',
      requestDate: DateTime(2026, 9, 1),
      designerName: 'Ananya Roy',
      designerRole: 'Principal Interior Architect',
      isContractor: false,
      projectId: 'PRJ-CAM-01',
      projectName: 'The Camellias Villa Interior #1402',
      customerName: 'Rahul Sharma',
      designType: 'Luxury Turnkey Interior Design',
      designStage: 'Stage 3: GFC & Working CAD Drawings Handover',
      milestoneTitle: 'GFC CAD Handover & Electrical Layout Sign-off',
      milestonePercent: 25.0,
      dueDate: DateTime(2026, 9, 10),
      workPeriod: 'Aug 15 - Aug 31, 2026',
      contractAmount: 350000,
      eligibleAmount: 87500,
      previouslyPaid: 175000,
      currentRequest: 87500,
      adjustment: 0,
      deductions: 0,
      netPayable: 87500,
      deliverablesCompletedPercent: 100,
      filesSubmittedCount: 18,
      filesApprovedCount: 18,
      filesPendingCount: 0,
      clientApprovalStatus: 'Approved on In-Person Review Meeting',
      executionHandoverStatus: 'Handed over to Site PM Rajesh Verma',
      revisionCount: 1,
      verificationNotes: 'All 18 GFC sheets (false ceiling, conduit, plumbing, millwork joinery) verified by Technical Director.',
      supervisorFeedback: 'Exceptional drawing clarity with zero site queries raised by carpentry gang.',
      googleDriveUrl: 'https://drive.google.com/drive/folders/homio-camellias-1402-gfc',
      paymentMethod: 'NEFT Bank Transfer',
      bankReference: 'HDFC-NEFT-99210044',
      paymentReference: 'PAY-DES-CAM-03',
      transactionId: 'TXN-9912044812',
      paidDate: DateTime(2026, 9, 4),
      status: DesignPaymentStatus.paid,
      timeline: [
        ProcurementTimelineEvent(
          id: 'dpr-tl-1',
          timestamp: DateTime(2026, 9, 1, 11, 0),
          title: 'Design Payment Request Submitted',
          description: 'Raised by Ananya Roy for Stage 3 GFC Handover (18/18 files approved)',
          actorName: 'Ananya Roy',
          actorRole: 'Principal Architect',
          icon: Icons.upload_file_rounded,
        ),
        ProcurementTimelineEvent(
          id: 'dpr-tl-2',
          timestamp: DateTime(2026, 9, 2, 16, 0),
          title: 'Technical Director Verification Completed',
          description: 'All drawings verified against site structural grid',
          actorName: 'Karan Mehra',
          actorRole: 'Design Director',
          icon: Icons.verified_rounded,
        ),
        ProcurementTimelineEvent(
          id: 'dpr-tl-3',
          timestamp: DateTime(2026, 9, 4, 12, 30),
          title: 'Payment Disbursed to Designer Account',
          description: '₹87,500 transferred via HDFC NEFT Ref HDFC-NEFT-99210044',
          actorName: 'Finance Desk',
          actorRole: 'Accounts Manager',
          icon: Icons.account_balance_rounded,
        ),
      ],
    ),
    DesignPaymentRequest(
      id: 'dpr-002',
      requestNumber: 'DPR-2026-00046',
      requestDate: DateTime(2026, 9, 5),
      designerName: 'Rohan Deshpande',
      designerRole: 'Lead 3D Visualizer & Lighting Designer',
      isContractor: true,
      projectId: 'PRJ-OBS-02',
      projectName: 'Oberoi Sky City Luxury Penthouse #A-2201',
      customerName: 'Dr. Arjun Singhania',
      designType: 'Photorealistic CGI & VR Walkthrough',
      designStage: 'Stage 2: 3D Render Sign-off & VR Model',
      milestoneTitle: 'Photorealistic 3D Renders (8 Views) & 360 Panorama',
      milestonePercent: 30.0,
      dueDate: DateTime(2026, 9, 15),
      workPeriod: 'Aug 20 - Sep 04, 2026',
      contractAmount: 180000,
      eligibleAmount: 54000,
      previouslyPaid: 54000,
      currentRequest: 54000,
      adjustment: 0,
      deductions: 0,
      netPayable: 54000,
      deliverablesCompletedPercent: 90,
      filesSubmittedCount: 10,
      filesApprovedCount: 8,
      filesPendingCount: 2,
      clientApprovalStatus: 'Pending Final Master Bedroom Render Re-tone',
      executionHandoverStatus: 'In Progress',
      revisionCount: 2,
      verificationNotes: 'Client Dr. Singhania requested warm champagne mood lighting for Master Bed.',
      supervisorFeedback: 'Renders look ultra-premium, pending 2 revised daytime camera angles.',
      googleDriveUrl: 'https://drive.google.com/drive/folders/homio-oberoi-3d-renders',
      status: DesignPaymentStatus.underVerification,
    ),
  ];

  // ===========================================================================
  // 8. PRD SCREEN 7: WEEKLY / SATURDAY FEES & WHATSAPP ENGINE
  // ===========================================================================

  static final List<WeeklyFee> weeklyFees = [
    WeeklyFee(
      id: 'wkf-001',
      feeCode: 'WKF-2026-W36-01',
      weekPeriod: 'Week 36 (01 Sep - 07 Sep 2026)',
      weekStartDate: DateTime(2026, 9, 1),
      weekEndDate: DateTime(2026, 9, 7),
      feeDate: DateTime(2026, 9, 8),
      paymentDueDate: DateTime(2026, 9, 11),
      paymentRequestDate: DateTime(2026, 9, 8, 10, 0),
      projectId: 'PRJ-CAM-01',
      projectName: 'The Camellias Villa Interior #1402',
      customerId: 'CUST-RS-01',
      customerName: 'Rahul Sharma',
      customerPhone: '+91 98101 44550',
      siteAddress: 'The Camellias, Golf Course Road, DLF Phase 5, Gurugram',
      projectManager: 'Amit Kumar',
      siteSupervisor: 'Rajesh Verma',
      department: 'Turnkey Luxury Fitouts',
      // Segregated amounts
      materialAmount: 125000,
      materialBills: [
        FeeBillItem(
          billNumber: 'BILL-MAT-101',
          billDate: DateTime(2026, 9, 2),
          recipientName: 'Century Wholesale Hub',
          description: 'Plywood & Framing Carcass Advance',
          amount: 45000,
          paidAmount: 45000,
          isPaid: true,
          notes: 'Covered under advance voucher #ADV-881',
        ),
        FeeBillItem(
          billNumber: 'BILL-MAT-102',
          billDate: DateTime(2026, 9, 5),
          recipientName: 'Berger Architectural Paints Store',
          description: 'Epoxy primers, masking tape & putty',
          amount: 80000,
          paidAmount: 0,
          isPaid: false,
          notes: 'Invoice #BER-991 verified by supervisor',
        ),
      ],
      labourAmount: 85000,
      labourBills: [
        FeeBillItem(
          billNumber: 'BILL-LAB-201',
          billDate: DateTime(2026, 9, 6),
          recipientName: 'Master Jiwan Carpentry Gang (8 Artisans)',
          description: '6 Days framing, carcass leveling & edge banding',
          amount: 55000,
          paidAmount: 55000,
          isPaid: true,
          notes: 'Disbursed via UPI directly on Saturday eve',
        ),
        FeeBillItem(
          billNumber: 'BILL-LAB-202',
          billDate: DateTime(2026, 9, 7),
          recipientName: 'Praveen MEP & Electrical Team',
          description: 'Wall chasing, box fixing & conduit pulling',
          amount: 30000,
          paidAmount: 0,
          isPaid: false,
          notes: 'Scheduled for release upon site supervisor sign-off',
        ),
      ],
      supervisionFees: 15000,
      consultingFees: 10000,
      otherApprovedFees: 0,
      feeNotes: 'Weekly site operations & architectural oversight retainer (Clause 5.1)',
      totalAmount: 235000,
      paidAmount: 100000,
      status: WeeklyFeeStatus.approved,
      whatsappStatus: 'Delivered',
      whatsappSentAt: DateTime(2026, 9, 8, 10, 02),
      paymentLinkUrl: 'https://pay.homio.in/w/CAM-W36-RS01',
      timeline: [
        ProcurementTimelineEvent(
          id: 'wkf-tl-1',
          timestamp: DateTime(2026, 9, 8, 09, 30),
          title: 'Weekly Fee Auto-Calculated by Saturday Engine',
          description: 'Aggregated Material (₹1,25,000) + Labour (₹85,000) + Fees (₹25,000) = ₹2,35,000',
          actorName: 'Homio Automation Bot',
          actorRole: 'System Core',
          icon: Icons.smart_toy_rounded,
        ),
        ProcurementTimelineEvent(
          id: 'wkf-tl-2',
          timestamp: DateTime(2026, 9, 8, 10, 02),
          title: 'WhatsApp Payment Request Dispatched',
          description: 'Sent to Rahul Sharma (+91 98101 44550). Status: Delivered.',
          actorName: 'WhatsApp Cloud API',
          actorRole: 'Homio Communication',
          icon: Icons.send_to_mobile_rounded,
        ),
      ],
    ),
    WeeklyFee(
      id: 'wkf-002',
      feeCode: 'WKF-2026-W36-02',
      weekPeriod: 'Week 36 (01 Sep - 07 Sep 2026)',
      weekStartDate: DateTime(2026, 9, 1),
      weekEndDate: DateTime(2026, 9, 7),
      feeDate: DateTime(2026, 9, 8),
      paymentDueDate: DateTime(2026, 9, 12),
      paymentRequestDate: DateTime(2026, 9, 8, 10, 0),
      projectId: 'PRJ-OBS-02',
      projectName: 'Oberoi Sky City Luxury Penthouse #A-2201',
      customerId: 'CUST-AS-02',
      customerName: 'Dr. Arjun Singhania',
      customerPhone: '+91 98200 88210',
      siteAddress: 'Western Express Hwy, Borivali East, Mumbai',
      projectManager: 'Vikram Malhotra',
      siteSupervisor: 'Mahesh Kadam',
      department: 'Civil & Architectural Finishes',
      materialAmount: 340000,
      materialBills: [
        FeeBillItem(
          billNumber: 'BILL-MAT-301',
          billDate: DateTime(2026, 9, 4),
          recipientName: 'Classic Marble Depot',
          description: 'Italian Marble Dry-Lay Reservation Deposit',
          amount: 340000,
          paidAmount: 340000,
          isPaid: true,
        ),
      ],
      labourAmount: 110000,
      labourBills: [
        FeeBillItem(
          billNumber: 'BILL-LAB-401',
          billDate: DateTime(2026, 9, 6),
          recipientName: 'Rajasthan Marble Polishers (12 Artisans)',
          description: 'Floor leveling, diamond grinding & curing',
          amount: 110000,
          paidAmount: 50000,
          isPaid: false,
        ),
      ],
      supervisionFees: 20000,
      consultingFees: 15000,
      otherApprovedFees: 5000,
      totalAmount: 490000,
      paidAmount: 390000,
      status: WeeklyFeeStatus.paymentRequested,
      whatsappStatus: 'Read',
      whatsappSentAt: DateTime(2026, 9, 8, 10, 02),
      paymentLinkUrl: 'https://pay.homio.in/w/OBS-W36-AS02',
    ),
  ];

  // ===========================================================================
  // 9. SATURDAY AUTOMATION ENGINE CONFIGURATION & AUDIT LOGS
  // ===========================================================================

  static const SaturdayAutomationConfig saturdayAutomationConfig = SaturdayAutomationConfig(
    isEnabled: true,
    frequency: 'Weekly',
    dayOfWeek: 'Saturday',
    executionTime: '10:00 AM',
    generateRequest: true,
    sendWhatsApp: true,
    sendEmail: true,
    managerReviewRequired: true,
    accountsReviewRequired: true,
  );

  static final List<SaturdayAutomationLog> saturdayAutomationLogs = [
    SaturdayAutomationLog(
      id: 'sat-log-01',
      executionDate: DateTime(2026, 9, 5, 10, 0),
      weekPeriod: 'Week 35 (24 Aug - 31 Aug 2026)',
      feeCount: 14,
      totalValue: 2840000,
      status: 'Delivered',
    ),
    SaturdayAutomationLog(
      id: 'sat-log-02',
      executionDate: DateTime(2026, 8, 29, 10, 0),
      weekPeriod: 'Week 34 (17 Aug - 23 Aug 2026)',
      feeCount: 12,
      totalValue: 2450000,
      status: 'Delivered',
    ),
    SaturdayAutomationLog(
      id: 'sat-log-03',
      executionDate: DateTime(2026, 8, 22, 10, 0),
      weekPeriod: 'Week 33 (10 Aug - 16 Aug 2026)',
      feeCount: 11,
      totalValue: 2190000,
      status: 'Delivered',
    ),
  ];

  // ===========================================================================
  // 10. CUSTOMER 360° & PROJECT PROCUREMENT SUMMARIES
  // ===========================================================================

  static final List<CustomerOperationsSummary> customerSummaries = [
    const CustomerOperationsSummary(
      customerId: 'CUST-RS-01',
      customerName: 'Rahul Sharma',
      projectId: 'PRJ-CAM-01',
      projectName: 'The Camellias Villa Interior #1402',
      materialTotal: 840000,
      materialPaid: 620000,
      materialDue: 220000,
      labourTotal: 510000,
      labourPaid: 400000,
      labourDue: 110000,
      feesTotal: 125000,
      feesPaid: 75000,
      feesDue: 50000,
    ),
    const CustomerOperationsSummary(
      customerId: 'CUST-AS-02',
      customerName: 'Dr. Arjun Singhania',
      projectId: 'PRJ-OBS-02',
      projectName: 'Oberoi Sky City Luxury Penthouse #A-2201',
      materialTotal: 1420000,
      materialPaid: 1100000,
      materialDue: 320000,
      labourTotal: 680000,
      labourPaid: 520000,
      labourDue: 160000,
      feesTotal: 180000,
      feesPaid: 120000,
      feesDue: 60000,
    ),
  ];

  static final List<ProjectProcurementSummary> projectSummaries = [
    const ProjectProcurementSummary(
      projectId: 'PRJ-CAM-01',
      projectName: 'The Camellias Villa Interior #1402',
      materialRequestsCount: 12,
      rfqsCount: 8,
      vendorQuotesCount: 18,
      approvedVendorsCount: 6,
      poCount: 7,
      dispatchCount: 5,
      materialCost: 1240000,
      labourCost: 780000,
      feesCost: 125000,
      approvedQuotationValue: 2850000,
    ),
  ];
}
