import 'operations_models.dart';

class OperationsMockData {
  // 1. Material Requisition Indents with Multi-Vendor Bids
  static final List<MaterialRequisitionIndent> indents = [
    MaterialRequisitionIndent(
      id: 'IND-8821',
      projectTitle: 'DLF Magnolias #402, Gurugram',
      clientName: 'Rajeev Singhania',
      siteSupervisor: 'Rajesh Verma',
      itemName: 'Century Club Prime BWP Marine Plywood 19mm',
      quantity: 45,
      unit: 'Sheets (8x4)',
      requiredDate: DateTime.now().add(const Duration(days: 2)),
      urgency: IndentUrgency.urgent,
      status: IndentStatus.bidsReceived,
      notes: 'Required urgently for Master Bedroom walk-in wardrobe carcasses & framing.',
      bids: [
        const VendorBid(
          id: 'BID-01',
          vendorName: 'Century Wholesale Hub, DLF Phase 2',
          vendorRating: 4.8,
          unitPrice: 2850,
          totalPrice: 128250,
          gstPercent: 18,
          deliveryDays: 1,
          qualityGrade: 'IS:710 Marine Certified (Calibrated)',
          warrantyMonths: 300, // 25 years
          paymentTerms: '100% Advance via Homio Pay',
          isSelected: true,
        ),
        const VendorBid(
          id: 'BID-02',
          vendorName: 'Austin Plywood Regional Depot, Delhi',
          vendorRating: 4.6,
          unitPrice: 2680,
          totalPrice: 120600,
          gstPercent: 18,
          deliveryDays: 2,
          qualityGrade: 'Austin Defender BWP Grade',
          warrantyMonths: 240, // 20 years
          paymentTerms: '50% Advance, 50% on Site Unloading',
        ),
        const VendorBid(
          id: 'BID-03',
          vendorName: 'Greenply Metro Timber Mart, Gurugram',
          vendorRating: 4.7,
          unitPrice: 2920,
          totalPrice: 131400,
          gstPercent: 18,
          deliveryDays: 1,
          qualityGrade: 'Green 710 Premium Marine',
          warrantyMonths: 300,
          paymentTerms: '100% on Dispatch Note',
        ),
      ],
      approvedBidId: 'BID-01',
      clientPaymentUrl: 'https://pay.homio.in/inv/DLF-MR-8821',
    ),
    MaterialRequisitionIndent(
      id: 'IND-8822',
      projectTitle: 'Trump Towers #2104, Golf Course Ext.',
      clientName: 'Kavita Chawla',
      siteSupervisor: 'Amitabh Sharma',
      itemName: 'Häfele Soft-Close Tandembox Drawers (500mm Antaro)',
      quantity: 24,
      unit: 'Sets',
      requiredDate: DateTime.now().add(const Duration(days: 4)),
      urgency: IndentUrgency.standard,
      status: IndentStatus.bidsReceived,
      notes: 'Kitchen island and base units Blum/Hafele hardware specification.',
      bids: [
        const VendorBid(
          id: 'BID-11',
          vendorName: 'Hafele Direct Corporate Channel, Okhla',
          vendorRating: 4.9,
          unitPrice: 4200,
          totalPrice: 100800,
          gstPercent: 18,
          deliveryDays: 2,
          qualityGrade: 'Blumotion Integrated Dynamic 65kg',
          warrantyMonths: 120, // 10 years
          paymentTerms: 'Immediate Online Card / UPI',
        ),
        const VendorBid(
          id: 'BID-12',
          vendorName: 'Hettich Hardware Studio, Gurugram',
          vendorRating: 4.7,
          unitPrice: 3950,
          totalPrice: 94800,
          gstPercent: 18,
          deliveryDays: 3,
          qualityGrade: 'InnoTech Atira Soft-Close System',
          warrantyMonths: 120,
          paymentTerms: 'Net 7 Days on Verification',
        ),
      ],
    ),
    MaterialRequisitionIndent(
      id: 'IND-8823',
      projectTitle: 'Lodha Altamount #18A, Mumbai',
      clientName: 'Vikramaditya Shroff',
      siteSupervisor: 'Suresh Patil',
      itemName: 'Saint-Gobain Planilaque Tinted Fluted Glass 8mm',
      quantity: 180,
      unit: 'Sq.Ft',
      requiredDate: DateTime.now().add(const Duration(days: 1)),
      urgency: IndentUrgency.urgent,
      status: IndentStatus.pendingRfq,
      notes: 'Dining area partition wall and custom crockery display unit.',
      bids: [],
    ),
    MaterialRequisitionIndent(
      id: 'IND-8819',
      projectTitle: 'Hiranandani Gardens #9B, Powai',
      clientName: 'Dr. Sameer Joshi',
      siteSupervisor: 'Mahesh Kadam',
      itemName: 'Asian Paints Royale Glitz Luxury Interior Emulsion (Truffle)',
      quantity: 80,
      unit: 'Litres',
      requiredDate: DateTime.now().subtract(const Duration(days: 2)),
      urgency: IndentUrgency.standard,
      status: IndentStatus.dispatched,
      approvedBidId: 'BID-99',
      clientPaymentUrl: 'https://pay.homio.in/inv/HIR-PT-8819',
      notes: 'Final coat painting scheduled for Saturday inspection.',
      bids: [
        const VendorBid(
          id: 'BID-99',
          vendorName: 'Asian Paints Wholesale Depot, Kanjurmarg',
          vendorRating: 4.9,
          unitPrice: 620,
          totalPrice: 49600,
          gstPercent: 18,
          deliveryDays: 1,
          qualityGrade: 'Royale Glitz Ultra-Sheen Teflon Coating',
          warrantyMonths: 60,
          paymentTerms: 'Paid via Homio Client Link',
          isSelected: true,
        ),
      ],
    ),
  ];

  // 2. Design Milestone Payment Links
  static final List<DesignPaymentMilestone> designMilestones = [
    DesignPaymentMilestone(
      id: 'DPM-101',
      projectTitle: 'DLF Magnolias #402',
      clientName: 'Rajeev Singhania',
      clientPhone: '+91 98101 22910',
      phaseTitle: 'Phase 1: 2D Spatial CAD Layouts & Floor Zoning (20%)',
      baseAmount: 65000,
      gstPercent: 18,
      status: PaymentLinkStatus.paid,
      paymentLinkUrl: 'https://pay.homio.in/design/DLF-2D-01',
      generatedDate: DateTime.now().subtract(const Duration(days: 18)),
      paidDate: DateTime.now().subtract(const Duration(days: 17)),
      invoiceNumber: 'HOM-DES-2026-048',
    ),
    DesignPaymentMilestone(
      id: 'DPM-102',
      projectTitle: 'DLF Magnolias #402',
      clientName: 'Rajeev Singhania',
      clientPhone: '+91 98101 22910',
      phaseTitle: 'Phase 2: 3D Photorealistic 4K Walkthrough Renders (30%)',
      baseAmount: 95000,
      gstPercent: 18,
      status: PaymentLinkStatus.pending,
      paymentLinkUrl: 'https://pay.homio.in/design/DLF-3D-02',
      generatedDate: DateTime.now().subtract(const Duration(days: 2)),
      invoiceNumber: 'HOM-DES-2026-072',
    ),
    DesignPaymentMilestone(
      id: 'DPM-103',
      projectTitle: 'Trump Towers #2104',
      clientName: 'Kavita Chawla',
      clientPhone: '+91 99204 88319',
      phaseTitle: 'Phase 1: 2D Spatial Layouts & Moodboards (20%)',
      baseAmount: 85000,
      gstPercent: 18,
      status: PaymentLinkStatus.paid,
      paymentLinkUrl: 'https://pay.homio.in/design/TT-2D-01',
      generatedDate: DateTime.now().subtract(const Duration(days: 12)),
      paidDate: DateTime.now().subtract(const Duration(days: 11)),
      invoiceNumber: 'HOM-DES-2026-059',
    ),
    DesignPaymentMilestone(
      id: 'DPM-104',
      projectTitle: 'Trump Towers #2104',
      clientName: 'Kavita Chawla',
      clientPhone: '+91 99204 88319',
      phaseTitle: 'Phase 3: GFC (Good-For-Construction) Working Drawings (50%)',
      baseAmount: 180000,
      gstPercent: 18,
      status: PaymentLinkStatus.pending,
      paymentLinkUrl: 'https://pay.homio.in/design/TT-GFC-03',
      generatedDate: DateTime.now().subtract(const Duration(hours: 14)),
      invoiceNumber: 'HOM-DES-2026-091',
    ),
    DesignPaymentMilestone(
      id: 'DPM-105',
      projectTitle: 'Lodha Altamount #18A',
      clientName: 'Vikramaditya Shroff',
      clientPhone: '+91 98200 11400',
      phaseTitle: 'Turnkey Luxury Architectural Consulting Retainer',
      baseAmount: 250000,
      gstPercent: 18,
      status: PaymentLinkStatus.disbursed,
      paymentLinkUrl: 'https://pay.homio.in/design/LODHA-RET-01',
      generatedDate: DateTime.now().subtract(const Duration(days: 25)),
      paidDate: DateTime.now().subtract(const Duration(days: 24)),
      invoiceNumber: 'HOM-DES-2026-033',
    ),
  ];

  // 3. Saturday Fee Auto-Dispatch Batches
  static final List<SaturdayFeeBatch> saturdayFees = [
    SaturdayFeeBatch(
      id: 'SAT-BATCH-01',
      projectName: 'DLF Magnolias #402',
      clientName: 'Rajeev Singhania',
      clientPhone: '+91 98101 22910',
      supervisorName: 'Rajesh Verma',
      currentStage: 'Modular Carpentry & Polishing',
      weekProgressPercent: 8.5,
      contractModel: 'Fixed Consulting',
      baseWeeklyFee: 35000,
      calculatedFee: 35000,
      adjustment: 0,
      status: SaturdayFeeStatus.scheduled,
      billingDate: _getNextSaturday(),
      invoiceRef: 'SAT-INV-2026-W36-01',
    ),
    SaturdayFeeBatch(
      id: 'SAT-BATCH-02',
      projectName: 'Trump Towers #2104',
      clientName: 'Kavita Chawla',
      clientPhone: '+91 99204 88319',
      supervisorName: 'Amitabh Sharma',
      currentStage: 'False Ceiling & Electrical Conduit MEP',
      weekProgressPercent: 12.0,
      contractModel: 'Percentage of Cost (12%)',
      baseWeeklyFee: 42000,
      calculatedFee: 48600, // Computed from material + labour spent this week
      adjustment: -2000, // Penalty rebate for 1-day material delay
      status: SaturdayFeeStatus.scheduled,
      billingDate: _getNextSaturday(),
      invoiceRef: 'SAT-INV-2026-W36-02',
    ),
    SaturdayFeeBatch(
      id: 'SAT-BATCH-03',
      projectName: 'Hiranandani Gardens #9B',
      clientName: 'Dr. Sameer Joshi',
      clientPhone: '+91 98331 44520',
      supervisorName: 'Mahesh Kadam',
      currentStage: 'Final Wall Painting & Deep Snagging',
      weekProgressPercent: 15.0,
      contractModel: 'Turnkey Contract Milestone',
      baseWeeklyFee: 50000,
      calculatedFee: 50000,
      adjustment: 0,
      status: SaturdayFeeStatus.sent,
      billingDate: _getPrevSaturday(),
      invoiceRef: 'SAT-INV-2026-W35-03',
    ),
    SaturdayFeeBatch(
      id: 'SAT-BATCH-04',
      projectName: 'Lodha Altamount #18A',
      clientName: 'Vikramaditya Shroff',
      clientPhone: '+91 98200 11400',
      supervisorName: 'Suresh Patil',
      currentStage: 'Italian Marble Honing & Civil Framing',
      weekProgressPercent: 10.0,
      contractModel: 'Fixed Consulting',
      baseWeeklyFee: 45000,
      calculatedFee: 45000,
      adjustment: 5000, // Extra site inspection on Sunday requested by client
      status: SaturdayFeeStatus.scheduled,
      billingDate: _getNextSaturday(),
      invoiceRef: 'SAT-INV-2026-W36-04',
    ),
  ];

  static DateTime _getNextSaturday() {
    final now = DateTime.now();
    int daysUntilSaturday = (DateTime.saturday - now.weekday) % 7;
    if (daysUntilSaturday == 0) daysUntilSaturday = 7;
    return DateTime(now.year, now.month, now.day + daysUntilSaturday, 10, 0);
  }

  static DateTime _getPrevSaturday() {
    final now = DateTime.now();
    int daysSinceSaturday = (now.weekday - DateTime.saturday) % 7;
    if (daysSinceSaturday <= 0) daysSinceSaturday += 7;
    return DateTime(now.year, now.month, now.day - daysSinceSaturday, 10, 0);
  }
}
