import 'design_models.dart';

/// Centralized production mock data for Designs & DAM (Module 6).
class DesignMockData {
  // ---------------------------------------------------------------------------
  // 1. Deliverables Catalog Across Projects
  // ---------------------------------------------------------------------------
  static final List<DesignDeliverable> deliverables = [
    // --- DLF The Camellias (PRJ-104) ---
    DesignDeliverable(
      id: 'DES-104-01',
      projectCode: 'PRJ-104',
      projectName: 'DLF The Camellias - 4BHK Duplex Penthouse',
      title: 'Double Height Living Room Luxury Ceiling & Cove CAD',
      roomArea: 'Living Room Pavilion',
      category: DesignCategory.twoDCad,
      fileType: DesignFileType.dwg,
      currentVersion: 'v3.0',
      status: DesignReviewStatus.approved,
      designerName: 'Ananya Roy',
      designerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&q=80',
      clientName: 'Vikram Malhotra',
      createdAt: DateTime.now().subtract(const Duration(days: 30)),
      clientReviewSlaDeadline: DateTime.now().subtract(const Duration(days: 28)),
      revisionCount: 3,
      fileSizeBytes: 14200000, // 14.2 MB
      thumbnailUrl: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=600&q=80',
      fileUrl: 'https://storage.homio.internal/designs/PRJ-104/CAD/Living_Ceiling_v3.dwg',
      executionWebhookTriggeredAt: '26/08/2026 14:30 IST (WBS Milestone MS-104-03 unlocked)',
      tags: ['DWG', 'False Ceiling', 'Gyproc', 'Philips Cove'],
      versionHistory: [
        DesignVersionRecord(
          versionTag: 'v1.0',
          fileName: 'Living_Ceiling_v1.dwg',
          fileUrl: 'https://storage.homio.internal/designs/PRJ-104/CAD/Living_Ceiling_v1.dwg',
          fileSizeBytes: 12400000,
          uploadedAt: DateTime.now().subtract(const Duration(days: 35)),
          uploadedByName: 'Ananya Roy',
          changelogNote: 'Initial layout with circular ceiling drop',
          reviewStatus: DesignReviewStatus.changesRequested,
          clientFeedback: 'Client requested rectilinear perimeter coves instead of circular drops',
          turnaroundHours: 36,
        ),
        DesignVersionRecord(
          versionTag: 'v2.0',
          fileName: 'Living_Ceiling_v2.dwg',
          fileUrl: 'https://storage.homio.internal/designs/PRJ-104/CAD/Living_Ceiling_v2.dwg',
          fileSizeBytes: 13800000,
          uploadedAt: DateTime.now().subtract(const Duration(days: 32)),
          uploadedByName: 'Ananya Roy',
          changelogNote: 'Perimeter linear coves with AC magnetic diffuser slot',
          reviewStatus: DesignReviewStatus.changesRequested,
          clientFeedback: 'Adjust HVAC grille drop depth to 150mm for Daikin VRV airflow clearance',
          turnaroundHours: 24,
        ),
        DesignVersionRecord(
          versionTag: 'v3.0',
          fileName: 'Living_Ceiling_v3.dwg',
          fileUrl: 'https://storage.homio.internal/designs/PRJ-104/CAD/Living_Ceiling_v3.dwg',
          fileSizeBytes: 14200000,
          uploadedAt: DateTime.now().subtract(const Duration(days: 30)),
          uploadedByName: 'Ananya Roy',
          changelogNote: 'Approved final drawing with engineer load anchor sign-off',
          reviewStatus: DesignReviewStatus.approved,
          clientFeedback: 'Approved by Vikram Malhotra. Ready for site execution.',
          turnaroundHours: 18,
        ),
      ],
    ),

    DesignDeliverable(
      id: 'DES-104-02',
      projectCode: 'PRJ-104',
      projectName: 'DLF The Camellias - 4BHK Duplex Penthouse',
      title: 'Master Bedroom Walk-in Wardrobe & Vanity 3D Render',
      roomArea: 'Master Suite',
      category: DesignCategory.threeDRender,
      fileType: DesignFileType.jpg,
      currentVersion: 'v2.1',
      status: DesignReviewStatus.submitted,
      designerName: 'Ananya Roy',
      designerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&q=80',
      clientName: 'Vikram Malhotra',
      createdAt: DateTime.now().subtract(const Duration(hours: 18)),
      clientReviewSlaDeadline: DateTime.now().add(const Duration(hours: 30)),
      revisionCount: 2,
      fileSizeBytes: 28500000, // 28.5 MB
      thumbnailUrl: 'https://images.unsplash.com/photo-1595428774223-ef52624120d2?w=600&q=80',
      fileUrl: 'https://storage.homio.internal/designs/PRJ-104/Renders/Master_Wardrobe_4K_v2.1.jpg',
      tags: ['4K Render', 'Corona', 'Merino Grey', 'Hafele Glass'],
      versionHistory: [
        DesignVersionRecord(
          versionTag: 'v1.0',
          fileName: 'Master_Wardrobe_v1.0.jpg',
          fileUrl: 'https://storage.homio.internal/designs/PRJ-104/Renders/Master_Wardrobe_v1.0.jpg',
          fileSizeBytes: 24000000,
          uploadedAt: DateTime.now().subtract(const Duration(days: 4)),
          uploadedByName: 'Ananya Roy',
          changelogNote: 'Initial 4K Corona render with tinted bronze glass doors',
          reviewStatus: DesignReviewStatus.changesRequested,
          clientFeedback: 'Client asked for fluted glass on outer doors and sensor lighting inside drawers',
          turnaroundHours: 48,
        ),
        DesignVersionRecord(
          versionTag: 'v2.1',
          fileName: 'Master_Wardrobe_4K_v2.1.jpg',
          fileUrl: 'https://storage.homio.internal/designs/PRJ-104/Renders/Master_Wardrobe_4K_v2.1.jpg',
          fileSizeBytes: 28500000,
          uploadedAt: DateTime.now().subtract(const Duration(hours: 18)),
          uploadedByName: 'Ananya Roy',
          changelogNote: 'Updated with fluted acoustic glass and warm 3000K sensor profiles',
          reviewStatus: DesignReviewStatus.submitted,
          turnaroundHours: 24,
        ),
      ],
    ),

    DesignDeliverable(
      id: 'DES-104-03',
      projectCode: 'PRJ-104',
      projectName: 'DLF The Camellias - 4BHK Duplex Penthouse',
      title: 'VRV HVAC Core Cutting & Electrical Schematic Layout',
      roomArea: 'Entire Penthouse',
      category: DesignCategory.mepEngineering,
      fileType: DesignFileType.pdf,
      currentVersion: 'v1.2',
      status: DesignReviewStatus.approved,
      designerName: 'Praveen Kumar',
      designerAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&q=80',
      clientName: 'Vikram Malhotra',
      createdAt: DateTime.now().subtract(const Duration(days: 22)),
      clientReviewSlaDeadline: DateTime.now().subtract(const Duration(days: 20)),
      revisionCount: 2,
      fileSizeBytes: 8400000,
      thumbnailUrl: 'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=600&q=80',
      fileUrl: 'https://storage.homio.internal/designs/PRJ-104/MEP/VRV_Electrical_v1.2.pdf',
      executionWebhookTriggeredAt: '18/08/2026 11:00 IST (WBS Milestone MS-104-02 unlocked)',
      tags: ['MEP', 'Daikin VRV', 'Schneider DB', 'FRLS'],
      versionHistory: [
        DesignVersionRecord(
          versionTag: 'v1.0',
          fileName: 'VRV_Electrical_v1.0.pdf',
          fileUrl: 'https://storage.homio.internal/designs/PRJ-104/MEP/VRV_Electrical_v1.0.pdf',
          fileSizeBytes: 7900000,
          uploadedAt: DateTime.now().subtract(const Duration(days: 26)),
          uploadedByName: 'Praveen Kumar',
          changelogNote: 'Draft MEP routing for 5 outdoor units and 9 indoor cassettes',
          reviewStatus: DesignReviewStatus.changesRequested,
          clientFeedback: 'Added 12 automation scene switches for living room and dining',
          turnaroundHours: 30,
        ),
        DesignVersionRecord(
          versionTag: 'v1.2',
          fileName: 'VRV_Electrical_v1.2.pdf',
          fileUrl: 'https://storage.homio.internal/designs/PRJ-104/MEP/VRV_Electrical_v1.2.pdf',
          fileSizeBytes: 8400000,
          uploadedAt: DateTime.now().subtract(const Duration(days: 22)),
          uploadedByName: 'Praveen Kumar',
          changelogNote: 'Incorporated smart automation bus wiring with phase balancing',
          reviewStatus: DesignReviewStatus.approved,
          clientFeedback: 'Approved by Vikram Malhotra.',
          turnaroundHours: 20,
        ),
      ],
    ),

    // --- Godrej Woods Tower B (PRJ-105) ---
    DesignDeliverable(
      id: 'DES-105-01',
      projectCode: 'PRJ-105',
      projectName: 'Godrej Woods Tower B - 3BHK Luxury Interior',
      title: 'Modular Gourmet Kitchen Cabinetry & Island 3D Walkthrough',
      roomArea: 'Open Gourmet Kitchen',
      category: DesignCategory.threeDRender,
      fileType: DesignFileType.skp,
      currentVersion: 'v2.0',
      status: DesignReviewStatus.changesRequested,
      designerName: 'Ananya Roy',
      designerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&q=80',
      clientName: 'Radhika Singhania',
      createdAt: DateTime.now().subtract(const Duration(days: 2)),
      clientReviewSlaDeadline: DateTime.now().add(const Duration(days: 1)),
      revisionCount: 2,
      fileSizeBytes: 54000000, // 54 MB
      thumbnailUrl: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=600&q=80',
      fileUrl: 'https://storage.homio.internal/designs/PRJ-105/3D/Kitchen_Island_v2.0.skp',
      tags: ['SketchUp', 'Modular Kitchen', 'Dekton Laurent', 'Blum'],
      versionHistory: [
        DesignVersionRecord(
          versionTag: 'v1.0',
          fileName: 'Kitchen_Island_v1.0.skp',
          fileUrl: 'https://storage.homio.internal/designs/PRJ-105/3D/Kitchen_Island_v1.0.skp',
          fileSizeBytes: 48000000,
          uploadedAt: DateTime.now().subtract(const Duration(days: 7)),
          uploadedByName: 'Ananya Roy',
          changelogNote: 'L-shaped kitchen layout with tall pantry unit',
          reviewStatus: DesignReviewStatus.changesRequested,
          clientFeedback: 'Radhika requested an island breakfast counter with waterfall marble edge',
          turnaroundHours: 36,
        ),
        DesignVersionRecord(
          versionTag: 'v2.0',
          fileName: 'Kitchen_Island_v2.0.skp',
          fileUrl: 'https://storage.homio.internal/designs/PRJ-105/3D/Kitchen_Island_v2.0.skp',
          fileSizeBytes: 54000000,
          uploadedAt: DateTime.now().subtract(const Duration(days: 2)),
          uploadedByName: 'Ananya Roy',
          changelogNote: 'Added central island counter and built-in microwave niche',
          reviewStatus: DesignReviewStatus.changesRequested,
          clientFeedback: 'Please adjust pantry shutter color from Walnut to Champagne Gold Metallic laminate',
          turnaroundHours: 24,
        ),
      ],
    ),

    DesignDeliverable(
      id: 'DES-105-02',
      projectCode: 'PRJ-105',
      projectName: 'Godrej Woods Tower B - 3BHK Luxury Interior',
      title: 'Civil Masonry Demolition & Partition Wall CAD Blueprint',
      roomArea: 'Living & Dining Foyer',
      category: DesignCategory.twoDCad,
      fileType: DesignFileType.pdf,
      currentVersion: 'v1.0',
      status: DesignReviewStatus.approved,
      designerName: 'Ananya Roy',
      designerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&q=80',
      clientName: 'Radhika Singhania',
      createdAt: DateTime.now().subtract(const Duration(days: 18)),
      clientReviewSlaDeadline: DateTime.now().subtract(const Duration(days: 16)),
      revisionCount: 1,
      fileSizeBytes: 6200000,
      thumbnailUrl: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=600&q=80',
      fileUrl: 'https://storage.homio.internal/designs/PRJ-105/CAD/Demolition_Layout_v1.pdf',
      executionWebhookTriggeredAt: '02/09/2026 11:20 IST (WBS Milestone MS-105-01 unlocked)',
      tags: ['Civil CAD', 'Demolition', 'Structural NOC'],
      versionHistory: [
        DesignVersionRecord(
          versionTag: 'v1.0',
          fileName: 'Demolition_Layout_v1.pdf',
          fileUrl: 'https://storage.homio.internal/designs/PRJ-105/CAD/Demolition_Layout_v1.pdf',
          fileSizeBytes: 6200000,
          uploadedAt: DateTime.now().subtract(const Duration(days: 18)),
          uploadedByName: 'Ananya Roy',
          changelogNote: 'Structural column preservation signoff and partition demolition plan',
          reviewStatus: DesignReviewStatus.approved,
          clientFeedback: 'Approved by Radhika Singhania via WhatsApp OTP (552109)',
          turnaroundHours: 12,
        ),
      ],
    ),

    // --- Prestige Golfshire Villa (PRJ-106) ---
    DesignDeliverable(
      id: 'DES-106-01',
      projectCode: 'PRJ-106',
      projectName: 'Prestige Golfshire Luxury Villa #42',
      title: 'Dyna Statuario Italian Marble Bookmatch Dry-Lay Pattern',
      roomArea: 'Double Height Grand Foyer',
      category: DesignCategory.twoDCad,
      fileType: DesignFileType.dwg,
      currentVersion: 'v2.0',
      status: DesignReviewStatus.approved,
      designerName: 'Arjun Swaminathan',
      designerAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&q=80',
      clientName: 'Col. K.S. Rathore',
      createdAt: DateTime.now().subtract(const Duration(days: 45)),
      clientReviewSlaDeadline: DateTime.now().subtract(const Duration(days: 43)),
      revisionCount: 2,
      fileSizeBytes: 18900000,
      thumbnailUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600&q=80',
      fileUrl: 'https://storage.homio.internal/designs/PRJ-106/CAD/Statuario_Bookmatch_v2.dwg',
      executionWebhookTriggeredAt: '28/07/2026 17:00 IST (WBS Milestone MS-106-02 unlocked)',
      tags: ['Statuario', 'Bookmatch CAD', 'Klindex Polish'],
      versionHistory: [
        DesignVersionRecord(
          versionTag: 'v1.0',
          fileName: 'Statuario_Bookmatch_v1.dwg',
          fileUrl: 'https://storage.homio.internal/designs/PRJ-106/CAD/Statuario_Bookmatch_v1.dwg',
          fileSizeBytes: 17200000,
          uploadedAt: DateTime.now().subtract(const Duration(days: 48)),
          uploadedByName: 'Arjun Swaminathan',
          changelogNote: 'Slab layout matching Italian quarry batch 89A',
          reviewStatus: DesignReviewStatus.changesRequested,
          clientFeedback: 'Col. Rathore requested mirror veining radiating outward from center focal point',
          turnaroundHours: 24,
        ),
        DesignVersionRecord(
          versionTag: 'v2.0',
          fileName: 'Statuario_Bookmatch_v2.dwg',
          fileUrl: 'https://storage.homio.internal/designs/PRJ-106/CAD/Statuario_Bookmatch_v2.dwg',
          fileSizeBytes: 18900000,
          uploadedAt: DateTime.now().subtract(const Duration(days: 45)),
          uploadedByName: 'Arjun Swaminathan',
          changelogNote: 'Quarry calibrated layout approved with 95+ GU polish spec',
          reviewStatus: DesignReviewStatus.approved,
          clientFeedback: 'Approved by Col. K.S. Rathore via OTP (712390)',
          turnaroundHours: 16,
        ),
      ],
    ),

    DesignDeliverable(
      id: 'DES-106-02',
      projectCode: 'PRJ-106',
      projectName: 'Prestige Golfshire Luxury Villa #42',
      title: 'Solid Burma Teak Entrance Portal & Yale Biometric Detail',
      roomArea: 'Main Entrance Portal',
      category: DesignCategory.detailJoinery,
      fileType: DesignFileType.max,
      currentVersion: 'v1.0',
      status: DesignReviewStatus.approved,
      designerName: 'Arjun Swaminathan',
      designerAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&q=80',
      clientName: 'Col. K.S. Rathore',
      createdAt: DateTime.now().subtract(const Duration(days: 25)),
      clientReviewSlaDeadline: DateTime.now().subtract(const Duration(days: 23)),
      revisionCount: 1,
      fileSizeBytes: 72000000, // 72 MB
      thumbnailUrl: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=600&q=80',
      fileUrl: 'https://storage.homio.internal/designs/PRJ-106/Joinery/Burma_Teak_Door_v1.max',
      executionWebhookTriggeredAt: '16/08/2026 12:45 IST (WBS Milestone MS-106-03 unlocked)',
      tags: ['Burma Teak', 'Joinery 3ds Max', 'Yale Smart Lock'],
      versionHistory: [
        DesignVersionRecord(
          versionTag: 'v1.0',
          fileName: 'Burma_Teak_Door_v1.max',
          fileUrl: 'https://storage.homio.internal/designs/PRJ-106/Joinery/Burma_Teak_Door_v1.max',
          fileSizeBytes: 72000000,
          uploadedAt: DateTime.now().subtract(const Duration(days: 25)),
          uploadedByName: 'Arjun Swaminathan',
          changelogNote: 'Solid 85mm teak door frame with SS concealed pivot hinge',
          reviewStatus: DesignReviewStatus.approved,
          clientFeedback: 'Approved by Col. K.S. Rathore',
          turnaroundHours: 12,
        ),
      ],
    ),

    // --- Oberoi Sky City (PRJ-107) ---
    DesignDeliverable(
      id: 'DES-107-01',
      projectCode: 'PRJ-107',
      projectName: 'Oberoi Sky City Tower E - 4BHK Duplex',
      title: 'Rigitone Acoustical Ceiling & Sound Dampening Layout',
      roomArea: 'Home Theatre Lounge',
      category: DesignCategory.twoDCad,
      fileType: DesignFileType.dwg,
      currentVersion: 'v1.1',
      status: DesignReviewStatus.submitted,
      designerName: 'Rohit Deshmukh',
      designerAvatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=100&q=80',
      clientName: 'Siddharth Shroff',
      createdAt: DateTime.now().subtract(const Duration(hours: 12)),
      clientReviewSlaDeadline: DateTime.now().add(const Duration(hours: 36)),
      revisionCount: 1,
      fileSizeBytes: 16400000,
      thumbnailUrl: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=600&q=80',
      fileUrl: 'https://storage.homio.internal/designs/PRJ-107/CAD/Acoustic_Ceiling_v1.1.dwg',
      tags: ['Acoustics', 'Saint-Gobain', 'Home Theatre', 'Rigitone'],
      versionHistory: [
        DesignVersionRecord(
          versionTag: 'v1.1',
          fileName: 'Acoustic_Ceiling_v1.1.dwg',
          fileUrl: 'https://storage.homio.internal/designs/PRJ-107/CAD/Acoustic_Ceiling_v1.1.dwg',
          fileSizeBytes: 16400000,
          uploadedAt: DateTime.now().subtract(const Duration(hours: 12)),
          uploadedByName: 'Rohit Deshmukh',
          changelogNote: 'Incorporated square 8/18 perforation and Rockwool density spec',
          reviewStatus: DesignReviewStatus.submitted,
          turnaroundHours: 12,
        ),
      ],
    ),
  ];

  // ---------------------------------------------------------------------------
  // 2. Auto-Generated Cloud Drive Folder Structure per Project (PRD Section 15.2)
  // ---------------------------------------------------------------------------
  static final List<CloudDriveFolder> cloudFolders = [
    // PRJ-104
    CloudDriveFolder(
      id: 'FLD-104-01',
      projectCode: 'PRJ-104',
      name: '01_Laser_Surveys_AsBuilt',
      folderType: CloudFolderType.surveys,
      itemCount: 8,
      totalSizeBytes: 86000000,
      lastModified: DateTime.now().subtract(const Duration(days: 35)),
    ),
    CloudDriveFolder(
      id: 'FLD-104-02',
      projectCode: 'PRJ-104',
      name: '02_2D_CAD_Working_Drawings',
      folderType: CloudFolderType.cadDrawings,
      itemCount: 16,
      totalSizeBytes: 245000000,
      lastModified: DateTime.now().subtract(const Duration(days: 2)),
    ),
    CloudDriveFolder(
      id: 'FLD-104-03',
      projectCode: 'PRJ-104',
      name: '03_3D_Photorealistic_Renders',
      folderType: CloudFolderType.renders3D,
      itemCount: 24,
      totalSizeBytes: 1850000000, // 1.85 GB
      lastModified: DateTime.now().subtract(const Duration(hours: 18)),
    ),
    CloudDriveFolder(
      id: 'FLD-104-04',
      projectCode: 'PRJ-104',
      name: '04_Material_Specifications_BOQ',
      folderType: CloudFolderType.boqSpecs,
      itemCount: 12,
      totalSizeBytes: 34000000,
      lastModified: DateTime.now().subtract(const Duration(days: 5)),
    ),
    CloudDriveFolder(
      id: 'FLD-104-05',
      projectCode: 'PRJ-104',
      name: '05_Site_Progress_Surveillance_4K',
      folderType: CloudFolderType.siteMedia,
      itemCount: 42,
      totalSizeBytes: 6200000000, // 6.2 GB
      lastModified: DateTime.now().subtract(const Duration(hours: 3)),
    ),
    CloudDriveFolder(
      id: 'FLD-104-06',
      projectCode: 'PRJ-104',
      name: '06_Client_Signoffs_Contracts',
      folderType: CloudFolderType.contractsSignoffs,
      itemCount: 6,
      totalSizeBytes: 14000000,
      lastModified: DateTime.now().subtract(const Duration(days: 14)),
    ),

    // PRJ-105
    CloudDriveFolder(
      id: 'FLD-105-02',
      projectCode: 'PRJ-105',
      name: '02_2D_CAD_Working_Drawings',
      folderType: CloudFolderType.cadDrawings,
      itemCount: 10,
      totalSizeBytes: 145000000,
      lastModified: DateTime.now().subtract(const Duration(days: 4)),
    ),
    CloudDriveFolder(
      id: 'FLD-105-03',
      projectCode: 'PRJ-105',
      name: '03_3D_Photorealistic_Renders',
      folderType: CloudFolderType.renders3D,
      itemCount: 14,
      totalSizeBytes: 980000000,
      lastModified: DateTime.now().subtract(const Duration(days: 2)),
    ),

    // PRJ-106
    CloudDriveFolder(
      id: 'FLD-106-02',
      projectCode: 'PRJ-106',
      name: '02_2D_CAD_Working_Drawings',
      folderType: CloudFolderType.cadDrawings,
      itemCount: 18,
      totalSizeBytes: 310000000,
      lastModified: DateTime.now().subtract(const Duration(days: 8)),
    ),
    CloudDriveFolder(
      id: 'FLD-106-03',
      projectCode: 'PRJ-106',
      name: '03_3D_Photorealistic_Renders',
      folderType: CloudFolderType.renders3D,
      itemCount: 30,
      totalSizeBytes: 2400000000,
      lastModified: DateTime.now().subtract(const Duration(days: 5)),
    ),

    // PRJ-107
    CloudDriveFolder(
      id: 'FLD-107-02',
      projectCode: 'PRJ-107',
      name: '02_2D_CAD_Working_Drawings',
      folderType: CloudFolderType.cadDrawings,
      itemCount: 8,
      totalSizeBytes: 120000000,
      lastModified: DateTime.now().subtract(const Duration(hours: 12)),
    ),
  ];

  // ---------------------------------------------------------------------------
  // 3. Individual Cloud Files Inside Drive
  // ---------------------------------------------------------------------------
  static final List<CloudDriveFile> cloudFiles = [
    CloudDriveFile(
      id: 'FIL-01',
      projectCode: 'PRJ-104',
      folderId: 'FLD-104-02',
      fileName: 'DLF_Camellias_FalseCeiling_Master_v3.dwg',
      fileType: DesignFileType.dwg,
      fileSizeBytes: 14200000,
      uploadedAt: DateTime.now().subtract(const Duration(days: 30)),
      uploadedBy: 'Ananya Roy (Lead Architect)',
      downloadUrl: 'https://storage.homio.internal/designs/PRJ-104/CAD/Living_Ceiling_v3.dwg',
      thumbnailUrl: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=400&q=80',
      versionTag: 'v3.0',
      tags: ['DWG', 'Gyproc', 'Approved'],
    ),
    CloudDriveFile(
      id: 'FIL-02',
      projectCode: 'PRJ-104',
      folderId: 'FLD-104-03',
      fileName: 'Master_Bedroom_Wardrobe_4K_Render_v2.1.jpg',
      fileType: DesignFileType.jpg,
      fileSizeBytes: 28500000,
      uploadedAt: DateTime.now().subtract(const Duration(hours: 18)),
      uploadedBy: 'Ananya Roy',
      downloadUrl: 'https://storage.homio.internal/designs/PRJ-104/Renders/Master_Wardrobe_4K_v2.1.jpg',
      thumbnailUrl: 'https://images.unsplash.com/photo-1595428774223-ef52624120d2?w=400&q=80',
      versionTag: 'v2.1',
      tags: ['4K Render', 'Under Review'],
    ),
    CloudDriveFile(
      id: 'FIL-03',
      projectCode: 'PRJ-104',
      folderId: 'FLD-104-02',
      fileName: 'Daikin_VRV_Concealed_MEP_Schematic_v1.2.pdf',
      fileType: DesignFileType.pdf,
      fileSizeBytes: 8400000,
      uploadedAt: DateTime.now().subtract(const Duration(days: 22)),
      uploadedBy: 'Praveen Kumar',
      downloadUrl: 'https://storage.homio.internal/designs/PRJ-104/MEP/VRV_Electrical_v1.2.pdf',
      thumbnailUrl: 'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=400&q=80',
      versionTag: 'v1.2',
      tags: ['MEP', 'PDF', 'Approved'],
    ),
    CloudDriveFile(
      id: 'FIL-04',
      projectCode: 'PRJ-104',
      folderId: 'FLD-104-04',
      fileName: 'Comprehensive_Finish_Specification_BOQ_v2.pdf',
      fileType: DesignFileType.pdf,
      fileSizeBytes: 12100000,
      uploadedAt: DateTime.now().subtract(const Duration(days: 15)),
      uploadedBy: 'Rohit Deshmukh (PM)',
      downloadUrl: 'https://storage.homio.internal/designs/PRJ-104/BOQ/BOQ_v2.pdf',
      thumbnailUrl: 'https://images.unsplash.com/photo-1541888946425-d0fbb186f5f7?w=400&q=80',
      versionTag: 'v2.0',
      tags: ['BOQ', 'Specifications'],
    ),
    CloudDriveFile(
      id: 'FIL-05',
      projectCode: 'PRJ-105',
      folderId: 'FLD-105-03',
      fileName: 'Kitchen_Island_Gourmet_Walkthrough_v2.skp',
      fileType: DesignFileType.skp,
      fileSizeBytes: 54000000,
      uploadedAt: DateTime.now().subtract(const Duration(days: 2)),
      uploadedBy: 'Ananya Roy',
      downloadUrl: 'https://storage.homio.internal/designs/PRJ-105/3D/Kitchen_Island_v2.0.skp',
      thumbnailUrl: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=400&q=80',
      versionTag: 'v2.0',
      tags: ['SketchUp', 'Revisions Pending'],
    ),
    CloudDriveFile(
      id: 'FIL-06',
      projectCode: 'PRJ-106',
      folderId: 'FLD-106-02',
      fileName: 'Dyna_Statuario_Marble_Bookmatch_Pattern_v2.dwg',
      fileType: DesignFileType.dwg,
      fileSizeBytes: 18900000,
      uploadedAt: DateTime.now().subtract(const Duration(days: 45)),
      uploadedBy: 'Arjun Swaminathan',
      downloadUrl: 'https://storage.homio.internal/designs/PRJ-106/CAD/Statuario_Bookmatch_v2.dwg',
      thumbnailUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=400&q=80',
      versionTag: 'v2.0',
      tags: ['DWG', 'Marble', 'Approved'],
    ),
  ];

  // ---------------------------------------------------------------------------
  // 4. Security Audit Trail for Restricted Deletions
  // ---------------------------------------------------------------------------
  static final List<DeletionAuditLog> deletionAuditLogs = [
    DeletionAuditLog(
      id: 'DEL-LOG-01',
      itemName: 'DLF_Camellias_FalseCeiling_Master_v2.dwg',
      attemptedBy: 'Pankaj (Junior Drafter)',
      superAdminApprover: 'Blocked (Regular Staff Restriction)',
      twoFactorOtpCode: 'N/A - Direct Rejection',
      reason: 'Attempted to delete superseded v2.0 drawing. Policy rule enforces historical retention.',
      timestamp: DateTime.now().subtract(const Duration(days: 3)),
      isAuthorized: false,
    ),
    DeletionAuditLog(
      id: 'DEL-LOG-02',
      itemName: 'Test_Export_Duplicated_Draft.pdf',
      attemptedBy: 'Ananya Roy (Lead Architect)',
      superAdminApprover: 'Super Admin (Rohit Deshmukh)',
      twoFactorOtpCode: '918402 (Verified 2FA SMS & Authenticator)',
      reason: 'Accidental duplicate export without layer dimensions. Super Admin authorized purge.',
      timestamp: DateTime.now().subtract(const Duration(days: 7)),
      isAuthorized: true,
    ),
  ];
}
