import 'quotation_models.dart';

/// Centralized production-grade mock data repository for the Quotation Module.
class QuotationMockData {
  // ---------------------------------------------------------------------------
  // 1. Centralized Item & Rate Master Catalogue (PRD Section 9.1 & 17.2)
  // ---------------------------------------------------------------------------
  static final List<ItemMasterEntry> masterItems = [
    // Civil & Masonry
    const ItemMasterEntry(
      id: 'ITM-CIV-001',
      name: 'Vitrified Floor Tile Demolition & Laying',
      category: ItemCategory.civil,
      technicalSpecs: 'Kajaria/Somany 800x800mm Double Charged Vitrified Tiles with epoxy grouting',
      imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=400&q=80',
      uom: UnitOfMeasurement.sqft,
      baseCostRate: 115.0,
      marginPercent: 22.0,
      gstPercent: 18.0,
      approvedBrands: ['Kajaria', 'Somany', 'Simpolo'],
    ),
    const ItemMasterEntry(
      id: 'ITM-CIV-002',
      name: 'Internal Brick Partition Wall (4.5 inch)',
      category: ItemCategory.civil,
      technicalSpecs: 'Red clay kiln bricks with 1:4 cement mortar, double coat sand plaster',
      imageUrl: 'https://images.unsplash.com/photo-1541888946425-d0fbb186f5f7?w=400&q=80',
      uom: UnitOfMeasurement.sqft,
      baseCostRate: 95.0,
      marginPercent: 20.0,
      gstPercent: 18.0,
      approvedBrands: ['Ultratech Cement', 'Ambuja', 'Tata TMT'],
    ),

    // Carpentry & Woodwork
    const ItemMasterEntry(
      id: 'ITM-CRP-001',
      name: 'Full Height Sliding Wardrobe with Loft',
      category: ItemCategory.carpentry,
      technicalSpecs: 'Century BWP Plywood 18mm, 1.0mm Merino laminate inside & outside, Hafele soft-close sliders',
      imageUrl: 'https://images.unsplash.com/photo-1595428774223-ef52624120d2?w=400&q=80',
      uom: UnitOfMeasurement.sqft,
      baseCostRate: 1450.0,
      marginPercent: 28.0,
      gstPercent: 18.0,
      approvedBrands: ['CenturyPly', 'Greenlam', 'Merino', 'Hafele'],
    ),
    const ItemMasterEntry(
      id: 'ITM-CRP-002',
      name: 'TV Entertainment Console & Fluted Panel Backdrop',
      category: ItemCategory.carpentry,
      technicalSpecs: 'Charcoal louvers / WPC fluted panels, floating console with PU paint finish',
      imageUrl: 'https://images.unsplash.com/photo-1594026112284-02bb6f3352fe?w=400&q=80',
      uom: UnitOfMeasurement.runningFt,
      baseCostRate: 2100.0,
      marginPercent: 30.0,
      gstPercent: 18.0,
      approvedBrands: ['Century Pro', 'Alstone Louvers', 'Asian Paints PU'],
    ),
    const ItemMasterEntry(
      id: 'ITM-CRP-003',
      name: 'Designer King Size Bed with Hydraulic Storage',
      category: ItemCategory.carpentry,
      technicalSpecs: 'Commercial Marine Ply 19mm, German gas-lift struts (150kg capacity), cushioned headboard',
      imageUrl: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=400&q=80',
      uom: UnitOfMeasurement.nos,
      baseCostRate: 38000.0,
      marginPercent: 25.0,
      gstPercent: 18.0,
      approvedBrands: ['CenturyPly', 'Ebco Hydraulics', 'DDecor Fabrics'],
    ),

    // Modular Kitchen
    const ItemMasterEntry(
      id: 'ITM-KTN-001',
      name: 'Modular Base & Overhead Cabinets (Acrylic Finish)',
      category: ItemCategory.modularKitchen,
      technicalSpecs: 'BWP 710 Calibrated Plywood, 2mm Rehau edge banding, High Gloss German Acrylic shutters',
      imageUrl: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=400&q=80',
      uom: UnitOfMeasurement.sqft,
      baseCostRate: 2350.0,
      marginPercent: 32.0,
      gstPercent: 18.0,
      approvedBrands: ['Greenply BWP', 'Rehau', 'Blum', 'Hafele'],
    ),
    const ItemMasterEntry(
      id: 'ITM-KTN-002',
      name: 'Blum Antaro Soft-Close Tandem Drawer Set',
      category: ItemCategory.modularKitchen,
      technicalSpecs: 'Set of 3 stainless steel tandem drawers: Cutlery, Plain, and Thali baskets with 50kg load capacity',
      imageUrl: 'https://images.unsplash.com/photo-1600585152220-90363fe7e115?w=400&q=80',
      uom: UnitOfMeasurement.nos,
      baseCostRate: 18500.0,
      marginPercent: 25.0,
      gstPercent: 18.0,
      approvedBrands: ['Blum Austria', 'Hettich Germany'],
    ),
    const ItemMasterEntry(
      id: 'ITM-KTN-003',
      name: 'Quartz Kitchen Countertop (KalingaStone 20mm)',
      category: ItemCategory.modularKitchen,
      technicalSpecs: 'Calacatta engineered quartz with full bullnose profiling and under-mount sink cutout',
      imageUrl: 'https://images.unsplash.com/photo-1507089947368-19c1da9775ae?w=400&q=80',
      uom: UnitOfMeasurement.runningFt,
      baseCostRate: 3200.0,
      marginPercent: 26.0,
      gstPercent: 18.0,
      approvedBrands: ['KalingaStone', 'Silestone'],
    ),

    // False Ceiling
    const ItemMasterEntry(
      id: 'ITM-FCL-001',
      name: 'Gypsum Designer False Ceiling with Perimeter Cove',
      category: ItemCategory.falseCeiling,
      technicalSpecs: 'Saint-Gobain Gypboard 12.5mm, GI metal framing, concealed Philips warm-white LED cove strip',
      imageUrl: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=400&q=80',
      uom: UnitOfMeasurement.sqft,
      baseCostRate: 135.0,
      marginPercent: 25.0,
      gstPercent: 18.0,
      approvedBrands: ['Saint-Gobain Gyproc', 'Philips', 'Havells'],
    ),

    // Painting & Polish
    const ItemMasterEntry(
      id: 'ITM-PNT-001',
      name: 'Asian Paints Royale Luxury Interior Emulsion',
      category: ItemCategory.painting,
      technicalSpecs: '3 coats of Asian Paints Royale Teflon surface protector over 2 coats Birla White putty and primer',
      imageUrl: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?w=400&q=80',
      uom: UnitOfMeasurement.sqft,
      baseCostRate: 38.0,
      marginPercent: 30.0,
      gstPercent: 18.0,
      approvedBrands: ['Asian Paints Royale', 'Birla White', 'Dulux Velvet'],
    ),
    const ItemMasterEntry(
      id: 'ITM-PNT-002',
      name: 'Italian PU Polish on Veneer Paneling',
      category: ItemCategory.painting,
      technicalSpecs: 'Sirca Italy / ICA clear PU matte finish, 4-stage automated spray polish',
      imageUrl: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=400&q=80',
      uom: UnitOfMeasurement.sqft,
      baseCostRate: 180.0,
      marginPercent: 35.0,
      gstPercent: 18.0,
      approvedBrands: ['Sirca Italy', 'ICA', 'Asian Paints Woodtech'],
    ),

    // Electrical & Lighting
    const ItemMasterEntry(
      id: 'ITM-ELC-001',
      name: 'Modular Switch Plate Wiring & Dimmable COB Downlights',
      category: ItemCategory.electrical,
      technicalSpecs: 'Schneider Electric AvatarOn switches, Finolex FRLS copper wiring, Bridgelux 7W COB downlights',
      imageUrl: 'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=400&q=80',
      uom: UnitOfMeasurement.nos,
      baseCostRate: 980.0,
      marginPercent: 28.0,
      gstPercent: 18.0,
      approvedBrands: ['Schneider Electric', 'Legrand Arteor', 'Finolex'],
    ),

    // Hardware & Fittings
    const ItemMasterEntry(
      id: 'ITM-HRD-001',
      name: 'Hafele Soft-Close Concealed Hinges & Profile Handles',
      category: ItemCategory.hardware,
      technicalSpecs: 'Hafele Metalla 3D clip-on 110° soft-close hinges, matte black aluminum edge J-pull profiles',
      imageUrl: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=400&q=80',
      uom: UnitOfMeasurement.runningFt,
      baseCostRate: 480.0,
      marginPercent: 25.0,
      gstPercent: 18.0,
      approvedBrands: ['Hafele', 'Blum', 'Hettich Sensys'],
    ),
  ];

  // ---------------------------------------------------------------------------
  // 2. Production Quotations (Residential & Commercial)
  // ---------------------------------------------------------------------------
  static final List<Quotation> quotations = [
    Quotation(
      id: 'QUO-2026-0892',
      quoteNumber: 'QUO-2026-0892',
      revisionNumber: 2,
      leadId: 'LD-9021',
      clientName: 'Vikram & Radhika Singhania',
      clientPhone: '+91 98201 44552',
      clientEmail: 'vikram.singhania@gmail.com',
      projectTitle: 'Godrej Woods Tower B - 3BHK Ultra-Luxe Interior',
      projectLocation: 'Sector 43, Noida, NCR',
      designerName: 'Ananya Roy (Principal Architect)',
      coverImageUrl: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=1200&q=80',
      submissionDate: DateTime.now().subtract(const Duration(days: 2)),
      discountExpiryDate: DateTime.now().add(const Duration(hours: 19, minutes: 45)),
      status: QuotationStatus.submitted,
      hideRate: false,
      hideSqft: false,
      showAmount: true,
      discountPercent: 8.0,
      gstPercent: 18.0,
      termsAndConditions: '1. 10% on Booking Token, 40% on Civil/Carcass delivery, 40% on Finish work, 10% upon final handover.\n'
          '2. 10-Year Comprehensive Warranty on BWP Grade Plywood & termite resistance.\n'
          '3. 5-Year German Hardware Warranty by Hafele India.\n'
          '4. Site readiness verification required prior to wooden carcass installation.',
      rooms: [
        RoomArea(
          id: 'RM-01',
          roomName: 'Living & Dining Hall',
          lengthFt: 22.0,
          widthFt: 14.0,
          heightFt: 10.0,
          tier: MaterialTier.luxury,
          items: [
            QuotationItem(
              id: 'QI-01',
              itemMasterId: 'ITM-CRP-002',
              name: 'TV Entertainment Console & Fluted Panel Backdrop',
              category: ItemCategory.carpentry,
              materialSpecs: 'Charcoal louvers / WPC fluted panels with Italian PU matte floating console',
              uom: UnitOfMeasurement.runningFt,
              quantity: 14.0,
              rate: 2730.0,
              marginPercent: 30.0,
              imageUrl: 'https://images.unsplash.com/photo-1594026112284-02bb6f3352fe?w=400&q=80',
            ),
            QuotationItem(
              id: 'QI-02',
              itemMasterId: 'ITM-FCL-001',
              name: 'Gypsum Designer False Ceiling with Perimeter Cove',
              category: ItemCategory.falseCeiling,
              materialSpecs: 'Saint-Gobain Gyproc 12.5mm with Philips dimmable LED cove lighting',
              uom: UnitOfMeasurement.sqft,
              quantity: 308.0,
              rate: 168.0,
              marginPercent: 25.0,
              imageUrl: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=400&q=80',
            ),
            QuotationItem(
              id: 'QI-03',
              itemMasterId: 'ITM-PNT-001',
              name: 'Asian Paints Royale Luxury Interior Emulsion',
              category: ItemCategory.painting,
              materialSpecs: '3 coats Asian Paints Royale with Teflon coat over Birla White putty base',
              uom: UnitOfMeasurement.sqft,
              quantity: 720.0,
              rate: 49.0,
              marginPercent: 30.0,
              imageUrl: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?w=400&q=80',
            ),
            QuotationItem(
              id: 'QI-04',
              itemMasterId: 'ITM-ELC-001',
              name: 'Modular Switch Plate Wiring & Dimmable COB Downlights',
              category: ItemCategory.electrical,
              materialSpecs: 'Schneider Electric AvatarOn switches, 7W Bridgelux warm white COB spotlights',
              uom: UnitOfMeasurement.nos,
              quantity: 16.0,
              rate: 1250.0,
              marginPercent: 28.0,
              imageUrl: 'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=400&q=80',
            ),
          ],
        ),
        RoomArea(
          id: 'RM-02',
          roomName: 'Master Bedroom Suite',
          lengthFt: 16.0,
          widthFt: 12.0,
          heightFt: 10.0,
          tier: MaterialTier.luxury,
          items: [
            QuotationItem(
              id: 'QI-05',
              itemMasterId: 'ITM-CRP-001',
              name: 'Full Height Sliding Wardrobe with Loft',
              category: ItemCategory.carpentry,
              materialSpecs: 'Century BWP Plywood, Merino 1.0mm anti-fingerprint laminates, Hafele soft-close sliders',
              uom: UnitOfMeasurement.sqft,
              quantity: 80.0,
              rate: 1856.0,
              marginPercent: 28.0,
              imageUrl: 'https://images.unsplash.com/photo-1595428774223-ef52624120d2?w=400&q=80',
            ),
            QuotationItem(
              id: 'QI-06',
              itemMasterId: 'ITM-CRP-003',
              name: 'Designer King Size Bed with Hydraulic Storage',
              category: ItemCategory.carpentry,
              materialSpecs: 'BWP 710 marine ply carcass with German gas lifts (150kg) & quilted headboard',
              uom: UnitOfMeasurement.nos,
              quantity: 1.0,
              rate: 47500.0,
              marginPercent: 25.0,
              imageUrl: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=400&q=80',
            ),
            QuotationItem(
              id: 'QI-07',
              itemMasterId: 'ITM-PNT-002',
              name: 'Italian PU Polish on Bed Backdrop Paneling',
              category: ItemCategory.painting,
              materialSpecs: 'Sirca Italy automated matte spray finish on imported walnut veneer',
              uom: UnitOfMeasurement.sqft,
              quantity: 120.0,
              rate: 243.0,
              marginPercent: 35.0,
              imageUrl: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=400&q=80',
            ),
          ],
        ),
        RoomArea(
          id: 'RM-03',
          roomName: 'Gourmet Modular Kitchen',
          lengthFt: 12.0,
          widthFt: 10.0,
          heightFt: 10.0,
          tier: MaterialTier.luxury,
          items: [
            QuotationItem(
              id: 'QI-08',
              itemMasterId: 'ITM-KTN-001',
              name: 'Modular Base & Overhead Cabinets (Acrylic Finish)',
              category: ItemCategory.modularKitchen,
              materialSpecs: 'BWP 710 Calibrated Plywood, Rehau seamless edge banding, German High-Gloss Acrylic',
              uom: UnitOfMeasurement.sqft,
              quantity: 95.0,
              rate: 3102.0,
              marginPercent: 32.0,
              imageUrl: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=400&q=80',
            ),
            QuotationItem(
              id: 'QI-09',
              itemMasterId: 'ITM-KTN-002',
              name: 'Blum Antaro Soft-Close Tandem Drawer Set',
              category: ItemCategory.modularKitchen,
              materialSpecs: 'Set of 3 stainless steel tandem drawers: Cutlery, Plain, and Thali with 50kg capacity',
              uom: UnitOfMeasurement.nos,
              quantity: 2.0,
              rate: 23125.0,
              marginPercent: 25.0,
              imageUrl: 'https://images.unsplash.com/photo-1600585152220-90363fe7e115?w=400&q=80',
            ),
            QuotationItem(
              id: 'QI-10',
              itemMasterId: 'ITM-KTN-003',
              name: 'Quartz Kitchen Countertop (KalingaStone 20mm)',
              category: ItemCategory.modularKitchen,
              materialSpecs: 'Calacatta engineered quartz with full bullnose profiling and under-mount sink cutout',
              uom: UnitOfMeasurement.runningFt,
              quantity: 22.0,
              rate: 4032.0,
              marginPercent: 26.0,
              imageUrl: 'https://images.unsplash.com/photo-1507089947368-19c1da9775ae?w=400&q=80',
            ),
          ],
        ),
      ],
    ),

    Quotation(
      id: 'QUO-2026-0895',
      quoteNumber: 'QUO-2026-0895',
      revisionNumber: 1,
      leadId: 'LD-9034',
      clientName: 'Dr. Arjun & Meera Nambiar',
      clientPhone: '+91 97112 88901',
      clientEmail: 'dr.arjun.nambiar@apollo.org',
      projectTitle: 'DLF The Camellias - 4BHK Duplex Penthouse',
      projectLocation: 'Golf Course Road, Gurgaon',
      designerName: 'Rohan Mehta (Design Director)',
      coverImageUrl: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200&q=80',
      submissionDate: DateTime.now().subtract(const Duration(days: 4)),
      discountExpiryDate: DateTime.now().subtract(const Duration(hours: 4)), // Expired
      status: QuotationStatus.expired,
      hideRate: true, // Example where rates are hidden
      hideSqft: true, // Example where sqft is hidden
      showAmount: true,
      discountPercent: 10.0,
      gstPercent: 18.0,
      rooms: [
        RoomArea(
          id: 'RM-04',
          roomName: 'Grand Foyer & Living Pavilion',
          lengthFt: 28.0,
          widthFt: 18.0,
          heightFt: 12.0,
          tier: MaterialTier.luxury,
          items: [
            QuotationItem(
              id: 'QI-11',
              itemMasterId: 'ITM-CRP-002',
              name: 'Imported Marble Backdrop & CNC Fluted Veneer Console',
              category: ItemCategory.carpentry,
              materialSpecs: 'Michaelangelo White marble with bookmatch finish and brass inlays',
              uom: UnitOfMeasurement.runningFt,
              quantity: 24.0,
              rate: 4800.0,
              marginPercent: 35.0,
            ),
          ],
        ),
      ],
    ),

    Quotation(
      id: 'QUO-2026-0901',
      quoteNumber: 'QUO-2026-0901',
      revisionNumber: 1,
      leadId: 'LD-9055',
      clientName: 'Pooja Bhatia & Family',
      clientPhone: '+91 98100 23411',
      clientEmail: 'pooja.bhatia@techmahindra.com',
      projectTitle: 'Prestige Lakeside Habitat - 2BHK Smart Home',
      projectLocation: 'Whitefield, Bangalore',
      designerName: 'Sneha Kapoor (Lead Designer)',
      coverImageUrl: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=1200&q=80',
      submissionDate: DateTime.now(),
      discountExpiryDate: DateTime.now().add(const Duration(days: 3)),
      status: QuotationStatus.draft,
      hideRate: false,
      hideSqft: false,
      showAmount: true,
      discountPercent: 5.0,
      gstPercent: 18.0,
      rooms: [
        RoomArea(
          id: 'RM-05',
          roomName: 'Living & Dining Area',
          lengthFt: 18.0,
          widthFt: 12.0,
          heightFt: 9.5,
          tier: MaterialTier.premium,
          items: [
            QuotationItem(
              id: 'QI-12',
              itemMasterId: 'ITM-FCL-001',
              name: 'Gypsum False Ceiling with Minimalist Cove',
              category: ItemCategory.falseCeiling,
              materialSpecs: 'Gyproc boards with Havells smart wifi dimmable warm LED strips',
              uom: UnitOfMeasurement.sqft,
              quantity: 216.0,
              rate: 165.0,
              marginPercent: 22.0,
            ),
          ],
        ),
      ],
    ),
  ];

  // ---------------------------------------------------------------------------
  // 3. Dynamic Pricing & 24h WhatsApp Urgency Logs (PRD Section 9.4 & TC-QUOT-001)
  // ---------------------------------------------------------------------------
  static final List<UrgencyAlertLog> urgencyLogs = [
    UrgencyAlertLog(
      id: 'URG-001',
      quotationId: 'QUO-2026-0892',
      quoteNumber: 'QUO-2026-0892',
      clientName: 'Vikram Singhania',
      clientPhone: '+91 98201 44552',
      quotationAmount: 1184500.0,
      discountAmount: 94760.0,
      expiryDate: DateTime.now().add(const Duration(hours: 19, minutes: 45)),
      scheduledAlertTime: DateTime.now().subtract(const Duration(hours: 4, minutes: 15)),
      isTriggered: true,
      triggeredAt: DateTime.now().subtract(const Duration(hours: 4, minutes: 15)),
      deliveryStatus: 'READ',
      whatsappMessagePreview:
          '🚨 Final 24h Notice: Vikram, your 8% Early Bird booking discount worth ₹94,760 on Godrej Woods 3BHK expires tonight! Click here to lock your pricing before rate hike: https://homio.design/q/0892-lock',
    ),
    UrgencyAlertLog(
      id: 'URG-002',
      quotationId: 'QUO-2026-0895',
      quoteNumber: 'QUO-2026-0895',
      clientName: 'Dr. Arjun Nambiar',
      clientPhone: '+91 97112 88901',
      quotationAmount: 2450000.0,
      discountAmount: 245000.0,
      expiryDate: DateTime.now().subtract(const Duration(hours: 4)),
      scheduledAlertTime: DateTime.now().subtract(const Duration(hours: 28)),
      isTriggered: true,
      triggeredAt: DateTime.now().subtract(const Duration(hours: 28)),
      deliveryStatus: 'EXPIRED',
      whatsappMessagePreview:
          '⏳ Attention Dr. Arjun: The Camellias 10% exclusive VIP pricing waiver of ₹2,45,000 has now expired. Contact Rohan Mehta to request an executive extension.',
    ),
    UrgencyAlertLog(
      id: 'URG-003',
      quotationId: 'QUO-2026-0901',
      quoteNumber: 'QUO-2026-0901',
      clientName: 'Pooja Bhatia',
      clientPhone: '+91 98100 23411',
      quotationAmount: 780000.0,
      discountAmount: 39000.0,
      expiryDate: DateTime.now().add(const Duration(days: 3)),
      scheduledAlertTime: DateTime.now().add(const Duration(days: 2)),
      isTriggered: false,
      deliveryStatus: 'SCHEDULED',
      whatsappMessagePreview:
          '✨ Early Bird Reminder: Pooja, secure your ₹39,000 seasonal voucher on Prestige Lakeside 2BHK before Friday 6 PM.',
    ),
  ];

  // ---------------------------------------------------------------------------
  // 4. B2C Customer Self-Estimator Inquiries (PRD Section 9.5)
  // ---------------------------------------------------------------------------
  static final List<CustomerSelfEstimateLead> selfEstimateLeads = [
    CustomerSelfEstimateLead(
      id: 'SEL-001',
      name: 'Gaurav Agarwal',
      phone: '+91 99102 77812',
      email: 'gaurav.ag@gmail.com',
      propertyType: '3BHK',
      carpetAreaSqft: 1450.0,
      tier: MaterialTier.premium,
      selectedRooms: ['Living Room', 'Master Bedroom', 'Modular Kitchen', 'Guest Bedroom'],
      estimatedMinBudget: 1150000.0,
      estimatedMaxBudget: 1420000.0,
      isOtpVerified: true,
      createdAt: DateTime.now().subtract(const Duration(hours: 3)),
      crmLeadStatus: 'SYNCED_TO_SALES',
    ),
    CustomerSelfEstimateLead(
      id: 'SEL-002',
      name: 'Kavita Chawla',
      phone: '+91 98711 00345',
      email: 'kavita.c@deloitte.com',
      propertyType: '2BHK',
      carpetAreaSqft: 980.0,
      tier: MaterialTier.budget,
      selectedRooms: ['Living Room', 'Modular Kitchen', 'Master Bedroom'],
      estimatedMinBudget: 580000.0,
      estimatedMaxBudget: 740000.0,
      isOtpVerified: true,
      createdAt: DateTime.now().subtract(const Duration(hours: 9)),
      crmLeadStatus: 'SITE_VISIT_BOOKED',
    ),
    CustomerSelfEstimateLead(
      id: 'SEL-003',
      name: 'Rajnish Oberoi',
      phone: '+91 98110 55998',
      email: 'rajnish@oberoigroup.in',
      propertyType: 'Villa',
      carpetAreaSqft: 3800.0,
      tier: MaterialTier.luxury,
      selectedRooms: ['Living Room', 'Dining', 'Italian Kitchen', '4 Bedrooms', 'Home Theatre', 'Terrace Deck'],
      estimatedMinBudget: 4200000.0,
      estimatedMaxBudget: 5500000.0,
      isOtpVerified: true,
      createdAt: DateTime.now().subtract(const Duration(days: 1)),
      crmLeadStatus: 'CONTACTED',
    ),
  ];
}
