import 'package:flutter/material.dart';
import 'quotation_models.dart';

/// Centralized production-grade mock data repository for the Quotation Module.
class QuotationMockData {
  // ---------------------------------------------------------------------------
  // 1. Centralized Item & Rate Master Catalogue (PRD Section 30)
  // ---------------------------------------------------------------------------
  static final List<ItemMasterEntry> masterItems = [
    // Civil & Masonry
    const ItemMasterEntry(
      id: 'ITM-CIV-001',
      sku: 'CIV-TILE-8080-01',
      name: 'Vitrified Floor Tile Demolition & Laying',
      category: ItemCategory.civil,
      subcategory: 'Flooring & Tiling',
      technicalSpecs: 'Kajaria/Somany 800x800mm Double Charged Vitrified Tiles with epoxy grouting',
      description: 'Complete floor demolition, screed leveling, adhesive application, and tile fixing with 3mm spacers.',
      imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=400&q=80',
      uom: UnitOfMeasurement.sqft,
      baseCostRate: 115.0,
      marginPercent: 22.0,
      minRate: 125.0,
      maxRate: 175.0,
      gstPercent: 18.0,
      approvedBrands: ['Kajaria', 'Somany', 'Simpolo'],
      preferredVendor: 'Apex Ceramic Hub',
      tags: ['flooring', 'tiles', 'vitrified', 'civil'],
      isActive: true,
    ),
    const ItemMasterEntry(
      id: 'ITM-CIV-002',
      sku: 'CIV-WALL-45IN-01',
      name: 'Internal Brick Partition Wall (4.5 inch)',
      category: ItemCategory.civil,
      subcategory: 'Masonry Walls',
      technicalSpecs: 'Red clay kiln bricks with 1:4 cement mortar, double coat sand plaster',
      description: 'Partition wall construction including RCC patla bands at lintel level and curing.',
      imageUrl: 'https://images.unsplash.com/photo-1541888946425-d0fbb186f5f7?w=400&q=80',
      uom: UnitOfMeasurement.sqft,
      baseCostRate: 95.0,
      marginPercent: 20.0,
      minRate: 105.0,
      maxRate: 140.0,
      gstPercent: 18.0,
      approvedBrands: ['Ultratech Cement', 'Ambuja', 'Tata TMT'],
      preferredVendor: 'Metro Building Supplies',
      tags: ['civil', 'masonry', 'partition', 'brick'],
      isActive: true,
    ),
    const ItemMasterEntry(
      id: 'ITM-CIV-003',
      sku: 'CIV-WPRF-02',
      name: 'Dr. Fixit 2-Coat Balcony & Wet Area Waterproofing',
      category: ItemCategory.civil,
      subcategory: 'Waterproofing',
      technicalSpecs: 'Elastomeric acrylic coating with fibre-mesh reinforcement and pond testing',
      description: 'Includes surface preparation, polymer injection grouting, and 48-hour flood test.',
      imageUrl: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=400&q=80',
      uom: UnitOfMeasurement.sqft,
      baseCostRate: 55.0,
      marginPercent: 25.0,
      minRate: 65.0,
      maxRate: 85.0,
      gstPercent: 18.0,
      approvedBrands: ['Dr. Fixit', 'Fosroc', 'Sika'],
      preferredVendor: 'Chemical Building Solutions',
      tags: ['waterproofing', 'civil', 'wet-area'],
      isActive: true,
    ),

    // Carpentry & Woodwork
    const ItemMasterEntry(
      id: 'ITM-CRP-001',
      sku: 'CRP-WDR-SLD-01',
      name: 'Full Height Sliding Wardrobe with Loft',
      category: ItemCategory.carpentry,
      subcategory: 'Wardrobes & Storage',
      technicalSpecs: 'Century BWP Plywood 18mm, 1.0mm Merino laminate inside & outside, Hafele soft-close sliders',
      description: 'Floor to ceiling sliding shutter wardrobe with internal drawer stacks, accessory tray, and sensor LED profile.',
      imageUrl: 'https://images.unsplash.com/photo-1595428774223-ef52624120d2?w=400&q=80',
      uom: UnitOfMeasurement.sqft,
      baseCostRate: 1450.0,
      marginPercent: 28.0,
      minRate: 1700.0,
      maxRate: 2200.0,
      gstPercent: 18.0,
      approvedBrands: ['CenturyPly', 'Greenlam', 'Merino', 'Hafele'],
      preferredVendor: 'Karnataka Timber & Hardware',
      tags: ['wardrobe', 'sliding', 'plywood', 'storage'],
      isActive: true,
    ),
    const ItemMasterEntry(
      id: 'ITM-CRP-002',
      sku: 'CRP-ENT-TVU-01',
      name: 'TV Entertainment Console & Fluted Panel Backdrop',
      category: ItemCategory.carpentry,
      subcategory: 'Living Consoles',
      technicalSpecs: 'Charcoal louvers / WPC fluted panels, floating console with PU paint finish',
      description: 'Acoustic WPC louver panelling with concealed wire routing raceway and push-to-open drawer storage.',
      imageUrl: 'https://images.unsplash.com/photo-1594026112284-02bb6f3352fe?w=400&q=80',
      uom: UnitOfMeasurement.runningFt,
      baseCostRate: 2100.0,
      marginPercent: 30.0,
      minRate: 2500.0,
      maxRate: 3200.0,
      gstPercent: 18.0,
      approvedBrands: ['Century Pro', 'Alstone Louvers', 'Asian Paints PU'],
      preferredVendor: 'Veneer & Panel House',
      tags: ['tv-unit', 'fluted-panel', 'pu-paint', 'living'],
      isActive: true,
    ),
    const ItemMasterEntry(
      id: 'ITM-CRP-003',
      sku: 'CRP-BED-HYD-01',
      name: 'Designer King Size Bed with Hydraulic Storage',
      category: ItemCategory.carpentry,
      subcategory: 'Beds & Headboards',
      technicalSpecs: 'Commercial Marine Ply 19mm, German gas-lift struts (150kg capacity), cushioned headboard',
      description: 'Upholstered platform bed with plush foam cushioning, premium velvet fabric, and smooth hydraulic lift mechanism.',
      imageUrl: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=400&q=80',
      uom: UnitOfMeasurement.nos,
      baseCostRate: 38000.0,
      marginPercent: 25.0,
      minRate: 45000.0,
      maxRate: 58000.0,
      gstPercent: 18.0,
      approvedBrands: ['CenturyPly', 'Ebco Hydraulics', 'DDecor Fabrics'],
      preferredVendor: 'Royal Furnishings Studio',
      tags: ['bed', 'king-size', 'hydraulic', 'bedroom'],
      isActive: true,
    ),
    const ItemMasterEntry(
      id: 'ITM-CRP-004',
      sku: 'CRP-WDR-OPN-02',
      name: 'Fluted Glass Shutter Dresser & Wardrobe',
      category: ItemCategory.carpentry,
      subcategory: 'Wardrobes & Storage',
      technicalSpecs: 'Aluminium profile rose gold frame, 5mm fluted tempered glass, LED strip inside',
      description: 'Contemporary boutique-style openable wardrobe with profile illumination and integrated vanity mirror.',
      imageUrl: 'https://images.unsplash.com/photo-1558997519-83ea9252edf8?w=400&q=80',
      uom: UnitOfMeasurement.sqft,
      baseCostRate: 1850.0,
      marginPercent: 30.0,
      minRate: 2200.0,
      maxRate: 2800.0,
      gstPercent: 18.0,
      approvedBrands: ['Saint-Gobain', 'Hafele Alumilux', 'Century BWP'],
      preferredVendor: 'Glass & Glazing World',
      tags: ['wardrobe', 'fluted-glass', 'profile-light', 'luxury'],
      isActive: true,
    ),

    // Modular Kitchen
    const ItemMasterEntry(
      id: 'ITM-KTN-001',
      sku: 'KTN-CAB-ACR-01',
      name: 'Modular Base & Overhead Cabinets (Acrylic Finish)',
      category: ItemCategory.modularKitchen,
      subcategory: 'Cabinetry',
      technicalSpecs: 'BWP 710 Calibrated Plywood, 2mm Rehau edge banding, High Gloss German Acrylic shutters',
      description: 'Moisture resistant core cabinetry engineered for Indian heavy cooking environments with sealed edges.',
      imageUrl: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=400&q=80',
      uom: UnitOfMeasurement.sqft,
      baseCostRate: 2350.0,
      marginPercent: 32.0,
      minRate: 2800.0,
      maxRate: 3600.0,
      gstPercent: 18.0,
      approvedBrands: ['Greenply BWP', 'Rehau', 'Blum', 'Hafele'],
      preferredVendor: 'Elite Modular Solutions',
      tags: ['kitchen', 'acrylic', 'cabinets', 'modular'],
      isActive: true,
    ),
    const ItemMasterEntry(
      id: 'ITM-KTN-002',
      sku: 'KTN-TDM-BLM-01',
      name: 'Blum Antaro Soft-Close Tandem Drawer Set',
      category: ItemCategory.modularKitchen,
      subcategory: 'Hardware & Drawers',
      technicalSpecs: 'Set of 3 stainless steel tandem drawers: Cutlery, Plain, and Thali baskets with 50kg load capacity',
      description: 'Feather-light glide motion with synchronised runners and built-in Blumotion soft closing dampening.',
      imageUrl: 'https://images.unsplash.com/photo-1600585152220-90363fe7e115?w=400&q=80',
      uom: UnitOfMeasurement.nos,
      baseCostRate: 18500.0,
      marginPercent: 25.0,
      minRate: 22000.0,
      maxRate: 27000.0,
      gstPercent: 18.0,
      approvedBrands: ['Blum Austria', 'Hettich Germany'],
      preferredVendor: 'Austrian Hardware Depot',
      tags: ['kitchen', 'blum', 'drawers', 'hardware'],
      isActive: true,
    ),
    const ItemMasterEntry(
      id: 'ITM-KTN-003',
      sku: 'KTN-CNT-QTZ-01',
      name: 'Quartz Kitchen Countertop (KalingaStone 20mm)',
      category: ItemCategory.modularKitchen,
      subcategory: 'Countertops',
      technicalSpecs: '20mm engineered quartz slab, machine chamfered edges, undermount sink cut-out',
      description: 'Stain, heat and scratch proof composite quartz slab with seamless silicone jointing.',
      imageUrl: 'https://images.unsplash.com/photo-1588854337236-6889d631faa8?w=400&q=80',
      uom: UnitOfMeasurement.runningFt,
      baseCostRate: 1750.0,
      marginPercent: 26.0,
      minRate: 2100.0,
      maxRate: 2600.0,
      gstPercent: 18.0,
      approvedBrands: ['KalingaStone', 'Silestone', 'Caesarstone'],
      preferredVendor: 'Classic Marble & Quartz',
      tags: ['countertop', 'quartz', 'kitchen'],
      isActive: true,
    ),
    const ItemMasterEntry(
      id: 'ITM-KTN-004',
      sku: 'KTN-PTY-HLF-01',
      name: 'Tall Pantry Unit with Blum Space Tower Pull-Outs',
      category: ItemCategory.modularKitchen,
      subcategory: 'Tall Units',
      technicalSpecs: 'Full height 7ft tall unit with 5 independent pull-out inner drawers',
      description: 'High capacity grocery pantry allowing ergonomic access from three sides with clear glass frontage.',
      imageUrl: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&q=80',
      uom: UnitOfMeasurement.nos,
      baseCostRate: 42000.0,
      marginPercent: 28.0,
      minRate: 50000.0,
      maxRate: 62000.0,
      gstPercent: 18.0,
      approvedBrands: ['Blum', 'Hafele', 'Century BWP'],
      preferredVendor: 'Elite Modular Solutions',
      tags: ['kitchen', 'pantry', 'tall-unit', 'blum'],
      isActive: true,
    ),

    // Electrical & Lighting
    const ItemMasterEntry(
      id: 'ITM-ELC-001',
      sku: 'ELC-MAG-TRK-01',
      name: 'Architectural Magnetic Track Light System',
      category: ItemCategory.electrical,
      subcategory: 'Track Lights',
      technicalSpecs: 'Recessed low voltage 48V magnetic rail, OSRAM LED drivers, modular spot & flood fixtures',
      description: 'Flexible lighting rail allowing tool-free snapping of spotlights, linear diffusers, and hanging pendants.',
      imageUrl: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400&q=80',
      uom: UnitOfMeasurement.runningFt,
      baseCostRate: 1650.0,
      marginPercent: 35.0,
      minRate: 2100.0,
      maxRate: 2800.0,
      gstPercent: 18.0,
      approvedBrands: ['Wipro Architectural', 'Philips Hue Pro', 'Hybec'],
      preferredVendor: 'Luminance Lighting Studio',
      tags: ['lighting', 'track-light', 'magnetic', 'electrical'],
      isActive: true,
    ),
    const ItemMasterEntry(
      id: 'ITM-ELC-002',
      sku: 'ELC-COV-STR-01',
      name: 'Seamless Indirect False Ceiling Cove Illumination',
      category: ItemCategory.electrical,
      subcategory: 'Cove & Strips',
      technicalSpecs: '240 LEDs/meter 24V Warm White 3000K silicone diffuser strip, Meanwell power supply',
      description: 'Dot-free indirect ambient glow installed into gypsum ceiling pelmets with remote dimmer module.',
      imageUrl: 'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=400&q=80',
      uom: UnitOfMeasurement.runningFt,
      baseCostRate: 220.0,
      marginPercent: 30.0,
      minRate: 260.0,
      maxRate: 350.0,
      gstPercent: 18.0,
      approvedBrands: ['Philips', 'Havells Professional', 'Crompton'],
      preferredVendor: 'Southern Electrical Traders',
      tags: ['cove-light', 'led-strip', 'ceiling', 'electrical'],
      isActive: true,
    ),
    const ItemMasterEntry(
      id: 'ITM-ELC-003',
      sku: 'ELC-AUT-SWT-01',
      name: 'Smart Touch Switch Automation Module (4-Gang Glass)',
      category: ItemCategory.electrical,
      subcategory: 'Smart Home & Switches',
      technicalSpecs: 'Capacitive touch tempered glass faceplate, Zigbee 3.0 / WiFi mesh protocol, scene control',
      description: 'Retrofit smart plate integrating with Alexa, Google Home, and Homio Mobile App.',
      imageUrl: 'https://images.unsplash.com/photo-1558002038-1055907df827?w=400&q=80',
      uom: UnitOfMeasurement.nos,
      baseCostRate: 4200.0,
      marginPercent: 28.0,
      minRate: 5100.0,
      maxRate: 6400.0,
      gstPercent: 18.0,
      approvedBrands: ['Schneider AvatarOn', 'Legrand Arteor', 'Wipro Smart'],
      preferredVendor: 'Home Automation Works',
      tags: ['smart-home', 'automation', 'switches', 'electrical'],
      isActive: true,
    ),

    // False Ceiling & POP
    const ItemMasterEntry(
      id: 'ITM-FCL-001',
      sku: 'FCL-GYP-IND-01',
      name: 'Saint-Gobain Gyproc Designer False Ceiling',
      category: ItemCategory.falseCeiling,
      subcategory: 'Gypsum Ceilings',
      technicalSpecs: '12.5mm Gyproc sheets, G.I. framing channels 0.50mm B.M.T., paper taped & POP flush finished',
      description: 'Levelled perimeter drop ceiling with perimeter lighting cutouts and acoustic thermal dampening.',
      imageUrl: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=400&q=80',
      uom: UnitOfMeasurement.sqft,
      baseCostRate: 110.0,
      marginPercent: 24.0,
      minRate: 130.0,
      maxRate: 165.0,
      gstPercent: 18.0,
      approvedBrands: ['Saint-Gobain Gyproc', 'USG Boral'],
      preferredVendor: 'Ceiling Master Supply Co.',
      tags: ['ceiling', 'gypsum', 'false-ceiling'],
      isActive: true,
    ),
    const ItemMasterEntry(
      id: 'ITM-FCL-002',
      sku: 'FCL-WOD-RAF-01',
      name: 'Wooden Rafter Ceiling Panelling (Teak Veneer)',
      category: ItemCategory.falseCeiling,
      subcategory: 'Decorative Ceiling',
      technicalSpecs: '2" x 2" seasoned pine wood battens dressed with natural Teak veneer and Melamine matte lacquer',
      description: 'Architectural linear ceiling rafters spaced at 4-inch centres creating warm Scandinavian warmth.',
      imageUrl: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=400&q=80',
      uom: UnitOfMeasurement.runningFt,
      baseCostRate: 380.0,
      marginPercent: 28.0,
      minRate: 460.0,
      maxRate: 580.0,
      gstPercent: 18.0,
      approvedBrands: ['Greenply Veneers', 'Timex Teak'],
      preferredVendor: 'Karnataka Timber & Hardware',
      tags: ['rafters', 'wood', 'ceiling', 'veneer'],
      isActive: true,
    ),

    // Painting & Polish
    const ItemMasterEntry(
      id: 'ITM-PNT-001',
      sku: 'PNT-ROY-LUX-01',
      name: 'Asian Paints Royale Luxury Emulsion (Full Prep)',
      category: ItemCategory.painting,
      subcategory: 'Interior Emulsion',
      technicalSpecs: '2 coats acrylic putty, 1 coat water-based primer, 2 finish coats Royale Luxury with roller finish',
      description: 'Ultra-smooth low VOC Teflon surface protection paint offering high washability and stain resistance.',
      imageUrl: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?w=400&q=80',
      uom: UnitOfMeasurement.sqft,
      baseCostRate: 28.0,
      marginPercent: 32.0,
      minRate: 35.0,
      maxRate: 45.0,
      gstPercent: 18.0,
      approvedBrands: ['Asian Paints Royale', 'Dulux Velvet Touch', 'Berger Silk'],
      preferredVendor: 'Metro Paints & Chemical Co.',
      tags: ['paint', 'royale', 'emulsion', 'walls'],
      isActive: true,
    ),
    const ItemMasterEntry(
      id: 'ITM-PNT-002',
      sku: 'PNT-LIM-WAS-01',
      name: 'Italian Limewash / Marmorino Venetian Stucco Texture',
      category: ItemCategory.painting,
      subcategory: 'Specialty Textures',
      technicalSpecs: 'Authentic slaked lime plaster applied in 3 hand-burnished trowel coats with natural beeswax seal',
      description: 'Artisanal organic textured accent wall with rich micro-marbling depth and velvety tactile feel.',
      imageUrl: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=400&q=80',
      uom: UnitOfMeasurement.sqft,
      baseCostRate: 145.0,
      marginPercent: 35.0,
      minRate: 180.0,
      maxRate: 240.0,
      gstPercent: 18.0,
      approvedBrands: ['Oikos Italy', 'San Marco', 'Asian Paints Royale Play Stucco'],
      preferredVendor: 'Artisanal Wall Finishes',
      tags: ['texture', 'limewash', 'venetian-stucco', 'accent-wall'],
      isActive: true,
    ),

    // Plumbing & Sanitary
    const ItemMasterEntry(
      id: 'ITM-PLM-001',
      sku: 'PLM-DIV-THM-01',
      name: 'Grohe Concealed Thermostatic Shower Diverter Set',
      category: ItemCategory.plumbing,
      subcategory: 'Faucets & Showers',
      technicalSpecs: 'Grohe Rapido SmartBox concealed valve, 3-way diverter, 300mm rain shower, baton hand spray',
      description: 'Anti-scald temperature stabiliser with Grohe StarLight chrome finish and TurboStat cartridge.',
      imageUrl: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=400&q=80',
      uom: UnitOfMeasurement.nos,
      baseCostRate: 28500.0,
      marginPercent: 22.0,
      minRate: 33000.0,
      maxRate: 40000.0,
      gstPercent: 18.0,
      approvedBrands: ['Grohe Germany', 'Kohler USA', 'Jaquar Artize'],
      preferredVendor: 'Sanitary Ware Palace',
      tags: ['plumbing', 'shower', 'grohe', 'diverter'],
      isActive: true,
    ),

    // Loose Furniture
    const ItemMasterEntry(
      id: 'ITM-FUR-001',
      sku: 'FUR-SOF-SEC-01',
      name: 'Custom L-Shape Sectional Chesterfield Sofa',
      category: ItemCategory.looseFurniture,
      subcategory: 'Sofas & Seating',
      technicalSpecs: 'Seasoned Sal wood internal frame, high resilience 40-density foam, Sarom Boucle / Nubuck upholstery',
      description: 'Generously proportioned 6-seater sofa with deep seating ergonomics and accent bolster cushions.',
      imageUrl: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&q=80',
      uom: UnitOfMeasurement.nos,
      baseCostRate: 64000.0,
      marginPercent: 30.0,
      minRate: 78000.0,
      maxRate: 98000.0,
      gstPercent: 18.0,
      approvedBrands: ['Sarom Fabrics', 'Sleepwell Foam', 'Homio Studio Craft'],
      preferredVendor: 'Royal Furnishings Studio',
      tags: ['sofa', 'sectional', 'living', 'furniture'],
      isActive: true,
    ),
    const ItemMasterEntry(
      id: 'ITM-FUR-002',
      sku: 'FUR-DIN-MRB-01',
      name: '6-Seater Italian Bottochino Marble Dining Table',
      category: ItemCategory.looseFurniture,
      subcategory: 'Dining Tables',
      technicalSpecs: '20mm Italian Bottochino marble top with chamfered edge, cast brass sculptural base',
      description: 'Opulent centrepiece dining table seating 6-8 people with protective resin polishing.',
      imageUrl: 'https://images.unsplash.com/photo-1617806118233-18e1de247200?w=400&q=80',
      uom: UnitOfMeasurement.nos,
      baseCostRate: 52000.0,
      marginPercent: 28.0,
      minRate: 62000.0,
      maxRate: 76000.0,
      gstPercent: 18.0,
      approvedBrands: ['Classic Marble', 'Homio Artisans'],
      preferredVendor: 'Artisan Metal & Stone Works',
      tags: ['dining', 'marble', 'table', 'furniture'],
      isActive: true,
    ),

    // Soft Furnishings & Decor
    const ItemMasterEntry(
      id: 'ITM-DEC-001',
      sku: 'DEC-CUR-DMC-01',
      name: 'Motorized Dual-Layer Ripple Fold Curtains',
      category: ItemCategory.softFurnishing,
      subcategory: 'Curtains & Drapes',
      technicalSpecs: '100% Blackout fabric + sheer linen layer, Somfy RTS wireless motorized track',
      description: 'Effortless automated drapery system synchronized with sunrise/sunset scenes via smart remote.',
      imageUrl: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=400&q=80',
      uom: UnitOfMeasurement.runningFt,
      baseCostRate: 850.0,
      marginPercent: 32.0,
      minRate: 1050.0,
      maxRate: 1400.0,
      gstPercent: 18.0,
      approvedBrands: ['Somfy France', 'DDecor', 'Pure Fine Fabrics'],
      preferredVendor: 'Window Dressing Emporium',
      tags: ['curtains', 'motorized', 'somfy', 'decor'],
      isActive: true,
    ),
  ];

  // ---------------------------------------------------------------------------
  // 2. Named Rate Cards (PRD Section 30.3)
  // ---------------------------------------------------------------------------
  static final List<RateCard> rateCards = [
    RateCard(
      id: 'RC-001',
      name: 'Standard Budget Tier',
      description: 'Optimized value pricing for rental assets, first-time homeowners, and investment apartments.',
      tier: MaterialTier.budget,
      effectiveDate: DateTime(2026, 1, 1),
      isActive: true,
      isDefault: false,
      markupPercent: 18.0,
      itemRateOverrides: {
        'ITM-CRP-001': 1600.0,
        'ITM-KTN-001': 2600.0,
        'ITM-PNT-001': 32.0,
      },
    ),
    RateCard(
      id: 'RC-002',
      name: 'Homio Premium Signature',
      description: 'Our benchmark residential interior specification with marine grade ply and soft-close German hardware.',
      tier: MaterialTier.premium,
      effectiveDate: DateTime(2026, 1, 1),
      isActive: true,
      isDefault: true,
      markupPercent: 26.0,
      itemRateOverrides: {
        'ITM-CRP-001': 1850.0,
        'ITM-KTN-001': 3100.0,
        'ITM-PNT-001': 38.0,
      },
    ),
    RateCard(
      id: 'RC-003',
      name: 'Ultra-Luxe Villa & Penthouse',
      description: 'Custom bespoke joinery, PU lacquers, Italian stones, and automated smart integrations.',
      tier: MaterialTier.luxury,
      effectiveDate: DateTime(2026, 1, 1),
      isActive: true,
      isDefault: false,
      markupPercent: 35.0,
      itemRateOverrides: {
        'ITM-CRP-001': 2300.0,
        'ITM-KTN-001': 3900.0,
        'ITM-PNT-001': 48.0,
      },
    ),
    RateCard(
      id: 'RC-004',
      name: 'Commercial & Developer B2B',
      description: 'Volume-based discounted rates for builder sample flats and corporate spaces.',
      tier: MaterialTier.premium,
      effectiveDate: DateTime(2026, 2, 1),
      isActive: true,
      isDefault: false,
      markupPercent: 15.0,
      itemRateOverrides: {
        'ITM-CIV-001': 130.0,
        'ITM-FCL-001': 125.0,
      },
    ),
  ];

  // ---------------------------------------------------------------------------
  // 3. Rate Change Audit Trail (PRD Section 30.4)
  // ---------------------------------------------------------------------------
  static final List<RateHistoryEntry> rateHistory = [
    RateHistoryEntry(
      id: 'RH-101',
      itemMasterId: 'ITM-CRP-001',
      itemName: 'Full Height Sliding Wardrobe with Loft',
      oldBaseRate: 1350.0,
      newBaseRate: 1450.0,
      oldSellingRate: 1728.0,
      newSellingRate: 1856.0,
      changedBy: 'Arun Varma (Pricing Lead)',
      changeReason: 'Century Plywood price hike of 7.5% announced in Q1 2026',
      changedAt: DateTime.now().subtract(const Duration(days: 12)),
    ),
    RateHistoryEntry(
      id: 'RH-102',
      itemMasterId: 'ITM-KTN-001',
      itemName: 'Modular Base & Overhead Cabinets (Acrylic Finish)',
      oldBaseRate: 2200.0,
      newBaseRate: 2350.0,
      oldSellingRate: 2904.0,
      newSellingRate: 3102.0,
      changedBy: 'Pooja Iyer (Supply Head)',
      changeReason: 'Rehau edge banding import customs revision',
      changedAt: DateTime.now().subtract(const Duration(days: 28)),
    ),
    RateHistoryEntry(
      id: 'RH-103',
      itemMasterId: 'ITM-PNT-001',
      itemName: 'Asian Paints Royale Luxury Emulsion',
      oldBaseRate: 25.0,
      newBaseRate: 28.0,
      oldSellingRate: 33.0,
      newSellingRate: 37.0,
      changedBy: 'Arun Varma (Pricing Lead)',
      changeReason: 'Annual labour union minimum wage hike',
      changedAt: DateTime.now().subtract(const Duration(days: 45)),
    ),
  ];

  // ---------------------------------------------------------------------------
  // 4. Document Templates (PRD Section 31.2)
  // ---------------------------------------------------------------------------
  static final List<QuotationTemplate> documentTemplates = [
    const QuotationTemplate(
      id: 'tmpl_standard_01',
      name: 'Homio Signature Minimalist',
      description: 'Clean monochrome aesthetic with large typography, perfect for premium apartment proposals.',
      type: QuotationType.residentialInterior,
      isDefault: true,
      coverTheme: 'Modern Elegance',
      primaryColorHex: '#1E3A8A',
      fontName: 'Inter',
      footerNote: 'This quotation is generated electronically by Homio Operations & is valid for 15 days.',
      termsAndConditions:
          '1. Quotation prices include standard transportation, installation and on-site testing.\n2. 50% advance before manufacturing kicks off at factory floor.\n3. Any structural civil changes outside BOQ scope billed on actuals.',
      includedSections: [
        DocumentSectionType.coverPage,
        DocumentSectionType.executiveSummary,
        DocumentSectionType.scopeOfWork,
        DocumentSectionType.roomBreakdown,
        DocumentSectionType.boqItemized,
        DocumentSectionType.paymentMilestones,
        DocumentSectionType.termsAndConditions,
      ],
    ),
    const QuotationTemplate(
      id: 'tmpl_luxury_02',
      name: 'Executive Villa & Penthouse Deck',
      description: 'Rich dark-accented presentation deck featuring 3D concept moodboards and material specifications.',
      type: QuotationType.luxuryVilla,
      isDefault: false,
      coverTheme: 'Royal Slate & Gold',
      primaryColorHex: '#0F172A',
      fontName: 'Playfair Display',
      footerNote: 'Homio Luxury Studio — Private & Confidential Client Document.',
      termsAndConditions:
          '1. Bespoke imported materials subject to shipping customs timeline.\n2. Designer site visits included up to 24 milestones.\n3. 10-year comprehensive warranty on all structural cabinetry.',
      includedSections: [
        DocumentSectionType.coverPage,
        DocumentSectionType.renderGallery,
        DocumentSectionType.executiveSummary,
        DocumentSectionType.materialSpecs,
        DocumentSectionType.roomBreakdown,
        DocumentSectionType.boqItemized,
        DocumentSectionType.paymentMilestones,
        DocumentSectionType.termsAndConditions,
        DocumentSectionType.warrantyAndSignoff,
      ],
    ),
    const QuotationTemplate(
      id: 'tmpl_kitchen_03',
      name: 'Modular Kitchen Specialist Scope',
      description: 'Focused technical specification sheet with detailed appliance cut-outs and hardware warranties.',
      type: QuotationType.modularKitchen,
      isDefault: false,
      coverTheme: 'Warm Terracotta',
      primaryColorHex: '#C2410C',
      fontName: 'Plus Jakarta Sans',
      footerNote: 'Certified Blum Industry Partner — Guaranteed 200,000 drawer cycles.',
      termsAndConditions:
          '1. Granite / Quartz countertop fabrication timeline commences after base carcass installation.\n2. Electrical and plumbing points must be in place as per Homio MEP drawing.',
      includedSections: [
        DocumentSectionType.coverPage,
        DocumentSectionType.materialSpecs,
        DocumentSectionType.boqItemized,
        DocumentSectionType.paymentMilestones,
        DocumentSectionType.termsAndConditions,
      ],
    ),
    const QuotationTemplate(
      id: 'tmpl_turnkey_04',
      name: 'Turnkey Comprehensive Project Contract',
      description: 'Full-fledged legal grade proposal complete with civil clauses, penalty SLAs, and milestone schedules.',
      type: QuotationType.turnkey,
      isDefault: false,
      coverTheme: 'Deep Forest',
      primaryColorHex: '#064E3B',
      fontName: 'Outfit',
      footerNote: 'Governed by Indian Arbitration and Conciliation Act.',
      termsAndConditions:
          '1. Delivery deadline 60 working days from civil handover.\n2. Handover delay compensation at ₹1,500/day capped at 5% of project value.\n3. Defect liability period 12 months post-possession.',
      includedSections: [
        DocumentSectionType.coverPage,
        DocumentSectionType.executiveSummary,
        DocumentSectionType.scopeOfWork,
        DocumentSectionType.roomBreakdown,
        DocumentSectionType.boqItemized,
        DocumentSectionType.materialSpecs,
        DocumentSectionType.paymentMilestones,
        DocumentSectionType.termsAndConditions,
        DocumentSectionType.warrantyAndSignoff,
      ],
    ),
  ];

  // ---------------------------------------------------------------------------
  // 5. Complete Production Quotations (PRD Section 4.3 & 5)
  // ---------------------------------------------------------------------------
  static final List<Quotation> quotations = [
    // 1. Accepted / Booked Luxury Villa
    Quotation(
      id: 'QUO-2026-0891',
      quoteNumber: 'QUO-2026-0891',
      title: 'The Camellias — 4BHK Bespoke Interior Execution',
      quotationType: QuotationType.luxuryVilla,
      revisionNumber: 2,
      leadId: 'LD-9902',
      clientName: 'Dr. Arjun K. Singhania',
      clientPhone: '+91 98201 44552',
      clientEmail: 'arjun.singhania@apexheart.org',
      projectTitle: 'The Camellias, Golf Course Rd',
      projectLocation: 'DLF Phase 5, Gurgaon',
      designerName: 'Ananya Roy',
      salesOwner: 'Vikram Malhotra',
      projectManager: 'Rajesh Sharma',
      createdBy: 'Vikram Malhotra',
      coverImageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&q=80',
      submissionDate: DateTime.now().subtract(const Duration(days: 4)),
      discountExpiryDate: DateTime.now().add(const Duration(days: 10)),
      status: QuotationStatus.accepted,
      hideRate: false,
      hideSqft: false,
      showAmount: true,
      discountPercent: 5.0,
      gstPercent: 18.0,
      amountPaid: 850000.0,
      tags: ['VIP', 'Luxury', 'Golf Course', 'Fast-Track'],
      customerInfo: const CustomerInfo(
        id: 'CUST-001',
        name: 'Dr. Arjun K. Singhania',
        phone: '+91 98201 44552',
        email: 'arjun.singhania@apexheart.org',
        address: 'Tower 3, Penthouse 2401, The Camellias',
        city: 'Gurgaon',
        state: 'Haryana',
        pinCode: '122002',
        company: 'Singhania Healthcare Trust',
        leadSource: 'Architect Referral',
      ),
      projectInfo: ProjectInfo(
        id: 'PRJ-001',
        name: 'The Camellias Penthouse 2401',
        code: 'PRJ-GUR-2401',
        type: 'Turnkey Luxury Villa',
        location: 'DLF Phase 5',
        city: 'Gurgaon',
        projectManager: 'Rajesh Sharma',
        designer: 'Ananya Roy',
        startDate: DateTime.now().subtract(const Duration(days: 10)),
        targetCompletionDate: DateTime.now().add(const Duration(days: 90)),
        totalBudget: 4500000.0,
      ),
      paymentSchedule: [
        PaymentMilestone(
          id: 'PM-01',
          title: 'Booking Advance (10%)',
          percentage: 10.0,
          amount: 247000.0,
          dueDate: DateTime.now().subtract(const Duration(days: 3)),
          triggerEvent: 'Signoff of estimation & kickoff',
          isPaid: true,
          paidDate: DateTime.now().subtract(const Duration(days: 3)),
          paymentReference: 'HDFC-NEFT-9912401',
        ),
        PaymentMilestone(
          id: 'PM-02',
          title: 'Factory Production Kickoff (40%)',
          percentage: 40.0,
          amount: 988000.0,
          dueDate: DateTime.now().add(const Duration(days: 15)),
          triggerEvent: 'Civil clearance & factory CNC cutting start',
          isPaid: false,
        ),
        PaymentMilestone(
          id: 'PM-03',
          title: 'Dispatch to Site (40%)',
          percentage: 40.0,
          amount: 988000.0,
          dueDate: DateTime.now().add(const Duration(days: 50)),
          triggerEvent: 'Factory inspection sign-off and vehicle dispatch',
          isPaid: false,
        ),
        PaymentMilestone(
          id: 'PM-04',
          title: 'Handover & Snag Resolution (10%)',
          percentage: 10.0,
          amount: 247000.0,
          dueDate: DateTime.now().add(const Duration(days: 85)),
          triggerEvent: 'Final deep cleaning and virtual punch-list handover',
          isPaid: false,
        ),
      ],
      revisions: [
        QuotationRevision(
          id: 'REV-01',
          quotationId: 'QUO-2026-0891',
          revisionNumber: 1,
          title: 'Initial Concept Estimate',
          changesSummary: 'First draft presented to client during design discovery meeting.',
          previousTotal: 0.0,
          newTotal: 2650000.0,
          createdAt: DateTime.now().subtract(const Duration(days: 10)),
          createdBy: 'Vikram Malhotra',
        ),
        QuotationRevision(
          id: 'REV-02',
          quotationId: 'QUO-2026-0891',
          revisionNumber: 2,
          title: 'Upgraded to Italian Stucco & Blum Servo-Drive',
          changesSummary: 'Client requested automated kitchen drawers and handcrafted Venetian marble walls.',
          previousTotal: 2650000.0,
          newTotal: 2845000.0,
          createdAt: DateTime.now().subtract(const Duration(days: 4)),
          createdBy: 'Ananya Roy',
          approvedBy: 'Sameer Sen (VP Design)',
        ),
      ],
      approvals: [
        QuotationApproval(
          id: 'AP-01',
          approverName: 'Sameer Sen',
          approverRole: 'VP of Design & Quality',
          status: ApprovalStatus.approved,
          comments: 'Exceeds margin threshold. Client approved premium materials.',
          requestedAt: DateTime.now().subtract(const Duration(days: 4, hours: 2)),
          respondedAt: DateTime.now().subtract(const Duration(days: 4)),
        ),
      ],
      activities: [
        QuotationActivity(
          id: 'ACT-01',
          quotationId: 'QUO-2026-0891',
          timestamp: DateTime.now().subtract(const Duration(days: 4)),
          actorName: 'Ananya Roy',
          actorRole: 'Senior Interior Architect',
          action: 'Quotation Revised',
          description: 'Added fluted glass wardrobes and upgraded kitchen hardware to Blum Servo-Drive.',
          icon: Icons.edit_rounded,
        ),
        QuotationActivity(
          id: 'ACT-02',
          quotationId: 'QUO-2026-0891',
          timestamp: DateTime.now().subtract(const Duration(days: 3)),
          actorName: 'Dr. Arjun K. Singhania',
          actorRole: 'Client',
          action: 'Quotation Accepted Online',
          description: 'Client accepted proposal via Homio Portal and initiated advance payment.',
          icon: Icons.verified_rounded,
        ),
      ],
      rooms: [
        RoomArea(
          id: 'RM-01',
          roomName: 'Grand Living & Dining Foyer',
          areaType: RoomAreaType.livingRoom,
          customName: 'Formal Reception Lounge',
          floor: 24,
          lengthFt: 28.0,
          widthFt: 18.0,
          heightFt: 11.5,
          tier: MaterialTier.luxury,
          items: [
            QuotationItem(
              id: 'QI-01',
              itemMasterId: 'ITM-CRP-002',
              itemCode: 'CRP-ENT-TVU-01',
              name: 'TV Entertainment Console & Fluted Panel Backdrop',
              category: ItemCategory.carpentry,
              materialSpecs: 'Charcoal louvers / WPC fluted panels, floating console with PU paint finish',
              uom: UnitOfMeasurement.runningFt,
              quantity: 18.0,
              rate: 2750.0,
              marginPercent: 30.0,
              discountPercent: 5.0,
            ),
            QuotationItem(
              id: 'QI-02',
              itemMasterId: 'ITM-PNT-002',
              itemCode: 'PNT-LIM-WAS-01',
              name: 'Italian Limewash / Marmorino Venetian Stucco Texture',
              category: ItemCategory.painting,
              materialSpecs: 'Authentic slaked lime plaster applied in 3 hand-burnished trowel coats',
              uom: UnitOfMeasurement.sqft,
              quantity: 420.0,
              rate: 195.0,
              marginPercent: 35.0,
            ),
            QuotationItem(
              id: 'QI-03',
              itemMasterId: 'ITM-ELC-001',
              itemCode: 'ELC-MAG-TRK-01',
              name: 'Architectural Magnetic Track Light System',
              category: ItemCategory.electrical,
              materialSpecs: 'Recessed low voltage 48V magnetic rail, OSRAM LED drivers',
              uom: UnitOfMeasurement.runningFt,
              quantity: 36.0,
              rate: 2250.0,
              marginPercent: 35.0,
            ),
            QuotationItem(
              id: 'QI-04',
              itemMasterId: 'ITM-FUR-001',
              itemCode: 'FUR-SOF-SEC-01',
              name: 'Custom L-Shape Sectional Chesterfield Sofa',
              category: ItemCategory.looseFurniture,
              materialSpecs: 'Seasoned Sal wood internal frame, high resilience foam, Sarom Boucle',
              uom: UnitOfMeasurement.nos,
              quantity: 1.0,
              rate: 85000.0,
              marginPercent: 30.0,
            ),
          ],
        ),
        RoomArea(
          id: 'RM-02',
          roomName: 'Master Bedroom Suite',
          areaType: RoomAreaType.masterBedroom,
          floor: 24,
          lengthFt: 20.0,
          widthFt: 16.0,
          heightFt: 10.5,
          tier: MaterialTier.luxury,
          items: [
            QuotationItem(
              id: 'QI-05',
              itemMasterId: 'ITM-CRP-004',
              itemCode: 'CRP-WDR-OPN-02',
              name: 'Fluted Glass Shutter Dresser & Wardrobe',
              category: ItemCategory.carpentry,
              materialSpecs: 'Aluminium profile rose gold frame, 5mm fluted tempered glass, LED strip inside',
              uom: UnitOfMeasurement.sqft,
              quantity: 140.0,
              rate: 2400.0,
              marginPercent: 30.0,
            ),
            QuotationItem(
              id: 'QI-06',
              itemMasterId: 'ITM-CRP-003',
              itemCode: 'CRP-BED-HYD-01',
              name: 'Designer King Size Bed with Hydraulic Storage',
              category: ItemCategory.carpentry,
              materialSpecs: 'Commercial Marine Ply 19mm, German gas-lift struts, cushioned headboard',
              uom: UnitOfMeasurement.nos,
              quantity: 1.0,
              rate: 52000.0,
              marginPercent: 25.0,
            ),
          ],
        ),
      ],
    ),

    // 2. Sent / Viewed — High Urgency (Expiring in 18 hours)
    Quotation(
      id: 'QUO-2026-0894',
      quoteNumber: 'QUO-2026-0894',
      title: 'Oberoi Sky City — 3BHK Turnkey Interior',
      quotationType: QuotationType.residentialInterior,
      revisionNumber: 1,
      leadId: 'LD-9915',
      clientName: 'Meera & Rohan Deshmukh',
      clientPhone: '+91 98205 91823',
      clientEmail: 'rohan.deshmukh@tcs.com',
      projectTitle: 'Oberoi Sky City, Tower B',
      projectLocation: 'Borivali East, Mumbai',
      designerName: 'Devika Nair',
      salesOwner: 'Kunal Kapoor',
      projectManager: 'Amitabh Joshi',
      createdBy: 'Kunal Kapoor',
      coverImageUrl: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=1200&q=80',
      submissionDate: DateTime.now().subtract(const Duration(days: 6)),
      discountExpiryDate: DateTime.now().add(const Duration(hours: 18)),
      status: QuotationStatus.viewed,
      discountPercent: 8.0,
      gstPercent: 18.0,
      tags: ['Hot Lead', 'Urgency', 'Expiring Today'],
      customerInfo: const CustomerInfo(
        id: 'CUST-002',
        name: 'Meera & Rohan Deshmukh',
        phone: '+91 98205 91823',
        email: 'rohan.deshmukh@tcs.com',
        address: 'Flat 1804, Tower B, Oberoi Sky City',
        city: 'Mumbai',
        state: 'Maharashtra',
        pinCode: '400066',
        company: 'Tata Consultancy Services',
      ),
      rooms: [
        RoomArea(
          id: 'RM-11',
          roomName: 'Modular Gourmet Kitchen',
          areaType: RoomAreaType.kitchen,
          floor: 18,
          lengthFt: 14.0,
          widthFt: 10.0,
          heightFt: 10.0,
          tier: MaterialTier.premium,
          items: [
            QuotationItem(
              id: 'QI-11',
              itemMasterId: 'ITM-KTN-001',
              itemCode: 'KTN-CAB-ACR-01',
              name: 'Modular Base & Overhead Cabinets (Acrylic Finish)',
              category: ItemCategory.modularKitchen,
              materialSpecs: 'BWP 710 Calibrated Plywood, Rehau edge banding, High Gloss Acrylic',
              uom: UnitOfMeasurement.sqft,
              quantity: 110.0,
              rate: 2950.0,
              marginPercent: 32.0,
            ),
            QuotationItem(
              id: 'QI-12',
              itemMasterId: 'ITM-KTN-002',
              itemCode: 'KTN-TDM-BLM-01',
              name: 'Blum Antaro Soft-Close Tandem Drawer Set',
              category: ItemCategory.modularKitchen,
              materialSpecs: 'Set of 3 stainless steel tandem drawers',
              uom: UnitOfMeasurement.nos,
              quantity: 2.0,
              rate: 23500.0,
              marginPercent: 25.0,
            ),
          ],
        ),
      ],
    ),

    // 3. Draft / In Progress Builder
    Quotation(
      id: 'QUO-2026-0902',
      quoteNumber: 'QUO-2026-0902',
      title: 'Prestige Falcon City — 2.5BHK Modern Nordic Style',
      quotationType: QuotationType.residentialInterior,
      revisionNumber: 1,
      leadId: 'LD-9930',
      clientName: 'Sunita & Deepak Verma',
      clientPhone: '+91 97411 88201',
      clientEmail: 'deepak.verma@wipro.com',
      projectTitle: 'Prestige Falcon City, Flat 1204',
      projectLocation: 'Kanakapura Road, Bangalore',
      designerName: 'Rahul Sen',
      salesOwner: 'Vikram Malhotra',
      projectManager: 'Rajesh Sharma',
      createdBy: 'Rahul Sen',
      coverImageUrl: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=1200&q=80',
      submissionDate: DateTime.now().subtract(const Duration(hours: 5)),
      discountExpiryDate: DateTime.now().add(const Duration(days: 7)),
      status: QuotationStatus.draft,
      discountPercent: 6.0,
      gstPercent: 18.0,
      tags: ['Draft', 'Nordic', 'Bangalore'],
      customerInfo: const CustomerInfo(
        id: 'CUST-003',
        name: 'Sunita & Deepak Verma',
        phone: '+91 97411 88201',
        email: 'deepak.verma@wipro.com',
        city: 'Bangalore',
      ),
      rooms: [
        RoomArea(
          id: 'RM-21',
          roomName: 'Living Room',
          areaType: RoomAreaType.livingRoom,
          floor: 12,
          lengthFt: 18.0,
          widthFt: 13.0,
          heightFt: 10.0,
          tier: MaterialTier.premium,
          items: [
            QuotationItem(
              id: 'QI-21',
              itemMasterId: 'ITM-FCL-001',
              itemCode: 'FCL-GYP-IND-01',
              name: 'Saint-Gobain Gyproc Designer False Ceiling',
              category: ItemCategory.falseCeiling,
              materialSpecs: '12.5mm Gyproc sheets, G.I. framing channels 0.50mm',
              uom: UnitOfMeasurement.sqft,
              quantity: 234.0,
              rate: 135.0,
              marginPercent: 24.0,
            ),
          ],
        ),
      ],
    ),

    // 4. Internal Review / Approval Pending
    Quotation(
      id: 'QUO-2026-0888',
      quoteNumber: 'QUO-2026-0888',
      title: 'Hiranandani Estate — 4BHK Custom Renovation',
      quotationType: QuotationType.renovation,
      revisionNumber: 2,
      leadId: 'LD-9890',
      clientName: 'Nitin & Shweta Parekh',
      clientPhone: '+91 98210 66332',
      clientEmail: 'parekh.nitin@rediffmail.com',
      projectTitle: 'Hiranandani Estate, Pelican Tower',
      projectLocation: 'Ghodbunder Road, Thane',
      designerName: 'Devika Nair',
      salesOwner: 'Kunal Kapoor',
      projectManager: 'Amitabh Joshi',
      createdBy: 'Devika Nair',
      coverImageUrl: 'https://images.unsplash.com/photo-1595428774223-ef52624120d2?w=1200&q=80',
      submissionDate: DateTime.now().subtract(const Duration(days: 2)),
      discountExpiryDate: DateTime.now().add(const Duration(days: 5)),
      status: QuotationStatus.internalReview,
      discountPercent: 12.0, // High discount requiring VP approval
      gstPercent: 18.0,
      tags: ['Approval Needed', 'High Discount'],
      approvals: [
        QuotationApproval(
          id: 'AP-02',
          approverName: 'Sameer Sen',
          approverRole: 'VP Design & Pricing',
          status: ApprovalStatus.pending,
          comments: 'Requested 12% discount exceeds sales manager threshold of 7.5%. Pending VP review.',
          requestedAt: DateTime.now().subtract(const Duration(hours: 14)),
        ),
      ],
      rooms: [
        RoomArea(
          id: 'RM-31',
          roomName: 'Master Bedroom',
          areaType: RoomAreaType.masterBedroom,
          floor: 8,
          lengthFt: 16.0,
          widthFt: 14.0,
          heightFt: 9.5,
          tier: MaterialTier.premium,
          items: [
            QuotationItem(
              id: 'QI-31',
              itemMasterId: 'ITM-CRP-001',
              itemCode: 'CRP-WDR-SLD-01',
              name: 'Full Height Sliding Wardrobe with Loft',
              category: ItemCategory.carpentry,
              materialSpecs: 'Century BWP Plywood 18mm, 1.0mm Merino laminate',
              uom: UnitOfMeasurement.sqft,
              quantity: 112.0,
              rate: 1850.0,
              marginPercent: 28.0,
              discountPercent: 12.0,
            ),
          ],
        ),
      ],
    ),

    // 5. Expired Discount
    Quotation(
      id: 'QUO-2026-0870',
      quoteNumber: 'QUO-2026-0870',
      title: 'Godrej Woodsman Estate — 3BHK Modular Scope',
      quotationType: QuotationType.modularKitchen,
      revisionNumber: 1,
      leadId: 'LD-9822',
      clientName: 'Vikas & Shruti Saxena',
      clientPhone: '+91 99002 44109',
      clientEmail: 'vikas.saxena@infosys.com',
      projectTitle: 'Godrej Woodsman Estate, Tower 4',
      projectLocation: 'Hebbal, Bangalore',
      designerName: 'Rahul Sen',
      salesOwner: 'Vikram Malhotra',
      projectManager: 'Rajesh Sharma',
      createdBy: 'Vikram Malhotra',
      coverImageUrl: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=1200&q=80',
      submissionDate: DateTime.now().subtract(const Duration(days: 20)),
      discountExpiryDate: DateTime.now().subtract(const Duration(days: 2)),
      status: QuotationStatus.expired,
      discountPercent: 10.0,
      gstPercent: 18.0,
      tags: ['Discount Expired', 'Re-engage'],
      rooms: [
        RoomArea(
          id: 'RM-41',
          roomName: 'Kitchen & Utility',
          areaType: RoomAreaType.kitchen,
          floor: 4,
          lengthFt: 15.0,
          widthFt: 11.0,
          heightFt: 9.5,
          tier: MaterialTier.premium,
          items: [
            QuotationItem(
              id: 'QI-41',
              itemMasterId: 'ITM-KTN-001',
              itemCode: 'KTN-CAB-ACR-01',
              name: 'Modular Base & Overhead Cabinets (Acrylic Finish)',
              category: ItemCategory.modularKitchen,
              materialSpecs: 'BWP 710 Calibrated Plywood, Rehau edge banding',
              uom: UnitOfMeasurement.sqft,
              quantity: 120.0,
              rate: 3100.0,
              marginPercent: 32.0,
            ),
          ],
        ),
      ],
    ),

    // 6. Booked / Converted to Ongoing Project
    Quotation(
      id: 'QUO-2026-0865',
      quoteNumber: 'QUO-2026-0865',
      title: 'Emaar Marbella Villa — Complete Architectural Interior',
      quotationType: QuotationType.luxuryVilla,
      revisionNumber: 3,
      leadId: 'LD-9801',
      clientName: 'Rajesh & Sonal Goenka',
      clientPhone: '+91 98111 23091',
      clientEmail: 'rajesh@goenkatex.com',
      projectTitle: 'Emaar Marbella Villa #42',
      projectLocation: 'Sector 66, Gurgaon',
      designerName: 'Ananya Roy',
      salesOwner: 'Vikram Malhotra',
      projectManager: 'Rajesh Sharma',
      createdBy: 'Vikram Malhotra',
      coverImageUrl: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=1200&q=80',
      submissionDate: DateTime.now().subtract(const Duration(days: 25)),
      discountExpiryDate: DateTime.now().subtract(const Duration(days: 10)),
      status: QuotationStatus.booked,
      discountPercent: 7.5,
      gstPercent: 18.0,
      amountPaid: 3200000.0,
      tags: ['Booked', 'Under Execution', 'Marbella'],
      rooms: [
        RoomArea(
          id: 'RM-51',
          roomName: 'Foyer & Living Area',
          areaType: RoomAreaType.livingRoom,
          floor: 0,
          lengthFt: 30.0,
          widthFt: 22.0,
          heightFt: 12.0,
          tier: MaterialTier.luxury,
          items: [
            QuotationItem(
              id: 'QI-51',
              itemMasterId: 'ITM-FUR-002',
              itemCode: 'FUR-DIN-MRB-01',
              name: '6-Seater Italian Bottochino Marble Dining Table',
              category: ItemCategory.looseFurniture,
              materialSpecs: '20mm Italian Bottochino marble top with chamfered edge',
              uom: UnitOfMeasurement.nos,
              quantity: 1.0,
              rate: 68000.0,
              marginPercent: 28.0,
            ),
          ],
        ),
      ],
    ),

    // 7. Submitted Quotation Pending Client Feedback
    Quotation(
      id: 'QUO-2026-0915',
      quoteNumber: 'QUO-2026-0915',
      title: 'Sobha Dream Acres — 2BHK Complete Interior Package',
      quotationType: QuotationType.residentialInterior,
      revisionNumber: 1,
      leadId: 'LD-9945',
      clientName: 'Siddharth & Priya Nair',
      clientPhone: '+91 98450 11223',
      clientEmail: 'siddharth.nair@gmail.com',
      projectTitle: 'Sobha Dream Acres, Tower 12',
      projectLocation: 'Panathur, Bangalore',
      designerName: 'Rahul Sen',
      salesOwner: 'Kunal Kapoor',
      projectManager: 'Rajesh Sharma',
      createdBy: 'Rahul Sen',
      coverImageUrl: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=1200&q=80',
      submissionDate: DateTime.now().subtract(const Duration(days: 2)),
      discountExpiryDate: DateTime.now().add(const Duration(days: 5)),
      status: QuotationStatus.submitted,
      hideRate: false,
      hideSqft: false,
      showAmount: true,
      discountPercent: 8.0,
      discountType: DiscountType.percentage,
      gstPercent: 18.0,
      amountPaid: 0.0,
      tags: ['Submitted', 'Residential', 'Sobha'],
      rooms: [
        RoomArea(
          id: 'RM-71',
          roomName: 'Living & Dining Hall',
          areaType: RoomAreaType.livingRoom,
          floor: 12,
          lengthFt: 22.0,
          widthFt: 14.0,
          heightFt: 10.0,
          tier: MaterialTier.premium,
          items: [
            QuotationItem(
              id: 'QI-71',
              itemMasterId: 'ITM-CRP-001',
              itemCode: 'CRP-TVU-WLN-01',
              name: 'Floating TV Console with Louvered Fluted Wall Paneling',
              category: ItemCategory.carpentry,
              materialSpecs: 'Greenply BWP 710 Plywood, Charcoal Louvers, PU matte finish',
              uom: UnitOfMeasurement.sqft,
              quantity: 80.0,
              rate: 1850.0,
              marginPercent: 28.0,
            ),
          ],
        ),
      ],
    ),

    // 8. Under Review Internal Commercial Approval
    Quotation(
      id: 'QUO-2026-0920',
      quoteNumber: 'QUO-2026-0920',
      title: 'Lodha Park — 3BHK Master Renovation & Smart Automation',
      quotationType: QuotationType.renovation,
      revisionNumber: 1,
      leadId: 'LD-9950',
      clientName: 'Manish & Ritu Agarwal',
      clientPhone: '+91 98200 99881',
      clientEmail: 'manish.agarwal@kotak.com',
      projectTitle: 'Lodha Park, Side Tower',
      projectLocation: 'Lower Parel, Mumbai',
      designerName: 'Ananya Roy',
      salesOwner: 'Vikram Malhotra',
      projectManager: 'Amit Desai',
      createdBy: 'Ananya Roy',
      coverImageUrl: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=1200&q=80',
      submissionDate: DateTime.now().subtract(const Duration(hours: 12)),
      discountExpiryDate: DateTime.now().add(const Duration(days: 7)),
      status: QuotationStatus.underReview,
      hideRate: false,
      hideSqft: false,
      showAmount: true,
      discountPercent: 12.0,
      discountType: DiscountType.percentage,
      gstPercent: 18.0,
      amountPaid: 0.0,
      tags: ['Under Review', 'High Value', 'Mumbai'],
      rooms: [
        RoomArea(
          id: 'RM-81',
          roomName: 'Master Bedroom',
          areaType: RoomAreaType.masterBedroom,
          floor: 35,
          lengthFt: 20.0,
          widthFt: 16.0,
          heightFt: 10.5,
          tier: MaterialTier.luxury,
          items: [
            QuotationItem(
              id: 'QI-81',
              itemMasterId: 'ITM-CRP-004',
              itemCode: 'CRP-WDR-OPN-02',
              name: 'Fluted Glass Shutter Dresser & Wardrobe',
              category: ItemCategory.carpentry,
              materialSpecs: 'Aluminium profile rose gold frame, 5mm fluted glass, sensor lights',
              uom: UnitOfMeasurement.sqft,
              quantity: 120.0,
              rate: 2400.0,
              marginPercent: 30.0,
            ),
          ],
        ),
      ],
    ),
  ];

  // ---------------------------------------------------------------------------
  // 6. Dynamic Pricing & WhatsApp Expiry Logs (PRD Section 32)
  // ---------------------------------------------------------------------------
  static final List<UrgencyAlertLog> urgencyAlerts = [
    UrgencyAlertLog(
      id: 'URG-001',
      quotationId: 'QUO-2026-0894',
      quoteNumber: 'QUO-2026-0894',
      clientName: 'Meera & Rohan Deshmukh',
      clientPhone: '+91 98205 91823',
      quotationAmount: 1850000.0,
      discountAmount: 148000.0,
      expiryDate: DateTime.now().add(const Duration(hours: 18)),
      scheduledAlertTime: DateTime.now().subtract(const Duration(hours: 6)),
      isTriggered: true,
      triggeredAt: DateTime.now().subtract(const Duration(hours: 5, minutes: 42)),
      deliveryStatus: ReminderStatus.read,
      salesOwner: 'Kunal Kapoor',
      whatsappMessagePreview:
          '⚠️ Urgent Homio Notice: Hi Rohan & Meera, your ₹1,48,000 seasonal discount on Oberoi Sky City expires in 18 hours. Click here to lock in your price with a ₹25,000 token: homio.in/q/QUO-2026-0894',
    ),
    UrgencyAlertLog(
      id: 'URG-002',
      quotationId: 'QUO-2026-0888',
      quoteNumber: 'QUO-2026-0888',
      clientName: 'Nitin Parekh',
      clientPhone: '+91 98210 66332',
      quotationAmount: 1420000.0,
      discountAmount: 170400.0,
      expiryDate: DateTime.now().add(const Duration(days: 2)),
      scheduledAlertTime: DateTime.now().add(const Duration(days: 1)),
      isTriggered: false,
      deliveryStatus: ReminderStatus.scheduled,
      salesOwner: 'Kunal Kapoor',
      whatsappMessagePreview:
          '✨ Reminder: Nitin, your early-bird waiver of ₹1,70,400 for Hiranandani Estate is reserved until Thursday 6 PM.',
    ),
    UrgencyAlertLog(
      id: 'URG-003',
      quotationId: 'QUO-2026-0870',
      quoteNumber: 'QUO-2026-0870',
      clientName: 'Vikas Saxena',
      clientPhone: '+91 99002 44109',
      quotationAmount: 980000.0,
      discountAmount: 98000.0,
      expiryDate: DateTime.now().subtract(const Duration(days: 2)),
      scheduledAlertTime: DateTime.now().subtract(const Duration(days: 3)),
      isTriggered: true,
      triggeredAt: DateTime.now().subtract(const Duration(days: 3)),
      deliveryStatus: ReminderStatus.lockedIn,
      salesOwner: 'Vikram Malhotra',
      whatsappMessagePreview:
          '⏳ Attention Vikas: Godrej Woodsman quotation discount voucher has expired. Contact Vikram Malhotra to request a revision.',
    ),
  ];

  /// Alias getter for urgency logs
  static List<UrgencyAlertLog> get urgencyLogs => urgencyAlerts;

  // ---------------------------------------------------------------------------
  // 7. B2C Customer Self-Estimator Inquiries (PRD Section 33-40)
  // ---------------------------------------------------------------------------
  static final List<CustomerSelfEstimateLead> selfEstimateLeads = [
    CustomerSelfEstimateLead(
      id: 'SEL-001',
      name: 'Gaurav Agarwal',
      phone: '+91 99102 77812',
      email: 'gaurav.ag@gmail.com',
      propertyType: '3BHK',
      city: 'Bangalore',
      possessionTimeline: 'Within 30 Days',
      carpetAreaSqft: 1450.0,
      tier: MaterialTier.premium,
      designStyle: 'Modern Contemporary',
      selectedRooms: ['Living Room', 'Master Bedroom', 'Modular Kitchen', 'Guest Bedroom'],
      estimatedMinBudget: 1150000.0,
      estimatedMaxBudget: 1420000.0,
      isOtpVerified: true,
      createdAt: DateTime.now().subtract(const Duration(hours: 3)),
      crmLeadStatus: 'SYNCED_TO_SALES',
      assignedTo: 'Vikram Malhotra',
      notes: 'Customer looking for fast execution before house warming next month.',
    ),
    CustomerSelfEstimateLead(
      id: 'SEL-002',
      name: 'Kavita Chawla',
      phone: '+91 98711 00345',
      email: 'kavita.c@deloitte.com',
      propertyType: '2BHK',
      city: 'Mumbai',
      possessionTimeline: 'Ready to Move',
      carpetAreaSqft: 980.0,
      tier: MaterialTier.budget,
      designStyle: 'Scandinavian Minimal',
      selectedRooms: ['Living Room', 'Modular Kitchen', 'Master Bedroom'],
      estimatedMinBudget: 580000.0,
      estimatedMaxBudget: 740000.0,
      isOtpVerified: true,
      createdAt: DateTime.now().subtract(const Duration(hours: 9)),
      crmLeadStatus: 'SITE_VISIT_BOOKED',
      assignedTo: 'Kunal Kapoor',
      notes: 'Site visit scheduled for Saturday 11 AM.',
    ),
    CustomerSelfEstimateLead(
      id: 'SEL-003',
      name: 'Rajnish Oberoi',
      phone: '+91 98110 55998',
      email: 'rajnish@oberoigroup.in',
      propertyType: 'Villa',
      city: 'Gurgaon',
      possessionTimeline: 'Under Construction (3-6 Months)',
      carpetAreaSqft: 3800.0,
      tier: MaterialTier.luxury,
      designStyle: 'Ultra-Luxe Neoclassical',
      selectedRooms: ['Living Room', 'Dining', 'Italian Kitchen', '4 Bedrooms', 'Home Theatre', 'Terrace Deck'],
      estimatedMinBudget: 4200000.0,
      estimatedMaxBudget: 5500000.0,
      isOtpVerified: true,
      createdAt: DateTime.now().subtract(const Duration(days: 1)),
      crmLeadStatus: 'QUOTATION_CREATED',
      assignedTo: 'Ananya Roy',
      notes: 'High net worth client, requested 3D VR walkthrough.',
    ),
  ];
}
