// Homio CRM — Enterprise Communication Mock Data
// Realistic Indian interior design CRM dataset.

import 'communication_models.dart';

class CommunicationMockData {
  // ---------------------------------------------------------------------------
  // KPI Summary
  // ---------------------------------------------------------------------------
  static const CommunicationKpiSummary kpiSummary = CommunicationKpiSummary(
    totalConversationsToday: 142,
    openConversations: 29,
    avgResponseMinutes: 4,
    unreadMessages: 18,
    broadcastsActive: 3,
    templatesApproved: 24,
    dripsActive: 5,
    whatsappDeliveryRate: 0.984,
  );

  // ---------------------------------------------------------------------------
  // WhatsApp Account Info
  // ---------------------------------------------------------------------------
  static final WhatsAppAccount whatsappAccount = WhatsAppAccount(
    businessName: 'Homio Interior Studio Private Limited',
    phoneNumber: '+91 80 4729 8800',
    displayPhoneNumber: '+91 98800 12345',
    wabaId: 'WABA-IND-HOMIO-88219401',
    status: WhatsAppConnectionStatus.connected,
    qualityRating: 'GREEN (High Quality)',
    messagingTier: '100K Messages / 24h',
    webhookStatus: 'Live (Latency 140ms)',
    lastSyncTime: DateTime.now().subtract(const Duration(minutes: 2)),
    dailyLimit: 100000,
    currentUsage: 14280,
  );

  // ---------------------------------------------------------------------------
  // Chatbot / AI Lead Qualifier Configuration
  // ---------------------------------------------------------------------------
  static const ChatbotConfig chatbotConfig = ChatbotConfig(
    botName: 'Homio Concierge AI',
    isEnabled: true,
    welcomeMessage:
        'Namaste! Welcome to Homio Interior Studios. We specialize in turn-key luxury interiors for apartments, villas, and penthouses. How can we assist your dream home today?',
    fallbackMessage:
        'Thank you for your response. Our Senior Design Consultant is reviewing your request and will connect with you within 15 minutes.',
    faqsCount: 18,
    qualificationQuestionsCount: 4,
    escalateToRole: 'Lead Architect / Senior Consultant',
    workingHoursOnly: false,
    activeConversationsCount: 14,
    escalatedTodayCount: 9,
    handoverKeywords: ['speak to human', 'call me', 'designer', 'meeting', 'visit site', 'pricing sheet', 'escalate'],
  );

  // ---------------------------------------------------------------------------
  // Reusable Message Templates
  // ---------------------------------------------------------------------------
  static final List<MessageTemplate> templates = [
    MessageTemplate(
      id: 'tpl_welcome_01',
      name: 'Welcome New Inquirer',
      code: 'homio_welcome_v2',
      category: TemplateCategory.leadWelcome,
      channel: CommunicationChannel.whatsapp,
      language: 'en',
      status: TemplateStatus.approved,
      headerType: 'IMAGE',
      headerMediaUrl: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=800',
      bodyText:
          'Hi {{customer_name}}, thank you for reaching out to Homio Interior Studio! We are thrilled to help craft your {{property_type}} in {{city}}. Would you like to schedule a complimentary 3D concept session with our principal architect?',
      footerText: 'Homio Design Studios • Bengaluru | Mumbai | Hyderabad',
      variables: [
        const TemplateVariable(key: 'customer_name', label: 'Customer Name', defaultValue: 'Client', sourceField: 'lead.name', sampleValue: 'Vikram Malhotra'),
        const TemplateVariable(key: 'property_type', label: 'Property Type', defaultValue: 'apartment', sourceField: 'lead.property_type', sampleValue: '4BHK Villa'),
        const TemplateVariable(key: 'city', label: 'City', defaultValue: 'Bengaluru', sourceField: 'lead.city', sampleValue: 'Whitefield, Bengaluru'),
      ],
      buttons: const [
        TemplateButton(id: 'btn_1', title: 'Schedule 3D Session', type: 'meeting', url: 'https://homio.in/consultation'),
        TemplateButton(id: 'btn_2', title: 'Explore Portfolio', type: 'url', url: 'https://homio.in/lookbook'),
      ],
      usageCount: 1240,
      lastUsedAt: DateTime.now().subtract(const Duration(minutes: 25)),
      updatedAt: DateTime.now().subtract(const Duration(days: 4)),
      createdBy: 'Pooja Hegde (Marketing Lead)',
    ),
    MessageTemplate(
      id: 'tpl_consult_02',
      name: 'Consultation Scheduled Confirmation',
      code: 'homio_consult_confirmed',
      category: TemplateCategory.meetingConfirmation,
      channel: CommunicationChannel.whatsapp,
      language: 'en',
      status: TemplateStatus.approved,
      headerType: 'TEXT',
      headerText: 'Design Consultation Confirmed',
      bodyText:
          'Dear {{customer_name}}, your interior design session is confirmed with {{designer_name}} on {{meeting_datetime}} at our {{studio_location}} Experience Studio. We look forward to reviewing floor plans for {{project_name}}.',
      footerText: 'Please bring floor layout drawings if available.',
      variables: [
        const TemplateVariable(key: 'customer_name', label: 'Customer Name', defaultValue: 'Client', sourceField: 'lead.name', sampleValue: 'Dr. Arishti Kapoor'),
        const TemplateVariable(key: 'designer_name', label: 'Designer Name', defaultValue: 'Lead Designer', sourceField: 'designer.name', sampleValue: 'Siddharth Varma'),
        const TemplateVariable(key: 'meeting_datetime', label: 'Meeting Date Time', defaultValue: 'Tomorrow 4 PM', sourceField: 'meeting.slot', sampleValue: 'Friday, 12th Sep at 4:00 PM'),
        const TemplateVariable(key: 'studio_location', label: 'Studio Branch', defaultValue: 'Indiranagar', sourceField: 'branch.name', sampleValue: 'Indiranagar Flagship Studio'),
        const TemplateVariable(key: 'project_name', label: 'Project Name', defaultValue: 'Residence', sourceField: 'project.name', sampleValue: 'Prestige Lakeside Habitat 3BHK'),
      ],
      buttons: const [
        TemplateButton(id: 'btn_loc', title: 'Get Studio Location', type: 'url', url: 'https://maps.google.com/?q=homio+indiranagar'),
        TemplateButton(id: 'btn_resched', title: 'Reschedule Session', type: 'quickReply', payload: 'RESCHEDULE_REQ'),
      ],
      usageCount: 890,
      lastUsedAt: DateTime.now().subtract(const Duration(hours: 1)),
      updatedAt: DateTime.now().subtract(const Duration(days: 12)),
      createdBy: 'Karan Mehra (Studio Operations)',
    ),
    MessageTemplate(
      id: 'tpl_quote_03',
      name: 'Detailed Quotation Ready',
      code: 'homio_quote_ready',
      category: TemplateCategory.quotationShared,
      channel: CommunicationChannel.whatsapp,
      language: 'en',
      status: TemplateStatus.approved,
      headerType: 'DOCUMENT',
      headerText: 'Homio Detailed Quotation',
      bodyText:
          'Hello {{customer_name}}, the itemized project quotation for {{project_name}} (BOQ Ref: {{quote_ref}}) is ready. Total estimated value is {{quote_amount}} with 45-day on-time handover warranty. Review specs and approve online.',
      footerText: 'Valid for 15 days • Includes 10-year warranty on modular plywood',
      variables: [
        const TemplateVariable(key: 'customer_name', label: 'Customer Name', defaultValue: 'Client', sourceField: 'customer.name', sampleValue: 'Sneha & Rajesh Reddy'),
        const TemplateVariable(key: 'project_name', label: 'Project Name', defaultValue: 'Home', sourceField: 'project.name', sampleValue: 'Sobha Dream Acres 3BHK'),
        const TemplateVariable(key: 'quote_ref', label: 'Quote Number', defaultValue: 'HQ-000', sourceField: 'quote.number', sampleValue: 'HQ-2026-8819'),
        const TemplateVariable(key: 'quote_amount', label: 'Quote Amount', defaultValue: '₹0', sourceField: 'quote.total', sampleValue: '₹34,50,000/-'),
      ],
      buttons: const [
        TemplateButton(id: 'btn_q1', title: 'View & Sign Estimate', type: 'url', url: 'https://homio.in/q/8819'),
        TemplateButton(id: 'btn_q2', title: 'Request Modification', type: 'quickReply', payload: 'REVISE_QUOTE'),
      ],
      usageCount: 654,
      lastUsedAt: DateTime.now().subtract(const Duration(hours: 3)),
      updatedAt: DateTime.now().subtract(const Duration(days: 20)),
      createdBy: 'Pooja Hegde',
    ),
    MessageTemplate(
      id: 'tpl_milestone_04',
      name: 'Site Milestone Payment Due',
      code: 'homio_payment_milestone',
      category: TemplateCategory.paymentReminder,
      channel: CommunicationChannel.whatsapp,
      language: 'en',
      status: TemplateStatus.approved,
      headerType: 'TEXT',
      headerText: 'Project Milestone Reached',
      bodyText:
          'Dear {{customer_name}}, we are delighted to share that {{milestone_name}} for your residence at {{project_name}} has successfully passed quality audit! Milestone invoice #{{invoice_number}} for {{due_amount}} is generated. Due date: {{due_date}}.',
      footerText: 'Homio Secure Payment Gateway powered by Razorpay',
      variables: [
        const TemplateVariable(key: 'customer_name', label: 'Customer Name', defaultValue: 'Client', sourceField: 'customer.name', sampleValue: 'Ananya Deshmukh'),
        const TemplateVariable(key: 'milestone_name', label: 'Milestone Name', defaultValue: 'Carpentry Milestone', sourceField: 'milestone.name', sampleValue: 'Carcass Installation & Electrical Roughing'),
        const TemplateVariable(key: 'project_name', label: 'Project Name', defaultValue: 'Project', sourceField: 'project.name', sampleValue: 'Phoenix One Bangalore West 4BHK'),
        const TemplateVariable(key: 'invoice_number', label: 'Invoice Number', defaultValue: 'INV-000', sourceField: 'invoice.number', sampleValue: 'INV-2026-0412'),
        const TemplateVariable(key: 'due_amount', label: 'Due Amount', defaultValue: '₹0', sourceField: 'invoice.balance', sampleValue: '₹4,85,000/-'),
        const TemplateVariable(key: 'due_date', label: 'Due Date', defaultValue: 'Upcoming', sourceField: 'invoice.dueDate', sampleValue: '15th Sept 2026'),
      ],
      buttons: const [
        TemplateButton(id: 'btn_pay', title: 'Pay via UPI / NetBanking', type: 'payment', url: 'https://homio.in/pay/0412'),
        TemplateButton(id: 'btn_site_audit', title: 'Inspect Site QC Photos', type: 'url', url: 'https://homio.in/portal/site-audit'),
      ],
      usageCount: 420,
      lastUsedAt: DateTime.now().subtract(const Duration(hours: 5)),
      updatedAt: DateTime.now().subtract(const Duration(days: 35)),
      createdBy: 'FinOps Team',
    ),
    MessageTemplate(
      id: 'tpl_site_progress_05',
      name: 'Weekly Live Site Progress Feed',
      code: 'homio_site_progress_feed',
      category: TemplateCategory.siteProgressUpdate,
      channel: CommunicationChannel.whatsapp,
      language: 'en',
      status: TemplateStatus.approved,
      headerType: 'IMAGE',
      headerMediaUrl: 'https://images.unsplash.com/photo-1541888946425-d0fbb186f5f7?w=800',
      bodyText:
          'Hello {{customer_name}}, here is your Weekly Site Progress Digest for {{project_name}}. Current overall progress is at {{progress_pct}}%. Key updates: {{summary_notes}}. Tap below to view high-res 360° site photos.',
      footerText: 'Homio Field QA & Engineering Desk',
      variables: [
        const TemplateVariable(key: 'customer_name', label: 'Customer Name', defaultValue: 'Client', sourceField: 'customer.name', sampleValue: 'Amitav Sen'),
        const TemplateVariable(key: 'project_name', label: 'Project Name', defaultValue: 'Residence', sourceField: 'project.name', sampleValue: 'Rustomjee Crown Tower A'),
        const TemplateVariable(key: 'progress_pct', label: 'Progress Percentage', defaultValue: '50%', sourceField: 'project.progress', sampleValue: '72%'),
        const TemplateVariable(key: 'summary_notes', label: 'Summary', defaultValue: 'Site on track', sourceField: 'project.notes', sampleValue: 'Kitchen quartz countertop installed, primer coat completed in master suite.'),
      ],
      buttons: const [
        TemplateButton(id: 'btn_cam', title: 'View 360° Site Stream', type: 'url', url: 'https://homio.in/site/live-feed'),
      ],
      usageCount: 780,
      lastUsedAt: DateTime.now().subtract(const Duration(hours: 8)),
      updatedAt: DateTime.now().subtract(const Duration(days: 15)),
      createdBy: 'Engineering Operations',
    ),
    MessageTemplate(
      id: 'tpl_handover_06',
      name: 'Post Handover Care & Warranty Check',
      code: 'homio_handover_warranty',
      category: TemplateCategory.afterSalesService,
      channel: CommunicationChannel.whatsapp,
      language: 'en',
      status: TemplateStatus.approved,
      headerType: 'TEXT',
      headerText: 'Homio 6-Month Happiness Check',
      bodyText:
          'Warm greetings {{customer_name}}! It has been 6 months since you moved into {{project_name}}. As part of our lifetime commitment, we have scheduled our complimentary hardware lubrication, hinge realignment & silicone touch-up visit on {{scheduled_date}}.',
      footerText: 'Homio Care Concierge • Helpline 1800-891-HOMIO',
      variables: [
        const TemplateVariable(key: 'customer_name', label: 'Customer Name', defaultValue: 'Client', sourceField: 'customer.name', sampleValue: 'Neha & Varun Kapoor'),
        const TemplateVariable(key: 'project_name', label: 'Project Name', defaultValue: 'Residence', sourceField: 'project.name', sampleValue: 'Embassy Lake Terraces'),
        const TemplateVariable(key: 'scheduled_date', label: 'Date', defaultValue: 'Saturday', sourceField: 'service.date', sampleValue: 'Saturday, 20th Sept 11 AM'),
      ],
      buttons: const [
        TemplateButton(id: 'btn_svc_ok', title: 'Confirm Service Slot', type: 'quickReply', payload: 'CONFIRM_SVC'),
        TemplateButton(id: 'btn_svc_req', title: 'Report Snag / Ticket', type: 'url', url: 'https://homio.in/care/ticket'),
      ],
      usageCount: 310,
      lastUsedAt: DateTime.now().subtract(const Duration(days: 1)),
      updatedAt: DateTime.now().subtract(const Duration(days: 45)),
      createdBy: 'Customer Delight Head',
    ),
    MessageTemplate(
      id: 'tpl_festive_07',
      name: 'Diwali Festive Decor Wish & Gift',
      code: 'homio_diwali_gift_2026',
      category: TemplateCategory.festiveGreeting,
      channel: CommunicationChannel.whatsapp,
      language: 'en',
      status: TemplateStatus.pendingApproval,
      headerType: 'IMAGE',
      headerMediaUrl: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800',
      bodyText:
          'Wishing {{customer_name}} and your lovely family a luminous and joyous Diwali! As our token of celebration for {{project_name}}, please collect your complimentary handcrafted brass ambient pendant lamp from our studio.',
      footerText: 'May your home sparkle with joy, prosperity & warmth.',
      variables: [
        const TemplateVariable(key: 'customer_name', label: 'Customer Name', defaultValue: 'Valued Client', sourceField: 'customer.name', sampleValue: 'Rohit Kulkarni'),
        const TemplateVariable(key: 'project_name', label: 'Home Name', defaultValue: 'your abode', sourceField: 'project.name', sampleValue: 'your home at Salarpuria Sattva'),
      ],
      buttons: const [
        TemplateButton(id: 'btn_claim', title: 'Claim Festive Gift', type: 'url', url: 'https://homio.in/festive-claim'),
      ],
      usageCount: 0,
      lastUsedAt: DateTime.now().subtract(const Duration(days: 60)),
      updatedAt: DateTime.now().subtract(const Duration(days: 2)),
      createdBy: 'Marketing Desk',
    ),
  ];

  // ---------------------------------------------------------------------------
  // 12 Realistic Conversations across all CRM stages
  // ---------------------------------------------------------------------------
  static final List<Conversation> conversations = [
    // 1. Vikram Malhotra - Active Project (High Priority, WhatsApp)
    Conversation(
      id: 'conv_01',
      customerContext: CustomerContext(
        customerId: 'CUST-8810',
        customerName: 'Vikram Malhotra',
        customerPhone: '+91 98450 91823',
        customerEmail: 'vikram.malhotra@techcorp.in',
        city: 'Bengaluru',
        crmStage: CustomerCrmStage.activeProject,
        leadId: 'LEAD-4412',
        leadSource: 'Architect Referral',
        budgetRange: '₹45L - ₹60L',
        propertyType: '4BHK Penthouse (3400 sq.ft)',
        assignedEmployeeName: 'Priya Sharma (Senior Architect)',
        assignedEmployeeId: 'EMP-014',
        assignedDesignerName: 'Nitin Rao (3D Visualizer)',
        projectId: 'PRJ-2026-08',
        projectName: 'Total Environment Windmills - Unit 402',
        projectStatus: 'Modular Factory Production',
        contractValue: 5250000.0,
        totalInvoiced: 2625000.0,
        totalPaid: 2625000.0,
        balanceDue: 2625000.0,
        nextMeetingDate: DateTime.now().add(const Duration(days: 2)),
        nextMeetingType: 'Stone & Veneer Sample Approval',
        tags: ['Penthouse', 'Italian Veneer', 'Smart Home', 'High Value'],
        recentMilestones: ['Civil changes signed', 'Factory cutlist approved', 'Carcass underway'],
      ),
      channel: CommunicationChannel.whatsapp,
      status: ConversationStatus.open,
      priority: ConversationPriority.high,
      assignedEmployeeName: 'Priya Sharma',
      assignedEmployeeId: 'EMP-014',
      tags: ['Penthouse', 'Factory Review'],
      isStarred: true,
      unreadCount: 2,
      lastMessage: 'Can we switch the master wardrobe fluted glass color from bronze to charcoal grey?',
      lastMessageTime: DateTime.now().subtract(const Duration(minutes: 8)),
      createdAt: DateTime.now().subtract(const Duration(days: 42)),
      messages: [
        ChatMessage(
          id: 'msg_01_01',
          conversationId: 'conv_01',
          direction: MessageDirection.incoming,
          senderName: 'Vikram Malhotra',
          senderRole: 'Client',
          content: 'Hi Priya, hope you are doing well. Just reviewing the render set you shared on Tuesday.',
          timestamp: DateTime.now().subtract(const Duration(hours: 3)),
          status: MessageStatus.read,
        ),
        ChatMessage(
          id: 'msg_01_02',
          conversationId: 'conv_01',
          direction: MessageDirection.outgoing,
          senderName: 'Priya Sharma',
          senderRole: 'Senior Architect',
          content: 'Good afternoon Mr. Malhotra! Yes, the factory team in Peenya has started cutting the Austrian Egger boards for the master walk-in.',
          timestamp: DateTime.now().subtract(const Duration(hours: 2, minutes: 40)),
          status: MessageStatus.read,
        ),
        ChatMessage(
          id: 'msg_01_03',
          conversationId: 'conv_01',
          direction: MessageDirection.internal,
          senderName: 'Priya Sharma',
          senderRole: 'Senior Architect',
          content: 'Internal Note: Client is very specific about acoustic sealing on the master sliding partitions. Remind factory QC head to double check Hettich soft-close profile.',
          timestamp: DateTime.now().subtract(const Duration(hours: 2, minutes: 15)),
          isInternalNote: true,
        ),
        ChatMessage(
          id: 'msg_01_04',
          conversationId: 'conv_01',
          direction: MessageDirection.incoming,
          senderName: 'Vikram Malhotra',
          senderRole: 'Client',
          content: 'Can we switch the master wardrobe fluted glass color from bronze to charcoal grey? Attaching a photo of the tile sample we picked for the adjoining bath.',
          timestamp: DateTime.now().subtract(const Duration(minutes: 8)),
          status: MessageStatus.delivered,
          attachments: const [
            MessageAttachment(
              id: 'att_01_1',
              fileName: 'charcoal_fluted_sample.jpg',
              fileType: 'image/jpeg',
              fileSize: 2450000,
              url: 'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=800',
            )
          ],
        ),
      ],
    ),

    // 2. Sneha & Rajesh Reddy - Meeting Scheduled (Urgent Priority, WhatsApp)
    Conversation(
      id: 'conv_02',
      customerContext: CustomerContext(
        customerId: 'CUST-8811',
        customerName: 'Sneha & Rajesh Reddy',
        customerPhone: '+91 97410 44219',
        customerEmail: 'rajesh.reddy@infoventure.com',
        city: 'Bengaluru',
        crmStage: CustomerCrmStage.meetingScheduled,
        leadId: 'LEAD-4490',
        leadSource: 'Instagram Ad Campaign',
        budgetRange: '₹30L - ₹40L',
        propertyType: '3BHK Luxury Apartment (1950 sq.ft)',
        assignedEmployeeName: 'Karan Mehra',
        assignedEmployeeId: 'EMP-021',
        assignedDesignerName: 'Shalini Nair',
        projectId: 'PRJ-2026-19',
        projectName: 'Sobha Neopolis Greek Theme 3BHK',
        projectStatus: 'Design & Estimations Stage',
        contractValue: 3500000.0,
        totalInvoiced: 0.0,
        totalPaid: 0.0,
        balanceDue: 3500000.0,
        nextMeetingDate: DateTime.now().add(const Duration(hours: 26)),
        nextMeetingType: '3D VR Walkthrough & Material Touch Panel',
        tags: ['Sobha Client', 'Greek Aesthetic', 'Fast Decision'],
        recentMilestones: ['Floor plan received', 'Preliminary moodboard prepared'],
      ),
      channel: CommunicationChannel.whatsapp,
      status: ConversationStatus.open,
      priority: ConversationPriority.urgent,
      assignedEmployeeName: 'Karan Mehra',
      assignedEmployeeId: 'EMP-021',
      tags: ['Greek Theme', 'Meeting Tomorrow'],
      isStarred: true,
      unreadCount: 1,
      lastMessage: 'Will the 3D walkthrough include the arched corridor with concealed cove lighting?',
      lastMessageTime: DateTime.now().subtract(const Duration(minutes: 24)),
      createdAt: DateTime.now().subtract(const Duration(days: 5)),
      messages: [
        ChatMessage(
          id: 'msg_02_01',
          conversationId: 'conv_02',
          direction: MessageDirection.outgoing,
          senderName: 'Homio Bot',
          senderRole: 'Concierge Bot',
          content: 'Namaste Rajesh & Sneha! Your design session at our Whitefield Studio is confirmed for tomorrow at 3:30 PM.',
          timestamp: DateTime.now().subtract(const Duration(hours: 5)),
          status: MessageStatus.read,
          templateName: 'homio_consult_confirmed',
        ),
        ChatMessage(
          id: 'msg_02_02',
          conversationId: 'conv_02',
          direction: MessageDirection.incoming,
          senderName: 'Sneha Reddy',
          senderRole: 'Client',
          content: 'Will the 3D walkthrough include the arched corridor with concealed cove lighting?',
          timestamp: DateTime.now().subtract(const Duration(minutes: 24)),
          status: MessageStatus.delivered,
        ),
      ],
    ),

    // 3. Ananya Deshmukh - Payment Milestone (Normal Priority, WhatsApp)
    Conversation(
      id: 'conv_03',
      customerContext: CustomerContext(
        customerId: 'CUST-8812',
        customerName: 'Ananya Deshmukh',
        customerPhone: '+91 99201 55670',
        customerEmail: 'ananya.deshmukh@investbank.com',
        city: 'Mumbai',
        crmStage: CustomerCrmStage.payment,
        leadId: 'LEAD-3982',
        leadSource: 'Walk-in Studio',
        budgetRange: '₹75L - ₹90L',
        propertyType: 'Sea-facing Duplex (4100 sq.ft)',
        assignedEmployeeName: 'Rohan Joshi',
        assignedEmployeeId: 'EMP-009',
        assignedDesignerName: 'Aarohi Sen',
        projectId: 'PRJ-2026-03',
        projectName: 'Piramal Mahalaxmi Tower 2',
        projectStatus: 'Civil Demolition & Wall Framing Completed',
        contractValue: 8400000.0,
        totalInvoiced: 4200000.0,
        totalPaid: 3360000.0,
        balanceDue: 840000.0,
        nextMeetingDate: DateTime.now().add(const Duration(days: 4)),
        nextMeetingType: 'Electrical Conduit Handover',
        tags: ['Sea Facing', 'Italian Marble', 'Duplex'],
        recentMilestones: ['Demolition completed', 'Plumbing pressure test passed'],
      ),
      channel: CommunicationChannel.whatsapp,
      status: ConversationStatus.pending,
      priority: ConversationPriority.normal,
      assignedEmployeeName: 'Rohan Joshi',
      assignedEmployeeId: 'EMP-009',
      tags: ['Milestone Due', 'Duplex'],
      isStarred: false,
      unreadCount: 0,
      lastMessage: 'Payment of ₹8.4L initiated via NEFT. UTR reference: HDFC00291048201. Please confirm receipt.',
      lastMessageTime: DateTime.now().subtract(const Duration(hours: 2)),
      createdAt: DateTime.now().subtract(const Duration(days: 60)),
      messages: [
        ChatMessage(
          id: 'msg_03_01',
          conversationId: 'conv_03',
          direction: MessageDirection.outgoing,
          senderName: 'Rohan Joshi',
          senderRole: 'Project Manager',
          content: 'Hello Ananya, milestone invoice INV-2026-0412 for the electrical & plumbing phase has been generated.',
          timestamp: DateTime.now().subtract(const Duration(days: 1)),
          status: MessageStatus.read,
        ),
        ChatMessage(
          id: 'msg_03_02',
          conversationId: 'conv_03',
          direction: MessageDirection.incoming,
          senderName: 'Ananya Deshmukh',
          senderRole: 'Client',
          content: 'Payment of ₹8.4L initiated via NEFT. UTR reference: HDFC00291048201. Please confirm receipt.',
          timestamp: DateTime.now().subtract(const Duration(hours: 2)),
          status: MessageStatus.read,
        ),
      ],
    ),

    // 4. Dr. Arishti Kapoor - Execution Phase (Normal Priority, WhatsApp)
    Conversation(
      id: 'conv_04',
      customerContext: CustomerContext(
        customerId: 'CUST-8813',
        customerName: 'Dr. Arishti Kapoor',
        customerPhone: '+91 98112 39012',
        customerEmail: 'dr.arishti.kapoor@medresearch.org',
        city: 'Delhi NCR',
        crmStage: CustomerCrmStage.execution,
        leadId: 'LEAD-4102',
        leadSource: 'Website Inquiry',
        budgetRange: '₹35L - ₹45L',
        propertyType: '3BHK + Study (2200 sq.ft)',
        assignedEmployeeName: 'Siddharth Varma',
        assignedEmployeeId: 'EMP-018',
        assignedDesignerName: 'Divya Rastogi',
        projectId: 'PRJ-2026-11',
        projectName: 'DLF The Camellias - Golf Course Road',
        projectStatus: 'POP False Ceiling & CNC Jali Work',
        contractValue: 4100000.0,
        totalInvoiced: 2460000.0,
        totalPaid: 2460000.0,
        balanceDue: 1640000.0,
        nextMeetingDate: DateTime.now().add(const Duration(days: 7)),
        nextMeetingType: 'Polishing & Primer Stage Inspection',
        tags: ['Clinic Space', 'Acoustics', 'CNC Partition'],
        recentMilestones: ['False ceiling grid installed', 'Cove profiles wired'],
      ),
      channel: CommunicationChannel.whatsapp,
      status: ConversationStatus.open,
      priority: ConversationPriority.normal,
      assignedEmployeeName: 'Siddharth Varma',
      assignedEmployeeId: 'EMP-018',
      tags: ['Ceiling Work', 'Medical Clinic Setup'],
      isStarred: false,
      unreadCount: 3,
      lastMessage: 'The magnetic track light channels look stunning! When do the spot fixtures arrive?',
      lastMessageTime: DateTime.now().subtract(const Duration(minutes: 50)),
      createdAt: DateTime.now().subtract(const Duration(days: 30)),
      messages: [
        ChatMessage(
          id: 'msg_04_01',
          conversationId: 'conv_04',
          direction: MessageDirection.outgoing,
          senderName: 'Siddharth Varma',
          senderRole: 'Site Operations',
          content: 'Good day Dr. Kapoor! Sharing the high-res site photos from this morning. Gyproc false ceiling framing in dining hall is 100% complete.',
          timestamp: DateTime.now().subtract(const Duration(hours: 3)),
          status: MessageStatus.read,
          attachments: const [
            MessageAttachment(
              id: 'att_04_1',
              fileName: 'dining_ceiling_frame.jpg',
              fileType: 'image/jpeg',
              fileSize: 3100000,
              url: 'https://images.unsplash.com/photo-1541888946425-d0fbb186f5f7?w=800',
            ),
          ],
        ),
        ChatMessage(
          id: 'msg_04_02',
          conversationId: 'conv_04',
          direction: MessageDirection.incoming,
          senderName: 'Dr. Arishti Kapoor',
          senderRole: 'Client',
          content: 'The magnetic track light channels look stunning! When do the spot fixtures arrive?',
          timestamp: DateTime.now().subtract(const Duration(minutes: 50)),
          status: MessageStatus.delivered,
        ),
      ],
    ),

    // 5. Rohan Mehta - New Lead (SMS, High Priority)
    Conversation(
      id: 'conv_05',
      customerContext: CustomerContext(
        customerId: 'CUST-8814',
        customerName: 'Rohan Mehta',
        customerPhone: '+91 98200 81765',
        customerEmail: 'rohan.mehta@fintechventures.co',
        city: 'Mumbai',
        crmStage: CustomerCrmStage.newLead,
        leadId: 'LEAD-4510',
        leadSource: 'Google Search Ads',
        budgetRange: '₹50L - ₹70L',
        propertyType: '4BHK Oberoi Realty (2800 sq.ft)',
        assignedEmployeeName: 'Aarti Kulkarni',
        assignedEmployeeId: 'EMP-027',
        projectId: null,
        projectName: 'Oberoi Sky City Borivali',
        projectStatus: 'Inquiry Qualification',
        contractValue: 0.0,
        totalInvoiced: 0.0,
        totalPaid: 0.0,
        balanceDue: 0.0,
        tags: ['New Lead', 'Oberoi Project', 'High Budget'],
        recentMilestones: ['Lead created from Google Lead Form'],
      ),
      channel: CommunicationChannel.sms,
      status: ConversationStatus.open,
      priority: ConversationPriority.high,
      assignedEmployeeName: 'Aarti Kulkarni',
      assignedEmployeeId: 'EMP-027',
      tags: ['SMS Lead', 'Needs Immediate Call'],
      isStarred: false,
      unreadCount: 1,
      lastMessage: 'Please call me after 6 PM today to discuss full interior design quotation for 4BHK.',
      lastMessageTime: DateTime.now().subtract(const Duration(hours: 1, minutes: 12)),
      createdAt: DateTime.now().subtract(const Duration(hours: 4)),
      messages: [
        ChatMessage(
          id: 'msg_05_01',
          conversationId: 'conv_05',
          direction: MessageDirection.outgoing,
          senderName: 'Homio SMS Gateway',
          senderRole: 'System',
          content: 'Dear Rohan Mehta, thank you for your inquiry with Homio Interior Studios Mumbai. Our designer Aarti will assist you.',
          timestamp: DateTime.now().subtract(const Duration(hours: 3)),
          status: MessageStatus.delivered,
        ),
        ChatMessage(
          id: 'msg_05_02',
          conversationId: 'conv_05',
          direction: MessageDirection.incoming,
          senderName: 'Rohan Mehta',
          senderRole: 'Client',
          content: 'Please call me after 6 PM today to discuss full interior design quotation for 4BHK.',
          timestamp: DateTime.now().subtract(const Duration(hours: 1, minutes: 12)),
          status: MessageStatus.delivered,
        ),
      ],
    ),

    // 6. Amitav & Priya Sen - After-Sales Care (Resolved, WhatsApp)
    Conversation(
      id: 'conv_06',
      customerContext: CustomerContext(
        customerId: 'CUST-8815',
        customerName: 'Amitav & Priya Sen',
        customerPhone: '+91 98300 23419',
        customerEmail: 'amitav.sen@globaltelecom.com',
        city: 'Kolkata / Bengaluru',
        crmStage: CustomerCrmStage.afterSales,
        leadId: 'LEAD-2910',
        leadSource: 'Friend Referral',
        budgetRange: '₹28L - ₹35L',
        propertyType: '3BHK Premium Flat (1850 sq.ft)',
        assignedEmployeeName: 'Manoj Kumar',
        assignedEmployeeId: 'EMP-031',
        projectId: 'PRJ-2025-44',
        projectName: 'Godrej Woodsman Estate 3BHK',
        projectStatus: 'Handed Over (Warranty Active)',
        contractValue: 3150000.0,
        totalInvoiced: 3150000.0,
        totalPaid: 3150000.0,
        balanceDue: 0.0,
        tags: ['Handed Over', 'Warranty Covered', 'Happy Client'],
        recentMilestones: ['Handover completed Nov 2025', '6-month inspection done'],
      ),
      channel: CommunicationChannel.whatsapp,
      status: ConversationStatus.resolved,
      priority: ConversationPriority.low,
      assignedEmployeeName: 'Manoj Kumar',
      assignedEmployeeId: 'EMP-031',
      tags: ['Snag Free', 'Google Review 5*'],
      isStarred: false,
      unreadCount: 0,
      lastMessage: 'The carpentry technician attended the soft-close hydraulic hinge calibration yesterday. Works like a charm now! Thank you.',
      lastMessageTime: DateTime.now().subtract(const Duration(days: 1)),
      createdAt: DateTime.now().subtract(const Duration(days: 280)),
      messages: [
        ChatMessage(
          id: 'msg_06_01',
          conversationId: 'conv_06',
          direction: MessageDirection.outgoing,
          senderName: 'Manoj Kumar',
          senderRole: 'After-Sales Care',
          content: 'Hello Mr. Sen, checking in to see if our technician Raju visited yesterday to adjust the crockery unit hinges?',
          timestamp: DateTime.now().subtract(const Duration(days: 1, hours: 3)),
          status: MessageStatus.read,
        ),
        ChatMessage(
          id: 'msg_06_02',
          conversationId: 'conv_06',
          direction: MessageDirection.incoming,
          senderName: 'Amitav Sen',
          senderRole: 'Client',
          content: 'The carpentry technician attended the soft-close hydraulic hinge calibration yesterday. Works like a charm now! Thank you.',
          timestamp: DateTime.now().subtract(const Duration(days: 1)),
          status: MessageStatus.read,
        ),
      ],
    ),

    // 7. Neha & Varun Kapoor - Booked / Signed (Normal Priority, WhatsApp)
    Conversation(
      id: 'conv_07',
      customerContext: CustomerContext(
        customerId: 'CUST-8816',
        customerName: 'Neha & Varun Kapoor',
        customerPhone: '+91 99100 88231',
        customerEmail: 'varun.kapoor@startupedge.io',
        city: 'Gurugram',
        crmStage: CustomerCrmStage.booked,
        leadId: 'LEAD-4389',
        leadSource: 'Partner Architect',
        budgetRange: '₹40L - ₹50L',
        propertyType: '4BHK High Rise (2600 sq.ft)',
        assignedEmployeeName: 'Pooja Hegde',
        assignedEmployeeId: 'EMP-005',
        projectId: 'PRJ-2026-27',
        projectName: 'M3M Golfestate 4BHK Suite',
        projectStatus: 'Design Signoff & 10% Booking Token Received',
        contractValue: 4600000.0,
        totalInvoiced: 460000.0,
        totalPaid: 460000.0,
        balanceDue: 4140000.0,
        tags: ['Booked', 'Golfestate', 'Luxury Modern'],
        recentMilestones: ['Booking token paid', 'Initial site measurement completed'],
      ),
      channel: CommunicationChannel.whatsapp,
      status: ConversationStatus.open,
      priority: ConversationPriority.normal,
      assignedEmployeeName: 'Pooja Hegde',
      assignedEmployeeId: 'EMP-005',
      tags: ['Token Paid', 'M3M'],
      isStarred: true,
      unreadCount: 0,
      lastMessage: 'Sharing the signed design brief document and our chosen palette for the bar lounge.',
      lastMessageTime: DateTime.now().subtract(const Duration(hours: 4)),
      createdAt: DateTime.now().subtract(const Duration(days: 14)),
      messages: [
        ChatMessage(
          id: 'msg_07_01',
          conversationId: 'conv_07',
          direction: MessageDirection.incoming,
          senderName: 'Varun Kapoor',
          senderRole: 'Client',
          content: 'Sharing the signed design brief document and our chosen palette for the bar lounge.',
          timestamp: DateTime.now().subtract(const Duration(hours: 4)),
          status: MessageStatus.read,
          attachments: const [
            MessageAttachment(
              id: 'att_07_1',
              fileName: 'Homio_Signed_Brief_M3M.pdf',
              fileType: 'application/pdf',
              fileSize: 4200000,
              url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
            )
          ],
        ),
      ],
    ),

    // 8. Gaurav Singhania - Qualified Lead (Email, Normal Priority)
    Conversation(
      id: 'conv_08',
      customerContext: CustomerContext(
        customerId: 'CUST-8817',
        customerName: 'Gaurav Singhania',
        customerPhone: '+91 98290 11980',
        customerEmail: 'gaurav@singhaniagroup.in',
        city: 'Jaipur / Delhi',
        crmStage: CustomerCrmStage.qualified,
        leadId: 'LEAD-4450',
        leadSource: 'Lookbook Download',
        budgetRange: '₹80L - ₹1.2Cr',
        propertyType: 'Independent Luxury Bungalow (6500 sq.ft)',
        assignedEmployeeName: 'Rohan Joshi',
        assignedEmployeeId: 'EMP-009',
        projectId: null,
        projectName: 'Civil Lines Royal Villa',
        projectStatus: 'Pre-Proposal Evaluation',
        contractValue: 0.0,
        totalInvoiced: 0.0,
        totalPaid: 0.0,
        balanceDue: 0.0,
        tags: ['Ultra Luxury', 'Heritage Modern', 'Bungalow'],
        recentMilestones: ['Lead qualified by Concierge Bot'],
      ),
      channel: CommunicationChannel.email,
      status: ConversationStatus.pending,
      priority: ConversationPriority.normal,
      assignedEmployeeName: 'Rohan Joshi',
      assignedEmployeeId: 'EMP-009',
      tags: ['Email Thread', 'High Net Worth'],
      isStarred: false,
      unreadCount: 0,
      lastMessage: 'Requested itemized quote breakdown for imported Italian marble flooring vs engineered herringbone oak wood.',
      lastMessageTime: DateTime.now().subtract(const Duration(hours: 6)),
      createdAt: DateTime.now().subtract(const Duration(days: 8)),
      messages: [
        ChatMessage(
          id: 'msg_08_01',
          conversationId: 'conv_08',
          direction: MessageDirection.incoming,
          senderName: 'Gaurav Singhania',
          senderRole: 'Client',
          content: 'Requested itemized quote breakdown for imported Italian marble flooring vs engineered herringbone oak wood.',
          timestamp: DateTime.now().subtract(const Duration(hours: 6)),
          status: MessageStatus.read,
        ),
      ],
    ),

    // 9. Tanvi Parekh - Meeting Completed (WhatsApp, Normal Priority)
    Conversation(
      id: 'conv_09',
      customerContext: CustomerContext(
        customerId: 'CUST-8818',
        customerName: 'Tanvi Parekh',
        customerPhone: '+91 98211 44556',
        customerEmail: 'tanvi.parekh@designcurators.com',
        city: 'Mumbai',
        crmStage: CustomerCrmStage.meetingCompleted,
        leadId: 'LEAD-4360',
        leadSource: 'Houzz India',
        budgetRange: '₹35L - ₹45L',
        propertyType: '3BHK Art Deco Flat (1700 sq.ft)',
        assignedEmployeeName: 'Shalini Nair',
        assignedEmployeeId: 'EMP-015',
        projectId: 'PRJ-2026-31',
        projectName: 'Bandra Reclamation Art Deco',
        projectStatus: 'Quotation Drafting',
        contractValue: 3800000.0,
        totalInvoiced: 0.0,
        totalPaid: 0.0,
        balanceDue: 3800000.0,
        tags: ['Art Deco', 'Bandra', 'Design Enthusiast'],
        recentMilestones: ['Studio session finished yesterday', 'Moodboard approved'],
      ),
      channel: CommunicationChannel.whatsapp,
      status: ConversationStatus.open,
      priority: ConversationPriority.normal,
      assignedEmployeeName: 'Shalini Nair',
      assignedEmployeeId: 'EMP-015',
      tags: ['Art Deco', 'Waiting for Quote'],
      isStarred: false,
      unreadCount: 1,
      lastMessage: 'Loved the fluted brass inlays in yesterday’s samples! Can you include that in the entrance foyer quote?',
      lastMessageTime: DateTime.now().subtract(const Duration(hours: 7)),
      createdAt: DateTime.now().subtract(const Duration(days: 10)),
      messages: [
        ChatMessage(
          id: 'msg_09_01',
          conversationId: 'conv_09',
          direction: MessageDirection.incoming,
          senderName: 'Tanvi Parekh',
          senderRole: 'Client',
          content: 'Loved the fluted brass inlays in yesterday’s samples! Can you include that in the entrance foyer quote?',
          timestamp: DateTime.now().subtract(const Duration(hours: 7)),
          status: MessageStatus.delivered,
        ),
      ],
    ),

    // 10. Harish & Shanti Iyer - Active Project (WhatsApp, Low Priority)
    Conversation(
      id: 'conv_10',
      customerContext: CustomerContext(
        customerId: 'CUST-8819',
        customerName: 'Harish & Shanti Iyer',
        customerPhone: '+91 94440 33812',
        customerEmail: 'harish.iyer@chennaitech.com',
        city: 'Chennai',
        crmStage: CustomerCrmStage.activeProject,
        leadId: 'LEAD-3820',
        leadSource: 'Exhibition Stall',
        budgetRange: '₹22L - ₹28L',
        propertyType: '3BHK Villa (2100 sq.ft)',
        assignedEmployeeName: 'Karan Mehra',
        assignedEmployeeId: 'EMP-021',
        projectId: 'PRJ-2026-15',
        projectName: 'Adyar Green Villa',
        projectStatus: 'Modular Factory Dispatch',
        contractValue: 2450000.0,
        totalInvoiced: 1225000.0,
        totalPaid: 1225000.0,
        balanceDue: 1225000.0,
        tags: ['Chennai Villa', 'Teak Accents'],
        recentMilestones: ['Factory assembly complete', 'Dispatch truck booked'],
      ),
      channel: CommunicationChannel.whatsapp,
      status: ConversationStatus.resolved,
      priority: ConversationPriority.low,
      assignedEmployeeName: 'Karan Mehra',
      assignedEmployeeId: 'EMP-021',
      tags: ['Factory Dispatch', 'Chennai'],
      isStarred: false,
      unreadCount: 0,
      lastMessage: 'Truck dispatch confirmation received. Delivery expected at site on Thursday morning.',
      lastMessageTime: DateTime.now().subtract(const Duration(days: 2)),
      createdAt: DateTime.now().subtract(const Duration(days: 55)),
      messages: [
        ChatMessage(
          id: 'msg_10_01',
          conversationId: 'conv_10',
          direction: MessageDirection.outgoing,
          senderName: 'Karan Mehra',
          senderRole: 'Operations',
          content: 'Truck dispatch confirmation received. Delivery expected at site on Thursday morning.',
          timestamp: DateTime.now().subtract(const Duration(days: 2)),
          status: MessageStatus.read,
        ),
      ],
    ),

    // 11. Sunil & Meera Chawla - New Lead (WhatsApp, High Priority)
    Conversation(
      id: 'conv_11',
      customerContext: CustomerContext(
        customerId: 'CUST-8820',
        customerName: 'Sunil & Meera Chawla',
        customerPhone: '+91 98100 44991',
        customerEmail: 'sunil.chawla@delhicorp.in',
        city: 'Gurugram',
        crmStage: CustomerCrmStage.newLead,
        leadId: 'LEAD-4530',
        leadSource: 'Facebook Ad',
        budgetRange: '₹35L - ₹45L',
        propertyType: '3BHK Apartment (2100 sq.ft)',
        assignedEmployeeName: 'Unassigned',
        assignedEmployeeId: '',
        projectId: null,
        projectName: 'Smart World The Edition',
        projectStatus: 'Unclaimed Inbound Lead',
        contractValue: 0.0,
        totalInvoiced: 0.0,
        totalPaid: 0.0,
        balanceDue: 0.0,
        tags: ['New Lead', 'Unassigned', 'High Intent'],
        recentMilestones: ['Lead captured via FB Messenger ad'],
      ),
      channel: CommunicationChannel.whatsapp,
      status: ConversationStatus.open,
      priority: ConversationPriority.high,
      assignedEmployeeName: 'Unassigned',
      assignedEmployeeId: '',
      tags: ['Unassigned Lead', 'Urgent Claim'],
      isStarred: false,
      unreadCount: 2,
      lastMessage: 'Hi, we just received possession key for Smart World. Looking for complete modular woodwork and gypsum ceiling.',
      lastMessageTime: DateTime.now().subtract(const Duration(minutes: 15)),
      createdAt: DateTime.now().subtract(const Duration(minutes: 20)),
      messages: [
        ChatMessage(
          id: 'msg_11_01',
          conversationId: 'conv_11',
          direction: MessageDirection.incoming,
          senderName: 'Sunil Chawla',
          senderRole: 'Lead',
          content: 'Hi, we just received possession key for Smart World. Looking for complete modular woodwork and gypsum ceiling.',
          timestamp: DateTime.now().subtract(const Duration(minutes: 15)),
          status: MessageStatus.delivered,
        ),
      ],
    ),

    // 12. Deepak Nambiar - Payment Milestone (SMS, Urgent Priority)
    Conversation(
      id: 'conv_12',
      customerContext: CustomerContext(
        customerId: 'CUST-8821',
        customerName: 'Deepak Nambiar',
        customerPhone: '+91 99450 77120',
        customerEmail: 'deepak.nambiar@techsol.org',
        city: 'Bengaluru',
        crmStage: CustomerCrmStage.payment,
        leadId: 'LEAD-4012',
        leadSource: 'Direct Client Referral',
        budgetRange: '₹32L - ₹38L',
        propertyType: '3BHK Row House (2400 sq.ft)',
        assignedEmployeeName: 'Priya Sharma',
        assignedEmployeeId: 'EMP-014',
        projectId: 'PRJ-2026-14',
        projectName: 'Adarsh Palm Retreat Row House 12',
        projectStatus: 'Countertop Installation Pending Clearance',
        contractValue: 3400000.0,
        totalInvoiced: 2380000.0,
        totalPaid: 1700000.0,
        balanceDue: 680000.0,
        tags: ['Row House', 'Overdue Milestone'],
        recentMilestones: ['Carcass verified', 'Overdue reminder SMS sent'],
      ),
      channel: CommunicationChannel.sms,
      status: ConversationStatus.pending,
      priority: ConversationPriority.urgent,
      assignedEmployeeName: 'Priya Sharma',
      assignedEmployeeId: 'EMP-014',
      tags: ['Overdue Payment', 'Site Delayed'],
      isStarred: true,
      unreadCount: 0,
      lastMessage: 'Automated SMS Alert: Milestone payment of ₹6,80,000/- for Adarsh Palm Retreat is overdue by 3 days.',
      lastMessageTime: DateTime.now().subtract(const Duration(hours: 18)),
      createdAt: DateTime.now().subtract(const Duration(days: 75)),
      messages: [
        ChatMessage(
          id: 'msg_12_01',
          conversationId: 'conv_12',
          direction: MessageDirection.outgoing,
          senderName: 'Homio Finance Bot',
          senderRole: 'Automation',
          content: 'Automated SMS Alert: Milestone payment of ₹6,80,000/- for Adarsh Palm Retreat is overdue by 3 days.',
          timestamp: DateTime.now().subtract(const Duration(hours: 18)),
          status: MessageStatus.delivered,
        ),
      ],
    ),
  ];

  // ---------------------------------------------------------------------------
  // 6 Broadcast Campaigns
  // ---------------------------------------------------------------------------
  static final List<Broadcast> broadcasts = [
    Broadcast(
      id: 'bc_01',
      title: 'Festive Living Room Makeover 15% Early Bird',
      channel: CommunicationChannel.whatsapp,
      audienceFilter: 'Stage: Qualified Leads & Meetings Completed (Bengaluru & Mumbai)',
      targetCount: 1450,
      sentCount: 1450,
      deliveredCount: 1422,
      readCount: 1180,
      failedCount: 28,
      templateId: 'tpl_welcome_01',
      templateName: 'homio_welcome_v2',
      status: BroadcastStatus.completed,
      scheduledAt: DateTime.now().subtract(const Duration(days: 3)),
      completedAt: DateTime.now().subtract(const Duration(days: 3, hours: -1)),
      createdBy: 'Pooja Hegde',
      mediaUrl: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=800',
      rawMessage: 'Upgrade your living space before the festive season. Get 15% complimentary factory upgrade on Italian marble finishes and Hafele hardware.',
    ),
    Broadcast(
      id: 'bc_02',
      title: 'Monsoon Waterproofing & Modular Wardrobe Upgrade',
      channel: CommunicationChannel.whatsapp,
      audienceFilter: 'Stage: Booked & Execution Phase Clients',
      targetCount: 380,
      sentCount: 380,
      deliveredCount: 376,
      readCount: 342,
      failedCount: 4,
      templateId: 'tpl_site_progress_05',
      templateName: 'homio_site_progress_feed',
      status: BroadcastStatus.completed,
      scheduledAt: DateTime.now().subtract(const Duration(days: 7)),
      completedAt: DateTime.now().subtract(const Duration(days: 7, hours: -1)),
      createdBy: 'Engineering Operations',
      rawMessage: 'Important monsoon protection protocol for all active sites. All plywood edges treated with boiling water proof marine sealant.',
    ),
    Broadcast(
      id: 'bc_03',
      title: 'Upcoming Price Revision Notice - Premium Italian Marble',
      channel: CommunicationChannel.whatsapp,
      audienceFilter: 'Stage: Leads with Proposals in Progress',
      targetCount: 520,
      sentCount: 390,
      deliveredCount: 380,
      readCount: 210,
      failedCount: 10,
      templateId: 'tpl_quote_03',
      templateName: 'homio_quote_ready',
      status: BroadcastStatus.processing,
      scheduledAt: DateTime.now().subtract(const Duration(minutes: 30)),
      createdBy: 'Sales Operations',
      rawMessage: 'Notice: Import duty adjustments on Botticino & Michelangelo marble will take effect from Oct 1st. Lock in current rates with quote signoff.',
    ),
    Broadcast(
      id: 'bc_04',
      title: 'Homio Experience Center VIP Open House - Indiranagar',
      channel: CommunicationChannel.whatsapp,
      audienceFilter: 'All High-Intent Inquiries (Budget > ₹40L)',
      targetCount: 850,
      sentCount: 0,
      deliveredCount: 0,
      readCount: 0,
      failedCount: 0,
      templateId: 'tpl_consult_02',
      templateName: 'homio_consult_confirmed',
      status: BroadcastStatus.scheduled,
      scheduledAt: DateTime.now().add(const Duration(days: 2, hours: 4)),
      createdBy: 'Pooja Hegde',
      rawMessage: 'Exclusive invitation: Preview our brand new 1:1 scale Smart Kitchen & Acoustic Home Cinema setup at 100ft Road Indiranagar this weekend.',
    ),
    Broadcast(
      id: 'bc_05',
      title: 'Design Trends 2026 Lookbook Release',
      channel: CommunicationChannel.sms,
      audienceFilter: 'Cold Leads & Old Inquiries (> 60 Days)',
      targetCount: 3200,
      sentCount: 0,
      deliveredCount: 0,
      readCount: 0,
      failedCount: 0,
      templateId: 'tpl_welcome_01',
      templateName: 'homio_welcome_v2',
      status: BroadcastStatus.draft,
      scheduledAt: DateTime.now().add(const Duration(days: 5)),
      createdBy: 'Marketing Desk',
      rawMessage: 'Download the Homio 2026 Interior Trends Lookbook: Japandi minimalism meets Indian craftsmanship. Link: homio.in/lookbook26',
    ),
    Broadcast(
      id: 'bc_06',
      title: 'Post-Handover Warranty Inspection Camp',
      channel: CommunicationChannel.whatsapp,
      audienceFilter: 'Stage: After-Sales Clients (Handover > 90 Days)',
      targetCount: 195,
      sentCount: 195,
      deliveredCount: 180,
      readCount: 155,
      failedCount: 15,
      templateId: 'tpl_handover_06',
      templateName: 'homio_handover_warranty',
      status: BroadcastStatus.completed,
      scheduledAt: DateTime.now().subtract(const Duration(days: 14)),
      completedAt: DateTime.now().subtract(const Duration(days: 14, hours: -2)),
      createdBy: 'Customer Delight Head',
      rawMessage: 'Free preventive health checkup for your modular kitchen and wardrobes. Our master carpenter visits this Saturday.',
    ),
  ];

  // ---------------------------------------------------------------------------
  // Bulk Message Jobs
  // ---------------------------------------------------------------------------
  static final List<BulkMessageJob> bulkJobs = [
    BulkMessageJob(
      id: 'bulk_01',
      title: 'Prestige Lakeside Habitat Possession Outreach',
      fileName: 'prestige_lakeside_homeowners_sep26.xlsx',
      totalRows: 420,
      validRows: 408,
      invalidRows: 8,
      duplicateRows: 4,
      channel: CommunicationChannel.whatsapp,
      templateId: 'tpl_welcome_01',
      status: 'Completed',
      createdAt: DateTime.now().subtract(const Duration(days: 2)),
      processedCount: 408,
      successCount: 402,
      failureCount: 6,
    ),
    BulkMessageJob(
      id: 'bulk_02',
      title: 'Godrej Woodsman Handover Inquiries',
      fileName: 'godrej_woodsman_leads_verified.csv',
      totalRows: 190,
      validRows: 185,
      invalidRows: 3,
      duplicateRows: 2,
      channel: CommunicationChannel.whatsapp,
      templateId: 'tpl_welcome_01',
      status: 'Completed',
      createdAt: DateTime.now().subtract(const Duration(days: 5)),
      processedCount: 185,
      successCount: 182,
      failureCount: 3,
    ),
    BulkMessageJob(
      id: 'bulk_03',
      title: 'DLF Camellias Renovation Campaign',
      fileName: 'camellias_hni_contacts.xlsx',
      totalRows: 85,
      validRows: 82,
      invalidRows: 2,
      duplicateRows: 1,
      channel: CommunicationChannel.whatsapp,
      templateId: 'tpl_consult_02',
      status: 'Processing',
      createdAt: DateTime.now().subtract(const Duration(minutes: 45)),
      scheduledAt: DateTime.now().add(const Duration(minutes: 15)),
      processedCount: 45,
      successCount: 44,
      failureCount: 1,
    ),
    BulkMessageJob(
      id: 'bulk_04',
      title: 'Exhibition Stall Inquiries - Index Fair 2026',
      fileName: 'index_fair_booth_visitors.csv',
      totalRows: 650,
      validRows: 620,
      invalidRows: 18,
      duplicateRows: 12,
      channel: CommunicationChannel.sms,
      templateId: 'tpl_welcome_01',
      status: 'Pending',
      createdAt: DateTime.now().subtract(const Duration(hours: 1)),
      scheduledAt: DateTime.now().add(const Duration(hours: 3)),
      processedCount: 0,
      successCount: 0,
      failureCount: 0,
    ),
  ];

  // ---------------------------------------------------------------------------
  // 15 Scheduled Messages
  // ---------------------------------------------------------------------------
  static final List<ScheduledMessage> scheduledMessages = [
    ScheduledMessage(
      id: 'sch_01',
      recipientName: 'Vikram Malhotra',
      recipientPhone: '+91 98450 91823',
      channel: CommunicationChannel.whatsapp,
      templateName: 'homio_consult_confirmed',
      content: 'Reminder: Stone & Veneer physical sample review scheduled for tomorrow at 11:30 AM at our Indiranagar Studio.',
      scheduledFor: DateTime.now().add(const Duration(hours: 18)),
      status: ScheduledMessageStatus.scheduled,
      createdBy: 'Priya Sharma',
      customerId: 'CUST-8810',
      projectId: 'PRJ-2026-08',
    ),
    ScheduledMessage(
      id: 'sch_02',
      recipientName: 'Sneha & Rajesh Reddy',
      recipientPhone: '+91 97410 44219',
      channel: CommunicationChannel.whatsapp,
      templateName: 'homio_consult_confirmed',
      content: 'Your 3D VR walkthrough session begins in 2 hours at Homio Whitefield Studio. Parking space reserved under your name.',
      scheduledFor: DateTime.now().add(const Duration(hours: 24)),
      status: ScheduledMessageStatus.scheduled,
      createdBy: 'Karan Mehra',
      customerId: 'CUST-8811',
      projectId: 'PRJ-2026-19',
    ),
    ScheduledMessage(
      id: 'sch_03',
      recipientName: 'Ananya Deshmukh',
      recipientPhone: '+91 99201 55670',
      channel: CommunicationChannel.whatsapp,
      templateName: 'homio_site_progress_feed',
      content: 'Electrical conduit pressure testing video upload scheduled for your client portal review.',
      scheduledFor: DateTime.now().add(const Duration(days: 2)),
      status: ScheduledMessageStatus.scheduled,
      createdBy: 'Rohan Joshi',
      customerId: 'CUST-8812',
      projectId: 'PRJ-2026-03',
    ),
    ScheduledMessage(
      id: 'sch_04',
      recipientName: 'Dr. Arishti Kapoor',
      recipientPhone: '+91 98112 39012',
      channel: CommunicationChannel.whatsapp,
      templateName: 'homio_payment_milestone',
      content: 'Milestone payment reminder for POP False Ceiling handover invoice #INV-2026-0419.',
      scheduledFor: DateTime.now().add(const Duration(days: 3)),
      status: ScheduledMessageStatus.scheduled,
      createdBy: 'FinOps Team',
      customerId: 'CUST-8813',
      projectId: 'PRJ-2026-11',
    ),
    ScheduledMessage(
      id: 'sch_05',
      recipientName: 'Rohan Mehta',
      recipientPhone: '+91 98200 81765',
      channel: CommunicationChannel.sms,
      content: 'Hi Rohan, Senior Consultant Aarti will call you at 6:15 PM today regarding your Oberoi Sky City 4BHK query.',
      scheduledFor: DateTime.now().add(const Duration(hours: 5)),
      status: ScheduledMessageStatus.scheduled,
      createdBy: 'Aarti Kulkarni',
      customerId: 'CUST-8814',
    ),
    ScheduledMessage(
      id: 'sch_06',
      recipientName: 'Neha & Varun Kapoor',
      recipientPhone: '+91 99100 88231',
      channel: CommunicationChannel.whatsapp,
      content: 'Material moodboard delivery to your residence by courier dispatched. Tracking code: DTDC-BLR-99214.',
      scheduledFor: DateTime.now().add(const Duration(hours: 3)),
      status: ScheduledMessageStatus.scheduled,
      createdBy: 'Pooja Hegde',
      customerId: 'CUST-8816',
      projectId: 'PRJ-2026-27',
    ),
    ScheduledMessage(
      id: 'sch_07',
      recipientName: 'Sunil & Meera Chawla',
      recipientPhone: '+91 98100 44991',
      channel: CommunicationChannel.whatsapp,
      templateName: 'homio_welcome_v2',
      content: 'Welcome to Homio! Sharing our curated 3BHK portfolio and layout suggestions for Smart World The Edition.',
      scheduledFor: DateTime.now().add(const Duration(minutes: 30)),
      status: ScheduledMessageStatus.scheduled,
      createdBy: 'Concierge Bot',
      customerId: 'CUST-8820',
    ),
    ScheduledMessage(
      id: 'sch_08',
      recipientName: 'Deepak Nambiar',
      recipientPhone: '+91 99450 77120',
      channel: CommunicationChannel.sms,
      content: 'Final notice: Please clear overdue milestone payment #INV-2026-0388 to prevent quartz countertop delivery hold.',
      scheduledFor: DateTime.now().add(const Duration(days: 1)),
      status: ScheduledMessageStatus.scheduled,
      createdBy: 'Priya Sharma',
      customerId: 'CUST-8821',
      projectId: 'PRJ-2026-14',
    ),
  ];

  // ---------------------------------------------------------------------------
  // 4 Drip Automation Campaigns with Visual Workflow Nodes
  // ---------------------------------------------------------------------------
  static final List<DripCampaign> dripCampaigns = [
    // Drip 1: High-Intent Web Lead 7-Day Nurture
    DripCampaign(
      id: 'drip_01',
      name: 'High-Intent Web Lead 7-Day Nurture Journey',
      description: 'Automated omnichannel engagement converting fresh website inquiries into booked 3D design studio sessions.',
      triggerType: DripTriggerType.leadCreated,
      status: DripCampaignStatus.active,
      targetAudienceDesc: 'All verified website leads with estimated budget > ₹25L',
      enrolledCount: 342,
      activeCount: 88,
      completedCount: 236,
      failedCount: 18,
      conversionRate: 0.384, // 38.4% consultation booking
      createdAt: DateTime.now().subtract(const Duration(days: 90)),
      updatedAt: DateTime.now().subtract(const Duration(days: 3)),
      nodes: [
        const DripNode(
          id: 'node_01',
          type: DripNodeType.sendWhatsApp,
          title: 'Immediate Welcome Message',
          description: 'Send greeting + 2026 Design Portfolio PDF link within 60 seconds.',
          config: {'template': 'homio_welcome_v2', 'delay_seconds': 60},
          posX: 80,
          posY: 120,
          nextNodeIds: ['node_02'],
        ),
        const DripNode(
          id: 'node_02',
          type: DripNodeType.waitDuration,
          title: 'Wait 24 Hours',
          description: 'Allow customer time to browse lookbook before follow-up.',
          config: {'duration_hours': 24},
          posX: 320,
          posY: 120,
          nextNodeIds: ['node_03'],
        ),
        const DripNode(
          id: 'node_03',
          type: DripNodeType.conditionCheck,
          title: 'Did Customer Reply or Book?',
          description: 'Branch based on whether lead interacted with lookbook or scheduled consultation.',
          config: {'condition': 'has_replied_or_scheduled'},
          posX: 560,
          posY: 120,
          nextNodeIds: ['node_04', 'node_05'],
          fallbackNodeId: 'node_05',
        ),
        const DripNode(
          id: 'node_04',
          type: DripNodeType.assignEmployee,
          title: 'Assign Senior Architect',
          description: 'Lead is warm & engaged. Notify sales manager to schedule consultation.',
          config: {'role': 'Senior Architect', 'priority': 'HIGH'},
          posX: 820,
          posY: 60,
          nextNodeIds: ['node_06'],
        ),
        const DripNode(
          id: 'node_05',
          type: DripNodeType.sendTemplate,
          title: 'Share Video Walkthrough of Live Project',
          description: 'Nurture cold lead with real video testimonial of finished apartment.',
          config: {'template': 'homio_video_testimonial', 'channel': 'whatsapp'},
          posX: 820,
          posY: 220,
          nextNodeIds: ['node_07'],
        ),
        const DripNode(
          id: 'node_06',
          type: DripNodeType.endWorkflow,
          title: 'Handover to Sales CRM',
          description: 'Lead entered sales pipeline.',
          config: {},
          posX: 1060,
          posY: 60,
        ),
        const DripNode(
          id: 'node_07',
          type: DripNodeType.waitDuration,
          title: 'Wait 48 Hours',
          description: 'Final follow-up interval.',
          config: {'duration_hours': 48},
          posX: 1060,
          posY: 220,
          nextNodeIds: ['node_08'],
        ),
        const DripNode(
          id: 'node_08',
          type: DripNodeType.sendSms,
          title: 'Complimentary 3D Consultation Offer',
          description: 'Final urgency trigger: Free site measurement worth ₹5,000.',
          config: {'channel': 'sms'},
          posX: 1300,
          posY: 220,
          nextNodeIds: ['node_09'],
        ),
        const DripNode(
          id: 'node_09',
          type: DripNodeType.endWorkflow,
          title: 'Complete 7-Day Cycle',
          description: 'Workflow completed.',
          config: {},
          posX: 1540,
          posY: 220,
        ),
      ],
    ),

    // Drip 2: Post-Design Consultation Booking Drip
    DripCampaign(
      id: 'drip_02',
      name: 'Post-Consultation Estimate Signoff Drip',
      description: 'Systematic reminder sequence after client attends 3D design consultation to accelerate token booking.',
      triggerType: DripTriggerType.meetingCompleted,
      status: DripCampaignStatus.active,
      targetAudienceDesc: 'Clients with meeting completed and quote shared',
      enrolledCount: 185,
      activeCount: 42,
      completedCount: 137,
      failedCount: 6,
      conversionRate: 0.512,
      createdAt: DateTime.now().subtract(const Duration(days: 60)),
      updatedAt: DateTime.now().subtract(const Duration(days: 5)),
      nodes: [
        const DripNode(
          id: 'd2_node_01',
          type: DripNodeType.sendWhatsApp,
          title: 'Send Minutes & 3D Render Gallery',
          description: 'Share personalized PDF proposal link within 2 hours of session.',
          posX: 80,
          posY: 100,
          nextNodeIds: ['d2_node_02'],
        ),
        const DripNode(
          id: 'd2_node_02',
          type: DripNodeType.waitDuration,
          title: 'Wait 48 Hours',
          description: 'Family discussion window.',
          posX: 340,
          posY: 100,
          nextNodeIds: ['d2_node_03'],
        ),
        const DripNode(
          id: 'd2_node_03',
          type: DripNodeType.conditionCheck,
          title: 'Has Quote Been Viewed?',
          description: 'Check proposal portal analytics.',
          posX: 600,
          posY: 100,
          nextNodeIds: ['d2_node_04', 'd2_node_05'],
        ),
        const DripNode(
          id: 'd2_node_04',
          type: DripNodeType.sendWhatsApp,
          title: 'Send 10-Year Warranty & Factory Assurance',
          description: 'Address quality hesitations with German hardware warranty proof.',
          posX: 860,
          posY: 40,
          nextNodeIds: ['d2_node_06'],
        ),
        const DripNode(
          id: 'd2_node_05',
          type: DripNodeType.createTask,
          title: 'Create Task: Designer Call',
          description: 'Lead hasn’t opened quote. Designer to call and assist.',
          posX: 860,
          posY: 180,
          nextNodeIds: ['d2_node_06'],
        ),
        const DripNode(
          id: 'd2_node_06',
          type: DripNodeType.endWorkflow,
          title: 'End Post-Consultation Flow',
          description: 'Concluded.',
          posX: 1120,
          posY: 100,
        ),
      ],
    ),

    // Drip 3: Milestone Payment Reminder Flow
    DripCampaign(
      id: 'drip_03',
      name: 'Milestone Payment Due & Gentle Recovery Flow',
      description: 'Polite, automated WhatsApp & SMS reminders before and after milestone due date.',
      triggerType: DripTriggerType.paymentDue,
      status: DripCampaignStatus.active,
      targetAudienceDesc: 'Active execution clients with invoices due in 3 days',
      enrolledCount: 220,
      activeCount: 28,
      completedCount: 188,
      failedCount: 4,
      conversionRate: 0.895, // 89.5% paid on time
      createdAt: DateTime.now().subtract(const Duration(days: 120)),
      updatedAt: DateTime.now().subtract(const Duration(days: 1)),
      nodes: [
        const DripNode(
          id: 'd3_node_01',
          type: DripNodeType.sendTemplate,
          title: 'T-3 Days: Upcoming Milestone Notice',
          description: 'Gentle notification with QC photo report and invoice breakdown.',
          posX: 80,
          posY: 100,
          nextNodeIds: ['d3_node_02'],
        ),
        const DripNode(
          id: 'd3_node_02',
          type: DripNodeType.waitDuration,
          title: 'Wait Until Due Date (3 Days)',
          description: 'Pause until invoice due date.',
          posX: 340,
          posY: 100,
          nextNodeIds: ['d3_node_03'],
        ),
        const DripNode(
          id: 'd3_node_03',
          type: DripNodeType.conditionCheck,
          title: 'Is Payment Cleared?',
          description: 'Verify finance ledger status.',
          posX: 600,
          posY: 100,
          nextNodeIds: ['d3_node_04', 'd3_node_05'],
        ),
        const DripNode(
          id: 'd3_node_04',
          type: DripNodeType.sendWhatsApp,
          title: 'Send Official Payment Receipt',
          description: 'Instant acknowledgment with GST breakdown.',
          posX: 860,
          posY: 40,
          nextNodeIds: ['d3_node_06'],
        ),
        const DripNode(
          id: 'd3_node_05',
          type: DripNodeType.sendPaymentLink,
          title: 'Send Urgent Razorpay Link + SMS',
          description: 'Payment overdue reminder to client and spouse.',
          posX: 860,
          posY: 180,
          nextNodeIds: ['d3_node_06'],
        ),
        const DripNode(
          id: 'd3_node_06',
          type: DripNodeType.endWorkflow,
          title: 'Flow Terminated',
          description: 'Finished.',
          posX: 1120,
          posY: 100,
        ),
      ],
    ),

    // Drip 4: Handover to 1-Year After-Sales Care
    DripCampaign(
      id: 'drip_04',
      name: '1-Year Post-Handover Happiness Journey',
      description: 'Scheduled touchpoints at 30 days, 90 days, 180 days, and 365 days for maintenance, referrals, and warranty renewals.',
      triggerType: DripTriggerType.siteMilestoneReached,
      status: DripCampaignStatus.active,
      targetAudienceDesc: 'All completed client handovers',
      enrolledCount: 95,
      activeCount: 82,
      completedCount: 12,
      failedCount: 1,
      conversionRate: 0.96,
      createdAt: DateTime.now().subtract(const Duration(days: 180)),
      updatedAt: DateTime.now().subtract(const Duration(days: 10)),
      nodes: [
        const DripNode(
          id: 'd4_node_01',
          type: DripNodeType.sendWhatsApp,
          title: 'Day 30: Housewarming Greetings & Gift Basket',
          description: 'Congratulate homeowner and request Google Review.',
          posX: 80,
          posY: 100,
          nextNodeIds: ['d4_node_02'],
        ),
        const DripNode(
          id: 'd4_node_02',
          type: DripNodeType.waitDuration,
          title: 'Wait 60 Days (Day 90)',
          description: 'Quarterly check-in.',
          posX: 340,
          posY: 100,
          nextNodeIds: ['d4_node_03'],
        ),
        const DripNode(
          id: 'd4_node_03',
          type: DripNodeType.sendWhatsApp,
          title: 'Day 90: Hardware Deep-Check Booking',
          description: 'Complimentary technician visit for drawer alignments.',
          posX: 600,
          posY: 100,
          nextNodeIds: ['d4_node_04'],
        ),
        const DripNode(
          id: 'd4_node_04',
          type: DripNodeType.endWorkflow,
          title: 'Journey Complete',
          description: 'Client transitions to lifetime loyalty tier.',
          posX: 860,
          posY: 100,
        ),
      ],
    ),
  ];

  // ---------------------------------------------------------------------------
  // Communication Audit Records (40+ items across channels & sources)
  // ---------------------------------------------------------------------------
  static final List<CommunicationRecord> auditHistory = [
    CommunicationRecord(
      id: 'AUD-9901',
      timestamp: DateTime.now().subtract(const Duration(minutes: 8)),
      customerName: 'Vikram Malhotra',
      customerPhone: '+91 98450 91823',
      customerId: 'CUST-8810',
      channel: CommunicationChannel.whatsapp,
      direction: MessageDirection.incoming,
      actorType: 'Client',
      actorName: 'Vikram Malhotra',
      contentType: MessageContentType.image,
      previewText: 'Can we switch master wardrobe glass to charcoal grey? Attaching photo.',
      status: MessageStatus.delivered,
      sourceModule: 'manual',
      relatedEntityId: 'PRJ-2026-08',
      relatedEntityType: 'project',
    ),
    CommunicationRecord(
      id: 'AUD-9902',
      timestamp: DateTime.now().subtract(const Duration(minutes: 24)),
      customerName: 'Sneha & Rajesh Reddy',
      customerPhone: '+91 97410 44219',
      customerId: 'CUST-8811',
      channel: CommunicationChannel.whatsapp,
      direction: MessageDirection.incoming,
      actorType: 'Client',
      actorName: 'Sneha Reddy',
      contentType: MessageContentType.text,
      previewText: 'Will 3D walkthrough include arched corridor with cove lighting?',
      status: MessageStatus.delivered,
      sourceModule: 'manual',
      relatedEntityId: 'LEAD-4490',
      relatedEntityType: 'lead',
    ),
    CommunicationRecord(
      id: 'AUD-9903',
      timestamp: DateTime.now().subtract(const Duration(minutes: 50)),
      customerName: 'Dr. Arishti Kapoor',
      customerPhone: '+91 98112 39012',
      customerId: 'CUST-8813',
      channel: CommunicationChannel.whatsapp,
      direction: MessageDirection.incoming,
      actorType: 'Client',
      actorName: 'Dr. Arishti Kapoor',
      contentType: MessageContentType.text,
      previewText: 'The magnetic track light channels look stunning! When do fixtures arrive?',
      status: MessageStatus.delivered,
      sourceModule: 'manual',
      relatedEntityId: 'PRJ-2026-11',
      relatedEntityType: 'project',
    ),
    CommunicationRecord(
      id: 'AUD-9904',
      timestamp: DateTime.now().subtract(const Duration(hours: 1, minutes: 12)),
      customerName: 'Rohan Mehta',
      customerPhone: '+91 98200 81765',
      customerId: 'CUST-8814',
      channel: CommunicationChannel.sms,
      direction: MessageDirection.incoming,
      actorType: 'Client',
      actorName: 'Rohan Mehta',
      contentType: MessageContentType.text,
      previewText: 'Please call me after 6 PM today to discuss full quote for 4BHK.',
      status: MessageStatus.delivered,
      sourceModule: 'manual',
      relatedEntityId: 'LEAD-4510',
      relatedEntityType: 'lead',
    ),
    CommunicationRecord(
      id: 'AUD-9905',
      timestamp: DateTime.now().subtract(const Duration(hours: 2)),
      customerName: 'Ananya Deshmukh',
      customerPhone: '+91 99201 55670',
      customerId: 'CUST-8812',
      channel: CommunicationChannel.whatsapp,
      direction: MessageDirection.incoming,
      actorType: 'Client',
      actorName: 'Ananya Deshmukh',
      contentType: MessageContentType.text,
      previewText: 'Payment of ₹8.4L initiated via NEFT. UTR: HDFC00291048201.',
      status: MessageStatus.read,
      sourceModule: 'manual',
      relatedEntityId: 'INV-2026-0412',
      relatedEntityType: 'invoice',
    ),
    CommunicationRecord(
      id: 'AUD-9906',
      timestamp: DateTime.now().subtract(const Duration(hours: 3)),
      customerName: 'Vikram Malhotra',
      customerPhone: '+91 98450 91823',
      customerId: 'CUST-8810',
      channel: CommunicationChannel.whatsapp,
      direction: MessageDirection.outgoing,
      actorType: 'Employee',
      actorName: 'Priya Sharma (Senior Architect)',
      contentType: MessageContentType.text,
      previewText: 'Factory team in Peenya has started cutting Austrian Egger boards for walk-in.',
      status: MessageStatus.read,
      sourceModule: 'manual',
      relatedEntityId: 'PRJ-2026-08',
      relatedEntityType: 'project',
    ),
    CommunicationRecord(
      id: 'AUD-9907',
      timestamp: DateTime.now().subtract(const Duration(hours: 4)),
      customerName: 'Neha & Varun Kapoor',
      customerPhone: '+91 99100 88231',
      customerId: 'CUST-8816',
      channel: CommunicationChannel.whatsapp,
      direction: MessageDirection.incoming,
      actorType: 'Client',
      actorName: 'Varun Kapoor',
      contentType: MessageContentType.document,
      previewText: 'Sharing signed design brief document and chosen palette for bar lounge.',
      status: MessageStatus.read,
      sourceModule: 'manual',
      relatedEntityId: 'PRJ-2026-27',
      relatedEntityType: 'project',
    ),
    CommunicationRecord(
      id: 'AUD-9908',
      timestamp: DateTime.now().subtract(const Duration(hours: 5)),
      customerName: 'Sneha & Rajesh Reddy',
      customerPhone: '+91 97410 44219',
      customerId: 'CUST-8811',
      channel: CommunicationChannel.whatsapp,
      direction: MessageDirection.outgoing,
      actorType: 'Bot',
      actorName: 'Homio Concierge AI',
      contentType: MessageContentType.template,
      previewText: 'Design consultation confirmed with Shalini Nair for tomorrow 3:30 PM.',
      status: MessageStatus.read,
      sourceModule: 'chatbot',
      relatedEntityId: 'LEAD-4490',
      relatedEntityType: 'meeting',
      templateCode: 'homio_consult_confirmed',
    ),
    CommunicationRecord(
      id: 'AUD-9909',
      timestamp: DateTime.now().subtract(const Duration(hours: 6)),
      customerName: 'Gaurav Singhania',
      customerPhone: '+91 98290 11980',
      customerId: 'CUST-8817',
      channel: CommunicationChannel.email,
      direction: MessageDirection.incoming,
      actorType: 'Client',
      actorName: 'Gaurav Singhania',
      contentType: MessageContentType.text,
      previewText: 'Requested itemized quote breakdown for Italian marble vs engineered oak.',
      status: MessageStatus.read,
      sourceModule: 'manual',
      relatedEntityId: 'LEAD-4450',
      relatedEntityType: 'lead',
    ),
    CommunicationRecord(
      id: 'AUD-9910',
      timestamp: DateTime.now().subtract(const Duration(hours: 8)),
      customerName: 'Tanvi Parekh',
      customerPhone: '+91 98211 44556',
      customerId: 'CUST-8818',
      channel: CommunicationChannel.whatsapp,
      direction: MessageDirection.outgoing,
      actorType: 'Employee',
      actorName: 'Shalini Nair',
      contentType: MessageContentType.text,
      previewText: 'Shared Art Deco moodboard and preliminary finish matrix.',
      status: MessageStatus.read,
      sourceModule: 'manual',
      relatedEntityId: 'PRJ-2026-31',
      relatedEntityType: 'quotation',
    ),
    CommunicationRecord(
      id: 'AUD-9911',
      timestamp: DateTime.now().subtract(const Duration(hours: 18)),
      customerName: 'Deepak Nambiar',
      customerPhone: '+91 99450 77120',
      customerId: 'CUST-8821',
      channel: CommunicationChannel.sms,
      direction: MessageDirection.outgoing,
      actorType: 'System',
      actorName: 'FinOps Automation',
      contentType: MessageContentType.text,
      previewText: 'Milestone payment ₹6,80,000/- for Adarsh Palm Retreat is overdue by 3 days.',
      status: MessageStatus.delivered,
      sourceModule: 'drip',
      relatedEntityId: 'INV-2026-0388',
      relatedEntityType: 'invoice',
    ),
    CommunicationRecord(
      id: 'AUD-9912',
      timestamp: DateTime.now().subtract(const Duration(days: 1)),
      customerName: 'Amitav & Priya Sen',
      customerPhone: '+91 98300 23419',
      customerId: 'CUST-8815',
      channel: CommunicationChannel.whatsapp,
      direction: MessageDirection.incoming,
      actorType: 'Client',
      actorName: 'Amitav Sen',
      contentType: MessageContentType.text,
      previewText: 'Technician attended soft-close hydraulic hinge calibration. Works great now!',
      status: MessageStatus.read,
      sourceModule: 'manual',
      relatedEntityId: 'PRJ-2025-44',
      relatedEntityType: 'project',
    ),
    CommunicationRecord(
      id: 'AUD-9913',
      timestamp: DateTime.now().subtract(const Duration(days: 2)),
      customerName: '1,450 Homeowners',
      customerPhone: 'Broadcast Audience',
      customerId: 'AUDIENCE-FESTIVE',
      channel: CommunicationChannel.whatsapp,
      direction: MessageDirection.outgoing,
      actorType: 'System',
      actorName: 'Broadcast Service',
      contentType: MessageContentType.template,
      previewText: 'Festive Living Room Makeover 15% Early Bird campaign broadcasted.',
      status: MessageStatus.delivered,
      sourceModule: 'broadcast',
      templateCode: 'homio_welcome_v2',
    ),
  ];
}
