import 'labour_models.dart';

class LabourMockData {
  static List<TradeMaster> tradesMasterList = const [
    TradeMaster(
      id: 'TRD-01',
      name: 'Carpentry & Woodwork',
      category: 'Wood & Millwork',
      description: 'Modular kitchens, wardrobes, carcass assembly, veneer lamination, door frame fittings.',
      skillLevels: [SkillLevel.beginner, SkillLevel.intermediate, SkillLevel.skilled, SkillLevel.expert, SkillLevel.specialist],
      defaultRateUnit: RateUnit.perDay,
      certifications: ['Hettich Certified', 'Hafele Hardware Specialist', 'Greenply Approved'],
    ),
    TradeMaster(
      id: 'TRD-02',
      name: 'Masonry & Civil Works',
      category: 'Civil & Structural',
      description: 'Brick masonry, plastering, Italian marble laying, granite counter polishing, civil demolition.',
      skillLevels: [SkillLevel.beginner, SkillLevel.intermediate, SkillLevel.skilled, SkillLevel.expert],
      defaultRateUnit: RateUnit.perDay,
      certifications: ['Laticrete Certified Slurry Applicator', 'Cemex Concrete Leveling'],
    ),
    TradeMaster(
      id: 'TRD-03',
      name: 'Electrical & Lighting',
      category: 'MEP Services',
      description: 'Conduit piping, wire pulling, switchboard fitting, smart home automation relays, distribution boards.',
      skillLevels: [SkillLevel.intermediate, SkillLevel.skilled, SkillLevel.expert, SkillLevel.specialist],
      defaultRateUnit: RateUnit.perDay,
      certifications: ['Schneider Electric EcoStruxure', 'Legrand Home Automation'],
    ),
    TradeMaster(
      id: 'TRD-04',
      name: 'Plumbing & Sanitary',
      category: 'MEP Services',
      description: 'CPVC/UPVC water lines, drainage piping, concealed divertors, sensor faucets, pressure pump setups.',
      skillLevels: [SkillLevel.intermediate, SkillLevel.skilled, SkillLevel.expert],
      defaultRateUnit: RateUnit.perDay,
      certifications: ['Kohler Certified Plumber', 'Grohe Hydro-Static Master'],
    ),
    TradeMaster(
      id: 'TRD-05',
      name: 'Painting & PU Polish',
      category: 'Finishing & Wall Decor',
      description: 'Wall putty sanding, Royale luxury emulsion, Italian PU polish spray, texture stucco, wood staining.',
      skillLevels: [SkillLevel.beginner, SkillLevel.intermediate, SkillLevel.skilled, SkillLevel.expert],
      defaultRateUnit: RateUnit.perSqft,
      certifications: ['Asian Paints Royale Certified', 'Berger Master Painter'],
    ),
    TradeMaster(
      id: 'TRD-06',
      name: 'POP & False Ceiling',
      category: 'Ceiling & Drywall',
      description: 'Gypsum board ceiling, perimeter cove light boxing, grid ceiling, acoustic drywall partitions.',
      skillLevels: [SkillLevel.intermediate, SkillLevel.skilled, SkillLevel.expert],
      defaultRateUnit: RateUnit.perSqft,
      certifications: ['Saint-Gobain Gyproc Certified', 'USG Boral Specialist'],
    ),
    TradeMaster(
      id: 'TRD-07',
      name: 'Metal Fabrication & Grills',
      category: 'Structural Metal',
      description: 'MS safety doors, stainless steel glass railings, staircase spiral stringers, laser cut jali welding.',
      skillLevels: [SkillLevel.skilled, SkillLevel.expert],
      defaultRateUnit: RateUnit.perDay,
      certifications: ['IS 2062 Grade Welding Certified'],
    ),
    TradeMaster(
      id: 'TRD-08',
      name: 'Tile & Granite Laying',
      category: 'Flooring & Cladding',
      description: 'Large format 1200x2400mm GVT tiles, vitrified flooring, bathroom epoxy grouting, kitchen platform.',
      skillLevels: [SkillLevel.intermediate, SkillLevel.skilled, SkillLevel.expert],
      defaultRateUnit: RateUnit.perSqft,
      certifications: ['Kajaria Certified Applicator', 'MYK Laticrete Grout Master'],
    ),
  ];

  static List<LabourProfile> profiles = [
    LabourProfile(
      id: 'LBR-101',
      legalName: 'Ramprasad Sharma',
      alias: 'Ramprasad Mistri',
      displayName: 'Ramprasad S.',
      phone: '+91 98101 23456',
      altPhone: '+91 98101 23457',
      email: 'ramprasad.sharma@homiofield.in',
      gender: 'Male',
      trade: TradeType.carpentry,
      secondarySkills: ['Modular Kitchen', 'Veneer Polish', 'Hardware Fitting'],
      experienceYears: 12,
      rating: 4.88,
      totalReviews: 64,
      completedJobs: 82,
      punctualityScore: 98.5,
      dailyRate: 1100.0,
      sqftRate: 125.0,
      overtimeHourlyRate: 200.0,
      minJobAmount: 600.0,
      travelCharge: 150.0,
      isNegotiable: false,
      city: 'Gurugram',
      zone: 'DLF Phase 1-5 & Golf Course Ext',
      address: 'H-42, Chakkarpur, Near MG Road Metro',
      state: 'Haryana',
      pincode: '122002',
      operatingAreas: ['DLF Phase 1-5', 'Golf Course Road', 'Cyber City', 'Sohna Road'],
      preferredRadiusKm: 18.0,
      distanceKm: 2.4,
      kycStatus: KycStatus.approved,
      labourStatus: LabourStatus.onSite,
      extendedStatus: ExtendedLabourStatus.onJob,
      skillLevel: SkillLevel.expert,
      rateUnit: RateUnit.perDay,
      aadhaarMasked: 'XXXX-XXXX-4892',
      policeVerificationNo: 'PCC-HR-GGN-2024-8841',
      photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
      emergencyContact: 'Sunita Sharma (Wife)',
      emergencyPhone: '+91 98101 99881',
      emergencyRelationship: 'Spouse',
      skillBadges: ['Master Woodworker', 'Hettich Hardware Certified', 'Clean Site Badge'],
      currentSiteAssigned: 'PRJ-104 - 4BHK DLF Phase 5',
      walletBalance: 14500.0,
      onTimePercentage: 98.0,
      qualityScore: 4.9,
      behaviourScore: 4.8,
      reliabilityScore: 4.9,
      activeJobsCount: 1,
      disputeCount: 0,
      strikesCount: 0,
      onboardingDate: DateTime(2023, 8, 14),
      lastActivity: 'Active on Site: PRJ-104 (15m ago)',
    ),
    LabourProfile(
      id: 'LBR-102',
      legalName: 'Mohammad Shakeel',
      alias: 'Shakeel Plumber',
      displayName: 'M. Shakeel',
      phone: '+91 98712 34567',
      altPhone: '+91 98712 34568',
      email: 'shakeel.plumber@homiofield.in',
      gender: 'Male',
      trade: TradeType.plumbing,
      secondarySkills: ['CPVC Piping', 'Grohe/Kohler Concealed Diverter', 'Pressure Testing'],
      experienceYears: 9,
      rating: 4.75,
      totalReviews: 48,
      completedJobs: 61,
      punctualityScore: 96.0,
      dailyRate: 950.0,
      sqftRate: 45.0,
      overtimeHourlyRate: 180.0,
      city: 'Gurugram',
      zone: 'Sohna Road & South City',
      address: 'Plot 18, Islampur Village, Sector 38',
      state: 'Haryana',
      pincode: '122001',
      operatingAreas: ['Sohna Road', 'South City 1 & 2', 'Nirvana Country'],
      preferredRadiusKm: 15.0,
      distanceKm: 4.1,
      kycStatus: KycStatus.approved,
      labourStatus: LabourStatus.available,
      extendedStatus: ExtendedLabourStatus.active,
      skillLevel: SkillLevel.skilled,
      rateUnit: RateUnit.perDay,
      aadhaarMasked: 'XXXX-XXXX-7123',
      policeVerificationNo: 'PCC-HR-GGN-2024-9120',
      photoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
      emergencyContact: 'Parveen Akhtar (Brother)',
      emergencyPhone: '+91 98712 88776',
      emergencyRelationship: 'Brother',
      skillBadges: ['Kohler Certified', 'Hydro-Static Pressure Expert', 'Zero Leakage Guarantee'],
      currentSiteAssigned: '',
      walletBalance: 8200.0,
      onTimePercentage: 96.0,
      qualityScore: 4.8,
      behaviourScore: 4.7,
      reliabilityScore: 4.8,
      activeJobsCount: 0,
      disputeCount: 0,
      strikesCount: 0,
      onboardingDate: DateTime(2023, 10, 5),
      lastActivity: 'Checked availability (30m ago)',
    ),
    LabourProfile(
      id: 'LBR-103',
      legalName: 'Dharmendra Kumar Yadav',
      alias: 'Dharmu Mistri',
      displayName: 'Dharmendra Y.',
      phone: '+91 99533 45678',
      altPhone: '',
      email: 'dharmendra.yadav@homiofield.in',
      gender: 'Male',
      trade: TradeType.masonry,
      secondarySkills: ['Italian Marble Inlay', 'Granite Molding', 'Epoxy Grouting'],
      experienceYears: 15,
      rating: 4.92,
      totalReviews: 92,
      completedJobs: 110,
      punctualityScore: 99.0,
      dailyRate: 1250.0,
      sqftRate: 85.0,
      overtimeHourlyRate: 220.0,
      city: 'New Delhi',
      zone: 'South Delhi & Golf Links',
      address: 'Lane 4, Kotla Mubarakpur, Near Defence Colony',
      state: 'Delhi',
      pincode: '110003',
      operatingAreas: ['Golf Links', 'Vasant Vihar', 'Jor Bagh', 'Sundar Nagar'],
      preferredRadiusKm: 25.0,
      distanceKm: 6.8,
      kycStatus: KycStatus.approved,
      labourStatus: LabourStatus.onSite,
      extendedStatus: ExtendedLabourStatus.onJob,
      skillLevel: SkillLevel.specialist,
      rateUnit: RateUnit.perDay,
      aadhaarMasked: 'XXXX-XXXX-8910',
      policeVerificationNo: 'PCC-DL-SD-2024-1002',
      photoUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
      emergencyContact: 'Manju Yadav (Wife)',
      emergencyPhone: '+91 99533 11223',
      emergencyRelationship: 'Spouse',
      skillBadges: ['Italian Marble Master', 'Diamond Level Finish', 'SOP Compliant'],
      currentSiteAssigned: 'PRJ-105 - Golf Links Luxury Villa',
      walletBalance: 28400.0,
      onTimePercentage: 99.0,
      qualityScore: 5.0,
      behaviourScore: 4.9,
      reliabilityScore: 4.9,
      activeJobsCount: 1,
      disputeCount: 0,
      strikesCount: 0,
      onboardingDate: DateTime(2023, 6, 20),
      lastActivity: 'Submitted daily log: PRJ-105 (1h ago)',
    ),
    LabourProfile(
      id: 'LBR-104',
      legalName: 'Rajesh Kumar Verma',
      alias: 'Rajesh Electrician',
      displayName: 'Rajesh V.',
      phone: '+91 98114 56789',
      altPhone: '+91 98114 56780',
      email: 'rajesh.verma@homiofield.in',
      gender: 'Male',
      trade: TradeType.electrical,
      secondarySkills: ['Home Automation Relays', 'Magnetic Track Lights', 'DB Dressing'],
      experienceYears: 8,
      rating: 4.68,
      totalReviews: 39,
      completedJobs: 54,
      punctualityScore: 94.2,
      dailyRate: 1000.0,
      sqftRate: 25.0,
      overtimeHourlyRate: 190.0,
      city: 'Gurugram',
      zone: 'Sector 56 & Golf Course Ext',
      address: 'Flat 302, Ghata Gaon, Sector 56',
      state: 'Haryana',
      pincode: '122011',
      operatingAreas: ['Sector 56', 'Sector 57', 'Golf Course Ext'],
      preferredRadiusKm: 12.0,
      distanceKm: 3.2,
      kycStatus: KycStatus.approved,
      labourStatus: LabourStatus.booked,
      extendedStatus: ExtendedLabourStatus.active,
      skillLevel: SkillLevel.skilled,
      rateUnit: RateUnit.perDay,
      aadhaarMasked: 'XXXX-XXXX-6632',
      policeVerificationNo: 'PCC-HR-GGN-2024-7731',
      photoUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150',
      emergencyContact: 'Santosh Verma (Father)',
      emergencyPhone: '+91 98114 99001',
      emergencyRelationship: 'Father',
      skillBadges: ['Automation Certified', 'Clean DB Wiring Award'],
      currentSiteAssigned: 'PRJ-104 (Starts Tomorrow)',
      walletBalance: 6700.0,
      onTimePercentage: 94.0,
      qualityScore: 4.7,
      behaviourScore: 4.6,
      reliabilityScore: 4.7,
      activeJobsCount: 1,
      disputeCount: 0,
      strikesCount: 0,
      onboardingDate: DateTime(2023, 11, 10),
      lastActivity: 'Accepted dispatch request BK-905',
    ),
    LabourProfile(
      id: 'LBR-105',
      legalName: 'Jagdish Chandra Roy',
      alias: 'Roy Painter',
      displayName: 'Jagdish Roy',
      phone: '+91 97175 67890',
      altPhone: '',
      email: 'jagdish.roy@homiofield.in',
      gender: 'Male',
      trade: TradeType.painting,
      secondarySkills: ['Italian PU Polish', 'Venetian Stucco', 'Airless Spray Painting'],
      experienceYears: 14,
      rating: 4.82,
      totalReviews: 53,
      completedJobs: 78,
      punctualityScore: 97.0,
      dailyRate: 1050.0,
      sqftRate: 35.0,
      overtimeHourlyRate: 200.0,
      city: 'Mumbai',
      zone: 'Bandra West & Khar',
      address: 'Room 12, Gazdar Bandh, Santacruz West',
      state: 'Maharashtra',
      pincode: '400054',
      operatingAreas: ['Bandra', 'Khar', 'Juhu', 'Santacruz'],
      preferredRadiusKm: 15.0,
      distanceKm: 5.5,
      kycStatus: KycStatus.approved,
      labourStatus: LabourStatus.onSite,
      extendedStatus: ExtendedLabourStatus.onJob,
      skillLevel: SkillLevel.expert,
      rateUnit: RateUnit.perSqft,
      aadhaarMasked: 'XXXX-XXXX-3341',
      policeVerificationNo: 'PCC-MH-MUM-2024-5542',
      photoUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150',
      emergencyContact: 'Rekha Roy (Wife)',
      emergencyPhone: '+91 97175 11998',
      emergencyRelationship: 'Spouse',
      skillBadges: ['Asian Paints Royale Gold', 'PU Mirror Finish Master'],
      currentSiteAssigned: 'PRJ-106 - Bandra Sea-Facing Penthouse',
      walletBalance: 19200.0,
      onTimePercentage: 97.0,
      qualityScore: 4.9,
      behaviourScore: 4.8,
      reliabilityScore: 4.8,
      activeJobsCount: 1,
      disputeCount: 0,
      strikesCount: 0,
      onboardingDate: DateTime(2023, 7, 18),
      lastActivity: 'Checked In on site (1h ago)',
    ),
    LabourProfile(
      id: 'LBR-106',
      legalName: 'Suresh Babu Naidu',
      alias: 'Suresh POP Works',
      displayName: 'Suresh N.',
      phone: '+91 98451 78901',
      altPhone: '',
      email: 'suresh.naidu@homiofield.in',
      gender: 'Male',
      trade: TradeType.popFalseCeiling,
      secondarySkills: ['Cove Lighting Boxing', 'Acoustic Wall Paneling', 'Grid Ceiling'],
      experienceYears: 11,
      rating: 4.79,
      totalReviews: 44,
      completedJobs: 69,
      punctualityScore: 95.5,
      dailyRate: 1100.0,
      sqftRate: 50.0,
      overtimeHourlyRate: 210.0,
      city: 'Bangalore',
      zone: 'Whitefield & ITPL',
      address: 'No 45, Immadihalli Main Road, Whitefield',
      state: 'Karnataka',
      pincode: '560066',
      operatingAreas: ['Whitefield', 'Marathahalli', 'Kagdaspura', 'Indiranagar'],
      preferredRadiusKm: 20.0,
      distanceKm: 8.2,
      kycStatus: KycStatus.approved,
      labourStatus: LabourStatus.available,
      extendedStatus: ExtendedLabourStatus.active,
      skillLevel: SkillLevel.skilled,
      rateUnit: RateUnit.perSqft,
      aadhaarMasked: 'XXXX-XXXX-1198',
      policeVerificationNo: 'PCC-KA-BLR-2024-3321',
      photoUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150',
      emergencyContact: 'Lakshmi Naidu (Wife)',
      emergencyPhone: '+91 98451 22334',
      emergencyRelationship: 'Spouse',
      skillBadges: ['Gyproc Certified', 'Zero Sagging Guarantee'],
      currentSiteAssigned: '',
      walletBalance: 11800.0,
      onTimePercentage: 96.0,
      qualityScore: 4.8,
      behaviourScore: 4.8,
      reliabilityScore: 4.8,
      activeJobsCount: 0,
      disputeCount: 0,
      strikesCount: 0,
      onboardingDate: DateTime(2023, 9, 12),
      lastActivity: 'Completed Job BK-904 (Yesterday)',
    ),
    LabourProfile(
      id: 'LBR-107',
      legalName: 'Amit Ranjan Das',
      alias: 'Amit Carpenter',
      displayName: 'Amit Das',
      phone: '+91 98112 89012',
      altPhone: '',
      email: 'amit.das@homiofield.in',
      gender: 'Male',
      trade: TradeType.carpentry,
      secondarySkills: ['CNC Jali Cutting Installation', 'Solid Wood Carving'],
      experienceYears: 6,
      rating: 4.45,
      totalReviews: 21,
      completedJobs: 28,
      punctualityScore: 91.0,
      dailyRate: 900.0,
      sqftRate: 100.0,
      overtimeHourlyRate: 160.0,
      city: 'Gurugram',
      zone: 'Palam Vihar',
      address: 'Block C, Palam Vihar Ext',
      state: 'Haryana',
      pincode: '122017',
      operatingAreas: ['Palam Vihar', 'Old Gurugram', 'Dwarka Expressway'],
      preferredRadiusKm: 15.0,
      distanceKm: 7.0,
      kycStatus: KycStatus.underReview,
      labourStatus: LabourStatus.available,
      extendedStatus: ExtendedLabourStatus.underVerification,
      skillLevel: SkillLevel.intermediate,
      rateUnit: RateUnit.perDay,
      aadhaarMasked: 'XXXX-XXXX-9901',
      policeVerificationNo: 'SUBMITTED-PENDING',
      photoUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150',
      emergencyContact: 'Bina Das (Mother)',
      emergencyPhone: '+91 98112 33441',
      emergencyRelationship: 'Mother',
      skillBadges: ['Fast Assembly Specialist'],
      currentSiteAssigned: '',
      walletBalance: 3400.0,
      onTimePercentage: 91.0,
      qualityScore: 4.4,
      behaviourScore: 4.5,
      reliabilityScore: 4.4,
      activeJobsCount: 0,
      disputeCount: 0,
      strikesCount: 0,
      onboardingDate: DateTime(2024, 2, 1),
      lastActivity: 'Awaiting police document approval',
    ),
    LabourProfile(
      id: 'LBR-108',
      legalName: 'Vikas Chandran',
      alias: 'Vikas Tiler',
      displayName: 'Vikas C.',
      phone: '+91 98450 90123',
      altPhone: '',
      email: 'vikas.chandran@homiofield.in',
      gender: 'Male',
      trade: TradeType.tiling,
      secondarySkills: ['Large Slab Tile Cladding', 'Epoxy Joint Filler'],
      experienceYears: 5,
      rating: 4.30,
      totalReviews: 18,
      completedJobs: 24,
      punctualityScore: 88.0,
      dailyRate: 850.0,
      sqftRate: 38.0,
      overtimeHourlyRate: 150.0,
      city: 'Bangalore',
      zone: 'Koramangala & HSR Layout',
      address: '24th Main, HSR Layout Sector 1',
      state: 'Karnataka',
      pincode: '560102',
      operatingAreas: ['HSR Layout', 'Koramangala', 'BTM Layout'],
      preferredRadiusKm: 10.0,
      distanceKm: 3.8,
      kycStatus: KycStatus.pending,
      labourStatus: LabourStatus.onLeave,
      extendedStatus: ExtendedLabourStatus.temporarilyUnavailable,
      skillLevel: SkillLevel.intermediate,
      rateUnit: RateUnit.perSqft,
      aadhaarMasked: 'XXXX-XXXX-4421',
      policeVerificationNo: 'NOT_SUBMITTED',
      photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
      emergencyContact: 'Deepa Chandran (Sister)',
      emergencyPhone: '+91 98450 66778',
      emergencyRelationship: 'Sister',
      skillBadges: [],
      currentSiteAssigned: '',
      walletBalance: 1200.0,
      onTimePercentage: 88.0,
      qualityScore: 4.3,
      behaviourScore: 4.4,
      reliabilityScore: 4.3,
      activeJobsCount: 0,
      disputeCount: 0,
      strikesCount: 0,
      onboardingDate: DateTime(2024, 3, 10),
      lastActivity: 'Marked on leave till Friday',
    ),
    LabourProfile(
      id: 'LBR-109',
      legalName: 'Kallu Ram Saini',
      alias: 'Kallu Mistry (Defaulted)',
      displayName: 'Kallu R. Saini',
      phone: '+91 99110 33445',
      altPhone: '',
      email: 'kallu.saini@homiofield.in',
      gender: 'Male',
      trade: TradeType.masonry,
      secondarySkills: ['Civil Brickwork'],
      experienceYears: 7,
      rating: 2.10,
      totalReviews: 12,
      completedJobs: 14,
      punctualityScore: 45.0,
      dailyRate: 850.0,
      sqftRate: 40.0,
      overtimeHourlyRate: 150.0,
      city: 'Gurugram',
      zone: 'Old Gurgaon',
      address: 'Gali 2, Surat Nagar, Old Railway Road',
      state: 'Haryana',
      pincode: '122006',
      operatingAreas: ['Old Gurgaon'],
      preferredRadiusKm: 12.0,
      distanceKm: 12.0,
      kycStatus: KycStatus.rejected,
      labourStatus: LabourStatus.blacklisted,
      extendedStatus: ExtendedLabourStatus.blacklisted,
      skillLevel: SkillLevel.beginner,
      rateUnit: RateUnit.perDay,
      aadhaarMasked: 'XXXX-XXXX-9912',
      policeVerificationNo: 'FLAGGED-ABSCONDING',
      photoUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150',
      emergencyContact: 'Ramvati (Sister)',
      emergencyPhone: '+91 99110 00112',
      emergencyRelationship: 'Sister',
      skillBadges: [],
      currentSiteAssigned: '',
      walletBalance: 0.0,
      onTimePercentage: 45.0,
      qualityScore: 2.0,
      behaviourScore: 2.1,
      reliabilityScore: 1.8,
      activeJobsCount: 0,
      disputeCount: 2,
      strikesCount: 3,
      onboardingDate: DateTime(2023, 11, 15),
      lastActivity: 'Locked permanently by Admin',
    ),
  ];

  static List<LabourKycDocument> kycDocuments = [
    LabourKycDocument(
      id: 'KYC-DOC-301',
      workerId: 'LBR-101',
      workerName: 'Ramprasad Sharma',
      aadhaarNumber: 'XXXX-XXXX-4892',
      aadhaarDocUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=400',
      selfiePhotoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200',
      policeClearanceUrl: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=400',
      policeStationName: 'DLF Phase 1 PS, Gurugram',
      bankAccountNo: '50100492819201',
      ifscCode: 'HDFC0000280',
      accountHolderName: 'RAMPRASAD SHARMA',
      upiId: 'ramprasadsharma@okhdfcbank',
      tradeTestScore: 94.5,
      tradeGrade: 'Grade A+ Master Craftsman',
      riskLevel: 'LOW (Clear Background)',
      verificationNotes: 'Biometric face match 99.2%. Aadhaar QR decoded successfully. No criminal records found in CCTNS sync.',
      submissionDate: DateTime(2024, 1, 15),
      verifiedAt: DateTime(2024, 1, 16),
      verifiedByAdmin: 'Karan Mehra (Compliance Lead)',
      status: KycStatus.approved,
      auditTrail: [
        KycAuditEntry(
          id: 'AUD-01',
          action: 'Document Submission',
          actor: 'Ramprasad Sharma',
          timestamp: DateTime(2024, 1, 15, 10, 30),
          previousStatus: 'Not Submitted',
          newStatus: 'Submitted',
          notes: 'Uploaded Aadhaar, Police Clearance and Bank Passbook photo.',
        ),
        KycAuditEntry(
          id: 'AUD-02',
          action: 'OCR & CCTNS Verification',
          actor: 'Karan Mehra (Compliance)',
          timestamp: DateTime(2024, 1, 16, 14, 15),
          previousStatus: 'Submitted',
          newStatus: 'Approved',
          notes: 'Verified against state police database and bank penny drop test successful.',
        ),
      ],
    ),
    LabourKycDocument(
      id: 'KYC-DOC-302',
      workerId: 'LBR-102',
      workerName: 'Mohammad Shakeel',
      aadhaarNumber: 'XXXX-XXXX-7123',
      aadhaarDocUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=400',
      selfiePhotoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200',
      policeClearanceUrl: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=400',
      policeStationName: 'Sushant Lok PS, Gurugram',
      bankAccountNo: '20391002938192',
      ifscCode: 'SBIN0001829',
      accountHolderName: 'MOHAMMAD SHAKEEL',
      upiId: 'shakeel.plumb@oksbi',
      tradeTestScore: 89.0,
      tradeGrade: 'Grade A Certified Plumber',
      riskLevel: 'LOW',
      verificationNotes: 'Hydro-static plumbing trade test passed with distinction. Police verification letter certified.',
      submissionDate: DateTime(2024, 2, 10),
      verifiedAt: DateTime(2024, 2, 11),
      verifiedByAdmin: 'Karan Mehra (Compliance Lead)',
      status: KycStatus.approved,
    ),
    LabourKycDocument(
      id: 'KYC-DOC-307',
      workerId: 'LBR-107',
      workerName: 'Amit Ranjan Das',
      aadhaarNumber: 'XXXX-XXXX-9901',
      aadhaarDocUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=400',
      selfiePhotoUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200',
      policeClearanceUrl: '',
      policeStationName: 'Palam Vihar PS, Gurugram',
      bankAccountNo: '918283746192',
      ifscCode: 'PUNB0029381',
      accountHolderName: 'AMIT RANJAN DAS',
      upiId: 'amit.das@okpnb',
      tradeTestScore: 78.0,
      tradeGrade: 'Grade B Tradesman',
      riskLevel: 'MEDIUM (Police Clearance Pending)',
      verificationNotes: 'Selfie and Aadhaar OCR match. Police verification receipt submitted; awaiting final clearance certificate.',
      submissionDate: DateTime(2024, 5, 2),
      verifiedAt: null,
      verifiedByAdmin: 'Pending Assignment',
      status: KycStatus.underReview,
      correctionRequiredAction: 'Upload official police verification certificate with barcode',
    ),
    LabourKycDocument(
      id: 'KYC-DOC-309',
      workerId: 'LBR-109',
      workerName: 'Kallu Ram Saini',
      aadhaarNumber: 'XXXX-XXXX-9912',
      aadhaarDocUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=400',
      selfiePhotoUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=200',
      policeClearanceUrl: '',
      policeStationName: 'Sector 5 PS, Gurugram',
      bankAccountNo: '302918274615',
      ifscCode: 'BARB0GURGAO',
      accountHolderName: 'KALLU RAM',
      upiId: 'kalluram@okbob',
      tradeTestScore: 41.0,
      tradeGrade: 'FAIL / UNVERIFIED',
      riskLevel: 'HIGH / BLACKLISTED',
      verificationNotes: 'Absconded from PRJ-102 site with ₹28,000 unreturned advance. Multiple quality breaches. Blacklisted permanently.',
      submissionDate: DateTime(2023, 11, 20),
      verifiedAt: DateTime(2023, 11, 22),
      verifiedByAdmin: 'Sunil Nair (Principal Architect)',
      status: KycStatus.rejected,
      rejectionReason: 'Absconded with advance payment and severe safety negligence.',
    ),
  ];

  static Map<String, List<WeeklyDaySchedule>> weeklySchedules = {
    'LBR-101': const [
      WeeklyDaySchedule(dayName: 'Monday', isAvailable: true),
      WeeklyDaySchedule(dayName: 'Tuesday', isAvailable: true),
      WeeklyDaySchedule(dayName: 'Wednesday', isAvailable: true),
      WeeklyDaySchedule(dayName: 'Thursday', isAvailable: true),
      WeeklyDaySchedule(dayName: 'Friday', isAvailable: true),
      WeeklyDaySchedule(dayName: 'Saturday', isAvailable: true),
      WeeklyDaySchedule(dayName: 'Sunday', isAvailable: false),
    ],
    'LBR-102': const [
      WeeklyDaySchedule(dayName: 'Monday', isAvailable: true),
      WeeklyDaySchedule(dayName: 'Tuesday', isAvailable: true),
      WeeklyDaySchedule(dayName: 'Wednesday', isAvailable: true),
      WeeklyDaySchedule(dayName: 'Thursday', isAvailable: true),
      WeeklyDaySchedule(dayName: 'Friday', isAvailable: true),
      WeeklyDaySchedule(dayName: 'Saturday', isAvailable: true),
      WeeklyDaySchedule(dayName: 'Sunday', isAvailable: true, startTime: '10:00 AM', endTime: '02:00 PM', isFullDay: false),
    ],
  };

  static List<ServiceBooking> activeBookings = [
    ServiceBooking(
      id: 'BK-901',
      bookingNumber: 'HOM-SB-2024-001',
      projectId: 'PRJ-104',
      projectName: 'PRJ-104 - 4BHK DLF Phase 5',
      clientId: 'CLI-801',
      clientName: 'Vikram Malhotra',
      clientPhone: '+91 98180 11223',
      supervisorId: 'SUP-401',
      supervisorName: 'Amit Joshi (Site Supervisor)',
      tradesmanId: 'LBR-101',
      tradesmanName: 'Ramprasad Sharma',
      tradesmanPhone: '+91 98101 23456',
      trade: TradeType.carpentry,
      skillLevel: SkillLevel.expert,
      workTitle: 'Master Bedroom Wardrobe Assembly & Hardware Fitting',
      scopeDescription: 'Master Bedroom Wardrobe carcass assembly, soft-close Hettich drawer channel installation, and edge-banding.',
      expectedOutput: 'Clean, gapless finish with 90° carcass alignment and flawless soft-close operation.',
      siteInstructions: 'Site has running AC. Wear safety helmet and dust masks while cutting MDF/Plywood.',
      qualityRequirements: 'Right-angle deviation < 1mm; no visible screw heads on front panels.',
      materialResponsibility: 'Homio supplies 18mm BWR Century Ply; Contractor brings professional power tools & clamps.',
      tradesmenCount: 2,
      dealValue: 38500.0,
      advancePaid: 15000.0,
      balanceDue: 23500.0,
      platformCommission: 3850.0,
      status: BookingStatus.inProgress,
      activeJobStatus: ActiveJobStatus.workStarted,
      progressPercent: 72.0,
      startDate: DateTime(2024, 5, 2),
      endDate: DateTime(2024, 5, 10),
      siteLocation: 'DLF Phase 5, Tower 4, Flat 1402, Gurugram',
      gpsCheckInStamp: '08:45 AM (Geo-fenced: 28.4595° N, 77.0266° E)',
      checkInRecord: JobCheckInRecord(
        id: 'CHK-REC-101',
        jobId: 'BK-901',
        workerId: 'LBR-101',
        workerName: 'Ramprasad Sharma',
        checkInTime: DateTime(2024, 5, 2, 8, 45),
        latitude: 28.4595,
        longitude: 77.0266,
        address: 'DLF Phase 5, Tower 4, Gurugram',
        selfiePhotoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200',
        deviceInfo: 'Samsung Galaxy M34 (Geo-verified)',
      ),
      dailyUpdates: [
        DailyWorkUpdate(
          id: 'UPD-01',
          jobId: 'BK-901',
          workDate: DateTime(2024, 5, 2),
          hoursWorked: 8.5,
          workCompleted: 'Carcass cutting, vertical upright positioning, edge banding completed.',
          workRemaining: 'Shelving assembly and Hettich channel installation.',
          progressPercentage: 45.0,
          blockers: 'None. Site power available.',
          photoUrls: ['https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=500'],
          submittedBy: 'Ramprasad Sharma',
          submittedAt: DateTime(2024, 5, 2, 18, 30),
        ),
        DailyWorkUpdate(
          id: 'UPD-02',
          jobId: 'BK-901',
          workDate: DateTime(2024, 5, 3),
          hoursWorked: 8.0,
          workCompleted: '3 Drawer boxes fitted with soft-close Quadro channels. Alignment verified.',
          workRemaining: 'Hanging rod fixing, top profile and final cleaning.',
          progressPercentage: 72.0,
          blockers: 'None.',
          photoUrls: ['https://images.unsplash.com/photo-1581094288338-2314dddb7ece?w=500'],
          submittedBy: 'Ramprasad Sharma',
          submittedAt: DateTime(2024, 5, 3, 18, 15),
        ),
      ],
      dailyChecklist: [
        const DailyChecklistItem(id: 'CHK-1', title: 'Plywood thickness (18mm BWR) verified', isCompleted: true, notes: 'Century Club Prime used'),
        const DailyChecklistItem(id: 'CHK-2', title: 'Laser plumb line & right angle 90° carcass leveling', isCompleted: true, notes: 'Within 1mm tolerance'),
        const DailyChecklistItem(id: 'CHK-3', title: 'Adhesive curing & edging tape pressure clamped', isCompleted: true, notes: 'Fevicol Marine adhesive'),
        const DailyChecklistItem(id: 'CHK-4', title: 'Soft-close hinges & telescopic channel fitment', isCompleted: true, notes: 'Quadro 4D tested'),
        const DailyChecklistItem(id: 'CHK-5', title: 'Site debris vacuumed & safety inspection sign-off', isCompleted: false, notes: 'Scheduled for completion day'),
      ],
      sitePhotos: [
        'https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=500',
        'https://images.unsplash.com/photo-1581094288338-2314dddb7ece?w=500',
      ],
      supervisorSignOffName: 'Amit Joshi',
      isDelayed: false,
      delayDays: 0,
    ),
    ServiceBooking(
      id: 'BK-902',
      bookingNumber: 'HOM-SB-2024-002',
      projectId: 'PRJ-105',
      projectName: 'PRJ-105 - Golf Links Luxury Villa',
      clientId: 'CLI-802',
      clientName: 'Sanjay Singhania',
      clientPhone: '+91 98111 22334',
      supervisorId: 'SUP-402',
      supervisorName: 'Rohit Verma (Site Supervisor)',
      tradesmanId: 'LBR-103',
      tradesmanName: 'Dharmendra Kumar Yadav',
      tradesmanPhone: '+91 99533 45678',
      trade: TradeType.masonry,
      skillLevel: SkillLevel.specialist,
      workTitle: 'Living Room Italian Statuario Marble Laying & Pattern Matching',
      scopeDescription: 'Living Room Italian Statuario marble dry-lay pattern matching and diamond grinding preparation.',
      expectedOutput: 'Seamless book-matched veins across 420 sqft living floor; zero hollow sound underneath.',
      siteInstructions: 'Strictly use Laticrete 335 polymer adhesive slurry; no sand-cement mix permitted.',
      qualityRequirements: 'Leveling tolerance < 0.5mm; 100% adhesive buttering on back of each slab.',
      materialResponsibility: 'Homio provides Italian marble and adhesives; Contractor provides heavy cutting machines and diamond blades.',
      tradesmenCount: 3,
      dealValue: 64000.0,
      advancePaid: 30000.0,
      balanceDue: 34000.0,
      platformCommission: 6400.0,
      status: BookingStatus.checklistSigned,
      activeJobStatus: ActiveJobStatus.awaitingVerification,
      progressPercent: 95.0,
      startDate: DateTime(2024, 4, 28),
      endDate: DateTime(2024, 5, 8),
      siteLocation: 'Golf Links, Bungalow 42, New Delhi',
      gpsCheckInStamp: '08:30 AM (Geo-fenced: 28.5983° N, 77.2345° E)',
      dailyChecklist: [
        const DailyChecklistItem(id: 'CHK-11', title: 'Sub-floor screed level & moisture test (<3%)', isCompleted: true, notes: 'Passed screed test'),
        const DailyChecklistItem(id: 'CHK-12', title: 'Marble vein book-matching signed by Client', isCompleted: true, notes: 'Client approved sample batch'),
        const DailyChecklistItem(id: 'CHK-13', title: 'Laticrete 335 polymer adhesive slurry application', isCompleted: true, notes: 'Full bed coverage verified'),
        const DailyChecklistItem(id: 'CHK-14', title: 'Tile leveler clips & 2mm spacer uniformity', isCompleted: true, notes: 'Verified by Supervisor Rohit'),
      ],
      sitePhotos: [
        'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=500',
        'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=500',
      ],
      supervisorSignOffName: 'Rohit Verma',
      isDelayed: false,
      delayDays: 0,
      workVerification: WorkVerificationRecord(
        id: 'VER-01',
        jobId: 'BK-902',
        supervisorName: 'Rohit Verma',
        status: 'Approved',
        assessmentNotes: 'Excellent vein matching and zero hollow sound tested across entire hall.',
        verifiedAt: DateTime(2024, 5, 8, 17, 30),
        qualityScore: 5.0,
      ),
    ),
    ServiceBooking(
      id: 'BK-903',
      bookingNumber: 'HOM-SB-2024-003',
      projectId: 'PRJ-106',
      projectName: 'PRJ-106 - Bandra Sea-Facing Penthouse',
      clientId: 'CLI-803',
      clientName: 'Pooja Hegde',
      clientPhone: '+91 98200 44556',
      supervisorId: 'SUP-403',
      supervisorName: 'Pradeep Patil (Site Supervisor)',
      tradesmanId: 'LBR-105',
      tradesmanName: 'Jagdish Chandra Roy',
      tradesmanPhone: '+91 97175 67890',
      trade: TradeType.painting,
      skillLevel: SkillLevel.expert,
      workTitle: 'Venetian Stucco Finish & PU Matt Polish on Fluted Paneling',
      scopeDescription: 'Living Room Venetian Stucco finish & PU Matt Polish on fluted acoustic wall panel.',
      expectedOutput: 'Mirror-like smooth surface with subtle marbleized depth and matte clear coat protection.',
      siteInstructions: 'Cover all Italian flooring with protective corrugated plastic rolls before commencing.',
      qualityRequirements: 'Dust-free environment during spraying; no orange peel texture.',
      materialResponsibility: 'Asian Paints Royale Aspira and Renner PU supplies provided by Homio.',
      tradesmenCount: 2,
      dealValue: 42000.0,
      advancePaid: 20000.0,
      balanceDue: 22000.0,
      platformCommission: 4200.0,
      status: BookingStatus.inProgress,
      activeJobStatus: ActiveJobStatus.delayed,
      progressPercent: 50.0,
      startDate: DateTime(2024, 5, 1),
      endDate: DateTime(2024, 5, 7),
      siteLocation: 'Carter Road, Bandra West, Mumbai',
      gpsCheckInStamp: '09:00 AM (Geo-fenced: 19.0607° N, 72.8258° E)',
      dailyChecklist: [
        const DailyChecklistItem(id: 'CHK-21', title: 'Surface sanding (180 to 320 grit) & dust extraction', isCompleted: true, notes: 'Clean surface prepped'),
        const DailyChecklistItem(id: 'CHK-22', title: 'Epoxy putty double-coat filling and hairline snag sealing', isCompleted: true, notes: 'Zero indentation'),
        const DailyChecklistItem(id: 'CHK-23', title: 'First coat Asian Paints Royale PU Matt spray application', isCompleted: false, notes: 'Delayed due to high sea humidity'),
      ],
      sitePhotos: [
        'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=500',
      ],
      supervisorSignOffName: 'Pradeep Patil',
      isDelayed: true,
      delayDays: 2,
      delayReason: 'Excessive humidity (>85%) on sea-facing balcony delayed PU spray curing. Dehumidifiers deployed.',
    ),
    ServiceBooking(
      id: 'BK-904',
      bookingNumber: 'HOM-SB-2024-004',
      projectId: 'PRJ-107',
      projectName: 'PRJ-107 - Whitefield Tech Executive Villa',
      clientId: 'CLI-804',
      clientName: 'Rohan Deshmukh',
      clientPhone: '+91 98450 77889',
      supervisorId: 'SUP-404',
      supervisorName: 'Kiran Gowda (Site Supervisor)',
      tradesmanId: 'LBR-106',
      tradesmanName: 'Suresh Babu Naidu',
      tradesmanPhone: '+91 98451 78901',
      trade: TradeType.popFalseCeiling,
      skillLevel: SkillLevel.skilled,
      workTitle: 'Double-tier Perimeter Cove False Ceiling',
      scopeDescription: 'Double-tier perimeter cove false ceiling with Saint-Gobain 12.5mm Gyproc sheets.',
      expectedOutput: 'Seamless joints, crisp 90-degree cove edges, and reinforced fan/chandelier hooks.',
      siteInstructions: 'Coordinate height clearance with central AC ducting team.',
      qualityRequirements: 'Max deflection < 2mm; fiberglass tape on all joints.',
      materialResponsibility: 'Saint-Gobain Gyproc channels & boards supplied.',
      tradesmenCount: 2,
      dealValue: 29000.0,
      advancePaid: 10000.0,
      balanceDue: 19000.0,
      platformCommission: 2900.0,
      status: BookingStatus.completed,
      activeJobStatus: ActiveJobStatus.settled,
      progressPercent: 100.0,
      startDate: DateTime(2024, 4, 15),
      endDate: DateTime(2024, 4, 22),
      siteLocation: 'EPIP Zone, Whitefield, Bangalore',
      gpsCheckInStamp: '08:50 AM (Geo-fenced: 12.9716° N, 77.5946° E)',
      dailyChecklist: [
        const DailyChecklistItem(id: 'CHK-31', title: 'GI perimeter channels anchored with rawl plugs at 600mm', isCompleted: true, notes: 'Heavy duty channel'),
        const DailyChecklistItem(id: 'CHK-32', title: 'Cove light recess wiring conduit checked by electrician', isCompleted: true, notes: 'Coordinated with Rajesh'),
        const DailyChecklistItem(id: 'CHK-33', title: 'Gyproc jointing compound + fiber mesh tape 3-coat finish', isCompleted: true, notes: 'Smooth seamless joints'),
      ],
      sitePhotos: [
        'https://images.unsplash.com/photo-1541888946425-d0fbb186156a?w=500',
      ],
      clientRating: 4.9,
      workerRating: 5.0,
      supervisorSignOffName: 'Kiran Gowda',
      isDelayed: false,
      delayDays: 0,
    ),
  ];

  static List<LabourPaymentRecord> paymentRecords = [
    LabourPaymentRecord(
      id: 'PAY-8801',
      bookingId: 'BK-904',
      bookingNumber: 'HOM-SB-2024-004',
      workerId: 'LBR-106',
      workerName: 'Suresh Babu Naidu',
      clientName: 'Rohan Deshmukh',
      projectName: 'PRJ-107 - Whitefield Tech Executive Villa',
      workDescription: 'False ceiling completion settlement (Double-tier cove)',
      billingPeriod: '15 Apr 2024 - 22 Apr 2024',
      grossAmount: 29000.0,
      deductions: 500.0, // Safety gear penalty
      adjustments: 0.0,
      platformCommission: 2900.0,
      netPayable: 25600.0,
      amountPaid: 25600.0,
      amountDue: 0.0,
      paymentDate: DateTime(2024, 4, 24),
      transactionRef: 'IMPS/41142091823/HDFC-BLR',
      status: 'Settled',
      remarks: 'Full settlement after customer rating & supervisor sign-off.',
    ),
    LabourPaymentRecord(
      id: 'PAY-8802',
      bookingId: 'BK-901',
      bookingNumber: 'HOM-SB-2024-001',
      workerId: 'LBR-101',
      workerName: 'Ramprasad Sharma',
      clientName: 'Vikram Malhotra',
      projectName: 'PRJ-104 - 4BHK DLF Phase 5',
      workDescription: 'Advance wage payout for carcass fabrication',
      billingPeriod: '02 May 2024 - 05 May 2024',
      grossAmount: 15000.0,
      deductions: 0.0,
      adjustments: 0.0,
      platformCommission: 1500.0,
      netPayable: 13500.0,
      amountPaid: 13500.0,
      amountDue: 23500.0,
      paymentDate: DateTime(2024, 5, 2),
      transactionRef: 'UPI/4501928374/RAMPRASAD@OKHDFC',
      status: 'Paid',
      remarks: 'Approved milestone 1 advance wage transfer.',
    ),
    LabourPaymentRecord(
      id: 'PAY-8803',
      bookingId: 'BK-902',
      bookingNumber: 'HOM-SB-2024-002',
      workerId: 'LBR-103',
      workerName: 'Dharmendra Kumar Yadav',
      clientName: 'Sanjay Singhania',
      projectName: 'PRJ-105 - Golf Links Luxury Villa',
      workDescription: 'Final payment claim for Italian Statuario laying',
      billingPeriod: '28 Apr 2024 - 08 May 2024',
      grossAmount: 34000.0,
      deductions: 0.0,
      adjustments: 2000.0, // Bonus for zero wastage
      platformCommission: 3400.0,
      netPayable: 32600.0,
      amountPaid: 0.0,
      amountDue: 32600.0,
      paymentDate: DateTime(2024, 5, 9),
      transactionRef: 'NEFT-QUEUED-REF-9941',
      status: 'Pending Approval',
      remarks: 'Verified by Supervisor Rohit Verma. Awaiting finance sign-off.',
    ),
  ];

  static List<PaymentClaim> paymentClaims = [
    PaymentClaim(
      id: 'CLM-501',
      bookingId: 'BK-902',
      bookingNumber: 'HOM-SB-2024-002',
      workerId: 'LBR-103',
      workerName: 'Dharmendra Kumar Yadav',
      workSummary: 'Finished 420 sqft Italian Statuario dry-lay & polymer bonding. 4 supervisor inspections completed.',
      billingPeriod: 'Week 2 (May 1 - May 8)',
      amountClaimed: 34000.0,
      status: 'Under Review',
      submittedDate: DateTime(2024, 5, 8, 18, 0),
      supervisorConfirmation: 'Verified by Rohit Verma (Score 5/5)',
    ),
    PaymentClaim(
      id: 'CLM-502',
      bookingId: 'BK-904',
      bookingNumber: 'HOM-SB-2024-004',
      workerId: 'LBR-106',
      workerName: 'Suresh Babu Naidu',
      workSummary: 'Cove ceiling 100% completed & lighting conduits handed over to electrical contractor.',
      billingPeriod: 'Final Settlement',
      amountClaimed: 19000.0,
      status: 'Approved',
      submittedDate: DateTime(2024, 4, 23, 11, 30),
      supervisorConfirmation: 'Approved by Kiran Gowda',
    ),
  ];

  static List<LabourRatingRecord> ratingsList = [
    LabourRatingRecord(
      id: 'RTG-201',
      bookingId: 'BK-904',
      bookingNumber: 'HOM-SB-2024-004',
      workerId: 'LBR-106',
      workerName: 'Suresh Babu Naidu',
      trade: TradeType.popFalseCeiling,
      reviewerName: 'Rohan Deshmukh (Homeowner)',
      reviewerRole: 'Customer',
      qualityScore: 5.0,
      timelineScore: 4.8,
      behaviourScore: 5.0,
      reliabilityScore: 5.0,
      overallScore: 4.95,
      reviewNotes: 'Suresh and his team worked very cleanly. The perimeter cove line is pin-straight and zero dust left on site. Highly recommend!',
      date: DateTime(2024, 4, 23),
    ),
    LabourRatingRecord(
      id: 'RTG-202',
      bookingId: 'BK-904',
      bookingNumber: 'HOM-SB-2024-004',
      workerId: 'LBR-106',
      workerName: 'Suresh Babu Naidu',
      trade: TradeType.popFalseCeiling,
      reviewerName: 'Kiran Gowda (Site Supervisor)',
      reviewerRole: 'Site Supervisor',
      qualityScore: 4.8,
      timelineScore: 4.9,
      behaviourScore: 4.8,
      reliabilityScore: 4.9,
      overallScore: 4.85,
      reviewNotes: 'Strong adherence to Gyproc SOP. Coordinated well with electrician Rajesh for cove wiring.',
      date: DateTime(2024, 4, 22),
    ),
    LabourRatingRecord(
      id: 'RTG-203',
      bookingId: 'BK-890',
      bookingNumber: 'HOM-SB-2024-019',
      workerId: 'LBR-101',
      workerName: 'Ramprasad Sharma',
      trade: TradeType.carpentry,
      reviewerName: 'Priya Narang (Architect)',
      reviewerRole: 'Service Manager',
      qualityScore: 5.0,
      timelineScore: 5.0,
      behaviourScore: 4.9,
      reliabilityScore: 5.0,
      overallScore: 4.98,
      reviewNotes: 'Master level veneer joints. Handles complex imported German hardware with extreme precision.',
      date: DateTime(2024, 4, 18),
    ),
    LabourRatingRecord(
      id: 'RTG-204',
      bookingId: 'BK-892',
      bookingNumber: 'HOM-SB-2024-022',
      workerId: 'LBR-109',
      workerName: 'Kallu Ram Saini',
      trade: TradeType.masonry,
      reviewerName: 'Karan Mehra (Site Manager)',
      reviewerRole: 'Site Supervisor',
      qualityScore: 2.0,
      timelineScore: 1.0,
      behaviourScore: 2.0,
      reliabilityScore: 1.5,
      overallScore: 1.62,
      reviewNotes: 'Unpunctual, absconded from site with cash advance, leaving demolition debris blocking emergency exit.',
      date: DateTime(2023, 11, 21),
      isAlertTriggered: true,
    ),
  ];

  static List<DisputeCase> disputeCases = [
    DisputeCase(
      id: 'DSP-701',
      caseNumber: 'LEGAL-DISP-2024-019',
      bookingId: 'BK-890',
      projectId: 'PRJ-101',
      projectName: 'PRJ-101 - Sushant Lok Luxury Floors',
      initiator: 'Ramprasad Sharma (Carpenter)',
      respondent: 'Gaurav Khandelwal (Client / Defaulting Owner)',
      disputeType: DisputeScenario.clientNonPayment,
      amountInDispute: 58000.0,
      dateFiled: DateTime(2024, 4, 10),
      assignedLawyerName: 'Adv. Rajeshwar Swaroop (Supreme Court & Delhi High Court)',
      lawyerBarCouncilNo: 'D/1492/2004',
      courtJurisdiction: 'Labour Court No. 2, Pataudi Road, Gurugram',
      legalStatus: DisputeLegalStatus.labourCourtFiled,
      evidenceDossierUrl: 'https://docs.homiocrm.com/dossier/PRJ-101-LBR-DISPUTE-019.pdf',
      strikesCount: 3,
      replacementDispatched: false,
      resolutionSummary: 'Client refused to pay final verified carpenter dues of ₹58,000 despite 4 signed supervisor checklists. Formal statutory Section 138 notice expired. Recovery case filed in Gurugram Labour Court under Payment of Wages Act.',
      auditTrail: [
        '2024-04-10: Worker filed wage default claim after 7-day grace period expired.',
        '2024-04-11: Homio auto-compiled Certified Digital Dossier (GPS check-ins, signed checklists, WhatsApp logs).',
        '2024-04-12: Client credit rating downgraded from 4.6★ to 1.1★. Account flagged for Blacklisting.',
        '2024-04-14: Statutory 15-day Legal Notice drafted & served by Empanelled Adv. Rajeshwar Swaroop.',
        '2024-04-30: Notice period lapsed without payment. Case registered at Labour Court Gurugram (CNR: HRGR010041282024).',
      ],
      isClientBlacklisted: true,
      isLabourBlacklisted: false,
      nextHearingDate: '28 Sep 2026',
      statutoryNoticeRef: 'NOT/2026/LEG/8812',
    ),
    DisputeCase(
      id: 'DSP-702',
      caseNumber: 'LEGAL-DISP-2024-022',
      bookingId: 'BK-892',
      projectId: 'PRJ-102',
      projectName: 'PRJ-102 - DLF Magnolia Ultra Penthouse',
      initiator: 'Karan Mehra (Site Manager)',
      respondent: 'Kallu Ram Saini (Mason)',
      disputeType: DisputeScenario.labourAbandonment,
      amountInDispute: 28000.0,
      dateFiled: DateTime(2023, 11, 22),
      assignedLawyerName: 'Adv. Meenakshi Sundaram (Corporate Legal Counsel)',
      lawyerBarCouncilNo: 'D/882/2012',
      courtJurisdiction: 'Homio Internal Arbitration & Police Cyber Cell',
      legalStatus: DisputeLegalStatus.blacklisted,
      evidenceDossierUrl: 'https://docs.homiocrm.com/dossier/PRJ-102-ABANDONMENT-022.pdf',
      strikesCount: 3,
      replacementDispatched: true,
      resolutionSummary: 'Worker Kallu Ram absconded from site after taking ₹28,000 cash advance, leaving 120 sq.ft civil wall demolition unfinished. Emergency backup team deployed within 3 hours. Worker permanently blacklisted across platform network.',
      auditTrail: [
        '2023-11-20: Site Supervisor flagged worker absconding without notice.',
        '2023-11-20 (11:30 AM): Emergency replacement squad (3 verified masons) dispatched to prevent project delay.',
        '2023-11-21: Official Strike #3 and termination notice issued to worker.',
        '2023-11-22: Wallet balance forfeited and Aadhaar locked on national blacklist registry.',
      ],
      isClientBlacklisted: false,
      isLabourBlacklisted: true,
      nextHearingDate: 'Arbitration Closed',
      statutoryNoticeRef: 'NOT/2023/ABN/0091',
    ),
  ];

  static List<PanelLawyer> panelLawyers = [
    const PanelLawyer(
      id: 'LAW-001',
      name: 'Adv. Rajeshwar Swaroop',
      barCouncilNo: 'D/1492/2004',
      specialization: 'Labour Law, Payment of Wages & Construction Arbitration',
      courtJurisdiction: 'Delhi High Court & Gurugram District Courts',
      activeCases: 4,
      phone: '+91 98102 99881',
      email: 'rajeshwar.swaroop@homiolegal.in',
      rating: 4.95,
    ),
    const PanelLawyer(
      id: 'LAW-002',
      name: 'Adv. Meenakshi Sundaram',
      barCouncilNo: 'D/882/2012',
      specialization: 'Corporate Contracts & Real Estate RERA Disputes',
      courtJurisdiction: 'Saket District Courts & NCLT New Delhi',
      activeCases: 2,
      phone: '+91 98111 77889',
      email: 'meenakshi.sundaram@homiolegal.in',
      rating: 4.88,
    ),
    const PanelLawyer(
      id: 'LAW-003',
      name: 'Adv. Alok Ranjan Verma',
      barCouncilNo: 'MAH/3104/2008',
      specialization: 'Contractor Disputes & Industrial Disputes Act',
      courtJurisdiction: 'Bombay High Court & Mumbai City Civil Court',
      activeCases: 3,
      phone: '+91 98200 11223',
      email: 'alok.verma@homiolegal.in',
      rating: 4.82,
    ),
  ];

  static List<BlacklistRecord> blacklistRegistry = [
    BlacklistRecord(
      id: 'BLK-001',
      entityName: 'Gaurav Khandelwal',
      entityType: 'CLIENT',
      reason: 'Repeated non-payment of verified worker wages (₹58,000 default on PRJ-101). Section 138 notice served. Labour Court Case pending.',
      identifier: 'CLI-805 / Phone: +91 98188 00991',
      blacklistedAt: DateTime(2024, 4, 12),
      lockedByAdmin: 'Karan Mehra (Compliance Lead)',
      defaultAmount: 58000.0,
    ),
    BlacklistRecord(
      id: 'BLK-002',
      entityName: 'Kallu Ram Saini (Mason)',
      entityType: 'LABOUR',
      reason: 'Absconded with ₹28,000 cash advance on PRJ-102. Repeated unpunctuality and safety violations.',
      identifier: 'Aadhaar: XXXX-XXXX-9912 / Phone: +91 99110 33445',
      blacklistedAt: DateTime(2023, 11, 22),
      lockedByAdmin: 'Sunil Nair (Principal Architect)',
      defaultAmount: 28000.0,
    ),
  ];
}
