import 'labour_models.dart';

class LabourMockData {
  static List<LabourProfile> profiles = [
    const LabourProfile(
      id: 'LBR-101',
      legalName: 'Ramprasad Sharma',
      alias: 'Ramprasad Mistri',
      phone: '+91 98101 23456',
      trade: TradeType.carpentry,
      secondarySkills: ['Modular Kitchen', 'Veneer Polish', 'Hardware Fitting'],
      experienceYears: 12,
      rating: 4.88,
      totalReviews: 64,
      completedJobs: 82,
      punctualityScore: 98.5,
      dailyRate: 1100.0,
      sqftRate: 125.0,
      overtimeHourlyRate: 200.0,
      city: 'Gurugram',
      zone: 'DLF Phase 1-5 & Golf Course Ext',
      distanceKm: 2.4,
      kycStatus: KycStatus.approved,
      labourStatus: LabourStatus.onSite,
      aadhaarMasked: 'XXXX-XXXX-4892',
      policeVerificationNo: 'PCC-HR-GGN-2024-8841',
      photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
      emergencyContact: 'Sunita Sharma (Wife)',
      emergencyPhone: '+91 98101 99881',
      skillBadges: ['Master Woodworker', 'Hettich Hardware Certified', 'Clean Site Badge'],
      currentSiteAssigned: 'PRJ-104 - 4BHK DLF Phase 5',
      walletBalance: 14500.0,
    ),
    const LabourProfile(
      id: 'LBR-102',
      legalName: 'Mohammad Shakeel',
      alias: 'Shakeel Plumber',
      phone: '+91 98712 34567',
      trade: TradeType.plumbing,
      secondarySkills: ['CPVC Piping', 'Grohe/Kohler Concealed Diverter', 'Pressure Testing'],
      experienceYears: 9,
      rating: 4.75,
      totalReviews: 48,
      completedJobs: 61,
      punctualityScore: 96.0,
      dailyRate: 950.0,
      sqftRate: 45.0,
      overtimeHourlyRate: 180.0,
      city: 'Gurugram',
      zone: 'Sohna Road & South City',
      distanceKm: 4.1,
      kycStatus: KycStatus.approved,
      labourStatus: LabourStatus.available,
      aadhaarMasked: 'XXXX-XXXX-7123',
      policeVerificationNo: 'PCC-HR-GGN-2024-9120',
      photoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
      emergencyContact: 'Parveen Akhtar (Brother)',
      emergencyPhone: '+91 98712 88776',
      skillBadges: ['Kohler Certified', 'Hydro-Static Pressure Expert', 'Zero Leakage Guarantee'],
      currentSiteAssigned: '',
      walletBalance: 8200.0,
    ),
    const LabourProfile(
      id: 'LBR-103',
      legalName: 'Dharmendra Kumar Yadav',
      alias: 'Dharmu Mistri',
      phone: '+91 99533 45678',
      trade: TradeType.masonry,
      secondarySkills: ['Italian Marble Inlay', 'Large Format GVT Tiles', 'Epoxy Grouting'],
      experienceYears: 15,
      rating: 4.92,
      totalReviews: 92,
      completedJobs: 114,
      punctualityScore: 99.0,
      dailyRate: 1200.0,
      sqftRate: 55.0,
      overtimeHourlyRate: 220.0,
      city: 'Delhi NCR',
      zone: 'South Delhi & Golf Links',
      distanceKm: 3.8,
      kycStatus: KycStatus.approved,
      labourStatus: LabourStatus.onSite,
      aadhaarMasked: 'XXXX-XXXX-9341',
      policeVerificationNo: 'PCC-DL-SD-2023-4102',
      photoUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
      emergencyContact: 'Gita Devi (Wife)',
      emergencyPhone: '+91 99533 11223',
      skillBadges: ['Italian Marble Specialist', 'Laser Level Master', '5-Star Punctuality'],
      currentSiteAssigned: 'PRJ-105 - Golf Links Luxury Villa',
      walletBalance: 21800.0,
    ),
    const LabourProfile(
      id: 'LBR-104',
      legalName: 'Rajesh Kumar Verma',
      alias: 'Rajesh Electrician',
      phone: '+91 98114 56789',
      trade: TradeType.electrical,
      secondarySkills: ['Schneider Smart Switches', 'DB Dressing', 'Concealed Conduit'],
      experienceYears: 8,
      rating: 4.65,
      totalReviews: 39,
      completedJobs: 47,
      punctualityScore: 94.2,
      dailyRate: 900.0,
      sqftRate: 35.0,
      overtimeHourlyRate: 160.0,
      city: 'Gurugram',
      zone: 'Sector 48-65',
      distanceKm: 5.6,
      kycStatus: KycStatus.approved,
      labourStatus: LabourStatus.available,
      aadhaarMasked: 'XXXX-XXXX-5521',
      policeVerificationNo: 'PCC-HR-GGN-2024-3312',
      photoUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150',
      emergencyContact: 'Rakesh Verma (Father)',
      emergencyPhone: '+91 98114 99001',
      skillBadges: ['Smart Home Automation', 'Safety Wire Gauge Compliance'],
      currentSiteAssigned: '',
      walletBalance: 6500.0,
    ),
    const LabourProfile(
      id: 'LBR-105',
      legalName: 'Jagdish Chandra Roy',
      alias: 'Jaggu Painter',
      phone: '+91 97175 67890',
      trade: TradeType.painting,
      secondarySkills: ['Asian Paints PU Polish', 'Velvet Touch Texture', 'Stucco Marble Finish'],
      experienceYears: 11,
      rating: 4.80,
      totalReviews: 53,
      completedJobs: 70,
      punctualityScore: 97.4,
      dailyRate: 1000.0,
      sqftRate: 28.0,
      overtimeHourlyRate: 180.0,
      city: 'Mumbai',
      zone: 'Bandra & Khar West',
      distanceKm: 1.8,
      kycStatus: KycStatus.approved,
      labourStatus: LabourStatus.onSite,
      aadhaarMasked: 'XXXX-XXXX-8819',
      policeVerificationNo: 'PCC-MH-MUM-2024-1189',
      photoUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150',
      emergencyContact: 'Manju Roy (Wife)',
      emergencyPhone: '+91 97175 44332',
      skillBadges: ['Italian PU Specialist', 'Airless Spray Certified', 'Zero Dust Masking'],
      currentSiteAssigned: 'PRJ-106 - Bandra Sea-Facing Penthouse',
      walletBalance: 17400.0,
    ),
    const LabourProfile(
      id: 'LBR-106',
      legalName: 'Suresh Babu Naidu',
      alias: 'Suresh POP Master',
      phone: '+91 98451 78901',
      trade: TradeType.popFalseCeiling,
      secondarySkills: ['Gyproc Grid Framing', 'Curved Cove Profile', 'Acoustic Armstrong Tiles'],
      experienceYears: 10,
      rating: 4.70,
      totalReviews: 42,
      completedJobs: 54,
      punctualityScore: 95.0,
      dailyRate: 950.0,
      sqftRate: 40.0,
      overtimeHourlyRate: 170.0,
      city: 'Bangalore',
      zone: 'Whitefield & Outer Ring Road',
      distanceKm: 3.2,
      kycStatus: KycStatus.approved,
      labourStatus: LabourStatus.onSite,
      aadhaarMasked: 'XXXX-XXXX-3344',
      policeVerificationNo: 'PCC-KA-BLR-2024-6621',
      photoUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150',
      emergencyContact: 'Lakshmi Naidu (Sister)',
      emergencyPhone: '+91 98451 00221',
      skillBadges: ['Saint-Gobain Gyproc Certified', 'Cove Lighting Precision'],
      currentSiteAssigned: 'PRJ-107 - Whitefield Tech Executive Villa',
      walletBalance: 9800.0,
    ),
    const LabourProfile(
      id: 'LBR-107',
      legalName: 'Vikram Singh Chauhan',
      alias: 'Vicky Carpenter',
      phone: '+91 98188 90123',
      trade: TradeType.carpentry,
      secondarySkills: ['Aluminium Sliding Wardrobes', 'Wall Panelling', 'Fluted Louvers'],
      experienceYears: 6,
      rating: 4.40,
      totalReviews: 21,
      completedJobs: 26,
      punctualityScore: 91.0,
      dailyRate: 900.0,
      sqftRate: 110.0,
      overtimeHourlyRate: 150.0,
      city: 'Gurugram',
      zone: 'Sector 57 & Golf Course Ext',
      distanceKm: 6.2,
      kycStatus: KycStatus.biometricsVerified,
      labourStatus: LabourStatus.available,
      aadhaarMasked: 'XXXX-XXXX-6672',
      policeVerificationNo: 'PCC-HR-GGN-2024-5021',
      photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
      emergencyContact: 'Balwant Chauhan (Brother)',
      emergencyPhone: '+91 98188 11990',
      skillBadges: ['Fast Track Carpentry'],
      currentSiteAssigned: '',
      walletBalance: 3200.0,
    ),
    const LabourProfile(
      id: 'LBR-108',
      legalName: 'Anil Kumar Paswan',
      alias: 'Anil Painter',
      phone: '+91 96541 23890',
      trade: TradeType.painting,
      secondarySkills: ['Exterior Waterproof Paint', 'Distemper', 'Enamel Paint'],
      experienceYears: 4,
      rating: 4.25,
      totalReviews: 15,
      completedJobs: 18,
      punctualityScore: 88.0,
      dailyRate: 800.0,
      sqftRate: 22.0,
      overtimeHourlyRate: 140.0,
      city: 'Delhi NCR',
      zone: 'Noida Sector 62 & Indirapuram',
      distanceKm: 8.5,
      kycStatus: KycStatus.underReview,
      labourStatus: LabourStatus.available,
      aadhaarMasked: 'XXXX-XXXX-1928',
      policeVerificationNo: 'Pending Verification',
      photoUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150',
      emergencyContact: 'Rekha Paswan (Mother)',
      emergencyPhone: '+91 96541 77665',
      skillBadges: ['Rapid Coating'],
      currentSiteAssigned: '',
      walletBalance: 1200.0,
    ),
    const LabourProfile(
      id: 'LBR-109',
      legalName: 'Kallu Ram Saini',
      alias: 'Kallu Mistry (Defaulted)',
      phone: '+91 99110 33445',
      trade: TradeType.masonry,
      secondarySkills: ['Civil Brickwork'],
      experienceYears: 7,
      rating: 2.10,
      totalReviews: 12,
      completedJobs: 14,
      punctualityScore: 45.0,
      dailyRate: 850.0,
      sqftRate: 40.0,
      overtimeHourlyRate: 150.0,
      city: 'Gurugram',
      zone: 'Old Gurgaon',
      distanceKm: 12.0,
      kycStatus: KycStatus.rejected,
      labourStatus: LabourStatus.blacklisted,
      aadhaarMasked: 'XXXX-XXXX-9912',
      policeVerificationNo: 'FLAGGED-ABSCONDING',
      photoUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150',
      emergencyContact: 'Ramvati (Sister)',
      emergencyPhone: '+91 99110 00112',
      skillBadges: [],
      currentSiteAssigned: '',
      walletBalance: 0.0,
    ),
  ];

  static List<LabourKycDocument> kycDocuments = [
    LabourKycDocument(
      id: 'KYC-DOC-301',
      workerId: 'LBR-101',
      workerName: 'Ramprasad Sharma',
      aadhaarNumber: 'XXXX-XXXX-4892',
      aadhaarDocUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=400',
      selfiePhotoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200',
      policeClearanceUrl: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=400',
      policeStationName: 'DLF Phase 1 PS, Gurugram',
      bankAccountNo: '50100492819201',
      ifscCode: 'HDFC0000280',
      accountHolderName: 'RAMPRASAD SHARMA',
      upiId: 'ramprasadsharma@okhdfcbank',
      tradeTestScore: 94.5,
      tradeGrade: 'Grade A+ Master Craftsman',
      riskLevel: 'LOW (Clear Background)',
      verificationNotes: 'Biometric face match 99.2%. Aadhaar QR decoded successfully. No criminal records found in CCTNS sync.',
      submissionDate: DateTime(2024, 1, 15),
      verifiedAt: DateTime(2024, 1, 16),
      verifiedByAdmin: 'Karan Mehra (HR & Compliance Lead)',
      status: KycStatus.approved,
    ),
    LabourKycDocument(
      id: 'KYC-DOC-302',
      workerId: 'LBR-102',
      workerName: 'Mohammad Shakeel',
      aadhaarNumber: 'XXXX-XXXX-7123',
      aadhaarDocUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=400',
      selfiePhotoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200',
      policeClearanceUrl: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=400',
      policeStationName: 'Sushant Lok PS, Gurugram',
      bankAccountNo: '20391002938192',
      ifscCode: 'SBIN0004123',
      accountHolderName: 'MOHAMMAD SHAKEEL',
      upiId: 'shakeelplumbing@oksbi',
      tradeTestScore: 89.0,
      tradeGrade: 'Grade A Certified Plumber',
      riskLevel: 'LOW (Clear Background)',
      verificationNotes: 'Plumbing skill evaluation test passed with 89%. Kohler plumbing toolset verified.',
      submissionDate: DateTime(2024, 2, 10),
      verifiedAt: DateTime(2024, 2, 11),
      verifiedByAdmin: 'Karan Mehra (HR & Compliance Lead)',
      status: KycStatus.approved,
    ),
    LabourKycDocument(
      id: 'KYC-DOC-307',
      workerId: 'LBR-107',
      workerName: 'Vikram Singh Chauhan',
      aadhaarNumber: 'XXXX-XXXX-6672',
      aadhaarDocUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=400',
      selfiePhotoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200',
      policeClearanceUrl: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=400',
      policeStationName: 'Sector 56 PS, Gurugram',
      bankAccountNo: '91827364501928',
      ifscCode: 'ICIC0001092',
      accountHolderName: 'VIKRAM SINGH CHAUHAN',
      upiId: 'vikramchauhan@okaxis',
      tradeTestScore: 82.0,
      tradeGrade: 'Grade B+ Skilled Worker',
      riskLevel: 'LOW',
      verificationNotes: 'Selfie biometric matched. Police verification certificate validated.',
      submissionDate: DateTime(2024, 4, 18),
      verifiedAt: DateTime(2024, 4, 19),
      verifiedByAdmin: 'Karan Mehra (HR & Compliance Lead)',
      status: KycStatus.biometricsVerified,
    ),
    LabourKycDocument(
      id: 'KYC-DOC-308',
      workerId: 'LBR-108',
      workerName: 'Anil Kumar Paswan',
      aadhaarNumber: 'XXXX-XXXX-1928',
      aadhaarDocUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=400',
      selfiePhotoUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=200',
      policeClearanceUrl: 'Pending Upload',
      policeStationName: 'Noida Sector 58 PS',
      bankAccountNo: '30491827364512',
      ifscCode: 'PUNB0182700',
      accountHolderName: 'ANIL KUMAR PASWAN',
      upiId: 'anilpaswan@paytm',
      tradeTestScore: 74.0,
      tradeGrade: 'Grade B Apprentice Painter',
      riskLevel: 'MEDIUM (Police Clearance Pending)',
      verificationNotes: 'Aadhaar uploaded, live facial selfie captured. Awaiting digital police verification clearance.',
      submissionDate: DateTime(2024, 5, 2),
      verifiedAt: null,
      verifiedByAdmin: 'Karan Mehra (HR & Compliance Lead)',
      status: KycStatus.underReview,
    ),
    LabourKycDocument(
      id: 'KYC-DOC-309',
      workerId: 'LBR-109',
      workerName: 'Kallu Ram Saini',
      aadhaarNumber: 'XXXX-XXXX-9912',
      aadhaarDocUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=400',
      selfiePhotoUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=200',
      policeClearanceUrl: 'REJECTED_DOCUMENT',
      policeStationName: 'Civil Lines PS, Gurugram',
      bankAccountNo: '11928374650192',
      ifscCode: 'BARB0GURGAO',
      accountHolderName: 'KALLU RAM',
      upiId: 'kallumistri@ybl',
      tradeTestScore: 41.0,
      tradeGrade: 'FAIL / UNVERIFIED',
      riskLevel: 'HIGH / BLACKLISTED',
      verificationNotes: 'Absconded from PRJ-102 site with ₹28,000 unreturned advance. Multiple quality breaches. Blacklisted permanently.',
      submissionDate: DateTime(2023, 11, 20),
      verifiedAt: DateTime(2023, 11, 22),
      verifiedByAdmin: 'Sunil Nair (Principal Architect)',
      status: KycStatus.rejected,
    ),
  ];

  static List<ServiceBooking> activeBookings = [
    ServiceBooking(
      id: 'BK-901',
      bookingNumber: 'HOM-SB-2024-001',
      projectId: 'PRJ-104',
      projectName: 'PRJ-104 - 4BHK DLF Phase 5',
      clientId: 'CLI-801',
      clientName: 'Vikram Malhotra',
      supervisorId: 'SUP-401',
      supervisorName: 'Amit Joshi (Site Supervisor)',
      tradesmanId: 'LBR-101',
      tradesmanName: 'Ramprasad Sharma',
      tradesmanPhone: '+91 98101 23456',
      trade: TradeType.carpentry,
      scopeDescription: 'Master Bedroom Wardrobe carcass assembly & soft-close Hettich drawer channel installation.',
      tradesmenCount: 2,
      dealValue: 38500.0,
      advancePaid: 15000.0,
      balanceDue: 23500.0,
      platformCommission: 3850.0, // 10%
      status: BookingStatus.inProgress,
      startDate: DateTime(2024, 5, 2),
      endDate: DateTime(2024, 5, 10),
      siteLocation: 'DLF Phase 5, Tower 4, Flat 1402, Gurugram',
      gpsCheckInStamp: '08:45 AM (Geo-fenced: 28.4595° N, 77.0266° E)',
      dailyChecklist: [
        const DailyChecklistItem(id: 'CHK-1', title: 'Plywood thickness (18mm BWR) verified', isCompleted: true, notes: 'Century Club Prime used'),
        const DailyChecklistItem(id: 'CHK-2', title: 'Laser plumb line & right angle 90° carcass leveling', isCompleted: true, notes: 'Within 1mm tolerance'),
        const DailyChecklistItem(id: 'CHK-3', title: 'Adhesive curing & edging tape pressure clamped', isCompleted: true, notes: 'Fevicol Marine adhesive'),
        const DailyChecklistItem(id: 'CHK-4', title: 'Soft-close hinges & telescopic channel fitment', isCompleted: false, notes: 'In progress today'),
      ],
      sitePhotos: [
        'https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=500',
        'https://images.unsplash.com/photo-1581094288338-2314dddb7ece?w=500',
      ],
      clientRating: null,
      workerRating: null,
      termsAccepted: true,
      autoReassignTimer: '00:00 (Accepted)',
      supervisorSignOffName: 'Amit Joshi',
    ),
    ServiceBooking(
      id: 'BK-902',
      bookingNumber: 'HOM-SB-2024-002',
      projectId: 'PRJ-105',
      projectName: 'PRJ-105 - Golf Links Luxury Villa',
      clientId: 'CLI-802',
      clientName: 'Sanjay Singhania',
      supervisorId: 'SUP-402',
      supervisorName: 'Rohit Verma (Site Supervisor)',
      tradesmanId: 'LBR-103',
      tradesmanName: 'Dharmendra Kumar Yadav',
      tradesmanPhone: '+91 99533 45678',
      trade: TradeType.masonry,
      scopeDescription: 'Living Room Italian Statuario marble dry-lay pattern matching and diamond grinding preparation.',
      tradesmenCount: 3,
      dealValue: 64000.0,
      advancePaid: 30000.0,
      balanceDue: 34000.0,
      platformCommission: 6400.0,
      status: BookingStatus.checklistSigned,
      startDate: DateTime(2024, 4, 28),
      endDate: DateTime(2024, 5, 8),
      siteLocation: 'Golf Links, Bungalow 42, New Delhi',
      gpsCheckInStamp: '08:30 AM (Geo-fenced: 28.5983° N, 77.2345° E)',
      dailyChecklist: [
        const DailyChecklistItem(id: 'CHK-11', title: 'Sub-floor screed level & moisture test (<3%)', isCompleted: true, notes: 'Passed screed test'),
        const DailyChecklistItem(id: 'CHK-12', title: 'Marble vein book-matching signed by Client', isCompleted: true, notes: 'Client approved sample batch'),
        const DailyChecklistItem(id: 'CHK-13', title: 'Laticrete 335 polymer adhesive slurry application', isCompleted: true, notes: 'Full bed coverage verified'),
        const DailyChecklistItem(id: 'CHK-14', title: 'Tile leveler clips & 2mm spacer uniformity', isCompleted: true, notes: 'Verified by Supervisor Rohit'),
      ],
      sitePhotos: [
        'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=500',
        'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=500',
      ],
      clientRating: null,
      workerRating: null,
      termsAccepted: true,
      autoReassignTimer: '00:00 (Accepted)',
      supervisorSignOffName: 'Rohit Verma',
    ),
    ServiceBooking(
      id: 'BK-903',
      bookingNumber: 'HOM-SB-2024-003',
      projectId: 'PRJ-106',
      projectName: 'PRJ-106 - Bandra Sea-Facing Penthouse',
      clientId: 'CLI-803',
      clientName: 'Pooja Hegde',
      supervisorId: 'SUP-403',
      supervisorName: 'Pradeep Patil (Site Supervisor)',
      tradesmanId: 'LBR-105',
      tradesmanName: 'Jagdish Chandra Roy',
      tradesmanPhone: '+91 97175 67890',
      trade: TradeType.painting,
      scopeDescription: 'Living Room Venetian Stucco finish & PU Matt Polish on fluted acoustic wall panel.',
      tradesmenCount: 2,
      dealValue: 42000.0,
      advancePaid: 20000.0,
      balanceDue: 22000.0,
      platformCommission: 4200.0,
      status: BookingStatus.inProgress,
      startDate: DateTime(2024, 5, 1),
      endDate: DateTime(2024, 5, 7),
      siteLocation: 'Carter Road, Bandra West, Mumbai',
      gpsCheckInStamp: '09:00 AM (Geo-fenced: 19.0607° N, 72.8258° E)',
      dailyChecklist: [
        const DailyChecklistItem(id: 'CHK-21', title: 'Surface sanding (180 to 320 grit) & dust extraction', isCompleted: true, notes: 'Clean surface prepped'),
        const DailyChecklistItem(id: 'CHK-22', title: 'Epoxy putty double-coat filling and hairline snag sealing', isCompleted: true, notes: 'Zero indentation'),
        const DailyChecklistItem(id: 'CHK-23', title: 'First coat Asian Paints Royale PU Matt spray application', isCompleted: false, notes: 'Underway'),
      ],
      sitePhotos: [
        'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=500',
      ],
      clientRating: null,
      workerRating: null,
      termsAccepted: true,
      autoReassignTimer: '00:00 (Accepted)',
      supervisorSignOffName: 'Pradeep Patil',
    ),
    ServiceBooking(
      id: 'BK-904',
      bookingNumber: 'HOM-SB-2024-004',
      projectId: 'PRJ-107',
      projectName: 'PRJ-107 - Whitefield Tech Executive Villa',
      clientId: 'CLI-804',
      clientName: 'Rohan Deshmukh',
      supervisorId: 'SUP-404',
      supervisorName: 'Kiran Gowda (Site Supervisor)',
      tradesmanId: 'LBR-106',
      tradesmanName: 'Suresh Babu Naidu',
      tradesmanPhone: '+91 98451 78901',
      trade: TradeType.popFalseCeiling,
      scopeDescription: 'Double-tier perimeter cove false ceiling with Saint-Gobain 12.5mm Gyproc sheets.',
      tradesmenCount: 2,
      dealValue: 29000.0,
      advancePaid: 10000.0,
      balanceDue: 19000.0,
      platformCommission: 2900.0,
      status: BookingStatus.completed,
      startDate: DateTime(2024, 4, 15),
      endDate: DateTime(2024, 4, 22),
      siteLocation: 'EPIP Zone, Whitefield, Bangalore',
      gpsCheckInStamp: '08:50 AM (Geo-fenced: 12.9716° N, 77.5946° E)',
      dailyChecklist: [
        const DailyChecklistItem(id: 'CHK-31', title: 'GI perimeter channels anchored with rawl plugs at 600mm', isCompleted: true, notes: 'Heavy duty channel'),
        const DailyChecklistItem(id: 'CHK-32', title: 'Cove light recess wiring conduit checked by electrician', isCompleted: true, notes: 'Coordinated with Rajesh'),
        const DailyChecklistItem(id: 'CHK-33', title: 'Gyproc jointing compound + fiber mesh tape 3-coat finish', isCompleted: true, notes: 'Smooth seamless joints'),
      ],
      sitePhotos: [
        'https://images.unsplash.com/photo-1541888946425-d0fbb186156a?w=500',
      ],
      clientRating: 4.9,
      workerRating: 5.0,
      termsAccepted: true,
      autoReassignTimer: '00:00 (Accepted)',
      supervisorSignOffName: 'Kiran Gowda',
    ),
    ServiceBooking(
      id: 'BK-905',
      bookingNumber: 'HOM-SB-2024-005',
      projectId: 'PRJ-104',
      projectName: 'PRJ-104 - 4BHK DLF Phase 5',
      clientId: 'CLI-801',
      clientName: 'Vikram Malhotra',
      supervisorId: 'SUP-401',
      supervisorName: 'Amit Joshi (Site Supervisor)',
      tradesmanId: 'LBR-104',
      tradesmanName: 'Rajesh Kumar Verma',
      tradesmanPhone: '+91 98114 56789',
      trade: TradeType.electrical,
      scopeDescription: 'Schneider smart automation relays and magnetic track lighting channel installation.',
      tradesmenCount: 1,
      dealValue: 18500.0,
      advancePaid: 5000.0,
      balanceDue: 13500.0,
      platformCommission: 1850.0,
      status: BookingStatus.accepted,
      startDate: DateTime(2024, 5, 8),
      endDate: DateTime(2024, 5, 12),
      siteLocation: 'DLF Phase 5, Tower 4, Flat 1402, Gurugram',
      gpsCheckInStamp: 'Scheduled for Tomorrow 08:30 AM',
      dailyChecklist: [
        const DailyChecklistItem(id: 'CHK-41', title: 'Earthing loop impedance test (< 1 Ohm)', isCompleted: false),
        const DailyChecklistItem(id: 'CHK-42', title: 'Smart home relay modules pairing with gateway', isCompleted: false),
      ],
      sitePhotos: [],
      clientRating: null,
      workerRating: null,
      termsAccepted: true,
      autoReassignTimer: '00:00 (Accepted)',
      supervisorSignOffName: '',
    ),
  ];

  static List<DisputeCase> disputeCases = [
    DisputeCase(
      id: 'DSP-701',
      caseNumber: 'LEGAL-DISP-2024-019',
      bookingId: 'BK-890',
      projectId: 'PRJ-101',
      projectName: 'PRJ-101 - Sushant Lok Luxury Floors',
      initiator: 'Ramprasad Sharma (Carpenter)',
      respondent: 'Gaurav Khandelwal (Client / Defaulting Owner)',
      disputeType: DisputeScenario.clientNonPayment,
      amountInDispute: 58000.0,
      dateFiled: DateTime(2024, 4, 10),
      assignedLawyerName: 'Adv. Rajeshwar Swaroop (Supreme Court & Delhi High Court)',
      lawyerBarCouncilNo: 'D/1492/2004',
      courtJurisdiction: 'Labour Court No. 2, Pataudi Road, Gurugram',
      legalStatus: DisputeLegalStatus.labourCourtFiled,
      evidenceDossierUrl: 'https://docs.homiocrm.com/dossier/PRJ-101-LBR-DISPUTE-019.pdf',
      strikesCount: 3,
      replacementDispatched: false,
      resolutionSummary: 'Client refused to pay final verified carpenter dues of ₹58,000 despite 4 signed supervisor checklists. Formal statutory Section 138 notice expired. Recovery case filed in Gurugram Labour Court under Payment of Wages Act.',
      auditTrail: [
        '2024-04-10: Worker filed wage default claim after 7-day grace period expired.',
        '2024-04-11: Homio auto-compiled Certified Digital Dossier (GPS check-ins, signed checklists, WhatsApp logs).',
        '2024-04-12: Client credit rating downgraded from 4.6★ to 1.1★. Account flagged for Blacklisting.',
        '2024-04-14: Statutory 15-day Legal Notice drafted & served by Empanelled Adv. Rajeshwar Swaroop.',
        '2024-04-30: Notice period lapsed without payment. Case registered at Labour Court Gurugram (CNR: HRGR010041282024).',
      ],
      isClientBlacklisted: true,
      isLabourBlacklisted: false,
    ),
    DisputeCase(
      id: 'DSP-702',
      caseNumber: 'LEGAL-DISP-2024-022',
      bookingId: 'BK-892',
      projectId: 'PRJ-102',
      projectName: 'PRJ-102 - DLF Magnolia Ultra Penthouse',
      initiator: 'Karan Mehra (Site Manager)',
      respondent: 'Kallu Ram Saini (Mason)',
      disputeType: DisputeScenario.labourAbandonment,
      amountInDispute: 28000.0,
      dateFiled: DateTime(2023, 11, 22),
      assignedLawyerName: 'Adv. Meenakshi Sundaram (Corporate Legal Counsel)',
      lawyerBarCouncilNo: 'D/882/2012',
      courtJurisdiction: 'Homio Internal Arbitration & Police Cyber Cell',
      legalStatus: DisputeLegalStatus.blacklisted,
      evidenceDossierUrl: 'https://docs.homiocrm.com/dossier/PRJ-102-ABANDONMENT-022.pdf',
      strikesCount: 3,
      replacementDispatched: true,
      resolutionSummary: 'Worker Kallu Ram absconded from site after taking ₹28,000 cash advance, leaving 120 sq.ft civil wall demolition unfinished. Emergency backup team deployed within 3 hours. Worker permanently blacklisted across platform network.',
      auditTrail: [
        '2023-11-20: Site Supervisor flagged worker absconding without notice.',
        '2023-11-20 (11:30 AM): Emergency replacement squad (3 verified masons) dispatched to prevent project delay.',
        '2023-11-21: Official Strike #3 and termination notice issued to worker.',
        '2023-11-22: Wallet balance forfeited and Aadhaar locked on national blacklist registry.',
      ],
      isClientBlacklisted: false,
      isLabourBlacklisted: true,
    ),
    DisputeCase(
      id: 'DSP-703',
      caseNumber: 'LEGAL-DISP-2024-025',
      bookingId: 'BK-895',
      projectId: 'PRJ-103',
      projectName: 'PRJ-103 - Vasant Vihar Heritage Residence',
      initiator: 'Ananya Roy (Project Manager)',
      respondent: 'Venkatesh Polish Works (Sub-Contractor)',
      disputeType: DisputeScenario.qualityBreach,
      amountInDispute: 35000.0,
      dateFiled: DateTime(2024, 4, 25),
      assignedLawyerName: 'Adv. Rajeshwar Swaroop',
      lawyerBarCouncilNo: 'D/1492/2004',
      courtJurisdiction: 'Delhi Mediation Centre, Saket Courts',
      legalStatus: DisputeLegalStatus.internalReview,
      evidenceDossierUrl: 'https://docs.homiocrm.com/dossier/PRJ-103-QUALITY-025.pdf',
      strikesCount: 1,
      replacementDispatched: false,
      resolutionSummary: 'Substandard PU polish applied with visible orange peel texture and uneven gloss on dining table veneer. Dispute held in internal mediation for free rework or ₹35,000 material refund.',
      auditTrail: [
        '2024-04-25: Quality Inspector recorded 8 photographic snags with gloss level mismatch.',
        '2024-04-26: Internal mediation meeting scheduled between Sub-contractor and Client.',
      ],
      isClientBlacklisted: false,
      isLabourBlacklisted: false,
    ),
  ];

  static List<PanelLawyer> panelLawyers = [
    const PanelLawyer(
      id: 'LAW-001',
      name: 'Adv. Rajeshwar Swaroop',
      barCouncilNo: 'D/1492/2004',
      specialization: 'Construction Contracts, Labour Court & Section 138 NI Act',
      courtJurisdiction: 'Delhi High Court, Gurugram District Courts, State Labour Commission',
      activeCases: 6,
      phone: '+91 98100 44556',
      email: 'rajeshwar.swaroop@homiolegal.in',
      rating: 4.95,
    ),
    const PanelLawyer(
      id: 'LAW-002',
      name: 'Adv. Meenakshi Sundaram',
      barCouncilNo: 'D/882/2012',
      specialization: 'Commercial Arbitration, RERA & Corporate Compliance',
      courtJurisdiction: 'Saket District Court, NCLT Delhi, RERA Haryana',
      activeCases: 4,
      phone: '+91 98111 77889',
      email: 'meenakshi.sundaram@homiolegal.in',
      rating: 4.88,
    ),
    const PanelLawyer(
      id: 'LAW-003',
      name: 'Adv. Alok Ranjan Verma',
      barCouncilNo: 'MAH/3104/2008',
      specialization: 'Contractor Disputes & Industrial Disputes Act',
      courtJurisdiction: 'Bombay High Court & Mumbai City Civil Court',
      activeCases: 3,
      phone: '+91 98200 11223',
      email: 'alok.verma@homiolegal.in',
      rating: 4.82,
    ),
  ];

  static List<BlacklistRecord> blacklistRegistry = [
    BlacklistRecord(
      id: 'BLK-001',
      entityName: 'Gaurav Khandelwal',
      entityType: 'CLIENT',
      reason: 'Repeated non-payment of verified worker wages (₹58,000 default on PRJ-101). Section 138 notice served. Labour Court Case pending.',
      identifier: 'CLI-805 / Phone: +91 98188 00991',
      blacklistedAt: DateTime(2024, 4, 12),
      lockedByAdmin: 'Karan Mehra (Compliance Lead)',
      defaultAmount: 58000.0,
    ),
    BlacklistRecord(
      id: 'BLK-002',
      entityName: 'Kallu Ram Saini (Mason)',
      entityType: 'LABOUR',
      reason: 'Absconded with ₹28,000 cash advance on PRJ-102. Repeated unpunctuality and safety violations.',
      identifier: 'Aadhaar: XXXX-XXXX-9912 / Phone: +91 99110 33445',
      blacklistedAt: DateTime(2023, 11, 22),
      lockedByAdmin: 'Sunil Nair (Principal Architect)',
      defaultAmount: 28000.0,
    ),
    BlacklistRecord(
      id: 'BLK-003',
      entityName: 'Shree Balaji Marble Polishing (Sub-contractor)',
      entityType: 'LABOUR',
      reason: 'Forged police verification clearance and severe material damage (chipped Italian Statuario slab worth ₹1.2 Lakh).',
      identifier: 'GSTIN: 07AABCS1293K1Z5 / Phone: +91 98711 66554',
      blacklistedAt: DateTime(2024, 2, 14),
      lockedByAdmin: 'Karan Mehra (Compliance Lead)',
      defaultAmount: 120000.0,
    ),
  ];
}
